- internal/rangekey/rangekey_test.go
Update formatting in a file that landed after the previous formatting
change.
> rangekey: fix formatting

- compaction.go
- compaction_test.go
- data_test.go
- sstable/writer.go
- testdata/compaction_output_splitters
The `userKeyChangeSplitter` is responsible for avoiding splits within a
user key during flushes. Previously, it worked by recording the current
user key when a split is requested. This introduced a delay in
splitting. When the split is requested, the current key might already be
different than the last key written to the sstable. This change alters
the `userKeyChangeSplitter` to read the last written point key from the
current sstable writer and the last written range key from the range
deletion fragmenter.
This has a couple advantages:
a) It avoids an extra copy of a user key.
b) It may split sooner, closer to the target file size. This is a
practical concern in writing unit tests that involves flushes and
small target file sizes. If we prevent splitting user keys across
outputs in …
> compaction: use sstable writer for detecting user key changes

- internal/keyspan/iter.go
- internal/rangekey/coalescer.go
- internal/rangekey/coalescer_test.go
- internal/rangekey/iter.go
- internal/rangekey/testdata/coalescer
- internal/rangekey/testdata/iter
internal/rangekey: add Coalescer, CoalescedSpan
Add a Coalescer type that may 'coalesce' overlapping range key fragments into a
single CoalescedSpan. A CoalescedSpan represents the aggregate of all the
information from the individual range keys coalesced. A CoalesecedSpan is always
internally consistent, meaning that all necessary shadowing of keys is applied.
Coalescer is expected to be used in compactions, coalescing any overlapping
range key fragments from compaction inputs, and emitting CoalescedSpans that may
be used to construct the range keys persisted to outputs. It is also expected to
be used during iteration, for coalescing snapshot-separated overlapping range
keys and for respecting unsets and deletes across levels. Additional interface
changes may be necessary to support all …
> internal/rangekey: add Coalescer, CoalescedSpan, Iter

- compaction.go
- sstable/testdata/rewriter
- sstable/testdata/writer
- sstable/writer.go
- sstable/writer_test.go
Ahead of an upcoming change that stores the smallest and largest
rangekeys in the metadata of an sstable, update the existing fields for
rangedels to explicitly refer to range _deletions_. This will avoid
confusion and naming collisions with range _keys_.
> sstable: rename {Smallest,Largest}Range to {Smallest,Largest}RangeDel

- internal/base/internal.go
InternalCompare previously suggested that in practice keys will never have
equal user keys and sequence numbers. That's true, except in ingested sstables
with unusual constructions (not in practice in CockroachDB) and now range keys.
> internal/base: adjust InternalCompare comment on key kinds

- internal/keyspan/span.go
The `(keyspan.Span).Empty` function checks whether the key kind is initialized
in order to determine whether a Span is empty. Update the implementation to
consider range key spans as non-empty.
> internal/keyspan: adjust Span.Empty for range keys

- sstable/table.go
The properties block is written after any range deletion block that may
be present in the sstable.
Fix the docs.
Follow-up from #1400.
> sstable: fix properties block location in docs

- sstable/properties.go
- sstable/reader.go
- sstable/testdata/writer
The `sstable.Layout` struct contains information pertaining to the
layout of an sstable. Add the range key block to the layout.
Related to #1339.
> sstable: add range keys to sstable.Layout

- internal/base/internal.go
- internal/rangekey/coalescer.go
- internal/rangekey/coalescer_test.go
- internal/rangekey/interleaving_iter.go
- internal/rangekey/interleaving_iter_test.go
- internal/rangekey/testdata/interleaving_iter
Add an InterleavingIter implementation of the InternalIterator interface that
wraps another InternalIterator and a `*rangekey.Iter`, interleaving the two.
An `InterleavingIter` steps through both a point iterator and a range key
iterator in tandem. At any point, a caller may query its `HasRangeKey()`,
`RangeKeyBounds()` and `RangeKeys()` methods to retrieve information about the
range keys covering the current iterator position, if any.  Additionally, when
an interleaving iterator passes over the inclusive start boundary of a range
key, it returns a key with the special InternalKey trailer
`InternalKeyBoundaryRangeKey`. This key (with the RangeKeySet key-kind and an
infinite sequence number) indicates the beginning of a range key.
Eventually, the `*pebble.Iterator` will use an …
> internal/rangekey: add InterleavingIter

- internal/metamorphic/config.go
- internal/metamorphic/generator.go
- internal/metamorphic/generator_test.go
- internal/metamorphic/key_manager.go
- internal/metamorphic/key_manager_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/options.go
- internal/metamorphic/parser_test.go
- internal/testkeys/testkeys.go
- internal/testkeys/testkeys_test.go
Generate keys with human-readable suffixes like '`@3`'. The key manager is
extended to track unique in-use prefixes as well. A fixed portion of new keys
are generated using an existing prefix but a new suffix.
New keys' suffixes are generated using a skewed-latest distribution, mimicking
MVCC timestamps
> internal/metamorphic: generate keys with suffixes

- tool/lsm.go
Include a description of the LSM tool such that calling the command with
`--help` will describe how the tool is intended to be used.
The description is a paraphrasing of the original commit message
(fd38155d).
> tool: add brief description of LSM tool to usage output

- sstable/block_property_test.go
- sstable/testdata/block_properties
Add a data-driven test to demonstrate the creation of a sstable with one
or more interval collectors. The test prints out the table- and
block-level properties, as written to the index block of the sstable.
> sstable: add data-driven test for block property collectors

- internal/rangekey/coalescer.go
- internal/rangekey/coalescer_test.go
- internal/rangekey/interleaving_iter_test.go
- internal/rangekey/iter.go
- internal/rangekey/testdata/coalescer
Allow the rangekey.Coalescer type to be configured with a visible sequence
number. If a span is added to the coalescer that must not be visible to reads
at the configured sequence number, then the coalescer drops the span.
> internal/rangekey: configure Coalescer to drop spans not visible

- sstable/block_property_test.go
- sstable/testdata/block_properties
A `DataBlockIntervalCollector` implementation should return an exclusive
upper bound from calls to `FinishDataBlock`.
Update the `valueCharBlockIntervalCollector` test implementation to
maintain an exclusive upper bound.
Update data-driven test print intervals of the form `[from, to)` (i.e.
exclusive upper bound).
Closes #1423.
> sstable: use exclusive upper bounds in valueCharBlockIntervalCollector

- internal/rangekey/rangekey.go
- internal/rangekey/rangekey_test.go
Add a helper function that returns true if the given key kind is a range
key kind, and false otherwise. This will help reduce the boilerplate of
checking for the presence of one of the three kinds.
> internal/rangekey: add IsRangeKey helper

- vfs/mem_fs.go
- vfs/mem_fs_test.go
- vfs/vfs_test.go
Before this change, a call to Open for "/" would result in `pebble/vfs: empty
file name` because the root directory has no name. This prevented use of
vfs.Clone on MemFS at the root of the FS.
> vfs: allow MemFS to be Open()'d at "/" or ""

- internal/keyspan/fragmenter.go
- internal/keyspan/fragmenter_test.go
- internal/keyspan/testdata/fragmenter_emit_order
Previously, emitted fragmented spans were guaranteed to be ordered by start key
sequence number, descending. Among keys with the same sequence number, the
ordering was undefined. This was fine for range deletions, for which there only
exist a single key kind. However, for range keys, there are three unique key kinds.
> internal/keyspan: emit fragmented spans ordered by (seqnum, kind)

- batch.go
- batch_test.go
- testdata/flushable_batch
Like range tombstones, range keys are handled separately from point keys.
During flushes and compactions, they will appear in a separate iterator. This
change prevents range keys from appearing in a flushable batch's point
iterator.
> batch: exclude range keys from primary flushable batch iterator

- data_test.go
- db.go
- internal/keyspan/doc.go
- internal/rangekey/iter.go
- iterator.go
- mem_table.go
- open.go
- options.go
- range_keys.go
- range_keys_test.go
- testdata/rangekeys
This change adds experimental, in-memory support for range keys. If a database
is configured with the `Experimental.RangeKeys` field set, batches containing
range keys may be committed. The range keys are applied to a fixed-size
in-memory arena. The `pebble.Iterator` type is extended to surface these range
keys when an iterator's `IterOptions.KeyTypes` option is set to
`IterKeyTypeRangesOnly` or `IterKeyTypePointsAndRanges`.
With this change, range keys are non-durable. When a database is closed, all
committed range keys are lost.
> db: add experimental, in-memory range keys implementation

- internal/rangekey/coalescer.go
- internal/rangekey/coalescer_test.go
- internal/rangekey/interleaving_iter.go
- internal/rangekey/interleaving_iter_test.go
- internal/rangekey/testdata/interleaving_iter_masking
Extend the InterleavingIter to also implement naïve range-key masking. When
configured with a range-key masking threshold _t_, and there exists a range key
with suffix _r_ covering a point key with suffix _p_, and
_t_ <= _r_ < _p_
then the point key is elided.
> internal/rangekey: implement range-key masking

- db.go
- internal/rangekey/iter.go
- options.go
- range_keys_test.go
- testdata/rangekeys
Expose a RangeKeyMasking struct on IterOptions for configuring automatic
masking of point keys by range keys. In #1425 naïve range-key masking was
implemented on the internal `rangekey.InterleavingIter` type. This change adds
the necessary public interface to enable range-key masking.
> db: expose range-key masking

- tool/db.go
- tool/logs/compaction.go
- tool/logs/compaction_test.go
- tool/logs/tool.go
Add a tool that summarizes compaction events within fixed fixed windows
of time from a collection of Pebble and Cockroach log files. Each window
summary dispays the count of compactions between pairs of levels,
grouped by compaction type. The average read-amp value for the window is
also printed.
For example, a sample window summary:
```
$ pebble db compactions --long-running-limit 1m ./cockroach*.log
... snip ...
from: 211215 14:20
to: 211215 14:30
______from________to___default______move_____elide____delete_____flush_____total_____bytes______time
WAL        L0         0         0         0         0      1277      1277      17 G     6m48s
L0        L0         2         0         0         0         0         2     401 M        6s
L0        L2       122         1         0         0 …
```
> tool: add compaction log event aggregation tool

- internal/keyspan/iter.go
- internal/keyspan/iter_test.go
- internal/keyspan/testdata/iter
The `keyspan.Iter` implementation previously did not implement `SetBounds`,
because Pebble never needs to set bounds on range deletion iterators. When
range keys are fully integrated, propagating bounds to range-key fragment
iterators (specifically range-key levelIters) will be an important optimization
to avoid needing to load range-key blocks beyond the iterator bounds. The
memtable and batch range keys will occupy levels above the range-key levelIters
in the form of `keyspan.Iter`s. Pushing bounds checks down requires the
memtable and batch range keys `keyspan.Iter`s to enforce bounds checks.
SetBounds will continue to be unused on `keyspan.Iter`s that expose range
deletion tombstones.
> internal/keyspan: implement SetBounds on Iter

- batch.go
- compaction.go
- compaction_test.go
- error_iter.go
- flushable.go
- get_iter.go
- get_iter_test.go
- ingest.go
- internal/keyspan/iter.go
- internal/keyspan/iter_test.go
- internal/keyspan/seek.go
- internal/keyspan/seek_test.go
- internal/rangekey/iter.go
- level_checker.go
- level_checker_test.go
- level_iter.go
- level_iter_test.go
- mem_table.go
- merging_iter.go
- merging_iter_test.go
- sstable/block.go
- sstable/reader.go
- table_cache.go
Introduce a keyspan.FragmentIterator interface that is a superset of the
InternalIterator interface, with additional methods relevant for dealing with
fragmented key spans. This removes the assumption from `keyspan.Seek{GE,LE}`
that a key span's internal value is always the end key.
When iteration over range key blocks is integrated, we may introduce a small
type that wraps a `*blockIter` and implements the `FragmentIterator` interface
and decodes end keys from internal values.
> internal/keyspan: add FragmentIterator interface

- sstable/writer.go
- sstable/writer_test.go
Currently, when finalizing the properties for a table, any error
returned by the `BlockPropertyCollector` is silently ignored.
Return any error returned by the collector.
> sstable: return err from `(BlockPropertyCollector).FinishTable`

- tool/logs/compaction.go
- tool/logs/compaction_test.go
- tool/logs/testdata/compactions
For collections of logs with multiple nodes stores and stores,
compaction summaries should be aggregated across node and store
boundaries to provide more meaningful results. This also avoids errors
when duplicate Job IDs are encountered from different nodes / stores.
Aggregate by node and store ID.
Add a data driven test harness to provide additional coverage using real
log data.
> tool/logs: aggregate compaction logs by node and store ID

- internal/rangekey/rangekey.go
- internal/rangekey/rangekey_test.go
- sstable/data_test.go
- sstable/testdata/writer_range_keys
- sstable/writer.go
- sstable/writer_rangekey_test.go
Users of `sstable.Writer` other than Pebble itself (e.g. Cockroach)
require a means of adding range keys to an sstable that is slightly more
flexible than the existing `AddRangeKey` method in the way in which key
spans can be added to the table.
Specifically, `AddRangeKey` requires that spans be sorted (start / end
key ascending, sequence number and key kind descending), in addition to
fragmented and coalesced (i.e. multiple suffixes within the same span
are coalesced into a single value).
Add the `RangeKey{Set,Unset,Delete}` methods on the `sstable.Writer`
that allow adding spans in order of start key. These methods have no
requirement that the spans be fragmented or coalesced. Instead, the
implementation handles the fragmenting of spans as keys are added. A
`keyspan.Fragmenter` emits …
> sstable: add (*sstable.Writer).RangeKey{Set,Unset,Delete} methods

- compaction.go
- compaction_iter.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- db.go
- ingest.go
- internal/base/internal.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/level_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_test.go
- level_checker.go
- level_iter.go
- merging_iter.go
- range_del_test.go
- table_stats.go
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
- testdata/range_del
- testdata/table_stats
When the largest key in a sstable is a range tombstone, the sstable's largest
boundary is set to the range deletion sentinel with the tombstone's exclusive
end boundary and the maximum sequence number. The range deletion sentinel
serves as a marker, indicating that the file's bounds end immediately before
the first key with the sentinel's user key.
In many places such as growing compactions or determining atomic compaction
units, Pebble considers the sentinel as exclusive and avoids unnecessarily
including files that share the same user key but only as a sentinel's exclusive
end bounary.
The `(*manifest.Version).Overlaps` method did not share this logic and only
considered user keys. This method is used during compaction picking when
finding the initial compaction inputs, for determining …
> internal/manifest: narrow Overlaps to exclude RANGEDEL sentinel keys

- tool/data/lsm.js
- tool/lsm.go
- tool/lsm_data.go
This change introduces 2 new CLI arguments for the lsm tool: `start-edit` and `end-edit`. 
These can be used to visualize only a contiguous range of manifest edits. I have also added an offset in the visualizer to make it explicit what the manifest edit range is.
Resolves https://github.com/cockroachdb/cockroach/issues/74537
Tested with [MANIFEST](https://github.com/cockroachdb/pebble/files/7857097/MANIFEST.sumeer-heuristics.zip)
> tool: constrain lsm visualizer b/w start and end version numbers

- sstable/block_property.go
- sstable/block_property_test.go
Unexport the BlockIntervalFilter implementation of the BlockPropertyFilter,
modifiyng the signature of NewBlockIntervalFilter to return the interface type,
rather than a concrete type.
I think this makes the interface a little more intuitive, since the
BlockIntervalFilter currently provides no additional functionality.
> sstable: unexport BlockIntervalFilter concrete type

- sstable/reader.go
- sstable/reader_test.go
```
name       old time/op    new time/op    delta
Layout-10    86.1µs ± 0%    85.8µs ± 0%   -0.43%  (p=0.000 n=9+10)
name       old alloc/op   new alloc/op   delta
Layout-10    58.9kB ± 0%    58.5kB ± 0%   -0.57%  (p=0.000 n=10+10)
name       old allocs/op  new allocs/op  delta
Layout-10      31.0 ± 0%      10.0 ± 0%  -67.74%  (p=0.000 n=10+10)
```
> sstable: reuse index block iterator in Layout

- sstable/table_test.go
- sstable/writer.go
- sstable/writer_test.go
This pr aims to serve as a first step towards unifying the parallel compression vs
on parallel compression code paths, as suggested in this pr:
#1383 (review).
This pr organizes the buffers in the Writer in a way which makes it easier to reason
about the ownership of buffers/slices.
Future prs will add, a writeQueue, a compressionQueue, a mechanism to schedule parallel
compression based on cpu utilization.
> sstable: reorganize sstable buffers and structs

- level_checker.go
Currently, if the level checker encounters a violation an the iterator
for the last level has been closed, the debug string providing
information on the level and the file is lost.
Save the debug string for potential use after the iterator is closed.
```
// Before
checker failed with error: found InternalKey zzqwavxgrec@12#4092,SINGLEDEL in L0.2: fileNum=000830 and InternalKey zzqwavxgrec@12#4627,DEL in %!s(<nil>)
// After
checker failed with error: found InternalKey zzqwavxgrec@12#4092,SINGLEDEL in L0.2: fileNum=000830 and InternalKey zzqwavxgrec@12#4627,DEL in L6: fileNum=000997
```
Related to #1459.
> db: save level iter debug output before closing

- docs/RFCS/20220112_pebble_sstable_format_versions.md
To safely support both range keys and block property collectors /
filters, which requires updating the SSTable layout, new table format
versions must be introduced.
Add a small RFC that proposes a new Pebble magic number and versioning
scheme and outlines relationship between the SSTable format version and
the existing Pebble format major version.
Informs #1339.
> docs/rfcs: pebble table format versions

- cmd/pebble/main.go
Support using the pebble command with files that used the
internal/testkeys Comparer.
> cmd/pebble: support testkeys comparer

- iterator_test.go
- sstable/block_property.go
- sstable/block_property_test.go
- sstable/testdata/block_properties
- sstable/writer.go
Currently, the `sstable.BlockIntervalCollector` exists as a helper
struct to which an implementation of
`sstable.DataBlockIntervalCollector` is passed. The latter contains the
user-defined logic for converting a key and value in an associated
interval that can be maintained.
The `BlockIntervalCollector` struct handles the logic required to
implement `sstable.BlockPropertyCollector`, encoding the interval as a
property when the data block is completed, and maintaining index-block-
and table-level intervals.
Update `sstable.Writer` to pass through range keys to each block
property collector as they are added to the writer.
As range and point keys can be thought of as existing in separate
keyspaces within the same LSM, range keys only contribute to table level
intervals (unioned with the …
> sstable: add range key support to BlockIntervalCollector

- batch.go
- batch_test.go
- db.go
Refactor the interface for the experimental write API that exposes range keys,
creating an ExperimentalWriter interface with two implementations: one backed
by a `*Batch` and one backed by a `*DB`. This refactor is necessary so that the
metamorphic tests may apply range keys to both `*DB`s and `*Batch`s.
> db: refactor experimental writer API, expose on DB

- sstable/options.go
- sstable/table.go
Once [Table format version RFC][1] is implemented, the `TableFormat`
enum will include at least two more values for two new Pebble-specific
table features.
In anticipation of the change, re-work the existing enum values to
introduce an "unknown" format version (for when the value is unspecified
and assumes the default value), and order the two existing values in
terms of their natural "lineage" (e.g. LevelDB begat RocksDB, which
begat ..., etc.).
In locations where an unspecified `TableFormat` makes its way all the
way down to the sstable, panic. This ensures that a table format version
is selected explicitly.
[1]: https://github.com/cockroachdb/pebble/pull/1450
> sstable: re-work `TableFormat` enum values

- internal/base/internal.go
- internal/manifest/testdata/overlaps
- internal/manifest/version.go
- internal/manifest/version_test.go
When Version.Overlaps is called for L0, the overlap window is
iteratively expanded until stable. In #1432, the Overlaps function was
adjusted to allow specifying that the end bound should be considered
exclusive. However, #1432 failed to update the exclusivity of the end
bound when the range widened. This improperly excluded files with
largest keys that exactly equaled the new widened end bound.
This commit also transforms the TestOverlaps test into a datadriven
test, introducing a few helpers for parsing the DebugString output of a
Version.
Fix #1459.
> internal/manifest: fix Overlaps L0 expansion with exclusive end

- sstable/writer.go
This reverts commit 9791c0f4c0526c9397312bb7a4021415b50513f1, and fixes
the memory usage issue in the original commit it reverts, which was caused by
the fact that the `Metadata` outlived the `Writer`, and since a key in that
metadata was backed by a portion of the Writer's allocation pooling slice,
the entire slice remained in-use. Instead, the field for the metadata is
restored to being allocated individually, so that only it needs to be
kept after the writer finishes.
> sstable: Revert "Revert "sstable: reduce allocations during index flushing""

- error_iter.go
- internal/keyspan/iter.go
- internal/rangekey/bound_iter.go
- internal/rangekey/bound_iter_test.go
- internal/rangekey/iter.go
- internal/rangekey/merging_iter.go
- internal/rangekey/merging_iter_test.go
- internal/rangekey/testdata/fragment_bound_iterator
- internal/rangekey/testdata/merging_iter
- sstable/block.go
Add a rangekey.MergingIter type that implements the keyspan.FragmentIterator
interface, merging and fragmenting keyspan.FragmentIterators across many
levels. MergingIter uses a heap to consider the spans between adjacent, unique
user keys across levels.
In future work, I'd like to explore adapting MergingIter to implement a
different interface (eg, no longer adhere to FragmentIterator) where each
positioning method returns the full set of fragments with those bounds. This
would require the rangekey.Iter type to explicitly depend on MergingIter, but
would eliminate redundant key comparisons in rangekey.Iter.
> internal/rangekey: add merging, fragmenting iterator

- compaction.go
- compaction_iter.go
- compaction_iter_test.go
- compaction_test.go
- open.go
- options.go
Use Equal rather than Compare to compare user keys in the compaction iterator.
The compaction iterator only needs to detect when a user key changes, and does
not need to order the user keys.
The Equal function is a special case comparator for when a caller only needs to
determine if two user keys are equal. It implements `Compare(a, b) == 0`.
The user-provided `Equal` function may possibly be more performant, allowing
for less decoding and direct use of intrinsics. 
CockroachDB uses the default `Equal` implementation: `bytes.Equal`. I didn't
perform benchmarks, but this is expected to be more performant than
CockroachDB's `Compare` function which must split the user key from the MVCC
timestamp.
> compaction: use Equal in compaction iterator

- internal/rangekey/coalescer.go
- internal/rangekey/coalescer_test.go
- internal/rangekey/iter.go
- internal/rangekey/testdata/iter
Previously, if the first fragment with new bounds was not visible at the read
sequence number and was elided by the Coalescer, the range key iterator would
improperly stop coalescing, repeating the previously returned range key.
Discovered while integrating range keys into the metamorphic tests.
> internal/rangekey: fix range key iteration bug

- sstable/write_queue.go
- sstable/writer.go
- sstable/writer_test.go
This pr adds a writeQueue to the sstable writer. The queue is used to
write data blocks to disk. Currently, the queue will run synchronously
with the Writer client goroutine.
A writeTask, along with a dataBlockBuf is passed to the writerQueue. The
Writer Client goroutine will block until the writeQueue finishes writing
the block to disk.
> sstable: add a writeQueue to the sstable writer

- db.go
- metrics.go
- metrics_test.go
- snapshot.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/testdata/db_lsm
Expose two new fields on Metrics, one recording the count of open snapshots and
the other recording the sequence number of the earliest snapshot.
Related to #1204.
> db: expose metrics on count and earliest seqnum of snapshots

- sstable/data_test.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/testdata/rewriter
This adds a function to the sstable package that can replace some suffix
with another suffix from every key in an sstable, assuming enforcing
that the sstable consists of only Sets.
If the replacement is passed a filter policy, rather than build new
filters, the filter blocks from the original sstable are copied over,
but only after checking that it used the same filter policy and the same
splitter, and that that splitter splits the same length that as is being
replaced i.e. that the pre-replacement filter remains valid
post-replacement.
Data blocks are rewritten in parallel. This informs a few choices in how
it does so: rewritten keys are not passed to `addPoint`, but rather are
directly handed to a worker-local blockWriter. Finished blocks are not
immediately flushed to the output or …
>  sstable: add parallelized RewriteKeySuffixes function

- sstable/write_queue.go
- sstable/writer.go
Fixes: cockroachdb/cockroach#75717
> sstable: Make sstable Writer.Close idempotent

- db_test.go
> db: avoid stats flake in TestMemTableReservation

- sstable/compression.go
- sstable/data_test.go
- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
This switches suffix rewriter workers from calling Reader.readBlock to using a
new helper instead, which avoids cache.Cache.Alloc/Free/Set/Release for these
once-read blocks, eliminating a significant source of contention between the
worker goroutines, and significantly improving throughput. Additionally, one
extra copy is removed by casting the underlying 'file' wrapper around the in-mem
SST byte slice, to just slice the block out of it directly instead of reading it
using ReaderAt into another buffer, and a single decompression buffer is reused
across all blocks instead of allocating a new one each time, again because we
know these are read only once so there is no need to allocate a new one for some
cache.
```
name …
```
> sstable: add direct block reading to suffix rewriter

- batch.go
- internal/batchskl/skl.go
- internal/batchskl/skl_test.go
Currently, the raw data for a skiplist node is stored in a byte slice,
which is indexed into with a `uint32`. In situations where a large
number of nodes are added to the skiplist (on the order of 100 M), the
addition of a node can result in integer overflow which results in a
runtime panic.
Rather than panic, check that the addition of a new node would not
result in an overflow. In the situation where an overflow would occur,
return an error to the caller.
Propagate potential errors for the skip list to external callers. Prior
to this, it was assumed that the addition of a node would never return
an error and the top level methods would panic. Exposing the error
allows external callers to make a determination at runtime as to how the
overflow should be handled.
The altered implementation …
> internal/batchskl: return error on index overflow

- batch.go
- internal/batchskl/skl.go
- internal/batchskl/skl_test.go
This is a backport of #1486 to 21.1.
---
Currently, the raw data for a skiplist node is stored in a byte slice,
which is indexed into with a `uint32`. In situations where a large
number of nodes are added to the skiplist (on the order of 100 M), the
addition of a node can result in integer overflow which results in a
runtime panic.
Rather than panic, check that the addition of a new node would not
result in an overflow. In the situation where an overflow would occur,
return an error to the caller.
Propagate potential errors for the skip list to external callers. Prior
to this, it was assumed that the addition of a node would never return
an error and the top level methods would panic. Exposing the error
allows external callers to make a determination at runtime as to how the
overflow …
> release-21.1: internal/batchskl: return error on index overflow

- batch.go
- internal/batchskl/skl.go
- internal/batchskl/skl_test.go
This is a backport of #1486 to 21.2.
---
Currently, the raw data for a skiplist node is stored in a byte slice,
which is indexed into with a `uint32`. In situations where a large
number of nodes are added to the skiplist (on the order of 100 M), the
addition of a node can result in integer overflow which results in a
runtime panic.
Rather than panic, check that the addition of a new node would not
result in an overflow. In the situation where an overflow would occur,
return an error to the caller.
Propagate potential errors for the skip list to external callers. Prior
to this, it was assumed that the addition of a node would never return
an error and the top level methods would panic. Exposing the error
allows external callers to make a determination at runtime as to how the
overflow …
> release-21.2: internal/batchskl: return error on index overflow

- compaction.go
- format_major_version.go
- format_major_version_test.go
- internal/metamorphic/ops.go
- options.go
- sstable/block_property_test.go
- sstable/data_test.go
- sstable/format.go
- sstable/format_test.go
- sstable/options.go
- sstable/table.go
- sstable/table_test.go
- sstable/writer.go
- sstable/writer_rangekey_test.go
- sstable/writer_test.go
The [Pebble SSTable Format Versions RFC][1] outlines a new versioning
scheme used for new SSTable-level features. The RFC also outlines a
requirement that external callers (i.e. Cockroach) ensure that the
format version is compatible with other stores in a cluster.
To ensure tables are created with an explicit version, the
`(*pebble.Options).NewWriterOptions` method now takes an additional
parameter that specifies the format version to be used when writing a
table. Previous the table format was pinned at RocksDBv2.
Expose a `(FormatMajorVersion).MaxTableFormat()` method that returns the
maximum allowable table format for the given `FormatMajorVersion`. This
can be used to ensure that given a store major version, an
`sstable.Writer` is capped at writing tables with a maximum table
format, …
> *: infer `sstable.TableFormat` from `FormatMajorVerison`

- batch.go
- batch_test.go
- db.go
- flushable.go
- mem_table.go
- range_keys.go
- range_keys_test.go
- testdata/batch_range_ops
- testdata/flushable_batch
- testdata/rangekeys
Support reading range keys through an indexed batch. This commit integrates the
new rangekey merging iterator, allowing merging of range keys from a batch and
the global in-memory arena.
> db: integrate range keys into indexed batches

- sstable/block_property.go
- sstable/block_property_test.go
- sstable/options.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/writer_test.go
This adds a new optional interface that property collectors can implement
which allows them to support their collected properties being _updated_
during SST key-suffix replacement, with the following description:
```
// SuffixReplaceableBlockCollector is an extension to the BlockPropertyCollector
// interface that allows a block property collector to indicate that it supports
// being *updated* during suffix replacement, i.e. when an existing SST in which
// all keys have the same key suffix is updated to have a new suffix.
//
// A collector which supports being updated in such cases must be able to derive
// its updated value from its old value and the change being made to the suffix,
// without needing to be passed each updated K/V.
//
// For example, a collector that only inspects …
```
> sstable: extend property collector API for suffix rewrites

- sstable/suffix_rewriter.go
This patch adds a `defer Writer.Close()` to close the writer on error,
preventing a goroutine leak.
> sstable: close `Writer` on `RewriteKeySuffixes` error

- compaction_picker.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/testdata/l0_sublevels
- internal/manifest/version.go
- internal/manifest/version_edit.go
NewL0Sublevels is an expensive method to call, and it's called every time
there's a change to L0. This commit adds a faster, incremental generation
method for cases when there are only additions to L0 and no deletions from
it. This lets us reuse most of the slices in NewL0Sublevels and merge new
fileIntervals into it instead of starting from scratch.
Improvement in load times for `MANIFEST_import`:
```
name                             old time/op  new time/op  delta
ManifestApplyWithL0Sublevels-12   27.1s ± 4%    4.0s ± 9%  -85.05%  (p=0.000 n=10+10)
```
Fixes #1406.
> internal/manifest: incrementally generate L0Sublevels for L0 additions

- internal/rangekey/interleaving_iter.go
- internal/rangekey/testdata/interleaving_iter
Previously, if an interleaving iterator was iterating in the backward direction
and exhausted its range key iterator, it would never Next its range key
iterator, effectively forgetting all range keys until the next absolute
positioning method.
> internal/rangekey: fix interleaving iteration bug

- sstable/block.go
- sstable/writer.go
When parallelism is enabled, index blocks are only updated from the writeQueue goroutine.
However, the index block size needs to be accessed from the Writer client goroutine. The
index block size is accessed to determine the EstimatedSize of the sstable, and to also
determine if the index block needs to be flushed. We need to determine whether to flush index
blocks in the Writer client goroutine, to support block property collectors.
> sstable: estimate indexBlock.estimatedSize()

- commit.go
- db.go
- iterator_test.go
- options.go
This is only supported for Iterators created on the DB, and
excludes data in the memtable. This will be used for
https://github.com/cockroachdb/cockroach/issues/36262
which is a prerequisite for separating the state machine
into a different DB.
Note that RocksDB supports such behavior using a ReadTier
setting equal to kPersistedTier, which this PR does not adopt
because it was considered too flexible (and has limitations
like not supporting iterators). See
https://github.com/facebook/rocksdb/blob/f6d7ec1d02de1fa84eff61b7ac5a3c663bd63cd7/include/rocksdb/options.h#L1394-L1408
https://github.com/facebook/rocksdb/blob/f6d7ec1d02de1fa84eff61b7ac5a3c663bd63cd7/include/rocksdb/options.h#L1467-L1471
Additionally, if the exclusion of memtables is an implementation
decision, as outlined in the …
> db: add OnlyReadGuaranteedDurable to IterOptions

- compaction.go
- db.go
- iterator_test.go
This will be used in CockroachDB's loosely coupled raft log
truncation (see
https://github.com/cockroachdb/cockroach/blob/c5d146b536aaf70f0b91aa38f88d62b967ac8411/pkg/kv/kvserver/raft_log_queue.go#L959-L967
in a WIP PR).
This is done via a registration function instead of adding
to the Options passed to Open since it simplifies integration
in CockroachDB -- kvserver.NewStore is given an already open
DB.
This interface is subject to change, hence it is marked
experimental with a warning regarding usage.
> db: add experimental DB.RegisterFlushCompletedCallback

- internal/cache/clockpro.go
- internal/cache/clockpro_normal.go
- internal/cache/clockpro_tracing.go
Currently, when Pebble is built and run with the `invariants` build
flag, debug stack traces are collected in a slice of strings for every
invocation of `(*Cache).trace`.
For long running metamorphic tests, especially those that require
relatively more calls through the block cache (e.g. when the flush split
or target file size is very low), the collection of the debug stack
traces can cause the process to consume a large amount of memory. For
nightly metamorphic tests runs on a Linux machine, this can manifest as
the process being OOM-killed by the kernel at a certain point, resulting
in test failures.
Split the `(*Cache).trace(msg string)` method into two implementations,
toggled by the `tracing` and `!tracing` flags. The former preserves the
current behavior, appending the debug stack …
> internal/cache: enable debug stack collection when tracing enabled

- batch.go
- db.go
- format_major_version.go
- format_major_version_test.go
- ingest.go
- ingest_test.go
- open_test.go
- range_keys_test.go
- sstable/reader.go
- sstable/reader_test.go
- testdata/checkpoint
- testdata/event_listener
- testdata/ingest
- testdata/ingest_load
- testdata/metrics
- testdata/rangekeys
Introduce a new format major version for range keys, with associated
table format `Pebble,v2`. When the DB is opened at this version, it is
free to make use of range key features.
Related to #1339.
> db: add format major version for range keys

- internal/metamorphic/options.go
Now that range keys are gated behind a format major version and the metamorphic
tests write range keys, we must use at least FormatRangeKeys in the metamorphic
tests.
Fix merge skew from #1497 and #1503.
> internal/metamorphic: use at least FormatRangeKeys

- internal/metamorphic/options.go
To allow a single metamorphic test run to complete faster, and thus for
more configurations to be tested during the nightly runs, remove the
disk-backed file-systems from the randomly generated DB configurations.
A single disk-backed configuration in the `standard-021` options should
provide sufficient coverage.
See #1514.
> internal/metamorphic: disable disk-backed FS for random configs

- db.go
- internal/rangekey/defragment.go
- internal/rangekey/defragment_test.go
- internal/rangekey/interleaving_iter.go
- internal/rangekey/interleaving_iter_test.go
- internal/rangekey/iter.go
- internal/rangekey/testdata/defragmenting_iter
- iterator.go
- range_keys.go
- testdata/rangekeys
Add a DefragmentingIter that wraps a range key iterator, defragmenting
physical fragmentation of range keys during iteration.
During flushes and compactions, range keys may be split at sstable
boundaries. This fragmentation can produce internal range-key bounds that do
not match any of the bounds ever supplied to a user range-key operation. This
physical fragmentation is necessary to avoid excessively wide sstables.
The defragmenting iterator undoes this physical fragmentation, joining spans
with abutting bounds and equal state. The defragmenting iterator supports two
separate methods of determining what is "equal state" for a span. The user
may configure which of the methods of defragmentation they desire at Init
through passing a DefragmentKind enum value:
DefragmentLogical is intended …
> internal/rangekey: add DefragmentingIter

- db.go
- range_keys_test.go
- testdata/rangekeys
Previously, iterators configured to iterate over range keys would only truncate
range-keys to bounds that had been set after iterator creation through
SetBounds.
Fix #1519.
> db: respect IterOptions bounds during range-key iteration

- batch_test.go
- compaction.go
- db.go
- error_test.go
- internal/metamorphic/options.go
- internal/rangekey/rangekey.go
- iterator_test.go
- mem_table.go
- range_keys.go
- range_keys_test.go
- testdata/rangekeys
This change moves where we copy range keys into the global in-memory arena.
Previously, we copied them in at batch application. Now, range keys are first
copied into a memtable's arena. Then, when the memtable is flushed, they're
copied again into the global in-memory arena.
This change increases the minimum memtable size beyond 1KB, as a consequence of
the additional skiplist's minimum size.
> db: write range keys to memtables

- internal/rangekey/interleaving_iter.go
- internal/rangekey/testdata/interleaving_iter
Previously, if an iterator had an upper bound set and a user seeked to the
upper bound using SeekGE, the interleaving iterator would panic with an
invariant violation.
If SeekGE(k) discovers a range key overlapping the search key k, the
interleaving iterator returns a synthetic range-key marker truncated to k.
However, the upper-bound check during `nextRangeKey` is performed against the
truncated range-key start bound, which passes if the original range key's start
is less than the upper bound. This resulted in the interleaving iterator
returning a synthetic range-key marker at the same user key as the upper bound,
a violation of the upper-bound invariant.
Discovered via the metamorphic tests.
> internal/rangekey: fix invariant violation during SeekGE(upper-bound)

- iterator.go
- testdata/rangekeys
During forward seek calls (SeekGE, SeekGEWithLimit, SeekPrefixGE) on an
iterator that includes range keys, the Pebble iterator will stop at the search
key if there exists a range key straddling the search key. If there's no
coincident point key at the same position, this introduces an 'ephemeral'
iterator position that only exists after the seek.
If the user Prev'd while positioned over an 'ephemeral' iterator position, the
underlying internal iterator would mistakenly be Prev'd twice, skipping a key.
This change alters the logic around when to Prev twice, avoiding the second
Prev if the exposed iterator position is ephemeral.
> db: fix skipped key during Prev at synthetic range key marker

- ingest.go
During ingest loads, the smallest and largest bounds for point and
ranges are calculated. The point and range key bounds are cloned from an
iterator. When setting the overall bounds for the table, the point and /
or range key bounds can be reused for `Smallest` and `Largest`, as the
former are stable.
Remove the unnecessary key clones.
Follow up from #1521.
> db: remove unnecessary key clones during ingest load

- compaction.go
- db.go
- iterator_test.go
This reverts commit b2295acd0a1514efd11b08bc9a43be073144245f.
Due to the discussion in https://github.com/cockroachdb/pebble/pull/1505#pullrequestreview-887496266
> Revert "db: add experimental DB.RegisterFlushCompletedCallback"

- internal/rangekey/defragment.go
- internal/rangekey/defragment_test.go
- internal/rangekey/iter.go
- internal/rangekey/merging_iter.go
- internal/rangekey/merging_iter_test.go
- internal/rangekey/testdata/merging_iter
- range_keys.go
Adapt the range key MergingIter interface to return sets of fragments
(encapsulated by a Fragments type), rather than individual fragments. This
avoids some redundant key comparisons, and simplifies some of the code in both
the merging iterator and the range key coalescing iterator.
It will also make it easier to return 'empty' range-key spans to avoid
unnecessary reading range key blocks when an iterator is positioned between two
range keys.
Some of the complexity that used to live within MergingIter now reappears in a
test-only `mergingIterAdapter` type that's used by the merging
iterator/fragmenter equivalence test, but at least it's relegated to test-only
code.
> internal/rangekey: adjust MergingIter interface, return fragment sets

- sstable/testdata/size_estimate
- sstable/writer.go
- sstable/writer_test.go
The index block size estimation, and the sstable size estimation for data blocks
had similar code, which could be abstracted into a single type. This pr does that.
> sstable: unify sstable size estimation by using a single abstraction

- data_test.go
- external_iterator.go
- external_iterator_test.go
- internal/rangekey/defragment.go
- internal/rangekey/interleaving_iter.go
- internal/rangekey/iter.go
- iterator.go
- sstable/block.go
- sstable/block_test.go
- sstable/reader.go
- testdata/external_iterator
Add a pebble.NewExternalIter function that may be used to construct a
*pebble.Iterator that reads from a provided slice of sstables rather than
committed database state. Input sstables are required to contain all
zero-sequence number keys. Shadowing of keys is resolved by treating the files
as ordered in reverse chronological order.
This iterator is intended to replace the storage package's multiIterator.
Close #1526.
> db: add external sstable merging iterator

- ingest.go
- ingest_test.go
- internal/base/internal.go
- internal/base/internal_test.go
- sstable/writer.go
- testdata/ingest_update_seqnums
The first commit alters `(base.InternalKey).IsExclusiveSentinel` to handle all range key kinds - previously only a RANGEKEYSET with a max seqnum was considered a sentinel.
The second updates the smallest and largest point keys to be set using the helper methods, rather than referencing the smallest / largest fields directly.
> sstable,db: two small bounds related changes

- compaction.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- flush_external.go
- get_iter_test.go
- ingest.go
- ingest_test.go
- internal/manifest/btree_test.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/level_metadata_test.go
- internal/manifest/testdata/file_metadata_bounds
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
- level_checker_test.go
- level_iter_test.go
- merging_iter_test.go
- sstable/suffix_rewriter.go
- sstable/writer.go
**Note for reviewers**
This is a fairly sizable patch given the many places where the smallest / largest fields were being set directly (and hence the motivation for the patch in the first place). Fortunately most of the diff comes from updating tests.
It might be beneficial to first review the updates in the `manifest` package (`version.go` and `version_edit.go`, and  corresponding data-driven test in `file_metadata_bounds`. Then review the non-test updates to use the new methods in the following:
- `compaction.go`
- `db.go`
- `flush_external.go`
- `ingest.go`
The remainder of the changes are to test files, and are fairly mechanical changes, so probably don't need as much scrutiny.
Fortunately, Reviewable seems to group the test and non-test files 👍 
---
Currently, `FileMetadata` exposes …
> manifest: add methods for extending table bounds

- checkpoint_test.go
- cleaner_test.go
- cmd/pebble/compact.go
- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- db_test.go
- error_test.go
- event_listener_test.go
- flush_test.go
- format_major_version_test.go
- ingest_test.go
- internal/datadriven/datadriven.go
- internal/metamorphic/generator.go
- internal/metamorphic/ops.go
- internal/metamorphic/parser.go
- iterator_test.go
- metrics_test.go
- open_test.go
- options.go
- range_del_test.go
- snapshot_test.go
- table_cache_test.go
- table_stats_test.go
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
- tool/make_test_find_db.go
This PR introduces concurrent execution for manual compactions - previously done one at a time, level by level.
This is achieved by splitting a single manual compaction for a level into
multiple compactions with non-overlapping key ranges. When compacted, the
output ranges of these compactions do not conflict and can thus be
performed in parallel.
A new parameter has been added to db.Compact, which determines whether or
not to split a single manual compaction into its encompassing non-overlapping
keyranges. Moreover, the changes in this PR rely on automatic compactions
being disabled when compactions are split to avoid conflicts.
Resolves https://github.com/cockroachdb/pebble/issues/1404
> compaction: add support for concurrent manual compactions

- compaction.go
This helps unit tests that use the callback to trigger a
read using an iterator with IterOptions.OnlyReadGuaranteedDurable.
Informs https://github.com/cockroachdb/cockroach/issues/77046
> db: produce the FlushEnd event after installing readState

- data_test.go
- db.go
- external_iterator.go
- get_iter.go
- get_iter_test.go
- internal.go
- internal/base/iterator.go
- internal/rangekey/interleaving_iter.go
- internal/rangekey/interleaving_iter_test.go
- iterator.go
- iterator_test.go
- level_iter.go
- merging_iter.go
- sstable/block_property_test.go
- sstable/data_test.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/table_test.go
- sstable/testdata/readerstats/iter
- sstable/writer_test.go
- testdata/iterator
- testdata/level_iter_seek
- testdata/merging_iter
The current IteratorStats only include information from the top
of the tree (pebble.Iterator). The new InternalIteratorStats
includes block bytes loaded (and cached), and stats for points
iterated over by the mergingIter. The latter includes points
that were ignored because of range tombstones.
These stats can be used to make inferences about root causes
of slow scans.
The stats are introduced by adding an InternalIteratorWithStats
interface that extends InternalIterator. Not all iterators need
to implement this interface (block iter, memtable iter etc.).
Flexibility of plugging in InternalIterators in various places
(especially for testing) is preserved by adding a trivial wrapper,
internalIteratorWithEmptyStats. This wrapping introduces a bug
risk that an InternalIteratorWithStats could …
> db: add iterator stats for iterators below the top-level

- tool/logs/compaction.go
- tool/logs/compaction_test.go
- tool/logs/testdata/compactions
An accumulation of improvements, based on using the tool as part of
various "real-world" debugging exercises.
**Accept any file as an input.** Previously, filenames were inspected to
determine how the log lines should be parsed. Rely instead on the
regular expressions.
**Rework the windowing algorithm.** Previously log lines could be
grouped into the wrong window based on the start and end timestamps.
Improve the windowing.
**Group by node, store and job.** Previously events were grouped only by
job ID. In the event that a store stopped and restarted and logged to
the same file, duplicate events could be dropped.
**Update read-amp parsing**. Newer versions of Cockroach print the LSM
debug as a single log event, with a single timestamp prefix. Update the
parser to split parsing of the read …
> tool/logs: various improvements to compaction event parser

- compaction_picker.go
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
In #1487, we decided to use the existing`conflictsWithInProgress` check 
which retries the compaction if the input/output level(s) conflict only when 
`parallelize=false`. We skip the check if`parallelize=true` because we allow 
multiple compactions to/from a level. We also rely on automatic compactions 
being disabled when executing parallel compactions since automatic 
compactions produce conflicts with the chosen keyranges and get dropped 
before scheduling.
This commit modifies `conflictsWithInProgress` to also check for conflicting
keyranges. So, a compaction is considered conflicting if it touches **the same
keyrange on the same level**. I think it would be helpful because then we can
be assured that `db.Compact` will function correctly regardless of disabling
automatic compactions.
> compaction: change `conflictsWithInProgress` to check keyranges

- sstable/write_queue.go
- sstable/writer.go
Previously, in the addPoint function, we would store a reference to w.dataBlockBuf.dataBlock.curKey
in the Writer.meta.
```
k := base.InternalKey{
// block.curKey contains the most recently added key to the block.
UserKey: w.dataBlockBuf.dataBlock.curKey[:len(w.dataBlockBuf.dataBlock.curKey)-8],
Trailer: key.Trailer,
}
w.meta.SetLargestPointKey(w.compare, k)
```
This slice is owned by the dataBlockBuf, which can be added back to the sync.Pool, and re-used by
another compaction/flush.
For now, we use a single dataBlockBuf in the Writer, to get rid of this race.
Fixes: https://github.com/cockroachdb/cockroach/issues/77194, https://github.com/cockroachdb/cockroach/issues/77189
> sstable: circumvent a dataBlockBuf race in the sstable Writer

- open_test.go
Wait for the compactions to finish before copying directory contents.
Fixes https://github.com/cockroachdb/pebble/issues/1549
> db: fix flaky TestOpenWALReplayReadOnlySeqNums

- .github/workflows/stale.yml
Add a GitHub actions workflow that marks issues as stale and closes them
after a period of inactivity.
Issues can be opted out of the stale bot by marking them with the
`X-nostale` label.
This change was adapted from the [corresponding file in Cockroach][1].
[1]: https://github.com/cockroachdb/cockroach/blob/master/.github/workflows/stale.yml
> ci: mark and close stale issues

- tool/logs/compaction.go
- tool/logs/compaction_test.go
- tool/logs/testdata/compactions
**tool/logs: fix single memtable flushes**
This commit adds a few additional adjustments to the compaction log
tool.
1. Previously, single memtable flushes were not picked up because the
regular expression required plural "memtables".
2. To make mistakes like the above more detectable, simplify the
'sentinel' regular expression to be less prescriptive.
3. Previously a truncated log line would stop log analyzing with an
error. These log lines are possible if a process exits ungracefully
before it's able to fully flush the log buffer. Parsing errors are
now accumulated and logged to stderr (so that they may also be
ignored by being redirected to /dev/null) at the end.
**tool/logs: add ingested events, reorganize output**
Add support for parsing out ingested sstable events. Lift these new …
> tool/logs: various improvements

- internal/manifest/testdata/version_check_ordering
- internal/manifest/version_test.go
Addresses an existing TODO, reusing the existing `ParseVersionDebug`
method to parse the testdata input to `TestcheckOrdering`, and
eliminating some duplicated code.
Update testdata input to reflect being parsed from the inverse of the
`DebugString` method.
For test cases involving L0, rewrite the test case to specify L0 files
in reverse order, to line up with how `DebugString` would print the
corresponding version.
> internal/manifest: refactor TestCheckOrdering to use ParseVersionDebug

- sstable/suffix_rewriter.go
- sstable/testdata/rewriter
- sstable/testdata/writer
- sstable/writer.go
- sstable/writer_test.go
Currently, the overall smallest / largest keys for `WriterMetadata` are
set if no point, range delete, or range key has been set on the table.
In the case where the largest key is set first, the check evaluates to
false (as at least one of the booleans is true), and the subsequent
check to compare the provided key to the smallest key also evaluates to
false, as there is rarely a key that sorts before a nil-valued user key
and zero trailer (the zero value of the field).
Update the check to instead use separate booleans for the smallest and
largest fields.
Improve test coverage by printing the overall table bounds in the
data-driven tests.
Move all boolean fields in `WriterMetadata` to the end of the struct.
This reduces the struct size from `680` bytes to `672` bytes, even with
the …
> sstable: fix bug with overall bound setting

- compaction.go
- compaction_picker.go
- compaction_test.go
- testdata/compaction_picker_L0
Previously, intra-L0 compactions used L1's target file size to populate
the compaction's max output file size, grandparent limit, etc. This
could result in intra-L0 compactions constructing outputs wider than
otherwise permitted when outputting to L0.
Also, replace the `readTriggered` bool on `pickedCompaction` with a
compaction kind that is directly thread through to `compaction.kind`.
Extracted these bits out of #1537, because they deserve their own
scrutiny and ability to atomically revert.
> db: use L0 target file size, grandparent limit for intra L0 compactions

- batch.go
- batch_test.go
Previously, if a Batch was Reset its running count of range keys was not reset.
> db: clear range key count during Batch Reset

- sstable/write_queue.go
- sstable/writer.go
As part of this pr, we documented some invariants which must be maintained in the Writer,
and also swept through the code to ensure that the documented invariants are met.
There is also a minor cleanup of the writeQueue.releaseBuffers function
> sstable: document and confirm ownership invariants in the Writer

- internal/base/internal.go
- sstable/writer.go
The WriterMetadata can outlive the Writer, and as such, it makes more
sense that byte slices in the WriterMetadata aren't owned by the Writer,
and are instead owned by the WriterMetadata.
It is unnecessary to update WriterMetadata.LargestPoint on every call to the
Writer's addPoint function. Instead, we can get away with updating it only
when the Writer is closed.
Prior to this pr, the WriterMetadata.LargestPoint was an InternKey with a UserKey
which directly pointed into the buffer owned by the dataBlockBuf. To prevent the
WriterMetadata from pointing into a buffer owned by the dataBlockBuf, it was required
to clone the key before updating WriterMetadata.LargestPoint.
However, doing this clone on every call to Writer.addPoint is prohibitively expensive.
So, we only update LargestPoint on …
> sstable: refactors WriterMetadata slice ownership

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- flush_external.go
- format_major_version.go
- format_major_version_test.go
- ingest.go
- internal/manifest/btree.go
- internal/manifest/level_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- metrics.go
- metrics_test.go
- open.go
- open_test.go
- testdata/checkpoint
- testdata/compaction_picker_L0
- testdata/event_listener
- testdata/ingest
- testdata/ingest_load
- testdata/marked_for_compaction
- testdata/metrics
- testdata/rangekeys
- testdata/split_user_key_migration
- tool/testdata/db_lsm
- version_set.go
Add two new format major versions FormatSplitUserKeysMarked and
FormatMarkCompacted that together may be used to guarantee that all sstables
within the table form their own atomic compaction unit. Previous versions of
Pebble (before #1470) and RocksDB allowed keys with identical user keys to be
split across multiple tables within a level. This produced a set of files known
as an 'atomic compaction unit' that must be compacted together to preserve the
LSM invariant.
The first format major version FormatSplitUserKeysMarked may be used to
guarantee that every file that is member to a multi-file atomic compaction unit
is marked for compaction. The 'marked-for-compaction' file metadata field is
currently unused by Pebble, but is repurposed here to record the intent to
recompact these files …
> db: add migration to rewrite atomic compaction units

- .github/workflows/ci.yaml
- cmd/pebble/fsbench.go
- compaction_iter.go
- ingest.go
- internal/batchskl/skl.go
- internal/keyspan/merging_iter_test.go
- internal/lint/lint_test.go
- internal/manifest/l0_sublevels.go
- internal/rangekey/coalescer.go
- internal/rangekey/interleaving_iter.go
- internal/rangekey/interleaving_iter_test.go
- iterator.go
- iterator_test.go
- merger.go
- record/record_test.go
- sstable/block_property.go
- sstable/block_property_test.go
- sstable/compression.go
- sstable/data_test.go
- sstable/filter.go
- sstable/suffix_rewriter.go
- sstable/writer.go
- table_cache.go
- tool/db.go
- tool/util.go
A mechanical change to format all files using `crlfmt` (excluding files in the vendor directory), and apply a lint check to enforce via CI. This is similar to the test in Cockroach.
> *: use crlfmt to enforce style

- compaction_test.go
- format_major_version_test.go
In tests that rely on deterministic output of compaction event logs, fix the
event durations directly rather than mocking d.timeNow. This avoids the
potential for `time.Time` monotonic times and floating point imprecision
causing truncation differences between platforms.
See #1571.
> db: mock event duration directly in tests

- format_major_version_test.go
- testdata/split_user_key_migration
Prevent automatic compactions from compacting away marked files before we get
an opportunity to check for their presence.
Fix #1571.
> db: fix TestSplitUserKeyMigration flake

- internal/manifest/testdata/file_metadata_bounds
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
Currently, only point key bounds for a table are present in a manifest
entry. With the addition of range keys, the manifest needs to track the
point and range key bounds, in addition to providing a mechanism to
infer the overall bounds for the table.
Adopt the following encoding scheme to incorporate range keys into the
manifest:
- if the table only contains point keys, the existing encoding applies -
a new file entry is written with `tagNewFile4` and the smallest and
largest point keys are used as the smallest and largest bounds for the
table.
- else, the table contains range keys, and the new file is written with
a new tag, `tagNewFile4RangeKeys` that extends `tagNewFile4`:
- a "marker" byte is written that indicates if the table also has
point keys, and how the bounds can be used to …
> internal/manifest: encode/decode range keys in manifest

- sstable/block_property_test.go
The existing test uses the top level index block to enumerate the
blocks. In the case that a table has a multi-level index, for
correctness, the test should enumerate blocks by traversing the
multi-level index. Currently, in cases where there is a multi-level
index, the test works as the number of index blocks in the top level
block equals the number of data blocks (by virtue of setting a low value
for the block size).
For simplicity, force the tables to be written with a single-level
index.
> sstable: use a single level index in block property data driven test

- sstable/block.go
- sstable/block_test.go
- sstable/write_queue.go
- sstable/writer.go
- sstable/writer_test.go
Pooling gives us the ability to enable parallelism in the Writer.
```
name                                                          old time/op    new time/op    delta
Writer/block=4.0_K/filter=true/compression=NoCompression-16      114ms ±25%      98ms ± 5%     ~     (p=0.310 n=5+5)
Writer/block=4.0_K/filter=true/compression=Snappy-16             114ms ± 4%     112ms ± 3%     ~     (p=0.548 n=5+5)
Writer/block=4.0_K/filter=true/compression=ZSTD-16               1.12s ± 3%     1.09s ± 6%     ~     (p=0.310 n=5+5)
Writer/block=4.0_K/filter=false/compression=NoCompression-16    64.5ms ± 8%    61.7ms ± 2%     ~     (p=0.548 n=5+5)
Writer/block=4.0_K/filter=false/compression=Snappy-16           79.6ms ± 2%    79.4ms ± 2%     ~     (p=0.905 n=4+5) …
```
> sstable: re-pool datablock buffers in the sstable Writer

- internal/manifest/level_metadata.go
- level_checker_test.go
- level_iter.go
- level_iter_test.go
- testdata/level_iter_seek
This change updates the LevelMetadata Seek{GE,LT} calls to
support specifying whether we are interested in files with
point keys, range keys, or both/combined. In future changes,
we will optimize this seek to be more efficient if we want
to skip over files with no range keys.
> *: Skip over files with no point keys in point key levelIter

- .github/workflows/ci.yaml
- internal/lint/lint_test.go
Add Go version 1.18 to the build matrix. The "default" for the most
specific test suites (race, invariants, etc.) remains version 1.17.
> ci: build and test against Go version 1.18

- compaction.go
- internal/keyspan/internal_iter_shim.go
This commit prepares for work that will disentangle keyspan.FragmentIterator
from the base.InternalIterator. Range deletions in compactions pose an obstacle
to this work, because the keyspan.FragmentIterators that hold compaction-input
range deletions are added as levels into the compaction input `mergingIter`.
This change refactors the compaction-input iterator construction to collect
rangedel iterators and wrap them in a `keyspan.MergingIter`. To merge the
resulting `FragmentIterator` into the compaction input `internalIterator`,  a
temporary `keyspan.InternalIteratorShim` type is introduced that exclusively
supports simple forward iteration required by the compaction iterator. This
shim iterator is added as a single level within the compaction input
`mergingIter`.
This unusual iterator …
> compaction: disentangle compaction rangedels from InternalIterator

- docs/memory.md
- internal/cache/entry_normal.go
- internal/lint/lint_test.go
Currently, the `entryCacheAlloc` struct maintains a slice of `entry`
structs. When CGo is enabled, the latter is backed by manually allocated
memory. As the former is a pooled struct, when it is released from the
pool, it will be garbage collected by the Go runtime.
The patch in #X introduced a regression where a no-op finalizer is used
unless running with `invariants` or `trace` when `race` is disabled.
Typical production binaries will not have these flags set, so the no-op
finalizer is installed in place of a "real" finalizer. This results in a
small memory leak given that the memory backing each of the `entry`
items is not released when the pool releases an `entryCacheAlloc` and it
is garbage collected by the runtime.
Revert to installing the "real" finalizer in this case, as it is …
> cache: use finalizer for freeing manually allocated memory

- docs/memory.md
- internal/cache/entry_normal.go
- internal/lint/lint_test.go
This is a backport of #1591 to the 22.1 release branch.
---
Currently, the `entryCacheAlloc` struct maintains a slice of `entry`
structs. When CGo is enabled, the latter is backed by manually allocated
memory. As the former is a pooled struct, when it is released from the
pool, it will be garbage collected by the Go runtime.
The patch in #1087 introduced a regression where a no-op finalizer is
used unless running with `invariants` or `trace` when `race` is
disabled.  Typical production binaries will not have these flags set, so
the no-op finalizer is installed in place of a "real" finalizer. This
results in a small memory leak given that the memory backing each of the
`entry` items is not released when the pool releases an
`entryCacheAlloc` and it is garbage collected by the runtime. …
> release-22.1: cache: use finalizer for freeing manually allocated memory

- docs/memory.md
- internal/cache/entry_normal.go
- internal/lint/lint_test.go
This is a backport of #1591 to the 21.1 release branch.
---
Currently, the `entryCacheAlloc` struct maintains a slice of `entry`
structs. When CGo is enabled, the latter is backed by manually allocated
memory. As the former is a pooled struct, when it is released from the
pool, it will be garbage collected by the Go runtime.
The patch in #1087 introduced a regression where a no-op finalizer is
used unless running with `invariants` or `trace` when `race` is
disabled.  Typical production binaries will not have these flags set, so
the no-op finalizer is installed in place of a "real" finalizer. This
results in a small memory leak given that the memory backing each of the
`entry` items is not released when the pool releases an
`entryCacheAlloc` and it is garbage collected by the runtime. …
> release-21.1: cache: use finalizer for freeing manually allocated memory

- docs/memory.md
- internal/cache/entry_normal.go
- internal/lint/lint_test.go
This is a backport of #1591 to the 21.2 release branch.
---
Currently, the `entryCacheAlloc` struct maintains a slice of `entry`
structs. When CGo is enabled, the latter is backed by manually allocated
memory. As the former is a pooled struct, when it is released from the
pool, it will be garbage collected by the Go runtime.
The patch in #1087 introduced a regression where a no-op finalizer is
used unless running with `invariants` or `trace` when `race` is
disabled.  Typical production binaries will not have these flags set, so
the no-op finalizer is installed in place of a "real" finalizer. This
results in a small memory leak given that the memory backing each of the
`entry` items is not released when the pool releases an
`entryCacheAlloc` and it is garbage collected by the runtime. …
> release-21.2: cache: use finalizer for freeing manually allocated memory

- db.go
- docs/RFCS/20220311_pebble_flushable_ingested_sstable.md
- internal/base/filenames.go
- internal/metamorphic/options.go
- level_iter.go
To prevent waiting for the memtable to flush when
there is an overlapping ingested sstable, we lazily
add the sstables to the memtable and add the sstables
directly to L0 when flushed.
Add a small RFC that discusses the various proposed
changes that implement this functionality.
Informs #25
> docs/rfc: flushable ingested sstable

- db.go
- internal/base/options.go
- internal/keyspan/iter.go
- internal/keyspan/iter_test.go
- internal/keyspan/level_iter.go
- internal/keyspan/level_iter_test.go
- internal/keyspan/merging_iter.go
- internal/keyspan/testdata/level_iter
- level_iter.go
- options.go
- sstable/block_property.go
- table_cache.go
When reading range keys directly from sstables, we will
need to instantiate levelIters for each level that contains
sstables that could contain range keys. This change adds
a levelIter that implements keyspan.FragmentIterator and
takes advantage of level invariants to only have one sstable's
range key block iter open at once. On top of that,
as fragmentBoundIterator does not currently support
SetBounds or truncation of spans based on iterator bounds, those
features are provided by LevelIter.
Also moves TableNewRangeKeyIter from the base package to
internal/keyspan.
First commit is #1568 .
> internal/keyspan: Add LevelIter for range keys 

- data_test.go
- db.go
- error_iter.go
- external_iterator.go
- internal/metamorphic/config.go
- internal/metamorphic/generator.go
- internal/metamorphic/ops.go
- internal/metamorphic/parser.go
- internal/metamorphic/retryable.go
- iterator.go
- options.go
- testdata/rangekeys
Add a SetOptions method to Iterator allowing a user to modify the IterOptions
of an existing iterator. This is intended to be used within CockroachDB for
modifying the key types and range key mask suffix of an existing Iterator.
The point iterator stack and range iterator stack both are initialized only
when needed. If no longer needed, the iterator stacks are preserved (in
`Iterator.pointIter` and `Iterator.rangeKey.rangeKeyIter`) but left
disconnected from the Iterator's root internal iterator. This allows the
existing iterator stack to be reused if the Iterator is switched back to
including a key type.
> db: add Iterator.SetOptions for modifying iterator options 

- data_test.go
- internal/manifest/version.go
- table_stats.go
- table_stats_test.go
- testdata/compaction_delete_only_hints
- testdata/compaction_tombstones
- testdata/ingest
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
- testdata/range_del
- testdata/table_stats
Two commits in this series - the first is a code shuffle (no logic changes); the second has the additions.
---
**db: factor out some table stats helpers**
To improve readability, factor out the logic to populate the point and
range key table stats into their own separate methods. This also allows
for adding a separate method for range keys in the future, if the logic
becomes complex enough.
**db: add range key count to table stats**
Range key-related statistics are not currently calculated and stored in
a table's `FileMetadata`, and are required for compaction picking.
Add a `NumRangeKeys` field to `manifest.TableStats` which is populated
by the total number of range keys present in a table (the sum of range
key sets, unsets and deletes).
> db: add range key table stats

- data_test.go
- iterator.go
- testdata/iterator_block_interval_filter
- testdata/iterator_table_filter
Rebuild the iterator stack if filters (block or table) are modified.
Fix #1621.
> db: respect changed filters in SetOptions

- compaction_picker.go
- compaction_picker_test.go
- internal/metamorphic/options.go
- iterator_test.go
- options.go
- options_test.go
- testdata/compaction_picker_L0
- testdata/metrics
Add a L0CompactionFileThreshold option that provides an alternative compaction
picking score for L0. The score is computed as the number of non-compacting
files in L0 divided by the threshold. The existing L0CompactionThreshold score
is a function of the number of sublevels and is still used, with compaction
picking using the maximum of the two scores.
Fix #1623.
Supersedes #1624.
> compaction: add L0CompactionFileThreshold compaction trigger

- compaction_picker.go
- compaction_picker_test.go
- internal/metamorphic/options.go
- iterator_test.go
- options.go
- options_test.go
- testdata/compaction_picker_L0
- testdata/metrics
Add a L0CompactionFileThreshold option that provides an alternative compaction
picking score for L0. The score is computed as the number of non-compacting
files in L0 divided by the threshold. The existing L0CompactionThreshold score
is a function of the number of sublevels and is still used, with compaction
picking using the maximum of the two scores.
Fix #1623.
----
CockroachDB 22.1 backport of #1632.
> crl-release-22.1: compaction: add L0CompactionFileThreshold compaction trigger

- compaction_picker.go
- compaction_picker_test.go
- internal/metamorphic/options.go
- options.go
- options_test.go
- testdata/compaction_picker_L0
- testdata/metrics
Add a L0CompactionFileThreshold option that provides an alternative compaction
picking score for L0. The score is computed as the number of non-compacting
files in L0 divided by the threshold. The existing L0CompactionThreshold score
is a function of the number of sublevels and is still used, with compaction
picking using the maximum of the two scores.
Fix #1623.
----
CockroachDB 21.2 backport of #1632.
> crl-release-21.2: compaction: add L0CompactionFileThreshold compaction trigger

- db.go
- external_iterator.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/keyspan/testdata/interleaving_iter
- internal/keyspan/testdata/interleaving_iter_masking
- iterator.go
Refactor range-key masking by lifting most of the range key particulars up onto
the `*pebble.Iterator` type, exposing narrowly-defined hooks that allow it
control the interleaving iterator's behavior.
In future work, the SpanChanged hook can be used to avoid unnecessary copying
of range-key state.
> internal/keyspan: genercize masking

- compaction.go
- compaction_test.go
- testdata/compaction_check_ordering
This ordering invariant is crucial to ensure that we're not writing
corrupted data to disk.
> db: check ordering invariant for sublevel compactions

- internal/keyspan/defragment.go
- internal/keyspan/defragment_test.go
- internal/keyspan/span.go
- internal/keyspan/testdata/defragmenting_iter
- internal/rangekey/coalesce.go
- table_stats.go
**internal/keyspan: reduce over defragmented spans**
Currently, when the `keyspan.DefragmentingIter` defragment spans, the
keys for all the spans are assumed to be equal, so the keys from the
first span in the defragmented set can be used.
Allow the caller to provide a "reducer" that determines how keys in
spans that are being defragmented are to be collected. This is useful,
for example, when defragmenting fragmented range del fragments, where
the keys in abutting spans are not necessarily equal.
Use a default, no-op reducer for all existing calls to
`(*keyspan.DefragmentingIter).Init()` that adopts the current behavior,
using the keys from the first span.
**db: implement rangedel defragmentation using keyspan.DefragmentingIter**
Address an existing TODO by replacing the custom …
> internal/keyspan: reduce over defragmented spans

- internal/keyspan/defragment.go
- internal/keyspan/defragment_test.go
- table_stats.go
- table_stats_test.go
Currently, the `keyspan.DefragmentReducer` implementation used for
defragmenting range deletions when computing table stats is inefficient
in that it retains all keys (with possibly duplicate items) in a slice
only to take the first and last item for the largest / smallest sequence
numbers, respectively. As both input slices to
`keyspan.DefragmentReducer` are sorted, a slice with length of at most
two can be used to maintain the largest and smallest keys for the
defragmented span. It also removes the O(n log n) sort in favor of O(n)
constant time operations.
Remove the boolean return value from the `keyspan.DefragmentReducer`,
instead documenting the requirement that the implementer to maintains
the contract that the keys in the output slice are sorted, in (sequence
number, kind) …
> internal/keyspan: tweak DefragmentReducer return types

- internal/metamorphic/generator.go
- internal/metamorphic/generator_test.go
- internal/metamorphic/key_manager.go
- internal/metamorphic/key_manager_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
- internal/metamorphic/parser_test.go
- internal/testkeys/testkeys.go
- options.go
- tool/db.go
- vfs/clone.go
**internal/metamorphic: use a wal_dir within the data directory**
When constructing database options to exercise the `wal_dir` option, use a
subdirectory of the `data` directory. This ensures that the `--keep`
command-line flag preserves these runs' WALs. Previously, `--keep` would
erroneously not preserve log files for runs with the `wal_dir` option set.
**vfs: add CloneSync, CloneSkip options for vfs.Clone**
**internal/metamorphic: add support for an initial database state**
Adjust the metamorphic tests to support three new command-line flags:
`--previous-ops` — The path of a previous metamorphic test's `ops` file. The
ops file is read to prepopulate the op generator's key set, ensuring the test
generates operations that frequently draw from the keys that already exist in
the database. …
> internal/metamorphic: add support for an initial database state

- options.go
The current comment mentions that the threshold is used relative to L0
sublevel count only when the `Experimental.L0SublevelCompactions` option
is enabled. As of 32a5180f, the L0 sublevel count is always used.
Update the comment.
Touches cockroachdb/cockroach#79956.
> db: update comment on L0StopWritesThreshold

- internal/metamorphic/generator.go
- internal/metamorphic/generator_test.go
- internal/metamorphic/key_manager.go
- internal/metamorphic/key_manager_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
- internal/metamorphic/parser_test.go
- internal/randvar/randvar.go
- internal/randvar/skewed_latest.go
- internal/randvar/uniform.go
- internal/randvar/zipf.go
- internal/testkeys/testkeys.go
- options.go
- tool/db.go
- vfs/clone.go
Backport of #1635 to the 22.1 release branch.
Backporting this will allow us to test the upgrade from 21.2 to 22.2
as a part of #1612.
> crl-release-22.1: internal/metamorphic: add support for an initial database state 

- compaction_test.go
- table_stats.go
- testdata/compaction_delete_only_hints
Currently, delete compaction hints are set manually in
`TestCompactionDeleteOnlyHints`. This is unnecessary given that the
hints are generated when table stats are collected.
Address the existing TODO, deferring all table stats generation to the
`get-stats` directive. Update the existing `set-hints` command to
`force-set-hints`, which is used in a test case where a hint needs to be
manually constructed on a non-existent table.
> db: generate delete compaction hints automatically in tests

- db.go
- external_iterator.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/keyspan/testdata/interleaving_iter
- internal/keyspan/testdata/interleaving_iter_masking
Remove superfluous Split parameter. Split was required for implementing
masking, but a direct implementation of masking was replaced with generic
Hooks.
Also, don't interleave a synthetic marker for empty spans. The synthetic marker
doesn't serve any purpose if there are no keys defined over the span. This
allows us to return a synthetic marker using an arbitrary Key's kind (rather
than always using RANGEKEYSET, even if the Span contained no RANGEKEYSET keys).
> internal/keyspan: clean up InterleavingIter

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/history.go
- internal/metamorphic/meta_test.go
Add a new metamorphic variant that runs metamorphic tests across multiple
Pebble SHAs. The test takes an arbitrary number of Pebble versions and paths to
prebuilt metamorphic package test binaries. It runs the metamorphic tests once
on the first version. It then takes a random sampling of `--factor` database
directories produced by that version, and uses them as initial database states
for the next version, and so on.
Resolve #1612.
> internal/metamorphic/crossversion: add TestMetaCrossVersion

- internal/keyspan/defragment.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/internal_iter_shim.go
- internal/keyspan/level_iter.go
- internal/keyspan/level_iter_test.go
- internal/keyspan/merging_iter.go
- internal/keyspan/testdata/defragmenting_iter
- internal/keyspan/testdata/level_iter
- internal/keyspan/testdata/merging_iter
- merging_iter.go
- testdata/external_iterator
This change updates keyspan.LevelIter to emit empty Spans (i.e.
spans with valid start/end but no values/Keys) between files.
This is used as an optimization to avoid loading the next file
after a file has been exhausted.
To preserve this optimization up the iterator stack, the
merging iter and defragmenting iter were also updated to
special-case empty spans returned by child iterators and
preserve them as-is instead of defragmenting them
or iterating beyond them.
Fixes #1605
> internal/keyspan: Emit empty spans where there are no range keys

- compaction.go
- compaction_test.go
- db.go
- internal/base/metrics.go
- internal/base/metrics_test.go
- metrics.go
- open.go
- record/log_writer.go
- record/log_writer_test.go
These are explicitly marked as subject to change since they are
exposing implementation of Pebble sub-systems.
They are useful for CockroachDB admission control for estimating
peak throughput, for generating write tokens. Utilization also
allows better understanding how close to the edge we are, before
a write can experience some kind of stall.
Based on some CockroachDB kv0 experimentation, one can drive the
flush pipeline to 100% utilization, resulting in write stalls.
The log writer can also surprisingly be driven to high time
utilization and high pending buffer utilization, in cases where
sync latency is high (say due to write bandwidth saturation of the
disk). This is a justification for exposing these metrics.
> db,record: add internal metrics for throughput, latency and utilization

- db.go
- error_iter.go
- external_iterator.go
- internal/keyspan/defragment.go
- internal/keyspan/filter.go
- internal/keyspan/iter.go
- internal/keyspan/level_iter.go
- internal/keyspan/merging_iter.go
- iterator.go
- sstable/block.go
Add a sync.Pool for pooling of the iteratorRangeKeyState struct which holds an
iterator's range key iterator stack.
Additionally, remove the (keyspan.FragmentIterator).Clone method. This method
is no longer necessary now that visibility of range keys is enforced by the
keyspan.MergingIter's transform, which hides keys created more recently than
the cloned iterator's sequence number.
> db: pool range-key iterator structs, remove Clone

- internal/keyspan/interleaving_iter.go
- internal/keyspan/testdata/interleaving_iter
Fix a bug with InterleavingIter.SeekLT that resulting in SeekLT returning a
span that did not overlap any keys less than the SeekLT's search key.
See the comment in keyspanSeekLT for an example.
> internal/keyspan: fix SeekLT bug

- compaction.go
- data_test.go
- db.go
- internal/keyspan/iter.go
- internal/keyspan/level_iter.go
- internal/keyspan/level_iter_test.go
- internal/keyspan/testdata/level_iter
- internal/manifest/level_metadata.go
- table_cache.go
- testdata/manual_compaction
This change updates compaction.newInputIters to create
a keyspan.LevelIter containing all rangedel iterators
in a level, instead of the old way of exposing all rangedel
iterators directly to the merging iter. This makes the merging
iter more efficient as it has to manage a smaller heap (especially
for very large compactions), and also reduces the amount of
files that need to be front-opened and rangedel blocks that need
to be front-loaded before the compaction can begin. The LevelIter
can lazily open files as it goes through the compaction.
Also adds a rangedel mode to keyspan.LevelIter that makes it
find files based on point key bounds instead of on range
key bounds.
Fixes #1645
> *: Use keyspan.LevelIter for rangedels in compactions

- compaction.go
- compaction_test.go
- testdata/compaction_check_ordering
This ordering invariant is crucial to ensure that we're not writing
corrupted data to disk.
(cherry picked from commit c55c1d80c374b3155795d3ed365ac40cffe35d4b)
> crl-release-22.1: db: check ordering invariant for sublevel compactions

- db.go
In 1b227d2c the trimming of memtables introduced a regression. The regression
would needlessly include all memtables if all memtables had sequence numbers
more recent than the iterator's sequence number.
The impact of this fix is exaggerated on the `NewIterReadAmp` benchmark,
because the one unnecessary included memtable increases the number of merging
levels beyond the iterAlloc preallocated array length.
```
name                  old time/op    new time/op    delta
NewIterReadAmp/10-10    2.18µs ± 2%    1.63µs ± 2%  -24.87%  (p=0.008 n=5+5)
name                  old alloc/op   new alloc/op   delta
NewIterReadAmp/10-10    2.37kB ± 0%    0.05kB ± 0%  -97.98%  (p=0.008 n=5+5)
name                  old allocs/op  new allocs/op  delta
NewIterReadAmp/10-10      3.00 ± 0%      1.00 ± 0% …
```
> db: fix NewIter regression resulting in extra memtable levels

- sstable/writer.go
Now that we have ways to determine whether parallelism is enabled, we
should check it, before making the invariant check for the no parallelism
case.
> sstable: fix invariant check for sstable size estimation

- db.go
- internal/testkeys/testdata/divvy
- internal/testkeys/testkeys.go
- internal/testkeys/testkeys_test.go
- iterator.go
- iterator_test.go
- options.go
**db: add BenchmarkIteratorScan**
Add a simple microbenchmark that benchmarks the construction of an iterator and
a scan across the entirety of a database's keyspace. Add variances for key
count, read-amplification and the kinds of keys iterated over.
Besides general utility in measuring iterator scan performance, it's expected
to be useful in optimizing the current iterator slow down with range-keys
enabled.
**db: remove newRangeKeyIter closure**
Avoid unnecessarily creating a closure over the *DB, resulting in an
allocation during iterator construction. This closure would have been
eliminated once range key state is fully ecapsulated by the `readState`. This
commit replaces the closure with a direct `*DB` reference for now to avoid the
allocation which may impact benchmarks, including …
> db: add BenchmarkIteratorScan

- level_iter.go
- options.go
- sstable/reader.go
- table_cache.go
This change adds an IterOption, defaulting to false,
that lets the caller opt into reading L6 filter blocks
if they exist on the sstable. Adding this option
allows for a low-risk, low-behaviour-change enabling
of always writing filter blocks to L6 sstables, as we
will not be reading them by default.
Necessary to unblock cockroachdb/cockroach#80980 .
> *: Add IterOption to optionally read L6 filter blocks.

- data_test.go
- db.go
- external_iterator.go
- internal/base/iterator.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/metamorphic/ops.go
- iterator.go
- iterator_test.go
- testdata/iterator
- testdata/iterator_bounds_lifetimes
- testdata/iterator_seek_opt
When a new iterator is constructed or when an existing iterator's bounds are
modified, copy the bounds into a Pebble-allocated slice. This gives Pebble
control over the lifetime of the bound buffers and allows Pebble to restore the
optimization for unchanged bounds that was removed in https://github.com/cockroachdb/pebble/pull/1073.
Two buffers are used, one for the current bounds and one for old bounds. This
scheme allows low-level internal iterators in Pebble to compare new and old
bounds so that context-dependent optimizations may be applied.
These bounds buffers are pooled on the `iterAlloc` to reduce allocations.
These new semantics are simpler and allow Pebble's SetOptions to perform more
optimizations. They come at the cost of the additional key copies, regardless
of whether the …
> db: copy user-provided bounds and optimize unchanged bounds

- open.go
- open_test.go
Previously, there were handful of places where an open directory was leaked if
Open returned an error. These were discovered by CockroachDB's goroutine leak
detector while bumping Pebble to include d79f9617. The goroutine created by
OpenDir was never being closed.
> db: ensure Open closes opened directories on error

- internal/keyspan/seek.go
- internal/keyspan/seek_test.go
- internal/keyspan/testdata/seek
- level_checker.go
- level_iter_test.go
- merging_iter.go
Alter `keyspan.SeekGE` and `keyspan.SeekLE` to omit any sequence number
filtering. The caller must now filter a Span's keys if necessary. This avoids
extra work in the case that there are no visible keys overlapping the search
key. Previously SeekGE and SeekLE would next or prev until they found a visible
key. Now, the caller can simply use the empty span.
This is partially motivated by the batch range deletion slowdown observed in
#1675.
> internal/keyspan: lift visibility filtering out of Seek{GE,LE}

- db.go
- external_iterator.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- iterator.go
- range_keys.go
Reduce allocations in the range-key iteration stack. Allocations are removed
from the defragmenting method's keys slices and the InterleavingIterator hooks
closures.
Additionally, this commit performs some setup for removing the allocations
produced by constructing closures to serve as `keyspan.Transform` and
`keyspan.DefragmentMethod`. Future work will adapt those two function types
into interfaces to avoid two additional allocations.
Time in scan benchmarks is largely flat.
```
name                                                             old time/op    new time/op    delta
IteratorScan/keys=100,r-amp=1,key-types=points-only-10             5.79µs ± 0%    5.81µs ± 1%     ~     (p=0.190 n=4+5)
IteratorScan/keys=100,r-amp=1,key-types=points-and-ranges-10       9.03µs ± 0%    8.91µs ± 1% …
```
> db: reduce allocations in range key iteration

- internal/metamorphic/options.go
Previously, parallelism was only enabled as a standard option, but we
can get more coverage by also enabling it for some of the randomized
runs.
> metamorphic: enable writer parallelism for randomzied metamorphic runs

- batch.go
- batch_test.go
- testdata/indexed_batch_mutation
In e32e94d86 the semantics of Iterators reading through indexed batch were
updated. The semantics of a Clone'd Iterator reading through an indexed batch
were updated so that the cloned Iterator observes exactly the same batch state
as the Iterator being cloned. There was a bug in this implementation where a
cloned iterator would use the cached tombstone/range key fragments on the
batch, if available, and the cache would contain keys more recent.
This commit updates the range deletion/range key fragment caching to only use
and update the cache of range deletion and range key fragments if reading at
the most-recent state of the batch.
A new randomized test is added that tests the visiblity of batch range
deletions and range keys in the presence of Clone.
> db: fix bug in interaction between Clone and indexed batches

- internal/keyspan/defragment.go
- internal/keyspan/defragment_test.go
- internal/keyspan/merging_iter.go
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- table_stats.go
Remove the two remaining excess allocations incured when iterating with range
keys enabled, in the absence of any committed range keys. This brings the
number of allocations to parity with iteration with points only.
The two removed allocations stemmed from use of closures constructed at
iteration construction. These closures have been replaced with interfaces.
```
name                                                             old time/op    new time/op    delta
IteratorScan/keys=100,r-amp=1,key-types=points-only-10             5.76µs ± 0%    5.87µs ± 0%   +1.86%  (p=0.000 n=8+8)
IteratorScan/keys=100,r-amp=1,key-types=points-and-ranges-10       8.81µs ± 2%    8.81µs ± 3%     ~     (p=0.684 n=10+10)
IteratorScan/keys=100,r-amp=3,key-types=points-only-10             10.1µs ± 2%    10.4µs …
```
> internal/rangekey: reduce range-key iteration allocations

- merging_iter.go
Fix a data race in SeekPrefixGE. The merging iterator's findNextEntry method
has an optimization for prefix iteration: When the merging iterator observes a
range deletion and seeks lower-level iterators to the deletion's end boundary,
the merging iterator checks whether the current iteration prefix is exhausted.
Previously, if the entire iterator was exhausted, this optimization would
accidentally read the heap root key `m.heap.items[0].key` for a heap that is
empty. The iterator that surfaced `m.heap.items[0].key` would have already been
exhausted, and the key could point into memory already released (eg, a sstable
iterator already returned to a pool).
This data race is not likely to have caused any inconsistencies in production,
because under the conditions the race was possible the …
> db: fix data race in SeekPrefixGE

- tool/logs/compaction.go
- tool/logs/testdata/compactions
**tool/logs: fix total time calculation**
Alter the truncation for the total time field to truncate to seconds,
rather than minutes. This ensures the total time aligns with the
individual times.
**tool/logs: sort output by (start, node, store)**
Currently the output of the compaction log tool sorts by (node, store,
start). When diagnosing issues, one typically wants to look at all
stores in a given time slice, before moving to the next window.
Re-sort the computed windows by (time, node, store) to improve the
presentation.
**tool/logs: print total flush / ingestion counts and durations**
Print the total count and duration of flushes and ingestions.
Update the total count column for compactions to be named "count", to
align with the column name for flushes / ingestions.
> tool/logs: minor fixes

- open.go
- open_test.go
Previously, there were handful of places where an open directory was leaked if
Open returned an error. These were discovered by CockroachDB's goroutine leak
detector while bumping Pebble to include d79f9617. The goroutine created by
OpenDir was never being closed.
----
This backport is required by #1710, otherwise CockroachDB tests leak goroutines.
> crl-release-22.1: db: ensure Open closes opened directories on error

- merging_iter.go
Fix a data race in SeekPrefixGE. The merging iterator's findNextEntry method
has an optimization for prefix iteration: When the merging iterator observes a
range deletion and seeks lower-level iterators to the deletion's end boundary,
the merging iterator checks whether the current iteration prefix is exhausted.
Previously, if the entire iterator was exhausted, this optimization would
accidentally read the heap root key `m.heap.items[0].key` for a heap that is
empty. The iterator that surfaced `m.heap.items[0].key` would have already been
exhausted, and the key could point into memory already released (eg, a sstable
iterator already returned to a pool).
This data race is not likely to have caused any inconsistencies in production,
because under the conditions the race was possible the …
> crl-release-22.1: db: fix data race in SeekPrefixGE

- sstable/block_property_test.go
If uninitialized, previously the test suffixIntervalCollector block property
collector would only include the first key in its computed interval. This would
fail to capture all the range keys' suffixes.
> sstable: fix test suffix collector's handling of range keys

- compaction.go
- compaction_test.go
- db.go
- internal/metamorphic/options.go
- options.go
- options_test.go
- testdata/metrics
CockroachDB has, or will have the ability to let Pebble know when
it can use additional CPU resources. Since Cockroach imports Pebble
and not the other way around, this pr defines a Pebble interface
which describes methods which Cockroach's slot granter should define.
> db: add Pebble interface for CPU slot granter

- checkpoint.go
- compaction.go
- db.go
- ingest.go
- open.go
- options.go
- vfs/syncing_file.go
- vfs/syncing_file_linux.go
- vfs/syncing_file_test.go
This commit adds NoSyncOnClose option to the syncingFile struct.
When this option is set to true (it is false by default), calling
Close() on a syncingFile will not trigger a Sync() on the file. If the
file system supports sync_file_range() system call, a Sync() will still be
called to synchronize the dirty data but the waiting flags are not set
so that the caller is usually not blocked.
Accordingly, a new option with the same name is added to the
Experimental section of Pebble's options. When it is set to true, the
syncingFiles opened by the db instance will have the NoSyncOnClose
option set.
A new test (TestSyncingFileNoSyncOnClose) is implemented.
> vfs: add option to turn off sync-on-close in syncingFile

- docs/index.html
Add an annotation to the Pebble nightly benchmarks page for the data
quality issue in YCSB between late-March and late-May.
See cockroachdb/cockroach#81871.
> docs: add benchmark annotation for data quality issue

- sstable/block_property_test.go
- sstable/block_test.go
- sstable/data_test.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/testdata/block_properties
Fix a bug that could result in an iterator being prematurely exhausted when
iterating in the reverse direction configured with block-property filtering and
a lower iterator bound.
If a reverse iteration operation on an sstable finds that the first index block
of the two-level index is excluded by the block property filter, it enters
`skipBackward` to move to the previous entry in the two-level index block.  If
a lower bound is set, `skipBackward` compares each key in the two-level index
to the iterator's bounds to exit early if the bounds have already been
exceeded. This comparison accidentally compared against the upper bound instead
of the lower bound.
> sstable: fix bug with two-level indexes, block props and bounds

- data_test.go
- iterator.go
Fix a bug where a call to SetOptions would invalidate the Iterator (such that
Valid returns false), but HasPointAndRange could continue returning values from
the previous iterator state.
Add an assertion within the datadriven test output to ensure Valid and
HasPointAndRange are always consistent with one another.
Fix #1735.
> db: ensure HasPointAndRange returns false after SetOptions

- level_iter.go
- options.go
- sstable/reader.go
- table_cache.go
Backport of https://github.com/cockroachdb/pebble/pull/1685
---
This change adds an IterOption, defaulting to false,
that lets the caller opt into reading L6 filter blocks
if they exist on the sstable. Adding this option
allows for a low-risk, low-behaviour-change enabling
of always writing filter blocks to L6 sstables, as we
will not be reading them by default.
Necessary to unblock cockroachdb/cockroach#80980 .
> [crl-release-22.1] *: Add IterOption to optionally read L6 filter blocks.

- get_iter.go
- internal/keyspan/fragmenter.go
- internal/keyspan/fragmenter_test.go
- internal/keyspan/get.go
- internal/keyspan/merging_iter.go
- internal/keyspan/span.go
- internal/keyspan/span_test.go
- internal/keyspan/testdata/covers_at
- internal/keyspan/testdata/visible_at
- level_checker.go
- merging_iter.go
The Span.Visible method returns a Span with the subset of keys visible at the
provided sequence number. Batch sequence numbers may force this method to
allocate under some circumstances, so it's preferrable to use narrower
methods that do not need to allocate.
Add two such narrower methods, VisibleAt and CoversAt, and use them to remove
calls to Span.Visible for range deletions during point iteration.
> internal/keyspan: replace calls to Span.Visible

- external_iterator.go
- internal/keyspan/merging_iter.go
- internal/rangekey/coalesce.go
- iterator.go
- range_keys.go
Take care of a pending TODO, and avoid allocations when the range-key iterator
stack has any child iterators. This has a minor effect on the MVCCGet
benchmarks that use a batch, which requires the batch to be included within the
range key merging iter.
```
name                                                    old time/op    new time/op    delta
MVCCGet_Pebble/batch=false/versions=1/valueSize=8-10      4.03µs ± 1%    4.06µs ± 1%  +0.61%  (p=0.026 n=9+10)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8-10     4.90µs ± 1%    4.86µs ± 4%    ~     (p=0.210 n=10+10)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8-10    9.91µs ± 2%    9.97µs ± 2%    ~     (p=0.271 n=10+10)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8-10       2.54µs ± 2%    2.50µs ± 1%  -1.54%  (p=0.003 n=10+10) …
```
> internal/keyspan: preallocate merging iter levels, items

- db.go
- internal/keyspan/iter.go
- iterator.go
- range_keys.go
Since e32e94d86 Pebble has unconditionally included batch rangedel iterators
and batch rangekey iterators in the iterator stack. This was done to allow
SetOptions to update these batch iterators if rangedels or rangekeys were added
to the batch between iterator construction and the call to SetOptions.
In this commit, we update iterator construction to again exclude these empty
iterators. To compensate, SetOptions must now test whether any range deletions
or range keys existed at iterator construction, and recreate the point/range
key iterator stacks if necessary. Cases that require iterator reconstruction
are expected to be rare, whereas empty batch rangedel and rangekey iterators
are expected to be very common.
```
name                                    old time/op    new time/op …
```
> db: exclude empty batch range deletion, range key iterators

- batch_test.go
- compaction_test.go
- db.go
- internal/metamorphic/meta_test.go
- iterator_test.go
- open.go
- options.go
- range_keys.go
- range_keys_test.go
- table_stats_test.go
Now that range keys are persisted durably, remove the in-memory range keys
arena.
> db: remove RangeKeysArena

- sstable/reader.go
- table_cache.go
Avoid allocation in newIters by using the cached closeHook closure. This
optimization was lost in 09203fd9a780ce8c15bf8bec3c773ff028051e02. Some version
of this should be backported to 22.1.
```
name                                                    old time/op    new time/op    delta
MVCCGet_Pebble/batch=false/versions=1/valueSize=8-10      4.40µs ±12%    3.76µs ± 1%  -14.42%  (p=0.000 n=10+9)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8-10     5.01µs ± 3%    4.49µs ± 1%  -10.32%  (p=0.000 n=10+10)
MVCCGet_Pebble/batch=false/versions=100/valueSize=8-10    9.56µs ± 2%    9.32µs ± 2%   -2.55%  (p=0.000 n=10+9)
MVCCGet_Pebble/batch=true/versions=1/valueSize=8-10       2.19µs ± 1%    2.15µs ± 0%   -1.71%  (p=0.000 n=10+9)
MVCCGet_Pebble/batch=true/versions=10/valueSize=8-10 …
```
> db: avoid allocation in newIters

- db.go
- external_iterator.go
- iterator.go
- testdata/external_iterator
Fix a bug where the external iterator initialization failed to initialize the
base.Compare to sort overlapping range keys by suffix.
Fix #1760.
> db: fix nil-pointer in external iterator range key iteration

- external_iterator.go
- iterator.go
- testdata/external_iterator
Allow iterators constructed through NewExternalIter to be reconfigured using
SetOptions. This required some restructuring of the external iterator
initialization code. Also, document and enforce the limitations around
unsupported IterOptions for external iterators.
> db: support SetOptions on iterators created through NewExternalIter

- batch.go
> db: document Batch as unsafe for concurrent access

- sstable/reader.go
- table_cache.go
CockroachDB 22.1 backport of #1757 and a tiny bit of #1738 to remove use of
the close hook for rangekey iterators.
----
Avoid an allocation when constructing newIters by using a cached closeHook
closure.
> crl-release-22.1: db: fix newIters allocation regression

- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- testdata/compaction_tombstones
Currently, a table is marked as eligible for elision-only compaction by
the `elisionOnlyAnnotator` under the following circumstances:
- the table's range deletion estimate is greater than or equal to 10% of
the total table size, OR
- the number of deletions is greater than or equal to 10% of the table's
total point key entries.
If a table contains only range keys, the second predicate is true (given
that `0 >= 0`). If the table contains a range key delete or a range key
unset, an elision-only compaction is possible (i.e. if there are no
spans underneath, or snapshots preventing the elision, etc.).
However, if the table contains just range key sets, the table is always
marked for elision, but an elision-only compaction has no effect. The
same elision-only compaction will continue to be …
> compaction: elision-only compactions for tables with only range keys

- docs/js/app.js
The Pebble nightly benchmarks page is currently loaded with each panel
using the same range on its y-axis, which is computed from the max
across all panels. This makes spotting regressions difficult, without
toggling "Local scale".
Load the page with "Local scale" by default.
> docs: use local scale by default on nightly benchmarks page

- sstable/write_queue.go
This method is now used. Addresses the following warning:
```
--- FAIL: TestLint (0.71s)
--- FAIL: TestLint/TestStaticcheck (42.53s)
lint_test.go:86:
sstable/write_queue.go:117:1: this linter directive didn't match anything; should it be removed? ()
```
> sstable: remove obsolete linter ignore directive

- iterator.go
- range_keys.go
- testdata/indexed_batch_mutation
The commit a015e5a0c introduced an optimization to avoid refreshing batch
rangedel and rangekey iterators when no rangedel or rangekey mutations were
applied.
This optimization had a bug: It compared unlike numbers to determine whether to
refresh. The batch's `count{RangeDels,RangeKeys}` fields record the number of
rangedels or range keys added to the batch and are monotonically increasing.
The count of spans in the `keyspan.Iter` on the other hand was the count of
fragments. This bug could result in erroroneously not refreshing the iterator's
view if the previous number of fragments matched the current number of batch
keys.
This commit adapts SetOptions to not avoid calls to initRangeDelIter and
initRangeKeyIter in these cases: These functions already avoid refragmenting
the spans if …
> db: fix SetOptions batch range{del,key} refresh logic

- internal/manifest/version.go
- internal/manifest/version_edit.go
- range_keys.go
This change creates a new LevelMetadata btree just for
sstables containing range keys. This btree is incrementally
updated with sstable additions/deletions that contain range
keys. This should have a relatively light overhead, as
range keys and files containing range keys are expected to be
rare. This also has the benefit of reducing the time it takes
to determine whether files contain range keys.
Fixes #1742.
> internal/manifest: Create new LevelMetadata for range keys

- batch.go
- batch_test.go
Add a new `Batch.Len` method that returns the current
size of the batch.
This method can be used to control the max size of Batches on 
small devices / low memory servers that need to deal with larger
than memory data.
It is also less expensive to call than `len(batch.Repr())` and can be 
used almost for free before every call to `Batch.Set` to monitor the
size of the batch, commit it if it reached a threshold and start a new
batch.
> db: add Len method to Batch

- sstable/internal.go
This change exports the IsRangeKey() and rangekey.Decode()
methods in the internal/rangekey package to the outside world.
Exporting these in the sstable package makes sense as they're
likely going to be used with BlockIntervalCollector, which exposes
internal keys.
Fixes #1774.
> sstable: Export internal/rangekey decoding functions

- compaction.go
- internal/manifest/l0_sublevels.go
If the compaction succeeds but version application fails
(eg. due to a manifest write/rotate error or so), we could
have a discrepancy where the last generated L0Sublevels was
belonging to a Version that never got added to versionSet.
This could mean that the interval indices in FileMetadata
are out of sync with the (now slightly older) L0Sublevels
that is in the actual currentVersion. This can cause panics
in future calls to InitCompactingFileInfo, and/or throw off
compaction picking functions. Fix this by regenerating
L0Sublevels in the currentVersion in case of an error.
Fixes #1781, #1669. Speculatively, that is.
> *: Rebuild L0Sublevels if version application fails

- sstable/block_property_test.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
Currently, sstable.RewriteKeySuffixes only rewrites suffixes
of point keys. This method is used to set MVCC timestamps
in ingested SSTs, so it must also be able to support range keys
containing non-overlapping range keys. This change adds a simple,
non-concurrent code path to rewriting the range key block with
updated suffixes.
Fixes #1765.
> sstable: Rewrite suffixes of range keys in RewriteKeySuffixes

- sstable/reader.go
- table_stats.go
- testdata/compaction_delete_only_hints
- testdata/table_stats
Consider a deletion hint generated from a table that does not contain
any range keys. When the disk space estimate encounters a table in a
lower level that is either partially or fully contained by the range
deletion, but only contains range keys, the estimate incorrectly takes
this disk space into account.
While the deletion _hint_ will correctly ignore the table that contains
only range keys (this is required for correctness), the deletion bytes
estimated is inflated.
A similar case exists when computing deletion estimates from a table
containing only range keys. This particular case is currently handled
correctly, as deletion estimates are not added to the stats of tables
that contain only range keys, though the bug is latent, and would
manifest if an equivalent estimate was computed …
> db: fix bug in deletion estimate computations

- rangekey/rangekey.go
- sstable/internal.go
Export two additional types for use in Cockroach.
See #1774.
> db: export keyspan.Span and keyspan.Key

- compaction_test.go
- testdata/compaction_delete_only_hints
- testdata/table_stats
Now that range keys are handled in compactions, update some existing
data-driven test cases to make use of the batch/flush combination,
rather than using ingests (which was a hack around the fact that range
keys were not persisted).
> *: clean up range key test cases

- rangekey/rangekey.go
Return `rangekey.Key` from `Decode`, rather than `keyspan.Key`.
> rangekey: use package-local return type

- compaction.go
- compaction_test.go
Add a test covering for the fix in #1784.
The test attempts to flush a table into an L0 that contains a single
interval. If the flush fails, the call to `logAndApply` fails, causing
the L0 sublevels to be rebuilt. Prior to #1784, the sublevels were not
rebuilt, which could result in inconsistent file metadata if the L0
intervals changed. In some cases could result in a panic (see #1669 and
#1781).
Sets any error present on the FlushInfo and CompactionInfo structs, if
`logAndApply` fails during the flush or compaction, respectively.
> compaction: test rebuilding L0Sublevels on logAndApply failure

- batch_test.go
- data_test.go
- internal/metamorphic/generator.go
- internal/metamorphic/ops.go
- internal/metamorphic/parser.go
- iterator.go
- iterator_test.go
- testdata/indexed_batch_mutation
- testdata/iterator_next_prev
- testdata/rangekeys
When creating an iterator through Clone, CockroachDB clones and then
immediately calls SetOptions. This adds unnecessary key comparisons to compute
the delta in the options, and if the options changed significantly, adds
unnecessary iterator stack construction.
Add a CloneOptions parameter to Clone that allows the user to optionally
specify IterOptions to construct the iterator with. Additionally, add a field
to support constructing the clone with a refreshed view of the indexed batch,
when cloning an iterator over an indexed batch.
Close #1712.
> db: support configuring iterator during Clone

- compaction.go
- compaction_test.go
- version_set.go
Backport of #1794 and #1785 to 22.1.
> crl-release-22.1: *: treat manifest-related errors during logAndApply as fatal

- .github/workflows/ci.yaml
- Makefile
- internal/metamorphic/.gitignore
Add a Makefile target for running crossversion metamorphic tests between the
current SHA and the most recent crl-release branch. Add a new CI job to run the
target. It's slow (~3-5 minutes), so run it in its own job and only on linux w/
invariants.
> Makefile: add crossversion-meta

- batch.go
- batch_test.go
- data_test.go
- db.go
- internal/metamorphic/ops.go
Remove the experimental designation from the range-key write interface.
> db: remove Experimental designation on range-key write interface

- .github/workflows/new-issue.yml
As Pebble lives in a repo separate from Cockroach, it misses out on a
number of the automation goodies - issue labeling, project management,
etc.
In anticipation of the eventual wiring of the Pebble repo and our
internal project management tool, apply the `T-storage` and `A-storage`
labels to incoming issues by way of a GitHub Action runner (as outlined
[here][1]).
Note that issue labeling is separate to project automation, which
requires a separate step in the pipeline. This will be added in a
subsequent patch, when the requisite credentials are available in the
repo.
[1]: https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
> github: add action runner for automating issue labeling

- internal.go
Export the ErrCorruption error from the public pebble package. This allows
users, including CockroachDB, to test specifically for errors marked as
corruption.
Informs cockroachdb/cockroach#84479.
> db: export ErrCorruption

- db.go
- internal/metamorphic/generator.go
- internal/metamorphic/ops.go
- internal/metamorphic/options.go
- internal/metamorphic/parser.go
- internal/metamorphic/retryable.go
- internal/metamorphic/test.go
- level_checker.go
- level_iter.go
- merging_iter.go
- merging_iter_test.go
- sstable/block_property.go
- sstable/block_property_test.go
- sstable/data_test.go
- sstable/reader.go
- sstable/testdata/block_properties
- table_cache.go
- testdata/level_iter_seek
**sstable: fix additional bounds check bugs**
In 4406dabc a bounds-checking bug was fixed in the two-level index
iterator's SeekLT method. The same bug existed within Last and
skipBackward and was missed.
**db: refactor levelIter/mergingIter boundary interface**
The levelIter and mergingIter are tightly coupled in a few places, with the
levelIter passing additional context to the mergingIter by writing into fields
owned by the mergingIter. This commit is a small refactor to organize these
fields together into a `levelIterBoundaryContext` struct. This is in
preparation for adding an additional field.
**db: don't filter range deletions based on point-key block filters**
Previously, if an iterator configured with a block-property filter encountered
a table that contained all excluded point …
> internal/metamorphic: add block-property filter coverage 

- .github/workflows/ci.yaml
- go.mod
- go.sum
- internal/lint/lint_test.go
- vendor/github.com/hashicorp/go-version/CHANGELOG.md
- vendor/github.com/hashicorp/go-version/LICENSE
- vendor/github.com/hashicorp/go-version/README.md
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/go-version/go.mod
- vendor/github.com/hashicorp/go-version/version.go
- vendor/github.com/hashicorp/go-version/version_collection.go
- vendor/modules.txt
Versions of Go >= 1.17 support using the `go run path@version` syntax to
run a binary at a given version. Making use of this syntax removes the
need to install the lint binaries ahead of time (i.e. developer or CI
runs `go get ...` to install the tool).
Remove the need to install the tools in preparation for a CI run.
Bump the `staticcheck` version to `2022.1.2`, which supports Go 1.18.
Fix #1319.
> lint: use `go run path@version` syntax for lint binaries

- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/keyspan/testdata/interleaving_iter
- internal/keyspan/testdata/interleaving_iter_masking
- iterator.go
- testdata/rangekeys
Refactor the InterleavingIter's Hooks to be masking-specific, and tighten its
contract of guarantees.
The InterleavingIter's SpanChanged hook is intended to notify a caller when the
span covering the current iterator position changes. This is used during
range-key masking to configure the suffix used to filter points. The
InterleavingIter previously called SpanChanged eagerly, whenever it positioned
the key span iterator. Range-key masking correctness relied on the SkipPoint
hook only being invoked when a point key is covered by the current span.
The previous guarantees were sufficient for filtering points in SkipPoint but
are not strong enough for block-property masking.
Filtering masked keys using block-property filters (#1713) requires bounds
checking. We intend to only activate …
> internal/keyspan: tighten masking guarantees

- mem_table.go
- range_keys_test.go
The memtable.containsRangeKeys method read an atomic value without using an
atomic intrinsic.
Informs cockroachdb/cockroach#84950.
> db: fix memtable.containsRangeKeys race

- data_test.go
- iterator.go
- iterator_test.go
- testdata/iterator_stats
Previously, if a mergingIter or levelIter was reused as part of a pooled
iterAlloc, only fields explicitly set were initialized. Other fields were left
with their previous values. This caused internal iterator stats to leak between
iterators.
This commit fixes this by zeroing the entire iterAlloc struct when returning it
to the pool.
> db: zero mergingIter, levelIter structs before use

- data_test.go
- iterator.go
- iterator_test.go
- testdata/iterator_stats
Previously, if a mergingIter or levelIter was reused as part of a pooled
iterAlloc, only fields explicitly set were initialized. Other fields were left
with their previous values. This caused internal iterator stats to leak between
iterators.
This commit fixes this by zeroing the entire iterAlloc struct when returning it
to the pool.
> crl-release-22.1: db: zero mergingIter, levelIter structs before use

- internal/keyspan/span.go
- internal/rangekey/coalesce.go
- sstable/block.go
```
name                                                           old time/op    new time/op    delta
Iterator_RangeKeyMasking/range-keys-suffixes=@10/forward-10      2.34ms ± 7%    2.32ms ± 5%     ~     (p=0.667 n=20+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@10/backward-10     3.30ms ± 6%    3.20ms ± 2%   -2.98%  (p=0.000 n=19+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/forward-10      2.24ms ± 6%    2.19ms ± 5%   -2.49%  (p=0.006 n=19+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@50/backward-10     2.95ms ± 4%    3.06ms ±10%   +3.50%  (p=0.006 n=19+20)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/forward-10      2.17ms ± 7%    2.22ms ± 7%   +2.21%  (p=0.030 n=19+19)
Iterator_RangeKeyMasking/range-keys-suffixes=@75/backward-10     2.74ms ±14%    2.77ms ± 8% …
```
> internal/keyspan: avoid allocation in SortKeys

- sstable/suffix_rewriter.go
- sstable/testdata/rewriter
- sstable/writer_test.go
Currently, when rewriting suffixes for a table that contains only range
keys (i.e. no point keys), the rewrite fails, as the rewriter expects to
see a filter block. However, a table will only contain a filter block if
the table contains point keys (range keys are not included in the
filter).
Allow a rewrite to continue if it does not encounter a filter block.
Fix cockroachdb/cockroach#85175.
> sstable: allow rewriting suffixes of tables that contain only range keys

- compaction_test.go
- db_test.go
- event_listener_test.go
- format_major_version.go
- format_major_version_test.go
- ingest.go
- ingest_test.go
- open_test.go
- testdata/checkpoint
- testdata/event_listener
- testdata/ingest_load
**db: introduce a minimum table format for each format major version**
Currently, a Pebble format major version has a corresponding maximum
supported SSTable format version. This ensures that a DB is running at a
given version before it can support reading and writing tables with a
certain features - i.e. range keys or block properties.
In addition to supporting an upper bound on the table format supported
by a DB, there are plans to support dropping support for certain
features (i.e. table properties). Dropping support for features relies
on being able to enforce that tables in the LSM (either created by the
DB, or external tables that are ingested) are compatible with the DB,
with table formats falling within a range of supported versions.
Add the `(FormatMajorVersion).MinTableFormat` …
> db: min table format; add FormatMinTableFormatPebblev1

- options.go
- range_keys.go
- sstable/block_property.go
- sstable/reader.go
Improve docs around range-key masking.
This commit contains response to feedback from #1824 that I forgot to
push.
> *: update range-key masking docs

- internal/base/internal.go
- iterator.go
Use a trailer comparison to avoid a key comparison during forward iteration
when the next key has a trailer ≥ than the previous key.
In Cockroach this is expected to help particularly during scans of over
ingested sstables: eg, replicas that were ingested through a snapshot, or
sstables ingested through AddSSTable.
```
name                                                          old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-10               3.80µs ± 0%    3.68µs ± 0%  -3.16%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-10             22.1µs ± 1%    21.0µs ± 0%  -4.79%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-10           1.38ms ± 1%    1.31ms ± 0%  -4.95%  (p=0.000 n=10+10) …
```
> db: avoid unnecessary key comparisons during iteration

- ingest_test.go
- sstable/testdata/writer
- sstable/writer.go
Previously, the sstable's key-order checks allowed an InternalKey to be
added to an sstable twice. Among keys with with equal user keys, each
key must have a unique Trailer in be added in Trailer decreasing order.
Noticed in cockroachdb/cockroach#85468, which uncovered a unit test
that improperly added an identical key to an external sstable intended
for ingestion.
> sstable: disallow identical point keys

- internal/keyspan/defragment.go
The defragmenting iterator avoids defragmenting empty spans, because the empty
span fragments are not observable by the user. However on seeks, it would still
pay the cost of buffering the empty span and stepping the iterator both
directions.
This was a regression added in #1748, hidden among that change's own
performance wins. Previously, we used `Span.Empty()` in the defragmenting
iterator to detect both of the two cases: a span doesn't exist, or a span
exists but is empty. Now that nonexistent spans are surfaced as `nil`s, these
cases must be handled separately.
```
name                                    old time/op    new time/op    delta
IteratorSeekNoRangeKeys/batch=false-10    2.58µs ± 1%    2.49µs ± 1%   -3.49%  (p=0.000 n=10+10)
IteratorSeekNoRangeKeys/batch=true-10     4.87µs ± …
```
> internal/keyspan: don't buffer empty span in DefragmentingIter seeks

- cmd/pebble/compact.go
- cmd/pebble/db.go
- compaction.go
- compaction_picker.go
- compaction_test.go
- db_test.go
- internal/metamorphic/options.go
- iterator_test.go
- options.go
We turn MaxConcurrentCompactions into a function so that Cockroach
has the ability to change MaxConcurrentCompactions on the fly.
> .*: make MaxConcurrentCompactions dynamically changeable

- .github/workflows/ci.yaml
Add Go version 1.19 to the test matrix.
Bump the Go version used to for the specific test runs (race, cgo,
crossversion) use Go 1.18.
> ci: test against go1.19

- internal/keyspan/interleaving_iter.go
- iterator_test.go
Avoid unnecessarily seeking the keyspan iterator in the InterleavingIter
when performing a seek on an already-positioned iterator with a current
span that encompasses the seek key.
```
name                                                 old time/op  new time/op  delta
CombinedIteratorSeek/range-key=false/batch=false-16  4.10µs ± 6%  3.81µs ± 2%   -6.94%  (p=0.000 n=10+10)
CombinedIteratorSeek/range-key=false/batch=true-16   6.72µs ± 4%  6.70µs ± 2%     ~     (p=0.796 n=9+9)
CombinedIteratorSeek/range-key=true/batch=false-16   29.7µs ± 6%   9.1µs ± 3%  -69.28%  (p=0.000 n=10+10)
CombinedIteratorSeek/range-key=true/batch=true-16    31.7µs ± 7%  12.2µs ± 1%  -61.57%  (p=0.000 n=10+9)
```
The benefit for CombinedIteratorSeek/range-key=false is noise: the
interleaving iterator is never …
> internal/keyspan: avoid unnecessarily re-seeking keyspan iter

- internal/keyspan/interleaving_iter.go
- testdata/rangekeys
The interleaving iterator SeekGE optimization added in 04f9100 attempted to use
trySeekUsingNext=true to avoid a key comparison, but it was based on faulty
logic. The span previously stored in i.span might not be the one previously
returned to the user if the *pebble.Iterator had to step the interleaving
iterator to check for a coincident point key.
Fixes #1850.
> internal/keyspan: fix interleaving SeekGE optimization

- compaction.go
- compaction_iter.go
- testdata/compaction_iter
- testdata/compaction_read_triggered
**compaction: avoid compactionIter key comparison when possible**
The compaction iterator performs a key-equality check in order to determine the
active snapshot stripe. The compaction iterator reads keys in the order defined
over InternalKeys: ascending by user key, followed by descending by trailer.
Identical InternalKeys are prohibited.
This patch introduces an optimization to the compaction iterator that takes
advantage of the sorted nature of incoming keys. If a key has a trailer greater
than or equal to the previous key's trailer, it necessarily must have a new
user key. In this case the compaction iterator skips the key comparison and
begins the new snapshot stripe.
In a database receiving randomly distributed writes, this fast path should
trigger 50% of the time. However, keys at …
> compaction: add a couple microoptimizations

- internal/keyspan/interleaving_iter.go
- iterator.go
- testdata/indexed_batch_mutation
The interleaving iterator SeekGE optimization added in 04f9100 had a bug in its
interaction with SetOptions calls on an indexed batch iterator. When SetOptions
is called on an iterator over an indexed batch, it refreshes its view of the
batch. The refresh of the batch's view may change the state of range keys,
including the span that the interleaving iterator is positioned over.
Previously, the SeekGE optimization would improperly return this existing,
possibly-outdated span.
Now, SetOptions invalidates the interleaving iterator position to disable the
SeekGE optimization, just like it does for other seek optimizations.
Informs cockroachdb/cockroach#85660.
> db: fix keyspan SeekGE optimization with indexed batch

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- db.go
- ingest_test.go
- internal/manifest/version.go
- level_iter.go
- range_keys_test.go
- table_stats.go
- testdata/compaction_tombstones
- testdata/ingest
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
- testdata/range_del
- testdata/rangekeys
- testdata/table_stats
Previously, the lazy combined iterator always switched to combined iteration
when it observed a file for which `m.HasRangeKeys` was true. This change tweaks
the table stats to record the number of `RangeKeySets` within a file. Now, if
table stats have been calculated for a file and the lazy combined iterator
observes it has no `RangeKeySet`s, the lazy combined iterator will NOT trigger
a switch.
In Cockroach, this is expected to help with snapshot ingested RANGEKEYDELs.
Cockroach lays both a RANGEDEL and RANGEKEYDEL across a range's snapshot
sstable. Previously, iterating onto this sstable would unconditionally trigger
a switch to combined iteration.
Additionally, fix a bug where a combined iterator that was non-lazy due to
batch or memtable range keys was incorrectly recorded as lazy. …
> db: only switch to combined iteration on RangeKeySet keys

- internal/keyspan/defragment.go
- internal/keyspan/fragmenter.go
- internal/keyspan/merging_iter.go
- internal/keyspan/span.go
- internal/rangekey/coalesce.go
- iterator.go
- range_keys.go
- sstable/block.go
- table_stats.go
During iteration over range keys, a stack of keyspan.FragmentIterators handle
various parts of range-key iteration: fragmenting, shadowing and defragmenting.
Previously, the keyspan.Span and keyspan.FragmentIterator strictly specified
the order of keys within a Span: always by Trailer, descending.
This created some unfortunate gymnastics during range-key iteration:
- To resolve shadowing (or "coalesce" range keys), the keyspan.Transform
invoked by the keyspan.MergingIter) would sort the keys by suffix, and
re-sort by Trailer.
- To determine whether or not two range key spans should be defragmented into a
single Span, the range-key iterator would copy the keys into a buffer to sort
by suffix.
- Lastly, when the range keys were surfaced to the *pebble.Iterator, they'd
once again be sorted …
> internal/rangekey: sort keys by suffix once during iteration

- sstable/block_property.go
Add an Init method to BlockIntervalFilter, allowing users to avoid allocations
by pooling or allocating within a larger structure.
> sstable: add BlockIntervalFilter.Init

- data_test.go
- db.go
- external_iterator.go
- internal/keyspan/interleaving_iter_test.go
- internal/metamorphic/ops.go
- internal/metamorphic/retryable.go
- iterator.go
- range_keys.go
- testdata/external_iterator
- testdata/indexed_batch_mutation
- testdata/rangekeys
Add a new Iterator method RangeKeyChanged() that indicates whether the state
of range keys changed in the most recent iterator positioning operation. If
this new method returns false, the user is guaranteed that the
previously-returned range key buffers returned from RangeBounds and RangeKeys
are still valid.
Additionally, use the SpanChanged hook to flip a flag on the range iterator
range key state, indicating that a new span was encountered. This allows the
iterator to avoid copying the range key state if the current range key has not
changed. This commit removes setRangeKey and always copies range key buffers to
Iterator-owned buffers in order to provide the guarantee that the buffers
returned by RangeKeyBounds and RangeKeys will be stable until the iterator's
range key changes.
Most …
> db: add Iterator.RangeKeyChanged

- db.go
- external_iterator.go
- internal/keyspan/bounded.go
- internal/keyspan/bounded_test.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/testdata/bounded_iter
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- iterator.go
- iterator_test.go
- range_keys.go
Enforce iterator bounds beneath defragmentation to avoid unnecessary range-key
block loads.
```
name                             old time/op    new time/op    delta
CombinedIteratorSeek_Bounded-10    2.77ms ± 1%    0.05ms ± 2%  -98.23%  (p=0.000 n=10+20)
name                             old alloc/op   new alloc/op   delta
CombinedIteratorSeek_Bounded-10    1.79MB ± 0%    0.02MB ± 0%  -98.89%  (p=0.000 n=10+19)
name                             old allocs/op  new allocs/op  delta
CombinedIteratorSeek_Bounded-10     17.0k ± 0%      0.1k ± 0%  -99.28%  (p=0.000 n=10+20)
```
Close #1861.
> internal/rangekey: enforce iterator bounds beneath defragmentation

- compaction_test.go
This test has become increasingly flaky on Windows.
Skip the test on Windows.
> db: skip TestCompactFlushQueuedMemTableAndFlushMetrics on windows

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- format_major_version.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/version.go
Currently, the boolean field `FileMetadata.Compcting` tracks the
compaction status of a file. Given the boolean nature of the field, a
file is modeled as either compacting or not compacting.
The compaction state of a file can also be modeled as a state machine. A
file starts in a "not-compacting" state, and typically transitions into
a "compacting" state when selected by the compaction picker. Compacted
files typically transition into a terminal "compacted" state, after
which the file is removed from the LSM as it becomes obsolete. A notable
exception to the terminal state is for move-compactions, where a file
becomes eligible for subsequent compactions after it has been moved,
transitioning back into a "not-compacting" state. There also exists a
pre-compaction state, where a file has …
> manifest: make `FileMetadata.Compacting` an enum

- internal/metamorphic/generator.go
Update `(generator).randPrefixToWrite` to use a pointer receiver, to
keep it consistent with the other methods.
> metamorphic: use pointer receiver

- compaction.go
- compaction_iter_test.go
- compaction_test.go
- data_test.go
- db.go
- external_iterator.go
- internal/base/comparer.go
- internal/keyspan/bounded.go
- internal/keyspan/bounded_test.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/keyspan/testdata/bounded_iter
- internal/keyspan/testdata/interleaving_iter
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- internal/testkeys/testkeys.go
- iterator.go
- iterator_test.go
- range_keys.go
- testdata/rangekeys
During prefix iteration, avoid defragmenting range keys beyond the bounds of
the prefix. To preserve determinism, also truncated returned range keys to the
prefix bounds.
This requires the introduction of a new ImmediateSuccessor function on the
Comparer.
```
name                           old time/op    new time/op    delta
CombinedIteratorSeekPrefix-10    2.53ms ± 3%    0.10ms ± 2%  -96.19%  (p=0.000 n=10+10)
name                           old alloc/op   new alloc/op   delta
CombinedIteratorSeekPrefix-10    1.78MB ± 0%    0.05MB ± 0%  -96.92%  (p=0.000 n=9+9)
name                           old allocs/op  new allocs/op  delta
CombinedIteratorSeekPrefix-10     17.0k ± 0%      0.4k ± 0%  -97.93%  (p=0.000 n=10+10)
```
Fix #1874.
> db: avoid defragmenting beyond prefix bounds during prefix iteration

- db.go
- metrics.go
- range_keys_test.go
- table_stats.go
- testdata/rangekeys
Add a metric recording the approximate number of internal range key sets that
exist within the database. It's calculated through an annotation on the
range-key only level metadata b-trees. It's approximate since it excludes
memtable range key sets and any tables for which table stats have not yet been
loaded. I intend to export this as a time-series metric.
Informs #1848.
> db: add Metrics.Keys.RangeKeySetsCount

- internal/keyspan/interleaving_iter.go
- testdata/rangekeys
Fix a bug where an InitSeekGE with a prefix failed to record that the
interleaving iterator was in prefix mode, allowing incorrect use of the
existing, potentially fragmented span stored on the iterator.
Fix #1878.
> internal/keyspan: fix prefixed InterleavingIter.InitSeekGE

- internal/keyspan/bounded.go
- iterator.go
- testdata/iterator
Previously, when Next was called on an already exhausted prefix iterator, the
iterator stack would still step the internal iterator. If a level was removed
from the merging iterator because the matching file returned nil due to bloom
filter exclusion, the iterator could miss a range key and trigger a switch to
combined iteration using a later key.
This would provide an inconsistent view of the range keys when seeking the
range key iterator. The SeekGE(k) would unexpectedly discover range keys with
start keys <k. This is an issue during prefix iteration, because the bounded
keyspan iterator only guarantees a consistent view of prefix iteration for
forward iteration.
Fix #1881.
> db: handle Next on exhausted prefix iterator

- sstable/block.go
- sstable/reader.go
Pool range key fragment iterators to avoid allocations every time a table's
range keys are read. Ideally we'd pool all *fragmentBlockIters, but currently
some code paths call Close twice on rangedel fragmentBlockIters.
```
name                                                                    old time/op    new time/op    delta
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=0-10       3.79µs ± 1%    3.85µs ± 3%     ~     (p=0.421 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=1-10       6.30µs ± 1%    6.11µs ± 1%   -2.96%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=1/valueSize=8/numRangeKeys=100-10     56.3µs ± 0%    55.0µs ± 1%   -2.30%  (p=0.008 n=5+5)
MVCCGet_Pebble/batch=false/versions=10/valueSize=8/numRangeKeys=0-10      4.26µs ± 1% …
```
> sstable: pool range key fragment iterators

- batch_test.go
- iterator.go
- testdata/indexed_batch_mutation
- testdata/rangekeys
The Iterator's RangeKeyChanged method returns a boolean signifying whether the
range keys at the current iterator position changed during the most recent
positioning operation. Seeking to the same range key as the previous iterator
position leaves RangeKeyChanged() as false, an optimization for repeated seeks
in the same region of the keyspace.
However, when an iterator is reused, the client may have forgotten the previous
iterator position and have the expectation that the first seek will return
RangeKeyChanged()->true if it lands on a range key.
This commit changes the semantics of SetOptions to clear the existing range key
state so that a subsequent seek to the same range key will return
RangeKeyChanged()->true.
Additionally, improve unit test coverage for some of these edge cases …
> db: invalidate RangeKeyChanged state in SetOptions

- internal/keyspan/interleaving_iter.go
- iterator.go
- range_keys_test.go
- sstable/reader.go
- testdata/rangekeys
When SeekPrefixGE is called on the interleaving iterator, if the seeked key
falls within the bounds of the current span, we avoid seeking the keyspan
iterator. To maintain deterministic bounds, we must only reuse the span if the
current span covers the entire prefix keyspace. Previously, we'd reuse the
current span as long as its start bound was ≤ the seek key. This allowed for
nondeterminism in the range key bounds.
> internal/keyspan: fix SeekPrefixGE span reuse nondeterminism

- iterator.go
- testdata/rangekeys
The change in #1888 was an incomplete fix for preventing range key state from
leaking across a SetOptions call. Specifically, it still permitted the use of
no-op seek optimizations. Take a more conservative stance of invalidating the
iterator in SetOptions calls with initialized range key iterator stacks.
It's possible this could be optimized to preserve the optimization in some
cases, but given the bugs in this area and stability, we should take the more
conservative approach.
Fix #1890.
> db: invalidate iterator in SetOptions if range keys are present

- internal/metamorphic/generator.go
The set bounds operation relies on the iters previous bounds being set
to determine if the new bounds should overlap with the previous. Not
having the bounds set may generate overlap even when the generator
is trying to create bounds with no overlap.
> metamorphic: set iters last bounds on iter creation

- compaction.go
- db.go
- flushable.go
- internal/metamorphic/options.go
- options.go
- options_test.go
- range_del_test.go
- testdata/metrics
Add a new FlushDelayRangeKey option to force the flush of a memtable with range
keys within some duration. Range keys within the memtable can slow iteration,
especially when range keys are sparse, because they prevent lazy-combined
iteration.
Also, rename the existing Experimental.DeleteRangeFlushDelay option to
FlushDelayDeleteRange. It's been used in production for two years and is no longer
experimental. Also renaming it keeps the related FlushDelayRangeKey and FlushDelayDeleteRange options adjacent.
Close #1857.
> db: add option to force memtable flush of range keys

- internal/metamorphic/generator.go
- internal/metamorphic/ops.go
- internal/metamorphic/parser.go
- internal/metamorphic/parser_test.go
- internal/metamorphic/retryable.go
Improve the test coverage of the metamorphic tests around SetOptions by
allowing SetOptions to modify block-property filters, and by improving the
probability of its fast paths.
Informs #1885.
> internal/metamorphic: improve SetOptions coverage

- internal/keyspan/bounded.go
- internal/keyspan/testdata/bounded_iter
- range_keys.go
- range_keys_test.go
- testdata/rangekeys
In #1875, the range key iterator stack was modified to avoid defragmenting
beyond the bounds of a prefix. During the switch to lazy combined iteration,
this could induce an invariant violation under very particular circumstances.
See the extended comment added to the range keys datadriven test case.
This violation is fixed in two places in this commit. The lazy combined
iterator will avoid switching to combined iteration if encountered range keys
fall wholly outside the prefix's bounds. Additionally, the bounded keyspan
iterator will enforce prefix bounds on both start and end bounds, rather than
just the direction of iteration. This redundancy is performed out of an
abundance of caution, because prefix iterator bounds enforcement has
been a frequent source of range key bugs since it's …
> db: fix prefix iteration invariant violation

- compaction.go
- db.go
- range_del_test.go
Fix a race between DB.Close and WAL rotation. WAL rotation drops the database
mutex several times. If the database was closed in one of these gaps, the WAL
rotation goroutine would not notice, instead panicking on an inconsistent
refcount for a memtable.
This change fixes the race by acquiring DB.commit.mu in Close. WAL rotation
requires both the commit pipeline and the global DB mutex to be held, and it
does not drop the commit pipeline mutex at any point. This provides
synchronization between Close and WAL rotation.
This race was surfaced by the metamorphic tests after #1867's inclusion of the
FlushDelayDeleteRange and FlushDelayRangeKey options as metamorphic parameters
made it more likely.
Close #1728.
Inform #1893.
> db: fix Close race with WAL rotation

- data_test.go
- internal/metamorphic/ops.go
- iterator_test.go
- options.go
- range_keys.go
- range_keys_test.go
- testdata/indexed_batch_mutation
The RangeKeyMasking.Filter option previously took a BlockPropertyFilterMask
implementation directly. Because BlockPropertyFilterMasks are mutable types,
this was easy to misuse when combined with Clone. If the Clone operation didn't
provide its own IterOptions, the cloned iterator would adopt the clonee's
BlockPropertyFilterMask. The two iterators would interfere with each other as
they iterate.
This was surfaced by the metamorphic tests, which currently never supplies
IterOptions to Clone (#1904). Cockroach already supplies IterOptions to Clone
and is unaffected.
Informs #1904.
Closes #1893.
> db: make RangeKeyMasking.Filter a constructor function

- internal/metamorphic/generator.go
- internal/metamorphic/generator_test.go
A call to Iterator.SetOptions leaves an iterator in an undefined position. The
Iterator contract requires that the caller reposition the iterator using an
absolute positioning method (eg, SeekGE, SeekLT, etc). The logic to perform
this repositioning in the metamorphic tests was faulty. It performed a random
absolute positioning operation on a random iterator rather than the iterator
that was just configured with SetOptions.
Fix #1911.
> metamorphic: reposition iterator after SetOptions

- external_iterator.go
- external_iterator_test.go
- iterator.go
- testdata/external_iterator
- testdata/simple_level_iter
Currently, we create a new merging iterator level for each file
passed into NewExternalIter. This is unnecessary for most use-cases
of creating ExternalIters around lots of sstables, as we can externally
guarantee that many of those sstables won't have overlapping points
with each other. We can have the caller pass this knowledge
by specifying a [][]sstable.ReadableFile where each sub-slice
obeys level invariants for files within it, and is also already
sorted by user keys.
This change makes the interface change to allow for the above
optimization, and also adds a `simpleLevelIter` that implements
forward iteration within a single "level". For files that don't
contain range deletes, we shove all the point iters into one
`simpleLevelIter`, greatly reducing merging iterator levels
and …
> *: add simpleLevelIterator, reduce merging levels in external iter

- internal/metamorphic/generator.go
In #1912, I forgot to update iterSeekLTWithLimit to actually use the iterID
parameter, rather than generating a random iterID.
Fix #1919.
> metamorphic: fix iterSeekLTWithlimit

- compaction.go
- db.go
- external_iterator.go
- get_iter_test.go
- internal/keyspan/defragment.go
- internal/keyspan/defragment_test.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/span.go
- internal/rangekey/coalesce.go
- iterator.go
- iterator_test.go
- range_keys.go
- table_stats.go
- table_stats_test.go
Use base.Equal for equality comparisons in more places. Equal(a,b) is faster
than Compare(a,b)==0. Additionally, embed the Comparer directly into the
Iterator struct for better cache locality and to avoid the additional pointer
indirection.
Informs #1819.
Informs cockroachdb/cockroach#82559.
```
name                                                                     old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-24           6.80µs ± 1%    6.72µs ± 2%    ~     (p=0.165 n=5+10)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=1-24           14.1µs ± 1%    14.0µs ± 2%    ~     (p=0.107 n=5+10)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=100-24          154µs ± 2%     152µs ± 2%    ~     (p=0.075 n=5+10) …
```
> *: use Equal for more efficient equality comparisons

- external_iterator.go
- external_iterator_test.go
In #1905 we added a simpleLevelIterator to allow for reductions
in mergingIter levels in the External iterator if the caller
can guarantee that point keys won't overlap between some
external SSTs. However, that iterator did not propagate errors.
This change fixes that.
> *: fix error handling in simpleLevelIter

- compaction.go
- compaction_iter_test.go
- data_test.go
- db.go
- error_iter.go
- external_iterator.go
- get_iter_test.go
- internal.go
- internal/base/iterator.go
- internal/base/iterator_test.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- iterator.go
- iterator_test.go
- level_iter.go
- level_iter_test.go
- merging_iter.go
- merging_iter_test.go
- range_keys.go
- sstable/block_property_test.go
- sstable/data_test.go
- sstable/reader.go
- sstable/reader_test.go
- table_cache.go
Replace the base.InternalIteratorWithStats interface with logic to propagate a
pointer to a shared *InternalIteratorStats down the iterator tree during
iterator construction. This reduces the cost of collecting stats, which no
longer needs to descend the iterator tree summing stats as it goes.
Informs cockroachdb/cockroach#86083.
Informs cockroachdb/cockroach#82559.
Edit: Eh, I think these benchmark results are somewhat fake because they're not consistently reproducing. There seems to be a lot of variance in these benchmarks.
```
name                                                                     old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-24           6.80µs ± 1%    6.58µs ± 1%  -3.16%  (p=0.008 n=5+5) …
```
> *: propagate pointer to InternalIteratorStats

- internal/metamorphic/generator.go
- internal/metamorphic/key_manager.go
- internal/metamorphic/key_manager_test.go
This pr increases the probablity of SeekPrefixGE calls which are in
range, and also makes it likely that the key passed to the
SeekPrefixGE function is readable by the iterator.
Currently, we only increase the probablity of valid SeekPrefixGE
calls for iterators created on the DB.
> metamorphic: increase probability of valid SeekPrefixGE calls

- internal/metamorphic/retryable.go
Prior to this pr, the metamorphic tests didn't test range key
changed when the block property filter was set. To accommodate
block property filtering non-determinism in the metamorphic tests,
one positioning op on the retryable iter can result in more than
one positioning op internally. This makes
retryableIter.iter.RangeKeyChanged unreliable.
However, if every single positioning op returns RangeKeyChanged=false,
then we can be certain that the retryableIter.RangeKeyChanged is also
false. This pr tests the RangeKeyChanged=false even when block property
filters are set.
> metamorphic: test RangeKeyChanged=false in the metamorphic tests

- external_iterator_test.go
In #1737, we added some intricate interactions around
block property filters, and added the contractual requirement
that all sstable iterators return MaybeFilteredKeys() == true
after a positioning operation that led to filtered keys due to
BPFs. We want to build more confidence around that function
obeying that contract after seek optimizations, so this change
adds a randomized test that does repeated seeks (incl. some
after monotonic bound changes and with trySeekUsingNext), and
ensures `MaybeFilteredKeys()` returns true after any skipped
keys.
I would have put this test in the sstable package, except
it'd cause a cyclical dependency between it and
`internal.testkeys.blockprops` so I moved it to the outer package.
Fixes #1817.
> *: Add random test for iterator seek - BlockPropertyFilters interaction

- internal/metamorphic/generator.go
- internal/metamorphic/history.go
- internal/metamorphic/history_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/ops.go
- internal/metamorphic/options.go
- internal/metamorphic/parser.go
- internal/metamorphic/test.go
- internal/metamorphic/testdata/reorder_history
Add a new test option that controls the number of concurrent execution
threads to use for running operations. To maintain determinism,
synchronization points are added at the level of objects: Each operation
defines the set of objects that it must synchronize on. Before
executing, operations block on completion of all operations with earlier
operation indexes that synchronize on any of the same objects.
The synchronization described above creates a strict partial order to
the operations, allowing operations on independent iterators and
independent batches to run concurrently. Notably this level of
synchronization does /not/ permit concurrent commits to the database,
since all operations that mutate the database state synchronize on the
database object. Future work may relax this …
> metamorphic: add limited concurrency

- internal/keyspan/merging_iter.go
This bug crept in during a refactor. `m.cmp` is a convenience method defined on
the MergingIter which calls through to `m.heap.cmp`. Passing `m.cmp`, the
method on the merging iterator, was forcing an allocation during Transform calls.
```
name                           old time/op    new time/op    delta
CombinedIteratorSeekPrefix-10    91.1µs ± 0%    89.1µs ± 1%   -2.16%  (p=0.016 n=4+5)
name                           old alloc/op   new alloc/op   delta
CombinedIteratorSeekPrefix-10    2.25kB ± 0%    0.57kB ± 0%  -74.82%  (p=0.008 n=5+5)
name                           old allocs/op  new allocs/op  delta
CombinedIteratorSeekPrefix-10       140 ± 0%        35 ± 0%  -75.00%  (p=0.008 n=5+5)
```
> internal/keyspan: remove unnecessary allocations

- db.go
- internal/metamorphic/options.go
- options.go
In 20% of random runs, disable lazy-combined iteration.
> metamorphic: add test option to disable lazy-combined iteration

- batch.go
- compaction.go
- db.go
- get_iter.go
- internal/base/internal.go
- internal/keyspan/merging_iter.go
- iterator.go
- level_checker.go
- merging_iter.go
Previously, visibility of batch point keys was enforced within the batch iterator. This commit moves this visibility enforcement into the merging iterator, alongside the visibility enforcement of committed keys. Span keys (eg, range deletions and range keys) are still subject to visibility filtering when the batch iterator is constructed, because it's necessary to process all these spans to fragment them appropriately.
This change addresses the pathological behavior observed in cockroachdb/cockroach#87277: filtering keys within leaf iterators can force the leaf iterators to iterate through more keys than necessary. If many mutations are made to a batch since the iterator was opened, the batch iterator may need to iterate over many entries before finding a visible key. This iteration may …
> db: enforce batch point visibility in the merging iterator

- iterator.go
- testdata/rangekeys
Previously, if a call to SetBounds hit the no-op optimization because the bounds were identical, a subsequent seek that discovered the same range key as the last valid iterator position would incorrectly report RangeKeyChanged() as false.
Fix #1947.
> db: ensure RangeKeyChanged is true after no-op SetBounds

- iterator.go
- testdata/rangekeys
22.2 backport of #1948
----
Previously, if a call to SetBounds hit the no-op optimization because the bounds were identical, a subsequent seek that discovered the same range key as the last valid iterator position would incorrectly report RangeKeyChanged() as false.
Fix #1947.
> crl-release-22.2: db: ensure RangeKeyChanged is true after no-op SetBounds

- iterator_test.go
Setting an Option after the DB has been initialized can lead to data races. Since the newTestKeysDatabase funciton is only called from one location, we set the Logger inside that function.
> db: fix opts.Logger race in TestSetOptionsEquivalence

- docs/rfcs/20211018_range_keys.md
- iterator.go
> docs: draft design sketch for ranged keys

- iterator.go
- testdata/rangekeys
Previously, RangeKeyChanged could report a false negative when an iterator hit a no-op seek optimization. These seek optimizations avoid repositioning the iterator in cases of repeated, monotonically shifting seek keys. These optimizations reuse the current iterator state for the next position.
If the previous iterator operation was a no-op SetOptions or SetBounds call and the last seek operation resulted in RangeKeyChanged()=false the iterator could falsely preserve the RangeKeyChanged()=false state after the no-op seek operation. The first seek call to return a range key after a SetOptions or SetBounds call must return RangeKeyChanged()=true.
Close #1950.
Close #1952.
> db: fix interaction between no-op optimizations and RangeKeyChanged

- iterator.go
- testdata/rangekeys
22.2 backport of #1953.
----
Previously, RangeKeyChanged could report a false negative when an iterator hit a no-op seek optimization. These seek optimizations avoid repositioning the iterator in cases of repeated, monotonically shifting seek keys. These optimizations reuse the current iterator state for the next position.
If the previous iterator operation was a no-op SetOptions or SetBounds call and the last seek operation resulted in RangeKeyChanged()=false the iterator could falsely preserve the RangeKeyChanged()=false state after the no-op seek operation. The first seek call to return a range key after a SetOptions or SetBounds call must return RangeKeyChanged()=true.
Close #1950.
Close #1952.
> crl-release-22.2: db: fix interaction between no-op optimizations and RangeKeyChanged

- docs/index.html
In #1822 we began zeroing the entirety of the iterAlloc structure to avoid
accidental reuse bugs. This had a noticeable impact on read-heavy YCSB
workloads. Add an annotation to the benchmarks explaining this change.
> docs: add benchmark annotation for #1822

- internal/metamorphic/ops.go
Previously, a Clone operation only synchronized with the Batch underlying the cloned iterator if refreshBatch=true. This was insufficient, because iterator construction must read shared state on the Batch to avoid refragmenting range deletions and range keys.
Close #1964.
> metamorphic: always synchronize Clone on underlying Batch

- docs/index.html
The previous date was off by 2 years.
> docs: fix date for struct zeroing annotation

- external_iterator.go
- external_iterator_test.go
- internal/base/iterator.go
- iterator.go
- sstable/block_property_test.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/table_test.go
- sstable/testdata/readerstats/iter
- testdata/external_iterator
- testdata/iterator_stats
- testdata/level_iter_seek
- testdata/merging_iter
- testdata/rangekeys
**sstable: include more blocks' stats in BlockBytes**
Previously, BlockBytes and BlockBytesInCache only included data blocks
and sometimes the top-level index block. Now it always includes the
top-level index block, the first-level index block and the filter block.
This is motivated by a latter commit that needs the inclusion of index
blocks for a test case that illustrates the effectiveness of an
optimization.
**db: add ExternalIter_NonOverlapping_SeekNextScan benchmark**
Add a new benchmark that illustrates the pathological behavior of an external
iterator that must repeatedly seek into exhausted sstables.
**db: enable TrySeekUsingNext after Next in external iters**
Enable the TrySeekUsingNext optimization in another case, specifically
for external iterators. Previously this …
> db: enable TrySeekUsingNext after Next in external iters

- iterator_test.go
The test was comparing keys suffixed with timestamps using bytes.Compare which lead to erroneous results.
Fixes: #1973
> db: fix TestRangeKeyMaskingRandomized

- external_iterator.go
- external_iterator_test.go
- internal/base/iterator.go
- iterator.go
- sstable/block_property_test.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/table_test.go
- sstable/testdata/readerstats/iter
- testdata/external_iterator
- testdata/iter_histories/range_key_masking
- testdata/iterator_stats
- testdata/level_iter_seek
- testdata/merging_iter
Cockroach 22.2 backport of #1960.
----
**sstable: include more blocks' stats in BlockBytes**
Previously, BlockBytes and BlockBytesInCache only included data blocks
and sometimes the top-level index block. Now it always includes the
top-level index block, the first-level index block and the filter block.
This is motivated by a latter commit that needs the inclusion of index
blocks for a test case that illustrates the effectiveness of an
optimization.
**db: add ExternalIter_NonOverlapping_SeekNextScan benchmark**
Add a new benchmark that illustrates the pathological behavior of an external
iterator that must repeatedly seek into exhausted sstables.
**db: enable TrySeekUsingNext after Next in external iters**
Enable the TrySeekUsingNext optimization in another case, specifically
for external …
> crl-release-22.2: db: enable TrySeekUsingNext after Next in external iters

- iterator_histories_test.go
- sstable/reader.go
- testdata/iter_histories/iter_optimizations
The sstable iterator has an optimization for when iterator bounds are
moved monotonically forward or backward. The first seek after the bounds
adjustment can reuse the existing iterator position to avoid a more
expensive full seek.
In iterators over sstables with two-level indexes, this optimization
could interact with block-property filters, improperly allowing the
second seek after the bounds adjustment to also reuse the existing
iterator position. If the second seek key was smaller than the first
seek key, the iterator would skip keys.
Informs https://github.com/cockroachdb/pebble/issues/1963.
Informs https://github.com/cockroachdb/cockroach/issues/88296.
> sstable: fix interaction between bpf and monotonic bounds optimization

- iterator_histories_test.go
- sstable/reader.go
- testdata/iter_histories/iter_optimizations
Cockroach 22.2 backport of #1970.
----
The sstable iterator has an optimization for when iterator bounds are moved monotonically forward or backward. The first seek after the bounds adjustment can reuse the existing iterator position to avoid a more expensive full seek.
In iterators over sstables with two-level indexes, this optimization could interact with block-property filters, improperly allowing the second seek after the bounds adjustment to also reuse the existing iterator position. If the second seek key was smaller than the first seek key, the iterator would skip keys.
Informs #1963.
Informs cockroachdb/cockroach#88296.
> crl-release-22.2: sstable: fix interaction between bpf and monotonic bounds optimization

- internal/testkeys/blockprop/blockprop.go
- iterator_histories_test.go
- sstable/reader.go
- testdata/iter_histories/iter_optimizations
Cockroach 22.1 backport of #1970. In order to carry over the tests, I brought over the `internal/testkeys/blockprop` package and the new `TestIterHistories` datadriven test.
----
The sstable iterator has an optimization for when iterator bounds are moved monotonically forward or backward. The first seek after the bounds adjustment can reuse the existing iterator position to avoid a more expensive full seek.
In iterators over sstables with two-level indexes, this optimization could interact with block-property filters, improperly allowing the second seek after the bounds adjustment to also reuse the existing iterator position. If the second seek key was smaller than the first seek key, the iterator would skip keys.
Informs #1963.
Informs cockroachdb/cockroach#88296.
> crl-release-22.1: sstable: fix interaction between bpf and monotonic bounds optimization

- iterator.go
- testdata/iter_histories/with_limit
Fix a bug whereby RangeKeyChanged would sometimes return false for an
iterator position that held range keys immediately after an at-limit
position. The documented interface dictates that after any !Valid()
iterator position, an iterator position that holds range keys should
return RangeKeyChanged()=true:
> Invalid iterator positions are considered to not hold range keys,
> meaning that if an iterator steps from an IterExhausted or IterAtLimit
> position onto a position with a range key, RangeKeyChanged will yield
> true.
Previously every iterator positioning operation would reset
`i.rangeKey.updated=false` before executing. Now, it's initialized to
represent the current internal state of the range keys held in
`i.rangeKey`. If there exists a range key at the current internal
iterator …
> db: fix RangeKeyChanged and -WithLimit interaction 

- iterator.go
- testdata/iter_histories/with_limit
Cockroach 22.2 backport of #1967.
----
Fix a bug whereby RangeKeyChanged would sometimes return false for an iterator position that held range keys immediately after an at-limit position. The documented interface dictates that after any !Valid() iterator position, an iterator position that holds range keys should return RangeKeyChanged()=true:
> Invalid iterator positions are considered to not hold range keys,
> meaning that if an iterator steps from an IterExhausted or IterAtLimit
> position onto a position with a range key, RangeKeyChanged will yield
> true.
Previously every iterator positioning operation would reset `i.rangeKey.updated=false` before executing. Now, it's initialized to represent the current internal state of the range keys held in `i.rangeKey`. If there exists a range …
> crl-release-22.2: db: fix RangeKeyChanged and -WithLimit interaction

- sstable/reader.go
Correct the comment that described the bug fix made in #1970.
> sstable: correct comment describing boundsCmp case

- data_test.go
- iterator.go
- testdata/compaction_delete_only_hints
- testdata/external_iterator
- testdata/ingest
- testdata/iter_histories/clone
- testdata/iter_histories/range_key_changed
- testdata/iter_histories/set_options
- testdata/iterator
- testdata/iterator_block_interval_filter
- testdata/iterator_bounds_lifetimes
- testdata/iterator_next_prev
- testdata/iterator_read_sampling
- testdata/iterator_seek_opt
- testdata/iterator_seek_opt_errors
- testdata/iterator_stats
- testdata/iterator_table_filter
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
- testdata/range_del
- testdata/read_compaction_queue
- testdata/singledel_manual_compaction
The recent bug fix in #1967 introduced a new bug when switching from iteration over range keys to iteration over only point keys. If the iterator was positioned over a range key before the swtich to point-only iteration, the first seek after SetOptions would improperly return RangeKeyChanged()=true, when the contract dictates that such a position must return RangeKeyChnaged()=false.
Fix #1980.
> db: always return RangeKeyChanged()=false when range keys disabled

- data_test.go
- iterator.go
- testdata/compaction_delete_only_hints
- testdata/external_iterator
- testdata/ingest
- testdata/iter_histories/clone
- testdata/iter_histories/range_key_changed
- testdata/iter_histories/set_options
- testdata/iterator
- testdata/iterator_block_interval_filter
- testdata/iterator_bounds_lifetimes
- testdata/iterator_next_prev
- testdata/iterator_read_sampling
- testdata/iterator_seek_opt
- testdata/iterator_seek_opt_errors
- testdata/iterator_stats
- testdata/iterator_table_filter
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
- testdata/range_del
- testdata/read_compaction_queue
- testdata/singledel_manual_compaction
Cockroach 22.2 backport of #1981.
----
The recent bug fix in https://github.com/cockroachdb/pebble/pull/1967 introduced a new bug when switching from iteration over range keys to iteration over only point keys. If the iterator was positioned over a range key before the swtich to point-only iteration, the first seek after SetOptions would improperly return RangeKeyChanged()=true, when the contract dictates that such a position must return RangeKeyChanged()=false.
Fix https://github.com/cockroachdb/pebble/issues/1980.
> crl-release-22.2: db: always return RangeKeyChanged()=false when range keys disabled

- db.go
- db_test.go
- internal/base/metrics.go
- internal/base/metrics_test.go
- metrics.go
- record/log_writer.go
- record/log_writer_test.go
Move the metrics stored on the `InternalIntervalMetrics` struct to the `Metrics` struct. Moving these metrics will enable multiple clients to get the metrics over an interval. Currently, if two clients interact with `GetInternalIntervalMetrics` one client will reset the other client’s interval. Ex: Client A calls every 5 seconds and Client B calls every 10 seconds. Client B will end up getting metrics at a 5-second interval since `GetInternalIntervalMetrics` resets the interval on each call.
Refactor `GetInternalIntervalMetrics` to use the
`InternalIntervalMetrics`  that have been moved over to `Metrics`. In order to facilitate the calculation of the delta between calls to `GetInternalIntervalMetrics`, `DB.mu.lastIntervalMetrics` has been added. Each call to  `GetInternalIntervalMetrics` …
> metrics: expose InternalIntervalMetrics as cumulative metrics

- batch.go
- data_test.go
- internal/base/iterator.go
- internal/base/iterator_test.go
- internal/batchskl/iterator.go
- internal/batchskl/skl_test.go
- iterator.go
- testdata/iter_histories/iter_optimizations
The change to batch mutation visibility (#1640) began invalidating the
iterator in SetOptions if the iterator was configured to read through an
indexed batch that had been modified. This prevented the
TrySeekUsingNext optimization from triggering when the pebbleBatch's
iterator was reused after a mutation.
This commit restores this optimization, and allows the batch iterator to
perform TrySeekUsingNext optimizations when the batch view has not been
just refreshed.
Relative to HEAD:
```
name                                                  old time/op    new time/op    delta
MVCCBatchPut_Pebble/valueSize=10/batchSize=1-24         7.52µs ± 4%    7.57µs ± 3%      ~     (p=0.690 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100-24       3.81µs ± 9%    1.39µs ± 2%   -63.52%  (p=0.008 …
```
> db: restore TrySeekUsingNext across SetOptions batch refresh

- batch.go
- data_test.go
- internal/base/iterator.go
- internal/base/iterator_test.go
- internal/batchskl/iterator.go
- internal/batchskl/skl_test.go
- iterator.go
- testdata/iter_histories/iter_optimizations
The change to batch mutation visibility began invalidating the iterator in SetOptions if the iterator was configured to read through an indexed batch that had been modified. This prevented the TrySeekUsingNext optimization from triggering when the pebbleBatch's iterator was reused after a mutation.
This commit restores this optimization, and allows the batch iterator to perform TrySeekUsingNext optimizations when the batch view has not been just refreshed.
Relative to HEAD:
```
name                                                  old time/op    new time/op    delta
MVCCBatchPut_Pebble/valueSize=10/batchSize=1-24         7.52µs ± 4%    7.57µs ± 3%      ~     (p=0.690 n=5+5)
MVCCBatchPut_Pebble/valueSize=10/batchSize=100-24       3.81µs ± 9%    1.39µs ± 2%   -63.52%  (p=0.008 n=5+5) …
```
> crl-release-22.2: db: restore TrySeekUsingNext across SetOptions batch refresh

- iterator.go
- testdata/iter_histories/iter_optimizations
In #1987 the existing TrySeekUsingNext optimization was expanded to apply to batch iterators as well. The logic to omit this optimization when the batch was just refreshed was accidentally omitted from SeekPrefixGE.
> db: fix SeekPrefixGE TrySeekUsingNext optimization with batch

- iterator.go
- testdata/iter_histories/iter_optimizations
In #1987 the existing TrySeekUsingNext optimization was expanded to apply to batch iterators as well. The logic to omit this optimization when the batch was just refreshed was accidentally omitted from SeekPrefixGE.
> crl-release-22.2: db: fix SeekPrefixGE TrySeekUsingNext optimization with batch

- iterator.go
- iterator_test.go
Add a Merge method to IteratorStats. I intend to use this in benchmarks to aggregate statistics across iterators to report a custom benchmark metric.
> db: add IteratorStats.Merge

- go.mod
- go.sum
- internal/lint/lint_test.go
> internal/lint: remove support for Go 1.16

- compaction_test.go
- db.go
- db_test.go
- range_del_test.go
- table_stats_test.go
Return an error from DB.Close if the database has open snapshots. This helps ensure clients don't accidentally leak snapshots, which during normal operation prevents dropping any keys older than the snapshot.
Fix #1986.
> db: return error from Close if open snapshots remain

- tool/data_test.go
- tool/db.go
- tool/find.go
- tool/manifest.go
- tool/sstable.go
- tool/util.go
- tool/wal.go
Currently, the tools write directly to `os.{Stdout,Stderr}`, which complicates testing in the case where the command is run from same process running the tests (i.e. from a `testing.T` func).
Adapt the tools to make use of the return values from `(*cobra.Command).{OutOrStdout,OutOrStderr}`. In testing scenarios, the tools can use `SetOut` and `SetErr` to pass in a writer that can intercept anything written to stdout / stderr. In productions scenarios, the tools will emit to the appropriate channel.
Touches cockroachdb/cockroach#89095.
> tool: capture stdout / stderr

- internal/metamorphic/crossversion/crossversion_test.go
In CI, which uses Docker, the binaries we seek to link may be mounted on another volume. It is not possible to link across volumes. In this case, fall back to copying the binary.
> metamorphic/crossversion: use LinkOrCopy

- tool/manifest.go
- tool/testdata/manifest_dump
Support accepting start and/or end bounds of a relevant keyspace in the manifest dump command. Dump skips any version edits that exclusively contain files that fall outside the provided key span.
> tool: add --filter-{start,end} flags

- .gitignore
- Makefile
- scripts/run-crossversion-meta.sh
Add a simple script that takes a series of branch names as arguments, and then runs the cross-version metamorphic tests across the branch's builds.
Informs cockroachdb/cockroach#82544.
> scripts: add script for running the crossversion metamorphic tests

- sstable/testdata/size_estimate
- sstable/write_queue.go
- sstable/writer.go
- sstable/writer_test.go
sizeEstimate is used for two purposes: estimating the total compressed size of the data blocks, and estimating the size of the index block. The commentary around sizeEstimate was incomplete in terms of how these use cases behave, which is now clarified (and the "written", "inflight" and "compressed" terms clarified, since they map to different concepts for the index block case).
Additionally, the size estimation of the total compressed data blocks can count a block as "written" once compression is complete, and does not need to wait until the write. This simplification is made now, so there is no need for the mutex to update sizeEstimate in the writeQueue. The mutex path is kept to allow for easy merging of the pending code for parallel compression. The interface is also simplified to not …
> sstable: adjust sizeEstimate logic for forthcoming value blocks

- internal/metamorphic/options.go
Use the testkeys comparer name so that opening a metamorphic test database with a later version of Pebble does not mistakenly think the comparers are incompatible.
Informs #2018.
> crl-release-21.2: metamorphic: use testkeys comparer

- .github/workflows/ci.yaml
- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
Previously, the logic to copy over data and WAL directories from initial state was subtly broken, resulting in the data directory containing the entirety of the "initial state directory" which has the _OPTIONS, history files and WAL directories. Then we'd copy the WAL logs out of the WAL directory into that directory if it existed. This meant we were always starting from a clean initial state, except if the previous state had a WAL directory and in that case we were starting with just the WALs (and no other initial files).
This change corrects that to copy over the initial data directory to the new data directory, and the initial WAL directory to the new data directory if necessary. If the new test options have a WAL directory, the WALs must be copied from the new data directory to the …
> metamorphic: Copy data/wal dirs from initial state

- format_major_version.go
- format_major_version_test.go
- testdata/event_listener
Fix the FormatPrePebblev1Marked migration to tolerate concurrent file deletions by disabling physical deletion of files removed from the LSM until the migration completes.
Fix #2019.
Informs cockroachdb/cockroach#89755.
Informs cockroachdb/cockroach#83079.
> db: fix FormatPrePebblev1Marked migration

- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
Backport of #2018 
Previously, the logic to copy over data and WAL directories from initial state was subtly broken, resulting in the data directory containing the entirety of the "initial state directory" which has the _OPTIONS, history files and WAL directories. Then we'd copy the WAL logs out of the WAL directory into that directory if it existed. This meant we were always starting from a clean initial state, except if the previous state had a WAL directory and in that case we were starting with just the WALs (and no other initial files).
This change corrects that to copy over the initial data directory to the new data directory, and the initial WAL directory to the new data directory if necessary. If the new test options have a WAL directory, the WALs must be moved from the new data …
> [crl-release-22.1] metamorphic: Copy data/wal dirs from initial state

- .github/workflows/ci.yaml
- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
Backport of #2018 
Previously, the logic to copy over data and WAL directories from initial state was subtly broken, resulting in the data directory containing the entirety of the "initial state directory" which has the _OPTIONS, history files and WAL directories. Then we'd copy the WAL logs out of the WAL directory into that directory if it existed. This meant we were always starting from a clean initial state, except if the previous state had a WAL directory and in that case we were starting with just the WALs (and no other initial files).
This change corrects that to copy over the initial data directory to the new data directory, and the initial WAL directory to the new data directory if necessary. If the new test options have a WAL directory, the WALs must be moved from the new data …
> [crl-release-22.2] metamorphic: Copy data/wal dirs from initial state

- scripts/run-crossversion-meta.sh
When I added the script, I seem to have accidentally only added the explicit test timeout to the STRESS=1 command.
> scripts: default to a 30m timeout in non-stress run-crossversion-meta.sh

- format_major_version.go
- format_major_version_test.go
- testdata/event_listener
Cockroach 22.2 backport of #2020.
----
Fix the FormatPrePebblev1Marked migration to tolerate concurrent file deletions by disabling physical deletion of files removed from the LSM until the migration completes.
Fix #2019.
Informs cockroachdb/cockroach#89755.
Informs cockroachdb/cockroach#83079.
> crl-release-22.2: db: fix FormatPrePebblev1Marked migration

- internal/metamorphic/ops.go
Now that we're using the state of one metamorphic test run as initial state for future metamorphic test runs with the crossversion test, we've noticed an incompatibility if the initial state belonged to a DB with WAL disabled. We'd drop the mutations since the last flush, as those would not be written to a WAL or sstable.
Explicitly do a pre-Close Flush() of the db if DisableWAL is true.
> metamorphic: Flush before close if DisableWAL is true

- internal/metamorphic/options.go
Later versions of Pebble use the data/wal directory in the metamorphic test if we're using a separate WAL directory. Version 21.2 used just the `wal` directory. Simplify logic in later releases by using the same `data/wal` directory if separate WAL directories are intended.
> crl-release-21.2: metamorphic: Use same WAL directory as later versions

- internal/metamorphic/ops.go
Backport of #2028
Now that we're using the state of one metamorphic test run as initial state for future metamorphic test runs with the crossversion test, we've noticed an incompatibility if the initial state belonged to a DB with WAL disabled. We'd drop the mutations since the last flush, as those would not be written to a WAL or sstable.
Explicitly do a pre-Close Flush() of the db if DisableWAL is true.
> [crl-release-22.1] metamorphic: Flush before close if DisableWAL is true

- internal/metamorphic/ops.go
Backport of #2028 
Now that we're using the state of one metamorphic test run as initial state for future metamorphic test runs with the crossversion test, we've noticed an incompatibility if the initial state belonged to a DB with WAL disabled. We'd drop the mutations since the last flush, as those would not be written to a WAL or sstable.
Explicitly do a pre-Close Flush() of the db if DisableWAL is true.
> [crl-release-21.2] metamorphic: Flush before close if DisableWAL is true

- internal/metamorphic/ops.go
Backport of #2028 
Now that we're using the state of one metamorphic test run as initial state for future metamorphic test runs with the crossversion test, we've noticed an incompatibility if the initial state belonged to a DB with WAL disabled. We'd drop the mutations since the last flush, as those would not be written to a WAL or sstable.
Explicitly do a pre-Close Flush() of the db if DisableWAL is true.
> [crl-release-22.2] metamorphic: Flush before close if DisableWAL is true

- compaction_test.go
- db.go
- internal/manifest/version.go
- testdata/compaction_tombstones
A manifest version uses reference counting to ensure that obsolete SSTables are only removed once it is safe to do so (i.e. no iterators or snapshots are open referencing tables in a older manifest version).
In #1771, a new slice of `LevelMetadata` was added to support range keys. A slice already existed for point keys (plus range dels). Currently, when a version's ref count reaches zero, only the files present in the point key `LevelMetadata` slice have their ref counts decremented. If a file also contains range keys, the reference count never becomes zero and the file becomes "zombied", and can never be deleted from disk.
Decrement the ref counts on files present in the range keys `LevelMetadata` slice, allowing the ref counts to be correctly zeroed.
Add regression test to exercise the …
> manifest: unref files with range keys when version refcnt is zero

- compaction_test.go
- db.go
- internal/manifest/version.go
- testdata/compaction_tombstones
Backport of #2022.
---
A manifest version uses reference counting to ensure that obsolete SSTables are only removed once it is safe to do so (i.e. no iterators or snapshots are open referencing tables in a older manifest version).
In #1771, a new slice of `LevelMetadata` was added to support range keys. A slice already existed for point keys (plus range dels). Currently, when a version's ref count reaches zero, only the files present in the point key `LevelMetadata` slice have their ref counts decremented. If a file also contains range keys, the reference count never becomes zero and the file becomes "zombied", and can never be deleted from disk.
Decrement the ref counts on files present in the range keys `LevelMetadata` slice, allowing the ref counts to be correctly zeroed.
Add …
> [crl-release-22.2]: manifest: unref files with range keys when version refcnt is zero

- compaction.go
- compaction_test.go
- db.go
- options.go
This pr modifies the interface of the CPUWorkPermissionGranter to accommodate the change from cpu soft slots to the elastic cpu granter.
The CPUWorkPermissionGranter returns a handle which internally calculates the CPU time spent on the Writer client goroutine.
> db: integrate elastic cpu granter with pebble

- data_test.go
- external_iterator_test.go
- internal/metamorphic/ops.go
- internal/metamorphic/options.go
- internal/testkeys/testkeys.go
- iterator.go
- iterator_histories_test.go
- iterator_test.go
- sstable/block_property_test.go
- sstable/block_property_test_utils.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/testdata/reader_bpf/iter
- testdata/external_iterator
- testdata/iter_histories/iter_optimizations
- testdata/iter_histories/range_key_changed
- testdata/iter_histories/range_key_masking
(backport, cherrypicked from commit fc37e522eff27f4a214c3669137ec27d88893daf)
The current TrySeekUsingNext optimization had a bug where a first SeekGE could set exhaustedBounds=+1, and the next
monotonic twoLevelIterator.SeekGE (without changing bounds) would set exhaustedBounds back to 0, call singleLevelIterator.SeekGE which would immediately return because of i.data.isDataInvalidated() (and TrySeekUsingNext), which would cause the twoLevelIterator to step the top-level index iterator.
This woud break a subsequent optimization when the bounds were monotonically advanced, since the top-level index iterator had been advanced too far. See https://github.com/cockroachdb/pebble/issues/2036#issuecomment-1287290559 for an example of the bug.
Given that both singleLevelIterator and …
> sstable: fix twoLevelIterator SeekGE optimization

- db_test.go
- testdata/event_listener
- version_set.go
- version_set_test.go
In addition to the manifest file size, the logic now waits until the
number of files in subsequent edits exceeds the minimim of the number
of files in the last snapshot and the prospective next snapshot. This
should prevent pathological situations where a large manifest
snapshot exceeds the size threshold, due to which we would rollover
after each edit, resulting in slow flushes and compactions.
Some justification for this change: The primary goal of the
size-based rollover logic is to ensure that when reopening a DB, the
number of edits that need to be replayed on top of the snapshot is
"sane". Rolling over to a new manifest after each edit is not
relevant to that goal. A secondary goal is to keep limited size
amplification of the manifest by reducing how much file metadata we
track for …
> db: adaptive size-based rollover logic for manifest

- ingest_test.go
- vfs/mem_fs.go
Default to Unix semantics in MemFS. The Windows semantics are left as configurable for unit tests that seek to ensure we don't remove open files, when possible.
There are existing cases where we cannot satisfy Windows semantics, and Go does not support opening files with the appropriate `FILE_SHARE_DELETE` permission bit (see golang/go#34681, golang/go#32088). The MemFS's implementation of Windows semantics is useful for ensuring we don't regress in the cases where we can satisfy Windows semantics.
Close #2064.
Informs #1236.
> vfs: default to Unix semantics in MemFS

- internal/metamorphic/crossversion/crossversion_test.go
Use an `-ops` distribution with a low lower bound, so that some versions do very little work before upgrading to the next version. This helps exercise state from version n that survives to versions ≥ n+2.
Informs #2042.
> crossversion: use op-count distribution with low lower bound

- vfs/disk_usage_linux.go
Currently, when computing the total size of a volume in `(defaultFS).GetDiskUsage`, `Bsize` is used to multiply the number of filesystem blocks to arrive at a total size. On Linux, there also exists the `Frsize` parameter, returned from `statfs` / `statvfs`.
For the most part, `Bsize` and `Frsize` are interchangeable on Linux. However, when a Linux container is run with a macOS filesystem mounted into it (for example, when using Docker), a discrepancy in the values can result in an incorrect total size. This can result in issues such as cockroachdb/cockroach#90150, where the denominator of a "percent available" calculation is computed using a larger value of `Bsize`, which results in the overall fraction falling below the allowable threshold for certain operations.
This can be seen with …
> vfs: use `Frsize` for computing total size on Linux

- internal/metamorphic/crossversion/crossversion_test.go
Explicitly set the directory that the subprocess metamorphic test runs should write artifacts to. This is normally unnecessary, but when executing within bazel the subprocesses do not assume the working directory provided to (exec.Cmd).Dir.
Informs cockroachdb/cockroach#83681.
> crossversion: explicitly set artifacts directory

- vfs/disk_usage_linux.go
This is a backport of #2073.
---
Currently, when computing the total size of a volume in `(defaultFS).GetDiskUsage`, `Bsize` is used to multiply the number of filesystem blocks to arrive at a total size. On Linux, there also exists the `Frsize` parameter, returned from `statfs` / `statvfs`.
For the most part, `Bsize` and `Frsize` are interchangeable on Linux. However, when a Linux container is run with a macOS filesystem mounted into it (for example, when using Docker), a discrepancy in the values can result in an incorrect total size. This can result in issues such as cockroachdb/cockroach#90150, where the denominator of a "percent available" calculation is computed using a larger value of `Bsize`, which results in the overall fraction falling below the allowable threshold for certain …
> [crl-release-21.2] vfs: use `Frsize` for computing total size on Linux

- sstable/reader.go
- sstable/reader_test.go
- vfs/disk_usage_linux.go
This is a backport of #2073 and #2071.
---
Currently, when computing the total size of a volume in `(defaultFS).GetDiskUsage`, `Bsize` is used to multiply the number of filesystem blocks to arrive at a total size. On Linux, there also exists the `Frsize` parameter, returned from `statfs` / `statvfs`.
For the most part, `Bsize` and `Frsize` are interchangeable on Linux. However, when a Linux container is run with a macOS filesystem mounted into it (for example, when using Docker), a discrepancy in the values can result in an incorrect total size. This can result in issues such as cockroachdb/cockroach#90150, where the denominator of a "percent available" calculation is computed using a larger value of `Bsize`, which results in the overall fraction falling below the allowable threshold for …
> [crl-release-22.2] vfs: use `Frsize` for computing total size on Linux

- tool/logs/compaction.go
- tool/logs/compaction_test.go
- tool/logs/testdata/compactions
Currently, the compaction log tool emits the sum bytes written to the output level. It is also useful to know the total number of bytes that were input to the compaction in a given interval, along with the number of bytes deleted and moved.
Update the tool to compute the total number of bytes that were present in input tables in each compaction, and track the total number of input bytes in a time interval, along with the number of bytes from tables removed and moved in delete-only and move compactions, respectively.
The updated tool output now resembles the following:
```console
node: 15, store: 15
from: 220906 23:59
to: 220907 00:00
r-amp: NaN
_kind______from______to_____________________________________count___bytes______time
flush                L0 …
```
> tool: print input, output, deleted and moved bytes in compaction log tool

- level_iter.go
- testdata/level_iter_seek
When TrySeekUsingNext=true, the iterator knows the current seek key must
be greater than or equal to the key at the current iterator position.
This knowledge can be used by level iterators to avoid re-seeking within
the level metadata, under the expectation that the seek key is proximate
and Next-ing will require fewer key comparisons.
Like other TrySeekUsingNext optimizations, this optimization falls back to
seeking if several Nexts does not appropriately position the iterator.  The
fallback seek is expected to be rare in real-world use cases that typically
seek within a limited area of the keyspace (eg, within a single Cockroach KV
range).
The MVCCScan microbenchmarks show an improvement of 1-19% with 64-byte value
sizes. I expect the true benefit to be higher with large, realistic LSMs …
> db: apply TrySeekUsingNext to level metadata

- compaction_picker.go
- internal/metamorphic/options.go
- options.go
- options_test.go
Add an Experimental.Option for configuring the level multiplier used to determine the relative target sizes of levels. Vary this level multiplier in metamorphic tests.
Varying the level multiplier can induce more automatic compactions which can be useful for scheduling more compactions than would otherwise be scheduled with the small store sizes produced by the metamorphic tests.
> db: add Experimental.LevelMultiplier option

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- internal/metamorphic/options.go
- options.go
- options_test.go
- testdata/compaction_tombstones
- testdata/metrics
Add an experimental option `point_tombstone_weight` that can be used to tune how much a table's point deletion tombstones factor into the decision whether or not include it as an input to a compaction.
This experimental option can to encourage compaction of point tombstones that would otherwise be de-prioritized in favor of other compactions, which may have an adverse effect on iteration, which would have to skip over the tombstones.
Informs #1836.
> db: allow for tuning point tombstone weight

- iterator.go
- iterator_test.go
- level_iter.go
- merging_iter.go
- testdata/iter_histories/iter_optimizations
The optimization added in https://github.com/cockroachdb/pebble/pull/2058 began using an enabled TrySeekUsingNext
flag to avoid re-seeking within a level's file metadata. This
optimization was dependent on the invariant that the iterator remained
positioned at the previous seek key, so that a subsequent seek to a
larger key does not need to backtrack.
This invariant wasn't strictly preserved by the levelIter during
SeekPrefixGE calls. During a SeekPrefixGE, the sstable iterator may
return nil despite the existence of sstable keys greater than the seek
key if the sstable's bloom filter excludes the seek prefix. If the
sstable DOES NOT contain any range tombstones, the levelIter does not
advance to the next file if the file's largest bound has a prefix larger
than the seek prefix, returning …
> db: fix levelIter TrySeekUsingNext optimization

- compaction.go
- compaction_picker.go
- internal/metamorphic/options.go
- options.go
- table_stats.go
In random runs, randomly disable delete-only and elision-only compactions. This can improve test coverage of snapshot-pinned data and range tombstones. Users should not disable these compaction types, so these new knobs are hidden within the private Options struct.
Informs #2042.
> metamorphic: disable {delete,elision}-only compactions randomly

- .github/workflows/ci.yaml
Cockroach 22.2 backport of #2037.
----
This CI action was temporarily disabled while it was being fixed. It can now be reenabled.
> crl-release-22.2: .github: renable crossversion metamorphic CI action

- sstable/reader.go
- sstable/reader_test.go
This optimization is done when TrySeekUsingNext is set to true.
A new microbenchmark is added for this case and shows substantial
improvement. We expect this to be helpful when an sstable is not
part of a levelIter (since if the data is exhausted, the levelIter
will switch to a different sstable), or when only the bounds are
reached (even with a levelIter).
Note: two-level=true/exhausted=bounds does not show as much
improvement since the index block is loaded and a fast path will
be taken when twoLevelIterator calls into singleLevelIterator. If
the index block was not loaded, say because of block property
filter not matching, then the speedup should be similar to the
exhausted=file case.
```
name                                                                   old time/op    new time/op …
```
> sstable: optimize twoLevelIterator, when exhausted, for SeekGE & SeekPrefixGE

- level_iter.go
- merging_iter.go
The isLargestUserKeyRangeDelSentinel flag on the levelIterBoundaryContext—used to propagate information to the merging iterator about a level's current file's boundaries—had an outdated, misleading name. Range deletion sentinels are no longer the only source of exclusive end boundaries. If a file's largest key is a range key sentinel, this flag was also marked as true. Rename it to specifically describe whether the largest key is exclusive.
> db: rename isLargestUserKeyRangeDelSentinel

- internal/metamorphic/meta_test.go
Adjust the metamorphic tests to run the variant subtests in parallel. This reduces the wall-time of the test somewhere around 20-40% on my laptop, and will improve utilization of host machines.
The benefit is not as pronounced as I'd hoped, because there are outlier subtests with considerably longer execution time than the other subtests (eg, `use_disk=true`).
Informs #2079.
> metamorphic: run subtests in parallel

- iterator_histories_test.go
- iterator_test.go
- level_iter.go
- merging_iter.go
- merging_iter_test.go
- testdata/iter_histories/iter_optimizations
In #2087, the levelIter began disabling the TrySeekUsingNext optimization deterministically in order to improve test coverage. Disabling the TrySeekUsingNext optimization on some but not all levels of a merging iterator can violate merging iterator invariants. Disabling the TrySeekUsingNext optimization can cause a child iterator to seek backwards to an earlier deleted key that is ≥ the seek key, but less than the key at the previous child iterator position.
This commit fixes this bug by disabling the TrySeekUsingNext optimization for all or none of the merging iterator's level iterators.
Fix #2101.
> db: fix mergingIter TrySeekUsingNext disablement

- sstable/writer.go
This pr adds an invariant check behing the invariants.Enabled flag to confirm that the start/end bounds of the range keys added to the Writer are not the same.
> sstable: assert invariant when range key is added to Writer

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- internal/metamorphic/options.go
- options.go
- options_test.go
- testdata/compaction_tombstones
- testdata/metrics
This is a backport of #2052 to 22.2.
---
Add an experimental option `point_tombstone_weight` that can be used to tune how much a table's point deletion tombstones factor into the decision whether or not include it as an input to a compaction.
This experimental option can to encourage compaction of point tombstones that would otherwise be de-prioritized in favor of other compactions, which may have an adverse effect on iteration, which would have to skip over the tombstones.
Informs #1836.
> [crl-release-22.2] db: allow for tuning point tombstone weight

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- internal/metamorphic/options.go
- options.go
- options_test.go
- testdata/compaction_tombstones
- testdata/metrics
This is a backport of #2052 to 22.1.
---
Add an experimental option `point_tombstone_weight` that can be used to tune how much a table's point deletion tombstones factor into the decision whether or not include it as an input to a compaction.
This experimental option can to encourage compaction of point tombstones that would otherwise be de-prioritized in favor of other compactions, which may have an adverse effect on iteration, which would have to skip over the tombstones.
Informs #1836.
> [crl-release-22.1] db: allow for tuning point tombstone weight

- compaction.go
- format_major_version.go
- format_major_version_test.go
- internal/base/internal.go
- internal/base/lazy_value.go
- open_test.go
- options.go
- sstable/block.go
- sstable/block_test.go
- sstable/format.go
- sstable/format_test.go
- sstable/options.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/raw_block.go
- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/table.go
- sstable/testdata/writer_value_blocks
- sstable/value_block.go
- sstable/value_block_test.go
- sstable/writer.go
- sstable/writer_test.go
- testdata/checkpoint
- testdata/event_listener
- testdata/format_major_version_pebblev1_migration
- testdata/ingest
- testdata/metrics
Value blocks are a mechanism designed for sstables storing MVCC data, where
there can be many versions of a key that need to be kept, but only the
latest value is typically read.
TableFormatPebblev3 is accompanied with DB format-major-version
FormatSSTableValueBlocks. The support for this format is incomplete
and is noted as such. It is introduced at this stage to allow code
in this new format-major-version to configurably write either v2
or v3 sstables.
The writing of sstable v3 is enabled via Options, specifically
EnableValueBlocks, ShortAttributeExtractor (optional), and
RequiredInPlaceValueBound. The RequiredInPlaceValueBound configures an
exclusion prefix key span that can have non-empty suffixes but should
not use value blocks. It is for use in CockroachDB's lock table key
space, …
> sstable: add TableFormatPebblev3 for writing value blocks

- cmd/pebble/db.go
- compaction_test.go
- event_listener_test.go
- format_major_version_test.go
- ingest_test.go
- internal/metamorphic/test.go
- options.go
- replay/workload_capture.go
- replay/workload_capture_test.go
- table_cache_test.go
- table_stats_test.go
- tool/make_test_find_db.go
- tool/testdata/mixed/main.go
- vfs/vfs.go
Develop a workload collector that captures tables and manifests from a
workload. The workload collector learns about the tables and manifests
from the `EventListener`. The workload collector exposes an `Attach`
method that  attaches to the pebble `Options`. It also reads and
saves information from the already configured options.
The workload collector replaces the cleaner of a pebble database in
order to ensure that the files that are ready for cleaning do not get
cleaned before the workload collector has a chance to process them.
During the `Attach` call the workload collector will save the originally
provided cleaner. This saved cleaner will be used to perform the final
cleaning once the files the are obsolete for the collector.
When a manifest is created the event listener will be …
> replay: collect tables and manifests from workloads

- db.go
- external_iterator.go
- iterator_histories_test.go
- iterator_test.go
- level_iter.go
- merging_iter.go
- testdata/iter_histories/iter_optimizations
- testdata/iterator
- testdata/merging_iter
Merge keys put the top level Iterator's position to `iterPosNext`, and
in the process of Next()ing to the next user key, one of the child
levelIters could have advanced past the sstable that contained the
Merge that is being returned.
If that sstable contained a range delete covering a key in an sstable
in a lower level, and the lower level's key was not exposed to the
mergingIter due to a bloom filter mismatch, and we do two consecutive
SeekPrefixGEs where the second one gets TrySeekUsingNext, we could
end up surfacing the deleted key in the lower sstable as the
higher level's levelIter has already moved past the sstable
containing the range deletion.
This change sets isIgnorableBoundaryKey = true when returning
largestBoundary in the levelIter to prevent the mergingIter from
next()ing …
> *: Set isIgnorableBoundaryKey=true for rangedel boundaries in levelIter

- internal/metamorphic/meta_test.go
Previously, if two metamorphic tests were started simulatneously, they could use the same directory because test directories were a function only of time. Fix this by using os.MkdirTemp, which guarantees that concurrent callers will not choose the same directory.
Fix #2125.
Fix #2126.
> metamorphic: prevent directory collisions

- internal/metamorphic/meta_test.go
Backport of #2135.
----
Previously, if two metamorphic tests were started simultaneously, they could use the same directory because test directories were a function only of time. Fix this by using os.MkdirTemp, which guarantees that concurrent callers will not choose the same directory.
> crl-release-22.2: metamorphic: prevent directory collisions

- .github/workflows/ci.yaml
- internal/metamorphic/meta_test.go
Backport of #2135.
----
Previously, if two metamorphic tests were started simultaneously, they could use the same directory because test directories were a function only of time. Fix this by using os.MkdirTemp, which guarantees that concurrent callers will not choose the same directory.
> crl-release-22.1: metamorphic: prevent directory collisions

- .github/workflows/ci.yaml
- internal/metamorphic/meta_test.go
Backport of #2135.
----
Previously, if two metamorphic tests were started simultaneously, they could use the same directory because test directories were a function only of time. Fix this by using os.MkdirTemp, which guarantees that concurrent callers will not choose the same directory.
> crl-release-21.2: metamorphic: prevent directory collisions

- compaction.go
- external_iterator.go
- internal/bytealloc/bytealloc.go
- internal/keyspan/defragment.go
- internal/keyspan/defragment_test.go
- internal/keyspan/interleaving_iter_test.go
- internal/keyspan/internal_iter_shim.go
- internal/keyspan/level_iter_test.go
- internal/keyspan/merging_iter.go
- internal/keyspan/merging_iter_test.go
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- iterator.go
- range_keys.go
- table_stats.go
Avoid various allocations during range key iteration by including additional buffers and slices on the pooled `iteratorRangeKeyState` type.
```
name                                                                      old speed      new speed      delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=0-24          6.61MB/s ± 3%  6.76MB/s ± 3%   +2.29%  (p=0.005 n=9+10)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=1-24          4.00MB/s ± 2%  4.09MB/s ± 3%   +2.22%  (p=0.014 n=9+9)
MVCCScan_Pebble/rows=1/versions=1/valueSize=64/numRangeKeys=100-24         420kB/s ± 0%   452kB/s ± 3%   +7.62%  (p=0.000 n=6+10)
MVCCScan_Pebble/rows=1/versions=2/valueSize=64/numRangeKeys=0-24          5.49MB/s ± 2%  5.52MB/s ± 4%     ~     (p=0.540 n=10+10) …
```
> *: avoid various range key iteration allocations

- docs/RFCS/virtual_sstable.md
Issue: https://github.com/cockroachdb/pebble/issues/1683
> rfc: virtual sstables in the ingestion path

- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
- sstable/reader_test.go
- sstable/value_block.go
It used to be a func, which meant that every assignment that used valueBlockReader.getValue caused an allocation for the closure. By changing to an interface, the two words needed for the interface representation are included in the LazyFetcher struct. And since valueBlockReader is already on the heap, there are no allocations.
The IteratorScanManyVersions benchmark is added and shows a significant improvement for v3 (old is master). Additionally, for a cache-size that results in poor cache hit rate for the whole sstable (20M), the new time for v3 (18.1ns) is significantly better than v2 (27.4ns), since the former has very little data in the data blocks. In contrast, the v2 iteration needs to repeatedly do block memory allocations and checksum checking (there is no real IO due to the use …
> db: change LazyFetcher.ValueFetcher to an interface

- internal/metamorphic/crossversion/crossversion_test.go
The crossversion metamorphic tests run the individual metamorphic tests with the `--keep` flag, to preserve the data directory after the test runs. When a test fails and fatalf is invoked, the corssversion tests copy the relevant directory into the artifacts. However, if a metamorphic test fails before it's able to write the run data directory, this directory won't exist.
This bug is not the reason for the recent crossversion metamorphic test failures (#2143, #2144), but it's made the issue more difficult to diagnose.
> crossversion: allow run dir to not exist

- .github/workflows/ci.yaml
The `linux-race` job is currently consistently failing in CI (both pre- and post-merge). This is being tracked in #2159.
Temporarily skip the job while the cause is investigated.
Touches #2159.
> ci: temporarily skip the linux-race job

- internal/metamorphic/crossversion/crossversion_test.go
- vfs/clone.go
- vfs/testdata/vfs
- vfs/vfs_test.go
Now that the crossversion metamorphic tests run subtests in parallel, it's possible for multiple subtests to fail and invoke fatalf before the process has exited. The fatalf command ensures the run's data is in the configured artifacts directory. If run by two fatalfs concurrently, these operations may conflict with one another. Additionally, previously fatalf would move the directory with a rename. The move would cause concurrent subtests to fail when their data directories were relocated. This commit also updates to fatalf to link-or-copy the files to the artifacts directory, allowing the parallel subtests to continue running undisturbed until torn down by the call to testing.Fatalf.
Additionally, include a binary's version 'label' in its directory name to make it easier to understand …
> crossversion: gracefully handle parallel test failures

- sstable/reader.go
Previously, we had inconsistent handling of errors encountered while opening a new file for OS-level readahead. If the error indicated the file did not exist, we panicked. Otherwise, we continued unperturbed. This commit removes the unnecessary fataling of ENOTEXIST errors (cockroachdb/cockroach#79801), which isn't appropriate in this case which may happen when using a sstable.Reader outside the context of a running pebble.DB.
This panic site was particularly troublesome for Sentry reports because the error surfaced by the `panicFataler` would be redacted.
Fix cockroachdb/cockroach#79801.
> sstable: don't fatal if file no longer exists during readahead

- merging_iter.go
- testdata/iter_histories/iter_optimizations
- testdata/merging_iter
Doing a TrySeekUsingNext during a SeekPrefixGE is incorrect if the
last SeekPrefixGE did a relative seek to the end of a rangedel tombstone
in the merging iter as part of the process of finding a visible user key.
This is because there could have been a visible key in between
our seek prefix and the start of the rangedel, that was not visible to us
due to a bloom filter mismatch, but will become visible on the second
SeekPrefixGE.
This change avoids this bug by removing any merging iter levels below a
range tombstone if the end of the range tombstone is past the prefix.
Fixes https://github.com/cockroachdb/cockroach/issues/92205. Fixes https://github.com/cockroachdb/pebble/issues/2150.
> merging_iter: don't relative-seek past prefix in isNextEntryDeleted

- vfs/vfs.go
The vfs.LimitedCopy and vfs.Copy functions copy vfs files and always perform sequential reads. Pass the SequentialReadsOption to Open to enable OS-level readahead when supported. This will allow the disk to perform fewer, larger reads.
It may improve the performance of checkpointing and ingests across volumes that fallback to copying instead of linking.
> vfs: use SequentialReadsOption in vfs.[Limited]Copy

- internal/metamorphic/crossversion/crossversion_test.go
Previously, I added functionality to stream metamorphic test output to stdout when verbosity is set to help in debugging recent failures. When tests are run in parallel, streaming makes the output difficult to parse. Put the streaming output behind a new, separate cli flag.
Informs #2144.
> crossversion: don't stream TestMeta output on verbose

- internal/manual/manual_64bit.go
- internal/rawalloc/rawalloc_64bit.go
This PR adds `riscv64` to the 64bit build tags, in order to allow building Pebble on 64-bit RISC-V CPUs. All tests are passing on riscv64:
```
ok  	github.com/cockroachdb/pebble	93.903s
ok  	github.com/cockroachdb/pebble/bloom	0.245s
?   	github.com/cockroachdb/pebble/cmd/pebble	[no test files]
?   	github.com/cockroachdb/pebble/internal/ackseq	[no test files]
ok  	github.com/cockroachdb/pebble/internal/arenaskl	0.435s
ok  	github.com/cockroachdb/pebble/internal/base	0.211s
ok  	github.com/cockroachdb/pebble/internal/batchskl	0.335s
?   	github.com/cockroachdb/pebble/internal/bytealloc	[no test files]
ok  	github.com/cockroachdb/pebble/internal/cache	1.502s
?   	github.com/cockroachdb/pebble/internal/crc	[no test files]
ok  	github.com/cockroachdb/pebble/internal/datadriven	0.151s
? …
```
> internal: Allow building on riscv64 architecture

- sstable/reader.go
22.2 backport of #2168. Backporting to try to stem the flow of unproductive Sentry reports.
----
Previously, we had inconsistent handling of errors encountered while opening a new file for OS-level readahead. If the error indicated the file did not exist, we panicked. Otherwise, we continued unperturbed. This commit removes the unnecessary fataling of ENOTEXIST errors (cockroachdb/cockroach#79801), which isn't appropriate in this case which may happen when using a sstable.Reader outside the context of a running pebble.DB.
> crl-release-22.2: sstable: don't fatal if file no longer exists during readahead

- tool/logs/compaction.go
- tool/logs/testdata/compactions
The existing one was unable to parse lines of the form
```
I221207 19:15:31.779316 34583 3@pebble/event.go:625 ⋮ [n1,s1,pebble] 88  [JOB 18] compacting(move) L0 [000014] (2.0 M) + L6 [] (0 B)
```
This meant no node and store numbers and no time bucketed output.
> tool: tweak the log context regexp

- go.mod
- go.sum
- vfs/errors_unix.go
- vfs/file_lock_unix.go
- vfs/file_lock_windows.go
- vfs/preallocate_linux.go
- vfs/prefetch_linux.go
- vfs/syncing_file_linux.go
Ever since Go 1.4 [1], the syscall package has been deprecated, replaced by golang.org/x/sys's platform-dependent packages. Update existing call sites to use these syscall entrypoints.
This commit should not have any functional changes.
[1] https://go.dev/doc/go1.4#major_library_changes
> *: use golang.org/x/sys package

- iterator.go
- iterator_histories_test.go
- iterator_test.go
- range_keys.go
- testdata/iter_histories/range_key_masking
- testdata/iter_histories/stats_no_invariants
Expand the IteratorStats structure to include a few statistics about range
key iteration.
Close #1848.
> db: add RangeKeyIteratorStats

- batch.go
- data_test.go
- db.go
- error_iter.go
- external_iterator.go
- get_iter.go
- internal/arenaskl/flush_iterator.go
- internal/arenaskl/iterator.go
- internal/base/iterator.go
- internal/keyspan/interleaving_iter.go
- internal/keyspan/interleaving_iter_test.go
- internal/keyspan/internal_iter_shim.go
- internal/metamorphic/config.go
- internal/metamorphic/generator.go
- internal/metamorphic/key_manager.go
- internal/metamorphic/ops.go
- internal/metamorphic/parser.go
- internal/metamorphic/retryable.go
- iterator.go
- iterator_test.go
- level_iter.go
- merging_iter.go
- range_keys.go
- sstable/block.go
- sstable/reader.go
- testdata/iter_histories/next_prefix
Expose a NextPrefix method on *pebble.Iterator that may be called when
the user wishes to move to the next key prefix (as determined by
Comparer.Split). NextPrefix guarantees that it will move to the next
key prefix.
When there are many keys per-prefix, the performance benefit of a new
NextPrefix is substantial. Previously, callers would need to SeekGE past
the previous key.  This would force repositioning all the levels of the
iterator. Now the dedicated NextPrefix method is able to use the current
iterator position to avoid a seek from scratch, and avoid repositioning
any levels that are already positioned at the next prefix. Additionally,
during combined iteration over a keyspace covered by a range key,
NextPrefix does not need to interleave range keys at the seek key and
instead will …
> db: add NextPrefix to Iterator

- cmd/pebble/main.go
- cmd/pebble/test.go
This patch allows the bench user to specify a max disk size they'd like the benchmark to run until. If the --duration flag is also set, either the duration or max size can terminate the test.
> bench: add --max-size flag

- internal/metamorphic/retryable.go
The metamorphic test uses a retryable iterator to manage nondeterminism within the `RangeKeyChanged` output when block-property filters are in use. The integration of NextPrefix into the metamorphic tests forgot to update the state on the `retryableIter`.
Fix #2188.
> metamorphic: fix NextPrefix integration

- iterator.go
- testdata/iter_histories/next_prefix
Previously, when an iterator was in prefix-iteration mode calling NextPrefix would error. This commit modifies NextPrefix to instead exhaust the iterator without any error. This allows for simpler code in CockroachDB's MVCC scanner.
> db: tweak NextPrefix semantics in prefix-iteration mode

- data_test.go
- testdata/format_major_version_split_user_key_migration
- testdata/iter_histories/range_keys_simple
- testdata/manual_compaction
- testdata/manual_compaction_set_with_del
The `runDBDefineCmd` function is used in many datadriven tests to define a database state. This command would populate the LSM, but it never ratcheted the log or visible sequence numbers. This meant that an iterator constructed over the defined state would not observe the keys, because it would obtain a snapshot sequence number of zero.
Fix the runDBDefineCmd to ratchet both of these sequence numbers beyond the largest sequence number provided to runDBDefineCmd. This revealed a few tests that defined invalid state—now caught by the level checker, which only now reads at a non-zero snapshot sequence number.
> db: set sequence numbers in datadriven DB define commands

- iterator.go
- iterator_histories_test.go
- iterator_test.go
- range_keys.go
- testdata/iter_histories/range_key_masking
- testdata/iter_histories/stats_no_invariants
22.2 backport of #1871.
----
Expand the IteratorStats structure to include a few statistics about range key iteration.
Informs #1848.
> crl-release-22.2: db: add RangeKeyIteratorStats

- replay/replay_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
- replay/workload_capture.go
- replay/workload_capture_test.go
Pebble encodes the Options.Cleaner used within the OPTIONS file. During workload collection, a custom cleaner is installed to defer the deletion of files until they've been collected. Previously, the `*pebble.WorkloadCollector` itself implemented the Cleaner interface, resulting in the `%s` serialization of the entire WorkloadCollector structure being recorded within the OPTIONS file. This commit adjusts the collector to pass a Cleaner that implements fmt.Stringer, so that a consistent, stable string representation is encoded in the OPTIONS file.
> replay: implement Stringer on workload collector's Cleaner

- data_test.go
- internal/metamorphic/ops.go
- internal/metamorphic/retryable.go
- iterator.go
Document that both HasPointAndRange and RangeKeyChanged require that the iterator already be known to be valid before being called. This is already true of CockroachDB's use of these methods:
* https://github.com/cockroachdb/cockroach/blob/75e145f4d4a7c4fec6d3daaee236ecca08f021ac/pkg/storage/engine.go#L189-L193
* cockroachdb/cockroach#94220
These methods are called in the hot path every KV, so eliding unnecessary
validity checks does slightly move the MVCCScan benchmarks.
```
name                                                                   old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=8/numRangeKeys=0-24          6.54µs ± 1%    6.47µs ± 1%  -1.13%  (p=0.001 n=9+10)
MVCCScan_Pebble/rows=1/versions=2/valueSize=8/numRangeKeys=0-24          7.74µs ± 1% …
```
> db: require validity check before calling HasPointAndRange, RangeKeyChanged

- iterator.go
- testdata/iter_histories/next_prefix
**db: factor out iterator repositioning to first/last key**
Pull out the logic to reposition the internal iterator to first or last
visible key into helper functions.
**db: allow switching directions using NextPrefix** 
Previously, NextPrefix had undefined behavior when called on an Iterator
positioned in the reverse direction. This commit expands NextPrefix to support
being called when oriented in the reverse direction, in which case it will
correctly advance to the first key with a greater prefix. The behavior while
positioned at an IterAtLimit position continues to be undefined (but in
practice, is implemented as a simple Next for metamorphic test determinism).
This will simplify code in Cockroach's MVCC scanner, which itself needs to
support switching directions.
The internal iterator …
> db: allow switching directions using NextPrefix 

- sstable/suffix_rewriter.go
- sstable/writer.go
This could happen if Writer.Close was called more than once. It is
tripping up some CockroachDB tests, which are panicking because a field
of the valueBlockWriter that should never be nil is nil. A concurrent
goroutine using the same valueBlockWriter would set that field to nil
before returning the valueBlockWriter to the sync.Pool. Even worse,
multiple goroutines using the same valueBlockWriter can cause data
corruption. Adding this defensive code fixes the test failure.
Additionally, the cause of the multiple calls to Writer.Close in
suffix_rewriter.go is fixed. There was also a missing call to Writer.Close
which is fixed.
Informs https://github.com/cockroachdb/pebble/issues/1170
Epic: [CRDB-20378](https://cockroachlabs.atlassian.net/browse/CRDB-20378)
> sstable: prevent duplicate put of valueBlockWriter to sync.Pool

- sstable/reader_test.go
- sstable/unsafe_test.go
Skip two tests that are known to be flakes when run on windows.
Touches #1897.
> sstable: skip two known test flakes on windows

- internal/manifest/btree.go
- internal/manifest/level_metadata.go
- internal/manifest/testdata/level_iterator
In #2187, the LevelIterator seeking methods were refactored to no longer early exit when a LevelIterator's bounds indicate that the iterator is empty. This change was necessary for new invariant checking around the exhausted iterator positions at the beginning and end of iteration.
This inadvertently allowed a seek on an empty, bounded iterator to improperly access the underlying b-tree iterator's current position, despite it being invalid.
Informs #2210.
> internal/manifest: fix out-of-bounds b-tree access

- db.go
This is a trivial change to add some additional context in the fatal log line when a commit fails.
I've been diagnosing a PebbleDB crash with `sync: negative WaitGroup counter` originating from this callsite (at the top of the stack). Since [panics are recovered](https://github.com/search?q=repo%3Acockroachdb%2Fpebble+recover%28%29&type=code) and the error is reproduced literally here, it was difficult to narrow down the source of this crash. This additional qualification in the message should make it easier to trace down in the future.
(I may open a separate issue for the commit failure crash once I am able to create a reliably reproducible test case)
> db: Qualify fatal commit error message

- .github/workflows/ci.yaml
- Makefile
- go.mod
- go.sum
Use Go 1.19 for the default workflows (excluding the explicit Go version compatibility tests, which run on compilers 1.1{7-9}). Go 1.19 introduced changes to gofmt that result in significant churn to our comments, so also update the lint check to use crlfmt (`--fast`).
> .github: use Go 1.19

- internal/metamorphic/generator.go
- internal/metamorphic/ops.go
- internal/metamorphic/options.go
- internal/metamorphic/parser.go
Add support for randomizing the bloom filter bits-per-key setting in
metamorphic tests.
Informs #2127
Fixes #2127.
> metamorphic: vary bloom filter setting and UseL6Filters for iterators

- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/writer.go
We replace fairly large buffered allocations with bytealloc.A which is cleaner and more efficient when buffers are small.
Fixes #2000
UpdateSSTTimestamps benchmark changes:
```
name                                              old time/op    new time/op     delta
UpdateSSTTimestamps/numKeys=1/concurrency=0         41.6µs ± 0%     41.7µs ± 1%      ~     (p=0.690 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=1          149µs ± 5%       33µs ± 1%   -78.00%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=2          148µs ± 1%       34µs ± 0%   -77.10%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=4          151µs ± 1%       36µs ± 1%   -75.95%  (p=0.008 n=5+5)
UpdateSSTTimestamps/numKeys=1/concurrency=8          155µs ± 1%       41µs ± 1%   -73.64%  (p=0.008 n=5+5) …
```
> sstable: use bytealloc.A in reader, writer, suffix rewriter

- range_keys.go
- testdata/iter_histories/lazy_combined_iteration
Lazy-combined iteration depends on individual point level iterators triggering a switch to combined iteration when they observe a file containing relevant range keys. Previously, this switch did not happen if the observed range keys all lied outside the current iteration prefix. This made it possible for a level to become positioned beyond the file containing range keys, without ever triggering the switch to combined iteration. A subsequent seek that made use of the TrySeekUsingNext optimization would never observe the file containing range keys, and omit the range keys.
This commit deletes the code preventing the switch to combined iteration when a key is observed outside the prefix. The commit that introduced this logic #1900 was fixing a range-key iterator invariant violation, but it …
> db: fix lazy-combined iteration bug

- compaction.go
- internal/base/iterator.go
- iterator.go
- iterator_test.go
- metrics.go
- metrics_test.go
- sstable/reader_test.go
- sstable/testdata/readerstats/iter
- sstable/testdata/readerstats_v3/iter
- sstable/value_block.go
- testdata/external_iterator
- testdata/iter_histories/iter_optimizations
- testdata/iter_histories/range_key_masking
- testdata/iter_histories/stats_no_invariants
- testdata/iterator
- testdata/iterator_stats
- testdata/level_iter_seek
- testdata/merging_iter
- testdata/metrics
- LevelMetrics.Additional contains cumulative metrics for bytes written to data blocks and value blocks.
- InternalIteratorStats.SeparatedPointValue contains iterator stats for points encountered whose values were in value blocks.
Informs #1170
Epic: CRDB-20378
> db: metrics and stats for value blocks and lazy values

- internal/base/lazy_value.go
- internal/metamorphic/options.go
- sstable/value_block.go
- Fix metamorphic test to actually test value blocks.
- Do buffer mangling when retrieving from valueBlockReader to ensure callers are not relying on excessive memory stability.
- Relax the invariant of LazyValue.Clone to allow cloning even if the value has been fetched.
Informs #1170
Epic: CRDB-20378
> db: misc LazyValue tweaks, for testing, and simpler Clone invariant

- batch.go
- batch_test.go
- commit.go
- commit_test.go
- db.go
- internal/metamorphic/ops.go
- internal/metamorphic/options.go
- open.go
- record/log_writer.go
- record/log_writer_test.go
ApplyNoSyncWait must only be used when WriteOptions.Sync is true. It enqueues
the Batch to the WAL, adds to the memtable, and waits until the batch is
visible in the memtable, and then returns to the caller. The caller is
responsible for calling Batch.SyncWait to wait until the write to the
WAL is fsynced.
This change required splitting the WaitGroup in the Batch into two
WaitGroups, so waiting for the visibility can happen separately from
waiting for the WAL write. Additionally, the channel used as a semaphore
for reserving space in the two lock-free queues is split into two channels,
since dequeueing from these queues can happen in arbitrary order.
Benchmarks indicate that the overhead of pushing and popping on an extra
channel is tolerable. Benchmarks were run on a macbook pro -- note …
> db: add DB.ApplyNoSyncWait for asynchronous apply

- testdata/compaction_tombstones
Fixing flaky test case caused by an automatic compaction.
Fixes #2033
> deflake TestCompactionTombstones

- sstable/value_block.go
Tests can set a high maximum block size e.g. TestReader sets the block size to 2GB. This resulted in a 3GB byte slice being allocated. The new logic is similar to the behavior in blockWriter.
Fixes #2159
> sstable: avoid allocating up to maximum block size in valueBlockWriter

- .github/workflows/ci.yaml
Follow-on from https://github.com/cockroachdb/pebble/pull/2236.
> ci: re-enable linux race

- sstable/reader_test.go
- sstable/unsafe_test.go
This reverts commit 65ff304d3d7a5f7b7ed038bd175a7dd440637af4.
Touches #1897.
> Revert "sstable: skip two known test flakes on windows"

- format_major_version.go
- open.go
- testdata/checkpoint
- testdata/event_listener
During a format major version, some version migrations must scan the LSM. These migrations require that the files they examine are not deleted before or while they're reading them. A previous attempt (#2020) at avoiding these unexpected deletions accidentally left an opening for the acquired versions' files to be deleted while waiting for file deletions to be disabled (sleeping on a condition variable).
A different fix with less subtlety is applied here. The format major version upgrade path acquires a readState, which refs the versions it acquires, preventing deletion of the referenced files. This requires the format major version upgrade in Open to be moved later within the Open routine, after the current read state is initialized.
Fix #2143.
> db: scan a readState during format major version upgrades

- cmd/pebble/main.go
- cmd/pebble/replay.go
- replay/replay.go
- replay/replay_test.go
Add a `pebble bench replay` command for replaying workloads for
compaction benchmarking.
> cmd/pebble: add bench replay command

- format_major_version.go
- open.go
- testdata/checkpoint
- testdata/event_listener
22.2 backport of #2186.
----
During a format major version, some version migrations must scan the LSM. These migrations require that the files they examine are not deleted before or while they're reading them. A previous attempt (#2020) at avoiding these unexpected deletions accidentally left an opening for the acquired versions' files to be deleted while waiting for file deletions to be disabled (sleeping on a condition variable).
A different fix with less subtlety is applied here. The format major version upgrade path acquires a readState, which refs the versions it acquires, preventing deletion of the referenced files. This requires the format major version upgrade in Open to be moved later within the Open routine, after the current read state is initialized.
Fix #2143.
> crl-release-22.2: db: scan a readState during format major version upgrades

- replay/replay_test.go
- replay/testdata/collect/clean_before_copy
- replay/testdata/collect/copy_before_clean
- replay/testdata/collect/manifest_copying
- replay/testdata/collect/start_stop
- replay/workload_capture.go
- replay/workload_capture_test.go
This commit applies a variety of code hygeine changes to the workload collector implementation. Some identifiers are renamed to be more concise, or clarify that they must be accessed through atomics. The workload collector tests are refactored to be datadriven tests.
> replay: various WorkloadCollector clean up and refactors

- checkpoint.go
- checkpoint_test.go
- internal/manifest/version.go
- testdata/checkpoint
- testdata/event_listener
This commit adds a checkpoint option to filter out SSTs that don't overlap with a given set of spans. This is useful when we are interested only in a single range (or a few ranges) and don't want to the checkpoint to take up large amounts of space as the store goes through compactions.
Fixes #2045
> db: support narrow checkpoints

- compaction.go
- metrics_test.go
Previously, when DisableWAL was enabled, L0's [BytesIn] field was always zero, because the logSizes were always zero. This commit adjusts the flush metrics accounting to consider all the L0 flushed bytes as [BytesIn] when the WAL is disabled. This allows Metrics to compute a total write amplification value, whereas previously the zero BytesIn quantity prevented it.
> db: calculate w-amp when DisableWAL is enabled

- .github/workflows/ci.yaml
Drop the Go version matrix and test against a single version of Go.
> ci: only use latest version of Go

- internal/metamorphic/meta_test.go
The metamorphic test already tests DeleteRange.
Closes #1935
> metamorphic: remove defunct comment

- replay/workload_capture.go
WorkloadCollector.clean can be called before WorkloadCollector.Start is called. Therefore, WorkloadCollector.Start must acquire WorkloadCollector.mu.
> replay: fix race in WorkloadCollector

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- internal/manifest/l0_sublevels.go
- options.go
- replay/replay_test.go
- testdata/compaction_setup_inputs_multilevel_dummy
This patch introduces the multiLevelHueristic interface, whose implementations
can evaluate whether to add an additional level to a conventional 2 level
compaction.
If the option.experimental.multiLevelHeuristic knob is set, the compaction
picker will create a deep copy of the original compaction, call setupInputs on
the newly allocated object, adding a new level to the new compaction
candidate. Then, the heuristic decides to compact with the original picked
compaction or the new multilevel candidate.
Informs #2053
> compaction: introduce multilevel compaction heuristic interface

- db.go
- replay/replay_test.go
Files can be deleted asynchronously so it makes sense to wait for cleaning to complete before listing the files.
> replay: unflake TestCollectCorpus

- sstable/reader_test.go
BenchmarkIteratorScanManyVersions, which iterates over all the versions, now also runs with readValue=true. Similarly, for
BenchmarkIteratorScanNextPrefix, which iterates over the most recent versions.
Informs #1170
> sstable: update two sstable benchmarks to also read the value

- compaction.go
- compaction_test.go
- internal/keyspan/span.go
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- sstable/testdata/writer
- sstable/testdata/writer_range_keys
- sstable/testdata/writer_v3
- sstable/writer.go
Optimize rangekey.Coalesce by sorting range keys altogether once, and then
deduplicating in a second pass.
```
name                                   old time/op  new time/op  delta
Transform/shadowing=false/keys=1-10    46.5ns ± 0%  35.7ns ± 0%  -23.19%  (p=0.016 n=5+4)
Transform/shadowing=false/keys=2-10     116ns ± 0%    96ns ± 0%  -17.50%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=4-10     436ns ± 0%   256ns ± 0%  -41.30%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=8-10    1.77µs ± 0%  0.95µs ± 0%  -46.67%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=16-10   8.85µs ± 0%  3.24µs ± 0%  -63.42%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=32-10   48.7µs ± 0%   7.2µs ± 0%  -85.19%  (p=0.008 n=5+5)
Transform/shadowing=false/keys=64-10    170µs ± 0%    19µs ± 0%  -88.85% …
```
> internal/rangekey: optimize Coalesce 

- internal/base/lazy_value.go
- iterator.go
- iterator_test.go
- sstable/block.go
- sstable/reader.go
BenchmarkIteratorScanNextPrefix now exercises value blocks. Also, the benchmark now does an iterator step per benchmark iteration instead of a full scan -- this makes the benchmark faster and allows us to compare performance metrics across benchmark parameters (since the metrics do not vary based on the total number of different key prefixes in the LSM).
There is a tiny tweak to the field ordering in LazyFetcher and additional code comments about performance and future optimization.
Informs #1170
> db: tweak to BenchmarkIteratorScanNextPrefix and performance commentary

- ingest.go
This special case is not necessary anymore - `MemFS` no longer has windows semantics by default. Only one test (`TestIngestCleanup`) enables them (via `UseWindowsSemantics`) and that test does not use `DebugCheck`.
> ingest: remove special MemFS case for hardlinking

- event.go
- options.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- vfs/fd_test.go
- vfs/vfs_test.go
Part of https://github.com/cockroachdb/cockroach/issues/67856. 
This is https://github.com/cockroachdb/pebble/pull/1672 from @nicktrav, rebased on top of https://github.com/cockroachdb/pebble/pull/1677 and extended so that the op type of filesystem metadata operations is also captured. I also addressed @sumeerbhola's last comments over at https://github.com/cockroachdb/pebble/pull/1672.
With this one merged, I still have more thing to do. I will extend `DiskSlowInfo` to track write size in case a sized write (e.g. a call to `Write`).
As an aside, some discussion was had at https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1674138778490679 about moving from a single long-lived monitor goroutine per file to a shorter-lived monitor goroutine per file op. Would mean no shared mutable state …
> vfs: capture operation type affected by disk slowness

- event.go
- vfs/disk_health.go
This change updates diskHealthCheckingFS to drop the mutex before
calling the event listener, in case the event listener's operations block
or take a while, potentially blocking write operations to
diskHealthCheckingFS until the event listener returns.
Also updates TeeEventListener to call its two children in
parallel and then wait on them to finish.
Fixes https://github.com/cockroachdb/pebble/issues/2273.
> vfs: don't call onDiskSlow while holding diskHealthCheckingFS mutex

- db.go
- external_iterator.go
- iterator.go
- testdata/iter_histories/next_prefix
See https://github.com/cockroachdb/pebble/issues/2260#issuecomment-1406803934 for the reason behind this choice. Note that CockroachDB never uses versioned keys in the bounds by construction, since bounds are always of type roachpb.Key. Completely disallowing versioned bounds in Pebble would also be an option, but was considered too strict, and switching the behavior based on the upper-bound is simple and cheap (well designed implementations of Comparer.Split should be O(1)).
Fixes #2260
> db: disallow NextPrefix if the upper-bound is a versioned key

- vfs/atomicfs/marker.go
This change clarifies some things I found confusing about markers - in
particular referring to the value as a filename (which raised the
question whether Move actually deletes the file an old marker pointed
to). We now refer only to generic values and not filenames.
Fixing a bug in the error case of `RemoveObsolete` - we were always
removing the first file instead of removing all files for which the
delete succeeded.
> atomicfs: better documentation, minor bug fix

- internal/manifest/btree.go
- internal/manifest/btree_test.go
- internal/manifest/l0_sublevels.go
- internal/manifest/level_metadata.go
- internal/manifest/testdata/overlaps
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
Previously, calling `Version.Overlaps` for a level lower than L0 would return a LevelSlice containing the correct files but a `length` field of zero. Thankfully, it appears there were no call sites that accessed such a LevelSlice's `Len()`. Compaction picking came close, but the `Reslice` calls to expand to the atomic compaction unit would compute the length on the adjusted slice before the first call to Len.
This commit fixes this bug by:
1. introducing a [subtreeCount] into the level metadata b-tree nodes, which is incrementally updated with the total number of files within the node's subtree.
2. adding a countLeft method to the B-Tree iterator, which returns the number of files to the left of the iterator's current position within a level. This method takes advantage of the …
> internal/manifest: fix Version.Overlaps length bug

- internal/keyspan/span.go
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- sstable/testdata/writer_range_keys
- sstable/writer.go
When a user adds a range key to a sstable that they're building (eg, for ingest or backups), sort the range keys before writing them. This was a bug introduced recently in #2197. Although we don't need to coalesce the keys, we should write them in disk descending by suffix. Note that this ordering of sstable keys isn't a property we rely upon or use in any way in practice, but we may want to make use of it sometime in the future.
> sstable: sort user-added range keys by suffix descending

- cleaner_test.go
- compaction.go
- options.go
Forces test archive cleaner to wait for cleaning after a flush by calling TestOnlyWaitForCleaning to ensure that the expected file removals in the test are observed.
But waiting for cleaning after the flush command in the test isn't sufficient, as the compact command in the test can itself schedule a flush and if the files after a flush test are deleted asynchronously, then the output of the compact command in the test will differ. So, we add an option to force flushes to wait for file deletions
> db: unflake TestArchiveCleaner

- compaction.go
- version_set.go
In `scanObsoleteFiles` we use `mergeFileMetas` on obsolete tables which deduplicates, but when we increment the obsolete table metrics we assume there were no duplicates.
This change makes updating the obsolete table metrics less fragile - we simply recalculate the metric from scratch each time.
> pebble: minor cleanup around obsolete tables

- cleaner_test.go
- compaction_test.go
- format_major_version_test.go
- ingest_test.go
- internal/metamorphic/meta_test.go
- iterator_histories_test.go
- options.go
- vfs/disk_health.go
**db: add Options.WithFSDefaults**
Add a facility for easily layering in the default VFS middleware—currently the
disk-health checking FS. Options.EnsureDefaults by default uses the disk-health
checking FS, but most of our tests explicitly set a VFS, and in particular a
*vfs.MemFS. These tests have always run without the disk-health checking
filesystem layer. Use the new WithFSDefaults method across many Pebble unit
tests and the Pebble metamorphic tests.
This is sufficient to surface the concurrent `Sync` operations observed in
https://github.com/cockroachdb/cockroach/issues/96422 and https://github.com/cockroachdb/cockroach/issues/96414. See https://github.com/cockroachdb/pebble/pull/2282 for
context on where this panic is originating.
**vfs: handle concurrent directory Syncs in …
> vfs: handle concurrent directory Syncs in disk-health checking

- cmd/pebble/replay.go
- cmd/pebble/replay_test.go
- db.go
- metrics.go
- replay/replay.go
- replay/replay_test.go
**cmd/pebble: add -count to replay command**
Add a -count flag to the replay command to replay a workload multiple times,
useful for building up a statistically significant number of runs.
**replay: refactor compaction tracking**
Refactor the compaction tracking for readability and eliminating an extra
goroutine. Also, add a unit test that ensures the replayer correctly
detects when compactions quiesce.
**cmd/pebble: remove temporary run directories before exit**
**replay: fix TotalWAmp calculation**
Fix TotalWAmp calculation to use Metrics.Total and maintain consistency with
the w-amp reported by Metrics.String(). The Metrics.Total method handles
adjusting BytesIn and BytesFlushed.
**cmd/pebble: allow setting custom Pebble Options through a CLI flag**
> replay: various compaction benchmarking tweaks

- go.mod
- go.sum
Update to the latest available version of
`github.com/klauspost/compress`. This package is only used when using zstd compression with a non-CGo build of Pebble.
Benchmarks show more or less no change in the performance between the previous (`v1.11.13`) and latest versions:
```
name                                                                                old time/op    new time/op    delta
Writer/format=(Pebble,v2)/block=4.0_K/filter=true/compression=ZSTD-16                  239ms ± 2%     235ms ± 1%  -1.60%  (p=0.000 n=10+9)
Writer/format=(Pebble,v2)/block=4.0_K/filter=false/compression=ZSTD-16                 221ms ± 2%     220ms ± 2%    ~     (p=0.165 n=10+10)
Writer/format=(Pebble,v2)/block=32_K/filter=true/compression=ZSTD-16                   115ms ± 1%     114ms ± 2%    ~ …
```
> deps: update github.com/klauspost/compress to v1.15.15

- go.mod
- go.sum
Pull in the latest version of xxhash.
Benchmarks show a slight performance improvement for Pebblev2 tables. A very slight regression is observed for v3 tables when using larger block sizes.
```
name                                                                                                           old time/op    new time/op    delta
Writer/format=(Pebble,v2)/block=4.0_K/filter=true/compression=NoCompression/checksum=xxhash64-16                 67.7ms ± 3%    64.8ms ± 2%  -4.28%  (p=0.000 n=10+9)
Writer/format=(Pebble,v2)/block=4.0_K/filter=true/compression=Snappy/checksum=xxhash64-16                        81.5ms ± 2%    78.1ms ± 1%  -4.19%  (p=0.000 n=10+10)
Writer/format=(Pebble,v2)/block=4.0_K/filter=true/compression=ZSTD/checksum=xxhash64-16                           239ms ± 1% …
```
> deps: update github.com/cespare/xxhash to v2.2.0

- cmd/pebble/replay.go
- replay/replay.go
- replay/replay_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
Add a `--max-writes` flag to the cmd/pebble replay command that limits the amount of a workload to replay by the configured MB. This allows us to collect large workloads and apply a smaller subset at replay time if the full workload is unnecessary.
> replay: add option to apply subset of a workload

- cleaner_test.go
- format_major_version_test.go
- internal/metamorphic/meta_test.go
- options.go
- vfs/disk_health.go
22.2 backport of #2298.
----
**db: add Options.WithFSDefaults**
Add a facility for easily layering in the default VFS middleware—currently the
disk-health checking FS. Options.EnsureDefaults by default uses the disk-health
checking FS, but most of our tests explicitly set a VFS, and in particular a
*vfs.MemFS. These tests have always run without the disk-health checking
filesystem layer. Use the new WithFSDefaults method across many Pebble unit
tests and the Pebble metamorphic tests.
This is sufficient to surface the concurrent `Sync` operations observed in
https://github.com/cockroachdb/cockroach/issues/96422 and https://github.com/cockroachdb/cockroach/issues/96414. See https://github.com/cockroachdb/pebble/pull/2282 for
context on where this panic is originating.
**vfs: handle …
> crl-release-22.2: vfs: handle concurrent directory Syncs in disk-health checking 

- cleaner_test.go
- internal/metamorphic/meta_test.go
- options.go
- vfs/disk_health.go
22.1 backport of #2298.
----
**db: add Options.WithFSDefaults**
Add a facility for easily layering in the default VFS middleware—currently the
disk-health checking FS. Options.EnsureDefaults by default uses the disk-health
checking FS, but most of our tests explicitly set a VFS, and in particular a
*vfs.MemFS. These tests have always run without the disk-health checking
filesystem layer. Use the new WithFSDefaults method across many Pebble unit
tests and the Pebble metamorphic tests.
This is sufficient to surface the concurrent `Sync` operations observed in
https://github.com/cockroachdb/cockroach/issues/96422 and https://github.com/cockroachdb/cockroach/issues/96414. See https://github.com/cockroachdb/pebble/pull/2282 for
context on where this panic is originating.
**vfs: handle …
> crl-release-22.1: vfs: handle concurrent directory Syncs in disk-health checking

- objstorage/shared/storage.go
- options.go
This change adds a Storage interface that can be implemented by blob storage drivers. The objstorage.Provider coming in #2267 will largely be responsible for storing state of files' locations (i.e. shared or local), and calling into Storage as necessary.
> *: Add objstorage.shared.Storage interface for storing sstables

- batch.go
- batch_test.go
- flushable_test.go
- ingest.go
- ingest_test.go
- open.go
The `InternalKeyKindIngestSST` key contains the file path of an SST object. We don't normally store paths in metadata, as it is fairly fragile (e.g. what if the store is moved).
Since this is always an SST object that we created (usually through hard-link), we can store just the FileNum.
This also opens up the door for this object to be potentially stored on shared storage (we'd need to support non-local SSTs as ingest inputs though).
> db: change flushable ingest key to encode just the FileNum

- db_test.go
- objstorage/sharedobjcat/catalog.go
- objstorage/sharedobjcat/catalog_test.go
- objstorage/sharedobjcat/testdata/catalog
- objstorage/sharedobjcat/version_edit.go
- objstorage/sharedobjcat/version_edit_test.go
- record/rotation.go
- record/rotation_test.go
- record/testdata/rotation
- version_set.go
This commit adds code for a shared object catalog. It is implemented very similarly to the manifest: the catalog file contains multiple records, where each record is an encoded version edit. A marker file is used to keep track of the latest file.
The new code is not yet used.
> objstorage: introduce shared object catalog

- objstorage/shared/storage.go
- options.go
This change adds an option to specify shared.Storage in pebble Options and also adds a missing error return value to the List() method in that interface.
> *: Add shared.Storage to Options.

- compaction.go
- compaction_iter.go
- compaction_iter_test.go
- compaction_test.go
- testdata/frontiers
Introduce a new type `frontiers`, designed to monitor several different user
key frontiers during a compaction. When a user key is encountered that equals
or exceeds the configured frontier, the code that specified the frontier is
notified and given an opportunity to set a new frontier. Internally,
`frontiers` uses a heap (code largely copied from the merging iterator's heap)
to avoid N key comparisons for every key.
This commit refactors the `limitFuncSplitter` type to make use of `frontiers`.
The `limitFuncSplitter` type is used to split flushes to L0 flush split keys,
and to split both flushes and compactions to avoid excessive overlap with
grandparent files.
This change is motivated by #2156, which will introduce an additional
compaction-output splitter that must perform key …
> db: refactor compaction splitting to reduce key comparisons

- version_set.go
The recently modified code was missing a reset.
Informs #2314.
> db: fix ObsoleteSize stat

- compaction.go
- compaction_test.go
- ingest.go
- ingest_test.go
- objstorage/provider.go
- objstorage/vfs.go
- open.go
- sstable/data_test.go
- sstable/reader_test.go
- table_cache_test.go
- testdata/cleaner
- testdata/event_listener
- tool/db.go
- tool/testdata/db_check
- tool/testdata/db_lsm
- tool/testdata/db_scan
This change modifies the objstorage API and restructures some of its
code to allow for adding support for shared objects.
The main change is that the Provider maintains its own list of known
objects. We populate the initial list from the local FS listing; for
shared objects the information will come from the shared object
catalog.
This change includes some cleanup in db.Open. We now open the
directories first and move more code up before the `Db` object
initialization (after which cleanup becomes more complicated).
> objstorage: keep track of objects in the Provider

- compaction.go
- compaction_test.go
- data_test.go
- testdata/compaction_tombstones
- testdata/manual_compaction
- testdata/manual_compaction_file_boundaries
This commit implements a compaction-splitting heuristic as implemented by
RocksDB and described within the blog post "Reduce Write Amplification by
Aligning Compaction Output File Boundaries." [1]
Aligning sstable boundaries can significantly reduce write amplification.
Consider the following compaction:
+----------------------+
input            |                      |
level            +----------------------+
\/
+---------------+       +---------------+
output   |XXXXXXX|       |       |      |XXXXXXXX|
level    +---------------+       +---------------+
The input-level file overlaps two files in the output level, but only
partially. The beginning of the first output-level file and the end of the
second output-level file will be rewritten verbatim. This write IO is "wasted"
in the sense …
> db: implement relaxed target file size splitting heuristic

- db.go
- metrics.go
- replay/replay.go
- replay/replay_test.go
- replay/sampled_metric.go
- table_stats.go
Add a metric to expose the approximate count of tombstones within the LSM. Sample this metric within compaction benchmarking replay to help in evaluating changes to tombstone compaction heuristics.
> db: add Metrics.Keys.TombstoneCount

- open.go
- open_test.go
- options.go
Add an option to fail Open if the database is not pristine.
A database that contains any key is never pristine. An empty database that used to have keys may or may not be considered pristine.
This option will be useful to recover from certain bootstrapping corner cases.
We also improve the `ErrorIfExists` and `ErrorIfNotExists` options to allow programmatically checking for the relevant errors and clean up the tests.
> db: add ErorrIfNotPristine option

- ingest_test.go
- objstorage/provider.go
- objstorage/provider_test.go
Return a NotExistError when the object is not in our list. This is important for Remove, where such an error is ignored.
Informs #2325
> objstorage: return NotExistError when object is not known

- compaction.go
- compaction_test.go
- db.go
- ingest.go
- ingest_test.go
- objstorage/provider.go
- open.go
- sstable/data_test.go
- sstable/reader_test.go
- table_cache_test.go
- testdata/checkpoint
- testdata/cleaner
- testdata/event_listener
- tool/db.go
Add Sync method to the objstorage provider. Object creation or removal is only durable when Sync is called. Currently we just sync the local directory; soon we will also push an update to the shared object catalog (if needed).
> objstorage: add Sync

- docs/index.html
Add an annotation to the nightly benchmarks displaying when we began splitting compaction outputs at grandparent boundaries.
> docs: add benchmark annotation for grandparent boundary splitting

- objstorage/sharedobjcat/catalog.go
- objstorage/sharedobjcat/catalog_test.go
- objstorage/sharedobjcat/testdata/catalog
- objstorage/sharedobjcat/version_edit.go
- objstorage/sharedobjcat/version_edit_test.go
This commit adds support for storing the creator ID in the shared
object catalog. Once set, the ID cannot change.
Add object type to on-disk catalog and include FileType in
SharedObjectMetadata.
> sharedobjcat: add creator-id and object type

- batch.go
- batch_test.go
- db.go
- external_iterator.go
- internal/keyspan/bounded.go
- internal/keyspan/level_iter_test.go
- internal/keyspan/merging_iter.go
- internal/keyspan/merging_iter_test.go
- internal/rangekey/coalesce.go
- internal/rangekey/coalesce_test.go
- internal_iterator.go
- internal_iterator_test.go
- level_iter.go
- mem_table_test.go
- range_keys.go
- snapshot.go
- testdata/scan_internal
This change adds a new scanInternalIterator that exposes internal keys to external users through a ScanInternal(). This will be useful for when we start creating iterators on partial LSM states, and we'd need to observe all keys that could impact the part of the LSM that we do not observe, such as point tombstones, rangedels, etc.
> db: add a ScanInternal to scan internal keys

- open.go
- open_test.go
The issue is described in detail in:
https://github.com/cockroachdb/pebble/issues/2234.
The fix is to set the mutable memtable to nil while replaying the large batch. When the next WAL is replayed, it will be forced to create a new mutable memtable to write to.
Fixes: https://github.com/cockroachdb/pebble/issues/2234
> db: fix replay corruption in read only mode

- cleaner_test.go
- compaction.go
- objstorage/provider.go
- objstorage/vfs.go
- testdata/cleaner
Ignore SST files in the listing and instead get the list of objects from the objstorage provider.
> db: use objstorage to find obsolete objects

- .github/workflows/ci.yaml
- Makefile
Add two test targets for address and memory sanitization. This is intended to improve Pebble coverage to aid in detection of subtle memory errors.
Add two new CI targets. The two types of sanitization must can not be run together.
Touches #2320.
> build: add make targets for asan and msan; add ci jobs

- record/log_writer_test.go
SyncRecord first releases the waitgroup, then reads from the channel. To avoid this race, we retry for a while in the test.
Fixes #2324
> record: fix TestSyncRecordWithSignalChan flake

- compaction.go
- error_test.go
- ingest_test.go
- objstorage/provider.go
- objstorage/provider_test.go
- objstorage/shared.go
- objstorage/shared/logging.go
- objstorage/shared/mem.go
- objstorage/shared/storage.go
- objstorage/shared_readable.go
- objstorage/shared_writable.go
- objstorage/sharedobjcat/catalog.go
- objstorage/sharedobjcat/catalog_test.go
- objstorage/testdata/provider
- objstorage/vfs.go
- objstorage/vfs_readable.go
- open.go
- sstable/data_test.go
- sstable/reader_test.go
- table_cache_test.go
- testdata/cleaner
This commit adds in-memory and with-logging implementations of
shared.Storage.
This commit adds basic shared object functionality to the provider.
We do not implement any refcounting or removal of shared objects.
> objstorage: basic shared object functionality 

- objstorage/provider.go
- objstorage/provider_test.go
- objstorage/shared.go
- objstorage/shared_backing.go
- objstorage/shared_backing_test.go
- objstorage/testdata/provider
This commit introduces the concept of a `SharedObjectBacking`. This is an opaque encoding of the metadata necessary to access a shared object (specifically creator ID and creator file num). The backing can be extracted for a shared object on an instance and then used to attach the object to another instance. This will be used for rebalancing.
> objstorage: allow attaching of shared objects

- format_major_version.go
- format_major_version_test.go
- ingest.go
- ingest_test.go
- internal/metamorphic/options.go
- open_test.go
- options.go
- testdata/checkpoint
- testdata/event_listener
- testdata/flushable_ingest
Introduce a new format major version that gates uses of flushable ingests and the corresponding backwards-incompatible changes to the write-ahead log.
Close #2292.
> db: add format major version for flushable ingests

- open.go
- open_test.go
The issue is described in detail in:
https://github.com/cockroachdb/pebble/issues/2234.
The fix is to set the mutable memtable to nil while replaying the large batch. When the next WAL is replayed, it will be forced to create a new mutable memtable to write to.
Fixes: https://github.com/cockroachdb/pebble/issues/2234 (cherry picked from commit 822e1941c7309c7046ede1a83416e3ff9b20b56d)
> crl-release-22.2: db: fix replay corruption in read only mode

- open.go
- open_test.go
The issue is described in detail in:
https://github.com/cockroachdb/pebble/issues/2234.
The fix is to set the mutable memtable to nil while replaying the large batch. When the next WAL is replayed, it will be forced to create a new mutable memtable to write to.
Fixes: https://github.com/cockroachdb/pebble/issues/2234 (cherry picked from commit 822e1941c7309c7046ede1a83416e3ff9b20b56d)
> crl-release-22.1: db: fix replay corruption in read only mode

- format_major_version.go
- format_major_version_test.go
- open_test.go
- testdata/checkpoint
- testdata/event_listener
- testdata/flushable_ingest
- testdata/format_major_version_pebblev1_migration
Currently, the `FormatPrePebblev1MarkedCompacted` (enum value `11`) is used as a synchronization point for the DB, ensuring that all pre-Pebblev1 tables have been rewritten. This format major version is implicitly tied to a Cockroach internal cluster version that ships in the 23.1 release. Not only is an implicit Pebble FMV upgrade confusing, it unnecessarily blocking.
Rather than blocking the finalization of 23.1, the decision was made to instead alter Cockroach to ensure that all tables had been rewritten before ratcheting the Pebble FMV.
Rename the existing FMV for the blocking re-write. The version was renamed to include `Unused`, along with a comment detailing the reasoning.
Move the existing FMV, `FormatPrePebblev1MarkedCompacted`, to be the latest in the sequence of FMVs, in a …
> db: reorder existing format major version for pre-Pebblev1 tables

- db.go
- objstorage/provider.go
- objstorage/provider_test.go
- objstorage/shared.go
- open.go
Add SetCreatorID method to initialize the shared object creator ID. Update the provider code to tolerate asynchronous initialization of the shared subsystem.
> db: add SetCreatorID

- objstorage/noop_readahead.go
- objstorage/provider.go
- objstorage/shared_readable.go
- objstorage/vfs_readable.go
- sstable/reader.go
- sstable/suffix_rewriter.go
This name is too specific - read-ahead is just one possible optimization. The idea as far as the API is concerned is that related operations should go through the same handle so they can benefit from internal optimizations.
> objstorage: rename ReadaheadHandle to ReadHandle

- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
- options.go
- options_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
Add a unit test that ensures that Options set by the metamorphic tests survive a serialization and deserialization roundtrip. The top-level metamorphic test propagates the options to sub-runs through a serialized OPTIONS file, so varying OPTIONS must be serialized to be tested.
Fix the LevelOptions.BlockSizeThreshold field that was not serialized, and wasn't effectively tested within the metamorphic tests.
This change also inverts the `useBlockPropertyCollector` option to be `disableBlockPropertyCollector` to play a little better with the default of using the collector.
> metamorphic: add unit test for Options propagation

- compaction.go
- compaction_test.go
- data_test.go
- db_test.go
- event_listener_test.go
- external_iterator_test.go
- ingest_test.go
- internal/metamorphic/ops.go
- iterator_test.go
- level_checker_test.go
- level_iter_test.go
- merging_iter_test.go
- objstorage/provider.go
- objstorage/provider_test.go
- objstorage/shared_writable.go
- objstorage/vfs_writable.go
- range_del_test.go
- sstable/reader_test.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/table_test.go
- sstable/writer.go
- sstable/writer_rangekey_test.go
- sstable/writer_test.go
- table_stats_test.go
- testdata/ingest_load
- tool/make_test_find_db.go
- tool/make_test_sstables.go
- version_set_test.go
We weren't checking the error returned from `Close`. It turns out that
some testcases were hitting the error but passing anyway; updating
the directives to set the necessary table version.
Improve the writable API to more closely match its actual usage.
Simplify `Write` to not return a length, and replace `Sync` and
`Close` with `Finish` and `Abort`.
`vfs.File` can no longer be used as a `Writable`; we provide access to
the objstorage file implementation for tests.
> objstorage: better Writable API

- level_iter.go
It's much easier to navigate code when using interfaces instead of passing around `func`s (e.g. you can easily find all implementations).
Change `tableNewIters` to a new `tableIterFactory` interface. We also improve the documentation and clean up the main implementation (adding some missing error path cleanup).
> db: improve documentation of tableNewIters

- sstable/writer.go
`Close()` records any error encountered and exits early if called again. One of the return paths was not setting `w.err`, possibly causing the panic in github.com/cockroachdb/cockroach/issues/97350.
This change fixes this and improves the structure of the function - instead of each exit path having to set `w.err`, we set it in the deferred function.
> sstable: fix error path in writer.Close

- tool/data/lsm.js
https://github.com/cockroachdb/pebble/issues/2383
**tool: implement 04efab2 in proper place to avoid generate staleness**
04efab2 added pretty-printed keys to the LSM visualization tool. It did this by updating a generated file. This commit updates the file that generates that file instead.
Release note: None.
To test, I did the following:
```
~/g/s/g/c/p/tool [fix_generate] $ bash make_lsm_data.sh
~/g/s/g/c/p/tool [fix_generate] $ git status
On branch fix_generate
nothing to commit, working tree clean
```
> tool: implement 04efab2 in proper place to avoid generate staleness

- event.go
- options.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- vfs/fd_test.go
Closes https://github.com/cockroachdb/cockroach/issues/67856. Previous work at https://github.com/cockroachdb/cockroach/pull/95436 & https://github.com/cockroachdb/pebble/pull/2255.
**vfs: include size of write in DiskSlowInfo**
This commit adds the size of a write to DiskSlowInfo, in cases where a write is sized. A small write stalling out points at file system / disk issues, while a large write taking time to complete may indicate CRDB issues with a certain workload, etc.
> vfs: include size of write in DiskSlowInfo

- Makefile
Now that a Pebble branch for 23.1 has been created, update runs of `make stress-crossversion` on master to test 23.1 separately from master. I've left testing of 21.2 for now.
The Nightly Pebble Metamorphic Crossversion teamcity configuration has also been updated to add `crl-release-23.1` to the command arguments.
> Makefile: update `stress-crossversion` to exercise 23.1

- internal/keyspan/level_iter_test.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/testdata/version_edit_apply
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- replay/replay.go
- tool/db.go
- tool/manifest.go
- version_set.go
Makes bulk version edit accumulation consistent with respect
to files being added and removed from a level; a file added
and deleted from the same level in the same bulk version edit
is no longer tracked in BulkVersionEdit.Added/Deleted.
We also explicitly write down the invariants which aid in proving
the correctness of the new approach.
We also separate out `BulkVersionEdit.Apply` into
`BulkVersionEdit.Apply` and `AccumulateAndApplySingleVE`. It's
easier to reason about accumulation/apply/zombie tables if we
have stricter invariants about when these functions are called.
> manifest: refactor BulkVersionEdit for consistency

- sstable/data_test.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/testdata/rewriter
- sstable/testdata/rewriter_v3
The code was broken both for v2=>v3 and v3=>v2 transitions. The modified test would catch both bugs. The test now also verifies that the vanilla rewrite and this optimized rewrite produce the same output.
Informs https://github.com/cockroachdb/cockroach/issues/97076
> sstable: fix RewriteKeySuffixes to disallow format changes

- internal/lint/lint_test.go
Bump crlfmt to pick up a change that ignores files/directories removed while walking the filesystem tree.
> internal/lint: bump crlfmt version used

- ingest.go
- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
- options.go
Convert the Experimental.DisableIngestAsFlushable setting to a function, allowing the client to disable ingesting sstables as flushable at runtime. This will be used to tie the setting to a cluster setting in CockroachDB.
This will be backported to 23.1.
Informs cockroachdb/cockroach#97194.
> db: use function for Experimental.DisableIngestAsFlushable

- internal/lint/lint_test.go
This is a backport of #2397 to 23.1.
---
Bump crlfmt to pick up a change that ignores files/directories removed while walking the filesystem tree.
> crl-release-23.1: internal/lint: bump crlfmt version used

- compaction.go
- event.go
- event_listener_test.go
- metrics.go
- metrics_test.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/testdata/db_lsm
This is a backport of #2389 to 23.1.
---
The new flushable ingest is designed to allow tables to be lazily ingested in the case where there is overlap with the memtable. To provide visibility into how the feature is being used, add two new flush metrics - a counter for each flushable ingest, and a counter for the number of bytes ingested as flushables.
Add the two new counts to the `Metrics` output. The formatting was altered slightly to improve the alignment.
Enhance the event logging for flushable ingests by printing the level into which the table is ingested.
> crl-release-23.1: db: add metrics for flushable ingests; improve logging

- replay/replay.go
- replay/replay_test.go
Expose the delay introduced by the replay pacer as a benchmark metric. This can help in interpreting other benchmark results.
> replay: expose pace delay as a benchmark metric

- ingest.go
- internal/metamorphic/options.go
- internal/metamorphic/options_test.go
- options.go
23.1 backport of #2398.
----
Convert the Experimental.DisableIngestAsFlushable setting to a function, allowing the client to disable ingesting sstables as flushable at runtime. This will be used to tie the setting to a cluster setting in CockroachDB.
Informs cockroachdb/cockroach#97194.
> crl-release-23.1: db: use function for Experimental.DisableIngestAsFlushable

- compaction.go
- event.go
- metrics.go
- metrics_test.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/testdata/db_lsm
**db: tweak ingest-as-flushable metrics**
Currently, the metric for ingest-as-flushable counts the number of
tables ingested, rather than the number of flushes that are handling
ingested tables. This can be confusing to the operator.
Switch the existing metric to count the flushes handling ingested
tables.
Introduce a separate metric tracking the count of tables ingested as
flushables.
---
**db: fix redaction of ingest-as-flushable filenum**
The filenum is currently not marked as safe for redaction, which results
in the field being delimited with redaction markers in Cockroach log
files.
As the file number is not sensitive, mark the field as safe.
> db: ingest-as-flushable metric and logging tweaks

- compaction.go
- event.go
- metrics.go
- metrics_test.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/testdata/db_lsm
This is a backport of #2408 to 23.1.
---
**db: tweak ingest-as-flushable metrics**
Currently, the metric for ingest-as-flushable counts the number of
tables ingested, rather than the number of flushes that are handling
ingested tables. This can be confusing to the operator.
Switch the existing metric to count the flushes handling ingested
tables.
Introduce a separate metric tracking the count of tables ingested as
flushables.
---
**db: fix redaction of ingest-as-flushable filenum**
The filenum is currently not marked as safe for redaction, which results
in the field being delimited with redaction markers in Cockroach log
files.
As the file number is not sensitive, mark the field as safe.
> crl-release-23.1: flushable metrics fixes

- internal/metamorphic/history.go
- internal/metamorphic/history_test.go
- internal/metamorphic/key_manager.go
- internal/metamorphic/meta.go
- internal/metamorphic/meta_test.go
Refactor the metamorphic tests to expose a package interface that allows other packages to invoke the metamorphic tests. Future work will build on this to move the package interface into a non-internal package (so that it may be invoked from the Cockroach repo) and expose additional options for configuring the runs.
Eventually, I'd like to invoke the metamorphic tests with some runs using the encryption-at-rest filesystem.
> internal/metamorphic: refactor to expose package interface

- compaction_test.go
- objstorage/provider.go
- objstorage/provider_test.go
- objstorage/vfs.go
- sstable/data_test.go
- sstable/reader_test.go
- table_cache.go
- tool/db.go
Add an `OpenOptions` struct and remove the `OpenForReadingMustExist` variant.
> objstorage: add OpenOptions

- internal/manifest/version.go
- table_stats.go
- testdata/compaction_tombstones
- testdata/table_stats
Previously, a file in L6 that contained range deletion(s) was assumed to contain range deletions due to open snapshots at the time it was written. Table stats, and in particular the RangeDeletionBytesEstimate value, was calculated assuming the range deletion dropped all keys within the sstable that fall within the range deletion's bounds. This is a decent heuristic for when snapshots were indeed open, preventing the elision of the range deletion.
However, Cockroach KV snapshot reception writes range deletions to each of the ingested sstables (see cockroachdb/cockroach#44048). These range deletions delete nothing within the tables themselves. They exist only to clear out existing state below the table in the LSM. In these cases, the RangeDeletionBytesEstimate value would be a gross …
> db: adjust range-del bytes estimate for L6 files

- Makefile
- compaction.go
- objstorage/objstorage.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_off.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_on.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_test.go
- objstorage/objstorageprovider/provider.go
- sstable/reader.go
- sstable/value_block.go
- table_cache.go
This commit adds an obj IO tracing subsystem. It works by wrapping `Readable` and `Writable` in implementations which generate tracing events. The events are dumped to `IOTRACE-<timestamp>` files in the store directory. Contexts are used to plumb various details, like LSM level or block type.
The tracing code is behind the `pebble_obj_io_tracing` build tag; this is to avoid causing any regressions to normal build.
The plumbing of details through contexts is not (nor it is intended to be) complete.
A new make target `testobjiotracing` runs the test (which requires the `pebble_obj_io_tracing` tag).
> objstorage: implement tracing

- ingest.go
- ingest_test.go
The IngestWithStats ingestion entrypoint returns statistics about the ingest. Cockroach uses these statistics to inform admission control. During a flushable ingest, at commit time the number of bytes that will be ingested into L0 is unknown. This commit adds an approximation based on which tables overlapped the flushable queue. This required adjusting the memtable overlap logic to avoid short circuiting as soon as overlap is found.
This approximation is rough and may be improved with future work, such as #2112.
Close #2421.
Informs #2112.
Informs cockroachdb/cockroach#100149.
> db: populate return statistics for flushable ingests

- ingest.go
- ingest_test.go
23.1 backport of #2425.
----
The IngestWithStats ingestion entrypoint returnrs statistics about the ingest. Cockroach uses these statistics to inform admission control. During a flushable ingest, at commit time the number of bytes that will be ingested into L0 is unknown. This commit adds an approximation based on which tables overlapped the flushable queue. This required adjusting the memtable overlap logic to avoid short circuiting as soon as overlap is found.
This approximation is rough and may be improved with future work, such as #2112.
Informs #2421.
Informs #2112.
Informs cockroachdb/cockroach#100149.
> crl-release-23.1: db: populate return statistics for flushable ingests

- compaction_picker.go
- data_test.go
- internal/manifest/level_metadata_test.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- iterator.go
- iterator_test.go
- table_stats.go
- version_set_test.go
This commit changes the atomic fields in FileMetadata to use atomic
types.
The `StatsValidLocked` function is removed; this was not much of an
optimization - on x86 an atomic load is just a regular load
(https://github.com/golang/go/blob/master/src/runtime/internal/atomic/atomic_amd64.go#L29).
> manifest: use atomic types in FileMetadata

- objstorage/objstorageprovider/provider.go
- objstorage/objstorageprovider/shared.go
- objstorage/objstorageprovider/shared_backing.go
- objstorage/objstorageprovider/testdata/provider/shared_attach_after_unref
- objstorage/shared/logging.go
- objstorage/shared/mem.go
- objstorage/shared/storage.go
This commit adds a IsNotExist error to shared.Storage and addresses some relevant TODOs.
Note that the CockroachDB implementation of `cloud.ExternalStorage` already uses a special error for this, so this should be easy to wire up.
> shared: add IsNotExistError method to shared.Storage

- sstable/filter.go
- table_cache.go
FilterMetrics is used both to pass around the current values of the metrics and to maintain them internally. In the latter case, the accesses are atomic.
This commit adds `AtomicFilterMetrics` for internal use, which clarifies the code and allows use of `atomic.Int64`.
> sstable: add AtomicFilterMetrics

- ingest.go
- internal/manifest/version.go
- testdata/event_listener
- testdata/metrics
Previously, when determining the level in which to ingest a new file,
we would iterate over every file in L0 to check for overlap. With this change,
we instead iterate over every sublevel to check for overlap. This is more
efficient since the number of sublevels in L0 is <= the number of files in L0.
Closes: https://github.com/cockroachdb/pebble/issues/2329
Epic: None
> *: check L0 sublevel metadata when ingesting files

- external_iterator_test.go
- sstable/block_property.go
- sstable/block_property_test.go
- sstable/reader_test.go
- table_cache.go
Previously, if block-property filters were in use and a sstable was found to NOT intersect the filters, the allocated BlockPropertiesFilterer was dropped instead of being returned to the pool.
This commit refactors the sstable package's interface to hide the IntersectsUserPropsAndFinishInit function's subtle semantics behind a new IntersectsTable function that returns a new filterer if the table intersects the provided filters. If the table does not intersect the provided filters, the obtained filterer is automatically returned to the sync pool.
This was discovered while looking at the RefreshRange regression in cockroachdb/cockroach#98881, although I believe the logic was the same in 22.2, and this is not the source of the regression.
``` …
```
> sstable: reuse block property filterers in all cases

- sstable/internal.go
- sstable/testdata/writer
- sstable/writer.go
- sstable/writer_test.go
Previously, the sstable property recording the number of deletion tombstones within a file included DELs and RANGEDELs but not SINGLEDELs. This caused SINGLEDELs to be excluded from point tombstone compaction heuristics that use these properties to estimate the amount of disk space that may be reclaimed by compacting a file.
> sstable: include SINGLEDELs within NumDeletions table property

- sstable/internal.go
- sstable/testdata/writer
- sstable/writer.go
- sstable/writer_test.go
Backport of #2445 for 23.1.x.
----
Previously, the sstable property recording the number of deletion tombstones within a file included DELs and RANGEDELs but not SINGLEDELs. This caused SINGLEDELs to be excluded from point tombstone compaction heuristics that use these properties to estimate the amount of disk space that may be reclaimed by compacting a file.
> crl-release-23.1: sstable: include SINGLEDELs within NumDeletions table property

- tool/tool.go
This method will be used to enable shared storage for `cockroach debug pebble`.
> tool: add EnableSharedStorage method

- objstorage/noop_readahead.go
- objstorage/objstorage.go
- objstorage/objstorageprovider/provider_test.go
- objstorage/objstorageprovider/shared_readable.go
- objstorage/objstorageprovider/vfs_readable.go
- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/table.go
- vfs/mem_fs.go
The MemFS implementation of `ReadAt` does not conform to the spec: an
error must be returned if `n < len(p)`. If we are at the end of the
file, we need to return `io.EOF`.
Minor change to the `readFooter` code to never try to read past
object EOF.
Simplify `ReadAt` to only return an error; the `n` return value is no
longer used.
Unlike `ReadHandle.ReadAt`, `Readable.ReadAt` must support concurrent
calls.
Note that most of the performance sensitive paths use `ReadHandle`.
This fixes an occasional race failure in CI.
> objstorage: simplify ReadAt for objects

- checkpoint.go
- checkpoint_test.go
- record/record.go
When a checkpoint is restricted to a set of spans, we append a record to the checkpoint's manifest removing all the excluded ssts.
We append the record after copying the raw data from the existing manifest. This is not quite ok: the `record` library works by breaking up records in chunks and packing chunks into 32KB blocks. Chunks cannot straddle a 32KB boundary, but this invariant is violated by our append method. In practice, this only happens if the record we are appending is big and/or we are very unlucky and the existing manifest is close to a 32KB boundary.
To fix this: instead of doing a raw data copy of the existing manifest, we copy at the record level (using a record reader and a record writer). Then we can add a new record using the same writer.
Informs …
> db: fix bug with restricted checkpoints

- ingest.go
- objstorage/objstorage.go
- objstorage/objstorageprovider/provider.go
- objstorage/objstorageprovider/provider_test.go
- objstorage/objstorageprovider/testdata/provider/local
- objstorage/objstorageprovider/testdata/provider/shared_basic
- objstorage/objstorageprovider/testdata/provider/shared_no_ref
Implement missing functionality in LinkOrCopyFromLocal: we now pass `CreateOptions` and the destination object can be on shared storage.
> objstorage: support LinkOrCopyFromLocal to shared storage

- internal/manifest/l0_sublevels.go
- internal/manifest/testdata/l0_sublevels
Previously, a buggy conditional meant that we could let incremental L0 sublevel generation (i.e. `AddL0Files`) continue chugging along even if the incoming file would get a lower sublevel than an existing L0 file in the same key interval. This can lead to invalid intra-L0 compaction picking, that can elevate rangedels above keys that they should not be deleting. We need to throw away the incrementally generated L0Sublevels object in this case and start from scratch, which is what this change does.
Fixes #2474.
Fixes cockroachdb/cockroach#101896.
Informs #2475.
> manifest: Enforce incremental L0 generation invariant

- internal/manifest/l0_sublevels.go
- internal/manifest/testdata/l0_sublevels
Previously, a buggy conditional meant that we could let incremental L0 sublevel generation (i.e. `AddL0Files`) continue chugging along even if the incoming file would get a lower sublevel than an existing L0 file in the same key interval. This can lead to invalid intra-L0 compaction picking, that can elevate rangedels above keys that they should not be deleting. We need to throw away the incrementally generated L0Sublevels object in this case and start from scratch, which is what this change does.
Fixes #2474.
Fixes cockroachdb/cockroach#101896.
Informs #2475.
> [crl-release-23.1] manifest: Enforce incremental L0 generation invariant

- internal/manifest/l0_sublevels.go
- internal/manifest/testdata/l0_sublevels
Previously, a buggy conditional meant that we could let incremental L0 sublevel generation (i.e. `AddL0Files`) continue chugging along even if the incoming file would get a lower sublevel than an existing L0 file in the same key interval. This can lead to invalid intra-L0 compaction picking, that can elevate rangedels above keys that they should not be deleting. We need to throw away the incrementally generated L0Sublevels object in this case and start from scratch, which is what this change does.
Fixes #2474.
Fixes cockroachdb/cockroach#101896.
Informs #2475.
> [crl-release-22.1] manifest: Enforce incremental L0 generation invariant

- internal/manifest/l0_sublevels.go
- internal/manifest/testdata/l0_sublevels
Previously, a buggy conditional meant that we could let incremental L0 sublevel generation (i.e. `AddL0Files`) continue chugging along even if the incoming file would get a lower sublevel than an existing L0 file in the same key interval. This can lead to invalid intra-L0 compaction picking, that can elevate rangedels above keys that they should not be deleting. We need to throw away the incrementally generated L0Sublevels object in this case and start from scratch, which is what this change does.
Fixes #2474.
Fixes cockroachdb/cockroach#101896.
Informs #2475.
> [crl-release-22.2] manifest: Enforce incremental L0 generation invariant

- objstorage/vfs_readable.go
- sstable/reader.go
Backport of #2481.
----
This commit adds a "shortcut" through objstorage which allows using a preallocated read handle. This avoids two sync.Pool-backed allocations in `singleLeveliter.init`.
Informs https://github.com/cockroachdb/cockroach/issues/101299.
> crl-release-23.1: sstable: optimize NewReadHandle allocations

- db.go
- tool/db.go
- tool/db_io_bench.go
This commit adds an `io-bench` command to the `db` tool. This tool performs IOs against the sstables of an existing database. It is meant to study the IO size vs latency behavior of shared object storage.
Sample output (local SSD):
```
IO count: 10000  Parallelism: 16  Levels: L5,L6
4KB  --  avg 0.01ms   stddev 0.17ms   p10 0.00ms   p50 0.00ms   p90 0.01ms   p95 0.01ms   p99 0.02ms
16KB  --  avg 0.01ms   stddev 0.18ms   p10 0.01ms   p50 0.01ms   p90 0.01ms   p95 0.02ms   p99 0.03ms
64KB  --  avg 0.03ms   stddev 0.15ms   p10 0.02ms   p50 0.03ms   p90 0.04ms   p95 0.05ms   p99 0.11ms
256KB  --  avg 0.12ms   stddev 0.36ms   p10 0.06ms   p50 0.10ms   p90 0.14ms   p95 0.17ms   p99 0.30ms
1024KB  --  avg 0.43ms   stddev 0.40ms   p10 0.24ms   p50 0.40ms   p90 0.56ms   p95 0.67ms   p99 1.17ms
```
> tool: add db io-bench command

- metamorphic/meta.go
- metamorphic/options.go
- metamorphic/options_test.go
- metamorphic/test.go
Allow external packages to include custom options that are serialized under the [TestOptions] stanza, and provide hooks to call into custom options during test execution. This commit will be used to construct a Cockroach encryption-at-rest test that runs the metamorphic tests with an encrypted FS.
Paired with the strictFS option, this will improve our test coverage of encryption-at-rest crash recovery.
> metamorphic: add support for custom options

- sstable/format.go
- sstable/format_test.go
- sstable/table.go
- tool/testdata/sstable_check
- tool/testdata/sstable_properties
Currently, if the magic number in an SSTable footer is invalid, an error is printed indicating as such. However, it would be useful to know what the magic number was for the SSTable. This allows for potentially faster issue triaging.
Print the magic number bytes when encountering an invalid table magic number.
> sstable: print magic number when encountering corruption

- sstable/format.go
- sstable/format_test.go
- sstable/table.go
- tool/testdata/sstable_check
- tool/testdata/sstable_properties
This is a backport of #2492 to 22.1.
---
Currently, if the magic number in an SSTable footer is invalid, an error is printed indicating as such. However, it would be useful to know what the magic number was for the SSTable. This allows for potentially faster issue triaging.
Print the magic number bytes when encountering an invalid table magic number.
> crl-release-22.1: sstable: print magic number when encountering corruption

- sstable/format.go
- sstable/format_test.go
- sstable/table.go
- tool/testdata/sstable_check
- tool/testdata/sstable_properties
This is a backport of #2492 to 23.1.
---
Currently, if the magic number in an SSTable footer is invalid, an error is printed indicating as such. However, it would be useful to know what the magic number was for the SSTable. This allows for potentially faster issue triaging.
Print the magic number bytes when encountering an invalid table magic number.
> crl-release-23.1: sstable: print magic number when encountering corruption

- objstorage/objstorageprovider/shared_readable.go
- objstorage/objstorageprovider/testdata/provider/shared_attach
- objstorage/objstorageprovider/testdata/provider/shared_basic
- objstorage/objstorageprovider/testdata/provider/shared_no_ref
Instead of serializing all `ReadAt` calls against a `Readable`, use a temporary throw-away handle. The end result is similar (we don't expect to be able to reuse the underlying reader in the common case) but without serialization.
Reads without a ReadHandle happen for various sst metadata (like index or filter blocks).
> objstorage: don't use mutex in sharedReadable.ReadAt

- db.go
- open.go
The DB.mu.mem.cond condition variable is no longer used. It previously was intended to synchronize concurrent callers of makeRoomForWrite during a memtable rotation, but that function requires that the commit pipeline's mutex be held throughout the entirety of the function, providing mutual exclusion.
This condition variable is now only broadcasted, without any waiters.
> db: remove unused condition variable

- ingest.go
- ingest_test.go
- internal/manifest/version_edit.go
Pebble's consistency relies on maintaining the sequence number invariant: for
two internal keys k#s1 and k#s2 with the same user key and s1 < s2, k#s2 must
be in a higher level of the LSM.
Previously, it was possible for a sequence number inversion to occur during a
concurrent ingest and batch application writing to the same key. If the ingest
acquired its sequence number before the batch, but the batch application
completed first AND the containing memtable flushed first, the batch's higher
sequenced key could exist below the older conflicting key.
Informs #2196.
> db: synchronize ingests with flushes of later memtables

- vfs/disk_health.go
When a disk stall is detected, the operation and path of the file are logged. Currently, in Cockroach, the path is redacted as it is not marked as safe.
As a path in a production environment could contain sensitive information (we have no control over how a user configures the directory in which they use for the Pebble store), we want to avoid leaking too much information. Only take the basename of the file, and mark this as safe. The filenames that Pebble uses are well-formed, and should not contain sensitive information.
Touches cockroachdb/cockroach#99756.
> vfs: mark file basename as safe to avoid log redaction

- Makefile
Currently, the cross-version makefile target infers the latest release version by querying git. While this is suitable for the master branch, on a release branch the latest version should be "capped" so as to avoid building against a later version.
Pin the latest release for the crl-release-22.2 branch.
> crl-release-22.2: makefile: pin latest release version for cross-version tests to 22.2

- db.go
- open.go
- open_test.go
- options.go
Allow callers of Open to acquire the database directory's file lock in advance of Open. This allows clients like Cockroach to use the existing LOCK file to protect additional on-disk data within the database directory. This is preferrable to a separate file lock, because in a mixed version scenario it avoids a newer version mutating state in use by a running process of a previous version.
Informs cockroachdb/cockroach#98294.
> db: allow locking directory before Open

- sstable/properties.go
- sstable/properties_test.go
- sstable/testdata/writer_value_blocks
- sstable/writer.go
- table_stats.go
- testdata/compaction_tombstones
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- testdata/table_stats
Pebble's compaction heuristics estimate the amount of disk space that will be reclaimed by compacting a file due to point tombstones contained within a file. This estimate is used to increase the priority of compacting these files by inflating the file size during level scoring and file picking.
Previously, these heuristics relied on average key sizes to estimate the space reclaimed by tombstones. Depending on the density of point tombstones, this average was computed over the table's own keys or over all overlapping tables in lower levels.
This commit updates this estimation to instead use a new sstable property that totals all point tombstones' key sizes within a file. This exact sum of the logical bytes that will be reclaimed through compaction, removing all error from uneven …
> db: use exact accounting of point tombstone key sizes

- testdata/compaction_tombstones
This is a backport of #2239 to 22.2.
---
Fixing flaky test case caused by an automatic compaction.
Fixes #2033
> crl-release-22.2: deflake TestCompactionTombstones

- sstable/format.go
- sstable/format_test.go
- sstable/table.go
- tool/testdata/sstable_check
- tool/testdata/sstable_properties
This is a backport of #2492 to 22.2.
---
Currently, if the magic number in an SSTable footer is invalid, an error is printed indicating as such. However, it would be useful to know what the magic number was for the SSTable. This allows for potentially faster issue triaging.
Print the magic number bytes when encountering an invalid table magic number.
> crl-release-22.2: sstable: print magic number when encountering corruption

- db.go
- open.go
- open_test.go
- options.go
23.1 backport of #2498.
----
Allow callers of Open to acquire the database directory's file lock in advance of Open. This allows clients like Cockroach to use the existing LOCK file to protect additional on-disk data within the database directory. This is preferrable to a separate file lock, because in a mixed version scenario it avoids a newer version mutating state in use by a running process of a previous version.
Informs cockroachdb/cockroach#98294.
> crl-release-23.1: db: allow locking directory before Open

- event.go
- options.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- vfs/fd_test.go
This is a backport of #2281 and #2499 to 23.1.
---
**vfs: include size of write in DiskSlowInfo**
This commit adds the size of a write to DiskSlowInfo, in cases where a write is
sized. A small write stalling out points at file system / disk issues, while
a large write taking time to complete may indicate CRDB issues with a certain
workload, etc.
**vfs: mark file basename as safe to avoid log redaction**
When a disk stall is detected, the operation and path of the file are
logged. Currently, in Cockroach, the path is redacted as it is not
marked as safe.
As a path in a production environment could contain sensitive
information (we have no control over how a user configures the directory
in which they use for the Pebble store), we want to avoid leaking too
much information. Only take the …
> crl-release-23.1: vfs: include size of write in DiskSlowInfo

- db.go
- open.go
- open_test.go
- options.go
22.2 backport of #2498.
----
Allow callers of Open to acquire the database directory's file lock in advance of Open. This allows clients like Cockroach to use the existing LOCK file to protect additional on-disk data within the database directory. This is preferrable to a separate file lock, because in a mixed version scenario it avoids a newer version mutating state in use by a running process of a previous version.
Informs cockroachdb/cockroach#98294.
> crl-release-22.2: db: allow locking directory before Open

- ingest.go
- ingest_test.go
- internal/manifest/version_edit.go
22.2 backport of #486.
----
Pebble's consistency relies on maintaining the sequence number invariant: for two internal keys k#s1 and k#s2 with the same user key and s1 < s2, k#s2 must be in a higher level of the LSM.
Previously, it was possible for a sequence number inversion to occur during a concurrent ingest and batch application writing to the same key. If the ingest acquired its sequence number before the batch, but the batch application completed first AND the containing memtable flushed first, the batch's higher sequenced key could exist below the older conflicting key.
Informs #2196.
> crl-release-22.2: db: synchronize ingests with flushes of later memtables

- internal/manifest/version.go
- internal/manifest/version_edit.go
This change verifies that the output of incrementally generated L0 sublevels matches that of a regenerated L0 sublevels, if invariants build flag is enabled.
Fixes #2475.
> internal/manifest: verify incremental L0 sublevel output

- Makefile
The latest crlfmt version tries to make a lot of (bad) comment changes. Until this is addressed, we fix the version used for `make format/format-check`.
> Makefile: fix crlfmt version

- sstable/reader.go
- table_cache.go
keyOutOfBounds is called deep in the iterator function call stack and should be inlined.
> sstable: inline keyOutOfBounds

- mem_table.go
- mem_table_test.go
(backport)
Informs https://github.com/cockroachdb/cockroach/issues/102945
Fixes #2516
> db: intialize memTable.reserve when creating memTable

- mem_table.go
- mem_table_test.go
22.2 backport of #2517.
----
Informs cockroachdb/cockroach#102945
Informs #2516
> crl-release-22.2: db: intialize memTable.reserve when creating memTable

- ingest.go
- testdata/event_listener
Previously, ingestions would trigger obsolete file deletions during the ingest application step. This has the potential to exacerbate the write "hiccup"/stall induced by sstable ingestion. The sequence numbers assigned to the ingestion are not published until after ingestion application. This prevents any concurrent writes that obtained later sequence numbers from publishing their own sequence numbers.
When Options.Experimental.MinDeletionRate is configured, this step to delete obsolete files should have minimal impact. However, when Experimental.MinDeletionRate is not configured, the ingesting goroutine would synchronously perform file deletions, extending the length of the commit stall.
Now ingestions don't trigger deletion of obsolete files. The only file deletion that an ingestion …
> db: don't delete files during ingest application

- event.go
- options.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- vfs/fd_test.go
This backport appears to be origin of recent disk-stall detection roachtest failures (eg, cockroachdb/cockroach#102946). I haven't identified what the exact bug is.
> crl-release-23.1: revert vfs: include size of write in DiskSlowInfo

- event.go
- options.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- vfs/fd_test.go
This un-reverts the two commits from #2525.
> crl-release-23.1: unrevert #2525

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- metrics.go
- open.go
- testdata/event_listener
Compute and calculate two new metrics, `Uptime` and `Compact.Duration` which together may be used to compute the effective compaction concurrency over an interval.
**db: add Uptime metric**
Add a new Metric recording the database's uptime since Open. This can be used
in combination with other metrics to integrate over time.
**db: add Compact.Duration metric**
Add a new Compact.Duration metric that measures the cumulative time spent in
compactions since Open. This may be used in combination with Metrics.Uptime to
compute the effective compaction concurrency (https://github.com/cockroachdb/pebble/issues/1934). Callers may compute
effective compaction concurrency over an interval by measuring both Uptime and
Compact.Duration at the beginning and end of the interval and subtracting.
Close …
> db: expose new metrics for compaction concurrency

- compaction.go
- data_test.go
- format_major_version.go
- options.go
- sstable/format.go
- sstable/format_test.go
- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/table.go
- sstable/testdata/writer_value_blocks
- sstable/writer.go
- table_cache.go
- testdata/format_major_version_pebblev1_migration
This commit defines but leaves unused a new sstable table Pebblev4 that will subsume Pebblev2 and Pebblev3 sstable formats. Future work (#2465, #2340) will require additional sstable table formats. Stabilization of the table format extensions introduced in the Pebblev3 table format is required before that can happen. The new Pebblev4 format will include Pebblev3's extensions. This commit adjusts the code to not respect the Experimental.EnableValueBlocks setting in future format major versions that make use of the Pebblev4 sstable format.
There's some subtlety involved in this change, hence the introduction of the Pebblev4 sstable format before it's used.
> db: add reserved Pebblev4 sstable format

- db_test.go
- ingest_test.go
A few unit tests in the top-level pebble package recently started logging database events (eg, MakeLoggingEventListener) to the DefaultLogger which outputs directly to stdout. This makes `go test` noisy. This commit updates these unit tests to use a logger that logs to the `*testing.T` type, so that the logs are only printed when verbosity is enabled.
> db: log events to testing.T in unit tests

- objstorage/objstorageprovider/shared.go
- objstorage/objstorageprovider/shared_readable.go
- objstorage/objstorageprovider/testdata/provider/shared_attach
- objstorage/objstorageprovider/testdata/provider/shared_basic
- objstorage/objstorageprovider/testdata/provider/shared_no_ref
- objstorage/shared/logging.go
- objstorage/shared/mem.go
- objstorage/shared/storage.go
The current `shared.Storage` interface forces the implementation to perform a metadata operation to look up the object on each read. Some experimental backends have a separate internal open step that doesn't need to be performed every time.
This commit improves the interface to allow opening the object once and then performing many reads.
> shared: improve interface for more efficient reading

- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
Clean up a comment in the sstable suffix rewriter code, and update the test to run subtests across all table formats.
This is response to feedback on #2528 that I forgot to push.
> sstable: clean up suffix rewriter comment, test

- objstorage/noop_readahead.go
- objstorage/objstorage.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_on.go
- objstorage/objstorageprovider/provider_test.go
- objstorage/objstorageprovider/shared_readable.go
- objstorage/objstorageprovider/testdata/provider/shared_readahead
- objstorage/objstorageprovider/vfs_readable.go
- objstorage/shared/storage.go
- sstable/reader.go
Renaming the primitive to be more specific. For compaction reads, we
may want to skip populating caches with the data since it's unlikely
to be used again.
We Reuse the existing ramp-up logic. For now, the max readahead is
256KB but we will probably want to make it configurable and increase
it for shared objects.
> objstorage: implement read-ahead for shared objects

- internal/errorfs/errorfs.go
- objstorage/objstorageprovider/provider.go
- objstorage/objstorageprovider/shared.go
- objstorage/objstorageprovider/shared_cache.go
- objstorage/objstorageprovider/shared_cache_test.go
- objstorage/objstorageprovider/testdata/cache/read_that_hits_two_cache_blocks
- objstorage/objstorageprovider/testdata/cache/read_that_hits_two_cache_blocks_with_first_read_at_big_offset
- objstorage/objstorageprovider/testdata/cache/read_that_hits_two_cache_blocks_with_first_read_at_offset
- objstorage/objstorageprovider/testdata/cache/read_that_hits_two_cache_shards
- objstorage/objstorageprovider/testdata/cache/read_that_hits_two_cache_shards_with_first_read_at_offset
- objstorage/objstorageprovider/testdata/cache/small_read
- objstorage/objstorageprovider/testdata/cache/small_read_with_first_read_at_offset
- vfs/disk_full.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- vfs/mem_fs.go
- vfs/vfs.go
Part of https://github.com/cockroachdb/pebble/issues/2541.
First two commit are authored by @RaduBerinde.
**vfs: support WriteAt**
Add support for opening files in read/write mode and writing at
arbitrary offsets.
**secondarycache: implement a minimal skeleton**
This commit implements a minimal skeleton for the secondary cache. As of this
commit, it is non-functional.
**secondarycache: implement a minimal functional secondary cache**
This commit expands the skeleton added in the last commit to be functional.
This commit also adds basic tests. Concretely, as of this commit, the secondary
cache implements storing cached data on disk, sharding, configurable cache
block sizes, a random eviction scheme, and in-memory metadata (implying the
overall secondary cache empties at restart time). …
> secondarycache: implement a minimal functional secondary cache

- internal/keyspan/span.go
- tool/testdata/wal_dump
- tool/wal.go
Improve the debug tool's output for dumping WALs. Previously, the contents of range keys (start key, end key, suffix and value) were never printed. Additionally, the file number associated with an INGESTSST (encoded within the user key as a varint) was not printed.
> tool: improve `wal dump` output

- compaction.go
- db.go
We were counting flushes for the bytes-in-progress metric (which is not the intention of the metric). When replaying the WAL, we perform a flush but do not clean up the metric, resulting in an one-time leak. The result is that we always see the same non-zero value instead of zero.
The fix is to not count at all during flushes. As a test, we run an invariants-only check on the metrics on close; we could potentially check other things here as well. This new assertion fails without this fix.
Fixes #2548
> db: fix leak for compaction bytes-in-progress metric

- internal/keyspan/span.go
- tool/testdata/wal_dump
- tool/wal.go
Backport of #2552.
----
Improve the debug tool's output for dumping WALs. Previously, the contents of range keys (start key, end key, suffix and value) were never printed. Additionally, the file number associated with an INGESTSST (encoded within the userkey as a varint) was not printed.
> crl-release-23.1: tool: improve `wal dump` output

- objstorage/objstorageprovider/shared_cache.go
- objstorage/objstorageprovider/shared_cache_test.go
- objstorage/objstorageprovider/testdata/cache/read_larger_than_two_cache_shards
- vfs/logging_fs.go
```
$ go test . -tags=invariants -run='TestSharedCacheRandomized' --count=1000
ok  	github.com/cockroachdb/pebble/objstorage/objstorageprovider	50.720s
```
**vfs: add logging for OpenReadWrite & WriteAt**
This commit adds logging for OpenReadWrite & WriteAt to the logging vfs.
**sharedcache: fix two bugs, add assertions & test case**
This commit fixes two bugs which were uncovered initially by the randomized
test that is added in the next commit. This commit adds assertions & a
non-randomized test case also.
The first bug was an incorrect computation of the length of the adjusted buffer
with the desired length being a multiple of the block size. The necessary
adjustment by ofs-adjustedOfs happened in the wrong place in the mathematical
expression computing the desired length of the …
> sharedcache: fix two bugs, add testing & assertions, esp. a randomized test

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- internal/metamorphic/options.go
- open.go
- options.go
- options_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
- table_stats.go
- testdata/compaction_picker_scores
- testdata/compaction_tombstones
- testdata/metrics
23.1 backport of #2550.
----
**db: remove experimental point tombstone weight option**
Remove the experimental point_tombstone_weight option. The introduction of this
option accidentally caused the loss of point tombstone compensation applied to
level scoring. It's been inconculsive whether setting this value >1.0 has ever
helped customers.
**db: consider scheduling compaction when adding point tombstone compensation**
Previously, when the asynchronous table stats collector calculated a positive
PointDeletionsBytesEstimate, it did not consider scheduling compactions unless
it also calculated a positive RangeDeletionsBytesEstimate. If the database was
otherwise quiet with few flushes and no in-progress compactions, this could
delay the scheduling of a compaction until the next flush or …
> crl-release-23.1: point tombstone bug fixes

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- internal/metamorphic/options.go
- open.go
- options.go
- options_test.go
- table_stats.go
- testdata/compaction_picker_scores
- testdata/compaction_tombstones
- testdata/metrics
22.2 backport of #2550.
----
**db: remove experimental point tombstone weight option**
Remove the experimental point_tombstone_weight option. The introduction of this
option accidentally caused the loss of point tombstone compensation applied to
level scoring. It's been inconculsive whether setting this value >1.0 has ever
helped customers.
**db: consider scheduling compaction when adding point tombstone compensation**
Previously, when the asynchronous table stats collector calculated a positive
PointDeletionsBytesEstimate, it did not consider scheduling compactions unless
it also calculated a positive RangeDeletionsBytesEstimate. If the database was
otherwise quiet with few flushes and no in-progress compactions, this could
delay the scheduling of a compaction until the next flush or …
> crl-release-22.2: point tombstone bug fixes

- compaction_test.go
- testdata/compaction_tombstones
Deflake additional test cases within TestCompactionTombstones that are dependent on automatic compactions not removing files before their table stats are queried.
> db: deflake additional TestCompactionTombstones cases

- db.go
- open.go
- open_test.go
- options.go
22.1 backport of #2498. Given the severity, I think we should backport to 22.1 as well.
----
Allow callers of Open to acquire the database directory's file lock in advance of Open. This allows clients like Cockroach to use the existing LOCK file to protect additional on-disk data within the database directory. This is preferrable to a separate file lock, because in a mixed version scenario it avoids a newer version mutating state in use by a running process of a previous version.
Informs cockroachdb/cockroach#98294.
> crl-release-22.1: db: allow locking directory before Open

- compaction.go
- table_cache.go
We recently saw a corruption error in a customer issue: https://github.com/cockroachlabs/support/issues/2340.
We couldn't figure out the sstable which was corrupted because the `bad magic number` error encountered by an sstable reader is currently only annotated with the sstable number for compaction reads.
This pr wraps all errors when we try to create a reader on an sstable with an error message which includes the sstable number.
> db: annotate table number when tables cannot be loaded

- compaction_picker_test.go
- compaction_test.go
- db_test.go
- external_iterator_test.go
- ingest_test.go
- iterator_test.go
- open_test.go
- options_test.go
- scan_internal_test.go
This removes the remaining output written to stdout from the main `pebble` package's unit tests. Running `go test` now prints just the output:
```
PASS
ok  	github.com/cockroachdb/pebble	11.011s
```
> db: avoid logging to stdout in unit tests

- metamorphic/generator.go
In concurrent runs of the metamorphic tests, a closeOp for the DB can race with a deleteOp for the batch. But if we close the batch before closing the db, then it acts as a synchronization point and ensures that all batch operations complete before the db is closed.
Fixes: https://github.com/cockroachdb/pebble/issues/2562
> metamorphic: close batches before closing db

- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- table_stats.go
- tool/make_incorrect_manifests.go
- version_set.go
- version_set_test.go
We introduce three new tags for virtual sstable encoding/decoding.
tagCreatedBackingTable, tagRemovedBackingTable are used to encode
VersionEdit.CreatedBackingTables and VersionEdit.RemovedBackingTables.
For CreatedBackingTables, we just need to encode the DiskFileNum and
the Size, and for RemovedBackingTable, we just need to encode the
DiskFileNum.
We introduce a customTag customTagVirtual, to encode whether the
FileMetadata belongs to a virtual sstable. We only use this tag for
virtual sstables. If this tag is absent, then the FileMetadata belongs
to a physical sstable. This tag is also used to encode
FileMetadata.FileBacking.DiskFileNum for virtual sstables.
Note that virtual sstable construction depends on state which may
not exist in the version edit in which the virtual sstable is …
> manifest: support ve encoding/decoding for virtual sstables

- objstorage/objstorageprovider/shared.go
- objstorage/objstorageprovider/shared_readable.go
- objstorage/objstorageprovider/sharedcache/shared_cache.go
- objstorage/objstorageprovider/sharedcache/shared_cache_test.go
- objstorage/objstorageprovider/sharedcache/testdata/cache/compaction_reads
- objstorage/objstorageprovider/sharedcache/testdata/cache/read_larger_than_two_cache_shards
- objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_blocks
- objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_blocks_with_first_read_at_big_offset
- objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_blocks_with_first_read_at_offset
- objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_shards
- objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_shards_with_first_read_at_offset
- objstorage/objstorageprovider/sharedcache/testdata/cache/small_read
- objstorage/objstorageprovider/sharedcache/testdata/cache/small_read_with_first_read_at_offset
This commit adds code to optionally use the shared cache when reading from an object.
When the read is for a compaction, we don't want to populate the cache (but we do want to read from it if the data is already there).
> objstorageprovider: use cache in ReadAt

- compaction_test.go
- testdata/manual_compaction_set_with_del_sstable_Pebblev4
The new ExperimentalFormatDeleteSizedAndObsolete format major version can result in sstables with different sizes than before.
> db: fix TestManualCompaction flake

- Makefile
- tool/make_incorrect_manifests.go
- tool/make_test_find_db.go
- tool/make_test_sstables.go
- tool/tool.go
We use `go:generate` to invoke programs that generate tool test data. This test data is non-deterministic (and tests don't generally pass when data is regenerated). This is not appropriate for the `make generate` target which is supposed to be a no-op on a "clean" branch.
This change separates these into a new `generate-test-data` target.
Fixes #2383.
> Makefile: separate target for generating test data

- .github/workflows/ci.yaml
- .github/workflows/sanitizers.yaml
This is a backport of #2601 to 23.1.
---
The ASAN and MSAN pipelines, while useful, often flake out during CI. This can block merging of a patch until fixed.
Move the ASAN and MSAN pipelines to run in a scheduled workflow, daily at midnight UTC.
> crl-release-23.1: ci: move asan / msan to scheduled workflow

- cleaner_test.go
TestCleaner flakes because of table stats are retrieved asynchronously. Disable table stats altogether.
Fixes #2560
> db: fix TestCleaner flake

- format_major_version.go
- format_major_version_test.go
- open_test.go
- testdata/checkpoint
- testdata/event_listener
- testdata/flushable_ingest
- version_set.go
- version_set_test.go
This change adds a specific FormatMajorVersion specifically for the virtual sstable work, as the changes in #2484 are not backward compatible. There's a guard in version application that will error out if we create a backing table without having an appropriate FMV.
Fixes #2557.
> db: Add FormatMajorVersion for virtual sstables

- objstorage/objstorageprovider/shared.go
- objstorage/objstorageprovider/sharedcache/shared_cache.go
- objstorage/objstorageprovider/sharedcache/shared_cache_helpers_test.go
- objstorage/objstorageprovider/sharedcache/shared_cache_test.go
Part of https://github.com/cockroachdb/pebble/issues/2541.
**sharedcache: fix bug that "leaks" cache block indexes**
This commit introduces assertions regarding in-memory shard state such as
s.mu.where & s.mu.free that caught an existing bug in the cache. The bug is:
If concurrent calls to ReadAt are made, then shard.set might be called for
a logical block that is already in the cache. Before this commit, such a
situation would "leak" a cache block, meaning the cache block index would
be removed from s.mu.where, implying the cache block could never be used
again. As of this commit, the bug is fixed.
**sharedcache: move to fine-grained locking**
Before this commit, s.mu was held when s.get & s.set were reading and
writing to s.file. This was done to simplify merging an initial …
> sharedcache: move to fine-grained locking

- objstorage/objstorageprovider/readahead.go
- objstorage/objstorageprovider/readahead_test.go
- objstorage/objstorageprovider/shared_readable.go
- objstorage/objstorageprovider/testdata/provider/shared_readahead
- objstorage/objstorageprovider/vfs_readable.go
This change makes the read-ahead size configurable in the code and sets it to 1MB for shared objects.
We also fix a bug where read-ahead was causing us to read past the end of objects.
> objstorage: increase shared readahead to 1MB, fix EOF bug

- cmd/pebble/ycsb.go
- docs/index.html
In c3bf955f I goofed and misused a rate.Limiter which caused continuous sampling of read amplification. Use an ordinary ticker instead.
> cmd/pebble: fix ycsb/F read amp sampling

- compaction_picker.go
- compaction_picker_test.go
- data_test.go
- testdata/compaction_picker_scores
In #2436 the semantics of d.mu.compact.inProgress changed, and it's now possible for that slice to hold compactions whose version edit has already been applied. During compaction picking, these compactions should not adjust level sizes because the current LSM already reflects the resulting LSM state.
> db: fix size adjustment for in-progress compactions

- ingest.go
After #2486 went in, we added some cases of writerRef/writerUnref without ensuring we schedule a flush after taking away the last writer ref. This resulted in some deadlocks if a future goroutine would wait for a flush while the unreffing goroutine didn't follow the convention of calling maybeScheduleFlush. This change adds those calls.
Fixes #2597.
> [crl-release-23.1] db: Call maybeScheduleFlush after writerUnref

- compaction.go
- data_test.go
- flushable_test.go
- ingest.go
- ingest_test.go
- internal/base/seqnums.go
- internal/keyspan/level_iter.go
- internal/manifest/version.go
- internal/rangekey/coalesce.go
- open.go
- scan_internal.go
- sstable/reader.go
- table_cache.go
- table_stats.go
- testdata/excise
- version_set.go
This change adds an IngestAndExcise operation that does the below additional things alongside a regular ingestion:
1) It ingests some SharedSSTMeta files, which are provider-backed
sstables that could be owned by other nodes.
2) It excises existing sstables within the provided excise span (within
which all sstables from 1 must fit) by creating new virtual sstables
that exclude keys from the excise span.
While this change can be implemented independently of #2455, some of the end-to-end tests in future changes will rely on both that and this.
Fixes #2520.
> *: add IngestAndExcise operation

- compaction_test.go
Skip `TestManualCompaction` until a fix is found. 
Informs: #2613
> Skip TestManualCompaction (flaky)

- db.go
- db_test.go
This change allows users to pass in a `start` and `end` bound option to filter sstables. This will be useful when trying to obtain metrics only for those sstables that intersect this key range.
Informs: https://github.com/cockroachdb/cockroach/issues/102604
> db: Add Option to Filter SSTables

- db.go
- scan_internal.go
- scan_internal_test.go
- snapshot.go
This change updates the ScanInternal function signature to not use the internal keyspan.Key type. Instead we use the new InternalRangeKey type alias that exports it.
Also update the pointCollapsingIter to just call SeekGE in NextPrefix instead of panicking.
Necessary for cockroachdb/cockroach#103028.
> db: don't use internal types in ScanInternal

- objstorage/objstorageprovider/sharedcache/shared_cache.go
- objstorage/objstorageprovider/sharedcache/shared_cache_helpers_test.go
Currently the shared cache performs writes asynchornously, spawning a separate goroutine each time. This is not ideal performance-wise, and can also hit problems related to too many goroutines and/or memory usage.
In this commit we switch to a pool of "write workers".
> sharedcache: use a pool of workers for writes

- compaction_iter.go
- compaction_iter_test.go
- testdata/compaction_iter_delete_sized
This commit refactors elements of #2620 and #2537 to more narrowly define what consitutes a 'missized tombstone.'
Previously, a DELSIZED tombstone could be counted as missized if it deleted a user key that had more than one internal key within the LSM. That lax accounting made it more difficult to use the count for asserting general correctness of client code.  The new calculation ensures that if the most recent version of a key was an accurately-sized SET when the DELSIZED tombstone was committed, the tombstone will not be regarded as missized regardless of internal LSM state.
> db: tighten missized tombstone metric count

- sstable/reader.go
This pr adds bounds checking (global and block) for singleLevelIterator when returning a value.
Fixes: #2593
> sstable: Add bounds checking for virtual sstable iterators

- internal/cache/refcnt_normal.go
- internal/cache/refcnt_tracing.go
The refcnt implementation uses non-atomic assignment on init. Mixing atomic and non-atomic operations is not good and it is conceivable that on some platforms, the non-atomic assignment might not always be "seen" by an atomic operation that happens very soon after.
This change switches to atomic.Int32 wrapper and uses `Store` on init.
Informs cockroachdb/cockroach#84971
> cache: use atomic.Int32 wrappers, fix potential bug

- checkpoint.go
- compaction.go
- db.go
- format_major_version.go
- ingest.go
- open.go
Allow readers of the database's format major version to read the format major version through an atomic load, instead of acquiring the global d.mu. This is particularly important for batch application, which must read the format major version to determine if the batch holds any keys that cannot be applied. Mutex contention during batch application in DB.FormatMajorVersion has been observed in experiments.
> db: don't require holding d.mu to read format major version

- sstable/compression.go
- sstable/compression_test.go
Previously, if decompression failed decompressBlock would discard the error and return a cache.Value that had already been freed. This is possibly related to occurrences of cockroachdb/cockroach#84971.
> sstable: propagate error if decompression fails

- ingest_test.go
- testdata/ingest_shared
This is a test-oriented change that adds more end-to-end testing for
ingesting shared sstables and also reading keys from them.
> db: Add IngestShared test to exercise shared ingestion 

- sstable/compression.go
- sstable/compression_test.go
23.1 backport of #2647.
----
Previously, if decompression failed decompressBlock would discard the error and return a cache.Value that had already been freed. This possibly explains some of the occurrences of cockroachdb/cockroach#84971.
> crl-release-23.1: sstable: propagate error if decompression fails

- sstable/compression.go
- sstable/compression_test.go
22.2 backport of https://github.com/cockroachdb/pebble/pull/2647.
----
Previously, if decompression failed decompressBlock would discard the error and return a cache.Value that had already been freed. This possibly explains some of the occurrences of cockroachdb/cockroach#84971.
> crl-release-22.2: sstable: propagate error if decompression fails

- internal/lint/lint_test.go
- mem_table.go
This commit adds a lint check for using atomic operations like
`atomic.LoadInt32` instead of using a wrapper like `atomic.Int32`. The
wrappers provide much better safety and alignment guarantees (e.g.
with a wrapper you can't accidentally use the value non-atomically).
> lint: add linter for raw atomic operations

- ingest.go
- testdata/ingest_shared
Previously when we called `excise()`, we created new FileMetadata objects without calling ExtendPointKeyBounds and ExtendRangeKeyBounds. During testing we quickly realized that we would result in some instances of us not having the `boundType` set correctly, resulting in panics when we tried to install a file that had a modified boundType.
> ingest: Call Extend{Point,Range}KeyBounds in excise

- metamorphic/generator.go
- metamorphic/ops.go
Added a batch close operation when closing a batch to avoid metamorphic test leaks. Additionally, `g.batchClose` has been renamed to `g.removeBatchFromGenerator`. 
Fixes: #2579
> metamorphic: Batch close operation to `g.BatchClose` and rename function to `removeBatchFromGenerator`

- checkpoint.go
- compaction.go
- db.go
- format_major_version.go
- ingest.go
- open.go
23.1 backport of #2643.
----
Allow readers of the database's format major version to read the format major version through an atomic load, instead of acquiring the global d.mu. This is particularly important for batch application, which must read the format major version to determine if the batch holds keys any keys that cannot be applied. Mutex contention during batch application in DB.FormatMajorVersion has been observed in experiments.
> crl-release-23.1: db: don't require holding d.mu to read format major version

- checkpoint.go
- compaction.go
- db.go
- format_major_version.go
- open.go
22.2 backport of #2643.
----
Allow readers of the database's format major version to read the format major version through an atomic load, instead of acquiring the global d.mu. This is particularly important for batch application, which must read the format major version to determine if the batch holds keys any keys that cannot be applied. Mutex contention during batch application in DB.FormatMajorVersion has been observed in experiments.
> crl-release-22.2: db: don't require holding d.mu to read format major version

- scan_internal.go
- scan_internal_test.go
- testdata/scan_internal
Previously, when we were exporting shared files through truncateSharedFile, and we found no point keys in the relevant span but found range keys (or vice versa), we would leave some of the bounds of the not-found key type set. This could trip up logic elsewhere that relied on null key bounds for keys not present.
> db: Zero out bounds for key type not present in ScanInternal

- commit.go
- ingest.go
Added a semaphore to prevent concurrent ingests from entering the commit pipeline
Fixes: #2487
> pebble: added semaphore to prevent concurrent ingests

- compaction_test.go
This change ensures that `TestManualCompaction` uses table format `TableFormatPebblev1` as the size of the sstable properties block was changed in the following pr https://github.com/cockroachdb/pebble/pull/2585
Fixes: #2613
> pebble: Fix TestManualCompaction Flaky Test

- ingest.go
- ingest_test.go
- internal/manifest/testdata/file_metadata_bounds
- internal/manifest/testdata/level_iterator_filtered
- internal/manifest/testdata/version_check_ordering
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_test.go
- testdata/compaction_picker_scores
- testdata/excise
- testdata/format_major_version_split_user_key_migration
- testdata/marked_for_compaction
Previously, we were leaving the Smallest,Largest SeqNum fields unset in the FileMetadata after we did an excise. This broke snapshot handling even if we weren't reading an excised key range through a snapshot; this is because we could excise a file that has an open snapshot reading some keys but not the exciseed keys, and the new file would contain zero seqnums in its FileMetadata, resulting in incorrect results.
This change fixes this bug, and improves a lot of datadriven testing across the project to better test for seqnum fields in the FileMetadata.
> ingest: Set {Smallest,Largest}SeqNum in Excise

- testdata/manual_compaction_range_keys
When #2670 merged, it did not incorporate a test change from #2677 that necessitated one more datadriven test rewrite, resulting in broken tests on master. This change fixes the merge skew by running `TestManualCompaction` with `-rewrite` to pick up changes from
> testdata: Fix merge skew in TestManualCompaction

- metamorphic/ops.go
Fixes the issue where a batch is closed twice when adding a closeOp after an applyOp. The `batch.close()` call in `applyOp.run` has been removed.
Fixes: #2671
> metamorphic: Fixes duplicate batch close issue

- compaction.go
- ingest.go
- internal/manifest/version.go
- version_set.go
This change reworks the logic to cancel concurrent compactions by moving to a per-compaction cancelled atomic boolean, instead of relying on a boolean in the input FileMetadatas. This is easier for the compaction to check during its execution, reducing the amount of wasted work. It's also more correct as it allows the excising goroutine to error out an entire compaction even if none of its inputs overlapped with the excised span, as there's no guarantee that there won't be an output that overlaps with the excise span even if no inputs overlapped with it.
> db: Refactor compaction cancellation with concurrent excises
