cockroachdb/pebble

db.go, scan_internal.go, testdata/scan_internal
Previously, we'd unintentionally expose newer keys in shared sstables through a snapshot if a compaction pushed keys newer than the snapshot down into a shared level. We can identify this case and return `ErrInvalidSkipSharedIteration`, forcing the caller to resort to non-skip-shared ways to replicate keys.
=> scan_internal: return err if skip-shared breaks snapshot consistency

internal/arenaskl/iterator.go, internal/arenaskl/node.go, internal/arenaskl/skl.go, internal/arenaskl/skl_test.go
Previously, the memtable keys had their trailer encoded after the user key in the same format used within batches or sstables. This adds some minor overhead during iteration, requiring extracting the trailer before key comparisons. This commit lifts the key trailer up into a field on the node struct. While worthwhile in its own right, this also prepares for multiple nodes within the memtable sharing the same copy of the user key (see #2683).
```
│   old2.txt   │               new2.txt               │
│    sec/op    │    sec/op     vs base                │
ReadWrite/frac_0-24                      455.1n ±  4%   409.1n ±  4%  -10.11% (p=0.000 n=10)
ReadWrite/frac_10-24                     423.4n ±  4%   387.5n ±  4%   -8.46% (p=0.000 n=10)
ReadWrite/frac_20-24                     398.4n ± …
```
=> arenaskl: lift key trailer onto node

scan_internal.go
Previously, we were returning an error if the largest seqnum of a file was strictly greater than the snapshot seqnum in skip-shared iteration and the file was in a shared level, for consistency reasons. However as snapshots only make visible keys that are strictly less than the snapshot sequence number, the comparison should have been greater than or equals.
This change resolves that by replacing the comparison with a call to base.Visible.
=> scan_internal: Fix seqnum comparison

cleaner.go, pacer.go, pacer_test.go
Delete pacing is currently an on or off decision. If we are running
out of space or have too many obsolete bytes in relation to live
bytes, we disable pacing. Otherwise we pace at the configured rate
(128MB by default in CRDB).
This change improves pacing by keeping track of the average deletion
rate over the last 5 minutes and increasing the target rate to match
this rate if necessary. The intention is to avoid deletions lagging
behind.
Fixes #2662.
=> db: improve delete pacing

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/shared.go, objstorage/objstorageprovider/sharedcache/shared_cache.go, objstorage/objstorageprovider/sharedcache/shared_cache_helpers_test.go, objstorage/objstorageprovider/sharedcache/shared_cache_test.go
As suggested by @sumeerbhola at https://github.com/cockroachdb/pebble/pull/2561#pullrequestreview-1442486353.
**sharedcache: add test cases that randomize block sizes**
This commit introduces test cases that randomize both the block size & the sharding block size, as suggested by Sumeer with the comment "small block sizes should exercise all the loops relating to slowly filling up the read byte slice".
This commit also fixes a buglet in TestSharedCacheRandomized involving a missing call to writable.Finish.
=> sharedcache: add test cases that randomize block sizes

level_iter.go
Previously we had some cases in the level iter where we'd set the boundary context's fields without checking if a non-nil boundary context existed in the first place. This change fixes that.
=> level_iter: Fix panic in boundaryContext set

db.go, db_test.go, internal/manifest/version.go
This change allows an option `WithApproximateSpanBytes` to be included to a `db.SSTables()` call. This will add a metric `approximateSpanBytes` which will be the number of bytes that overlap the given key span.
More detail in https://github.com/cockroachdb/cockroach/issues/102604#issuecomment-1610052155
Informs: https://github.com/cockroachdb/cockroach/issues/102604
=> pebble: Add option to include `ApproximateSpanBytes` to `db.SSTables()`

record/log_writer.go
A call to cockroachdb/errors.New produces an error with a stack trace which can require allocating several times. Avoid allocating every call to LogWriter.Close.
=> record: don't allocate errors during WAL rotation

objstorage/objstorageprovider/sharedcache/shared_cache_test.go, objstorage/objstorageprovider/sharedcache/testdata/cache/compaction_reads, objstorage/objstorageprovider/sharedcache/testdata/cache/eof_handling, objstorage/objstorageprovider/sharedcache/testdata/cache/lru, objstorage/objstorageprovider/sharedcache/testdata/cache/read_larger_than_two_cache_shards, objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_blocks, objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_blocks_with_first_read_at_big_offset, objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_blocks_with_first_read_at_offset, objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_shards, objstorage/objstorageprovider/sharedcache/testdata/cache/read_that_hits_two_cache_shards_with_first_read_at_offset, objstorage/objstorageprovider/sharedcache/testdata/cache/small_read, objstorage/objstorageprovider/sharedcache/testdata/cache/small_read_with_first_read_at_offset
This commit changes the read/write test directives to use named
arguments. This allows using K/M/G suffixes and makes the tests easier
to read. We also swap the order of offset and size in the tests since
the offset is typically first.
=> sharedcache: data-driven test cosmetic improvements

compaction.go, db.go, open.go, pacer.go, pacer_test.go
Delete pacing is currently an on or off decision. If we are running out of space or have too many obsolete bytes in relation to live bytes, we disable pacing. Otherwise we pace at the configured rate (128MB by default in CRDB).
This change improves pacing by keeping track of the average deletion rate over the last 5 minutes and increasing the target rate to match this rate if necessary. The intention is to avoid deletions lagging behind.
Informs #2662.
I have tested this change against a heavy write workload where deletion is known to lag behind (resulting in 10k+ goroutines waiting in the pacer); with the change, the goroutine count is small and stable (after the first 5-10 minutes):
=> crl-release-23.1: db: improve delete pacing

cmd/pebble/replay.go
Previously, if the user passed --stream-logs or --ignore-checkpoint and with a --count>2, the replay tool would fail on the second run because the bool args would get incorrectly passed to syscall.Exec(). Specifically, for these flags, an additional `true` arg would get passed, which the cobra parser does not appreciate.
=> replay: pass correct replay bool flags on reruns

metamorphic/generator.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, sstable/reader_test.go, sstable/testdata/writer_value_blocks, sstable/writer.go, testdata/compaction_iter_delete_sized
Fix a few bugs in the metamorphic tests' use of format major versions. These bugs were hiding an issue with the new obsolete-bit in the sstable format, and so I've temporarily disabled that codepath.
=> metamorphic: fix format major version ratcheting and parsing

compaction.go, ingest.go, internal/keyspan/truncate.go, internal/manifest/version.go, open.go, scan_internal.go, sstable/reader.go, table_stats.go, testdata/ingest_shared
Previously, our virtual sstable read code panicked if we saw a rangedel or rangekey get truncated at a virtual sstable file bound. While this is rare, this is an allowable use of virtual sstables in Cockroach and one that will (on rare occasion) happen organically, eg. when there are two range dels or range keys that abut each other while in different KV ranges (thereby getting defragmented by Pebble, which isn't aware of CockroachDB ranges).
Also add a guard against 0 filesizes, which can cause panics in compaction code.
=> *: allow virtual sstables to truncate range keys/dels

internal/errorfs/errorfs.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/options_test.go, metamorphic/test.go, open.go, options.go, vfs/disk_health.go
**metamorphic: test shared storage including the secondary cache**
This commit adds a standard option to the metamorphic tests that tests shared storage including the secondary cache.
This commit fixes a buglet in the vfs stack involving incorrect OpenReadWrite implementations, which affect the secondary cache and were caught by the changes to the metamorphic tests.
To test the test changes, I introduced a bug in the secondary cache like so:
```
b/objstorage/objstorageprovider/sharedcache/shared_cache.go @@ -127,6 +127,7 @@ func (c *Cache) ReadAt(
// Note this. The below code does not need the original ofs, as with the earlier
// reading from the cache done, the relevant offset is ofs + int64(n). Same with p.
ofs += int64(n)
+              ofs += 3
p = p[n:]
```
With this change, the test …
=> metamorphic: test shared storage including the secondary cache

objstorage/objstorageprovider/sharedobjcat/catalog.go, objstorage/objstorageprovider/sharedobjcat/testdata/catalog
On rare occasions, if we cancel a compaction at a point right after creating a new object, we'll end up deleting the object shortly after. Sometimes the two can happen with no explicit Sync() call in between, resulting in the object being created and deleted in the same batch which currently results in an error. This change allows for this case by moving around logic in the catalog batch application code.
=> sharedobjcat: allow addition/deletion of object in same batch

ingest.go, metamorphic/ops.go, open.go
Previously, the flushable ingest code assumed that all flushable ingested SSTs were locally present on vfs.FS, and the replayWAL code for that type of recovery bypassed the objProvider. This change updates replayWAL and ingestLoad to allow for the case where an ingested SST has already been copied/linked into shared storage.
Fixes #2717.
=> ingest: don't assume flushable ingests are locally present

db.go
Before #2641, we had a conditional to explicitly schedule deletion of obsolete files in db.Close(). We took it out as part of the deletion refactor as the comment on it made it seem no longer necessary. However, the code for readState.unrefLocked(), which we call earlier in Close(), explicitly states that it does not schedule obsolete file deletion and that it expects the caller to schedule that. Since we're calling readState.unrefLocked() here, we should be doing said deletion.
Fixes #2708.
=> db: Bring back call to deleteObsoleteFiles in Close()

internal/cache/refcnt_normal.go, internal/cache/refcnt_tracing.go
The refcnt implementation uses non-atomic assignment on init. Mixing atomic and non-atomic operations is not good and it is conceivable that on some platforms, the non-atomic assignment might not always be "seen" by an atomic operation that happens very soon after.
This change switches to atomic.Int32 wrapper and uses `Store` on init.
Informs cockroachdb/cockroach#84971
=> crl-release-23.1: cache: use atomic.Int32 wrappers, fix potential bug

internal/cache/refcnt_normal.go, internal/cache/refcnt_tracing.go
The refcnt implementation uses non-atomic assignment on init. Mixing atomic and non-atomic operations is not good and it is conceivable that on some platforms, the non-atomic assignment might not always be "seen" by an atomic operation that happens very soon after.
This change switches to using `StoreInt32` on init.
Informs cockroachdb/cockroach#84971
=> crl-release-22.2: cache: use atomic store on init

cleaner.go
This change adds a log when the cleaner job queue gets 75% full; once that happens we will log gain when the queue gets under 10% full.
=> db: add some logging for the cleaner

vfs/disk_health_test.go
Previously we were relying on sleeps and timing-based ways of
synchronization between observing a stall in the disk health checking
goroutine and confirming for it in the test code itself. This change
adds a more direct synchronization between the two events through
the use of channels, to deflake both tests. Furthermore,
the TestDiskHealthChecking_Filesystem_Close test was previously
doing a relatively thread-unsafe use of a map, which increased
the chances of a flake.
Also closes diskHealthCheckingFiles created in some Create operations
to prevent goroutine leaks.
Removes some tests that tested for false positives on disk stalls,
even though scheduler delays can also cause perceived disk
stalls at the small thresholds that were used.
Also selectively skips two tests on windows that …
=> vfs: Deflake TestDiskHealthChecking_File*

ingest.go
This change updates IngestAndExcise to use version.Overlaps() to calculate overlaps between the excise span and overlapping sstables, instead of using LevelIterator for each level that is inaccurate and could miss certain overlaps in L0.
=> ingest: Use Overlaps() to calculate L0 overlaps in excise

cmd/pebble/db.go, cmd/pebble/main.go, objstorage/shared/localfs.go
**cmd: enable benchmarking shared storage including the secondary cache**
This commit makes it possible to run commands like 'pebble bench ycsb' against shared storage & the secondary cache. To do this, I have introduced a version of shared.Storage that is backed by local disk, as opposed to memory or blob storage. This enables running too-large-for-memory benchmarks from a single machine without access to blob storage. One reason this is convenient is that today the code to communicate with blob storage is in the cockroachdb repo, not the pebble repo.
The concrete benchmarking plan I have in mind is worth mentioning as motivation. I will measure the maximum ycsb thruput of shared storage without a secondary cache and shared storage with a secondary cache. Since shared objects will be …
=> cmd: enable benchmarking shared storage including the secondary cache

internal/lint/lint_test.go, internal/manifest/btree_test.go
=> make go-linux-race builds faster

compaction.go, db_test.go, flushable.go, ingest.go, internal/cache/clockpro.go, internal/cache/clockpro_test.go, level_iter.go, level_iter_test.go, merging_iter_test.go, sstable/block.go, sstable/block_property_test.go, sstable/buffer_pool.go, sstable/buffer_pool_test.go, sstable/compression.go, sstable/compression_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/testdata/buffer_pool, sstable/value_block.go, sstable/writer_test.go, table_cache.go, testdata/event_listener, testdata/ingest, testdata/metrics
**db: do not cache compaction block reads**
During compactions, avoid populating the block cache with input files' blocks.
These files will soon be removed from the LSM, making it less likely any
iterator will need to read these blocks. While Pebble uses a scan-resistant
block cache algorithm (ClockPRO), the act of inserting the blocks into the
cache increases contention on the block cache mutexes (https://github.com/cockroachdb/pebble/issues/1997). This contention
has been observed to significantly contribute to tail latencies, both for reads
and for writes during memtable reservation. Additionally, although these blocks
may be soon replaced with more useful blocks due to ClockPRO's scan resistance,
they may be freed by a different thread inducing excessive TLB shootdowns …
=> db: do not cache compaction block reads

db.go
The builtins test `TestGetSSTableMetricsSingleNode` flakes due to a data race (modifying SSTable.Properties.UserProperties) on pebble side without making a copy.
Fixes: https://github.com/cockroachdb/cockroach/issues/106817
=> pebble: Fix TestGetSSTableMetricsSingleNode flake

objstorage/objstorageprovider/sharedcache/shared_cache_test.go
Reduce the max number of shards and skip the random block size tests under race. This significantly reduces the runtime and memory footprint of the test.
Informs: #2741
=> sharedcache: reduce the scope of TestSharedCacheRandomized under race

cleaner.go, db.go, ingest.go, ingest_test.go, objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/shared.go, objstorage/objstorageprovider/shared_backing.go, objstorage/objstorageprovider/shared_backing_test.go, objstorage/objstorageprovider/shared_obj_name.go, objstorage/objstorageprovider/shared_obj_name_test.go, objstorage/shared/storage.go, open.go, scan_internal.go
`IsShared()` is split into `IsRemote()`, `IsShared()`, `IsExternal()`.
I tried to update the former uses of `IsShared()` appropriately - use `IsRemote()` in most cases but keep using `IsShared()` in the disagg storage code for skip-shared iteration. These callsites can use reviewing though.
I can wait to merge this when it is convenient, given the other ongoing work.
=> objstorage: rename Shared to Remote in the objstorage provider API

cmd/pebble/db.go, compaction_test.go, db.go, ingest.go, ingest_test.go, metamorphic/options.go, metamorphic/options_test.go, objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/shared.go, objstorage/objstorageprovider/shared_backing.go, objstorage/objstorageprovider/shared_backing_test.go, objstorage/objstorageprovider/shared_readable.go, objstorage/objstorageprovider/shared_writable.go, objstorage/objstorageprovider/sharedcache/shared_cache.go, objstorage/objstorageprovider/sharedobjcat/catalog.go, objstorage/objstorageprovider/sharedobjcat/version_edit.go, objstorage/remote/factory.go, objstorage/remote/localfs.go, objstorage/remote/logging.go, objstorage/remote/mem.go, objstorage/remote/storage.go, open.go, options.go, scan_internal_test.go, tool/tool.go
---
There will be some upcoming work inside the objstorage provider to rename things and separate the aspect of supporting remote storage vs supporting shared storage. We should allow external files even if shared storage is not enabled / we don't have a creator ID.
=> objstorage: rename objstorage/shared package to remote and rename SharedStorage to RemoteStorage in options

compaction_picker.go
We should set bytesAddedToNextLevel to 0, if there will be no bytes added to the next level.
This pr also takes the opportunity to make the loop which computes compaction debt easier to reason about.
=> db: fix estimatedCompactionDebt metric

batch.go, batch_test.go, commit_test.go, db.go, record/log_writer.go, record/log_writer_test.go, vfs/vfstest/vfstest.go
Previously, a LogWriter would allocate up to 16 blocks of 32 KiB for buffering WAL writes. If all 16 blocks had been allocated and no free blocks were available, a batch writing to the WAL would queue until the flushing goroutine freed blocks. In testing of write-heavy workloads, especially with larger value sizes, we've seen queueing at the LogWriter. This queueing blocks the commit pipeline, preventing any batches from committing regardless of priority and whether they require waiting for fsync.
This commit modifies LogWriter to allow the queueing of an unbounded number of blocks. In practice, for the current WAL, the memtable size serves as an upper bound. With a 64 MiB memtable, at most 64 MiB / 32 KiB = 2,048 blocks may queue. This is not an unreasonable of additional memory overhead …
=> record: allow unbounded queued blocks in LogWriter

record/log_writer.go
Increase record.SyncConcurrency to 4096 to allow additional concurrency within the commit pipeline. In workloads with heavy writes and high concurrency, we've observed semaphore queueing artificially increasing tail latencies.
Here's a graph of a kv0 workload with 2KiB writes. Before ~16:00 cockroach was running with just #2762, and after was running with #2762 and this commit:
=> record: increase SyncConcurrency

db.go, ingest.go, ingest_test.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/remote.go, objstorage/objstorageprovider/remote_backing.go, objstorage/objstorageprovider/remote_backing_test.go, objstorage/objstorageprovider/remote_obj_name.go, objstorage/objstorageprovider/remote_obj_name_test.go, objstorage/objstorageprovider/remote_readable.go, objstorage/objstorageprovider/testdata/provider/shared_attach, objstorage/objstorageprovider/testdata/provider/shared_attach_after_unref, objstorage/objstorageprovider/testdata/provider/shared_attach_multi, objstorage/objstorageprovider/testdata/provider/shared_basic, objstorage/objstorageprovider/testdata/provider/shared_no_ref, objstorage/objstorageprovider/testdata/provider/shared_readahead, objstorage/objstorageprovider/testdata/provider/shared_remove, open.go
Shared objects refer to objects that have been created by a Pebble instance and are owned by the Pebble instances in a cluster. Remote objects can be shared objects or external objects (such as those attached by online restore).
In this commit we rename uses of "shared" to "remote" in objstorage provider code that applies to all types of remote objects. We now conceptually have a remote subsystem which itself contains a shared subsystem.
=> objstorage: rename 'shared' to 'remote'

record/log_writer.go
This includes a 23.1 backport of #2764. Additionally, it contains a safer alternative to #2762, bumping the maximum allocated LogWriter blocks to 512. These are being backported as a part of a commitment to a customer.
=> crl-release-23.1: bump commit pipeline constants

db.go, db_test.go, mem_table.go, metrics.go, testdata/event_listener, testdata/metrics
We've observed large allocations like the 64MB memtable allocation take 10ms+.
This can add latency to the WAL/memtable rotation critical section during which
the entire commit pipeline is stalled, contributing to batch commit tail
latencies. This commit adapts the memtable lifecycle to keep the most recent
obsolete memtable around for use as the next mutable memtable.
This reduces the commit latency hiccup during a memtable rotation, and it also
reduces block cache mutex contention (https://github.com/cockroachdb/pebble/issues/1997) by reducing the number of times we
must reserve memory from the block cache.
```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.30GHz
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op …
```
=> db: keep up to one memtable for recycling

internal/cache/clockpro.go, internal/cache/entry.go, internal/cache/value.go
**internal/cache: reduce mutex contention from EvictFile**
We've observed block cache mutex contention originating from EvictFile. When
evicting a file with a significant count of blocks currently held within the
block cache, EvictFile may hold the block cache shard mutex for an extended
duration, increasing latency for requests that must access the same shard.
This commit mitigates this contention with two approaches. EvictFile now
periodically drops the mutex to provide these other requests with an
opportunity to make progress. Additionally, rather than free()-ing manually
managed memory back to the memory allocator while holding the mutex, the free
is deferred until the shard mutex has been dropped.
Informs #1997.
**internal/cache: increase shard count to 4x CPUs**
Increase the block …
=> internal/cache: reduce mutex contention

db.go
This commit introduces a `DB.Download()` API which is used during online restore to copy off external data.
=> db: introduce Download API

scan_internal.go, scan_internal_test.go, table_cache.go, testdata/point_collapsing_iter, testdata/scan_internal
Previously we were using pointCollapsingIters to collapse obsolete points in foreign sstables. This was necessary because of snapshots that were open at the time those sstables were written, however they really blew up code complexity and performance. This change transitions to using vanilla sstable iterators for foreign sstables with `hideObsoletePoints` set to true. We error out if the sstable format for a foreign sstable is not high enough to support the obsolete flag.
Also remove all cases in the pointCollapsingIter that were not used by ScanInternal (which is the last remaining user of it).
Part of #2756.
=> *: simplify pointCollapsingIter, use vanilla iters for foreign SSTs

db.go, ingest.go, table_cache_test.go, version_set_test.go
Added a check inside of `FileMetadata.ValidateVirtual()` to check if the keys returned from a virtual sstable are within the bounds of the Smallest and Largest metadata keys.
=> manifest: virtual iterator bounds checking virtual sstable metadata

db.go, ingest_test.go, options.go, scan_internal.go, scan_internal_test.go, snapshot.go, testdata/scan_statistics
Created a new function `ScanStatistics` that returns counts of the
different key kinds in Pebble (by level) as well as the number of
snapshot keys. Also modified `ScanInternal` to surface the level of each
key within each visitor function.
Informs: #1996
=> pebble: Collect Key Statistics

.gitignore, Makefile
Convenience target to generate a unit test coverage profile.
=> Makefile: add testcoverage target

.github/workflows/ci.yaml
The CI job prescribes go version 1.20.1. The github action runners
cache version 1.20.6 and the setup is much faster (instant) for that
version. So we require 1.20 instead and let github choose the point
version.
We also use the v4 of setup-go which caches dependencies by default.
=> ci: use any 1.20 go version

internal/cache/refcnt_normal.go
Informs cockroachdb/cockroach#84971.
=> internal/cache: mark panic messages as redaction-safe

internal/cache/refcnt_normal.go
Backport of #2797.
----
Informs cockroachdb/cockroach#84971.
=> crl-release-23.1: internal/cache: mark panic messages as redaction-safe

internal/cache/refcnt_normal.go
Backport of #2797.
----
Informs cockroachdb/cockroach#84971.
=> crl-release-22.2: internal/cache: mark panic messages as redaction-safe

db.go, ingest_test.go, options.go, scan_internal.go, scan_internal_test.go, snapshot.go
This pull request uses a `TokenBucket` to limit the number of keys that
read from `ScanStatistics` within a certain period of time.
Changes rely on https://github.com/cockroachdb/pebble/pull/2713 
Fixes: #2778
=> Rate Limit ScanStatistics

.github/workflows/code-cover-gen.yaml, .github/workflows/code-cover-publish.yaml, .gitignore
This change adds two github action workflows which run on each PR: one
generates unit test code coverage data, and one publishes the coverage
data to a GCS bucket (from where Reviewable can use it).
Two workflows are required for security (the first workflow runs
potentially malicious code from a fork); for more details, see
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> github: code coverage workflows

.github/workflows/code-cover-gen.yaml
The trim prefix left a slash in the filenames. This commit fixes the argument to include the slash.
=> workflows: fix trim-prefix in code-cover-gen.yaml

db.go, go.mod, go.sum, options.go, scan_internal.go
This change updates the cockroach tokenbucket version in pebble as well as uses `TokenBucket.WaitCtx` inside of `DB.ScanStatistics`.
Fixes: #2784
=> pebble: Update TokenBucket package and use WaitCtx

internal/arenaskl/arena.go, internal/arenaskl/arena_test.go, internal/arenaskl/node.go, open.go
This commit disallows creation of arenas larger than 4GB in invariants mode and otherwise limits the size to 4GB. The existing code could allow a larger buffer to be used, which would result in uint32 offset overflows.
We also cleanup the alignment argument so it's actually the alignment and not the maximum padding.
=> arenaskl: disallow arenas larger than 4GB

sstable/format.go, sstable/reader_test.go
In #2829 some facilities for running tests against all table formats was introduced, but it mistakenly used `< MaxTableFormat`, omitting the max table format.
=> sstable: fix testing bug that omitted Pebblev4 table format

replay/replay_test.go, replay/workload_capture.go
All the replay datadriven tests wait for all enqueued sstables to finish copying to the collection directory before we terminate the workload collector. The one exception is TestCompactionsQuiesce which currently calls the Stop() method even if there are sstables waiting to be copied. This change delays the call to Stop() until all enqueued sstables have been copied over.
Fixes #2833.
=> replay: Deflake TestCompactionsQuiesce by waiting for sstable copy

objstorage/objstorageprovider/sharedcache/shared_cache_test.go
We can sometimes see flakes if rand.Int63 chooses a size of zero, as we feed that size into another Int63 call and it expects nonzero arguments. An example is https://github.com/cockroachdb/pebble/actions/runs/5907184465
This change fixes it by forcing a nonzero size.
=> sharedcache: Deflake TestSharedCacheRandomized

db.go, metrics.go, objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/sharedcache/shared_cache.go, objstorage/objstorageprovider/sharedcache/shared_cache_helpers_test.go, objstorage/objstorageprovider/sharedcache/shared_cache_test.go, testdata/event_listener, testdata/ingest, testdata/metrics, tool/testdata/db_lsm
Fixes https://github.com/cockroachdb/pebble/issues/2687.
**sharedcache: introduce metrics**
This commit adds various metrics to the shared cache. In a follow up PR, I will export these metrics as time-series metrics from CRDB.
=> sharedcache: introduce metrics

compaction.go, compaction_iter_test.go, db.go, external_iterator.go, internal/keyspan/interleaving_iter.go, internal/keyspan/interleaving_iter_test.go, internal/keyspan/testdata/interleaving_iter, internal/keyspan/testdata/interleaving_iter_masking, iterator.go, range_keys.go, scan_internal.go, scan_internal_test.go
This commit refactors the interleaving iterator with a goal of simplifying its logic, but also to support a future mode in which the interleaving iterator may interleave end boundaries during iteration.
The logic to interleave span bounds and point keys is disentangled from the logic to determine when to yield a key-value pair to the caller. This also allows the yielding logic to be shared among forward and reverse iteration.
=> internal/keyspan: refactor interleaving iterator

.github/workflows/code-cover-gen.yaml, scripts/changed-go-pkgs.sh, scripts/pr-codecov-run-tests.sh
This commit improves the code-cover-gen workflow to only run tests for the changed packages; other packages won't show up in the review so coverage data is not useful. This should speed up the build significantly.
=> workflows: restrict coverage testing to changed packages

objstorage/objstorageprovider/sharedcache/shared_cache_test.go, sstable/unsafe_test.go
Fixes #2849.
Reduce memory usage of TestGetBytes which allocates a 2GB slice. We
don't actually do anything with the data so we can allocate a small
slice.
Reduce the maximum sharding block size to 4MB from 10MB (we always use
1MB in production) and reduce the maximum number of shards from 64 to
32. This reduces the memory footprint of the test significantly.
=> sstable, sharedcache: reduce test memory usage

sstable/reader.go
The 23.1 backport of the monotonic bounds bug fix was unclean due to recent churn that split reader.go into multiple files. In the rebase, the SeekPrefixGE i.index.isDataInvalidated condition was inverted. This was caught by the new blockIter data-validity assertions.
It will take some legwork to produce a unit test that exercises exactly the condition that is uncaught by existing unit tests, and I don't want that to block correcting this backport.
Fix #2856.
=> crl-release-23.1: sstable: fix backport of monotonic bounds bug fix

range_keys.go, sstable/block_property.go, sstable/block_property_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/testdata/block_properties_boundlimited
The BoundLimitedBlockPropertyFilter interface previously unnecessarily accepted InternalKeys for bounds. Index block internal keys always have identical, unmeaningful trailers.
=> sstable: use simple user keys in BoundLimitedBlockPropertyFilter

go.mod, go.sum
Downgrade golang.org/x/exp to v0.0.0-20230626212559-97b1e661b5df, the version currently in use by the Cockroach master branch.
=> go.mod: downgrade golang.org/x/exp

internal/metamorphic/meta_test.go, internal/metamorphic/metaflags/meta_flags.go, internal/metamorphic/metarunner/main.go, metamorphic/meta.go, scripts/code-coverage.sh
`TestMeta` runs multiple instances of itself in other processes by
executing the same binary (`os.Args[0]`). This doesn't work with the
go test code coverage infrastructure - the "inner" call is not
covered.
To address this, we modify `TestMeta` to allow specifying the "inner
binary" and we create a regular binary `metarunner` that can run a
single instance of `TestMeta` (i.e. either `--run-dir` or `--compare`
is passed). This will allow building `metarunner` with binary coverage
instrumentation (see https://go.dev/testing/coverage/#building).
Add a script that collects overall code coverage profiles from all
tests (including the metamorphic test).
It generates three profiles, in LCOV format: `profile-tests.lcov`,
`profile-meta.lcov`, and `profile-combined.lcov`.
The intention is to make …
=> scripts: add code coverage script

compaction.go, compaction_test.go
The flushing code currently returns an error if a logNum invariant is violated. However, it's unlikely that we'll be able to recover from a bug here, and we end up keeping the node up but without making any forward progress.
We switch to crashing in this case - a panic is much more visible and restarting the node has a better chance of making progress anyway.
Informs #109078.
=> db: crash on logNum invariant violation

batch.go, commit.go, commit_test.go, flushable.go, mem_table.go
=> db: minor cleanup and comments

compaction.go, compaction_test.go
The flushing code currently returns an error if a logNum invariant is violated. However, it's unlikely that we'll be able to recover from a bug here, and we end up keeping the node up but without making any forward progress.
We switch to crashing in this case - a panic is much more visible and restarting the node has a better chance of making progress anyway.
=> crl-release-22.2: db: crash on logNum invariant violation

compaction.go, compaction_test.go
The flushing code currently returns an error if a logNum invariant is violated. However, it's unlikely that we'll be able to recover from a bug here, and we end up keeping the node up but without making any forward progress.
We switch to crashing in this case - a panic is much more visible and restarting the node has a better chance of making progress anyway.
=> crl-release-23.1: db: crash on logNum invariant violation

compaction.go, internal/manifest/l0_sublevels.go
Previously, we had one case where we could be calling InitCompactingFileInfo (a method on L0Sublevels that must be called on the most-recently-created L0Sublevels) on a failed compaction while another version was being installed but was in the process of writing to the manifest, and had hence dropped the db mutex during IO. This had the potential to panic on a case where we expect the interval indices in FileMetadata to match exactly with those in the latest version's L0Sublevels. If there's a newer L0Sublevels being created that hasn't been installed into the versions list yet, the two are expected to be out of sync.
This change resolves this by grabbing the manifest lock before calling InitCompactingFileInfo in clearCompactionState.
Will address cockroachdb/cockroach#109866 when it …
=> manifest: grab manifest lock when calling InitCompactingFileInfo

open.go, options.go, tool/data_test.go, tool/db.go, tool/testdata/corrupt-options-db/OPTIONS-000002, tool/testdata/db_check, tool/testdata/db_lsm, tool/testdata/db_scan, tool/tool.go
This commit improves the output of the pebble tool when it is run against an encrypted store and the encryption key is not set up correctly.
Until now, we get a very obscure "invalid key=value syntax" error from inside the options parsing code. What's worse the error contains unescaped non-printable characters which can end up erasing the message prefix altogether.
Finally, the errors show up on stdout instead of stderr.
This commit
- escapes the non-printable characters and limits the length in the above error message
- adds more context as to where the error is coming from
- marks the error as a corruption error
- augments all corruption errors with a specific note about encrypted stores
- switches to using stderr for all `pebble db` subcommand errors.
Before:
```
$ go run ./cmd/pebble …
```
=> tool: better errors in case of encrypted store

tool/testdata/mixed/main.go
Fixing a compile error introduced by a previous PR.
=> tool: fix testdata generator

internal/testkeys/testkeys.go
The RandomSeparator function wasn't obeying its contract. If there is an id between apIdx and bpIdx, we use it now. If there is no such id, then we fix the computation of timestamps. Note that if there is no id between apIdx, and bpIdx, we will not necessarily respect the suffix parameter passed to the function. This is stated in the function contract.
Fixes: https://github.com/cockroachdb/pebble/issues/2874
=> metamorphic: fix testkeys.RandomSeparator

objstorage/objstorageprovider/remoteobjcat/version_edit.go
We recently added some assertions when applying a VersionEdit. Unfortunately we used to have a bug where when we rotate a catalog file, we dump the up-to-date state *and* the last version edit. This was a no-op, but now when we upgrade a node we can hit these assertions.
Fixes #2894.
=> remoteobjcat: move assertions behind invariants.Enabled

compaction.go, compaction_iter_test.go, db.go, internal/invalidating/iter.go, iterator.go, iterator_test.go, merging_iter.go
In invariants builds, with 10% probability wrap various internal iterators with
an invalidating iterator. This helps ensure we're not accidentally depending on
key byte slice stability where we shouldn't.
Close #2896.
=> db: use invalidating iterators with low probability under invariants

scripts/code-coverage.sh
We have a significant number of assertions across the codebase gated behind the invariants build tag. This code is run in CI and during the long-running nightly metamorphic tests. When generating code coverage profiles, run with this build tag to also capture code blocks that run with invariants.Enabled.
=> scripts: generate code coverage with invariants build tag

flushable_test.go, table_cache.go, table_cache_test.go
Double check the file reference counts before attempting to find/create a table
cache node for a file. Once a file's reference count falls to zero, the file
becomes obsolete and may be deleted at any moment.
Today if we have a race, break this invariant and attempt to load a file with a
nonpositive reference count, it's relatively unlikely that it manifests as an
error. Typically tables remain open in the table cache, allowing the table
cache to serve the request even if the file is no longer linked into the data
directory. Additionally, even if it's not in the table cache presently,
deletion of obsolete files may be delayed due to deletion pacing, hiding the
race.
This commit preemptively asserts on the file reference counts. I opted for not
restricting this invariant check to invariants …
=> db: double check file reference counts when loading file

metamorphic/options.go
In the metamorphic test runs with randomized options, vary the sstable compression algorithm rather than always using the default Snappy compression algorithm.
Close #1705.
=> metamorphic: vary sstable compression algorithm

vfs/mem_fs.go, vfs/mem_fs_test.go, vfs/testdata/memfs_lock
Previously MemFS's Lock method did not implement mutual exclusion under the assumption that databases are given separate processes which do not share memory. This commit adapts Lock to enforce mutual exclusion, preventing accidentally using same FS concurrently from more than one Pebble instance. It's believed that cockroachdb/cockroach#110645 is the result of Cockroach acceptance tests opening a MemFS store twice, with one Pebble instance deleting files from beneath another Pebble instance.
=> vfs: enforce mutual exclusion in MemFS.Lock

internal/testkeys/testkeys.go
Fixes: https://github.com/cockroachdb/pebble/issues/2907
=> metamorphic: 0 suffix should be suffixless in the RandomSeparator

metrics.go, objstorage/objstorageprovider/sharedcache/shared_cache.go
This is needed to follow up on https://github.com/cockroachdb/cockroach/pull/110818 & complete the metrics work.
**pebble: export bucketing scheme used for secondary cache**
This commit exports the bucketing scheme used for histograms exported by the secondary cache, to enable exporting said metrics in CRDB itself.
=> pebble: export bucketing scheme used for secondary cache

ingest.go
Previously we were letting the inbound SharedMeta dictate what sequence numbers would go into shared file bounds, before resetting sequence numbers on those file bounds in a later step. This led to a rare case where we'd end up setting the overall file bounds based on a point key when we should have done it based on a range key (due to the Kind being greater).
This change addresses it by using zero sequence numbers when calling Extend{Point,Range}KeyBounds on shared metas.
=> ingest: Set bounds with zero sequence number internal keys

tool/logs/compaction.go, tool/logs/compaction_test.go, tool/logs/testdata/compactions-23-1, tool/logs/testdata/compactions-latest
There are two kinds of log lines which are relevant to flushable ingestions.
The first one is of the form:
```
ingested as flushable 024323 (1.5KB), 024328 (1.0KB), 024324 (2.0KB), 024325 (1.1KB), 024326 (1.1KB), 024327 (54KB)
```
The second one is of the form:
```
flushed 6 ingested flushables L0:024323 (1.5KB) + L0:024328 (1.0KB) + L0:024324 (2.0KB) + L2:024325 (1.1KB) + L2:024326 (1.1KB) + L0:024327 (54KB) in 0.0s (0.0s total), output rate 152MB/s
```
The first type gets printed when we perform a flushable ingestion, and the second type gets printed when we actually ingest the sstables during the flush.
For now, we ignore the first log type, and parse the second log type as ingestions.
On the following logs:
```
I230831 04:13:28.689575 3717 3@pebble/event.go:685 ⋮ [n10,s10,pebble] 345 …
```
=> tool/logs: add support for flushable ingestions

compaction.go, db.go, snapshot.go
It's unnecessary to grab a read state when the EFOS is first created.
Case 1: No excises.
If there's no excises, then any iterator created on the EFOS prior to it transition to an FOS can read using only a sequence number. As memtables are flushed, and compactions occur, the keys relevant to the EFOS will be preserved.
Once the EFOS transitions to an FOS, we don't need a read state, because we grab a version ref for the latest version, which contains all sstables with keys which are relevant to the FOS.
Case 2: Excises.
If a relevant excise occurs after transition to FOS, we don't care, because the FOS is performing reads using a version which contains all the relevant files.
If an excise occurs before transition to an FOS, then all iterators already created on the EFOS will still be …
=> db: get rid of readstate in EFOS

compaction.go, compaction_test.go
Refactor the construction of the compaction input iterator to better unify flushing and compaction codepaths, and factor out range deletion iterator construction into a helper.
=> db: refactor construction of compaction input iterator

metamorphic/config.go, metamorphic/meta.go
Previously, the metamorphic test always generated operations according to a fixed distribution. This commit adds a second configuration and adjusts the test to randomly chose between available configurations. The new configuration strongly prefers generating versions of existing key prefixes when generating a new key. Additionally, it generates significantly fewer deletion write operations in order to allow a test run to accumulate a more sizable working set of live keys.
This new configuration is sufficient to exercise all the non-error cases within the ssblock nextPrefix code paths (#2921).
The overall impact on metamorphic test code coverage is minor, moving from 67.3% to 67.7%.
Close #2921.
Informs #2041.
=> metamorphic: add variant that constructs many versions

ingest.go, ingest_test.go, sstable/reader_virtual.go
Supports validation of virtual sstable block checksums during ingestion.
It was easier to deduplicate the virtual sstables by file backing to
ensure that the checksums for each file are only validated once. We
could also implement a VirtualReader.ValidateVirtual function which only
validates blocks which fall within virtual sstable bounds, but that
seems like too much work for a feature which is off by default and was
never turned on.
This pr also prepares us for
https://github.com/cockroachdb/pebble/issues/2885. The metamorphic test
might set `ValidateOnIngest` to true in which case we'll hit a panic.
=> db: support virtual sstables in block checksum validation

batch.go, compaction_iter_test.go, compaction_test.go, format_major_version.go, format_major_version_test.go, ingest.go, ingest_test.go, metamorphic/generator.go, metamorphic/ops.go, metamorphic/options.go, version_set.go, version_set_test.go
These versions are now stable.
=> db: remove 'Experimental' prefix from recent format major versions

compaction_picker.go, metrics.go, testdata/compaction_picker_target_level
During large table drops, we see level compensation become drastically high, which leads to L0 compaction starvation, which in turn leads to AC queueing of requests and increases in foreground latencies.
We completely ignore compensation during prioritization of levels during compaction, but we consider compensation when we try and pick a level for compaction.
The above approach ensures that L0 isn't starved during large table drops.
Note that there might be scenarios where a level say L3, has a high compensated score due to a wide range delete, and L3 will also drop a ton of data in L4, but we end up picking L4 for compaction because it has a higher raw score.
While this will make some of the compactions picked inefficient, most of the data which is dropped due to the range delete should …
=> db: use uncompensated scores to prioritize levels for compaction

iterator.go, metamorphic/ops.go, metamorphic/retryable.go, metamorphic/test.go, options.go
Add a new IterOption that allows a user to configure an arbitrary predicate of point keys that should be skipped in the form of a function. The Iterator consults this predicate for every internal key.
Use this new SkipPoint function to remove the complicated logic within the metamorphic test for ensuring determinisim of RangeKeyChanged() in the presence of time-bound block-property filters. A SkipPoint predicate may be combined with a block-property filter to achieve deterministic iteration.
=> db: add SkipPoint iterator option

objstorage/objstorageprovider/sharedcache/shared_cache.go
Instead of erroring out when the cache size is too small given the number of shards, we up the size as needed.
Fixes #2935.
=> sharedcache: tolerate small sizes

compaction.go, data_test.go, ingest.go, ingest_test.go, options.go, testdata/ingest, testdata/ingest_target_level
Currently, if we identify boundary overlap in a level
during ingest target level calculation, but no data overlap,
we are forced to find a target level above the file we saw
the overlap with (if we can't fall below it, such as if the
existing file is in L6, which happens commonly).
This change takes advantage of virtual sstables to split
existing sstables into two virtual sstables when an ingested
sstable would be able to go into the same level had the sstables
been split that way to begin with. Doing this split reduces a
lot of write-amp as it avoids us from having to compact the
newly-ingested sstable with the sstable it boundary-overlapped with.
Biggest part of https://github.com/cockroachdb/pebble/issues/1683. First commit is https://github.com/cockroachdb/pebble/pull/2538, which this …
=> db: add ingest-time splitting of ssts into virtual ones

metamorphic/options.go, metamorphic/options_test.go
Ingest-time splitting was added in #2582. This change adds testing for it to the metamorphic test, by flipping it off/on in random options.
=> metamorphic: Add testing for ingest splits

iterator.go, metamorphic/ops.go, metamorphic/retryable.go, metamorphic/test.go, options.go
This reverts commit 895ffed51f35c1e1867b7b6bf6330e8bec58210c.
This was insufficiently tested because #2932 wasn't merged yet, and there
appears to be an unidentified interaction. Reverting this will allow us to
restore testing of block property filters, and then I can reexamine this
refactor.
=> Revert "db: add SkipPoint iterator option"

metamorphic/meta.go, metamorphic/options.go, metamorphic/options_test.go
Fix a bug where the testkeys timestamp suffix block property collectors were unused. This is coverage that we had but was lost at some point.
I've added a focused unit test to cover this case. This increases overall meta-only test coverage from 67.9% to 68.6%.
Close #2931.
=> metamorphic: fix block property collectors integration

open.go, version_set.go
Previously, if the FormatMajorVersion was ratcheted forward post-DB initialization, the options would still keep reflecting the old FMV while the new dynamic FMV has moved forward. The Manifest code had an assertion on not adding Virtual SSTable backing entries based on the FormatMajorVersion in the Options and not the dynamically updated one, resulting in spurious assertion errors. This change addresses that code to look at the more up-to-date FMV.
Fixes #2940.
=> db: Fix FormatMajorVersion check in version_set for VSSTs

data_test.go, internal/manifest/version.go, sstable/properties.go, sstable/properties_test.go, sstable/reader.go, sstable/reader_test.go, sstable/reader_virtual.go, sstable/testdata/virtual_reader, table_cache.go, table_stats.go, table_stats_test.go, testdata/table_stats, tool/testdata/sstable_properties
Currently, virtual sstables lack stats unless they're set upon
creation. Even if these stats are set upon creation, they will
be lost upon a db restart.
This pr adds support to compute virtual sstable table stats
asynchronously.
To easily support this with minimal code changes, we introduce a
CommonReader interface meant to be used by those who don't care
if they're reading from a virtual or a physical sstable.
To support the CommonReader, we introduce a CommonProps type which
contains either virtual or physical sstable properties which are
useful to the users of the CommonReader.
Fixes: https://github.com/cockroachdb/pebble/issues/2558
=> .*: support async stats for virtual sstables

compaction.go, metamorphic/test.go
Previously, if we cancelled a compaction due to an excise or ingest-split, the resultant error would error out the metamorphic test as it wasn't ignored in the metamorphic test's EventListener.
This change updates the ignore rule in the metamorphic test to not exit out on a background error that is ErrCancelledCompaction.
Fixes #2948.
=> metamorphic: Ignore ErrCancelledCompaction in background errors

compaction.go, data_test.go, db.go, flushable.go, flushable_test.go, get_iter.go, get_iter_test.go, ingest.go, ingest_test.go, level_checker.go, level_checker_test.go, level_iter.go, level_iter_test.go, merging_iter_test.go, scan_internal.go
Rather than propagating just the individual Compare and Split funcs, propagate the entire *Comparer further, and specifically to the levelIter. In some places this makes for smaller, more readable call sites, but it's primarily motivated by future changes that will propagate the Comparer further into a keyspan.InterleavingIter per-levelIter.
=> db: propagate Comparer into levelIter

internal/manifest/btree.go, internal/manifest/btree_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go
1. By returning FileBackings from the LevelMetadata.release functions, we can clean up some duplication in Version.Unref and Version.UnrefLocked.
2.
It is not obvious how Pebble determines when it is okay to delete the backing sstable associated with a virtual sstable.
The flow is that Filemetadata refcounting actually happens on the FileBacking. Multiple virtual sstables with the same backing sstable will share the same FileBacking struct. Once the refcount on the FileBacking struct hits 0, we know that 0 virtual sstables require that FileBacking, and therefore it is safe to delete the backing sstable.
This pr adds some commentary which explains this.
It was a bit awkward prior to this pr when a btree returns an obsolete virtual metadata, and then we grab the filebacking from the …
=> db: cleanup btree obsoletion logic

event.go, testdata/event_listener
The log line emitted by the logging event listener when a compaction begins had an unnecessary trailing space.
=> db: remove trailing whitespace from compacting log line

ingest.go, ingest_test.go, internal/manifest/version_edit.go, testdata/excise
Problem explained in detail in: https://github.com/cockroachdb/pebble/issues/2947#issuecomment-1738225516
We were adding too many CreatedBackingTables entries to the manifest. Such an
entry should only be added when an sstable is first virtualized. This is
mentioned as an invariant above VersionEdit.CreatedBackingTables.
Note that the excise function will create backing tables and add them to the
version edit. But these backing tables should only be added to the version edit,
if the sstable being virtualized is NOT virtual. If we're further virtualizing
an already virtual sstable, then a backing table entry associated with the file
backing will already be present in the manifest as part of an older version edit.
=> db: only create one CreatedBackingTables entry per sstable

go.mod
=> go.mod: specify Go 1.20

checkpoint.go, internal/manifest/version_edit.go, version_set.go, version_set_test.go
This is required for metrics calculations which need the backing table size to calculate the virtual sstable space amplification.
=> db: incrementally keep tracking of backing table size

db.go, metrics.go, metrics_test.go, testdata/event_listener, testdata/ingest, testdata/metrics, tool/testdata/db_lsm
Pr just adds backing size/count into the Metrics struct and
grabs them from the version set. Needs loglock to grab these
as the fields are protected by the loglock.
=> db: add metrics for num backing sstables and size

checkpoint.go, checkpoint_test.go, testdata/checkpoint
Virtual sstable checkpointing will remove the backing files which won't be required by the checkpoint. Need to make sure that the virtual sstables which are present in the checkpoint manifest are still readable, and that the backing files not required are deleted.
=> db: add test for virtual sstable checkpointing

compaction.go, internal/manifest/l0_sublevels.go
Previously, we had one case where we could be calling InitCompactingFileInfo (a method on L0Sublevels that must be called on the most-recently-created L0Sublevels) on a failed compaction while another version was being installed but was in the process of writing to the manifest, and had hence dropped the db mutex during IO. This had the potential to panic on a case where we expect the interval indices in FileMetadata to match exactly with those in the latest version's L0Sublevels. If there's a newer L0Sublevels being created that hasn't been installed into the versions list yet, the two are expected to be out of sync.
This change resolves this by grabbing the manifest lock before calling InitCompactingFileInfo in clearCompactionState.
Will address cockroachdb/cockroach#109866 when it …
=> crl-release-22.2: manifest: grab manifest lock when calling InitCompactingFileInfo

compaction.go, internal/manifest/l0_sublevels.go
Previously, we had one case where we could be calling InitCompactingFileInfo (a method on L0Sublevels that must be called on the most-recently-created L0Sublevels) on a failed compaction while another version was being installed but was in the process of writing to the manifest, and had hence dropped the db mutex during IO. This had the potential to panic on a case where we expect the interval indices in FileMetadata to match exactly with those in the latest version's L0Sublevels. If there's a newer L0Sublevels being created that hasn't been installed into the versions list yet, the two are expected to be out of sync.
This change resolves this by grabbing the manifest lock before calling InitCompactingFileInfo in clearCompactionState.
Will address cockroachdb/cockroach#109866 when it …
=> crl-release-22.1: manifest: grab manifest lock when calling InitCompactingFileInfo

checkpoint_test.go, cleaner_test.go, compaction.go, db.go, event_listener_test.go, options.go, testdata/checkpoint
There are some potential racy problems by making it a variable which is written to after the db is opened. All of the existing use cases can just use this variable as an option.
=> db: turn testingAlwaysWaitForCleanup into an option

internal/manifest/level_metadata.go, metrics.go, metrics_test.go, testdata/event_listener, testdata/ingest, testdata/metrics, tool/testdata/db_lsm, version_set.go
The virtual sstable size sum is useful because it along with the
backing table size can be used to compute the space amp associated
with virtual sstables.
=> db: keep track of virtual sstable size sum

cmd/pebble/db.go, compaction.go, compaction_picker_test.go, compaction_test.go, ingest_test.go, metamorphic/options.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/remote/storage.go, open_test.go, options.go, options_test.go, replay/testdata/replay, replay/testdata/replay_paced, scan_internal.go, scan_internal_test.go, testdata/ingest_shared_lower, tool/tool.go
This change adds the ability to do a copy compaction for a file from local to remote storage, by copying the underlying file and producing a new filenum + backing file. This gives us the flexibility to specify finer-grained placement rules for files in local vs remote storage, and we can use this to selectively place only L5/6 in shared storage, an option that is now Options.Experimental.CreateOnShared (which becomes an enum as opposed to the previous bool).
Fixes #2626.
=> *: implement local to remote/shared copy compaction

compaction.go
objProvider doesn't know about FileMetadata filenums.
Fixes: https://github.com/cockroachdb/pebble/issues/2973
=> db: Use the filenum in the Filebacking for lookup

metamorphic/generator.go
Previously, when cloning an iterator backed by a bounded snapshot, the metamorphic test would sometimes clear all iterator options. This included terator bounds which are required to keep the iterator's access within the snapshot's bounds to prevent nondeterminism outside those bounds. This commit fixes this, by defaulting to the cloned iterator's options in these cases.
Resolves #2969.
=> metamorphic: fix unbounded snapshot access

.github/workflows/ci.yaml, .github/workflows/code-cover-gen.yaml, .github/workflows/nightly-code-cover.yaml, .github/workflows/sanitizers.yaml, go.mod, go.sum
There's an effort underway to upgrade to Go 1.21 before shipping 23.2. Begin testing 1.21 in Pebble CI, and declare Go 1.21 in the go.mod file.
Informs cockroachdb/cockroach#97260.
=> go.mod,.github: upgrade to Go 1.21

event.go, go.mod, go.sum, internal/base/filenames.go, internal/base/filenames_test.go, log_recycler_test.go
Implement SafeFormat on these types to ensure that they're never redacted
within error messages, logs, etc.
=> internal/base: never redact FileNum or DiskFileNum

ingest_test.go
Deflake TestIngestLoadRand by using require.Equal instead of a pretty.Diff test assertion.
Close #2986.
=> db: deflake TestIngestLoadRand

ingest.go, ingest_test.go
After a table is ingested, an asynchronous job reads the table and validates
its checksums. If corruption is uncovered, the job fatals the process.
Previously, a transient I/O error would also fatal the process, even if the I/O
error did not indicate corruption. This commit adapts this code path to log the
error to the BackgroundError event listener and re-queue the file for
validation.
Informs #270.
Informs #1115.
=> db: tolerate errors during async ingest sstable validation

checkpoint.go, compaction.go, db.go, db_test.go, event.go, flushable.go, flushable_test.go, format_major_version.go, ingest.go, internal/base/filenames.go, internal/base/filenames_test.go, internal/manifest/testdata/version_edit_apply, internal/manifest/version_edit.go, open.go, record/log_writer.go, record/record.go, record/record_test.go, replay/workload_capture.go, replay/workload_capture_test.go, table_cache_test.go, tool/find.go, tool/wal.go, version_set.go, version_set_test.go
These subsystems deal with on-disk files, using `DiskFileName` is more appropriate. This reduces the number of conversions in the code a lot. There are only a few `DiskFileName.FileName()` conversions left.
We change `DiskFileNum` to be a `uint64` like `FileNum`, so that `DiskFileNum`s can also be compared and printed as integers.
=> db: use DiskFileName for manifest files and memtables

format_major_version.go
Previously nearly all events logged by the `EventListener` used types that had been marked as safe by implementing `SafeFormatter`, defining them as non-sensitive and not requiring redaction in logs, however `FormatMajorVersion` had been excluded. This change makes `FormatMajorVersion` a `redact.SafeValue` as well.
Requires the following in the [cockroachdb/cockroach `redactcheck.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/testutils/lint/passes/redactcheck/redactcheck.go):
```
"github.com/cockroachdb/pebble": {
"FormatMajorVersion": {},
},
=> event: mark `FormatMajorVersion` as safe from redaction

objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/remote.go, objstorage/objstorageprovider/remoteobjcat/catalog.go, objstorage/remote/storage.go
Fix up a few instances where nonsensitive data could be redacted in logs or error messages, and a couple instances where errors were included twice (once as the target of Wrapf, and once as a formatting operand to Wrapf).
=> objstorage: fix up redaction, error message formatting

compaction.go
This PR removed the duplicated function `mergeFileInfo`, which code was the same as `merge`.
```go
func merge(a, b []fileInfo) []fileInfo {
if len(b) == 0 {
return a
}
a = append(a, b...)
sort.Slice(a, func(i, j int) bool {
return a[i].fileNum.FileNum() < a[j].fileNum.FileNum()
})
n := 0
for i := 0; i < len(a); i++ {
if n == 0 || a[i].fileNum != a[n-1].fileNum {
a[n] = a[i]
n++
}
}
return a[:n]
}
```
=> compaction: remove the duplicated function mergeFileInfo

compaction_test.go, data_test.go, error_test.go, ingest_test.go, iterator_histories_test.go, metamorphic/meta.go, open_test.go, record/log_writer_test.go, sstable/reader_test.go, testdata/iter_histories/errors, vfs/atomicfs/marker_test.go, vfs/errorfs/dsl.go, vfs/errorfs/errorfs.go, vfs/errorfs/errorfs_test.go, vfs/errorfs/testdata/errorfs
We frequently use the errorfs package to inject errors into filesystem operations to test error code paths. This commit builds off this package to support encoding error injection conditions within datadriven tests through parsing a small DSL. Future work will build off this to test handling of I/O errors during iteration.
Informs #1115.
Informs #2994.
=> vfs/errorfs: add facilities for error injection in datadriven tests

compaction_picker.go, tool/logs/compaction.go
There is a constant definition for `manifest.NumLevels`. But the literal value `7` is still hard code in the codebase. The PR tries to fix this issue and replace the literal value with the constant `manifest.NumLevels`.
=> *: use the constant manifest.NumLevels instead of literal value

ingest_test.go, vfs/mem_fs.go
Backport of #2065. Informs cockroachdb/cockroach#112087.
----
Default to Unix semantics in MemFS. The Windows semantics are left as configurable for unit tests that seek to ensure we don't remove open files, when possible.
There are existing cases where we cannot satisfy Windows semantics, and Go does not support opening files with the appropriate `FILE_SHARE_DELETE` permission bit (see golang/go#34681, golang/go#32088). The MemFS's implementation of Windows semantics is useful for ensuring we don't regress in the cases where we can satisfy Windows semantics.
Close #2064.
Informs #1236.
=> crl-release-22.2: vfs: default to Unix semantics in MemFS

internal/manual/manual_mips.go, internal/rawalloc/rawalloc_mips.go
Compilation fails on 32bit mips with:
```
$ env GO111MODULE=on GOOS=linux GOARCH=mips GOMIPS=softfloat  go build ./...
internal/rawalloc/rawalloc.go:22:2: type [2147483647]byte larger than address space
internal/cache/value_normal.go:54:2: type [2147483647]byte larger than address space
internal/cache/robin_hood.go:73:2: type [2147483647]byte larger than address space
internal/cache/entry_normal.go:92:3: type [2147483647]byte larger than address space
```
It turns out that `1<<31-1` overflows the mips address space.  This fixes it by defining `MaxArrayLen` as `1<<30` for 32bit mips architectures.
=> internal/{manual,rawalloc}: Reduce max array size to support MIPS

data_test.go, iterator_histories_test.go, range_keys.go, testdata/iter_histories/errors, vfs/errorfs/dsl.go, vfs/errorfs/errorfs.go, vfs/errorfs/testdata/errorfs
Previously, construction of an iterator over range keys that found sstables
containing range keys within L0 performed I/O to load the range key blocks
during iterator construction. This was less efficient: If the iterator
ultimately didn't need to read the keyspace overlapping the sstables containing
range keys, the block loads were unnecessary.
More significantly, if the I/O failed during iterator construction, the
resulting iterator was unusable. It would always error with the original error
returned by the failed block load. This is a deviation from iterator error
handling across the rest of the iterator stack, which allows an Iterator to be
re-seeked to clear the current iterator error.
Resolves https://github.com/cockroachdb/pebble/issues/2994.
=> db: defer loading L0 range key blocks during iterator construction 

metamorphic/meta.go, vfs/errorfs/dsl.go, vfs/errorfs/errorfs.go, vfs/errorfs/testdata/errorfs
Add a new Randomly errorfs predicate to replace the old WithProbability injector. The Randomly predicate takes a probability and optionally a seed.  I intend to use it in randomized tests by first generating a datadriven randomized test, and then executing it.
The predicate is deterministic with respect to file paths: its behavior for a particular file is deterministic regardless of intervening evaluations for operations on other files. This can be used to ensure determinism despite nondeterministic concurrency if the concurrency is constrained to separate files.
=> vfs/errorfs: add Randomly

db.go
Previously, we wouldn't retry a manual compaction if it returned ErrCancelledCompaction, even though the error message states that that compaction will be retried. Instead we returned this error to the caller.
This change checks for that particular error case and follows it up by retrying a compaction on that level.
Fixes #3011.
=> db: retry manual compactions that get cancelled

compaction_picker.go, db.go, db_test.go, error_test.go, event.go, event_listener_test.go, filenames_test.go, ingest.go, ingest_test.go, internal/base/logger.go, metamorphic/history.go, objstorage/objstorageprovider/sharedcache/shared_cache.go, table_cache_test.go
Add Errorf to the Logger interface. This allows us to log errors at the error level in Cockroach.
Informs cockroachdb/cockroach#112730.
=> db: add Errorf to Logger interface

go.mod, go.sum
Cockroach uses go1.21 as of cockroachdb/cockroach#112349. Update Pebble to do the same.
=> build: use go1.21

internal/keyspan/interleaving_iter.go, iterator.go
Previously, the InterleavingIter could violate the InternalIterator contract when an error is encountered. If one of its two child iterators encountered an error and returned a nil KV pair, the iterator could yield a non-nil KV to the caller. This commit updates the interleaving iterator error handling to accumulate any encountered errors on a field and always yield nil.
This bug was surfaced by a new 'invariants' tag assertion in Valid, asserting that Error() returns nil if the iterator is valid. With this invariants tag, existing tests surface the assertion failure. Additional test coverage will come with #1115.
=> internal/keyspan: fix InterleavingIter error handling

internal/metamorphic/meta_test.go, internal/metamorphic/metaflags/meta_flags.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/generator_test.go, metamorphic/key_manager.go, metamorphic/key_manager_test.go, metamorphic/meta.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, metamorphic/parser_test.go, metamorphic/test.go, metamorphic/testdata/parser, metamorphic/utils.go
This change adds a two-instance metamorphic test as well as a new metamorphic test command, db.Replicate, that under some testOptions does a shared ingestion (i.e. ScanInternal with skip-shared iteration to only get keys above files in shared levels) along with an excise, and in other testOptions it does a normal ingestion with range deletes/rangekeydels to clear out the "replicated" range
Fixes #2711.
=> metamorphic: Add TestMetaTwoInstance

vfs/disk_health.go, vfs/disk_health_test.go
Pass the start time in the form of nanoseconds since the unix epoch as a parameter to timeDiskOp and timeFilesystemOp. This aids post-mortem debugging when the disk-health checker fatals the process and GOTRACEBACK is set to dump the stacks, including arguments. The start time argument will be printed in hex form, allowing us to decode the start time of the operation. This can be used to confirm that the timed operation was still inflight at the time stacks were collected.
Close #3009.
=> vfs: pass start time in nanos to disk-health timing functions

batch.go, db.go, open.go
Add a guardrail that ensures a batch isn't in the process of being committed
when applying a mutation to the Batch. We've observed panics during batch
application that suggest concurrent modification of the batch, and these
guardrails will help surface any races more readily.
Informs cockroachdb/cockroach#113268.
Resolve #3024.
Informs #2873.
=> db: guard against concurrent batch writes during Commit

ingest_test.go, open.go, table_stats.go, testdata/ingest_shared
This change moves the Size() check for remote files to the asynchronous table stats loading job instead of the previous synchronous check during Open(). This greatly speeds up the time it takes to load up Pebble and make a node live, if the store had a lot of remote files before the restart.
=> db: move size check for remote files to table stats job

compaction_test.go, data_test.go, error_test.go, ingest_test.go, internal/dsl/dsl.go, internal/dsl/predicates.go, metamorphic/meta.go, vfs/errorfs/dsl.go, vfs/errorfs/errorfs.go, vfs/errorfs/errorfs_test.go, vfs/errorfs/testdata/errorfs
Extract the parsing logic of vfs/errorfs's DSL into a separate package providing generic interfaces for parsing lisp-esque DSLs.
Some error pathways are difficult to test only through filesystem-injected errors. This new package prepares for a similar DSL for errors injected by a special InternalIterator that wraps other internal iterators.
=> internal/dsl: new package

tool/logs/compaction.go, tool/logs/compaction_test.go
In recent releases, the log context now contains a tenant ID (`T`) that comes before the node. This was not accounted for in the logs regexp.
This commit fixes this and adds some tests.
=> tool: fix tool to tolerate T in the log context

tool/logs/compaction.go, tool/logs/compaction_test.go
In recent releases, the log context now contains a tenant ID (`T`) that comes before the node. This was not accounted for in the logs regexp.
This commit fixes this and adds some tests.
=> crl-release-23.2: tool: fix tool to tolerate T in the log context

metamorphic/config.go, metamorphic/generator.go, metamorphic/generator_test.go, metamorphic/key_manager.go, metamorphic/key_manager_test.go, metamorphic/meta.go, metamorphic/ops.go, metamorphic/options_test.go, metamorphic/parser.go, metamorphic/parser_test.go, metamorphic/test.go
This change deprecates and removes `generator.db` in the metamorphic package as it's duplicated by the `dbs` slice that was added to support multi-instance mode. All uses of `dbObjID` outside of tests are also updated to support multi-instance mode, and rely on deriving db IDs or having them passed-in instead of assuming one.
Snapshot operations are also updated to track the underlying DB IDs, and are now re-enabled in multi-instance mode albeit with some limitations that will be addressed in #2885.
=> metamorphic: allow snapshots in multi-instance, remove `dbObjID`

internal/keyspan/bounded_test.go, internal/keyspan/datadriven_test.go, internal/keyspan/defragment.go, internal/keyspan/defragment_test.go, internal/keyspan/iter.go, internal/keyspan/merging_iter_test.go, internal/keyspan/testdata/defragmenting_iter
A single iterator operation performed on a keyspan defragmenting iterator may
result in many iterator operations performed against its inner iterator.
Previously, in some circumstances if an error occurred during an inner iterator
operation other than the final one, the error was silently swallowed. This
allowed incorrect results, including spans that were not fully defragmented.
These commits fix these bugs. They also introduce some internal keyspan testing
facilities that build on the new internal/dsl package to provide iterator
"probes" for use in the keyspan datadriven tests. These probes may be used to
conditionally inject errors, mutate return values or log operations.
Future work will use these probes to expand error-handling unit tests for the
other iterators within the keyspan …
=> internal/keyspan: fix defragmenting iterator error handling

batch.go, error_iter.go, external_iterator.go, get_iter.go, internal/arenaskl/iterator.go, internal/base/iterator.go, internal/invalidating/iter.go, internal/keyspan/interleaving_iter.go, internal/keyspan/interleaving_iter_test.go, internal/keyspan/internal_iter_shim.go, iterator.go, iterator_test.go, level_iter.go, merging_iter.go, range_keys.go, scan_internal.go, sstable/block.go, sstable/reader_iter_single_lvl.go, sstable/reader_test.go
This is to allow for (short-lived) Iterator reuse in CockroachDB, and cases where the code that uses an Iterator is "far" from the code that uses the iterator (e.g. rangefeed.registration.maybeRunCatchUpScan).
Relates to https://github.com/cockroachdb/cockroach/issues/113257 and https://github.com/cockroachdb/cockroach/issues/113256
=> db: add SetContext method to Iterator to override existing context

db.go, scan_internal_test.go, testdata/scan_statistics
Also give one example of how to interpret these statistics. And clarify that SnapshotPinned* are not counting what they are claiming to count.
----
Release justification: Low risk observability improvement motivated by escalation involving CRDB liveness range.
=> release-23.2: db: add KeyStatistics.LatestKindsCount

internal/keyspan/filter.go, internal/keyspan/filter_test.go, internal/keyspan/testdata/truncate, internal/keyspan/truncate.go, internal/keyspan/truncate_test.go, table_stats.go
Previously if filteringIter's FilterFunc mutated the passed-in span to no longer be a valid return value for a SeekLT or SeekGE call, we would still return that span even though it could be >=  the seek key (for SeekLT), or less than it (for SeekGE).
This change updates filteringIter to guard for this case before returning from a seek call.
Found with #3044.
Informs cockroachdb/cockroach#113973, cockroachdb/cockroach#114056.
=> internal/keyspan: obey Seek invariants in filteringIter

internal/keyspan/filter.go, internal/keyspan/filter_test.go, internal/keyspan/testdata/truncate, internal/keyspan/truncate.go, internal/keyspan/truncate_test.go, table_stats.go
23.2 Backport of #3046.
----
Previously if filteringIter's FilterFunc mutated the passed-in span to no longer be a valid return value for a SeekLT or SeekGE call, we would still return that span even though it could be >=  the seek key (for SeekLT), or less than it (for SeekGE).
This change updates filteringIter to guard for this case before returning from a seek call.
Found with #3044.
Informs cockroachdb/cockroach#113973, cockroachdb/cockroach#114056.
=> crl-release-23.2: internal/keyspan: obey Seek invariants in filteringIter

internal/dsl/dsl.go, internal/dsl/predicates.go, internal/keyspan/bounded_test.go, internal/keyspan/datadriven_test.go, internal/keyspan/defragment.go, internal/keyspan/defragment_test.go, internal/keyspan/iter.go, internal/keyspan/merging_iter_test.go, internal/keyspan/testdata/defragmenting_iter
This is a 23.2 backport of #3029 and #3034 in order to fix and test the range key defragmenting iterator's handling of errors.
----
**internal/dsl: new package**
Extract the parsing logic of vfs/errorfs's DSL into a separate package
providing generic interfaces for parsing lisp-esque DSLs.
Some error pathways are difficult to test only through filesystem-injected
errors. This new package prepares for a similar DSL for errors injected by a
special InternalIterator that wraps other internal iterators.
**internal/keyspan: consolidate datadriven iterator ops**
Previously, a few different datadriven test repeated logic for driving a
FragmentIterator through datadriven commands. This commit refactors them to
share code for driving these datadriven commands.
**internal/keyspan: fix defragmenting …
=> crl-release-23.2: internal/keyspan: fix defragmenting iterator error handling

internal/keyspan/interleaving_iter.go
In #3021 (33a77e17) we fixed the InterleavingIter's error handling to propagate
all errors encountered by child iterators. This commit documents the invariants
more thoroughly.
Additionally the behavior of nextPos|prevPos is adjusted to set posExhausted if
on i.err != nil on entry. This fixes a remaining latent bug when changing
directions, resulting in two steps. Previously, if both steps were on the same
iterator and the first step errored but the second did not, the error could go
unnoticed.
Future work will unit test these cases explicitly using new error-injection
testing facilities.
=> internal/keyspan: document InterleavingIter error invariants

internal/keyspan/interleaving_iter.go, internal/keyspan/truncate_test.go, iterator.go
This is a 23.2 backport of #3021 and #3035.
----
Previously, the InterleavingIter could violate the InternalIterator contract when an error is encountered. If one of its two child iterators encountered an error and returned a nil KV pair, the iterator could yield a non-nil KV to the caller. This commit updates the interleaving iterator error handling to accumulate any encountered errors on a field and always yield nil.
This bug was surfaced by a new 'invariants' tag assertion in Valid, asserting that Error() returns nil if the iterator is valid. With this invariants tag, existing tests surface the assertion failure. Additional test coverage will come with #1115.
=> crl-release-23.2: internal/keyspan: fix InterleavingIter error handling

internal/rangekey/coalesce.go
In the invariants build, with onlySets set to false (i.e. in ScanInternal), we would see RangeKeyDels in the coalescer that would sort to the end of the span.Keys when in BySuffixAsc order. This is expected and should not trip up the invariant panic, but it was.
=> internal/rangekey: fix invariant check with onlySets=false

format_major_version.go
23.2 backport of #2992.
----
Previously nearly all events logged by the `EventListener` used types that had been marked as safe by implementing `SafeFormatter`, defining them as non-sensitive and not requiring redaction in logs, however `FormatMajorVersion` had been excluded. This change makes `FormatMajorVersion` a `redact.SafeValue` as well.
=> crl-release-23.2: event: mark `FormatMajorVersion` as safe from redaction

internal/keyspan/bounded_test.go, internal/keyspan/datadriven_test.go, internal/keyspan/merging_iter_test.go, internal/keyspan/testdata/merging_iter
Expand the unit tests for the MergingIter to test error-handling cases. These
unit tests did not surface any bugs. Future work will add randomized unit tests
at the top-level pebble.Iterator level.
=> internal/keyspan: test MergingIter error handling

Makefile
Move the `LATEST_RELEASE` initialization to the only target that uses it (crossversion-meta). For all other targets this just adds a delay (or error if there is no connectivity).
=> Makefile: don't git fetch for all targets

batch.go, batch_test.go, metamorphic/ops.go
Previously, the integration of range keys into the metamorphic test's ingest operation had a couple of bugs:
When constructing the sstable to ingest, the batch's range keys were fragmented, their sequence numbers zeroed and then written to the sstable. This allowed for a range key to be both SET and UNSET at the same suffix at the same sequence number, which is prohibited. Within a sequence number, range keys are required to be internally consistent. This commit resolves this issue by first coalescing the range keys and writing them out to the table. This mirrors the treatment of point keys in which we drop all but the most recent InternalKey at any particular user key.
When the ingestUsingApply test option was set, the batch's range keys were fragmented and then the individual keys were …
=> metamorphic: fix range key ingestion

data_test.go, db.go, ingest.go, scan_internal.go, sstable/reader.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/scan_internal
Contains 3 commits, each of which contains some fixes around shared/foreign sstables.
Previously, we weren't setting hideObsoletePoints to true for
compaction iters created out of shared foreign sstables. This
change addresses that by passing that state through virtualState
in VirtualReader through to the old Reader.
Unblocks https://github.com/cockroachdb/pebble/pull/3044.
Previously, we were calling checkVirtualBounds on FileMetadatas
before they were installed. This would lead to panics in invariant
builds as we would try to load an uninstalled FileMetadata
from the table cache.
This change removes the checkVirtualBounds call, making it a test-only
thing. Adding a check after version installation also doesn't guarantee
that refs will be nonzero, as a compaction immediately after …
=> *: shared ingestion fixes

objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/remote_backing.go, objstorage/objstorageprovider/remote_backing_test.go
Previously, we weren't adding the custom object name to the catalog. As a result, upon re-opening, various parts of pebble would treat this external object as a local object.
=> objstorage/objstorageprovider: save custom object name to catalog

compaction_iter.go, testdata/compaction_iter_delete_sized
The compaction iterator had a few methods and complicated edge cases that were undocumented. This commit comments some of these and adds a new assertion. It also adds a few test cases around SINGLEDEL and DELSIZED, unfruitfully trying to reproduce some form of behavior that might explain cockroachdb/cockroach#114421.
=> db: extend compaction iterator comments, tests

compaction_iter.go, testdata/compaction_iter_delete_sized
In bfb2e6a (#3081) a small refactor the handling of DELSIZED introduced a bug when a DELSIZED shadows a SINGLEDEL. When a DELSIZED and a SINGLEDEL meet in a compaction, we began accidentally emitting a SINGLEDEL rather than a DEL, weakening the tombstone. Previously the problematic code branch was only ever executed when a DELSIZED and DEL met, so iterKey.Kind() was always DEL.
Fix #3087.
=> db: fix newly-introduced SINGLEDEL+DELSIZED bug

compaction_iter.go, internal/base/internal.go
Previously the compaction iterator would avoid user key comparisons in some circumstances when invariants around sequence numbers implied user keys must be different. This commit removes this optimization, replacing it with an assertion that the sequence number invariants hold.
This is done out of caution and with the realization that these user key comparisons form a relatively small portion of the CPU cost of a compaction.
Informs cockroachdb/pebble#3082.
Informs cockroachdb/cockroach#114421.
=> db: remove compaction iter seqnum optimization, replace with assert

compaction_iter.go, internal/base/internal.go
Previously the compaction iterator would avoid user key comparisons in some circumstances when invariants around sequence numbers implied user keys must be different. This commit removes this optimization, replacing it with an assertion that the sequence number invariants hold.
This is done out of caution and with the realization that these user key comparisons form a relatively small portion of the CPU cost of a compaction.
Informs cockroachdb/pebble#3082.
Informs cockroachdb/cockroach#114421.
=> [crl-release-23.2] db: remove compaction iter seqnum optimization, replace with assert

compaction.go, compaction_test.go, format_major_version.go, get_iter_test.go, internal/keyspan/level_iter_test.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/version_check_ordering, internal/manifest/testdata/version_edit_apply, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go, replay/replay.go, testdata/compaction_check_ordering, testdata/manual_compaction, testdata/manual_compaction_file_boundaries_delsized, testdata/manual_compaction_set_with_del_sstable_Pebblev4, tool/db.go, tool/manifest.go, version_set.go
Adapt CheckOrdering to perform its overlap comparisons using the stricter requirement that adjacent files not contain the same user key. Since we still support the earlier format major versions that predate this requirement, this behavior is gated behind an OrderingInvariants enum variant determined by the active format major version.
Some of the tests that use more recent format major versions still created test cases with split user keys, and they needed to be adjusted.
Informs #3064.
=> db: enforce no split user keys in CheckOrdering

compaction_iter.go, testdata/compaction_iter_delete_sized
Backport of #3081, #3088 and #3089.
Informs https://github.com/cockroachdb/cockroach/issues/114421
=> crl-release-23.2: backport compaction iterator assertions

ingest_test.go
Deflake TestIngestLoadRand by using require.Equal instead of a pretty.Diff test assertion.
Close #2986.
=> crl-release-23.2: db: deflake TestIngestLoadRand

compaction.go, compaction_test.go, format_major_version.go, get_iter_test.go, internal/keyspan/level_iter_test.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/version_check_ordering, internal/manifest/testdata/version_edit_apply, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go, replay/replay.go, testdata/compaction_check_ordering, testdata/manual_compaction, testdata/manual_compaction_file_boundaries_delsized, testdata/manual_compaction_set_with_del_sstable_Pebblev4, tool/db.go, tool/manifest.go, version_set.go
23.2 backport of #3085.
----
Adapt CheckOrdering to perform its overlap comparisons using the stricter requirement that adjacent files not contain the same user key. Since we still support the earlier format major versions that predate this requirement, this behavior is gated behind an OrderingInvariants enum variant determined by the active format major version.
Some of the tests that use more recent format major versions still created test cases with split user keys, and they needed to be adjusted.
=> crl-release-23.2: db: enforce no split user keys in CheckOrdering

data_test.go, iterator.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/parser.go, testdata/iter_histories/internal_next
Add a new specialized CanDeterministicallySingleDelete function that allows a
user to inspect hidden internal keys within the current user key to determine
whether the behavior of a SingleDelete of the current Key would be
deterministic, assuming no writes are made to the key between Iterator creation
and commit of the SingleDelete. The CanDeterministicallySingleDelete func may
only be called on an Iterator oriented in the forward direction and does not
change the external Iterator position.
During intent resolution, CockroachDB will write a SINGLEDEL tombstone to
delete the intent if the intent's value indicates that it must have only been
written once. Subtle logic that cuts across the stack makes this optimization
possible, and one possible explanation for a recent instance of replica …
=> db: add CanDeterministicallySingleDelete

data_test.go, iterator.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/parser.go, testdata/iter_histories/internal_next
23.2 backport of #3077.
----
Add a new specialized CanDeterministicallySingleDelete function that allows a user to inspect hidden internal keys within the current user key to determine whether the behavior of a SingleDelete of the current Key would be deterministic, assuming no writes are made to the key between Iterator creation and commit of the SingleDelete. The CanDeterministicallySingleDelete func may only be called on an Iterator oriented in the forward direction and does not change the external Iterator position.
During intent resolution, CockroachDB will write a SINGLEDEL tombstone to delete the intent if the intent's value indicates that it must have only been written once. Subtle logic that cuts across the stack makes this optimization possible, and one possible explanation for …
=> crl-release-23.2: db: add CanDeterministicallySingleDelete

data_test.go, external_iterator.go, internal/rangekey/coalesce.go, internal/rangekey/coalesce_test.go, range_keys.go, scan_internal.go, scan_internal_test.go, testdata/scan_internal
This change moves the `scanInternalIterator` use case of
UserIteratorConfig over to something that's closer to
rangeKeyCompactionTransform, where internal keys are coalesced
using rangekey.coalesce, key order is maintained at ByTrailerDesc,
and defragmentation happens by internal key using
keyspan.DefragmentInternal. The onlySets var is renamed to internalKeys
and its meaning is reversed.
Fixes #3058.
=> *: handle non-Sets correctly in UserIteratorConfig

replay/replay_test.go
Currently, we don't increase the timeout for the require.Eventually call on compactions finishing up under race builds. This change increases the timeout to 5x what it otherwise is, recognizing that race+asan builds have this test running much slower than otherwise.
Fixes #2355
=> replay: bump up Eventually timeout in TestCompactionsQuiesce under race

batch.go, batch_test.go, db.go, internal/base/internal.go, mem_table.go, metamorphic/ops.go, open.go, replay/replay_test.go, testdata/batch_reader, testdata/compaction_iter, testdata/compaction_iter_delete_sized, testdata/compaction_iter_set_with_del, tool/find.go, tool/wal.go
Previously BatchReader.Next had a subtle API. If Next returned ok=false, the caller is responsible for checking len(r) and interpreting it as corruption if len(r) > 0. This commit introduces an explicit error return value.
Fixes #3023.
=> db: add an error return value to BatchReader.Next

go.mod, go.sum, sstable/random_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, vfs/errorfs/errorfs.go
Add a unit test that constructs sstables with random point keys using random
options and runs a random set of iterator operations against them. Randomly
inject errors into the VFS operations performed, and assert that if an error
was injected, it's also surfaced by the sstable.Iterator.
This test surfaced one new bug in #3052. This bug is fixed in the third commit.
Informs #1115.
Fixes #3052.
=> sstable: add error injection unit test, fix NextPrefix bug

batch.go, db.go, error_iter.go, external_iterator.go, range_keys.go, scan_internal.go, snapshot.go
Previously iterator construction methods did not have a return value to surface errors (like ErrNotIndexed), so errors encountered during construction would be surfaced through the first iterator operation by installing an errorIter and/or errorKeyspanIter within the iterator stack. We now have error return values for all the iterator construction methods and can return these errors eagerly.
Similarly, the ScanInternal methods have error return values available and do not need to propagate iterator construction errors through adding fake iterators to the iterator stack.
For now, the errorIter and errorKeyspanIter types remain for a few test cases and to serve as "empty" iterator implementations when all a table's keys are excluded.
=> db: return iterator construction errors eagerly

vfs/mem_fs.go
Strict `MemFS` methods can be used by mistake on a non-strict `MemFS`. Panic if this happens, instead of (previously) ignoring this silently. This saves a test writer time being confused if they mis-use the type.
=> pebble: panic on incorrect strict MemFS methods use

data_test.go, external_iterator.go, internal/rangekey/coalesce.go, internal/rangekey/coalesce_test.go, range_keys.go, scan_internal.go, scan_internal_test.go, sstable/reader.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/scan_internal
This change backports #3069 (1/1 commits) and #3074 (2/3 commits, the third being irrelevant for non-invariant builds)
---
Previously, we were passing range keys that were sorted by trailer
descending right from ScanInternal. However, the caller isn't
interested in seqnum-based sorting, only kind-based trailer sorting.
This change zeroes seqnums before sorting the keys.
Unblocks https://github.com/cockroachdb/pebble/pull/3044.
Previously, we weren't setting hideObsoletePoints to true for
compaction iters created out of shared foreign sstables. This
change addresses that by passing that state through virtualState
in VirtualReader through to the old Reader.
Unblocks https://github.com/cockroachdb/pebble/pull/3044.
This change moves the `scanInternalIterator` use case of
UserIteratorConfig …
=> crl-release-23.2: backport shared ingestion fixes

metamorphic/key_manager_test.go, metamorphic/meta.go, metamorphic/parser.go, metamorphic/parser_test.go, metamorphic/testdata/key_manager
Convert the TestKeyManager test and its existing test cases to a datadriven format. Future work will add additional test cases, and new functionality around tracking of range deleted spans.
=> metamorphic: convert TestKeyManager to datadriven

db.go, internal/metamorphic/meta_test.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, options.go, snapshot.go, tool/manifest.go
This change updates the metamorphic tests to support a new useExcise testOption and a new IngestAndExcise operation, which calls db.IngestAndExcise() if useExcise is true, or calls it with an sstable containing DeleteRange/RangeKeyDelete for the same span if useExcise is false.
Furthermore, a new private option is added, efosAlwaysCreatesIterators. If the test option for useExcise (or the previously added useSharedReplicate) is enabled, one of these two things happen to guarantee EFOS determinism around excises:
1) If efosAlwaysCreatesIterators is true, the behaviour of EFOS is changed to always hold onto a readState and never return errors from NewIter.
2) If efosAlwaysCreatesIterators is false, regular EFOS behaviour is retained, but a flush is completed after every EFOS instantiation …
=> metamorphic: add IngestAndExcise, make EFOS determinitic

README.md, format_major_version.go, format_major_version_test.go, snapshot_test.go
Expand the README with documentation on format major versions and the support for them in Cockroach versions.
This is a partial cherry-pick of #2162. For now we are not mentioning deprecating any version.
We also unexport an unused format constant.
=> README: expand on format major versions and version compatibility

README.md, format_major_version.go, format_major_version_test.go, snapshot_test.go
The reason for backporting this is that we will tag a `v1.0.0` release from this branch and it would be good if that included this information.
Expand the README with documentation on format major versions and the support for them in Cockroach versions.
This is a partial cherry-pick of #2162. For now we are not mentioning deprecating any version.
We also unexport an unused format constant.
=> crl-release-23.2: README: expand on format major versions and version compatibility

README.md
The version for 24.1 is incorrect. Removing the entire row given that it's a future release.
=> crl-release-23.2: minor fix to README.md

sstable/reader_iter_two_lvl.go
23.2 backport of the bug fix contained in #3051.
----
Previously, if reading the index or data block encountered an error while handling a NextPrefix operation on a sstable with a two-level index, the error was swallowed. This commit fixes the bug, returning to the caller so that the error may be propagated up the iterator stack.
This could benefit from a targeted unit test, but we don't yet have the machinery in place within the sstable package. In the meantime, the randomized test that surfaced the bug reproduces it on near every run.
Fix #3052.
=> crl-release-23.2: sstable: fix two-level iterator NextPrefix error propagation

batch.go, data_test.go, db.go, ingest.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go
This change adds an invariant-gated assertion that all range key operations are on suffix-less keys, as having range key operations on suffixed keys can break NextPrefix(). It also updates the metamorphic IngestAndExcise operation to only generate prefixes, as it does a RangeKeyDelete in
the non-excise case.
Fixes #3113.
Fixes #3121.
=> metamorphic: generate IngestAndExcise op on prefix keys

table_cache.go, table_cache_test.go
Add a benchmark for the hot path of `findNode` (when we hit the
cache).
A seemingly innocuous change in `tableCacheShard.findNode` resulted in
a new allocation. We named the return variable, then we captured it in
the `closeHook` callback, which I guess means that the pointer itself
needs to be put on the heap.
With this change `BenchmarkTableCacheHotPath` goes down from 1
alloc/op to 0, and the CRDB
`RefreshRange/linear-keys/refresh_window=[99.00,99.00]` benchmark goes
from 101 allocs/op to 61.
Informs https://github.com/cockroachdb/cockroach/issues/115215
=> db: fix regression in table cache hot path

table_cache.go, table_cache_test.go
Add a benchmark for the hot path of `findNode` (when we hit the
cache).
A seemingly innocuous change in `tableCacheShard.findNode` resulted in
a new allocation. We named the return variable, then we captured it in
the `closeHook` callback, which I guess means that the pointer itself
needs to be put on the heap.
With this change `BenchmarkTableCacheHotPath` goes down from 1
alloc/op to 0, and the CRDB
`RefreshRange/linear-keys/refresh_window=[99.00,99.00]` benchmark goes
from 101 allocs/op to 61.
Informs https://github.com/cockroachdb/cockroach/issues/115215
=> crl-release-23.2: db: fix regression in table cache hot path

version_set_test.go
This check is racy in both directions:
- we can check "too early", in that an asynchronous `collectTableStats` might still be holding a reference
- we can check "too late", in that cleanup of the obsolete table has already happened
Since object cleanup is not the main point of this test, this commit removes this check altogether.
Fixes #3043
=> db: fix flaky TestLatestRefCounting

batch.go, data_test.go, db.go, ingest.go, internal/metamorphic/meta_test.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, options.go, snapshot.go, tool/manifest.go
Revert commits 0f084ca9ef80783c7ff95f86408717b1a95ec180, 596d16da9806bc3c5622f6cc8faf415f6904f79c and 1b9268afc8ca6cae8c10dd7d9e4067dbde03256b that together integrate IngestAndExcise into the metamorphic tests. Virtual sstables are still unstable and leading to persistent metamorphic failures. This PR reverts the integration for now until the underlying issue can be fixed. This partially motivated by the need to get metamorphic test coverage of single deletes now.
Informs #3128.
=> metamorphic: revert IngestAndExcise integration

compaction_iter.go, testdata/compaction_iter, testdata/compaction_iter_delete_sized, testdata/compaction_iter_set_with_del
Previously, when a MERGE consumed a deletion tombstone during a compaction, the MERGE key was transformed into a SET. This SET lost knowledge of the previous deletion. Previously, a subsequent SingleDelete (intended to remove the MERGE key) could elide the SET, resurrecting internal keys that were deleted by the consumed deletion tombstone.
This commit adjusts the compaction iterator to produce a SETWITHDEL (see #1255) that preserves knowledge of the consumed deletion tombstone. This ensures that a SINGLEDEL that meets the merged key yields a DEL.
=> db: fix SINGLEDEL, MERGE + DEL interaction

compaction_test.go, testdata/compaction_elide_tombstone
Convert the TestElideTombstone unit test to a datadriven test. One of the test cases was removed because it tests a case that will be imminently unsupported (split user keys).
=> db: convert TestElideTombstone to datadriven

metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/key_manager_test.go, metamorphic/testdata/key_manager
This commit refactors the key tracking performed across objects and
decision-making around when to perform single deletes. Previously, the
metamorphic test tracked inflight writes to batches and restricted operations
to keys with inflight deletes (both SINGLEDEL and DEL). This commit takes an
alternative approach of tracking entire key histories per object and only
restricting per-object single deletes. This tracking alone is sufficient to
maintain single delete invariants for operations only performed directly
against the DB object.
Operations performed to batches and then committed to the database require
additional care. Rather than attempting to prevent violations from ever being
generated, this commit adapts the generator to detect violations and correct
them. When an applying or …
=> metamorphic: refactor key tracking for single deletes 

.github/workflows/ci.yaml, scripts/check-workspace-clean.sh
We run `make test generate` in CI, but the main point of that would be to check that all generated stuff is up to date.
This commit adds a last step that checks that the workspace is clean.
=> ci: check that make generate did not change anything

sstable/reader.go
23.1 backport of the bug fix contained in #3051.
----
Previously, if reading the index or data block encountered an error while handling a NextPrefix operation on a sstable with a two-level index, the error was swallowed. This commit fixes the bug, returning to the caller so that the error may be propagated up the iterator stack.
This could benefit from a targeted unit test, but we don't yet have the machinery in place within the sstable package. In the meantime, the randomized test that surfaced the bug reproduces it on near every run.
Fix #3052.
=> crl-release-23.1: sstable: fix two-level iterator NextPrefix error propagation

compaction.go, compaction_picker.go, db.go, ingest_test.go, testdata/ingest_external
This change adds a simplified Download() API implementation that uses any spare compaction concurrency to schedule copy compactions on the next external file in the download spans passed in. It also tracks for progress in `Download()` and returns when all external files are gone.
=> db: add simplified Download() that does copy compactions

metamorphic/options.go, metamorphic/test.go
Previously, we'd copy the contents of MemFS if a metamorphic test failed, but not the contents of shared storage if that was enabled. This change updates maybeSaveData to also copy over contents of the shared in-mem storage into a directory of its own.
=> metamorphic: copy shared storage contents when saving data

batch.go, data_test.go, db.go, ingest.go, internal/metamorphic/meta_test.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, options.go, snapshot.go, tool/manifest.go
This change disables all operations and options that would create
virtual sstables in TestMeta, while leaving TestMetaTwoInstance
as the sole metamorphic test testing virtual sstables. This
gives us interim test coverage for VSSTs while unblocking
TestMeta for singledel hardening/testing.
First three commits revert #3140, last commit disables IngestAndExciseOp
in the metamorphic test's defaultConfig and also turns off the ingestSplit
TestOption.
See #3128.
=> metamorphic: Unrevert virtual sstable integration, disable VSSTs in TestMeta

compaction_picker.go, compaction_picker_test.go, metamorphic/options.go, metamorphic/options_test.go, options.go, options_test.go, replay/testdata/replay, replay/testdata/replay_paced, testdata/metrics
Adapt the multilevel compaction heuristic into a metamorphic option, allowing
random option runs to use no multilevel compactions, multilevel compactions
with the default write amplification heuristic, and multilevel compactions with
additional, artificially inflated propensity.
Previously, the metamorphic tests tended to exercise simple multilevel
compactions, and especially multilevel move compactions. Now some random runs
should schedule a higher portion of nontrivial multilevel compactions.
=> metamorphic: increase probability of non-move multilevel compactions

compaction.go, compaction_iter.go, compaction_iter_test.go, metamorphic/options.go, metamorphic/options_test.go, options.go, testdata/compaction_iter, testdata/compaction_iter_delete_sized, testdata/compaction_iter_set_with_del
(clean) Backport of https://github.com/cockroachdb/pebble/pull/3118, https://github.com/cockroachdb/pebble/pull/3143, https://github.com/cockroachdb/pebble/pull/3153
The first PR is needed since the latter PRs include the MERGE case. The MERGE + SINGLEDEL is not exercised in CockroachDB.
Informs https://github.com/cockroachdb/cockroach/issues/115881
=> crl-release-23.2: backport compactionIter changes for SingleDelete assertions

Makefile
Previously the `crossversion-meta` target would test 23.2 -> 23.1 (moving back releases) because it always used the latest release. Update the Makefile to always test 22.2 -> 23.1 on the 23.1 release branch.
=> crl-release-23.1: Makefile: update crossversion-meta to test 22.2 -> 23.1 only

metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/key_manager_test.go, metamorphic/testdata/key_manager
This commit adjusts operation generation to track the smallest and largest keys in all objects. This is used to determine at generation time whether an ingestion should succeed or fail. Only if the ingestion will succeed is key manager state updated as if the operation succeeded.
This increases the probability of multi-batch ingestions and ingestions involving deletion operations through removing the old canTolerateApplyFailure mechanic that avoided ingesting some batches as a multi-batch ingestion if they contained any delete operations.
=> metamorphic: track object key bounds

compaction_picker.go, metrics.go, testdata/compaction_picker_target_level
23.1 backport of #2917. The backport was not clean because we refactored several pieces of the compaction picker over the course of 23.2, but the overall structure of the patch is the same.
----
During large table drops, we see level compensation become drastically high, which leads to L0 compaction starvation, which in turn leads to AC queueing of requests and increases in foreground latencies.
We completely ignore compensation during prioritization of levels during compaction, but we consider compensation when we try and pick a level for compaction.
The above approach ensures that L0 isn't starved during large table drops.
Note that there might be scenarios where a level say L3, has a high compensated score due to a wide range delete, and L3 will also drop a ton of data in L4, but we …
=> crl-release-23.1: db: use uncompensated scores to prioritize levels for compaction

ingest_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, testdata/excise
Previously, when a virtual sstable's iterator was SeekLT'd
past its end key or had Last() called on it, and the virtual
sstable had an inclusive end bound, we'd do a SeekGE on the end
key in `virtualLast()`. This had the potential of being inconsistent
with the rest of the iterator stack on the positioning of the
BoundLimitedBlockPropertyFilter in range-key combined iteration
with range key masking enabled, as the sstable iterator expects
that to always be set to a range key that's behind of us in the
direction we're iterating in. This saves some key comparisons
when checking for whether the current key is masked.
This change passes a SeekGEFlag for cases where we translate a
Last/SeekLT to a SeekGE, that overrides the direction specified
to loadIndex/loadData, forcing both the lower and …
=> sstable: fix incorrect range key mask in virtualLast() 

internal/keyspan/assert_iter.go, internal/keyspan/assert_iter_test.go, internal/keyspan/filter.go, internal/keyspan/interleaving_iter.go, internal/keyspan/level_iter.go, internal/keyspan/testdata/assert_iter, table_cache.go, table_cache_test.go, table_stats.go
Note: the first commit is https://github.com/cockroachdb/pebble/pull/3152.
This iterator is used in `invariants` mode to verify that the ranges
inside sstables (physical or virtual) conform to the smallest/largest
keys in the metadata.
=> keyspan: add AssertBounds iterator

data_test.go, format_major_version.go, format_major_version_test.go, ingest.go, ingest_test.go, internal/manifest/version.go, internal/manifest/version_edit.go, open_test.go, sstable/prefix_replacing_iterator.go, sstable/prefix_replacing_iterator_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, testdata/checkpoint, testdata/event_listener, testdata/flushable_ingest, testdata/ingest_external
These changes allow ingesting an sstable that contains keys that all have some prefix `old` as if it actually had been built with all of those keys with prefix `new`. This is done by changing "new" to "old" in the arguments to interactions with this sstable, and then changing "old" to "new" in the results of those interactions. 
There are plenty of potentially ways to implement similar behavior that might be more performant, however the goal of this initial implementation is more to demonstrate the functionality, and allow tests to start to be put in place to verify correctness, after which the performance can be optimized as needed (for example by pushing the replacement deeper into table reader, perhaps on specially-built tables that elide their common prefix, etc).
=> sstable: add NewPrefixReplacingIterator

compaction.go, compaction_test.go, db.go, ingest_test.go, internal/manifest/version.go
Move the pebble package's calculateInuseKeyRanges function into the manifest package as a method on Version. This is a more obvious place for this logic to live, but this is also done in preparation for a randomized test of CalculateInuseKeyRanges that will need to live in an external package (eg, manifest_test). Exporting it from the manifest package will allow the external test package to access the method.
=> internal/manifest: move CalculateInuseKeyRanges

metamorphic/config.go, metamorphic/example_test.go, metamorphic/generator.go, metamorphic/generator_test.go, metamorphic/key_manager.go, metamorphic/key_manager_test.go, metamorphic/meta.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/options_test.go, metamorphic/parser_test.go, metamorphic/test.go
**metamorphic: export OpType and its variants, OpConfig, DefaultOpConfig**
This commit exports the OpType and its variants, as well as related type
OpConfig and constructor DefaultOpConfig. This is in preparation for future
work that will allow other Pebble packages to run variants of the metamorphic
test with custom operation distributions.
**metamorphic: export a usable interface for running custom variants**
This commit refactors and exports a minimal interface necessary for generating
and running a set of operations against a randomized configuration. This
intended to be used in future work to make randomized testing easier, for
example by easily constructing a randomized database state by running the
metamorphic test with only write operations.
=> metamorphic: export a usable interface for running custom variants

internal/manifest/manifest_test.go, metamorphic/config.go
This commit adds a randomized test for CalculateInUseKeyRanges. One possible explanation for #114421 could be a compaction incorrectly eliding a tombstone too early, before it's deleted the key it's intended to delete. When a compaction begins, we calculate the "in-use key ranges" beneath the compaction. If a tombstone overlaps an in-use key range, it cannot be elided because there may exist a key that the tombstone should delete within the in-use key range.
This randomized test is intended to shake out any unconsidered edge cases within the non-trivial calculation of in-use key ranges performed during compaction setup.
=> internal/manifest: add TestInUseKeyRangesRandomized

internal/metamorphic/meta_test.go, internal/metamorphic/metaflags/meta_flags.go, internal/metamorphic/reduce_test.go, metamorphic/meta.go, metamorphic/parser.go, metamorphic/test.go, metamorphic/testdata/parser
This change adds a variation of `RunOnce` where we try to reduce the
number of ops that reproduce a problem.
Currently it can be used by tests that fail (e.g. with a panic or
internal error); extending it to "compare" mode in the future should
be easy.
Sample usage:
```
go test -run TestMetaTwoInstance ./internal/metamorphic \
--run-dir _meta/231220-073015.8533726292752/random-027 \
--tags invariants --try-to-reduce -v
```
The test will save the smallest reproduction found and print out the
relevant information.
=> metamorphic: add --try-to-reduce flag

format_major_version.go, ingest.go, metamorphic/options.go, open.go, options.go, scan_internal_test.go, table_cache.go, testdata/batch_reader, testdata/scan_statistics
We now require the `VirtualSSTables` format to use shared files. This
helps with replication via shared ingest and excise, which requires V4
table format.
We update the metamorphic tests to use the correct version when shared
storage is enabled.
We weren't setting this flag correctly When a shared file is ingested
by another store and then ingested back into the original store,
leading to an "out of order keys" error in `TestMetaTwoInstances`.
Informs #3174.
=> db: set hideObsoletePoints for "boomerang" files

sstable/data_test.go, sstable/format.go, sstable/format_test.go, sstable/options.go, sstable/random_test.go, sstable/reader_test.go, sstable/table.go, sstable/table_test.go, sstable/testdata/writer, sstable/testdata/writer_v3, sstable/writer_test.go
Add back support for older sstable formats. These are still not supported by any non-deprecated Pebble format, but they can be used if the `sstable` package is used directly. CockroachDB uses it to read data from backups, which could be old.
This will fix a bunch of "bad magic number" test failures which use older backup fixtures.
=> sstable: add back support for older formats

sstable/prefix_replacing_iterator.go, sstable/prefix_replacing_iterator_test.go
Previously SetBounds was passing the underlying iterator bounds that would mutate on the next call to any of the methods of the iterator, causing the unexpected value in the test case that is updated here as well.
=> sstable: fix PrefixReplacingIterator.SetBounds memory aliasing

data_test.go, event_listener_test.go, ingest_test.go, internal/keyspan/transformer.go, internal/rangekey/coalesce.go, metrics_test.go, sstable/reader.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/event_listener, testdata/ingest, testdata/ingest_shared, testdata/metrics
This change updates the virtual sstable range key iterator to
hide obsolete range keys for shared ingested files. It does
this by reusing the ForeignSSTTransformer that was removed
in https://github.com/cockroachdb/pebble/pull/2782.
This change also cleans up some dangling references to the older
`isForeign` way of determining whether to hide obsolete keys,
in lieu of the newer isSharedIngested approach to address
boomerang shared files.
Fixes https://github.com/cockroachdb/pebble/issues/3174.
=> sstable: hide obsolete range keys for shared ingested sstables

internal/metamorphic/meta_test.go, internal/metamorphic/metaflags/meta_flags.go, internal/metamorphic/metarunner/main.go, internal/metamorphic/reduce_test.go
The compare flag currently has format
`231220-164251.3552792807512/random-003,231220-164251.3552792807512/random-025`
This is dissimilar from the `--run-dir` format (which includes the
`_meta` dir) and is dissimilar from the format used to report a
failure, which is `_meta/231220-164251.3552792807512/{standard-000,random-025}`.
This change updates the flag to use the
`test-root-dir/{run1,run2,...}` format that is used to report
failures.
We generalize the reducer code to allow reducing compare failures.
=> metamorphic: support --try-to-reduce with --compare

checkpoint_test.go, cleaner_test.go, compaction_picker_test.go, compaction_test.go, data_test.go, db_test.go, error_test.go, event_listener_test.go, ingest_test.go, options.go, table_stats.go, table_stats_test.go
Export the previously private disableTableStats field to allow external users access. This is intended for use within external tests that require additional determinism.
=> db: add Options.DisableTableStats

.github/workflows/ci.yaml, db.go, objstorage/objstorageprovider/objiotracing/obj_io_tracing.go, objstorage/objstorageprovider/objiotracing/obj_io_tracing_on.go, objstorage/objstorageprovider/objiotracing/obj_io_tracing_test.go, tool/db_io_bench.go
Switch to `DiskFileNum` which makes more sense and matches how it is
actually used.
The objiotracing build (`make testobjiotracing`) was broken. This
commit fixes it and switches to `DiskFileNum` in this layer.
We also add the `testobjiotracing` target to the linux CI build.
=> db, objiotracing: more DiskFileNum cleanup

data_test.go, iterator.go, iterator_histories_test.go, testdata/iter_histories/errors
Previously, when iterating backwards within findPrevEntry, it was possible for an error to stop backwards iteration without the error propagating up: If the iterator state was already IterValid (eg, because we'd already observed a valid KV), the error was ignored, and the most recent entry was returned. This could cause a reader to observe an older version of the key than what was committed.
=> db: fix unpropagated error in Iterator.findPrevEntry

data_test.go, iterator.go, iterator_histories_test.go, testdata/iter_histories/errors
This commit adds datadriven test cases for an iterator error encountered while
switching from backward to forward iteration. It also fixes a case within
NextPrefix in which an `invariants` build would panic, improperly assuming
iterKey is non-nil (the only case in which it may be nil is if an error
occurred).
=> db: test iterator error while switching to forward direction

iterator.go, testdata/iter_histories/errors
Previously, if the underlying internal iterator encountered an error while
merging MERGE keys in the forward direction, the iterator would stop merging
and return a key representing the partially merged state up until the error.
This commit fixes the bug and adds a regression test.
=> db: fix unpropagated error in Iterator.mergeForward

internal/itertest/datadriven.go, internal/itertest/dsl.go, internal/itertest/probe.go, internal/itertest/probe_test.go, internal/itertest/testdata/probes, internal/keyspan/seek.go, keyspan_probe_test.go, level_iter.go, merging_iter.go, merging_iter_test.go, testdata/merging_iter
**internal/itertest: add iterator probes**
This commit introduces facilities for attaching 'probes' to internal iterators.
A probe is invoked on every operation against the iterator and provided with
information about the operation in-progress and its results. A probe may modify
the return result freely.
Building off the work in vfs/errorfs and internal/dsl, this commit introduces a
DSL for expressing probes and the circumstances with which they should
activate.
In the immediate term, probes will be used for error injection in intenral
iterator unit tests.
**db: fix mergingIter, levelIter error propagation**
This commit adds facilities for unit testing error propagation in the merging
iterator and level iterator through defining "probes" for individual file point
iterators or range …
=> db: fix mergingIter, levelIter error propagation

.github/workflows/stress.yaml, scripts/stress.sh
Add a nightly unit tests stress run. This won't autofile issues (requires more work); for now we can keep an eye on the build.
=> github: add nightly stress action

internal/metamorphic/reduce_test.go, metamorphic/diagram.go, metamorphic/diagram_test.go, metamorphic/meta.go, metamorphic/ops.go, metamorphic/simplify.go, metamorphic/simplify_test.go, metamorphic/testdata/diagram, metamorphic/testdata/simplify
This commit makes a few improvements to the metamorphic test:
- as part of `--try-to-reduce`, we now also try to simplify keys to
single characters; we also set a timeout and treat timeouts as
"bad" op sequences.
- we add support for diagrams that show the relevant keys or key
ranges for each operation; `--try-to-reduce` generates diagrams
when they would be of reasonable size.
- we improve error messages to show the `go test` command line that
can be used to reduce the ops; `--try-to-reduce` shows the
`go test` command line that can be used to re-run with the final
ops.
=> metamorphic: add diagrams, key simplification, more useful messages

Makefile
Previously the `crossversion-meta` target would test 23.2 -> 23.2 (moving laterally) because it always used the latest release. Update the Makefile to always test 23.1 -> 23.2 on the 23.2 release branch.
=> crl-release-23.2: Makefile: update crossversion-meta to test 23.1 -> 23.2 only

batch.go, db.go, flushable.go, ingest.go, ingest_test.go, internal/manifest/version.go, mem_table.go, mem_table_test.go, snapshot.go, testdata/mem_table, testdata/metrics
Creation of an eventually file-only snapshot requires inspecting the flushable queue to look for overlap with the key ranges of the new snapshot. This is performed while holding the DB mutex to avoid racing with other goroutines that may mutate the flushable queue. Previously, if ingested sstables were queued as flushable ingests, checking for overlap could perform read I/O while holding the database mutex.
Similarly, ingestion requires determining which ingested sstables overlap any flushables. This is used for correctness (to ensure we sequence the sstable higher in the LSM than any overlapping flushables) and for ingest statistics that we return to the caller. Previously, if ingested sstables were already in the queue as flushable ingests, checking for overlap could perform read I/O …
=> db: avoid mutex-protected I/O in Ingest and NewEventuallyFileOnlySnapshot

level_iter.go, testdata/merging_iter
Previously, if a levelIter exhausted a file, advanced to the next file and found no KVs within the file, it advanced past the file without checkign whether the seek errored.
=> db: propagate errors from levelIter.skipEmptyFile[Forward|Backward]

error_iter.go, internal/keyspan/assert_iter.go, internal/keyspan/bounded.go, internal/keyspan/datadriven_test.go, internal/keyspan/defragment.go, internal/keyspan/filter.go, internal/keyspan/iter.go, internal/keyspan/iter_test.go, internal/keyspan/level_iter.go, internal/keyspan/logging_iter.go, internal/keyspan/logging_iter_test.go, internal/keyspan/merging_iter.go, internal/keyspan/testdata/logging_iter, internal/treeprinter/tree_printer.go, internal/treeprinter/tree_printer_test.go, metamorphic/ops.go, options.go, range_keys.go, sstable/block.go, sstable/prefix_replacing_iterator.go
This change adds a logging `FragmentIterator` and new infrastructure
that allows injecting logging iterators in an entire iterator stack.
This helps understand how and why the stack produces a certain result.
We do this by adding a `FragmentIterator.WrapChildren()` method which
uses a given wrap function to replace any children iterators. The
wrap function itself can call `WrapChildren` again to recursively do
the same to all iterators in the stack.
Some iterators that create new child iterators on the fly have to
remember the wrap function.
Sample output: https://gist.github.com/RaduBerinde/0200d3c4726966f24c1ef81ed02e440e
The treeprinter library was lifted from cockroach without changes.
Sample output: https://gist.github.com/RaduBerinde/cc744c9922868740169cd670bfdb8b2a
=> keyspan: add logging infrastructure for iterator stacks

get_iter.go, internal/keyspan/fragmenter_test.go, internal/keyspan/get.go, internal/keyspan/get_test.go, internal/keyspan/testdata/get
The keyspan.Get helper is used by `DB.Get` to retrieve range deletions overlapping a particular key. It was written before #2146 when a `SeekGE(k)` seeked the iterator to the first span with a _start key_ ≥ k. In #2146, the semantics of `SeekGE(k)` was modified to seek to the first span with an end key greater than k (or, more intuitively, the first span to "cover" a key ≥ k). With the new semantics, a simple `SeekGE` seeks to the span covering `k` if any, and `keyspan.Get` only needs to verify that the returned span doesn't lie wholly after `k`.
Despite being written against the old iterator interface, the previous keyspan.Get implementation remained correct in the absence of iterator errors after #2146. However, if an iterator error occurred during the SeekLT, keyspan.Get would …
=> internal/keyspan: simplify Get and fix error handling

internal/keyspan/iter.go, internal/keyspan/seek.go, internal/keyspan/seek_test.go, internal/keyspan/testdata/seek, level_iter_test.go, merging_iter.go, testdata/merging_iter
Similar to #3209, this commit simplifies SeekLE for the new (as of #2146) FragmentIterator semantics. It also fixes a nil-pointer access if iter.Error()!= nil after Next-ing the iterator in the second else block.
=> internal/keyspan: simplify SeekLE, fix nil-pointer

external_test.go, metamorphic/config.go, metamorphic/history.go, metamorphic/meta.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/retryable.go, metamorphic/test.go, vfs/errorfs/dsl.go, vfs/errorfs/errorfs.go
Add a new randomized test that ensures errors injected within iterator
operations are surfaced to end users. The test uses the metamorphic test
framework to first generate a random database. It again uses the metamorphic
test framework to run random read-only operations against the database,
injecting errors randomly to VFS operations. The test fails if an error was
injected during the course of an operation, but the operation did not surface
an error.
Informs #1115.
=> db,metamorphic: add TestIteratorErrors

metamorphic/generator.go, metamorphic/ops.go, metamorphic/parser.go
The `closeOp` on a db now syncs with all objects associated with that
DB. This prevents the test from executing e.g. an iterator operation
in parallel with the db close operation.
Note that we only populate the field in `computeDerivedFields`, which
is now called by the generator (in addition to the parser).
Fixes #3205.
=> metamorphic: sync with all affected objects when closing DB

db_test.go, metrics_test.go, sstable/category_stats.go, sstable/reader.go, testdata/metrics
This could be helpful if some categories are seeing faster reads due to environmental effects (such as page cache or caches in virtual block devices).
=> sstable: add CategoryStats.BlockReadDuration

vfs/mem_fs.go
This commit fixes the following data race over `memNode.name`:
- `memFile.Stat().Name()` reads `memNode.name` without a lock
- `MemFS.Rename()` writes `memNode.name` under `MemFS.mu`
The `memNode.name` field is fundamentally owned by `MemFS`, so must be accessed under `MemFS.mu` lock. However, this lock is not accessible from `memNode`.
After this commit, `memNode` no longer implements `os.FileInfo`. Instead, the `FileInfo` role is now played by `memFile` (which has access to `MemFS`, and can use its lock to safely access the `name` field).
[Discovered](https://github.com/cockroachdb/pebble/pull/3220#issuecomment-1892616251) in CI.
=> vfs: fix data race over memNode.name

vfs/mem_fs.go, vfs/mem_fs_test.go
This PR fixes a bug in `MemFS.String()` method. For hard links created using the `Link()` method, `String()` previously printed the original file name rather than the name of the link.
=> vfs: fix hard link names in MemFS.String()

metamorphic/ops.go, metamorphic/options.go, sstable/options.go, sstable/testdata/writer_value_blocks, sstable/writer.go, sstable/writer_test.go
Previously there was no way to disable value blocks in table formats that supported value blocks. Now, it can be disabled using WriterOptions.DisableValueBlocks. This is never used by Pebble since we expect small sstables where the memory overhead of buffering value blocks in the sstable.Writer is acceptable.
Informs https://github.com/cockroachdb/cockroach/issues/117113
=> db: allow value block writing to be disabled

ingest.go, testdata/ingest_shared
Previously, for shared file ingestions, we could have seqnum substitution result in invalid bounds (eg. smallest > largest). This change detects this case as an artifact of seqnum substitution and addresses it.
Fixes #3225.
=> db: fix sstable bound inversion in ingestSynthesizeShared

batch.go, batch_test.go, batchrepr/reader.go, batchrepr/reader_test.go, batchrepr/testdata/reader, batchrepr/testdata/writer, batchrepr/writer.go, batchrepr/writer_test.go, commit.go, open.go, replay/replay_test.go
Move some of the logic related to the batch representation to a new batchrepr package. For now, this is primarily the BatchReader type and a few very small facilities around the Header. Future work may move additional logic related to writing new batch mutations and sorted iteration over a batch's contents, assuming there's no impact on performance.
This move is motivated by #3230. The planned wal package will need to inspect batch sequence numbers for deduplication when reconstructing the logical contents of a virtual WAL. Moving the logic outside the pebble package avoids duplicating the logic.
=> batchrepr: new package

flushable_test.go, ingest.go, ingest_test.go, internal.go, internal/base/internal.go, objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/remote.go, objstorage/objstorageprovider/remote_backing.go, objstorage/objstorageprovider/testdata/provider/shared_attach, objstorage/objstorageprovider/testdata/provider/shared_attach_after_unref, objstorage/objstorageprovider/testdata/provider/shared_attach_multi, objstorage/objstorageprovider/testdata/provider/shared_no_ref, objstorage/objstorageprovider/testdata/provider/shared_remove, open.go
We pass around pending `FileNum`s instead of `DiskFileNum`s, which
better matches the usage.
Move the attaching of external objects to the link phase. We already
attach the shared objects at this phase. We now attach all remote
objects with a single call.
Simplify `AttachRemoteObjects` to not call `sharedSync`. We already
call `Sync` as part of ingestion.
Add a call `sharedSync` when closing the provider (this should be a
no-op in practice, other than tests).
=> objstorage: simplify AttachRemoteObjects

level_checker.go, level_iter.go, merging_iter.go, table_stats.go, testdata/merging_iter
For a couple years now, Pebble has not allowed the creation of untruncated range tombstones outside the context of virtual sstables. Additionally, since v22.2 untruncated range tombstones should all have been compacted and rewritten as truncated range tombstones. Virtual SSTables (which similarly allow a physical range deletion to exceed the bounds of the containing logical sstable) handle this case by truncating the tombstones at iteration time in the iterator returned by keyspan.Truncate.
This leaves the merging iterator's delicate handling of untruncated range tombstones obsolete. This commit removes that complexity. In addition, as an extra safety precaution, the table stats collector's invariants-build assertion that range deletions are contained within their files' bounds is lifted …
=> db: remove handling of untruncated range tombstones

internal/base/close_helper.go, internal/base/iterator.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, tool/sstable.go
A flag indicates if an iterator is in the pool; if we call `Close()`
twice and the iterator has not been reused yet, we panic.
We add a `CloseHelper` which can absorb multiple `Close()` calls,
which is convenient to use with `defer`.
Also update the `InternalIterator` documentation to reflect the
reality that multiple `Close()` calls are not supported by all
implementations.
=> sstable: detect double Close on sstable iterators

ingest_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, testdata/excise
In the rare case where the data block iter does not return a key at the upper bound of the virtual sstable, such as due to the obsolete bit, we could go past the lower bound of the iterator in `virtualLastSeekLE`. This change addresses this by enforcing the lower bound in those conditionals in `virtualLast` where we previously weren't enforcing anything.
Fixes #3236.
=> sstable: enforce lower bounds in virtualLastSeekLE()

cleaner.go, external_test.go, get_iter.go, internal/keyspan/interleaving_iter.go, internal/keyspan/logging_iter.go, internal/keyspan/logging_iter_test.go, internal/keyspan/merging_iter.go, iterator.go, metamorphic/test.go, vfs/errorfs/errorfs.go
Fixes `TestIteratorErrors` failures.
We also improve the `Counter` injector to keep track of the stack
trace when the last error was injected.
Fixes #3234
This assertion was hit while stress-testing `TestIteratorErrors`. It
is not necessary, since the code is designed to block as needed. It
was there to make sure we never block under normal circumstances.
=> db: fix some iterator error paths

record/log_writer.go, record/log_writer_test.go
The syncQueue is generalized via the pendingSyncs and helper interfaces. pendingSyncs has two implementations, one for the standalone case where there is a real queue (backed by syncQueue), and one for the failover case where the LogWriter only tracks the latest record that has requested a sync.
LogWriterConfig.ExternalSyncQueueCallback is introduced for the failover case to inform the caller when a particular record index is synced. This callback is also utilized on close, to inform the caller of the tail of the records that have now been synced (even if they did not originally request to be synced).
SyncRecordGeneralized and CloseWithLastQueuedRecord are the new methods that will be used in the failover case.
Informs #3230
=> record: LogWriter changes for use in failover WAL writing

compaction.go, ingest.go, metamorphic/ops.go, metamorphic/options.go, options.go, snapshot.go, testdata/checkpoint, testdata/concurrent_excise, testdata/excise, testdata/ingest_shared, testdata/ingest_shared_lower, testdata/metrics, testdata/table_stats
Previously, we had to make EventuallyFileOnlySnapshots (EFOS) wait for all relevant keys in their key bounds to be flushed, just in case an excise came in before that happened. This change avoids the need to do that by assigning a seqnum to every excise (which will be useful when we do #2676), and by flushing any memtables that overlap with the protected ranges of any EFOS that has a sequence number below the excise.
The reduction in waiting is desirable as actual conflicts between excises and EventuallyFileOnlySnapshots are rare, while users of EventuallyFileOnlySnapshots were previously stuck waiting or stuck doing excessive flushes at times when no such excises were happening.
Fixes #3210.
=> db: have excises wait for EFOS below them, reducing EFOS waits

internal/metamorphic/reduce_test.go, metamorphic/ops.go, metamorphic/simplify.go
We weren't using the right key comparer for diagrams and simplification. We also weren't exposing the iterator bounds as keys.
=> metamorphic: minor fixes to the reducer

compaction.go, internal/rangekey/coalesce.go, internal/rangekey/coalesce_test.go, metamorphic/ops.go
The coalesce function is infallible and never returns a non-nil error return value. Remove the error return value altogether.
=> internal/rangekey: remove coalesce's error return value

internal/manifest/level_metadata.go
As far as I can tell, it's been unused since it's introduction in https://github.com/cockroachdb/pebble/pull/1648.
=> internal/manifest: remove unused keyTypeAnnotator

data_test.go, external_iterator.go, external_iterator_test.go, iterator.go, testdata/external_iterator, testdata/iter_histories/iter_optimizations
Remove the ExternalIterForwardOnly option that enabled a specific iterator optimization for extenral iterators that would move exclusively monotonically forward. The NextPrefix optimization removed the repeated SeekGE, Next usage of external iterators, making this optimization unnecessary.
=> db: remove ExternalIterForwardOnly

internal/base/filenames.go, open.go, wal/reader.go, wal/reader_test.go, wal/standalone_manager.go, wal/testdata/list, wal/wal.go
Add some internal (still unexported) facilities for listing the WAL files across several directories, ordering the consitutent files by log number and index.
=> wal: add facilities to list WAL files across Dirs

metamorphic/history.go, metamorphic/meta.go
In #2093 we accidentally changed the argument to `test.run` to be the
full subtest name (e.g. `-test.run=TestMeta/execution/random-015$`)
instead of just the top-level name. This makes the `$` ineffective and
we end up running both `TestMeta` and `TestMetaTwoInstance`.
The history object implements a logger object which can be used after
the end of the test if a database isn't closed. This can cause writes
to the history file after close (which can result in subtle issues).
This commit adds a `Close()` method to `history` which causes further
logging calls to be ignored.
=> metamorphic: fix passed test.run argument

options.go, vfs/disk_health.go, vfs/disk_health_test.go, vfs/fd_test.go
This commit introduces a disk write stats collector to the disk health checking virtual file system. It makes it possible to aggregate the bytes written on a `Write([]byte)` call and identify the behaviour that is responsible. This commit will be followed up with changes to pass down the write category to the vfs layer and changes to export categorized write metrics at the cockroach layer.
Informs cockroachdb/cockroach#115434
=> vfs: add disk write metrics to disk health checking vfs

ingest.go, internal/keyspan/truncate.go, level_iter.go, table_cache.go, table_stats.go, testdata/concurrent_excise, testdata/ingest_external, testdata/ingest_shared, testdata/ingest_shared_lower, testdata/level_iter_boundaries
The level iterator relies on checking if `SmallestPointKey` is of kind
`InternalKeyKindRangeDelete`. But in the case of external files, we
don't know the kind and we use `InternalKeyKindMax`.
We modify the code to always issue a synthetic boundary at the
smallest boundary if we have a rangeDel iterator, and adjust the logic
to potentially issue two synthetic boundaries (one at
`SmallestPointKey` and one at `Smallest`).
We add an external ingestion testcase which fails against the existing
code.
The kinds in the key bounds for shared ingestion can be incorrect
because of sequence number rewriting. We loosen the bounds to use the
minimum and maximum relevant kinds, similar to external file
ingestion.
We also switch to using `AssertBounds` instead of
`AssertUserKeyBounds` which is now …
=> db: use correct bounds for shared ingestion

batch.go, batch_test.go, db.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/ops.go, metamorphic/parser.go
**db: skip LogData when building batch iterators**
Previously, if a batch containing a LogData was sufficiently large to be
considered a 'large batch' and enqueued among the in-memory flushables, it
would be surfaced to the eventual memtable flush. With the current compaction
iterator assertions, the flush would fail when it observed an unexpected key
kind. The `Batch.refreshMemTableSize` and `Batch.Apply` functions also had bugs
in which they failed to consider LogData keys, which meant that a batch only
containing a single large LogData could be considered a large batch if it was
committed through these code paths.
This commit adjusts all memtable-size calculations to skip LogDatas and error
on key kinds not explicitly handled. It also adjusts the construction of a
flushable batch to …
=> db: skip LogData when building flushable batch iterators

internal/datadrivenutil/datadrivenutil.go, wal/reader.go, wal/reader_test.go, wal/testdata/reader
Add a new virtualWALReader type that handles merging multiple physical log
files that together form a single virtual WAL file. This new reader
implementation hides the complexity of reading back a WAL that's undergone
failover between devices.
Informs https://github.com/cockroachdb/pebble/issues/3230.
=> wal: implement virtual WAL reader

external_iterator_test.go, format_major_version.go, ingest.go, internal/base/options.go, internal/manifest/version.go, internal/manifest/version_edit.go, iterator_test.go, range_keys.go, sstable/block.go, sstable/block_property.go, sstable/block_property_test.go, sstable/block_property_test_utils.go, sstable/block_test.go, sstable/layout.go, sstable/random_test.go, sstable/reader.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, sstable/suffix_rewriter.go, sstable/testdata/block_properties, sstable/testdata/block_properties_boundlimited, sstable/testdata/virtual_reader, sstable/writer.go, table_cache.go
=> sstable: teach pebble about suffix replacement

batch.go, batch_test.go, internal/manifest/version_edit.go, testdata/flushable_batch
**internal/manifest: add verbosity in panic message** 
When pancing due to a L0 sublevels assertion failure, include the verbose
sublevels data in the panic message.
**db: don't assign LogDatas sequence numbers in flushable batches**
In https://github.com/cockroachdb/pebble/pull/3277 the calculation of a batch's memtable size and count was corrected to
no longer allocate memtable space or sequence numbers for LogData entries in
all cases. However the existing code was dependent on the sequence number
allocation for LogData entries when the batch was considered "large" and
enqueued among the flushables. When the large batch was indexed, LogDatas were
indexed and assigned sequence numbers (relative to the batch's first sequence
number). Since sequence numbers are not allocated for LogDatas, …
=> db: don't assign LogDatas sequence numbers in flushable batches

internal/testkeys/testkeys.go, internal/testkeys/testkeys_test.go, metamorphic/generator.go, metamorphic/key_generator.go
The `RandomSeparator` function is complex and very fragile: it can
fail and return `nil`, and it can return incorrect results if one of
the input keys is longer than ~13 characters (because of overflows in
the `Alpha` keyspace calculations).
In this commit we:
- add overflow assertions to `keyCount`
- replace `RandomSeparator` with a simpler `RandomPrefixInRange`
which returns a prefix in the `[a, b)` range. This function cannot
fail and supports any key lengths.
- change the metamorphic key generator to add a suffix to the
generated prefix.
=> testkeys: replace RandomSeparator

flushable_test.go, ingest.go, ingest_test.go, testdata/ingest_external
One of the validation checks was in the wrong place, leading to
errors.
During ingest we sort the `fileMetadata` for the external files
and then incorrectly assume they map 1-1 to the given `[]ExternalFile`.
This commit fixes this by refactoring the `loadResult` structure to
contain only three slices (for local, shared, and external) which
contain all the relevant information. We can now use `slices.SortFunc`
to sort and don't have to pass around the extra information for shared
and external files.
=> ingest: fix external backing mix-up during ingest

data_test.go, format_major_version.go, format_major_version_test.go, ingest.go, ingest_test.go, testdata/ingest_external
PR https://github.com/cockroachdb/pebble/pull/3240 introduced synthetic suffix replacement, whose use should be gated on 
a major format version. This follow up patch gates its use on the same major
format version added for prefix replacement and renames the version to
FormatSyntheticSuffixPrefix. This patch also adds more testing around synthetic
suffix ingestion.
=> rename FormatSyntheticSuffixes major format version to FormatSynethicSuffixPrefix

table_cache.go
This looks like an accidental leftover (it's not used anywhere).
=> db: remove syntheticSuffix from loadInfo

ingest.go, level_iter.go, metamorphic/build.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_generator.go, metamorphic/key_manager.go, metamorphic/meta.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, metamorphic/test.go, metamorphic/testdata/diagram, metamorphic/testdata/parser, metamorphic/utils.go, objstorage/objstorageprovider/remote_readable.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go
This commit adds two new operations:
- `newExternalObjOp` transforms a batch into an external object.
- `ingestExtternalFilesOp` ingests random parts of random external
objects. If external storage is not enabled, this operation is
emulated by creating sst files in the local FS and ingesting those.
The support of external storage is a setting independent of the shared
storage setting, allowing us to test more combinations. The external
storage uses the `"external"` locator whereas shared storage uses the
empty locator.
=> metamorphic: add external files ingest operation

compaction_test.go, internal/testutils/duration.go, wal/failover_writer_test.go
Unskip the test and just skip the time check, which is flaky on Windows because of its coarse timer. Add a test helper and use it for another similar existing case.
Fixes #3289.
=> wal: reenable TestFailoverWriter

open.go, vfs/errorfs/errorfs.go, wal/failover_manager.go, wal/failover_manager_test.go, wal/failover_writer.go, wal/failover_writer_test.go, wal/testdata/dir_prober, wal/testdata/failover_writer/blocking, wal/testdata/failover_writer/errors, wal/testdata/manager_failover, wal/wal.go
failover_manager.go contains the failoverManager (which implements
wal.Manager) for the write path, and helper classes. dirProber monitors
the primary dir when failed over to use the secondary, to decide when to
failback to the primary. failoverMonitor uses the latency and error seen
by the current *LogWriter, and probing state, to decide when to switch to
a different dir.
Informs #3230
=> wal: failover write path code

internal/manifest/version_edit.go, internal/manifest/version_edit_test.go
We were missing a `continue` which leads to an error when the suffix
rewrite tag is used (meaning we can't open a database).
This commit restructures the code into a single switch to make this
mistake less likely.
=> manifest: fix bug when parsing the suffix rewrite tag

internal/metamorphic/reduce_test.go, metamorphic/simplify.go, metamorphic/simplify_test.go, metamorphic/testdata/simplify
When we `--try-to-reduce` a failure, we try to simplify the keys into
single letters. This commit adds a mode where we only simplify the
prefixes and retain the suffixes.
=> metamorphic: support retaining prefixes when simplifying keys

ingest.go, internal/testkeys/testkeys.go, metamorphic/build.go, metamorphic/generator.go, metamorphic/key_generator.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go, metamorphic/test.go, sstable/block_property.go, sstable/block_property_test_utils.go, sstable/reader.go, testdata/ingest_external
Require that the smallest and largest keys for the external file have
no suffix when we are doing suffix replacement. This is sufficient for
our use case and makes things easier to reason about.
We also improve and correct a few comments around suffix replacement.
Add a random synthetic suffix for external ingestion.
One difficulty is that the synthetic suffix has to be larger (as an
integer value) than all suffixes in the object. We can't easily
determine this at generation time, so we generate a random suffix and
at runtime determine if it's ok to use or not.
=> metamorphic: add testing for synthetic suffix

sstable/block.go
=> sstable: add more commentary on synthetic suffix replacement

tool/find.go
Previously, the find tool used a map[base.DiskFileNum]string to record file paths across all file types. With #3230, WALs will need separate file path tracking because a single file number may actually consist of several physical files at several unique file paths. To avoid any confusion after this change is made, paths are now propagated alongside disk file numbers.
=> tool: adapt find command to explicitly track paths, filenames

checkpoint.go, db_test.go, open.go, wal/failover_manager.go, wal/failover_manager_test.go, wal/log_recycler.go, wal/reader.go, wal/reader_test.go, wal/standalone_manager.go, wal/wal.go
This commit separates the interface for reading WAL files from the Manager interface.  This helps unify some code on the read path, but it also makes it easier to support changing configuration (eg, changing secondary location or disabling failover).
=> wal: separate read interface from Manager

sstable/prefix_replacing_iterator.go, sstable/prefix_replacing_iterator_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, testdata/ingest_external
The prefix replacing iterators did not support arguments that don't
start with the synthetic prefix. We fix this by adding a `keyInRange`
argument that we can compare against when we are outside the synthetic
prefix range to figure out which side we are on.
We also fix assertions in `maybeVerifyKey` which were not correct when
prefix replacement is used.
Fixes #3319.
=> db: prefix replacement fixes

sstable/block.go, sstable/block_test.go
This patch adds a few test cases to ensure that when the block iterator adds a synthetic suffix to a key without a suffix, the block iterator calls behave as expected.
=> test  and add commentary on synthetic suffix replacement on keys without suffix

internal/keyspan/bounded_test.go, internal/keyspan/keyspanimpl/merging_iter_test.go, internal/keyspan/test_utils.go, internal/keyspan/truncate_test.go
In #3293 some helpers were exported for reuse in other tests and the file suffix of _test was removed, however this meant that the keyspan package started to link in datadriven even in non-test binaries. This is not desired, as datadriven has init-registered flags such as rewrite and should only be linked in test binaries.
Fortunately the helpers only needed a string field so we don't need to use 'datadriven' to pass it that.
=> internal/keyspan: remove datadriven runtime dep

cleaner.go, wal/failover_manager.go, wal/failover_manager_test.go, wal/failover_writer.go, wal/failover_writer_test.go, wal/reader.go, wal/standalone_manager.go, wal/testdata/failover_writer/blocking, wal/testdata/failover_writer/errors, wal/testdata/manager_failover, wal/wal.go
=> wal: implement failoverManager.{Obsolete,Stats} and log recycling

db.go, metamorphic/meta.go
Add a `DB.DebugString()` method which can be used during debugging.
The meta test uses it to log the final state of the db (which after
reduction will be right after the problematic operation).
=> db: add DebugString method

internal/manifest/manifest_test.go
One of the tests was leaking a Cache, which sometimes shows up as a
"cache has non-zero reference count" error (especially in coverage
builds).
=> manifest: unref Cache in test

ingest.go, metamorphic/history.go, sstable/prefix_replacing_iterator.go
Check for assertion errors when recording history and display their
stacktrace and panic. This helps with debugging.
We also fix some cases where we return an assertion error when we are
checking an API input; assertion errors should indicate a bug inside
Pebble.
=> metamorphic: special handling of assertion errors

data_test.go, sstable/reader_common.go, sstable/reader_iter.go, sstable/reader_iter_two_lvl.go, sstable/reader_virtual.go, testdata/ingest_external
The `ReplaceArg / ReplaceResult` methods are not too descriptive, I
always have to look at the code to remember which does what. Renaming
to `Apply` and `Invert`.
The sstable compaction iterators stop when the key exceeds
`vState.upper`; however this is incorrect when we replace prefixes
(the key has the content prefix and `vState.upper` has the synthetic
prefix).
Switch to using `i.upper` which is in the "content prefix space" and
was already calculated at initialization.
=> sstable: fix compaction iterator bug with prefix replacement

metamorphic/generator.go
Rework how we generate non-overlapping external ingestions to have
more freedom in selecting the bounds for each object. This will make
adding prefix replacement possible.
We also stop using `UniqueKeys` to generate the bounds which can fail
occasionally.
Fixes #3317.
=> meta: rework external ingest generation

wal/failover_manager.go, wal/failover_manager_test.go, wal/wal.go
Make UnhealthyOperationLatencyThreshold a `func() time.Duration` to allow dynamically modifying the threshold at runtime. This will be used by CockroachDB to tie the setting to a cluster setting.
Informs #3230.
=> wal: convert UnhealthyOperationLatencyThreshold to a func()

compaction.go, db_test.go, internal/base/filenames.go, internal/base/filenames_test.go, replay/replay_test.go, tool/find.go, tool/testdata/find, tool/wal.go, wal/failover_manager.go, wal/failover_writer.go, wal/failover_writer_test.go, wal/reader.go, wal/reader_test.go, wal/standalone_manager.go, wal/wal.go
**wal: extract filename parsing to a FileAccumulator**
This commit extracts the logic around parsing filenames and constructing
LogicalLogs from them into a new FileAccumulator type, and uses this type to
implement Scan.
**tool: parse WAL files through wal.FileAccumulator in find**
Adjust the [find] debug tool to use wal.FileAccumulator to parse and accumulate
physical log files. All parsing of WAL filenames should be delegated to the wal
package which understands the physical log format.
***: delegate all log filename handling to the wal package**
This commit removes the remaining instances where non-wal packages attempt to
parse wal filenames.
=> *: delegate all log filename handling to the wal package

open_test.go, tool/testdata/db_lsm, wal/failover_manager.go, wal/reader.go, wal/standalone_manager.go, wal/testdata/manager_failover
During Open, there may exist log files that were constructed from a previous WAL configuration. Adjust both the standalone and failover WAL managers to account for WALs of a kind other than their own by separately recording these initial logs as obsolete.
Informs #3230
Informs [CRDB-35401](https://cockroachlabs.atlassian.net/browse/CRDB-35401)
=> wal: handle initial obsolete logs

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, data_test.go, db.go, get_iter_test.go, ingest.go, ingest_test.go, internal/base/comparer.go, internal/keyspan/keyspanimpl/level_iter_test.go, internal/manifest/l0_sublevels_test.go, internal/manifest/manifest_test.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go, level_checker_test.go, open.go, open_test.go, options.go, replay/replay.go, table_stats.go, table_stats_test.go, tool/db.go, tool/lsm.go, tool/manifest.go, version_set.go
This PR is only for the top commit (the rest is #3346).
The `Version` and `VersionEdit` code has a ton of `Compare` and
`FormatKey` arguments passed around. We simplify all this code by
storing a `*base.Comparer` reference in `Version` and `versionSet`.
=> manifest: store comparer in Version

data_test.go, ingest_test.go, testdata/ingest_external
Use a better syntax for the external ingestion test, which allows
specifying prefix and suffix replacement per object.
=> pebble: improve syntax for external ingestion test

batch.go, get_iter.go, ingest.go, internal/base/comparer.go, internal/base/iterator.go, iterator.go, level_iter.go, snapshot.go, sstable/writer.go, tool/sstable.go
This change makes `Comparer.EnsureDefaults` set a trivial `Split`
implementation which returns the full length of the key. This
simplifies code which had to check `Split != nil`, and we no longer
have to think about what are the semantics of a given operation when
`Split` is  `nil`.
=> base: default Split to trivial implementation

metamorphic/generator.go, metamorphic/key_manager.go
Fix invalid DeleteRange bounds where the keys can be equal; this
causes a problem when it results in an external object with invalid
bounds.
We also add more assertions around bounds.
Informs #3325
=> metamorphic: fix invalid DeleteRange bounds

open.go, options.go, options_test.go, wal/failover_manager.go, wal/failover_manager_test.go, wal/standalone_manager.go, wal/wal.go
Add new WALFailover and WALRecoveryDirs fields to the pebble.Options. The
WALFailover field enables and configures WAL failover when present. The
WALRecoveryDirs field may be used when modifying WAL configuration (eg, either
changing the WALFailover configuration or the Options.WALDir),  to supply
additional paths that should be scanned for relevant WALs during recovery.
Informs https://github.com/cockroachdb/pebble/issues/3230.
Informs [CRDB-35401](https://cockroachlabs.atlassian.net/browse/CRDB-35401)
=> db: add WALFailover to the Options

checkpoint.go, checkpoint_test.go, db.go, internal/manifest/file_backings.go, internal/manifest/version_edit.go, version_set.go, version_set_test.go
We currently maintain a map of `FileBacking`s in the pebble package
and pass callbacks to add and remove backings to the `manifest`
package. This commit cleans this up by defining a `FileBackings` data
structure in `manifest` and passing that instead.
=> manifest: add FileBackings structure

metamorphic/options.go
Cross-version metamorphic tests use an initial database state produced by a previous run of the metamorphic test with a different configuration. Since the previous and current configurations may use differing directories for WALs, we need to account for this difference during setup. Previously the test would copy all WALs into place. With the introduction of Options.WALRecoveryDirs, we can simply add the previous WAL directory as a recovery-only directory to ensure the relevant WALs are replayed during Open.
=> internal/metamorphic: use WALRecoveryDirs in cross-version tests

open.go, open_test.go, testdata/open_wal_failover
On Open create and sync the WALFailover's secondary directory if it doesn't yet exist. Open will List the contents during recovery and expects it to exist. Add a new TestOpen_WALFailover test to exercise this behavior and other Open behavior with respect to WAL failover.
Informs #3230.
=> db: create the WALFailover.Secondary directory on Open

.github/workflows/ci.yaml
Use this in CI test runs. Showing all goroutines should help pinpoint
the test that was running when a panic is hit in a background task
(like collecting table stats).
=> ci: use GOTRACEBACK=all

ingest.go, internal/manifest/version.go, sstable/block.go, sstable/block_test.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_iter_single_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, testdata/ingest_external
=> teach pebble about block level prefix synthesis

data_test.go, ingest.go, metamorphic/generator.go, metamorphic/ops.go, testdata/ingest_external
We already require this when `SyntheticSuffix` is used.
Also, use `Bounds KeyRange` instead of `SmallestUserKey/LargestUserKey`
in `ExternalFile`.
=> db: require ExternalFile bounds without suffixes

ingest.go, metamorphic/build.go, metamorphic/generator.go, metamorphic/key_generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/test.go
Note : `require ExternalFile bounds without suffixes` commit is a separate PR #3357
We use this information to select a Batch without range keys when
creating an external object (rather than ignoring them). We will use
the range dels to correctly generate synthetic suffix/prefix upfront
(instead of correcting them during `run()`, which makes tracking key
histories inaccurate).
We also clean up the object merging code a bit.
Change `SortedKeysForObj` and `inRangeKeys` to return a slice of
`keyMeta` instead of `*keyMeta`. This makes it more clear that we
don't modify them (and allows local modification as needed).
This commit corrects the tracking of external ingestion keys in the
key manager when synthetic suffixes are used. This is important for
detecting SINGLEDEL conflicts correctly. …
=> metamorphic: fix tracking of external ingest keys with synthetic prefix

data_test.go, open_test.go, options.go, options_test.go, testdata/open_wal_failover
**db: introduce separate [WAL Failover] stanza in OPTIONS file**
Add a new [WAL Failover] stanza to the OPTIONS file and serialize all the exposed WAL failover options under the stanza. We don't anticipate users modifying these duration settings, but serializing them will help with the integration of the metamorphic test. In the metamorphic test, we'll be able to vary these settings from run to run and simulate a wider variety of behaviors.
**db: fix TestOpen_WALFailover data race**
Previously, there was a data race where the memFile may be Close'd while it was
was still being read.
=> db: introduce separate [WAL Failover] stanza in OPTIONS file

vfs/errorfs/dsl.go, vfs/errorfs/latency.go, vfs/errorfs/testdata/errorfs, wal/failover_manager.go, wal/failover_manager_test.go
**vfs/errorfs: add RandomLatency injector**
Introduce a new RandomLatency injector that injects latency rather than errors.
Informs #2482.
Informs #3230.
**wal: fix FailoverManager Close deadlock**
Fix a deadlock while closing a failover manager: The dirProber goroutine could
notice that it shouldQuiesce before the failover monitor and exit. If the
failover monitor is in the process of switching, it may attempt to enable or
disable probing which would block indefinitely waiting for the dirProber
goroutine that is no longer running.
=> wal: fix FailoverManager Close deadlock 

metamorphic/build.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/parser.go
This commit adds prefix synthesis (i.e. `PrefixReplacement` with empty
`ContentPrefix`) to the metamorphic test.
We generate a random prefix and prepend it to the initially-generated
bounds. We take it into account when emulating the ingestion and when
determining key histories.
=> metamorphic: add testing for prefix synthesis

batch.go, batch_test.go, commit.go, commit_test.go, db.go, internal/datadrivenutil/datadrivenutil.go, mem_table_test.go, testdata/batch_reuse, wal/failover_manager_test.go, wal/failover_writer.go, wal/failover_writer_test.go, wal/standalone_manager.go, wal/wal.go
Fix a data race between Batch reuse and WAL failover. Before the existence of WAL failover, a committed batch was read synchronously during the commit pipeline's call to LogWriter.[Write|Sync]Record. When Batch.Commit returned, the caller was guaranteed that the Batch was safe for reuse. The Batch could be reused either immediately and explcitly through calling Reset, or implicitly through calling Close which added the Batch to a sync.Pool.
Now, when  WAL failover is configured, a committed batch must be retained by the WAL writer until the batch has been durably synced, because it may need to re-encode the batch into a new WAL block for a new WAL file in the event of a failover. If the Batch was reused before the wal.Writer's reads completed, the wal.Writer could read the mutated batch …
=> db: fix batch recycling data race with WAL failover

metamorphic/meta.go, metamorphic/options.go, metamorphic/options_test.go
Integrates WAL failover into the metamorphic tests as a random option with random durations. Future work #2482 will expand the circumstances in which we'll actually exercise failover by injecting artifical I/O latency.
Informs #3230.
=> metamorphic: use WAL failover

metamorphic/meta.go, metamorphic/options.go
Inject random latency in some IO operations in some random configurations of the metamorphic test. This helps exercise code that's dependent on IO latency, most notably WAL failover.
Close #2482.
=> metamorphic: inject random IO latency

compaction_picker.go, compaction_picker_test.go, internal/manifest/version.go, testdata/compaction_picker_pick_file
When we consider a virtual sst as a candidate for the seed file for a compaction, the size of that sst is adjusted by a fraction of the garbage in the backing sst, where the fraction is the reciprocal of the number of virtual ssts that are referencing this backing sst.
The objective is to reduce space amp, by being aware of garbage accumulation, when picking compactions.
Fixes #2323
=> db: account for garbage in backing files when picking a compaction

db.go, db_test.go
=> db: during WAL failover, don't write stall due to too many memtables

data_test.go, db.go, ingest.go, ingest_test.go, internal/manifest/level_metadata.go, metamorphic/ops.go, options.go, scan_internal.go, scan_internal_test.go, snapshot.go, testdata/ingest_external, testdata/scan_internal
This change contains three changes:
1. The ability to iterate over external files.
2. Allowing a mix of local and remote files at the _first_ level where remote files are present when iterating.
3. Supporting importing External files in the same way that we do for SharedSSTs.
Like the sharedFileVisitor, the new externalFileVisitor allows the caller to process external files directly.
In this PR, the externalFileVisitor only applies to L6 and L6 must be completely external or shared files.
=> allow replication of external files

db.go, internal/manifest/level_metadata.go, scan_internal.go
Previously, we were adding remote file skipping logic to LevelIterator alongside the logic to skip files without point/range keys. Since determining whether a file is remote or not requires an objprovider call, this change moves that to iterator construction and undo's the change to leveliterator.
=> db: move skip-remote logic out of manifest.LevelIterator

wal/failover_writer.go
failoverWriter has competing consumers who do compare-and-swap (CAS) to pop from recordQueue. Since the CAS releases the popped slots in buffer to the producer, the consumers need to read the contents of these slots before doing the CAS. After the CAS, they only use the read entries that they actually popped. But the fact that they read some entries, even though they are not going to use them, trips up the data race detector (since the read can be happening while the producer is writing).
We work around this by introducing a consumer mutex to make consumption single threaded. This is acceptable since what we really care about is many concurrent producers, and consmers not interfering with producers.
Fixes #3380
Informs #3230
=> wal: work around false data race in failoverWriter

checkpoint.go, checkpoint_test.go, compaction.go, db.go, internal/manifest/version_edit.go, testdata/excise, testdata/ingest_shared, testdata/ingest_shared_lower, version_set.go, version_set_test.go
Rename to clarify that this includes only backings for virtual
sstables.
And fix the copy compaction code to create the backing in the
manifest.
=> db: verify virtualBackings in invariants mode

db.go, error_iter.go, external_iterator.go, get_iter.go, internal.go, internal/base/iterator.go, internal/invalidating/iter.go, iterator.go, iterator_test.go, merging_iter.go, testdata/iter_histories/range_keys_simple, testdata/iterator, testdata/merging_iter, testdata/merging_iter_seek
Currently for `SeekPrefixGE` calls we filter out keys without a matching prefix at the top layer iterator. This causes the merging iterator to build a larger heap containing entries without the required prefixes. This commit shifts the prefix filtering responsibility to the merging iterator before inserting keys in the heap.
Fixes #2182.
=> iterator: require prefix filtering in merging iterator

vfs/vfstest/open_files.go, vfs/vfstest/open_files_test.go
Add a wrapping vfs.FS implementation that tracks open files and prints the stack trace of the call to open them. I wrote this to debug leaked files in Cockroach. This is a common occurrence (eg, cockroachdb/cockroach#117853).
=> vfs/vfstest: add WithOpenFileTracking

ingest.go, scan_internal.go, testdata/ingest_external
When truncating external files to our scan bounds, we may find that the file has Start == End. Other validation in ingest asserts these are invalid bounds.
=> scan_internal: don't visit empty external files

internal/keyspan/keyspanimpl/level_iter_test.go, internal/manifest/l0_sublevels_test.go, internal/manifest/manifest_test.go, internal/manifest/testdata/version_edit_apply, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, replay/replay.go, tool/db.go, tool/manifest.go, version_set.go
Previously, the logic for maintaining the `virtualBackings` map was very convoluted; in addition, modification happened outside `DB.mu` which makes the map unusable outside the log lock (we will want to use it for finding existing external backings).
`Apply` is no longer responsible for updating the backing refcounts and the `virtualBackings` map (and for updating a zombies map). It is more straightforward to do that separately (and under `DB.mu`); this allows us to remove `AccumulateIncompleteAndApplySingleVE` as well, which was semantically dubious (e.g. it modified `ve`).
=> db: rework backing refcount management

internal/manifest/testdata/version_edit_apply, internal/manifest/testutils.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go
Some background: the goal of these changes is to address [a versionSet test TODO](https://github.com/cockroachdb/pebble/blob/master/version_set_test.go#L216) as I am reworking where and how the "latest ref"s are maintained.
We add a parsing helper and use it to simplify the
`ParseFileMetadataDebug` and `ParseVersionDebug` code. This will make
it easier to extend these functions (e.g. to support virtual
sstables).
In this commit we add a `ParseVersionEditDebug` which can create a
`VersionEdit` from a `DebugString` output (similar to
`ParseFileMetadataDebug` and `ParseVersionDebug`).
We improve `TestVersionEditApply` to use the `DebugString` formats
instead of a one-off format.
=> manifest: improve VersionEdit tests

internal/manifest/testdata/version_edit_apply, internal/manifest/testutils.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go, testdata/excise, testdata/ingest_shared, testdata/ingest_shared_lower
This makes the format of the fields more consistent.
Improve the debug parsing methods to parse virtual tables and backing
operations and add some `version_edit_apply` tests with virtual
tables.
=> manifest: add VersionEdit tests with virtual tables

tool/db.go, tool/tool.go
In #3395 I added a new tool.DirectoryLock option for passing an already-acquired directory lock. This was motivated by cockroachdb/cockroach#120156 which begins to acquire the lock before loading encryption-at-rest state. When adding that option, I forgot the nuance that the tool doesn't know what database you'll open at the time the tool is initialized. When a node has multiple stores, the operator might try to open any of them. CockroachDB will lazily initialize the encryptedFS for a store only once the tool attempts to access a path within the store.
This commit removes the DirectoryLock option and adds a new OpenOptions option that allows the caller to pass in arbitrary OpenOptions that are run when constructing the pebble.Options to use. CockroachDB will be able to implement an …
=> tool: replace DirectoryLock with OpenOptions

compaction.go, objstorage/objstorage.go, sstable/suffix_rewriter.go, sstable/writer.go
Pulling these fixups out of an in-progress change to make it and them easier to review in isolation.
=> sstable: cleanup/move code, fix two-level when calling sync add

db_test.go, metamorphic/options.go, options.go, wal/failover_manager.go, wal/failover_manager_test.go, wal/testdata/manager_failover, wal/wal.go
This commit adds a new bool return value to the option func UnhealthyOperationLatencyThreshold that allows the client to dynamically toggle whether failover is permitted. This will be used by Cockroach to prevent failover until cluster version finalization begins.
Informs #3230.
=> wal: allow runtime toggling of WAL failover

testdata/open_wal_failover, wal/wal.go
Adjust the FailoverOptions defaults to match our initial choices for use in Cockroach. Additionally, this provides a default for ElevatedWriteStallThresholdLag which previously had none.
Informs #3230.
=> wal: adjust FailoverOptions defaults

internal/manifest/testdata/virtual_backings, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/virtual_backings.go, internal/manifest/virtual_backings_test.go, testdata/version_set, version_set.go, version_set_test.go
Add `Protect` and `Unprotect` which control a separate ref count on
each backing. This will allow external ingestions to temporarily
prevent a backing from being removed from the latest version.
This commit updates versionSet code to support protected virtual
backings. The main change is that we now also `Ref` all backings that
exist in `vs.virtualBackings`; we reorganize the code related to
zombie backings in `logAndApply` to facilitate maintaining these refs
correctly.
=> db: add virtual backing protection mechanism

sstable/reader.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go
All uses of `errCorruptIndexEntry` swallow the actual error. This
commit changes it into a function that retains the original error
message. We also panic in invariants mode.
=> sstable: better corrupt index entry errors

checkpoint.go, checkpoint_test.go, objstorage/objstorage.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/remoteobjcat/catalog.go, testdata/checkpoint, testdata/checkpoint_shared
Previously, if we couldn't read a remote file's DiskFileNum locally, we'd error out on the Checkpoint() function even though the store was valid and the file just happened to be remote (shared or external). This change adds support for saving the catalog's state to the checkpoint directory so references to remote files from the checkpoint can still be resolved. To prevent unreffing of shared files, we need to add a dangling reference to them that doesn't get deleted.
Fixes #3362.
=> db: add support for checkpointing with remote files

data_test.go, ingest.go, metamorphic/ops.go, scan_internal.go, scan_internal_test.go, testdata/ingest_external, testdata/scan_internal
An excise can result in an external file having an inclusive bounds. But, previously we would erroneously expose that as an exclusive bounds.
Here, we add a boolean that indicates whether the Bounds on and ExternalFile are inclusive.
=> ingest: expose inclusive bounds for ExternalFile end keys

checkpoint_test.go, metamorphic/options.go, metamorphic/options_test.go, options.go
Allow clients to change configuration of the compression algorithm at runtime. This will be used to tie the compression algorithm to a CockroachDB cluster setting, enabling opt-in use of zstd.
=> db: allow runtime configuration of compression

format_major_version.go, ingest_test.go, open.go, open_test.go, testdata/peek, version_set.go, vfs/atomicfs/marker.go
The pebble.Peek function allows external users to retrieve metadata about an Engine without opening it. This commit adds the filename of the latest OPTIONS file to the output, so the caller may parse the options used by the most recent process. Additionally, this commit adds new methods for locating atomicfs.Marker that use an existing directory listing to avoid repeated listing of the data directory during Open and Peek.
=> db: surface OPTIONS filename in pebble.Peek

checkpoint.go, compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, flushable.go, ingest.go, internal/base/internal.go, internal/base/key_bounds.go, internal/base/key_bounds_test.go, internal/keyspan/span.go, internal/manifest/level_metadata.go, internal/manifest/manifest_test.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_test.go, table_stats.go
This commit adds `UserKeyBounds` which represents a range of user keys with inclusive start boundary and either inclusive or exclusive range boundary.
This replaces ad-hoc code in various places.
Note: I think there are more places where this can be used and I will look at them as a follow-up, I just didn't want it all in one PR.
=> base: add UserKeyBounds

compaction.go, data_test.go, flushable.go, flushable_test.go, ingest.go, ingest_test.go, metamorphic/ops.go, open.go, testdata/excise
This patch amends the ingest pipeline to allow for certain cases to use `flushaleIngest` in order to avoid waiting on memtable flushes when there is overlap. The current use for this is range snapshots in Cockroach where we include `RANGEDEL`. When we use this path, we also pass the `exciseSpan` down down into the flushable to then excise at flush time to still benefit from the use of excise in the ingest path.
Fixes #3335.
=> ingest,compaction: use excise when flushing flushableIngest

ingest.go, testdata/event_listener, testdata/metrics
When we were previously ingesting as a flushable, we were not incrementing the `metrics.Ingest.Count` metric.
=> ingest: fix ingestion metric for flushableIngest

metamorphic/ops.go, metamorphic/options.go
This change updates the two-instance metamorphic test to test fast external snapshotting added in #3348.
=> metamorphic: add support for external ingestions in replicateOp

internal/keyspan/filter.go, internal/keyspan/filter_test.go, internal/keyspan/testdata/truncate, internal/keyspan/truncate.go, internal/keyspan/truncate_test.go, metamorphic/build.go, scan_internal.go, sstable/reader_virtual.go, table_stats.go
We can simplify the Truncate operator, as we will never truncate
within the same user key. It now only takes user key bounds and is
much easier to reason about.
We also reimplement it so that we can simplify Filter.
The `FilterFunc` contract is not adequately spelled out; the code
makes certain unverified assumptions about how the bounds can be
changed.
Now that Truncate is a separate iterator, we no longer need Filter to
allow for changing bounds. We simplify `FilterFunc` to just return the
list of keys that are retained. We no longer need the extra
comparisons in `SeekGE/SeekLT`.
=> keyspan: simplify Truncate, Filter

compaction.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, metamorphic/options.go, metamorphic/parser.go
Previously, we disabled these features in the main metamorphic test to try to tease out issues elsewhere. However, seeing as these features are being turned on in 24.1 and have been stable for a while, we should turn it on in the main metamorphic test.
This change also implements the bulk of #3432 (i.e. the case where we can flushable-ingest an excise) but leaves it off as it's failing at the moment.
=> metamorphic: re-enable ingest split and ingestAndExcise in TestMeta

compaction.go, metamorphic/config.go, metamorphic/generator.go, metamorphic/key_manager.go, metamorphic/ops.go, testdata/excise
Previously, we'd repeatedly call Excise() if we had multiple files to ingest, and we'd mutate the ingestSplitFile param. This change fixes that.
Also update the metamorphic test to resume testing IngestAndExcise with sstContainsExciseTombstone=true.
=> db: flushable ingest excise fixes

objstorage/objstorageprovider/remote.go
We currently call `GetExternalObjects` under the provider lock, which is correct. However, we return the slice directly and then use it outside the lock; this slice is part of the map and is modified in place when an object is removed (the `DeleteFunc` call in `removeExternalObject`).
The fix is to clone the slice. Note that the common path here is an empty slice (backing is not reused).
Fixes #3439
=> objstorageprovider: fix race in `GetExternalObjects`

ingest.go
The code that creates new files during excise wasn't copying the synthetic prefix and suffix.
Fixes #3447.
=> db: copy synthetic prefix/suffix when excising

metamorphic/options.go
ZSTD compression is broken on the 23.2 release branch.
Close #3434.
=> crl-release-23.2: metamorphic: disable compression metamorphism

sstable/data_test.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/testdata/virtual_reader, sstable/testdata/virtual_reader_iter, sstable/testdata/virtual_reader_props
Consider the following iterator operations: SeekLT, Prev, Prev
(returns nil), Next.
For a top-level or regular index block, it is possible that
`skipBackward` moves beyond the last index block that intersects the
vtable.  Then, when we do Next, we move back to that block and return
the smallest key inside that block, but this is incorrect if the lower
bound is inside this block.
In normal circumstances, `skipBackward` can't move beyond the last
index block; but it is possible when range key masking is in use: on
the filter causes the index block that intersects the vtable to be
skipped. Then the `rangeKeyMasking` filter is updated, and on the Next
call, the block is no longer skipped.
Note that this can't happen in the other direction - this is because
the index key is an end bound for …
=> sstable: fix two level iterator bug with virtual tables

Makefile
Update the stress-crossversion Makefile target to drop 22.1 as the starting version and add 23.2 as the penultimate version.
=> Makefile: update stress-crossversion to include 23.2 and not 22.1

metamorphic/meta.go, metamorphic/options.go
Print 10 decimal digits of `ioLatencyProbability` when stringifying
the options and make sure that it's at least that value when
generating a random probability.
Fixes #3421.
=> metamorphic: fix TestOptionsRoundtrip flake

internal/metamorphic/metaflags/meta_flags.go, metamorphic/meta.go, metamorphic/test.go
Add a per-op timeout. The default value is a very conservative 5
minutes so we don't cause flakiness in stress/race builds. It can be
changed with `--op-timeout`.
This should help detect hung operations under stress, which I believe
would otherwise keep running.
=> metamorphic: add per-op timeout

compaction.go, ingest.go, ingest_test.go, testdata/ingest_external
Previously, if we had an ingestion file that had an inclusive upper bound, and an existing file with a loose lower bound, we'd correctly see no data overlap on that existing file and suggest an ingest-split. However, if the upper bound of the incoming sstable equals the loose lower bound in user keys, the excise() method would be a no-op as it would expect the upper bound of the incoming sstable to be exclusive.
This change updates db.excise() to take in UserKeyBounds with info on whether the bound is exclusive or inclusive. For inclusive bounds, we have additional guards to ensure we don't have data overlap at the upper bound, as this would only happen in the ingest-split case.
Fixes #3456.
=> ingest: fix ingest-split with loose bounds on split candidate

go.mod, go.sum
This is the version used by cockroachdb/cockroach.
=> go.mod: update github.com/klauspost/compress to v1.16.7

wal/failover_manager.go, wal/failover_manager_test.go, wal/testdata/manager_failover
When initializing the WAL failover manager, synchronously verify that we can write to the secondary directory by writing some human-readable metadata about the Pebble instance using it as a secondary.
Informs #3230.
=> wal: synchronously verify secondary is writable

compaction.go, sstable/copier.go
We were ignoring the synthetic suffix when using `CopySpan`. This can
cause it to miss keys or generate the "empty span" error.
We handle the synthetic suffix by using suffix-free keys, extending
the bounds as necessary.
Fixes #3459
=> sstable: handle synthetic suffix when using CopySpan

compaction.go
This trivial commit just adds a `download` label to the compaction `Reason`, which shows up in logs.
=> db: label download compactions logs

metamorphic/history.go, metamorphic/history_test.go
Example:
```
// 09:21:33.077 INFO: [JOB 1] MANIFEST created 000209
// 09:21:33.077 INFO: [JOB 1] WAL created 000208
```
=> metamorphic: add timestamps to logs

batch.go, ingest.go, internal/base/error.go, internal/keyspan/interleaving_iter.go, internal/keyspan/truncate.go, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/remote.go, objstorage/objstorageprovider/remote_backing.go, objstorage/objstorageprovider/remoteobjcat/catalog.go, objstorage/objstorageprovider/remoteobjcat/catalog_test.go, objstorage/objstorageprovider/remoteobjcat/version_edit.go, scan_internal.go, sstable/block_property.go, sstable/block_property_obsolete.go, sstable/copier.go, sstable/reader.go, version_set.go, wal/standalone_manager.go
We add a wrapper for `errors.AssertionFailedf` which panics in `invariants.Enabled` mode. This makes these errors easier to debug and less likely to be ignored.
=> base: add AssertionFailedf wrapper

ingest_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go
The L0 `LevelMetadata` is ordered by `LargestSeqNum` so using `SeekGE/SeekLT` is not valid. This addresses a TODO to verify this.
The assertion failed on some test code that is also fixed.
=> manifest: assert that we don't use Seek on L0 LevelMetadata

data_test.go, db_test.go, testdata/determinism
Add a new datadriven unit test intended to exercise potential races. The test allows a datadriven test case to run a sequence of operations, recording the sequence, and then re-run it with varying sources of nondeterminism, ensuring that test output itself is deterministic.
Motivated by cockroachdb/cockroach#121263.
=> db: add TestDeterminism

sstable/copier.go, sstable/properties.go, sstable/writer.go, testdata/ingest_external
The user properties contain the table block properties and the
presence of any such property implies that index entries have the same
properties. When we create a partial copy of an sst in `CopySpan`, we
don't calculate properties for index entries but non-existent
properties can still have meaning (for example, it means a
non-obsolete block for the obsolete property filter; and it means an
empty interval for the interval filter).
The fix is to just clear out the user properties so that the reader
knows there are no block properties collected.
Fixes #3485
=> sstable: clear user properties in CopySpan

testdata/concurrent_excise
Previously, the unblocking of a compaction was followed by an LSM printout, leading to a race where the datadriven output could or could not have reflected the output of the compaction. This change adds a manual compaction in between to flush out this race.
Fixes #3490.
=> db: deflake TestConcurrentExcise

external_iterator_test.go, level_checker.go, level_iter.go, merging_iter.go, sstable/block_property_test.go, sstable/data_test.go, sstable/reader_iter.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/testdata/block_properties, sstable/testdata/block_properties_boundlimited, table_cache.go, testdata/level_iter_boundaries, testdata/level_iter_seek, testdata/merging_iter
**db: unconditionally interleave ignorable boundaries**
The levelIter has a concept of ignorable boundary keys. When a levelIter
exhausts a file's point keys, it's possible that the same file still contains
range deletions relevant to other levels of the LSM. The levelIter will, under
some conditions, interleave the largest boundary key of the sstable into
iteration as an 'ignorable boundary key,' so that the file's range deletions
remain accessible until all other levels progress beyound the file's boundary.
When block-property filters are in use, a file's point key iterator may become
exhausted early, before the file's range deletions are irrelevant, even if the
file's largest key is not a range deletion. To work around this subtlety, the
sstable iterator previously would surface …
=> db: unconditionally interleave ignorable boundaries

iterator_test.go, sstable/block_property.go, sstable/block_property_obsolete.go, sstable/block_property_test.go, sstable/block_property_test_utils.go, sstable/suffix_rewriter.go, sstable/writer_test.go
This change cleans up the design of `SuffixReplaceableBlockCollector`: instead of having a separate optional interface, we fold this functionality in the `BlockPropertyCollector` and
`DataBlockIntervalCollector` interfaces. This makes things much easier to follow.
Note that the old design was especially problematic for `DataBlockIntervalCollector`: we were passing the encoded properties to the implementation but the encoding of intervals into properties is implemented by Pebble. This works only because the Cockroach implementation (`pebbleDataBlockMVCCTimeIntervalCollector`) does not need to look at the old properties at all.
=> sstable: clean up UpdateKeySuffixes

batch.go, batch_test.go, db.go
Closes: https://github.com/cockroachdb/pebble/issues/2780
=> Configurable initial and max retained batch sizes

metamorphic/generator.go, metamorphic/key_manager.go
We are not allowed to use a synthetic suffix if the relevant portion
of the external file has multiple keys with the same prefix. After
suffix replacement, they would become the same key.
I first added the code to check for duplicate keys in
`KeysForExternalIngest` and stressed just the generation part and it
reproduced. I then added the generator check and the panic  no longer
reproduces.
Fixes #3502
=> metamorphic: don't set synthetic suffix if there are duplicate prefixes

db.go, get_iter.go, get_iter_test.go, internal/keyspan/span.go, level_iter.go, testdata/range_del
**db: refactor Reader.Get**
This commit refactors the implementation of getIter to be a little more
understandable and avoid the unnecessary use of levelIter. Current supported
format major versions guarantee that a user key is not split across sstables
within a level. This ensures that Get (which only retrieves one individual user
key) need only consult 1 sstable per level.
This is somewhat motivated by https://github.com/cockroachdb/pebble/issues/2863. Removing getIter's dependency on levelIter
will make that refactor easier.
**db: simplify levelIter skipEmptyFileForward**
Apply a small simplification to levelIter.skipEmptyFileForward's condition for
when to interleave a synthetic boundary. Previously we needed to check whether
a file's largest point key was a range deletion to work …
=> db: refactor Reader.Get

metamorphic/generator.go, metamorphic/key_manager.go
We are not allowed to use a synthetic suffix if the relevant portion of the external file has multiple keys with the same prefix. After suffix replacement, they would become the same key.
I first added the code to check for duplicate keys in `KeysForExternalIngest` and stressed just the generation part and it reproduced. I then added the generator check and the panic  no longer reproduces.
Fixes #3502
=> crl-release-24.1: metamorphic: don't set synthetic suffix if there are duplicate prefixes

ingest.go, options.go
This commit adds in invariants-only check that the external ingestions are not empty. This is not allowed and leads to errors or correctness issues down the line.
Informs #122176
=> db: check for empty external ingestions

batch.go, batch_test.go, compaction.go, flushable.go, internal/arenaskl/flush_iterator.go, internal/arenaskl/skl.go, internal/arenaskl/skl_test.go, level_iter.go, mem_table.go, mem_table_test.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_iter.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go
Remove the bytesIterated used in flushes and compactions to incrementally update compaction.bytesIterated. It was a vestige of an attempt at pacing flushes and compactions to reduce impact on foreground traffic. That pacing logic had been inactive for years and has been removed from the code base for a while.
The only remaining use was for the flush throughput metric, but this metric did not require an incrementally-updated value, only an aggregate after the flush has completed.
=> *: remove bytesIterated

metrics.go, open.go, wal/failover_manager.go, wal/failover_manager_test.go, wal/failover_writer.go, wal/failover_writer_test.go, wal/testdata/manager_failover, wal/wal.go
FailoverWriteAndSyncLatency measures the latency of writing and syncing a set of writes that were synced together. Each sample represents the highest latency observed across the writes in the set of writes. It gives us a sense of the user-observed latency, which can be much lower than the underlying fsync latency, when WAL failover is working effectively.
Informs #122364
=> wal,db: add FailoverWriteAndSyncLatency histogram

internal/manifest/version.go
In FileMetadata.Validate, validate that the key kinds of the boundary keys match expected key kinds. This is motivated by a bug I introduced in a work-in-progress branch.
=> internal/manifest: validate bound key kinds

merging_iter.go, testdata/merging_iter
When the merging iterator finds a range deletion during a seek, it uses the tombstone to adjust the seek key of lower levels, skipping over deleted keys. Previously this code used (*keyspan.Span).Contains to ensure that the range deletion tombstone's bounds allowed the optimization. This had a couple minor unnecessary consequences:
- It performed key comparisons against both bounds, despite keyspan.Seek[GE|LE] has already ensured one of the bounds is met.
- It didn't handle the SeekLT(k) case where k is also the end bound of the range deletion. In this case, the optimization is still valid because SeekLT(k) is exclusive with respect to k.
=> db: tweak merging iterator range deletion cascading logic

tool/db.go, tool/testdata/db_excise, tool/tool.go
This commit adds an option to pass down a function for a custom method
to specify the excise span. On the CRDB side, we will add table/tenant
ID flags and when those flags are set, the function will return the
table span.
Informs [#122059](https://github.com/cockroachdb/cockroach/issues/122059)
=> tool: add custom excise span option

compaction_iter_test.go, internal/base/test_utils.go, iterator_test.go, level_iter_test.go, merging_iter_test.go, scan_internal_test.go
Move the fake iterator and the deletable sum value merger into base.
This will be useful when we move some of the compaction code into
another package.
=> base: move some test utils to base

flushable.go, ingest.go, level_checker.go, scan_internal.go, table_cache.go, table_cache_test.go, testdata/ingest
Update the remaining users of tableNewIters.TODO to use the new interface and delete the TODO method.
=> db: update newIters callers to use new interface

internal/keyspan/interleaving_iter.go, internal/keyspan/interleaving_iter_test.go, internal/keyspan/testdata/interleaving_iter, internal/keyspan/testdata/interleaving_iter_masking
**internal/keyspan: refactor interleaving iterator tests**
Refactor the interleaving iterator tests to take the masking threshold on the
iterator command. Rename 'define-rangekeys' to 'define-spans'.
**internal/keyspan: fix interleaving iter intermediary state**
Previously in InterleavingIter.prevPos when
a) moving from a point key
b) the point key was contained within a span
c) no lesser point key exists
prevPos would improperly move to posKeyspanEnd instead of posKeyspanStart. This
doesn't have any externally visible impact on the behavior of the
InterleavingIter because end boundaries are not interleaved: prevPos is called
again before returning to the user, ensuring we step to posKeyspanStart. With
cases.
=> internal/keyspan: refactor interleaving iterator tests

compaction.go, compaction_test.go, internal/base/logger.go, internal/compact/iterator.go, internal/compact/iterator_test.go, internal/compact/snapshots.go
We move the compaction iterator parameters to `IterConfig` which gives
us a natural place to include documentation and makes the calling code
cleaner.
Some cleanup of compaction code:
- cleaner validation of VersionEdits
- extract out specialized compaction code (for delete-only, move,
etc)
=> compact: move iterator arguments into a struct

internal/manifest/level_metadata_test.go, internal/manifest/testdata/level_iterator, internal/manifest/testdata/level_iterator_filtered, internal/manifest/testdata/overlaps, internal/manifest/version.go, internal/manifest/version_test.go, testdata/download_cursor
Fix some tests that have split keys which are no longer allowed. Add
`CheckOrdering` calls to check validity going forward.
This makes it easier to read the output of tests with many iterator
commands.
=> manifest: fix some tests that have split keys

compaction.go, compaction_test.go, data_test.go, testdata/compaction_transform
We remove this field which is not very useful (tests can just pass a
large in-use key range instead).
We also consult `inUseEntireRange` in `elideRangeTombstone` which
seems like an omission. We also simplify `allowZeroSeqNum()`.
=> db: remove compaction.disableSpanElision

internal/keyspan/interleaving_iter.go, internal/keyspan/interleaving_iter_test.go, internal/keyspan/testdata/interleaving_iter
Adapt the InterleavingIter to support a mode that interleaves span end keys.
Informs #2863.
=> internal/keyspan: support interleaving end keys 

level_iter.go, merging_iter.go
The mergingIter logic for switching the direction of the heap has special handling for the "synthetic iterator bounds" that the levelIter interleaves when it encounters the largest key in a table. These conditionals were more complicated and involved than they needed to be. The isSyntheticIterBoundsKey flag implies that the current key is an exclusive sentinel and that there's a bound in the previously-active direction of iteration.
=> db: simplify mergingIter direction switching

ingest.go, options.go
This commit adds a check that the external ingestions are not empty.
This is not allowed and leads to errors or correctness issues down the
line.
We don't want to open all remote ssts files in production, so the
check only happens in invariants mode or if a new
CheckExternalIngestions option is set. This will be set by crdb in
tests.
=> crl-release-24.1: db: check for empty external ingestions

level_iter.go, testdata/level_iter
Previously the levelIter did not support changing directions from an exhausted iterator position. If a levelIter returned nil, the caller was responsible for repositioning the iterator in the other direction using a seek.
=> db: support changing directions of exhausted levelIter

.github/CODEOWNERS
Add a CODEOWNERS file that sets the storage team as a reviewer.
=> github: automatically add storage team to PRs

compaction.go, compaction_test.go, db.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/manifest_test.go, internal/manifest/version.go, internal/manifest/version_test.go, testdata/compaction_elide_tombstone, testdata/compaction_inuse_key_ranges
This is a mechanical change to remove `UserKeyRanges` and switch to
`UserKeyBounds` for in-use key ranges. They are still always
inclusive.
Use the `UserKeyBounds` format, which shows whether the end bound is
exclusive or inclusive.
We now take into account the exclusivity of the largest key, with more
accurate ("tighter") resulting ranges.
=> manifest: more accurate in-use key ranges

internal/itertest/datadriven.go, level_iter_test.go, merging_iter_test.go, testdata/level_iter_boundaries, testdata/level_iter_seek
The unit tests TestMergingIterCornerCases, TestLevelIterBoundaries and TestLevelIterSeek all fake tableNewIters implementations, but previously these implementations ignored the requested iterator types, always constructing both point and range deletion iterators.
Additionally, the output of TestLevelIterBoundaries is adjusted to make it clearer when the levelIter has actually opened a file.
=> db: clean up levelIter, mergingIter unit tests

compaction.go, compaction_test.go, internal/compact/iterator.go, internal/compact/iterator_test.go, internal/compact/testdata/iter_range_keys
We move the elision of range keys from a transformer in the merging
iterator to the compaction iterator. This is consistent with how we
are handling tombstones, and will make it easier to push down all the
elision logic into the iterator.
=> compaction: move elision of range keys to the iterator

compaction.go, compaction_test.go, internal/compact/iterator.go, internal/compact/iterator_test.go, internal/compact/testdata/tombstone_elider, internal/compact/testdata/tombstone_elision, internal/compact/testdata/tombstone_elision_setup, internal/compact/tombstone_elision.go, internal/compact/tombstone_elision_test.go, internal/manifest/version.go, internal/manifest/version_test.go, testdata/manual_compaction_set_with_del_sstable_Pebblev4
We move the logic that sets up the in-use key ranges and then uses
those to determine which tombstones need to be elided.
We store the in-use key ranges in a new type `TombstoneElision`. The
`TombstoneElision` is passed to the compaction iterator, replacing the
`ElideTombstone` and `ElideRangeTombstone` callbacks.
New point and range elider types are used to check against the in-use
ranges. They assume the "queries" are ordered.
The minor test result changes are due to the new code being better at
taking into account exclusive boundaries.
=> compaction: move tombstone elision logic to internal/compact

compaction.go, sstable/writer.go
This code removes the `PreviousPointKeyOpt` and replaces it with a simple method on the writer.
=> sstable: remove PreviousPointKeyOpt

db.go, level_checker.go, level_iter.go, merging_iter.go, merging_iter_test.go, scan_internal.go, testdata/level_iter_boundaries, testdata/level_iter_seek, testdata/merging_iter
The merging iterator and the level iterator are more tightly coupled than desired. Most of this coupling is a consequence of range deletions. The merging iterator is responsible for applying range deletions across levels and requires that the level iterator not progress to a new file until the file's range deletions are no longer relevant to other levels. It does this by interleaving "synthetic" keys. When these keys reach the top of the heap, it signals that all other levels have progressed to a point where the current file's range deletions are no longer relevant.
Previously, knowledge of which keys were interleaved "synthetic" keys was propagated indirectly—outside the internal iterator interface—through a pointer to a levelIterBoundaryContext struct with boolean fields. This commit …
=> db: rework mergingIter and levelIter synthetic keys

internal/base/options.go, internal/cache/value.go, internal/cache/value_cgo.go, internal/cache/value_normal.go, options.go, sstable/options.go, sstable/testdata/flush_heuristics, sstable/writer.go, sstable/writer_test.go
Currently, the sstable writer contains heuristics to flush sstable blocks once the size reaches a specified threshold. In CRDB this is defined as 32KiB. However, when these blocks are loaded into memory additional metadata is allocated sometimes exceeding the 32KiB threshold. Since CRDB uses jemalloc, these allocations use a 40KiB size class which leads to significant internal fragmentation. In addition, since the system is unaware of these size classes we cannot design heuristics that prioritize reducing memory fragmentation. Reducing internal fragmentation can help reduce CRDB's memory footprint. This commit decrements the target block size to prevent internal fragmentation for small key-value pairs and adds support for optionally specifying size classes to enable a new set of …
=> sstable: reduce block cache fragmentation

metamorphic/history.go, metamorphic/meta.go
`Fatalf` was storing an error but we were never checking it. It will now fail the execution.
=> meta: fail execution if Fatalf was used

sstable/value_block.go
We now panic in invariants mode. This might help debug #3556.
=> sstable: change an out-of-bounds error into an assertion

internal/batchskl/iterator.go, testdata/internal_iter_bounds
Since 5bcf51bf44 the batchskl.Iterator has cached nodes corresponding to lower or upper bounds. These cached nodes were not cleared in calls to SetBounds, allowing incorrect results when the bounds changed.
Close #3564.
=> batchskl: clear cached bound nodes in SetBounds

compaction.go, db.go, ingest.go, metrics_test.go, testdata/event_listener, testdata/metrics
**db: update flushableEntry.logSize during flushable ingest**
Performing a flushable ingestion causes two WAL rotations: one to switch away
from the WAL corresponding to the mutable memtable to a temporary, intermediary
WAL for the ingestion, and one to switch to the next mutable memtable's WAL.
Both these WAL rotations ignored the previous log size, omitting the
propagation to the corresponding flushable.
This commit fixes this bug, propagating the logSize appropriately.
**db: ensure Metrics.WAL.BytesWritten is nondecreasing**
The Metrics.WAL.BytesWritten metric is intended to be a monotonically
increasing counter of all bytes written to the write-ahead log. Previously, it
was possible for this metric to violate monotonicity immediately after a WAL
rotation. The d.logSize value—which …
=> db: ensure Metrics.WAL.BytesWritten is nondecreasing

compaction.go, db.go, ingest.go, metrics_test.go, testdata/event_listener, testdata/metrics
=> crl-release-24.1: db: ensure Metrics.WAL.BytesWritten is nondecreasing

batch.go, batch_test.go, db.go, wal/failover_writer.go, wal/standalone_manager.go, wal/wal.go
24.1 backport of #3565.
----
Passing in the Batch.refData func into (wal.Writer).WriteRecord forced an allocation for every committed batch. This commit defines a new wal.RefCount interface implemented by Batch to avoid the allocation.
Informs cockroachdb/cockroach#123236.
=> crl-release-24.1: db,wal: avoid Batch.refData allocation

ingest_test.go, testdata/ingest_target_level
Update the format of file metadatas provided to the TestIngestTargetLevel unit test. It now uses the manifest.ParseFileMetadataDebug, removing bespoke parsing code and allowing test cases to express ingested file bounds that are exclusive on the end boundary.
=> db: update TestIngestTargetLevel test format

objstorage/test_utils.go, sstable/data_test.go, sstable/suffix_rewriter_test.go, sstable/writer_test.go, table_cache_test.go
Add an in-memory implementation of Writable/Readable and replace
existing test implementations.
=> objstorage: add MemObj for testing

compaction.go, compaction_test.go, internal/compact/iterator.go, internal/compact/iterator_test.go
During compaction, we obtain rangedel and rangekey spans by querying
the interleaving iterators that are used as input to `compact.Iter`.
To reduce this tight coupling, we move the interleaving iterators to
`compact.Iter`. We now pass the point/rangedel/rangekey iterators
separately and we use new `compact.Iter` methods to obtain the
relevant spans.
=> compact: move interleaving iterators to compact.Iter

internal/compact/splitting.go, internal/compact/testdata/output_splitter
Make sure we never split on the first key. In this case we were
returning SplitKey equal to the first key, which is not allowed.
Note that the newly added check is not in a hot path.
This doesn't cause visible problems currently because the compaction
code initializes the output writer lazily, and a nil `Writer`
has an estimated size of 0. It becomes a problem if we initialize the
writer upfront, since an empty but initialized writer has a few bytes
of estimated size.
=> compact: minor fix to the splitter

internal/lint/lint_test.go
**internal/lint: update staticcheck**
Update staticcheck to 2023.1.7.
---
**internal/lint: update crlfmt**
Update to cockroachdb/crlfmt@461e8663b4b4887b1c6a6c9deaeeb775109a635f.
=> internal/lint: update lint deps

compaction.go, internal/compact/splitting.go, internal/compact/splitting_test.go, internal/compact/testdata/output_splitter, testdata/manual_compaction_set_with_del_sstable_Pebblev4
`NewOutputSplitter` requires the `firstKey` to be at or after the
current frontier (because it relies on the frontier tripping the
boundaries before the corresponding `ShouldSplitBefore` call).
In practice, this requirement is bothersome: if there are range del or
range key spans, the current table would start at the previous split
key, which can be behind the frontier. The current code uses the next
point key but this is not ideal - we may want to split a span multiple
times in-between two very far-away points.
This change relaxes this requirement by manually checking the
boundaries the first time `ShouldSplitBefore` is called. The
compaction code is improved to provide the correct first key.
=> compact: relax splitter frontier requirement

data_test.go, db_test.go, mem_table.go, testdata/determinism
Previously it was not obvious why memTable.availBytes() could reset the memtable's reserved size when memTable.writerRefs() == 1. In #3557, a code reading lead us to believe there was a race where competing writers could improperly double reserve the tail of the memtable's arena. However, in the code reading we missed that the mutable memtable always has a writerRefs()≥1, which is why a writerRefs()==1 indicates there are no concurrent applications to the memtable.
Additionally, add a unit test that exercises the race of two batches competing for the tail of the memtable arena.
Close #3557.
=> db: document memTable.writerRefs subtlety

level_checker.go, level_checker_test.go, testdata/level_checker
Recent refactors made it possible for the level checker to visit a point key twice if the point key's levelIter interleaved a boundary sentinel key. The corresponding level's simpleMergingIterItem's key and value were not updated, leaving the old point key on the heap. When the point key remained at the top of the heap, but the underlying levelIter had moved on, it was possible to access freed memory associated with the old point key's value.
Fix #3556.
Fix #3583.
=> db: fix level checker use of stale iterator value

internal/keyspan/interleaving_iter.go, internal/keyspan/testdata/interleaving_iter
Previously when the interleaving iterator interleaved a span boundary, the semantics of calling NextPrefix were undefined. Ordinarily NextPrefix guarantees that it advances to a key with a new prefix. The existing interleaving iterator implementation didn't guarantee this when positioned on a span boundary. Guaranteeing it would require otherwise unnecessary key comparisons.
In existing use cases (for range keys, which always begin and end at prefix keys), we never call NextPrefix while positioned at a span boundary. With the planned refactor of #2863, we'll begin to use the interleaving iterator to interleave range deletions which may have bounds within the keys of a prefix. This assertion will ensure we don't unintentionally rely on currently undefined behavior of calling NextPrefix on …
=> internal/keyspan: prohibit NextPrefix at span boundary

flushable.go, internal/keyspan/keyspanimpl/level_iter.go, iterator.go
This commit fixes a few issues surrounding NextPrefix and iterator errors. Previously, under some circumstances, an error propagated by the underlying iterator would not immediately be propagated up. Instead the Iterator could in some circumstances call Next or NextPrefix on an already exhausted, errored iterator, resulting in undefined behavior.
Similarly, the results of calling NextPrefix on an exhausted top-level pebble.Iterator are not defined. This commit adapts the implementation to early exit in this case. The metamorphic test may generate such operations.
Fix #3592.
=> db: fix iterator error propagation, NextPrefix violation

internal/metamorphic/meta_test.go, internal/metamorphic/metaflags/meta_flags.go, internal/metamorphic/reduce_test.go
Make the number of attempts for each probability configurable. When
the problem doesn't reproduce most of the time, we need more attempts.
=> metamorphic: make a reduce parameter configurable

metamorphic/options.go
Before the recent compaction cleanup, the output table writer was
initialized lazily, which means that until the first key was written
the estimated size was 0. So even with a tiny target size, we will get
at least one point key and any associated spans.
Now the table writer is initialized up front and the estimated size of
an empty table writer is 8. When the target file size is less than
that, we try to split the table as soon as possible (and emit just a
small piece of a span in many cases). These many tiny tables slow down
the tests a lot, to the point of timing out certain operations.
This change sets the minimum target file size in the metamorphic
tests to 12.
Fixes #3594
Fixes #3595
=> metamorphic: use 12 as the minimum target file size

iterator.go
Revert the changes to Iterator.nextPrefix in bfd3ee2. Instead, adjust Iterator.NextPrefix to error if the iterator is already an error state.  This mirrors the behavior of Iterator.Next.
Fix #3597.
=> db: adjust Iterator.NextPrefix to error if in error state

internal/keyspan/interleaving_iter.go, level_checker_test.go, level_iter.go, merging_iter.go, testdata/ingest, testdata/level_iter_boundaries, testdata/level_iter_seek, testdata/merging_iter, testdata/metrics
Previously, levelIter would sometimes interleave fake keys at file boundaries
or user-provided iteration boundaries when a file contains range deletions.
This commit reworks the levelIter to instead interleave the individual bounds
of the range deletions themselves, using an interleaving iterator. This
simplifies the levelIter. Because range deletions are now read in two places:
once for interleaving bounds and once to expose a rangeDelIter to the
mergingIter, this commit requires opening a file's range deletion iterator
twice. This is an intermediary state until https://github.com/cockroachdb/pebble/issues/2863 is completed when the
mergingIter will consult the levelIter's interleaving iterator to determine
which range deletions overlap the current iterator position.
Informs …
=> db: interleave range deletion boundaries in levelIter 

metrics.go, metrics_test.go, replay/replay.go, replay/replay_test.go, testdata/event_listener, testdata/ingest, testdata/metrics, tool/testdata/db_lsm, version_set.go
Currently copy compactions don't count towards the total number of
compactions, even though the bytes they write do count towards the
total bytes written by compactions.
This change fixes this and adds a copy compaction metric.
=> metrics: count copy compactions

compaction.go, ingest.go, metamorphic/build.go, metamorphic/ops.go, options.go, sstable/copier.go, testdata/ingest_external
We now tolerate empty external ingestions.
When we encounter an empty table in a download compaction, we just
delete the table.
The iterator correctness issues that occurred before seem to no longer
apply, very likely thanks to the recent refactoring and cleanup of the
iterator stack (I ran the meta test for ~5hrs and saw no failures).
Fixes #3408
=> db: tolerate empty external ingestions

compaction.go, db.go, ingest.go, metrics_test.go, testdata/event_listener, testdata/metrics
=> crl-release-23.2: db: ensure Metrics.WAL.BytesWritten is nondecreasing

data_test.go, internal/base/iterator.go, level_iter.go, testdata/iter_histories/prefix_iteration
During prefix iteration mode, avoid stepping the levelIter beyond the current iteration prefix. This fixes a bug whereby a levelIter.Next may position a levelIter to a file beyond the iteration prefix and a subsequent SeekPrefixGE to a later key with TrySeekUsingNext would fail to observe keys in the skipped file.
Fix #3610.
=> db: avoid stepping beyond iteration prefix in levelIter

objstorage/objstorageprovider/readahead.go, objstorage/objstorageprovider/readahead_test.go, objstorage/objstorageprovider/testdata/readahead
- The limit was not being updated in certain cases, which delayed when readahead would occur. This is fixed, and new test case exercises this.
- The code in recordCacheHit is almost identical to the one in maybeReadahead and the main comprehension challenge of the code is the various predicates (and their code comments with examples), which are repeated (without the examples). These are now merged into a single helper method.
- A small side-effect of the previous change is that numReads is incremented on a cache hit when we are already above the threshold. This has no actual effect on when readahead will happen. And arguably, this new behavior is more principled.
- One of the test cases had a missing - and was not being exercised, and resulting in an incorrect error in a later test case. …
=> objstorageprovider: small readahead improvements

db.go, ingest.go, open.go, open_test.go
**db: move log bytes-in to an atomic**
Move the log bytes-in metric out of the protection of db.mu and into an atomic.
**db: avoid acquiring DB.mu during batch commit, unless rotating memtable**
Previously, DB.commitWrite would acquire the DB.mu before calling
makeRoomForWrite to ensure the current memtable had sufficient space for the
batch's contents. When DB.commitWrite is called, the caller already holds the
commit pipeline's mutex providing mutual exclusion with other committers and,
crucially, preventing the concurrent rotation of the memtable.
This commit adjusts DB.commitWrite to attempt reserving space in the current
mutable memtable before acquiring DB.mu. In the common case, if successful,
there is no need to acquire DB.mu. If unsuccessful, the committer falls back to
acuqiring …
=> db: avoid acquiring DB.mu during batch commit, unless rotating memtable

level_iter.go, testdata/ingest, testdata/level_iter_seek, testdata/metrics
Since #3596 the levelIter began opening a file's range deletion iterator twice: once to pass off to the mergingIter and once to interleave range deletion boundaries among the levelIter output to ensure we don't advance to a subsequent file until the file's range deletions are irrelevant. The implementation in #3596 naively always requested the range deletion iterator from the table cache a second time, even when it already discovered the file contained no range deletions. This caused a small regression in the Pebble YCSB benchmarks.
=> db: avoid unnecessary second opening of range deletion iter

internal/base/iterator.go, iterator.go, testdata/external_iterator, testdata/iter_histories/iter_optimizations, testdata/iter_histories/range_key_masking, testdata/iter_histories/stats_no_invariants, testdata/iterator, testdata/iterator_seek_opt, testdata/iterator_stats
This change reformats the output of iterator stats which are very hard
to read. We omit reverse counts when they are zero and remove
redundant information.
=> db: more readable iterator stats

tool/db.go, tool/testdata/db_lsm
We now show the LSM viewer URL as well in the `pebble db lsm` command.
An `--omit-url` flag can be used to omit it (e.g. if generating one on
a very large LSM is too slow).
=> tool: show LSM viewer URL in `db lsm` command

tool/manifest.go, tool/testdata/manifest_summarize
These were motivated by some disagg storage experimentation. There are summaries for compacted in bytes and files. Also, a histogram of file lifetimes when the file gets deleted. The classification of what is a compaction is slightly improved, and there is some small cleanup (unused field).
On a real manifest, in verbose mode (for the lifetime histograms) the output looks like:
_______L0_______L1_______L2_______L3_______L4_______L5_______L6_____TOTAL
2024-05-01T12:00:00Z
Ingest+Flush Bytes       16GB        .        .        .        .        .        .     16GB
Ingest+Flush Bytes/s    4.5MB/s        .        .        .        .        .        .  4.5MB/s
Compact Out Bytes       16GB        .     32GB     36GB     36GB     32GB        .    151GB
Compact Out Bytes/s    4.5MB/s        . …
=> tool: add more summaries to manifest summarize

objstorage/objstorage.go, objstorage/objstorageprovider/objiotracing/obj_io_tracing_on.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/remote_readable.go, objstorage/objstorageprovider/remote_readable_test.go, objstorage/objstorageprovider/testdata/provider/shared_readahead, objstorage/objstorageprovider/testdata/remote_read_handle, objstorage/objstorageprovider/vfs_readable.go, objstorage/test_utils.go, sstable/block_property_test.go, sstable/copier.go, sstable/reader.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/suffix_rewriter.go, sstable/table.go, sstable/table_test.go, tool/db_io_bench.go
We consider two use cases for read-before when using a
objstorageprovider.remoteReadable, given the high latency (and cost) of
each read operation:
- When a sstable.Reader is opened, it needs to read the footer, metaindex
block and meta properties block. It starts by reading the footer which is
at the end of the table and then proceeds to read the other two. Instead
of doing 3 tiny reads, we would like to do one read.
- When a single-level or two-level iterator is opened, it reads the
(top-level) index block first. When the iterator is used, it will
typically follow this by reading the filter block (since SeeKPrefixGE is
common in CockroachDB). For a two-level iterator it will also read the
lower-level index blocks which are after the filter block and before the
top-level index block. It …
=> objstorage,sstable: add read-before for reader creation and iter index/filter blocks

compaction.go, internal/keyspan/keyspanimpl/level_iter_test.go, internal/keyspan/keyspanimpl/merging_iter.go, internal/keyspan/keyspanimpl/merging_iter_test.go, internal/rangekeystack/user_iterator.go, internal/rangekeystack/user_iterator_test.go, scan_internal.go, table_stats.go
Adapt keyspanimpl.MergingIter to take a *base.Comparer and use its equals Equal method when appropriate.
=> keyspanimpl: use base.Equal in MergingIter

internal/base/comparer.go, iterator.go, iterator_test.go, level_iter.go, merging_iter.go, testdata/iter_histories/prefix_iteration, testdata/iterator_seek_opt, testdata/level_iter, testdata/merging_iter
Don't load arbitrarily later files during levelIter.SeekPrefixGE. This avoids unnecessary IO and CPU overhead.
Close #3575.
=> db: avoid loading later files for a level in SeekPrefixGE

compaction.go, compaction_picker.go, ingest.go, internal/manifest/level_metadata.go, internal/manifest/version.go, internal/manifest/version_edit.go
This change cleans up a few aspects of the `manifest` package:
- we move `overlaps` to a method on the `LevelSlice`
- we simplify the interface and improve the implementation of
`LevelIterator.Find()`
- we remove no-op uses of `LevelSlice.Reslice()`
=> manifest: minor cleanup

ingest.go, testdata/ingest
This commit sets the upper bound on the level iterator used when checking for overlap. This avoids unnecessarily opening a file that starts after the key range of interest.
=> crl-release-24.1: ingest: avoid unnecessary I/O when checking overlap

metamorphic/generator.go, metamorphic/key_manager.go, options.go, sstable/options.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go
Fixes https://github.com/cockroachdb/pebble/issues/3627
We had a bug in `deriveDB` and we weren't setting the right entry in
the map. This resulted in `iterSeekPrefixGE` not being able to use
known keys; in this case it falls back to returning a previously
generated random key, which is highly unlikely to match a key from an
external object ingested with prefix replacement. This caused the meta
test to completely miss a severe bug with bloom filters and prefix
replacement.
Fix the sstable iterators to strip the synthetic prefix before
checking the bloom filter.
Fix the `TestRandomizedPrefixSuffixRewriter` to check `SeekPrefixGE`
and randomly enable filters.
=> crl-release-24.1: sstable: handle synthetic prefix when checking bloom filter

compaction.go, ingest.go, ingest_test.go, overlap.go
This change separates the LSM overlap checking from
`ingestTargetLevel`, with the former now happening without holding
`DB.mu`.
We will make more improvements in this area soon, but this change
should be a significant improvement on its own.
Informs #2112
=> ingest: perform LSM overlap checks outside of DB.mu

db.go, flushable.go, ingest.go, internal/base/key_bounds.go, internal/base/key_bounds_test.go, internal/base/test_utils.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_test.go, internal/overlap/checker.go, internal/overlap/checker_test.go, internal/overlap/testdata/checker, overlap.go, testdata/event_listener, testdata/ingest_external, testdata/metrics
~This PR is only for the last commit (it is based on #3626).~
Instead of using level iterators, we directly check overlap with files
separately. This requires less machinery and there is no chance of
opening files that are outside of the bounds of interest.
We put the new code in a new `internal/overlap` package and
`overlapChecker` is now a very small wrapper which interfaces with
`overlap.Checker`.
=> overlap: rework ingest LSM overlap check code

sstable/reader.go
During a cache miss, increment the BlockBytes and BlockReadDuration iterator stats together, immediately after the read. Previously, if an error occurred, it was possible for the duration to be incremented without updating the bytes stats.
24.1 backport of #3641.
=> crl-release-24.1: sstable: increment BlockBytes and BlockReadDuration together

sstable/reader.go
During a cache miss, increment the BlockBytes and BlockReadDuration iterator stats together, immediately after the read. Previously, if an error occurred, it was possible for the duration to be incremented without updating the bytes stats.
23.2 backport of #3641.
=> crl-release-23.2: sstable: increment BlockBytes and BlockReadDuration together

go.mod, go.sum
Removing `!go1.23`, which is needed by [1].
[1] https://github.com/cockroachdb/cockroach/issues/125104
=> go.mod: update swiss

sstable/category_stats.go
Embedding here is not necessary and it causes the types to inherit
methods like `SafeFormat` which at best are incomplete.
=> sstable: don't embed fields in category stats

db_test.go, go.mod, go.sum, options.go, sstable/options.go, sstable/reader.go, testdata/ingest, testdata/metrics
Add option to use a semaphore to limit the number of block loads in
parallel.
=> sstable: add LoadBlockSema option

db_test.go, go.mod, go.sum, options.go, sstable/options.go, sstable/reader.go, testdata/event_listener, testdata/ingest, testdata/metrics
Add option to use a semaphore to limit the number of block loads in parallel.
=> crl-release-24.1: sstable: add LoadBlockSema option

internal/base/iterator.go, iterator.go, testdata/external_iterator, testdata/iter_histories/iter_optimizations, testdata/iter_histories/range_key_masking, testdata/iter_histories/stats_no_invariants, testdata/iterator, testdata/iterator_seek_opt, testdata/iterator_stats
This change reformats the output of iterator stats which are very hard to read. We omit reverse counts when they are zero and remove redundant information.
We also show the cached and not-cached block bytes instead of the total and cached.
=> crl-release-23.2: db: more readable iterator stats

internal/base/iterator.go, iterator.go, testdata/external_iterator, testdata/iter_histories/iter_optimizations, testdata/iter_histories/range_key_masking, testdata/iter_histories/stats_no_invariants, testdata/iterator, testdata/iterator_seek_opt, testdata/iterator_stats
This change reformats the output of iterator stats which are very hard to read. We omit reverse counts when they are zero and remove redundant information.
We also show the cached and not-cached block bytes instead of the total and cached.
=> crl-release-24.1: db: more readable iterator stats

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/readahead.go, objstorage/objstorageprovider/testdata/provider/local, objstorage/objstorageprovider/testdata/provider/local_readahead, objstorage/objstorageprovider/testdata/provider/shared_basic, objstorage/objstorageprovider/testdata/provider/shared_no_ref, objstorage/objstorageprovider/vfs.go, objstorage/objstorageprovider/vfs_readable.go, open.go, options.go, testdata/checkpoint, testdata/checkpoint_shared, testdata/cleaner, testdata/event_listener, vfs/logging_fs.go
Log the options passed to `Open`.
We were not initializing the readahead state when using a preallocated
handle. We add an assertion that would have failed and improve an
existing test to use the preallocated handle sometimes.
This commit adds a way to configure the read-ahead method, for both
cases of "informed readahead" (currently just compactions, but in the
future possibly backup scans as well) and "speculative readahead".
=> objstorage: fix preallocated handle initialization and add readahead configuration

internal/rangedel/rangedel.go, internal/rangekey/rangekey.go, internal/rangekey/rangekey_test.go, sstable/block_fragment_iter.go, sstable/reader.go, sstable/writer.go
The way we use `Decode` to append to an existing span is pretty
subtle. This change adds a separate `DecodeIntoSpan` which is used to
add keys to an existing span. Checks for consistency of the start/end
keys are moved here.
=> sstable: clean up TODO in fragmentBlockIter

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/readahead.go, objstorage/objstorageprovider/testdata/provider/local, objstorage/objstorageprovider/testdata/provider/local_readahead, objstorage/objstorageprovider/testdata/provider/shared_basic, objstorage/objstorageprovider/testdata/provider/shared_no_ref, objstorage/objstorageprovider/vfs.go, objstorage/objstorageprovider/vfs_readable.go, open.go, options.go, sstable/reader_iter_two_lvl.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener, vfs/logging_fs.go
Log the options passed to `Open`.
We were not initializing the readahead state when using a preallocated
handle. We add an assertion that would have failed and improve an
existing test to use the preallocated handle sometimes.
We also use a preallocated handle for the single level iterator (using
it only for the two level was an omission).
This commit adds a way to configure the read-ahead method, for both
cases of "informed readahead" (currently just compactions, but in the
future possibly backup scans as well) and "speculative readahead".
=> crl-release-23.2: objstorage: fix preallocated handle initialization and add readahead configuration

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/readahead.go, objstorage/objstorageprovider/testdata/provider/local, objstorage/objstorageprovider/testdata/provider/local_readahead, objstorage/objstorageprovider/testdata/provider/shared_basic, objstorage/objstorageprovider/testdata/provider/shared_no_ref, objstorage/objstorageprovider/vfs.go, objstorage/objstorageprovider/vfs_readable.go, open.go, options.go, sstable/reader_iter_two_lvl.go, testdata/checkpoint, testdata/checkpoint_shared, testdata/cleaner, testdata/event_listener, vfs/logging_fs.go
Log the options passed to `Open`.
We were not initializing the readahead state when using a preallocated
handle. We add an assertion that would have failed and improve an
existing test to use the preallocated handle sometimes.
We also use a preallocated handle for the single level iterator (using
it only for the two level was an omission).
This commit adds a way to configure the read-ahead method, for both
cases of "informed readahead" (currently just compactions, but in the
future possibly backup scans as well) and "speculative readahead".
=> crl-release-24.1: objstorage: fix preallocated handle initialization and add readahead configuration

cmd/pebble/db.go, cmd/pebble/main.go, cmd/pebble/mvcc.go, cmd/pebble/queue.go, cmd/pebble/replay.go, cmd/pebble/scan.go, cmd/pebble/sync.go, internal/crdbtest/crdbtest.go
Create new internal package that emulates CockroachDB's MVCC key structure for use in benchmarks that seek to faithfully represent CockroachDB workloads.
=> internal/crdbtest: new package

compaction.go, error_iter.go, flushable.go, flushable_test.go, get_iter.go, internal/keyspan/assert_iter.go, internal/keyspan/bounded.go, internal/keyspan/defragment.go, internal/keyspan/filter.go, internal/keyspan/interleaving_iter.go, internal/keyspan/iter.go, internal/keyspan/keyspanimpl/level_iter.go, internal/keyspan/keyspanimpl/level_iter_test.go, internal/keyspan/keyspanimpl/merging_iter.go, internal/keyspan/logging_iter.go, internal/keyspan/logging_iter_test.go, internal/keyspan/test_utils.go, internal/keyspan/transformer.go, internal/keyspan/truncate.go, iterator.go, keyspan_probe_test.go, level_checker.go, level_iter.go, merging_iter.go, metamorphic/build.go, metamorphic/ops.go, scan_internal_test.go, sstable/block_fragment_iter.go, sstable/reader.go, table_cache.go
None of the actual `FragmentIterator` implementations generate an
error during Close. This change removes the error return, simplifying
relevant code.
=> keyspan: remove error from FragmentIterator.Close

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go, objstorage/objstorageprovider/vfs_readable.go, open.go, options.go
We currently retrieve the readahead config when we create a `Readable`
and then we use that config for all read handles. This makes the
settings not responsive, as any tables already in the table cache will
have the `Readable` created.
We change `ReadaheadConfig` to an atomic that is loaded every time we
initialize a read handle.
=> provider: consult readahead config when initializing handle

internal/invariants/off.go, internal/invariants/on.go, internal/keyspan/iter.go, level_checker.go, level_iter.go, sstable/block_fragment_iter.go, sstable/reader.go, sstable/reader_iter.go, table_cache.go
This change addresses a TODO to fix double closing of the
`fragmentBlockIter`. We can now use a sync.Pool and we can remove the
wrapper type that used a sync pool only for range key iterators.
We add an `invariants.DoubleCloseCheck` type which checks for multiple
close calls in invariant builds. In these builds we sometimes don't
put objects back in the pool, so that this check can run.
We now always call `fragmentBlockIter.init()` (we were missing on a
minor optimization before).
=> sstable: fix double close of fragmentBlockIter

batchrepr/testdata/writer, batchrepr/writer_test.go, internal/binfmt/binfmt.go
Add new internal binfmt package for formatting binary data in a descriptive
way, suitable for datadriven tests.
----
This is motivated from the columnar block format unit tests which make use of it for pretty-printing the binary formats. I think it could make sense to pull this into the datadriven package itself eventually, but maybe we should wait. I expect we may want to iterate it on it in the short term.
=> internal/binfmt: new package

.github/workflows/ci.yaml
The windows test run is the only one that uses the `-v` flag which makes the output hard to use in the UI and likely makes the run much slower.
Adjust to not use `-v` and use `-tags invariants`.
=> github: don't use -v flag for windows test run

sstable/block_fragment_iter.go
=> ssstable: temporarily disable reuse of fragment iterators

internal/keyspan/assert_iter.go, internal/keyspan/interleaving_iter.go, internal/keyspan/iter.go, internal/keyspan/span.go, internal/keyspan/test_utils.go, internal/keyspan/truncate_test.go, internal/lint/lint_test.go, level_checker.go, scan_internal.go, sstable/block_iter.go, sstable/reader.go, sstable/test_utils.go, tool/find.go, tool/sstable.go
We were performing shallow clones of spans, which is not sufficient
when the spans come from a FragmentIterator.
This change wraps raw range del and range key iterators with
`assertIter` and `invalidatingIter` and we fix a few cases of using
stale values (especially Prefix/Value for range keys).
=> sstable: wrap raw fragment iterators with checkers, fix issues found

.gitignore, Makefile
This change adds a `gen-bazel` target which generates a `WORKSPACE`
file and runs gazelle to generate `BUILD.bazel `files. Generating
these files  allows a local clone of the repository to be used
directly when building Cockroach using the `override_repository` flag,
for example:
```
./dev build short -- --override_repository=com_github_cockroachdb_pebble=~/go/src/github.com/cockroachdb/pebble
```
The new files are added to `.gitignore` so that generating them
doesn't interfere with commits.
We also add a `clean-bazel` target that cleans up these files (useful 
when switching back to an older branch)
=> Makefile: add gen-bazel target

internal/invalidating/iter.go, internal/invariants/off.go, internal/invariants/on.go, internal/invariants/utils.go, internal/keyspan/assert_iter.go, iterator.go, merging_iter.go, sstable/block_fragment_iter.go, sstable/reader_iter_single_lvl.go, table_cache.go, table_stats.go
This commit adds `invariants.Sometimes` which returns true in
invariants builds with a given probability.
We audit all uses of `invariants.Enabled` and switch to `Sometimes` if
they involve non-trivial code path changes (like wrapping iterators).
We also make some improvements to the close checker.
Informs #3678
=> invariants: add Sometimes

.gitignore, Makefile, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go, objstorage/objstorageprovider/vfs_readable.go, open.go, options.go
Backport of #3668
This change adds a `gen-bazel` target which generates a `WORKSPACE`
file and runs gazelle to generate `BUILD.bazel `files. Generating
these files  allows a local clone of the repository to be used
directly when building Cockroach using the `override_repository` flag,
for example:
```
./dev build short -- --override_repository=com_github_cockroachdb_pebble=~/go/src/github.com/cockroachdb/pebble
```
The new files are added to `.gitignore` so that generating them
doesn't interfere with commits.
We also add a `clean-bazel` target that cleans up these files (useful
when switching back to an older branch).
We currently retrieve the readahead config when we create a `Readable`
and then we use that config for all read handles. This makes the
settings not responsive, as any …
=> crl-release-24.1: provider: consult readahead config when initializing handle

.gitignore, Makefile, objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go, objstorage/objstorageprovider/vfs_readable.go, open.go, options.go
Backport of #3668
This change adds a `gen-bazel` target which generates a `WORKSPACE`
file and runs gazelle to generate `BUILD.bazel `files. Generating
these files  allows a local clone of the repository to be used
directly when building Cockroach using the `override_repository` flag,
for example:
```
./dev build short -- --override_repository=com_github_cockroachdb_pebble=~/go/src/github.com/cockroachdb/pebble
```
The new files are added to `.gitignore` so that generating them
doesn't interfere with commits.
We also add a `clean-bazel` target that cleans up these files (useful
when switching back to an older branch).
We currently retrieve the readahead config when we create a `Readable`
and then we use that config for all read handles. This makes the
settings not responsive, as any …
=> crl-release-23.2: provider: consult readahead config when initializing handle

sstable/block/block.go, sstable/block/buffer_pool.go, sstable/block/kv.go, sstable/block/kv_test.go, sstable/block_iter.go, sstable/block_test.go, sstable/block_writer.go, sstable/copier.go, sstable/layout.go, sstable/options.go, sstable/reader.go, sstable/reader_test.go, sstable/suffix_rewriter.go, sstable/table.go, sstable/table_test.go, sstable/value_block.go, sstable/value_block_test.go, sstable/write_queue.go, sstable/writer.go, sstable/writer_test.go
**sstable/block: move Checksummer, ChecksumType**
Move sstable.ChecksumType and sstable.Checksummer types into the sstable/block
package.
**sstable/block: add Trailer type**
Add a fixed-width block.Trailer type, and use it to avoid subtle usage of
blockBuf.tmp to pass encoded trailers.
**sstable/block: clean up cache.Value and BufferPool union**
Clean up the block.CacheValueOrBuf union type, renaming it to block.Value and
adding a single block.Alloc entry point for constructing values.
=> sstable/block: additional refactoring

internal.go, internal/arenaskl/node.go, internal/base/internal.go, internal/compact/iterator.go, internal/keyspan/fragmenter.go, internal/keyspan/keyspanimpl/merging_iter.go, internal/keyspan/span.go, internal/manifest/version.go, internal/rangekey/coalesce.go, iterator.go, scan_internal.go, sstable/block_iter.go, sstable/block_test.go, sstable/writer.go
This type needs to be used by Cockroach and is now exported as
`pebble.InternalKeyTrailer`.
=> base: rename Trailer to InternalKeyTrailer

db.go, level_checker.go, level_iter.go, level_iter_test.go, merging_iter.go, merging_iter_test.go, testdata/level_iter_seek
`rangeDelIterPtr` is a mechanism through which the level iter passes
a range deletion iterator to the merge iterator (which uses it to
maintain a heap of tombstones).
This change cleans up the mechanism by making it a function instead.
This makes the ownership much clearer and allows the caller to add
more logic whenever the iterator changes. The merge iterator now
maintains a generation counter to detect changes (instead of comparing
by pointer, which doesn't work when iterators are pooled).
=> db: change leveliter.rangeDelIterPtr to a function

sstable/block_iter.go, sstable/block_test.go, sstable/options.go, sstable/properties.go, sstable/properties_test.go, sstable/raw_block.go, sstable/reader.go, sstable/rowblk/rowblk_test.go, sstable/rowblk/rowblk_writer.go, sstable/suffix_rewriter.go, sstable/writer.go, sstable/writer_test.go
Move the blockWriter and rawBlockWriter types into a new sstable/rowblk package for organizing code specific to the row-oriented block format.
=> sstable/rowblk: new package

internal/crdbtest/crdbtest.go
The compaction picker compares keys to the empty key, so it must be
supported by the Compare function. We recently made this function more
strict but we have to account for the empty key case.
This was causing some nightly benchmarks to error out.
=> crdbtest: tolerate empty keys in the comparer

internal/manifest/manifest_test.go, internal/manifest/version.go, internal/manifest/version_test.go
Updating this function to better handle end-exclusive ranges. In
particular, we now merge ranges that "touch", like [a, b) and [b, c].
Informs #3673
=> manifest: minor improvement to CalculateInuseKeyRanges

sstable/data_test.go, sstable/reader_test.go, sstable/rowblk/rowblk_test.go
Use the datadriven package's MaybeScanArgs helper to scan the global sequence number, removing some test code duplication.
=> sstable: use MaybeScanArgs for global seq num

sstable/internal.go, sstable/properties.go, sstable/properties_test.go, sstable/reader.go, sstable/reader_test.go, sstable/suffix_rewriter.go, sstable/writer_test.go
Fix a few lint issues, like an unused parameter and a few ineffective nil checks.
=> sstable: fix a few lint issues

db.go
Don't include in-progress ingested flushables for Compact.Duration.
They don't contribute to the total when they complete, so we can see
non-monotonic blips in the value.
I reproduced this by keeping track of the last reported duration and
setting up a goroutine to poll the metrics frequently.
Fixes #3706
=> metrics: fix Compact.Duration metric bug

external_iterator.go, ingest.go, internal/manifest/version.go, level_checker_test.go, level_iter_test.go, merging_iter_test.go, metamorphic/build.go, replay/replay.go, sstable/block/block.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_test.go, sstable/reader_virtual.go, sstable/rowblk/rowblk_fragment_iter.go, sstable/suffix_rewriter.go, sstable/test_utils.go, sstable/writer_rangekey_test.go, sstable/writer_test.go, table_cache.go, table_stats.go, tool/find.go, tool/sstable.go
We add a separate struct for transforms passed to the fragment
iterator. This includes the option to elide keys at the same sequence
number.
We also move the underlying `block.Iter` handle initialization to the
fragment iterator constructor. It's up to the iterator to decide what
transformations to pass to that "raw" iterator. For example, prefix
and suffix synthesis will happen in the `FragmentIter` and these
options won't be passed to the `block.Iter`.
=> sstable: add FragmentIterTransforms

vfs/mem_fs.go, vfs/mem_fs_test.go
Open files in Go have only one position for both read and write. Change memFile such that it behaves the same as a file opened with the defaultFS.
=> vfs: fix memFile pos

internal/keyspan/keyspanimpl/level_iter.go, internal/manifest/level_metadata.go
This commit cleans up the `keyspanimpl.LevelIter` implementation: we
no longer need to store an error with the updated APIs that return an
error. We also remove the deprecated `Leveliterator.Current()` method.
=> keyspan: remove err field from LevelIter

data_test.go, internal/manifest/version.go, metamorphic/generator.go, sstable/block/block.go, sstable/rowblk/rowblk_fragment_iter.go, sstable/rowblk/rowblk_fragment_iter_test.go, sstable/rowblk/rowblk_iter.go, sstable/rowblk/testdata/rowblk_fragment_iter, testdata/ingest_external
We rely on the blockIter to prepend the prefix for start keys, and the
fragment iterator adjusts the end keys.
We still don't support range keys in external files because of an
outstanding issue which I will start tackling.
=> rowblk: support synthetic prefix in FragmentIter

sstable/reader_iter_single_lvl.go
When a sstable iterator's bounds move monotonically forward to an abutting keyspan, the iterator employs an optimization to use the existing iterator position. When checking whether this condition was possible, the single-level iterator previously checked !i.index.IsDataInvalidated().
This case will always be true within the context of the single-level iterator. No single-level iterator methods other than initialization routines ever load the index block.
=> sstable: simplify monotonic bounds optimization condition

batchrepr/writer_test.go, internal/aligned/aligned.go, internal/binfmt/binfmt.go, sstable/colblk/base.go, sstable/colblk/block.go, sstable/colblk/column.go, sstable/colblk/column_test.go, sstable/colblk/testdata/uints, sstable/colblk/uints.go, sstable/colblk/uints_test.go, sstable/colblk/unsafe_slice.go
Add a UintBuilder column writer for building uint{8,16,32,64} columns. The UintBuilder will use a delta encoding when possible to represent an array of values as a constant C and an array of deltas using a smaller-width uint. This is expected to reduce the size of blocks in many instances. Internal key trailers have zero sequence numbers in ingested sstables, and almost always have zero sequence numbers in L6 sstables. This will allow most data blocks in these sstables to encode either a single 8-byte constant, or an 8-byte constant and an array of 1-byte deltas if the key kinds vary.
=> colblk: add UintBuilder, DeltaEncoding

sstable/reader.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_test.go, sstable/reader_iter_two_lvl.go
We've had multiple issues with divergences between initializing the data block read handles. This PR removes the code duplication.
Add `newSingleLevelIterator` and `newTwoLevelIterator` constructors.
This commits factors out most of the `singleLevelIterator`
initialization code, so that `twoLevelIterator` can use it too.
=> sstable: factor out common iterator init code

db_test.go, error_test.go, metamorphic/meta.go, metrics_test.go, vfs/errorfs/latency.go, wal/failover_manager_test.go
Limit the amount of I/O latency injected into any individual run of the metamorphic test to improve worst-case test runtimes.
Informs #3681.
Informs #3733.
=> metamorphic: limit aggregate injected I/O latency

sstable/colblk/testdata/uints, sstable/colblk/uints.go
Columns with a constant value would improperly try to read an extra N bytes where N is the width of the logical data type.
=> colblk: fix bug in uint column debug formatting

internal/binfmt/binfmt.go, sstable/colblk/raw_bytes.go, sstable/colblk/raw_bytes_test.go, sstable/colblk/testdata/raw_bytes, sstable/colblk/uints.go, sstable/colblk/uints_test.go, sstable/colblk/unsafe_slice.go
Add a new columnar primitive for storing an array of variable-length, unordered byte slices. The new format stores an offset table to provide readers with constant-time lookup of the position of any item in the array.
=> colblk: add RawBytes, RawBytesBuilder

db_test.go, internal/base/logger.go, sstable/reader.go, sstable/table.go, sstable/table_test.go
=> sstable: trace/expensive log when sstable footer read is slow

db_test.go, internal/base/logger.go, sstable/reader.go, sstable/table.go, sstable/table_test.go
backport #3745
---
This is a manual backport of https://github.com/cockroachdb/pebble/pull/3745
Relates to #3728
=> crl-release-24.1: sstable: trace/expensive log when sstable footer read is slow

db_test.go, internal/base/logger.go, sstable/reader.go, sstable/table.go, sstable/table_test.go
backport https://github.com/cockroachdb/pebble/pull/3745
---
This is a manual backport of https://github.com/cockroachdb/pebble/pull/3745
Relates to #3728
=> crl-release-23.2: sstable: trace/expensive log when sstable footer read is slow

db_test.go, internal/base/logger.go, sstable/reader.go, sstable/table.go, sstable/table_test.go
backport https://github.com/cockroachdb/pebble/pull/3745
----
This is a manual backport of https://github.com/cockroachdb/pebble/pull/3745
Relates to #3728
=> crl-release-23.1: sstable: trace/expensive log when sstable footer read is slow

sstable/colblk/column.go, sstable/colblk/testdata/raw_bytes, sstable/colblk/testdata/uints, sstable/colblk/uints.go, sstable/colblk/uints_test.go, sstable/colblk/unsafe_slice.go
Previously, even when using a delta-encoding, the uint column encoding aligned its output to the width of the logical uint. This was necessary to read the full-width constant using a pointer cast. This commit adapts the encoding to only align to the width of the deltas, using ordinary binary.LittleEndian methods for setting and getting the constant. This get only needs to happen once, while parsing the column. This reduces the amount of alignment padding necessary when delta encoding is effective.
=> colblk: only align uint deltas

ingest.go, internal/base/internal.go, internal/keyspan/keyspanimpl/level_iter_test.go, internal/keyspan/keyspanimpl/testdata/level_iter, metamorphic/generator.go, metamorphic/ops.go, testdata/ingest_external
This change improves the data-driven LevelIter test and simplfies the
code. Instead of specifying point keys, we allow extending either
point key or range key bounds directly.
We now support range keys in external files, and we support synthetic
prefix for range keys. We don't yet support synthetic suffix.
Informs #3287
=> db: support range keys in external files

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go
We improve this test by using a strict MemFS, simulating a crash at
a random point, and checking that all objects that were synced are
accessible.
We have a race in `vfsSync`: if two goroutines Sync at the same time,
one might see the flag=false and return immediately, before the other
goroutine actually runs/completes the Sync.
The fix is to store a change counter and wait for any in-progress
syncs as necessary.
Informs https://github.com/cockroachdb/cockroach/issues/124845
=> objstorage: fix race in vfsSync

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go
We improve this test by using a strict MemFS, simulating a crash at
a random point, and checking that all objects that were synced are
accessible.
We have a race in `vfsSync`: if two goroutines Sync at the same time,
one might see the flag=false and return immediately, before the other
goroutine actually runs/completes the Sync.
The fix is to store a change counter and wait for any in-progress
syncs as necessary.
Informs https://github.com/cockroachdb/cockroach/issues/124845
=> crl-release-23.2: objstorage: fix race in vfsSync

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go
We improve this test by using a strict MemFS, simulating a crash at
a random point, and checking that all objects that were synced are
accessible.
We have a race in `vfsSync`: if two goroutines Sync at the same time,
one might see the flag=false and return immediately, before the other
goroutine actually runs/completes the Sync.
The fix is to store a change counter and wait for any in-progress
syncs as necessary.
Informs https://github.com/cockroachdb/cockroach/issues/124845
=> crl-release-24.2: objstorage: fix race in vfsSync

objstorage/objstorageprovider/provider.go, objstorage/objstorageprovider/provider_test.go, objstorage/objstorageprovider/vfs.go
We improve this test by using a strict MemFS, simulating a crash at
a random point, and checking that all objects that were synced are
accessible.
We have a race in `vfsSync`: if two goroutines Sync at the same time,
one might see the flag=false and return immediately, before the other
goroutine actually runs/completes the Sync.
The fix is to store a change counter and wait for any in-progress
syncs as necessary.
Informs https://github.com/cockroachdb/cockroach/issues/124845
=> crl-release-24.1: objstorage: fix race in vfsSync

db_test.go, sstable/reader.go, sstable/table.go
Example message:
```
reading block for 000101 of 421 bytes took 166ns (sstable/reader.go:1003 -> sstable/reader.go:602)
```
=> sstable: improve slow block read log

go.mod
=> go.mod: require Go 1.22+

db_test.go, sstable/reader.go, sstable/table.go
=> crl-release-23.1: sstable: improve slow block read log

db_test.go, internal/base/logger.go, sstable/reader.go, sstable/table.go, sstable/table_test.go
=> crl-release-24.2: sstable: improve slow block read log

db_test.go, sstable/reader.go, sstable/table.go
=> crl-release-24.1: sstable: improve slow block read log

db_test.go, sstable/reader.go, sstable/table.go
=> crl-release-23.2: sstable: improve slow block read log

vfs/errorfs/latency.go
Previously, we didn't obey the limit that was passed into errorfs.RandomLatency due to a bug. This change fixes it.
Fixes #3748.
Fixes #3757.
=> vfs: fix capping of latency in errorfs

ingest_test.go, iterator_test.go, level_iter_test.go, metamorphic/build.go, metamorphic/ops.go, scan_internal_test.go, sstable/block_property.go, sstable/block_property_obsolete.go, sstable/block_property_test.go, sstable/block_property_test_utils.go, sstable/data_test.go, sstable/internal.go, sstable/suffix_rewriter.go, sstable/suffix_rewriter_test.go, sstable/testdata/block_properties, sstable/testdata/virtual_reader_iter, sstable/testdata/virtual_reader_props, sstable/testdata/writer, sstable/testdata/writer_v3, sstable/writer.go, sstable/writer_test.go, table_stats_test.go, testdata/ingest_target_level
This change makes the following improvements:
- we now pass range key spans through a separate `AddRangeKeys` API.
This is cleaner and avoids an unnecessary decode step on a span we
just encoded.  The Writer no longer has a public `AddRangeKey`
method - `EncodeSpan` is used instead.
- we simplify the interface for block interval collectors: we now
have an interface to map point keys and range key spans to
intervals, plus an optional interface to apply a synthetic suffix.
This greatly simplifies the implementation on the CRDB side (and
allows it to be stateless).
=> sstable: improve the property collector interface

.github/workflows/ci.yaml
Backport of #2409 to 23.1.
---
Use the latest available runner image for macOS.
=> crl-release-23.1: ci: bump macOS version to 12

compaction_picker.go, compaction_test.go
Removes the unused `levelMaxBytes` parameter from `pickAutoLPositive`.
=> compact: remove unused parameter in pickAutoLPositive

sstable/colblk/bitmap.go, sstable/colblk/bitmap_test.go, sstable/colblk/block.go, sstable/colblk/block_test.go, sstable/colblk/column.go, sstable/colblk/prefix_bytes.go, sstable/colblk/prefix_bytes_test.go, sstable/colblk/raw_bytes.go, sstable/colblk/raw_bytes_test.go, sstable/colblk/unsafe_slice.go
**colblk: make decoder function signatures consistent**
Unify the various functions that decode data structures from a columnar block
so that they all have consistent function signatures, and define a generic
DecodeFunc that captures this consistency. In future work, the DecodeFunc will
be used to aid in composing decoders.
**colblk: implement a common interface across column data accessors**
Introduce a new generic `Array[T]` type that allows indexed access to data and
implement it across the various accessors.
**colblk: randomize BundleSizes in block writer randomized test**
Randomize the BundleSize used for PrefixBytes columns in the
TestBlockWriterRandomized test.
**colblk: add facility for cloning an Array to a []T**
Add a `Clone[T](Array[T], int)` func that clones an array of n …
=> colblk: impose consistent interfaces

external_iterator.go, ingest.go, level_checker_test.go, level_iter_test.go, merging_iter_test.go, metamorphic/build.go, replay/replay.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_test.go, sstable/reader_virtual.go, sstable/suffix_rewriter.go, sstable/test_utils.go, sstable/writer_rangekey_test.go, sstable/writer_test.go, table_cache.go, table_stats.go, tool/find.go, tool/sstable.go
This context covers the read of the range del or range key block.
Informs #3728
=> sstable: plumb context to range iterator constructors

internal/base/comparer.go, open.go
The new block format assumes that prefixes are ordered lexicographically. We now require the `Compare` function to adhere to this assumption. This is already the case with our test comparators and the CRDB comparator.
We add a `Comparer` wrapper that verifies this assumption, and we use this in a low percentage of `invariant` test runs.
=> base: make Compare more restrictive

iterator_test.go
BenchmarkQueueWorkload benchmarks a workload consisting of multiple queues that are all being processed at the same time. Processing a queue entails either appending to the end of the queue (a `Set` operation) or deleting from the start of the queue (a `Delete` operation). The goal is to detect cases where we see a large buildup of point tombstones at the beginning of each queue, which leads to the slowdown of `SeekGE(<start of queue>)`. To that end, the test progresses through a series of steps that each 1) process the queues a certain number of times and then 2) benchmark both the queue processing throughput and `SeekGE` performance.
See https://github.com/facebook/rocksdb/wiki/Implement-Queue-Service-Using-RocksDB for more context.
=> db: Add BenchmarkQueueWorkload

compaction.go, db_test.go, error_iter.go, flushable.go, internal/keyspan/assert_iter.go, internal/keyspan/bounded.go, internal/keyspan/defragment.go, internal/keyspan/filter.go, internal/keyspan/interleaving_iter.go, internal/keyspan/iter.go, internal/keyspan/keyspanimpl/level_iter.go, internal/keyspan/keyspanimpl/level_iter_test.go, internal/keyspan/keyspanimpl/merging_iter.go, internal/keyspan/logging_iter.go, internal/keyspan/test_utils.go, internal/keyspan/truncate.go, keyspan_probe_test.go, open.go, range_keys.go, scan_internal.go, sstable/rowblk/rowblk_fragment_iter.go, table_cache.go, testdata/tracing
Informs #3728
Rewrite this test to use `datadriven`. This will make it much easier
to update and extend.
This change adds a `SetContext()` method to `FragmentIterator` which
updates any context stored in an iterator and its children. The
iterator context is now plumbed correctly through to the table range
key iterators.
=> keyspan: add contexts to keyspan iterators

sstable/reader_iter_single_lvl.go, sstable/reader_test.go, sstable/testdata/reader_hide_obsolete/iter
Currently, if we skipBackward in singleLevelIterator and come across a seemingly empty data block, we stop right there. This is not safe if hide obsolete points is true, as the block could have just been obsolete in its entirety. This change makes the iterator continue iterating backward until some other termination condition is exhausted.
This matches the behaviour for two-level iterators, as well as for skipForward in single-level iterators.
Fixes #3761.
=> sstable: don't skipBackward past empty blocks with hideObsolete

compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, format_major_version.go, internal/manifest/annotator.go, internal/manifest/annotator_test.go, internal/manifest/btree.go, internal/manifest/btree_test.go, internal/manifest/level_metadata.go, table_stats.go
Refactors `manifest.Annotator` to use generics and a simplified API. This eliminates the need to perform pointer manipulation and unsafe typecasting when defining a new Annotator. The goal of this change is to improve the `Annotator` interface while not changing any existing behavior.
`BenchmarkNumFilesAnnotator` shows roughly the same performance as master when compared
to the equivalent implementation of `orderStatistic`:
```
pkg: github.com/cockroachdb/pebble/internal/manifest
│     old     │             new              │
│   sec/op    │   sec/op     vs base         │
NumFilesAnnotator-10   1.635µ ± 1%   1.572µ ± 7%  ~ (p=0.065 n=6)
│    old     │              new              │
│    B/op    │    B/op     vs base           │
NumFilesAnnotator-10   536.0 ± 0%   536.0 ± 0%  ~ (p=1.000 …
```
=> manifest: improve Annotator interface with generics

batch.go, batch_test.go, data_test.go, iterator_histories_test.go, testdata/iter_histories/prefix_iteration
Every key we avoid propagating up the iterator stack avoids a key comparison
during initialization of the merging iterator heap.
Informs #3794.
=> db: strictly enforce prefix in [flushable]BatchIter.SeekPrefixGE

data_test.go, external_iterator.go, flushable.go, ingest_test.go, internal/manifest/level.go, internal/manifest/level_test.go, iterator.go, level_iter_test.go, merging_iter_test.go, sstable/block_property_test.go, sstable/random_test.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_test.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/flushable_ingest
=> db: don't load large filter blocks for flushable ingests

go.mod, go.sum
Picks up a couple commits from upstream. One material change, https://github.com/golang/snappy/commit/fa5810519dcbfaa60974183cbe11c6c0d050a23d.
=> deps: update snappy to 43d5d4c

ingest_test.go
We don't reset `closed` which can lead to the DB not being closed. Surprisingly, the finalizers did not detect this issue (except in crl-release-23.1).
=> db: fix missing close in TestOverlappingIngestedSSTs

data_test.go, external_iterator.go, flushable.go, ingest_test.go, internal/manifest/level.go, internal/manifest/level_test.go, iterator.go, level_iter_test.go, merging_iter_test.go, sstable/block_property_test.go, sstable/random_test.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/flushable_ingest
=> crl-release-24.2: db: don't load large filter blocks for flushable ingests

data_test.go, external_iterator.go, external_iterator_test.go, flushable.go, ingest_test.go, internal/manifest/level.go, internal/manifest/level_test.go, iterator.go, level_iter_test.go, merging_iter_test.go, sstable/block_property_test.go, sstable/random_test.go, sstable/reader.go, sstable/reader_common.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/flushable_ingest
=> crl-release-24.1: db: don't load large filter blocks for flushable ingests

data_test.go, external_iterator.go, external_iterator_test.go, flushable.go, ingest_test.go, internal/manifest/level.go, internal/manifest/level_test.go, iterator.go, level_iter_test.go, merging_iter_test.go, sstable/block_property_test.go, sstable/reader.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/reader_virtual.go, table_cache.go, testdata/flushable_ingest
=> crl-release-23.2: db: don't load large filter blocks for flushable ingests

data_test.go, external_iterator.go, external_iterator_test.go, flushable.go, ingest_test.go, internal/lint/lint_test.go, internal/manifest/level.go, internal/manifest/level_test.go, iterator.go, level_iter_test.go, merging_iter_test.go, objstorage/testdata/provider/local, objstorage/testdata/provider/shared_basic, sstable/block_property_test.go, sstable/reader.go, sstable/reader_test.go, table_cache.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener, testdata/flushable_ingest, vfs/logging_fs.go
=> crl-release-23.1: db: don't load large filter blocks for flushable ingests

external_iterator.go, iterator.go, iterator_test.go, level_iter.go, options.go, table_cache.go
Remove support for IterOptions.TableFilter. The earliest supported format major version (FormatFlushableIngest introduced in v23.1) guarantees that all sstables that predate the introduction of block-property filters have already been compacted.
=> db: remove IterOptions.TableFilter

sstable/data_test.go, sstable/reader.go, sstable/reader_iter.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/writer_test.go
We now store `useFilterBlock` in both the single level and the two
level iterators. When the single level iterator is part of a two-level
iterator, the "inner" `useFilterBlock` is always false.
=> sstable: clean up use-filter-block logic

sstable/raw_writer.go, sstable/writer.go
Remove the WriterOption type and associated extraOpts variadic parameter to New[Raw]Writer. There are no existing implementations of the WriterOption interface since #3736.
=> sstable: remove WriterOption

data_test.go, ingest_test.go, internal/compact/run.go, internal/compact/spans.go, internal/rangedel/rangedel.go, internal/rangekey/rangekey.go, level_checker_test.go, level_iter_test.go, merging_iter_test.go, metamorphic/build.go, metamorphic/ops.go, replay/replay.go, scan_internal_test.go, sstable/block_property_test.go, sstable/raw_writer.go, sstable/rowblk/rowblk_fragment_iter_test.go, sstable/suffix_rewriter.go, sstable/writer.go, table_stats_test.go, tool/find.go, tool/sstable.go
**internal/{rangedel,rangekey}: take Span by value**
Pass a Span rather than a pointer to a Span to rangedel.Encode and
rangekey.Encode. This avoids an unnecessary allocation in some instances.
**sstable: implement Writer.DeleteRange using RawWriter.EncodeSpan**
Refactor Writer.DeleteRange to use RawWriter.EncodeSpan instead of directly
calling the RawWriter's internal addTombstone method. This is in preparation
for multiple RawWriter implementations (for row-based vs column-based blocks).
=> sstable: implement Writer.DeleteRange using RawWriter.EncodeSpan

sstable/colblk/block.go, sstable/colblk/keyspan.go, sstable/colblk/keyspan_test.go, sstable/colblk/raw_bytes.go, sstable/colblk/testdata/keyspan_block
Add a columnar block schema for keyspans, used for range deletion and range keys.
```
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.80GHz
│    old.log    │              newer.log               │
│    sec/op     │    sec/op     vs base                │
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=10/SeekGE-24       156.20n ± 1%    73.42n ± 0%  -53.00% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=10/Next-24          49.36n ± 0%    71.46n ± 0%  +44.77% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=128/SeekGE-24      171.00n ± 0%    80.19n ± 0%  -53.11% (p=0.000 n=10)
KeyspanBlock_RangeDeletions/numSpans=1/keysPerSpan=1/keySize=128/Next-24         54.04n ± …
```
=> colblk: add keyspan block writer, reader, iterator

sstable/block/compression.go, sstable/block/compression_test.go, sstable/layout.go, sstable/raw_writer.go, sstable/suffix_rewriter.go, sstable/value_block.go, sstable/write_queue.go
This commit moves logic around finishing a block (compressing and checksumming) into the block package. The logic is refactored to use a PhysicalBlock type that distinguishes a finished block from an unfinished, trailer-less block.
=> sstable/block: refactor CompressAndChecksum

sstable/reader.go, sstable/rowblk/rowblk_rewrite.go, sstable/suffix_rewriter.go
Move the suffix-rewriting logic that's specific to row-based blocks into a
rowblk.Rewriter type. In future work, a columnar equivalent will be introduced.
=> sstable/rowblk: extract block-level suffix rewriting

internal/keyspan/span.go, internal/manifest/version.go, metamorphic/build.go, metamorphic/generator.go, metamorphic/key_manager.go, sstable/block/block.go, sstable/reader.go, sstable/reader_test.go, sstable/rowblk/rowblk_fragment_iter.go, sstable/rowblk/rowblk_fragment_iter_test.go, sstable/rowblk/testdata/rowblk_fragment_iter, table_cache.go, testdata/ingest_external
This commit adds support for synthetic suffix for external ingestions
with range keys. The synthetic suffix applies to the `RangeKeySet`
suffix.
=> sstable: support synthetic suffix in range keys

go.mod, go.sum, sstable/block/compression_test.go, sstable/block_property_test.go, sstable/data_test.go, sstable/format_test.go, sstable/properties_test.go, sstable/random_test.go, sstable/raw_writer.go, sstable/reader_iter_test.go, sstable/reader_test.go, sstable/suffix_rewriter_test.go, sstable/table_test.go, sstable/unsafe_test.go, sstable/value_block_test.go, sstable/writer.go, sstable/writer_fixture_test.go, sstable/writer_rangekey_test.go, sstable/writer_test.go
This commit adds a `leaktest` check to all sstable tests and fixes
goroutine leaks in some error paths.
=> sstable: add leaktest to sstable tests

sstable/colblk/testdata/uints, sstable/colblk/uints.go
Previously if a UintBuilder was constructed with InitWithDefault, and the column contained no non-zero elements, the UintBuilder would never construct an array to back b.array.elems. The call to unsafe.Slice would panic when it observed a non-zero element count and a nil pointer.
=> colblk: fix UintBuilder's construction of constant column with default

sstable/colblk/prefix_bytes.go, sstable/colblk/prefix_bytes_test.go, sstable/colblk/raw_bytes.go
**colblk: add PrefixBytes.AppendAt**
Add a new PrefixBytes.AppendAt method that appends the slice at the i'th index
to the provided destination slice. This commit also adjusts the
BenchmarkPrefixBytes microbenchmark to access slices sequentially.
```
goos: darwin
goarch: arm64
│ prefixbytes-old.txt │
│       sec/op        │
PrefixBytes/alphaLen=2/iteration-10            22.61n ± 0%
PrefixBytes/alphaLen=5/iteration-10            23.18n ± 2%
PrefixBytes/alphaLen=26/iteration-10           23.62n ± 0%
geomean                                        23.13n
```
**colblk: use pointer receiver for RawBytes, PrefixBytes**
```
goos: darwin
goarch: arm64
│ prefixbytes-old.txt │ …
```
=> colblk: add PrefixBytes.AppendAt,SetNextAt

internal.go
Currently, we export MakeInternalKey but not MakeTrailer. This change exports MakeTrailer so we can use it directly in https://github.com/cockroachdb/cockroach/pull/127997 .
=> db: export MakeTrailer

sstable/colblk/unsafe_slice_test.go
Add a microbenchmark for the UnsafeIntegerSlice.
```
goos: darwin
goarch: arm64
│   old.txt   │
│   sec/op    │
UnsafeIntegerSlice/uint64,delta8-10   3.651n ± 0%
UnsafeIntegerSlice/uint64,delta4-10   3.557n ± 3%
UnsafeIntegerSlice/uint64,delta2-10   3.468n ± 1%
UnsafeIntegerSlice/uint64,delta1-10   3.418n ± 2%
UnsafeIntegerSlice/uint64,delta0-10   3.397n ± 0%
UnsafeIntegerSlice/uint32,delta4-10   3.542n ± 6%
UnsafeIntegerSlice/uint32,delta2-10   3.530n ± 3%
UnsafeIntegerSlice/uint32,delta1-10   3.496n ± 4%
UnsafeIntegerSlice/uint32,delta0-10   3.448n ± 2%
UnsafeIntegerSlice/uint16,delta2-10   3.512n ± 2%
UnsafeIntegerSlice/uint16,delta1-10   3.483n ± 2%
UnsafeIntegerSlice/uint16,delta0-10   3.536n ± 3%
UnsafeIntegerSlice/uint8,delta1-10 …
```
=> colblk: add UnsafeIntegerSlice microbenchmark

sstable/colblk/base.go, sstable/colblk/prefix_bytes.go, sstable/colblk/prefix_bytes_test.go, sstable/colblk/unsafe_slice.go
Replace PrefixBytes.{AppendAt,SetNextAt} with a new PrefixBytes.{SetAt,SetNext} API that uses a PrefixBytesIter type to hold the key buffer and metadata that can be used to more cheaply perform SetNext operations. Subsequent work will also extend the API to support a SetPrev method.
```
goos: darwin
goarch: arm64
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
PrefixBytes/alphaLen=2/iteration-10    7.799n ± 4%   5.600n ± 1%  -28.20% (p=0.000 n=20)
PrefixBytes/alphaLen=5/iteration-10    7.741n ± 1%   5.590n ± 1%  -27.78% (p=0.000 n=20)
PrefixBytes/alphaLen=26/iteration-10   7.655n ± 0%   5.616n ± 1%  -26.63% (p=0.000 n=20)
geomean                                7.732n        5.602n …
```
=> colblk: add PrefixBytesIter for stateful key synthesis

sstable/block/kv.go, sstable/reader_iter_single_lvl.go, sstable/reader_test.go, sstable/rowblk/rowblk_iter.go, sstable/value_block.go, sstable/writer_test.go
Fix an allocation introduced when intializing a rowblk.Iter over a table that contains value blocks.
```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/pebble/sstable
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
IteratorScanManyVersions/format=(Pebble,v4)/cache-size=20MB/NewIter-10   681.8n ± 2%   659.0n ± 1%  -3.35% (p=0.000 n=20)
│  old.txt   │              new.txt              │
│    B/op    │    B/op     vs base               │
IteratorScanManyVersions/format=(Pebble,v4)/cache-size=20MB/NewIter-10   304.0 ± 0%   288.0 ± 0%  -5.26% (p=0.000 n=20)
│  old.txt   │              new.txt               │
│ allocs/op  │ allocs/op   vs base                │
IteratorScanManyVersions/format=(Pebble,v4)/cache-size=20MB/NewIter-10 …
```
=> sstable: fix value block closure allocation

compaction_picker.go
=> db: fix compaction bounds expansion to avoid empty key comparisons

db.go, db_test.go
Add a couple improvements to the DB.SSTables method that powers the crdb_internal.sstable_metrics builtin in Cockroach. Subsequent work up in Cockroach will adopt a custom JSON serialization to improve the ergonomics of working with the builtin
=> db: various DB.SSTables improvements

sstable/block/block.go, sstable/data_test.go, sstable/reader.go, sstable/reader_iter.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_test.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/testdata/reader_bpf/Pebblev3/iter, sstable/writer_test.go
In preparation for columnar blocks, this commit introduces type parameters to the {single,two}LevelIterator types. Parameterizing the sstable iterator ensures we pay the cost of dynamic dispatch only when entering the sstable iterator (as we do today).
In order to continue to allocate the data block iterator struct within the single-level iterator, this commit introduces two type paramters: one for the non-pointer iterator type, and one for the pointer type on which iteration methods are defined. This adds some slightly cumbersome ergonomics to data block iterator usage sites.
=> sstable: genericize sstable iterators by data block iterator

checkpoint.go, open_test.go, testdata/checkpoint, testdata/checkpoint_shared, testdata/cleaner, testdata/event_listener, testdata/mkdir_all_and_sync_parents, vfs/mem_fs.go
Previously Open with a relative path containing a single element would fail on real filesystems, because Open would attempt to open the empty path.
Fix #3509.
=> db: fix Open issue with single-item relative paths

compaction.go, objstorage/objstorage.go, sstable/copier.go, sstable/reader_virtual.go
Previously, if we had some blocks in the block cache at the time of starting a download, we would still read all blocks from object storage. This was pretty wasteful, especially for index/footer/etc blocks that are more likely to be in cache.
This change threads through the appropriate Reader through sstable.CopySpan, so that the cached blocks can be appropriately used. Data blocks are also read through the cache if they exist in the cache; if not, we fall back to the old sequence of reading and writing bytes blindly from object storage to local disk as fast as IO allows us to.
Fixes #3758.
=> sstable: use block cache / readhandle for downloads

compaction.go, compaction_test.go, data_test.go, db_test.go, event_listener_test.go, flushable_test.go, ingest.go, ingest_test.go, iterator_test.go, metamorphic/ops.go, open_test.go, range_del_test.go, replay/replay.go, scan_internal_test.go, tool/db.go, version_set_test.go
=> db: plumb context through ingest methods

internal/manifest/annotator.go, internal/manifest/annotator_test.go, internal/manifest/btree.go, internal/manifest/btree_test.go, internal/manifest/l0_sublevels.go, internal/manifest/level_metadata.go, internal/manifest/version.go
manifest: add range annotations
This change adds a "range annotation" feature to Annotators , which are computations that aggregate some value over a specific key range within a level. Range annotations use the same B-tree caching behavior as regular annotations, so queries remain fast even with thousands of tables because they avoid a sequential iteration over a level's files.
This PR only sets up range annotations without changing any existing behavior. See cockroachdb#3793 for some potential use cases.
`BenchmarkNumFilesRangeAnnotation` shows that range annotations are significantly faster than using `version.Overlaps` to aggregate over a key range:
```
pkg: github.com/cockroachdb/pebble/internal/manifest
BenchmarkNumFilesRangeAnnotation/annotator-10         	  306010	      4015 ns/op …
```
=> manifest: add range annotations

internal.go, internal/keyspan/fragmenter.go
This change exports these two methods to unblock https://github.com/cockroachdb/cockroach/pull/129018.
=> crl-release-24.1: export fragmenter.Truncate, MakeInternalKeyTrailer

internal.go, internal/keyspan/fragmenter.go
This change exports these two methods to unblock https://github.com/cockroachdb/cockroach/pull/128997.
=> crl-release-24.2: export Fragmenter.Truncate, MakeInternalKeyTrailer

sstable/colblk/prefix_bytes.go, sstable/colblk/raw_bytes.go, sstable/colblk/testdata/data_block/bundle_search, sstable/colblk/testdata/data_block/external_value, sstable/colblk/testdata/data_block/next_prefix, sstable/colblk/testdata/data_block/simple, sstable/colblk/testdata/keyspan_block, sstable/colblk/uints.go
This changes a few instances where a block is empty and we are returning 0 instead of `offset` as the next offset.
=> colblk: fix offset reset to 0 when encoding/decoding empty block

sstable/properties_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, vfs/default_linux.go, vfs/default_unix.go, vfs/default_windows.go, vfs/disk_full.go, vfs/disk_health.go, vfs/disk_health_test.go, vfs/errorfs/errorfs.go, vfs/mem_fs.go, vfs/vfs.go, vfs/vfstest/open_files.go, vfs/vfstest/vfstest.go
Define a new vfs.FileInfo interface to serve as the return value of Stat calls. Currently, this simply embeds os.FileInfo but future work will extend the interface with better ergonomics for information contained within the platform-depedent FileInfo.Sys().
=> vfs: add FileInfo, DeviceID

metamorphic/generator.go, metamorphic/key_manager.go
Applying a synthetic suffix to overlapping `RangeKeySet`s leads to a logical ambiguity - they both have the same suffix but they can have different values. In practical terms it causes metamorphic test failures because their relative sorting order is indeterminate.
Add code in the metamorphic tests to keep track of `RangeKeySet`s and prevent the use of synthetic suffix when the external object has overlapping `RangeKeySet`s.
Fixes #3833
Fixes #3824
=> metamorphic: no synthetic suffix with overlapping RangeKeySets

sstable/block/block.go, sstable/block_property_test.go, sstable/copier.go, sstable/data_test.go, sstable/filter.go, sstable/layout.go, sstable/raw_writer.go, sstable/reader.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/suffix_rewriter.go, sstable/table.go, sstable/value_block.go, sstable/write_queue.go
Move block.HandleWithProperties and the routines for encoding and decoding block handles in their variable-width format into the block package.
=> block: move block handle encoding and decoding

docs/RFCS/20240701_tombstone_density_heuristic.md
Adds an RFC for a new compaction heuristic that considers density of point tombstones.
Informs: #918
=> docs/rfc: add RFC for point tombstone density compaction heuristic

go.mod, go.sum, sstable/colblk/block_test.go, sstable/colblk/cockroach_test.go, sstable/colblk/data_block.go, sstable/colblk/prefix_bytes.go, sstable/colblk/prefix_bytes_test.go
Update crlib and use its faster implementation for finding the longest
shared prefix of two byte slices.
=> colblk: use crlib/crbytes.CommonPrefix

wal/reader.go, wal/reader_test.go, wal/testdata/reader
While stitching together physical WAL segments, the WAL reader reads each record's contents into a temporary buffer. Previously, if an error was encountered mid-copy of a record (eg, because the record was large enough to be split across multiple chunks), the buffer was not reset before attempting to read the next file's record. This corruption could prevent replay of the WAL.
This commit fixes the bug moving the buffer reset to immediately precede its use.
Informs #3865.
=> wal: fix reader buffer reuse

wal/reader.go, wal/reader_test.go, wal/testdata/reader
While stitching together physical WAL segments, the WAL reader reads each record's contents into a temporary buffer. Previously, if an error was encountered mid-copy of a record (eg, because the record was large enough to be split across multiple chunks), the buffer was not reset before attempting to read the next file's record. This corruption could prevent replay of the WAL.
This commit fixes the bug moving the buffer reset to immediately precede its use.
Informs #3865.
=> crl-release-24.2: wal: fix reader buffer reuse

wal/reader.go, wal/reader_test.go, wal/testdata/reader
While stitching together physical WAL segments, the WAL reader reads each record's contents into a temporary buffer. Previously, if an error was encountered mid-copy of a record (eg, because the record was large enough to be split across multiple chunks), the buffer was not reset before attempting to read the next file's record. This corruption could prevent replay of the WAL.
This commit fixes the bug moving the buffer reset to immediately precede its use.
Informs #3865.
=> crl-release-24.1: wal: fix reader buffer reuse

open.go, wal/reader.go, wal/testdata/reader, wal/wal.go
If an error occurs while replaying the WALs during Open, the error is annotated with the log number and the offset within the log. Previously, the offset was always zero. This also caused the queued flushables to be created with a zero logSize. This didn't matter in practice because the queued flushables would be flushed before Open returned.
This commit adds a PreviousFilesBytes total to the wal.Offset type to describe the number of bytes replayed from previous WAL segement files.
=> db: fix WAL offset in replayWAL errors

sstable/block/block.go, sstable/data_test.go, sstable/reader_iter.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/rowblk/rowblk_index_iter.go, sstable/testdata/reader_bpf/Pebblev3/iter
Add an IndexIter type that abstracts some of the details of a rowblk index block away from the sstable iterator. Future work will define a constraint and make single-level and two-level iterators generic with respect to the type of the index block, allowing the addition of a colblk implementation.
=> rowblk: add IndexIter type

sstable/colblk/cockroach_test.go, sstable/colblk/data_block.go, sstable/colblk/prefix_bytes.go, sstable/colblk/prefix_bytes_test.go
We currently store an `unsafe.Pointer` and separate length and
capacities. In many cases in the hot path we have to create a slice
using `unsafe.Slice`. However `unsafe.Slice` includes some checks that
we don't need (see [here](https://github.com/golang/go/blob/f38d42f2c4c6ad0d7cbdad5e1417cac3be2a5dcb/src/runtime/unsafe.go#L53)).
In this change we switch to storing a regular slice and converting to
an `unsafe.Pointer` using `unsafe.SliceData` (which directly accesses
the pointer field). This improves performance, even while gaining
boundary checks when appending the suffix.
```
CockroachDataBlockIter/AlphaLen=4,Shared=8,PrefixLen=32,Logical=0,value=8/Next    11.4ns ± 2%    10.6ns ± 1%  -7.32%  (p=0.008 n=5+5)
```
=> colblk: use regular slice in PrefixBytesIter

sstable/colblk/data_block.go, sstable/colblk/prefix_bytes.go, sstable/colblk/unsafe_slice.go, sstable/colblk/unsafe_slice_test.go
This PR is only for the last commit.
We add a function that returns two consecutive offsets (to cut down on
the branches and size of the inlined code). We also reorganize
`UnsafeUints.At` to check the most common cases first.
```
CockroachDataBlockIter/AlphaLen=4,Shared=8,PrefixLen=32,Logical=0,value=8/Next    11.1ns ± 0%    10.3ns ± 3%  -7.17%  (p=0.016 n=4+5)
```
=> colblk: add UnsafeOffsets.At2 and improve UnsafeUints.At

sstable/colblk/prefix_bytes.go
This PR is only for the last commit.
We currently store the shared prefix length and bundle length
separately and have to add them every time we move to a new key. We
switch to storing their sum.
Together with #3877, #3869, #3872 we get about 15-20% improvement on Next benchmarks and are now ~on par with the row iterator.
Full results on AMD64 (Ryzen 9):
https://gist.github.com/RaduBerinde/d94b28f87943d9258f950c8588cb6a98
=> colblk: store shared and bundle prefix length

sstable/data_test.go, sstable/reader_iter.go, sstable/reader_iter_single_lvl.go, sstable/reader_iter_two_lvl.go, sstable/reader_test.go, sstable/testdata/reader_bpf/Pebblev3/iter, sstable/writer_test.go
This is done in preparation for sstable iterators over colblk sstables.
=> sstable: genericize iterators over index block iterator type

compaction.go, data_test.go, ingest_test.go, internal/compact/run.go, internal/compact/spans.go, level_iter_test.go, merging_iter_test.go, metamorphic/build.go, metamorphic/ops.go, scan_internal_test.go, sstable/data_test.go, sstable/rowblk_writer.go, sstable/suffix_rewriter.go, sstable/testdata/writer, sstable/testdata/writer_v3, sstable/write_queue.go, sstable/writer.go, sstable/writer_test.go, table_cache_test.go
Convert RawWriter into an interface that's satisfied by the existing RawRowWriter type. Future work will introduce a RawColWriter that writes sstables with columnar blocks.
=> sstable: convert RawWriter into an interface

tool/testdata/wal_dump, tool/wal.go
Adjust the wal dump tool to error on unrecognized key kinds, and surface errors
encounted more prominently in the output.
Additionally, add a new `wal dump-merged` command that dumps the merged view of
a WAL that's composed of multiple physical segment files.
Informs #3865.
=> tool: fix up wal dump, add wal dump-merged

checkpoint_test.go, error_test.go, format_major_version_test.go, ingest_test.go, iterator_test.go, metamorphic/options.go, metamorphic/test.go, objstorage/objstorageprovider/provider_test.go, open_test.go, testdata/flushable_ingest, vfs/atomicfs/marker_test.go, vfs/mem_fs.go, vfs/mem_fs_test.go, vfs/testdata/memfs_crashable, wal/failover_writer_test.go, wal/reader_test.go
Currently we use `MemFS` in "strict" mode to test crash recovery in
the following way:
- at the desired crash point we call `SetIgnoreSyncs(true)`
- after we close the database, we call `ResetToSyncedState()` and
`SetIgnoreSyncs(false)` and proceed using the same filesystem.
This model is a bit fragile in the sense that both the previous
operation that we're simulating a crash of and the new operation use
the same filesystem. For example, a background operation that is
finishing up some cleanup could in principle interfere with the new
process.
We switch to a "crash clone" model, where we instead extract a
crash-consistent copy of the filesystem; further testing can proceed
on this independent copy. This allows for more usage patterns - e.g.
we can take multiple crash clones at various …
=> vfs: redesign MemFS strict mode

db.go, internal/manifest/annotator.go, open.go, table_cache.go
This change updates `db.EstimateDiskUsage` to use range annotations to
estimate the disk usage of a key range. This should improve the
performance of repeated disk usage estimates for similar or identical
key ranges.
At the Cockroach layer we use `db.EstimateDiskUsage` in a few places,
most notably when [computing MVCC span stats](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/span_stats_server.go#L217).
Informs: cockroachdb#3793
=> db: refactor disk usage estimate using range annotations

sstable/data_test.go, sstable/testdata/block_properties, sstable/testdata/rewriter, sstable/testdata/rewriter_v3, sstable/testdata/virtual_reader_iter, sstable/testdata/virtual_reader_props, sstable/testdata/writer, sstable/testdata/writer_v3
Clean up the datadriven build and build-raw commands uses by various sstable unit tests. The build command confusingly had its own fragmenters for range deletions and range keys sitting between the test instructions and the Writer being tested.
These commands are updated so that the build instructions mirror what is supplied to the writer.
=> sstable: clean up datadriven build commands

open_test.go
Add a randomized test of WAL failover and recovery of a DB from failover WAL logs.
Close #3865.
=> db: add TestWALFailoverRandomized

open.go, tool/testdata/wal_dump, tool/wal.go, wal/reader.go, wal/testdata/reader, wal/wal.go
24.1 backport of #3862 and #3864.
----
tool: fix up `wal dump`, add `wal dump-merged`
Adjust the wal dump tool to error on unrecognized key kinds, and surface errors
encountered more prominently in the output.
Additionally, add a new `wal dump-merged` command that dumps the merged view of
a WAL that's composed of multiple physical segment files.
db: fix WAL offset in replayWAL errors
If an error occurs while replaying the WALs during Open, the error is annotated
with the log number and the offset within the log. Previously, the offset was
always zero. This also caused the queued flushables to be created with a zero
logSize. This didn't matter in practice because the queued flushables would be
flushed before Open returned.
This commit adds a PreviousFilesBytes total to the wal.Offset type …
=> crl-release-24.1: backport WAL observability fixes

open.go, tool/testdata/wal_dump, tool/wal.go, wal/reader.go, wal/testdata/reader, wal/wal.go
24.2 backport of #3862 and #3864.
----
tool: fix up `wal dump`, add `wal dump-merged`
Adjust the wal dump tool to error on unrecognized key kinds, and surface errors
encounted more prominently in the output.
Additionally, add a new `wal dump-merged` command that dumps the merged view of
a WAL that's composed of multiple physical segment files.
db: fix WAL offset in replayWAL errors
If an error occurs while replaying the WALs during Open, the error is annotated
with the log number and the offset within the log. Previously, the offset was
always zero. This also caused the queued flushables to be created with a zero
logSize. This didn't matter in practice because the queued flushables would be
flushed before Open returned.
This commit adds a PreviousFilesBytes total to the wal.Offset type to …
=> crl-release-24.2: backport WAL observability fixes

.github/workflows/ci.yaml
Add CI targets to verify that Pebble builds for some MIPS platforms.
=> github: add MIPS builds to CI

internal/cache/clockpro.go, internal/cache/entry.go
This field is unused and makes the `entry` unnecessarily larger.
=> cache: remove entry.shard field
