cockroachdb/pebble

internal/record/log_writer.go, internal/record/record.go, internal/record/record_test.go
Fixes #36.
This commit fixes two bugs in the record.LogWriter and adds tests for the
LogWriter alongside the record.Writer.
The first bug is that a record of length zero were skipped over and not
written. I'm not sure if this behaviour is ever exercised in practice,
but it is exercised by the tests for Writer so fixing it makes testing
simpler.
The second bug is the cause of #36: each chunk header is 7 bytes long,
and no chunk can span block boundaries. When there is insufficient space
left in a block to write an entire record, a "starting" chunk is written
and we move onto the next block to write the rest of it. If there are
exactly seven bytes available in the block, the original Writer would
write the seven byte header despite not having any room to write any
body bytes, while the …
=> record: fix LogWriter's chunk alignment

batch.go, cmd/pebble/mvcc.go, db.go, db/comparer.go, internal/batchskl/iterator.go, internal/batchskl/skl.go, internal/batchskl/skl_test.go, open.go
The key "abbreviated key" is borrowed from Postgres and more accurately
describes the functionality.
=> *: rename InlineKey to AbbreviatedKey

cmd/pebble/mvcc.go, db/comparer.go, db/comparer_test.go
The default AbbreviatedKey implementation was failing to generate
properly ordered abbreviated keys when the length of the source key was
less than 8. Add a test which would have caught this bug.
Add a fast-path default AbbreviatedKey implementation when len(key)>=8.
```
name              old time/op  new time/op  delta
AbbreviatedKey-8  14.4ns ± 1%  11.0ns ± 1%  -23.81%  (p=0.000 n=10+10)
```
=> db: fix default AbbreviatedKey implementation

internal/arenaskl/arena.go, internal/arenaskl/arena_test.go
Based on https://github.com/andy-kimball/arenaskl/pull/4:
This change protects against large allocations causing Arena's internal
size accounting to overflow and produce incorrect results.  This
overflow could allow for invalid offsets being returned from
`Arena.alloc`, leading to slice bounds and index out of range panics
when passed to `Arena.getBytes` or `Arena.getPointer`.
Specifically, if `Arena.n` overflowed in `Arena.alloc`, which was
possible because it was a `uint32` and we allow up to `MaxUint32` size
allocations, then `Arena.alloc` could bypass the length check against
`Arena.buf`. The "padded" size would then be subtracted from the offset,
allowing the offset to underflow back around to an offset that was out
of `Arena.buf's` bounds.
=> internal/arenaskl: protect against overflow in Arena allocation

compaction_test.go, data_test.go, db.go, level_iter.go, merging_iter.go, range_del_test.go, testdata/range_del
A range tombstone's end key may extend past its containing sstable's
upper bound. In that case, the portion of the range tombstone outside
the sstable's boundaries does not necessarily cover keys in lower levels.
The iterator optimization for seeking past keys covered by a range
tombstone in lower levels should take this into account and limit its
seek to the sstable's upper bound.
The approach taken here is to maintain the sstable upper bounds in
`mergingIter` for the partitioned levels. `levelIter` holds a pointer to
the upper bound for its level and updates it when the current sstable
changes. `mergingIter` then uses this info to prevent seeking too far in
lower levels upon encountering a range tombstone.
=> Fix iterator bug when range tombstone ends after its sstable

db.go, open.go, sstable/writer.go, storage/syncing_file.go, storage/syncing_file_generic.go, storage/syncing_file_linux.go, storage/syncing_file_test.go
Encapsulate the logic to periodically sync a file as it is written to in
a new `syncingFile` object. Add support for using `sync_file_range` when
possible so that this periodic syncing can be performed asynchronously.
Use `syncingFile` for both sstable creation and WAL writing.
Fixes #69
Fixes #70
=> Add syncingFile

compaction.go, compaction_test.go, internal/rangedel/get.go, internal/rangedel/testdata/truncate, internal/rangedel/truncate.go, internal/rangedel/truncate_test.go, testdata/compaction_atomic_unit_bounds, testdata/range_del
Enforce the invariant that the boundaries of the output of a compaction
can be larger than the boundaries of the input. This fixes a problem
where a compaction can cause a range tombstone to expand to cover a
newer key at a lower level in the LSM.
Fixes #26
Closes #27
=> Prevent sstable boundaries from expanding during compaction

batch.go, batch_test.go, commit.go, commit_test.go, db.go, open.go
Noticed in passing. This was a mechanical change and makes access of the
batchStorage fields slightly more verbose, but prevents the
`batchStorage` methods from leaking into `Batch`. There is no other
effect (the `Batch` struct layout remains unchanged).
=> Do not leak batchStorage methods into Batch

db.go, open.go, sstable/writer.go, storage/preallocate_darwin.go, storage/preallocate_linux.go, storage/syncing_file.go, storage/syncing_file_linux.go, storage/syncing_file_linux_test.go, storage/syncing_file_test.go
On Linux, preallocation makes a huge difference in sync performance.
```
name                         time/op
SyncPreallocFile/size=0MB-4  503µs ± 6%
SyncPreallocFile/size=4MB-4  303µs ± 2%
SyncReuseFile-4              291µs ± 1%
```
The effect is much more mutated on Darwin, but still present:
```
name                         time/op
SyncPreallocFile/size=0MB-8  50.4µs ±14%
SyncPreallocFile/size=4MB-8  46.4µs ± 2%
SyncReuseFile-8              46.7µs ± 2%
```
Note that the `SyncReuseFile` benchmark is an attempt to measure the win from reusing WAL files. WAL file reuse is not actually implemented  yet.
See #41
=> Add support for WAL preallocation

commit.go, commit_test.go, db.go, ingest.go, open.go
Change `commitPipeline` to use a separate mutex rather than `DB.mu` for
serializing writing to the WAL. The use of `DB.mu` was a potential
performance problem because `DB.mu` is used for reads and holding it
during a log write meant that it was potentially held during disk
IO. There was also a super subtle bug here: `DB.makeRoomForWrite`
releases and then reacquires `DB.mu`. This behavior is necessary when
rotating the log, but the effect was that all of the careful ordering
guarantees in `commitePipeline` could be violated.
Fixes #44
=> Avoid holding DB.mu during log writes

compaction.go, data_test.go, db.go, ingest.go, iterator.go, open.go, read_state.go, read_state_test.go
Add a `readState` struct which holds the current version and memtable
slice. A `DB.readState` pointer is updated whenever the current version
or memtable slice changes.
```
name                    time/op
ReadState/updates=0-8   49.7ns ± 1%
ReadState/updates=10-8  89.9ns ± 2%
ReadState/updates=50-8   115ns ± 1%
```
Note that the `updates={10,50}` benchmarks are unrealistic. It is
extremely unlikely that 10% or 50% of the operations in a real workload
will be calls to `updateReadStateLocked`.
Fixes #45
=> Acquire state for reading without using DB.mu

commit_test.go, db.go, internal/record/log_writer.go, internal/record/record.go, internal/record/record_test.go, open.go, version_edit_test.go, version_set.go
The recyclable log record format associated a log file number with each
record in a file which allows a log file to be reused safely without
truncating the file. This is an important performance optimization in
itself and a prerequisite for writing the WAL using direct IO.
Changed `record.LogWriter` to always use the recyclable log record
format which in turn changes Pebble to use the recyclable format for the
WAL. `record.Writer` (used to write the `MANIFEST`) continues to use the
legacy log record format. `record.Reader` can now read either format and
will return an error when a record with a log number does not match the
supplied log number.
Took the opportunity to unexport some methods that were not being used
outside of the `internal/record` package such as `Reader.SeekRecord` and …
=> Add support for the "recyclable" log record format

batch.go, compaction.go, compaction_test.go, db.go, get_iter.go, get_iter_test.go, ingest.go, internal/arenaskl/iterator.go, internal/arenaskl/skl.go, internal/arenaskl/skl_test.go, internal/batchskl/iterator.go, internal/batchskl/skl.go, internal/batchskl/skl_test.go, iterator.go, iterator_test.go, level_iter.go, level_iter_test.go, mem_table.go, merging_iter_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/writer_test.go, table_cache.go, table_cache_test.go, testdata/level_iter
NB: this change is in anticipation of pushing lower/upper bound checks down into `sstable.Reader`.
Trim `IterOptions.{Lower,Upper}Bound` when loading a table to avoid requiring lower/upper bounds checks if all of the keys within the table pass the checks.
See #28
=> Trim {Lower,Upper}Bound for table iteration

compaction.go, compaction_iter.go, compaction_iter_test.go, compaction_test.go, iterator.go, testdata/compaction_allow_zero_seqnum, testdata/manual_flush, version.go
Zero seqnums in sstables in order to improve sstable compression and
enable an optimization to avoid a user-key comparison during forward
iteration. The seqnum for an entry can be zeroed if the key does not
exist at lower levels in the tree and if the entry is in the last
snapshot stripe. Rather than performing the check on a per-key basis, a
single check is done to see if the bounds of a compaction overlaps with
any sstables at lower-levels in the tree. This is slightly
pessimistic (it disallows zeroing of some keys when they could be
zeroed), but fast.
Forward iteration normally requires a user-key comparison to determine
if we've moved to the next user-key. We can skip this comparison if the
seqnum for an entry is 0 as that is the oldest seqnum for a particular
user-key which …
=> Zero seqnums in sstables where possible

db.go, internal/arenaskl/iterator.go, internal/arenaskl/skl.go, internal/arenaskl/skl_test.go, iterator.go, mem_table.go, sstable/block.go, sstable/reader.go
Pool allocating these iterator structures removes a significant source of allocations during short range scans, improving average latency of `pebble scan --rows=1` by ~15%.
=> Pool allocate pebble.Iterator, sstable.Iterator, and arenaskl.Iterator

sstable/reader.go
Previously we were trimming the upper-bound comparison of the
upper-bound was >= the index key. As the comments already note: The
separator (the index key) between blocks i and i+1 is a key that is >=
every key in block i and is < every key i block i+1.
The existing `TestReader*` tests caught this problem when stressed,
failing with the error:
table_test.go:376: expected 777, but found 778.
This occurred whenever the upper-bound `king` was selected, as that is
both an index key and the entry in a block.
=> Fix the trimming of the upper-bound for sstable iteration

batch.go, cmd/pebble/main.go, cmd/pebble/scan.go, cmd/pebble/sync.go, cmd/pebble/test.go, db.go, db/internal.go, mem_table.go
Log data is a batch entry that gets written to the WAL, but is not
added to the database state. RocksDB uses log data to implement 2PC. It
is also useful for performance testing the WAL in isolation from other
the other parts of the system.
Add `--disable-wal` and `--wal-only` flags to the `pebble` tool.
=> Add basic support for "log data"

version_edit.go
Replace O(n) work with O(1) work on levels which do not have any
edits. In steady state operation, an edit will only operate on 2 levels
of the LSM (which usually has 7 levels).
=> Optimize applying version edits

internal/record/record.go, internal/record/record_test.go, open.go, open_test.go
Previously, replaying of a preallocated WAL would encounter the error:
`pebble/record: block appears to be zeroed`. This occurred because the
tail of the log was all zeroes. Now we treat the zeroed records error
similar to EOF.
=> Fix replaying of the WAL when preallocation is active

compaction.go, db.go, db/event.go, db_test.go, event_listener_test.go, log_recycler.go, log_recycler_test.go, open.go, storage/storage.go
WAL recycling is an important performance optimization as it is faster
to sync a file that has already been written, than one which is being
written for the first time. This is due to the need to sync file
metadata when a file is being written for the first time. Note this is
true even if file preallocation is performed (e.g. fallocate).
Fixes #41
=> Implement WAL recycling

compaction.go, compaction_test.go, testdata/manual_compaction, testdata/range_del
We need a nil check on the output file's ranges. Without it, we may
unnecessarily extend the output file's lower-bound to the previous
output file's upper bound (the nil `UserKey` compares less than the
previous file's upper bound, regardless of what it is).
=> Fix compaction output file boundaries

Makefile
Previously they were always running the test to stress from the root
directory, which would cause tests that use testdata files to fail. The
new approach borrows the technique used in the CockroachDB Makefile and
uses `go test -exec stress`.
=> Fix the stress and stressrace targets

cmd/pebble/main.go, cmd/pebble/random.go, cmd/pebble/sync.go, cmd/pebble/ycsb.go
This PR adapts the logic from Cockroach repo's `workload kv` and
integrates it into a Pebble subcommand, `ycsb`. It can be run as
follows:
`go run ./cmd/pebble/ ycsb --wipe ./tmp --read-percent 50 --min-block-bytes 4096 --max-block-bytes 4096 --duration 3600s`
Not all of the options are included. In particular, these ones are
omitted: `--tolerate-errors`, `--max-rate`, `--max-op`, `--ramp`,
`--pprof-port`, `--histograms`, and `--zipfian`. We can add them later
if needed.
=> Add ycsb benchmark

batch.go, compaction.go, db.go, log_recycler_test.go, mem_table.go, open.go, version.go, version_edit.go, version_set.go, version_test.go
Previously, `deleteObsoleteFiles` would perform a directory listing to
find obsolete files. The directory listing is fairly expensive,
especially as the number of tables gets large. Switch to an approach
that is similar to RocksDB, where in steady state we keep track of
obsolete logs and tables as memtables are flushed and versions are
unreferenced.
Fix a bug in handling of `versionSet.logNumber`. Previously that field
was being bumped to the most recent log file number any time a flush was
performed, but we can only bump it to the most recent log file that
hasn't been flushed.
Fixes #96
=> Rework DB.deleteObsoleteFiles

compaction.go
It was a bit confusing because we were using the largest seqnum but the
smallest key kind. Explained why it's ok in a comment.
=> Comment why sstable smallest key forging is correct

db/options.go, db/options_test.go, db_test.go, event_listener_test.go, filenames.go, internal/record/record.go, internal/record/record_test.go, open_test.go, version_set.go
The MANIFEST is a log (in `internal/record` format) containing a
sequence of version edits. A version edit is created whenever a flush or
compaction occurs. The actual current version is obtained by replaying
the log at startup (the current version is also maintained in memory, of
course). In order to avoid the MANIFEST growing excessively large, it is
"rolled" whenever its size exceeds
`Options.MaxManifestFileSize` (default 128 MB). The new MANIFEST is
completely self-contained with the version entry being a snapshot of the
entire state (essentially a delta from the empty state).
Re-jiggered the way the MANIFEST is initially created which resulted in
slightly different file numbering at database creation: the first log
now gets file number 2, and the manifest file number 3.
Fixes #42
=> Add support for capping the size of the MANIFEST

open_test.go
The answer is no. We don't expect a LOCK file when using a `memFS` as
`memFS.Lock` is a no-op.
=> Remove TODO about the presence of a LOCK file

batch_test.go, compaction.go, compaction_test.go, data_test.go, db.go, db/options.go, db_test.go, event_listener_test.go, flush_test.go, ingest.go, ingest_test.go, log_recycler_test.go, open.go, open_test.go, range_del_test.go, read_state_test.go, snapshot_test.go, testdata/event_listener, version_set.go, vfs/mem_fs.go, vfs/vfs.go
Whenever an sstable is created (due to flush or compaction) or a WAL or
MANIFEST is created, we need to sync the parent directory in order to
ensure that the directory update is persisted to disk.
Set O_CLOEXEC and all of the files created and opened by Pebble, to
match RocksDB behavior.
Fixes #125
=> Sync the DB dir whenever we manipulate directory entries

compaction.go, compaction_picker.go, compaction_test.go, data_test.go, db.go, internal/datadriven/datadriven.go, internal/datadriven/datadriven_test.go, internal/datadriven/test_data_reader.go, range_del_test.go, testdata/compaction_output_level, testdata/manual_compaction, version_set.go
The implementation of dynamic-level-bytes was incomplete: we were
dynamically determining the base level and the size for each level, but the
base level wasn't being utilized to compute the compaction output level
when compacting from L0. The end result is that we'd determine the LSM only
needed 2 levels, but then compact from L0 -> L1, thus invalidating the
dyanmic-level-bytes heuristic (which stops at the first non-empty level).
Also fixed the target file size calculation to account for the dynamic base
level.
Fixes #108
=> Fix dynamic-level-bytes heuristic

internal/record/record.go, internal/record/record_test.go, open.go
Change `record.Reader.Next()` to return `ErrInvalidChunk` when a chunk
with an invalid header, length, or checksum is encountered. Treat
`ErrInvalidChunk` similarly to `ErrZeroedChunk`.
Fixes #111
=> Fix handling of invalid chunks when replaying a recycled WAL

cmd/pebble/ycsb.go
Make `--num-ops=0` really mean unlimited. Previously it was causing
`ycsb` to exit as soon as the first set of ops completed.
=> Fix behavior of `ycsb --num-ops=0`

compaction.go, data_test.go, db.go, db/options.go, db/options_test.go, event_listener_test.go, ingest.go, open.go, open_test.go, testdata/event_listener
Add `Options.WALDir` which specifies the directory to store write-ahead
logs in. This allows write-ahead logs to be stored on faster disk than
sstables. For example, write-ahead logs could be stored on
battery-backed SSD, while sstables are stored on spinning disk. Or
write-ahead logs could be stored on an Optane drive, while sstables are
stored on SSDs. If `Options.WALDir` is empty, write-ahead logs are
stored in the primary data directory.
Fixes #65
=> Support storing WALs in a separate directory

batch.go, cmd/pebble/test.go, compaction.go, db.go, event_listener_test.go, ingest.go, internal/datadriven/datadriven_test.go, internal/humanize/humanize.go, internal/record/log_writer.go, mem_table.go, metrics.go, testdata/event_listener, version_edit.go, version_set.go
Track level metrics during flushes, compactions, and ingestion. Provide a
pretty-printer for thes metrics which shows per-level num-files, size,
bytes-in, bytes-ingested, bytes-moved, bytes-read, bytes-written, and
write-amplification. Also show a total across all levels, as well as WAL
bytes in, and written.
=> Add basic level / compaction metrics

commit.go, commit_test.go, db.go, internal/record/log_writer.go, internal/record/log_writer_test.go, open.go
Replace the commitQueue implementation with one based on the
single-producer, multi-consumer queue used to implement `sync.Pool` in
go1.13. This implementation is similar to the previous one, but uses
fewer atomic operations per enqueue/dequeue and also takes care of
nil'ing out unused slots to avoid unnecessary retention of
batches. Removed the use of the cond var to signal when the queue had
space available. That approach was racy as it isn't safe to signal a
`sync.Cond` without holding a lock on the condition being examined
unless you jump through some hoops. Instead, we configure a maximum
commit concurrency which is enforced through a semaphore (implemented
via a `chan struct{}`).
Move most of the syncing logic into LogWriter. Added
`LogWriter.SyncRecord` which is similar to …
=> Rework the commitQueue and commitPipeline syncing

compaction.go, sstable/writer.go
This makes it easier to generate sstables without implementing the full
`vfs.File` interface.
Moved wrapping of `vfs.File` with `NewSyncingFile` from
`sstable.NewWriter` to its callers.
Fixes #140
=> Change sstable.NewWriter to take an io.WriteCloser

batch.go, data_test.go, db.go, db/comparer.go, db/options.go, error_iter.go, get_iter.go, internal.go, internal/arenaskl/iterator.go, internal/arenaskl/skl_test.go, internal/rangedel/iter.go, internal_test.go, iterator.go, iterator_test.go, level_iter.go, merging_iter.go, open.go, sstable/block.go, sstable/raw_block.go, sstable/reader.go, sstable/reader_test.go, sstable/testdata/prefixreader/bloom, sstable/testdata/prefixreader/iter, testdata/internal_iter_next, testdata/iterator, testdata/level_iter, testdata/level_iter_boundaries, testdata/merging_iter_seek
This is a continuation of https://github.com/petermattis/pebble/pull/35, which added support for writing prefix bloom filters.
Some things to keep note of are:
- `First()`, `Last()`, and `SeekLT()` are not supported in prefix iteration mode
- Prefix iteration mode **requires** a `Split()` function (aka `PrefixExtractor()` in RocksDB) to be passed into the reader options
- `{Lower,Upper}Bound` are ignored in prefix iteration mode
- There can be multiple calls to `SeekGE()`, each of which reset the prefix being iterated on
- The prefix is extracted on calls to `SeekGE()` from the key which is passed in, not the first key encountered
Since prefix iterators behave differently from regular iterators, the `./sstable/testdata/reader/` tests were separated into `./sstable/testdata/prefixreader/` …
=> Add support for prefix iterators

batch.go, data_test.go, db.go, error_iter.go, get_iter.go, internal.go, internal/arenaskl/iterator.go, internal/batchskl/iterator.go, internal/rangedel/iter.go, iterator.go, iterator_test.go, level_iter.go, merging_iter.go, sstable/block.go, sstable/reader.go, testdata/iterator, testdata/level_iter
Add support for dynamically setting `Lower,Upper{Bound}` after an iterator has already been created. This is useful for setting the bounds on the fly before calling `SeekGE`, `SeekPrefixGE`, `SeekLT`, `First`, and `Last`, without having to recreate the iterator.
Fixes #143.
=> Add support for dynamic bounds

internal/rangedel/fragmenter.go, sstable/block.go, sstable/block_test.go, sstable/reader.go, sstable/testdata/writer, sstable/writer.go, sstable/writer_test.go
RocksDB generates range-del blocks that contain range tombstones that are
not fragmented and sorted. Pebble generates range-del blocks containing
tombstones that are fragmented and sorted. The fragmented and sorted
range-del blocks are suitable for serving from directly, while the
unfragmented/unsorted blocks are not. We now transform RocksDB format
range-del blocks into Pebble format blocks on the fly.
The transformation is done via a hook that allows passing a block through a
function after it has been read from disk but before it is added to the
cache.
Fixes #68
Provide key stability across blockIter positioning calls
Provide stability for the keys returned from a blockIter across positioning
calls (Seek*, First, Last, Prev, Next) when the block has a restart
interval of 1. This is …
=> Convert v1 to v2 range-del blocks on the fly

batch.go, batch_test.go, testdata/flushable_batch
Fix `flushableBatchIter` by adding support for lower and upper bounds.
Fixes #148.
=> Fix lower and upper bound for flushableBatchIter

db.go, get_iter_test.go, iterator.go, testdata/iterator, testdata/snapshot
When the iterator is invalid, a call to `{Next,Prev}` needs to consider
the lower and upper bounds. Previously it was ignoring them allowing the
iterator to return keys outside of the bounds.
=> Fix Iterator.{Next,Prev} boundary cases

internal/randvar/zipf.go, internal/randvar/zipf_test.go
Ensure that creating a Zipf distribution incrementally produces the same
results as constructing the same range via the constructor.
=> Fix Zipf.IncMax

compaction.go, db.go, db_test.go, iterator.go, snapshot.go, snapshot_test.go
Return errors from operations on snapshots that have been closed.
=> Provide guard rails for various invalid operations

Makefile, vfs/syncing_file_linux.go, vfs/syncing_file_linux_test.go
Simply checking the filesystem is not sufficient to determine if
sync_file_range is supported. We need to perform a "smoke test" call to
determine if the kernel supports the call (Windows Subsystem for Linux does
not).
=> Dynamically test for sync_file_range support

batch.go, batch_test.go, mem_table.go
Export BatchReader so users can have a tool for iterating over the contents
of a batch.
=> Export BatchReader

internal/pacertoy/main.go
Simulation which models RocksDB heuristics for pacing user writes.
The "levels" of the LSM tree are initially filled to full capacity, except for the bottom-most level. This means that every flush results in an increase in compaction debt of (num_levels * size_of_sstable), where compaction debt is defined as the total sum of all the bytes at each level which are over the maximum number of bytes at that level.
We see the sawtooth-like pattern when we look at compaction debt but it may be due to an error in my modeling. If we look from `10s` below, we see that when a flush happens which then triggers a compaction, compaction debt grows very large immediately and tapers down. Because of how this pattern interacts with the RocksDB heuristics, compaction debt and the number of L0 sstables grow …
=> Add RocksDB simulation

compaction.go, error_test.go, open.go, open_test.go, version_set.go
When a MANIFEST write fails, recovery is difficult because it is unclear
what has made it to disk and what hasn't. Rather than trying to perfom
inline recovery to a good state, we fatal and rely on the standard
recovery mechanism run when a database is open. In particular, that
mechanism generates a new MANIFEST and ensures it is synced.
Fixes #153
=> Fatal on MANIFEST write errors

internal/arenaskl/node.go, vfs/syncing_file_generic.go, vfs/syncing_file_linux.go, vfs/syncing_file_linux_test.go
syscall.SyncFileRange is not defined on arm (though it is for arm64?).
Fix a warning about a comparison that is always true when ints are
32-bits.
Fixes #171
=> Disable SyncFileRange on arm

cmd/pebble/db.go, cmd/pebble/main.go, cmd/pebble/mvcc.go, cmd/pebble/rocksdb.go, cmd/pebble/rocksdb_disabled.go, cmd/pebble/scan.go, cmd/pebble/sync.go, cmd/pebble/test.go, cmd/pebble/ycsb.go
The RocksDB support utilizes cockroachdb/cockroach/pkg/storage/engine,
which is a very heavyweight dependency. To make this more palatable,
that dependency is optional and RocksDB support is only compiled in if
`-tags rocksdb` is specified.
Much of this code was written by @ajkr.
=> Add support for using RocksDB instead of Pebble

cache/clockpro.go, cache/clockpro_test.go, open.go, table_cache.go, table_cache_test.go
* Shard tableCache and cache.Cache
* Update tableCacheNode.refCount atomically.
=> Reduce concurrency bottlenecks in the table and block caches

batch.go, batch_test.go, cmd/pebble/db.go, compaction.go, db.go, db_test.go, get_iter.go, get_iter_test.go, internal/arenaskl/arena.go, internal/arenaskl/arena_test.go, internal/arenaskl/flush_iterator.go, internal/arenaskl/iterator.go, internal/arenaskl/node.go, internal/arenaskl/skl.go, internal/arenaskl/skl_test.go, internal/base/options.go, internal/base/options_test.go, level_iter.go, level_iter_test.go, mem_table.go, mem_table_test.go, open.go, sstable/reader.go, sstable/reader_test.go, table_cache.go, table_cache_test.go
Added a flush iterator which tracks the number of bytes iterated through. This allows us to see how much of the memtable has been flushed so that we can slow down flushing to match the speed of incoming writes.
This implements a portion of #7
Initially, I tried to expose an API on the iterator itself to determine the node size of the current node, something like `FlushIterator.NodeSize()`. However, the `internalIterator` interface doesn't expose this API so that wasn't an option. The compaction iterator wraps an `internalIterator` so there is no way to access the `FlushIterator.NodeSize()` API during the actual flushing. To get past this issue, I've extended the `flushable` interface. FlushIterator updates a `bytesIterated` field in the underlying skiplist, which then exposes the field …
=> Add memtable flush pacing mechanism

cache/alloc.go, cache/alloc_test.go, cache/clockpro.go, cache/clockpro_test.go, cmd/pebble/db.go, cmd/pebble/main.go, cmd/pebble/rocksdb.go, ptable/reader.go, sstable/block.go, sstable/reader.go
Add support for lightweight manual memmory management to the block cache.
Memory is still allocated using the Go runtime, yet we track blocks that
are either in the cache, or still in use by an iterator. When the final
reference to a block is released, the byte slice is added to a per-thread
list of recently freed blocks. Allocations for block memory are first
satisfied from this cache before falling back to the Go allocator.
The allocation cache groups allocation sizes into 1024-byte classes. There
is some space wastage in this setup which we could reduce with finer
granularity classes such as those used in the Go runtime.
Experimentation shows that 99% of allocation sizes for blocks cluster
within a single size class: the configured target block size. In a workload
where the working set …
=> Add lightweight manual memory management for the block cache

sstable/block.go, sstable/raw_block.go, sstable/reader.go
During reverse iteration, the cache of entries to the previous restart
point was holding a pointer into `blockIter.cachedBuf`. That buffer started
size at 0 and then increased on every entry added. If the buffer had to be
resized, existing cached entries would still point to the old buffer. The
result was not incorrect, but it used more memory than expected.
=> Fix a "memory leak" in caching entries during reverse iteration

cmd/pebble/test.go
Heap sampling is always enabled, so might as well write the heap profile.
=> Write heap profile at the end of the benchmark

cmd/pebble/main.go, cmd/pebble/scan.go, cmd/pebble/sync.go, cmd/pebble/ycsb.go
Add a flag to specify max operations per second in scan, sync, and ycsb benchmarks.
This allows us to properly measure read/write latencies at specified rates. Concurrency should be set high enough so that the go routines are stopped by the rate limiter. This way, even if read/write latencies are high on certain go routines, new reads/writes can still come in.
=> Add max ops/sec to benchmarks

sstable/reader.go, table_cache.go
Side benefit of removing duplicated code.
=> Avoid an allocation for a closure in tableCache.newIters

compaction.go, db.go, log_recycler.go, log_recycler_test.go, metrics.go, open.go, testdata/event_listener, version_set.go
The tracking of the number of WAL files was buggy, causing incorrect and
impossible values (very large positive values due to subtracting 1 from
a count of 0). Also noticed that we weren't exposing the number of
obsolete (dead) log files. That count is now exposed via
WAL.ObsoleteFiles.
=> Fix metrics WAL file tracking

cache/clockpro.go
The previous setting of NumCPU shards was causing `shard.Set` to show up
as a contention point in concurrent read-only workloads where the
working set is larger than the block cache size.
=> Increase the number of block cache shards to 2*NumCPU

cmd/pebble/rocksdb.go
A previous commit changed `LevelMetrics.NumFiles` from a `uint64` to an
`int64` which broke the `-tags rocksdb` build.
=> Fix rocksdb build

ingest.go, ingest_test.go, internal/base/internal.go, testdata/ingest_sort_and_verify
Previously, the end key of a range deletion tombstone was considered exclusive for the purposes of deletion, but considered inclusive when checking if two SSTables overlap. For example, an SSTable with a range deletion tombstone [a, b) would be considered overlapping with an SSTable with a range deletion tombstone [b, c). This commit fixes this check.
Fixes #193.
=> Fix ingestSortAndVerify overlapping check

cache/clockpro.go, cache/clockpro_test.go, compaction_test.go, db.go, ingest.go, ingest_test.go, internal/base/options.go, internal/base/options_test.go, level_iter_test.go, merging_iter_test.go, open.go, ptable/reader.go, sstable/properties_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/writer_test.go, table_cache.go, table_cache_test.go
Allow a cache to be shared by multiple Pebble instances by adding a
`dbNum` argument to the cache methods which take a `fileNum`. Plumb this
through everywhere, which is the majority of changes.
Provide a global `dbNum` allocator. This "uniquifier" only needs to
provide uniqueness within a single process.
Change the default options to create an 8 MB cache rather than not
caching at all. This matches the RocksDB behavior.
Fixes #206
=> cache: add a dbNum argument to cache methods

sstable/reader.go, sstable/reader_test.go
The previous calculation of `curOffset` at the end of a compressed
block caused the value to be larger than the end offset of the block on
disk. This is problematic because the next block would then set
`curOffset` to a smaller value. This in turn would lead to
`bytesIterated` being incremented by a very large value (a negative
value stuffed in a `uint64`) which would in turn cause the compaction
pacer to enter a loop which would take ~forever to terminate.
=> sstable: fix curOffset calculation at end of compressed block

batch_test.go, internal/arenaskl/skl_test.go, mem_table_test.go, sstable/reader_test.go
Updated bytes iterated tests to check if it moves backwards during iteration. Also increased the value range in the test table creation in `reader_test.go` to test different entry sizes.
=> Update bytes iterated tests

vfs/file_lock_windows.go
The defaultFS.Lock() function was not being defined correctly
on Windows, resulting in defaultFS not matching the definition of
the FS interface on that platform.
=> vfs: Fix Lock() function for Windows

cmd/pebble/ycsb.go
The ycsb benchmarks implemented in pebble currently encode MVCC
keys incorrectly. As a result, rocksdb is unable to read and parse
these keys (assuming the db was generated without `--rocksdb`):
```
ubuntu@ip-10-12-37-11:~$ ./pebble ycsb /mnt/data1/bench_16G --workload scan=100 --concurrency 16 --prepopulated-keys $[16*1024*1024*1024/64] --initial-keys 0 --keys uniform --duration 2m --cache $[1*1024*1024*1024] --scans 1000 --rocksdb
dir /mnt/data1/bench_16G
concurrency 16
I190808 17:37:01.891432 1 storage/engine/rocksdb.go:602  opening rocksdb instance at "/mnt/data1/bench_16G"
I190808 17:37:01.971822 74 ???:1  bad log format: failed to split mvcc key
```
Bump the number of "timestamp bytes" at the end by 1 to account for
the zero byte (on top of the usual uint64 wall time).
Thanks to …
=> cmd/pebble: Fix MVCC encoding for keys

error_test.go, go.mod, go.sum, table_cache.go, table_cache_test.go, vendor/modules.txt, vfs/fadvise_generic.go, vfs/fadvise_linux.go, vfs/mem_fs.go, vfs/vfs.go
This change calls fadvise with FADV_RANDOM on sstable file descriptors,
to ensure that readahead is disabled. This reduces wasted I/Os when
reading from sstables, since sstable reads especially for short to
medium range scans do not read large enough contiguous blocks to be
able to take advantage of readahead. Instead, readahead ends up reducing
user-visible I/O performance.
See #198 .
=> vfs, table_cache: fadvise FADV_RANDOM on sstable files

db.go, db_test.go, event.go, event_listener_test.go, flush_test.go, internal/base/event.go
Call `WriteStallBegin()` when entering write stall mode and
`WriteStallEnd()` when leaving write stall mode.
=> Add `EventListener` functions for write stalls

internal/pacertoy/pebble/main.go, internal/pacertoy/rocksdb/main.go
Simulation which models the new proposed pacing mechanism for Pebble.
This should be compared with #159, which is a simulation to model the current pacing mechanism in RocksDB.
This mechanism takes inspiration from [bLSM](https://www.eecs.harvard.edu/~margo/cs165/papers/gp-lsm.pdf) and [ScyllaDB](https://www.scylladb.com/2018/12/04/worry-free-ingestion-flow-control/). In particular, the memtable pacing takes inspiration from bLSM by using a low and high watermark to throttle user writes and slow down memtable flushing, and inspiration from ScyllaDB to pace memtable flushing by looking at compaction debt to ensure that data is ingested as quickly as possible, but not any quicker.
The formula for throttling memtable flushing is:
**memtable_flush_rate = …
=> Add Pebble pacing simulation

commit.go, commit_test.go, get_iter_test.go, ingest.go, ingest_test.go, testdata/ingest
When two or more files are ingested atomically, assign distinct global
sequence numbers to each sstable. This avoids an error that would
previously occur when two L0 sstables shared the same global sequence
number which violated the invariant about the ordering of L0
sstables. Rather than relaxing the error, assigning distinct sequence
numbers avoids it and opens up the possibility of ingesting overlapping
sstables in the future.
=> Assign distinct seqnums to ingested sstables

cmd/pebble/main.go, tool/data_test.go, tool/db.go, tool/manifest.go, tool/sstable.go, tool/sstable_test.go, tool/testdata/sstable_scan, tool/tool.go, tool/util.go, tool/wal.go
Rather than global commands, provide the tool commands via structs. This
will make it more natural for configuring options associated with the
commands, such as registering pretty printers or additional comparers or
mergers.
Add support for specifying start and end keys for `sstable scan` in
hex. Add support for specifying the format of keys and values for
`sstable scan`.
=> Restructure the tool commands

compaction.go, db.go, event_listener_test.go, internal/base/options.go, open.go, open_test.go, testdata/event_listener
Allow a DB to be opened in read-only mode, which disables writes,
background flushes and compactions, and the flush which normally occurs
after replay the WAL at startup. This is useful for introspection tools
which wish to inspect the state of a DB without modifying it.
=> Add Options.ReadOnly

compaction.go, data_test.go, event.go, event_listener_test.go, internal/base/event.go, open.go, testdata/event_listener
Add an event for table creation. This event fires immediately after the
sstable file is created which means the file will be empty (nothing has
been written to it yet).
Refactor the write stall event tests to use the TableCreated event for
detecting when a table is created for flush vs compaction.
=> Add TableCreated event

internal/base/options.go, sstable/comparer.go, sstable/reader.go, sstable/reader_test.go, tool/sstable.go, tool/tool.go
Replace `base.Options.{Comparers,Mergers}` with
`sstable.OpenOption`. The `Comparers` and `Mergers` fields were only
being used by `sstable.NewReader` to allow opening of a table where the
comparer or merger is not known ahead of time. This primarily occurs in
debug tooling.
Fixes #232
=> Remove Options.{Comparers,Mergers}

batch.go, batch_test.go
RocksDB batches contain a count field in their byte representation
which is usually NOT incremented for any operation of kind LogData
that exists in the WAL but isn't applied to the memtable. As
Cockroach moves to using pebble.Batch instead of its own batch builder,
reconcile this difference so RocksDB doesn't error out on pebble.Batch
produced batches.
Also adds two exported helper functions - MaybeInit and NewBatchFromRepr,
which will be used in Cockroach.
=> batch: Don't increment count on LogData(), add misc helpers

batch.go, batch_test.go, db.go, mem_table.go, open.go
Rather than returning a `DeferredBatchOp`, the `Batch.*Deferred` methods
now return a `*DeferredBatchOp`. This replaces copying the
`DeferredBatchOp` struct (64 bytes) with a pointer (8 bytes). This sped
up the benchmarks sufficiently that we can use the `*Deferred` methods
to implement the non-deferred methods.
Add a `Batch.count` field, rather than incrementing the count directly
in the batch representation. This is both a minor performance
win (`Batch.increment` showed up in the `BatchSet` benchmark), as well
as a convenience win `Batch.Reset` no longer mutates the value returned
by `Batch.Repr()`. There were a handful of places in the code which were
previously accessing or setting `Batch.storage.data` directly which were
changed to use `{Repr,SetRepr}()`.
````
name …
```
=> Tweak the Batch.*Deferred implementation for performance

batch.go, batch_test.go, commit.go
Note that `Batch.Empty()` is not the same as `Batch.Count() == 0`
because log-data records do not increment the count.
=> Add Batch.Empty method

batch_test.go
Copying a batch by value causes `go vet` to complain due to the
embedded `sync.NoCopy` courtesy of `sync.WaitGroup`.
=> Avoid copying a batch by value

sstable/reader.go, tool/sstable.go, tool/testdata/sstable_layout, tool/util.go
Show layout of range-del blocks.
Optionally display keys and values in data and range-del blocks. This is
useful to see exactly what data has been stored in an sstable, and
provides visibility into the contents of the range-del block.
See #250
=> Enhance `sstable layout` output

compaction.go, pacer.go, pacer_test.go, testdata/compaction_pacer_maybe_throttle
In the absence of user writes, allow flushes and compactions to proceed
as fast as possible, but lower the pacer recalculation threshold in
order to be nimble to new user writes.
Fixes #248
=> Don't pace flushes/compactions if there are no user writes

cmd/pebble/main.go, cmd/pebble/random.go, cmd/pebble/scan.go, cmd/pebble/sync.go, cmd/pebble/ycsb.go
Add option to fluctuate ops per second in the benchmarks.
This would be useful for testing how Pebble/RocksDB behaves when the read/write rates fluctuate.
=> Add fluctuation option to benchmarks

compaction_iter.go, testdata/compaction_iter
Elide point deletion tombstones in compaction output when they are
covered by range deletion tombstones.
=> Elide tombstones when they are covered by range tombstones

compaction.go, compaction_test.go, flush_test.go, get_iter_test.go, internal/base/comparer.go, internal/base/internal.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/rangedel/tombstone.go, iterator_test.go, range_del_test.go, sstable/writer.go, testdata/compaction_check_ordering, tool/db.go, tool/manifest.go, tool/util.go, tool/wal.go, version_set.go
Use the configured format when formatting keys for error messages.
Clarify some comments about the keys passed to Comparer functions.
=> Introduce Formatter function for formatting user keys

batch.go, batch_test.go, internal/batch/batch.go
Previously, creating a flushable batch on an empty batch would panic.
Add a `Batch.sort` facility which is exposed for testing via
`internal/Batch.Sort`. Not currently used, but will be in the
metamorphic tests.
=> Allow creating a flushable batch on an empty batch

tool/data_test.go, tool/manifest.go, tool/sstable.go, tool/testdata/manifest_dump, tool/testdata/sstable_scan, tool/testdata/wal_dump, tool/tool.go, tool/util.go, tool/wal.go
If the key formatter falls back to calling printf on the key,
and there's an in-use pebble.Comparator with a specified Format
function, then use that format function instead.
=> tool: Use the comparator-specified Formatter if there is one

internal/manifest/version.go, testdata/compaction_check_ordering
The `manifest.CheckOrdering` checks were overly strict, rejecting valid
L0 orderings. In particular, the checks were rejecting orderings that
can occur after ingestion. An sstable ingested into L0 can be given a
global seqnum which lies in the middle of another L0 sstable. This is ok
because during ingestion we checked that the ingested sstable does not
overlap in the key range of the other sstable.
=> Fix incorrect manifest.CheckOrdering checks

internal/rangedel/fragmenter.go, internal/rangedel/fragmenter_test.go, internal/rangedel/testdata/fragmenter, internal/rangedel/testdata/fragmenter_flush_to, testdata/compaction_iter
An empty range tombstone doesn't delete any keys. Avoid emitting them as
they cause the fragmenter to violate the invariant that range tombstones
are emitted in start-key order.
=> Avoid emitting empty range tombstones

batch_test.go, data_test.go, db.go, internal/arenaskl/flush_iterator.go, internal/arenaskl/iterator.go, internal/arenaskl/skl_test.go, internal/base/iterator.go, internal_test.go, iterator_test.go, level_iter.go, level_iter_test.go, mem_table_test.go, merging_iter.go, sstable/block.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/testdata/reader/iter, sstable/writer_test.go, table_cache_test.go
It is only valid to call `Iterator.Key()` if `Iterator.Valid()` returns
true.
=> Avoid invalid calls to Iterator.Key

Makefile, cmd/pebble/badger.go, cmd/pebble/badger_disabled.go, cmd/pebble/boltdb.go, cmd/pebble/boltdb_disabled.go, cmd/pebble/main.go, cmd/pebble/test.go
Replace the `--rocksdb` flag with an `--engine` flag that can specify
"pebble", "badger", "boltdb", or "rocksdb". Note that not all of the
engine types implement all of the engine functionality. This is intended
for comparative performance tests.
=> Add support for boltdb and badger

internal/base/options.go, sstable/table.go, sstable/testdata/writer, sstable/writer.go, sstable/writer_test.go
Currently this disables usage of the RocksDB sstable footer and
two-level indexes.
Fixes #285
=> Disable RocksDB sstable extensions with TableFormatLevelDB

db.go, db_test.go, mem_table.go, tool/manifest.go
Currently, any batches with LogDatas would panic on commit due to
mismatching batch counts. This is because we were not accounting for
the fact that LogData's don't add to the batch count when incrementing
seqNum.
=> mem_table: Don't increment seqNum for logData requests

sstable/block_test.go
I just ran `go get golang.org/x/lint/...` and TestLint started
complaining about the `kFoo` variable names.
=> sstable: satisfy new golint

ingest.go, ingest_test.go, vfs/mem_fs.go, vfs/testdata/vfs, vfs/vfs.go, vfs/vfs_test.go
Add `LinkOrCopy` utility which attempts to create a hard link, and falls
back to copying if hard linking fails.
Fixes #305
=> vfs: add LinkOrCopy utility

commit_test.go, ingest.go, internal/record/log_writer.go
`TestCommitPipelineWALClose` was calling `LogWriter.Close` concurrently
with `LogWriter.SyncRecord`. This is a no-no according to the
`LogWriter` comments, and also not something done by Pebble itself. Fix
this concurrency violation by adding a `WaitGroup` that allows the test
to determine when all of the workers have queued their WAL writes and
are waiting for them to sync. This both the concurrency problem, and
also removes a timing wart in the test implementation.
=> fix concurrent use of LogWriter in TestCommitPipelineWALClose

compaction_iter.go, testdata/compaction_iter
Fix a panic in rangedel.Fragmenter: `flush-to key < flushed key`. The
problem was that `compactionIter` was adding tombstones to the
fragmenter too early. In particular, we hit this panic by adding
tombstones that had a larger start key than the current key. If the
compaction logic decided to switch to the next sstable, we'd flush up to
the current key which is less than the start key of the most recently
added tombstone.
Fixes #317
=> fix rangedel.Fragmenter panic

cmd/pebble/main.go, cmd/pebble/random.go, cmd/pebble/scan.go, cmd/pebble/sync.go, cmd/pebble/ycsb.go, internal/randvar/flag.go
Add `randvar.Flag` and `randvar.BytesFlag` for specifying random
variables via command line flags. Extracted from
`cmd/pebble.parse{RandVar,Values}Spec`. Also added `rateFlag` which is
used by `cmd/pebble`. This is both general cleanup and preparation for
being able to use `randvar.{,Bytes}Flag` outside of `cmd/pebble`.
=> add randvar.Flag and randvar.BytesFlag

ingest.go, ingest_test.go
Ingestion needs to schedule a compaction as a final step, otherwise we
can hit a write stall due to too many L0 files, but nothing has kicked
off a compaction. Found by the metamorphic test.
=> fix indefinite write stall after ingestion

db.go
Previously, L0StopWritesThreshold was stalling writes until the number
of L0 files fell to `<= L0StopWritesThreshold`. This is now changed to
`< L0StopWritesThreshold` to match the semantics in RocksDB.
=> fix L0StopWritesThreshold write stalls

internal/base/event.go, testdata/event_listener
Include the file numbers of compaction and flush output, and the file
numbers of compaction inputs. This will make logging flush/compaction
events more useful for post-mortem debugging.
=> internal/base: tweak format of {Compaction,Flush}Info.String()

cleaner.go, cleaner_test.go, compaction.go, internal/base/cleaner.go, internal/base/options.go, internal/base/options_test.go, internal/datadriven/test_data_reader.go, testdata/cleaner, vfs/mem_fs.go, vfs/vfs.go
For debugging purposes, db cleaner option can set as archive cleaner. If this option is set, the files are renamed to the archive directory instead of deleting.
Fixes #284
=> db: provide facility for retaining obsolete WALs, MANIFESTs, and sstables

internal/base/options.go, internal/base/options_test.go
Fixes test breakage due to merge skew.
=> internal/base: add parsing support for Options.Cleaner

internal/manifest/testdata/version_check_ordering, internal/manifest/testdata/version_edit_apply, internal/manifest/version.go, internal/manifest/version_edit.go, tool/testdata/manifest_dump
=> Handle case of sequence number 0 files for compatibility with RocksDB.

compaction_test.go, db.go, ingest.go, internal/cache/clockpro.go, internal/cache/clockpro_test.go, internal/private/sstable.go, level_iter_test.go, merging_iter_test.go, open.go, sstable/properties_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/writer_test.go, table_cache.go, table_cache_test.go, tool/sstable.go
Avoid a common source of errors which made it easy to accidentally get
cache collisions by preventing the use of the zero cache ID. Renamed
`dbNum` to `cacheID` to make it clear that the cache can be used without
a DB.
Added `Cache.NewID()` for allocating cache IDs. Changed
`sstable.NewReader` to allocate a new `cacheID` via `Cache.NewID()` if 0
is passed as an argument.
=> db: rework how cache IDs are allocated

ingest.go, sstable/reader.go, sstable/reader_test.go, tool/sstable.go, vfs/mem_fs.go
Changed `NewReader()` to return either a Reader on success, or an
error on failure, but never both. This should be more conventional.
Also introduced `vfs.NewMemFile()` on the pretense of it being useful
for this PR's unit test. Though really it is needed to simplify a PR in
Cockroach repo.
=> sstable: NewReader cleanup on error

vfs/mem_fs.go, vfs/mem_fs_test.go
Follow-up to #341. Since `NewMemFile()` was only used in tests expected
to encounter errors that hid the bug that such files were not readable.
Added a test for `NewMemFile()` where its contents must be readable.
=> vfs: NewMemFile should be readable

compaction.go, ingest.go, internal/cache/clockpro.go, internal/cache/clockpro_test.go, sstable/reader.go, sstable/writer.go, sstable/writer_test.go, table_cache.go
When an sstable is being written, evict newly written blocks from the
block cache. This provides a further defensive mechanism against
accidentally using a block in the cache that was written by a previous
sstable.
Fixes #336
=> sstable: evict newly written blocks from the block cache

batch.go, db.go, db_test.go, open.go
CockroachDB uses pebble.Batch for building batches. This avoids a
performance a regression due to the recomputation of
`Batch.memTableSize` whenever `Batch.Apply` and `Batch.SetRepr` are
called. `Batch.memTableSize` is only used by Pebble when committing a
batch. Rather than computing it up front, we can delay computation if
the `Batch` is not associated with a `DB`.
=> avoid (re-)computing Batch.memTableSize when it won't be used

batch.go, batch_test.go, cmd/pebble/db.go, cmd/pebble/test.go, compaction.go, db.go, ingest.go, internal/cache/clockpro.go, internal/humanize/humanize.go, mem_table.go, mem_table_test.go, metrics.go, metrics_test.go, pacer.go, pacer_test.go, sstable/filter.go, sstable/reader.go, table_cache.go, testdata/event_listener, tool/testdata/db_lsm, version_set.go
Add metrics for the cache, compactions, flushes, filters, and
memory. Extend the per-level metrics with counts of flushed, compacted,
ingested, and moved sstables.
Fixes #322
=> db: extend the metrics returned by DB.Metrics

compaction.go, ingest.go, options.go, table_cache.go
This exposes `Make{Reader,Writer}Options` for use by the metamorphic
test.
=> rename make{Reader,Writer}Options to Options.Make{Reader,Writer}Options

db_test.go, tool/data_test.go, vfs/clone.go, vfs/testdata/vfs, vfs/vfs_test.go
`vfs.Clone` was accidentally using `vfs.Default` instead of `srcFS` in
one place.
Tweaked the semantics of clone so that the `dstDir` now becomes
`dstPath`. This makes `vfs.Clone(..., "a/b", "c")` copy the contents of
directory "a/b" into "c", rather than copying the contents into "c/b".
Extended `TestVFS` to test the behavior of clone.
=> fix buglet in vfs.Clone

compaction.go, compaction_picker.go, compaction_test.go, internal/manifest/version.go, range_del_test.go, testdata/compaction_expand_inputs, testdata/compaction_setup_inputs
When determining the boundaries for an sstable, we need to truncate the
boundaries to the boundaries of the input. Failing to do this was
allowing the lower bound of the first sstable in a compaction to expand
beyond the lower bound of the input when the sstable contain a range
tombstone.
Fixes #337
=> truncate sstable boundaries to the compaction input boundaries

internal/cache/alloc.go, internal/cache/alloc_test.go
Rather than always evicting the last slot in `allocCache.free`, we now
evict a random slot. Additionally, the newly freed buffer is inserted
into a random slot. This prevents pathological behavior where the cache
is filled with buffers of a size class that is no longer useful for
allocation.
```
name           old time/op    new time/op    delta
AllocCache-16     271ns ± 2%      40ns ± 1%   -85.15%  (p=0.000 n=9+10)
name           old alloc/op   new alloc/op   delta
AllocCache-16    2.05kB ± 0%    0.00kB       -100.00%  (p=0.000 n=10+10)
name           old allocs/op  new allocs/op  delta
AllocCache-16      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
```
Fixes #358
=> internal/cache: improve allocCache eviction heuristics

internal/cache/clockpro.go, internal/cache/clockpro_test.go
Noticed when ingesting SSTables as part of a cockroach snapshot apply.
reservedSize would exceed maxSize, leading to an infinite loop in
evict().
=> cache: Update cache targetSize to always return a positive int

internal/rate/rate_test.go
The flakiness seems related to the lower time resolution on Windows, but
could also be related to the VMs. Regardless, getting notified about
these failures isn't helpful.
=> internal/rate: skip a few tests that are flaky on Windows CI

batch.go, commit.go, db.go, db_test.go, mem_table.go
We were failing to clear `Batch.count` for large batches which was leading
to some super strange `make stress` errors. This turned out to be extremely
onerous to debug which resulted in most of the code changes here (the fix
is the small change to `Batch.Reset`).
The `make stress` failure was a panic comming out of `syncQueue.pop()`
because the `WaitGroup` had a negative counter. How did an incorrect
`Batch.count` result in a negative `WaitGroup` counter? The incorrect
`Batch.count` was causing `memTable.apply` to panic. The panic there was
propagating up through `DB.LogData` which had a `defer Batch.release()`.
Defers get run on the panic return, so we were calling
`Batch.release()` on a batch still sitting on the
`syncQueue`. Internally, `Batch.release()` resets `Batch.commit` (the …
=> fix resetting of Batch.count for large batches

open.go, open_test.go, options.go
Needed to implement `MustExist` when opening a CRDB storage engine.
Rename `Options.ErrorIfDBExists` to `Options.ErrorIfExists` for
consistency.
=> add Options.ErrorIfNotExists

compaction_iter.go, internal/base/merger.go, iterator.go, merger.go
Changed the merge operator API to support adding operands one by one via
`Merge{Newer,Older}()` followed by a call to `Finish()`. This gives
implementations the option to accumulate merge operands, only doing the
final merge work when `Finish()` is called. For example, it can be used
to reduce (de)serialization of partial merge results compared to the
previous binary operation API.
=> allow accumulation of merge operands before merge

db.go, error_test.go, event_listener_test.go, internal/record/record.go, internal/record/record_test.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener, vfs/mem_fs.go, vfs/mem_fs_test.go, vfs/testdata/vfs, vfs/vfs.go, vfs/vfs_test.go
The existing rename+create flow prevents the FS from distinguishing
this case from normal renames, which is a problem for an encrypted
FS where we are currently unable to reuse WAL files.
=> Add vfs.FS.ReuseWAL method for reusing WAL files.

internal/record/log_writer.go
This commit makes it clear that the primary benefit of the data type is
to allow the condition variable's condition to change outside of its
lock, not just to allow it to be signalled outside of its lock.
=> clarify comment on flusherCond

sstable/block.go, sstable/reader.go
Retain the `blockIter.{fullKey,cached,cachedBuf}` (the dynamically
allocated buffers) across `sync.Pool` reuse of `singleLevelIterator` and
`twoLevelIterator`. This significantly reduces allocations which is the
point of pool allocation in the first place. This also obviates the need
for `blockIter.keyBuf` which has now been removed.
This provides a nice speedup on CRDB's short range (1-10 row)
`MVCCReverseScan` benchmarks:
```
name                                                         old time/op    new time/op    delta
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=8-16        3.17µs ± 3%    2.69µs ± 2%  -15.39%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=64-16       5.07µs ± 4%    4.00µs ± 3%  -21.08%  (p=0.000 n=10+10) …
```
=> sstable: retain blockIter buffers across sync.Pool reuse

batch.go, commit.go, commit_test.go, db.go, internal/batchskl/iterator.go, internal/batchskl/skl.go, internal/batchskl/skl_test.go, open.go
* internal/batchskl: add in-order insertion fast-path
* internal/batchskl: remove splice.init and Skiplist.set{Next,Prev}
* internal/batchskl: manually inline findSpliceForLevel in findSplice
* batchDecodeStr
* remove batchStorage
* internal/batchskl: rework Skiplist key storage
These were motivated by investigation of the CRDB
`BatchApplyBatchRepr_Pebble` benchmark:
```
name                                                                                 old time/op    new time/op    delta
BatchApplyBatchRepr_Pebble/indexed=false/seq=false/valueSize=10/batchSize=10000-16      188µs ± 4%     148µs ± 2%   -21.22%  (p=0.000 n=10+9)
BatchApplyBatchRepr_Pebble/indexed=false/seq=true/valueSize=10/batchSize=10000-16       185µs ± 4%     148µs ± 1%   -19.80%  (p=0.000 n=10+9) …
```
=> various batch and batchskl optimizations

db.go, level_iter.go, merging_iter.go, merging_iter_test.go, testdata/level_iter, testdata/merging_iter
Improvements and bug fixes related to levelIter and mergingIter
- levelIter:
- introduce smallestUserKey.
- close the range delete iterator before switching it, since
the mergingIter does not know it is being switched, so we
do not ignore errors.
- mergingIter:
- added test that catches multiple bugs in our current logic
(the following uses forward iteration -- similar bugs were
in reverse iteration).
- The use of tombstone.Contains() in isNextEntryDeleted()
allowed a tombstone to extend before the smallest key.
- L0=>L0 compaction and the same code as previous bullet:
The rangeDelIter will not be nil even though we have
exhausted the L0 file, since we don't wrap these in a
levelIter. The tombstone can extend greater than the
largest key.
- In isNextEntryDeleted() the seekGE() call does …
=> Bug fixes related to range deletions in levelIter and mergingIter

.travis.yml, compaction.go, compaction_test.go, testdata/compaction_allow_zero_seqnum
When flushing, the `allowZeroSeqNum` check finds the smallest and
largest key being flushed and checks to see if there is any overlap with
sstables in lower levels. This logic is sound, but we need to make a
copy of the keys because any iterator positioning call such as `Last`
will invalidate the key returned from a previous call. So instead of
checking `[smallest,largest]` for overlap, we were checking
`[largest,largest]`.
=> fix compaction.allowZeroSeqNum when flushing

level_iter.go, testdata/level_iter_boundaries
Fix a bug which caused `levelIter.Seek{GE,LT}` to return `nil,nil` when
it was positioned at a boundary key and the seek operation was to the
same sstable that it was already pointing at. The root cause of the bug
was overloading the meaning of the `levelIter.iter` field.
Took the opportunity to remove some detritus that had been necessary
before previous simplifications to the `internalIterator`
API. Specifically, now that there is no longer `Key()` method we don't
need to setting `levelIter.iter` to `nil` when we're at a boundary
key. Additionally, there is no need for `Next()` and `Prev()` to do
anything sane when positioned off the end of the level as all callers
properly use `First()` and `Last()` now.
=> fix levelIter.Seek{GE,LT} bug

merging_iter.go, merging_iter_test.go
Motivated by Peter's finding of an infinite loop which turned out to
have a different root cause.
=> Comments on why certain loops in mergingIter will make forward progress.

batch.go, commit_test.go, compaction.go, data_test.go, db.go, db_test.go, get_iter_test.go, ingest_test.go, mem_table.go, mem_table_test.go, open.go, open_test.go, options.go, testdata/event_listener, tool/testdata/db_lsm
Always allocating memtables with a backing arena of
`Options.MemTableSize` causes severe memory pressure in tests which use
a lot of concurrent DB instances such as the CRDB logic tests. Unlike
RocksDB, the Pebble memtable fully allocates the memory for a memtable
up front. So a 64MB memtable consumes 64MB immediately. Changing the
`arenaskl` to allow the arena to grow dynamically is tricky to do in a
performant manner in Go. Rather, we take the approach of starting a DB
with a small memtable size (256KB) and then doubling the size of each
subsequent memtable up to `Options.MemTableSize`.
In order to avoid any significant change in flushing behavior, the flush
heuristic has been changed so that we only flush when the sum of the
flushable queued memtables reaches `Options.MemTableSize/2`. …
=> dynamically grow the memtable size

iterator.go, testdata/iterator
`Iterator.SeekPrefixGE` was using `bytes.HasPrefix` to determine if the
key found shared the prefix with the seek key. Somewhat confusingly,
this is not the correct semantics for prefix iteration. Instead, prefix
iteration requires that the key found has the same prefix as that
returned by `Comparer.Split`.
Replaced calls to `bytes.HasPrefix` with code which extracts the prefix
using `Comparer.Split` and performs equality comparision between the
seek prefix with current key's prefix.
=> fix Iterator.SeekPrefixGE semantics

compaction.go, testdata/compaction_allow_zero_seqnum, testdata/manual_flush
RocksDB never zeroes seqnums when flushing. Doing so mostly works except
for a bad interaction with WAL replaying at startup. While that
interaction could be fixed, for now it seems safest to match the RocksDB
behavior.
=> disable zeroing of seqnums when flushing

db.go, db_test.go, event_listener_test.go, mem_table.go, open.go, testdata/event_listener
Tweak the dynamic memtable sizing logic so that we only grow the
memtable size if we filled it over 50% when a manual flush was
performed. This reduces memtable memory pressure in workloads which
frequently manually flush.
=> only grow the memtable size if we filled it over 50%

level_iter.go, testdata/level_iter
and iter is nil because the file pointed to by index is beyond the
iteration bounds. This is not an error, and if the bounds change
and the index does not, we should create an iterator.
Fixes cockroach #42353
=> levelIter bug fix: Handle the case where index is valid, err is nil

event.go, testdata/event_listener
`TableIngestInfo.String` was the only event info struct that used a
multi-line format. A single-line format looks nicer in output to CRDB
log files. Tweaked the format to include the file numbers of the
ingested sstables.
=> change TableIngestInfo.String to a single-line format

data_test.go, internal/base/iterator.go, level_iter.go, level_iter_test.go, testdata/level_iter, testdata/level_iter_boundaries, testdata/level_iter_seek_prefix_ge, testdata/merging_iter_seek
Fix `levelIter.SeekPrefixGE` to not seek past an sstable which doesn't
contain the target key if that table does contain range tombstones. The
prior behavior allowed range tombstones to be unintentionally skipped.
=> fix levelIter.SeekPrefiGE positioning

compaction.go, data_test.go, ingest.go, ingest_test.go, open.go, testdata/ingest, version_set.go
Fix a bug where ingestion was blindly updating the seqnum for the
largest key in an sstable. This unintentionally extended the bounds for
an sstable when the largest key was a range tombstone sentinel key. This
is a minor cosmetic issue as the range tombstone's effect was not
changed by the extension of the sstable bounds.
Fix a bug where concurrent ingestions could collide in choosing their
target level. This collision occurred in `DB.ingestApply` which appears
to have mutual exclusion via `DB.mu`, but that exclusion was being
thwarted by `versionSet.logAndApply` which releases `DB.mu` during the
write to the MANIFEST. Internally, `logAndApply` achieves mutual
exclusion of MANIFEST operations by a separate mechanism. That mechanism
is now made visible via `versionSet.log{Lock,Unlock}` …
=> fix two ingestion bugs

db.go, sstable/reader.go, table_cache.go, tool/db.go, tool/sstable.go, tool/testdata/db_space, tool/testdata/sstable_space
Introduced a new DB API, `EstimateDiskUsage()`, which takes an
inclusive-inclusive range of user keys, `[start, end]`, and returns the
approximate space used in files for storing that range. See comment in
"db.go" for details on how it is calculated.
=> add EstimateDiskUsage API for range space usage

internal/metamorphic/history.go, internal/metamorphic/history_test.go
Prefix all lines of `Infof` and `Fatalf` output with `// {INFO,FATAL}`.
=> internal/metamorphic: address a TODO in history logging

cleaner_test.go, compaction.go, internal/metamorphic/test.go, testdata/cleaner
Fix a bug where we were specifying the wrong path for cleaning when
`Options.WALDir` is specified.
=> internal/metamorphic: exit early on any background error

go.mod, internal/metamorphic/config.go, internal/metamorphic/meta_test.go, internal/metamorphic/ops.go, internal/metamorphic/options.go
Output comparison is currently disabled by default as it is finding
differences that appear to be due to bugs in Pebble.
Pass `pebble.NoSync` to the various write methods as we're not relying
on syncing and Pebble returns an error if you try to sync and the WAL is
disabled.
Fixes #408
=> internal/metamorphic: compare output from runs

compaction.go, compaction_iter.go, compaction_iter_test.go, pacer.go, testdata/compaction_iter, testdata/compaction_pacer_maybe_throttle
Previously compactionIter internally added range tombstones to the
fragmenter as they were seen and then skipped over them. However, this did
not give the client the option to make decisions based on the range
tombstone data before adding it to fragmenter. This was inconsistent
with point keys, which were always returned by compactionIter before
being added to the output file by `runCompaction()`'s loop.
This PR makes range tombstone start keys "non-skippable", i.e., returned
by compactionIter as soon as they are seen, even if covered by another
key in the same snapshot stripe. The ownership of the fragmenter is
moved into the `compaction` object and it is now responsible for adding
tombstones after they are returned by the `compactionIter`.
There are also some miscellaneous cleanup …
=> pause compactionIter at range tombstone start keys

compaction.go, compaction_test.go
`shouldStopBefore()` was hard to change because it needed to be called
every time before extending a file's range by adding a point key. But in
the world of range data (i.e., range tombstones) this no longer makes
sense because we do not want a simple yes/no answer to whether a point
key is acceptable to add; instead, we want the exact key at which the
file should be cut as it may be in the middle of a range.
To provide this capability, this PR replaces `shouldStopBefore()` with a
function, `findGrandparentLimit()`. It takes the start key of a file and
returns the latest possible end key that can be used without violating
grandparent overlap rules. Unlike `shouldStopBefore()`, it does not
maintain any state about keys seen or files already passed, which I
believe makes it easier to …
=> replace shouldStopBefore with stateless function

compaction.go, compaction_test.go, data_test.go, db.go, ingest.go, internal/metamorphic/test.go, level_checker.go, level_checker_test.go, open.go, options.go, range_del_test.go, read_state.go, read_state_test.go, testdata/level_checker, tool/db.go, tool/testdata/db_check
=> Add DB.CheckLevels() that compares sequence number across all levels for

compaction.go, db.go, internal/manifest/testdata/version_edit_apply, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, level_checker.go, mem_table.go, metrics.go, metrics_test.go, read_state.go, testdata/event_listener, testdata/metrics, tool/manifest.go, tool/testdata/db_lsm, version_set.go
Add support for tracking zombie memtable and sstable counts and
sizes. Zombie {mem,ss}tables are those which are no longer referenced by
the current `readState`, but are still in use by an earlier
`readState` (i.e. inuse by an iterator).
Fix a bug where we weren't deleting obsolete sstables when an iterator
was closed until the next flush or compaction occurred.
Fixes #49
=> add support for Metrics.{,Mem}Table.Zombie{Count,Size}

compaction.go, data_test.go, db.go, event.go, ingest.go, ingest_test.go, open.go, testdata/ingest_target_level
Previously, a concurrent ingestion and compaction could lead to
violation of the no-overlap invariant. This was due to ingestion not
accounting for in-progress compactions when determining the target level
for an ingestion. We now keep track of in-progress flushes and
compactions and prohibit ingestion into a compaction's output level if
the ingested sstables overlaps the key-range of the compaction.
=> fix concurrent ingestion and compaction

compaction.go, compaction_test.go, options.go
Disable compaction/flush pacing until we understand why it so
significantly impacts throughput.
```
name                    old ops/sec  new ops/sec  delta
kv0/enc=false/nodes=1    15.2k ± 6%   16.5k ± 6%   +9.09%  (p=0.000 n=20+19)
```
=> disable compaction/flush pacing

go.mod
Apparently this declaration is harmless. Older versions of Go will
ignore it and there is still active discussion over what the semantics
would be.
=> add the "go 1.13" declaration to go.mod

compaction_iter.go, compaction_iter_test.go, testdata/compaction_iter
If a merge ends by hitting a range tombstone, there may still be unmerged
operands for that key. Those yet-to-be-merged operands will have their
seqnum zeroed, so we cannot zero the seqnum of the present merge result.
=> stop zeroing merge seqnum above range tombstones

compaction_iter.go, testdata/compaction_iter
Consider the sequence of records: `a.MERGE.5`, `a.DEL.3`,
`a.MERGE.1`. During a compaction, if there is a snapshot at seqnum 2 we
were previously dropping the record `a.DEL.3`, emitting only `a.MERGE.5`
and `a.MERGE.1`. Now we transform `a.MERGE.5`+`a.DEL.3` into
`a.SET.5`. This causes that record to shadow the older `a.SET.1` record,
instead of erroneously merging with it.
=> db: transform merge+del -> set during compaction

iterator.go, testdata/iterator
`SeekPrefixGE` + `Prev` is very difficult to support correctly. The
challenge is that switching from forward iteration (requested by
`SeekPrefixGE`) to reverse iteration (`Prev`) sometimes requires seeking
one of the `InternalIterators`. Normally this seeking is done via
`SeekLT` or `Last`, but neither of those operations is correct during
prefix iteration. Rather, we'd need to add an
`InternalIterator.SeekPrefixLE` method. Plumbing that through to all of
the `InternalIterator` implementations is onerous. An alternative is to
implement `SeekPrefixLE` on top of `SeekPrefixGE`+`Next`, yet even that
approach is tricky.
CRDB never uses reverse prefix iteration. Rather than attempt a subtle
and intricate implementation, `Iterator.Prev` now sets an error if it is
called while in prefix …
=> db: disable reverse prefix iteration

internal/metamorphic/history.go, internal/metamorphic/history_test.go, internal/metamorphic/meta_test.go, internal/metamorphic/test.go
Add a `-fail` flag which specifies a regular expression to match against
the the results of operations. When the regular expression matches, the
test is failed, saving the in-memory FS state to allow for post-mortem
debugging. This is useful for debugging problems that
non-deterministically fail in ways that are not detectable from an
individual test run. For example, we might uncover a failure in the
output between two tests, determine which of the two outputs is in
error, then add additional instrumentation to debug the erroneous
output. But if that erroneous output only occurs once out of every 100
runs reproduction becomes onerous. With the `-fail` flag you can specify
a regular expression to detect the erroneous output and run with:
`-count 100 -fail <re>`
=> internal/metamorphic: add -fail flag

db.go, iterator_test.go, level_iter.go, level_iter_test.go, options.go, testdata/level_iter, testdata/level_iter_boundaries
Added `levelIter.verify` which is a race-build-only verification that
the returned key lies within the iterator bounds. Verified that this
structure of `if raceEnabled` gets compiled out of existence for
non-race builds and doesn't impact performance. `levelIter.verify` is
currently disabled as it exposes bugs in `mergingIter` bounds
handling. Those will be fixed in a subsequent change.
Fixed resetting of the table iter boundaries in
`levelIter.SetBounds()`. This was preventing a subsequent positioning
call from correctly encountering the boundary key.
Fixes #395
=> db: verify returned levelIter keys lie within iterator bounds

compaction.go, db.go, internal/base/iterator.go, iterator_test.go, level_iter.go, merging_iter.go, merging_iter_heap.go, merging_iter_test.go, testdata/merging_iter, testdata/merging_iter_seek
`mergingIter` was previously blindly calling `Seek{GE,LT},First,Last` and
disregarding supplied iterator bounds. This violated the
`InternalIterator` contract for these methods leading to various badness 
such as returning out of bounds keys which could in turn lead to iteration
stopping prematurely, making it seem like keys were missing.
=> db: various fixes to mergingIter iter bounds handling

batch.go, batch_test.go, testdata/batch_delete_range
Clear `Batch.tombstones` in `Batch.release` and in `Batch.Apply` if
tombstones were added to the batch. This fixes a bug where tombstones
added to a batch were not seen during subsequent iteration.
=> db: properly reset Batch.tombstones

compaction_test.go, data_test.go, ingest_test.go, iterator.go, iterator_test.go, metrics_test.go, range_del_test.go, testdata/iterator_next_prev, testdata/range_del
`Iterator` is required to skip over any range tombstones it sees as
there is nothing for it to do with them. These range tombstones are
present because `levelIter` uses them as markers to prevent iterating to
the next (or prev) sstable too soon. Somewhat confusingly, these marker
records may exists while iterating in one direction, but not the
other. This caused a subtle bug in `Iterator` when switching
directions. The code in `Iterator.{Next,Prev}` to handle switching from
forward to backward iteration (and vice versa) relies on knowing how the
child iterator is positioned in the absence of range
tombstones. Unfortunately, the logic was incomplete and was not ignoring
range tombstones in some circumstances (specifically,
`Iterator.{next,prev}UserKey`).
=> db: fix skipping of range tombstones in Iterator 

sstable/data_test.go, sstable/reader.go, sstable/reader_test.go, sstable/testdata/prefixreader/bloom, sstable/testdata/prefixreader/iter, sstable/testdata/reader/bloom, sstable/testdata/reader/iter, sstable/writer_test.go
Clear `singleLevelIterator.block{Lower,Upper}` in `SetBounds`. Failing to
do this was causing the values to be reused inappropriately if previous
bounds on the iterator were replaced with no bounds. Also remove the
unnecessary optimizing to elide setting `block{Lower,Upper}` in
`singleLevelIterator.initBounds`.
=> sstable: reset singleLevelIterator.block{Lower,Upper} on bounds change

tool/sstable.go, tool/testdata/sstable_properties
In `sstable properties`, account for `NumDeletions` also include
`NumRangeDeletions`. We were previously double counting range-deletions
in both the "set" and "delete" record counts.
Fixes #459
=> tool: properly calculate "set" and "delete" records

compaction_iter.go, testdata/compaction_iter
Fixes #402.
This is done for better usage semantics of `compactionIter.key`.
The other change going in is to not include previous emitted entry's value when emitting a single delete entry from `compactionIter`.  A data driven test case is included to assert this no longer happens.
=> Make `compactionIter.key` always point to an immutable buffer

sstable/data_test.go, sstable/reader.go, sstable/testdata/writer, sstable/writer.go
Properly handle skipping over empty data blocks. Such blocks could be 
created if a very small `BlockSize` was specified. RocksDB seems to handle
empty data blocks in its read path, which suggests that it can create them
(or could at some point).
The creation of empty data was itself a bug and `sstable.Writer` will no 
longer create such data blocks.
=> sstable: handle empty data blocks

compaction.go, db.go, get_iter.go, iterator.go, iterator_test.go, level_checker.go, level_iter.go, level_iter_test.go, merging_iter.go, merging_iter_test.go, testdata/iterator_next_prev
Fix a bug in `Iterator.{Next,Prev}` when switching iteration directions
at the boundaries of iteration. We need to skip over range tombstones if
they are the first/last key returned by the child iterator.
=> db: fix Iterator.{Next,Prev} direction switching at boundaries

batch.go, error_iter.go, get_iter.go, internal/arenaskl/flush_iterator.go, internal/arenaskl/iterator.go, internal/base/iterator.go, internal/rangedel/iter.go, iterator_test.go, level_iter.go, merging_iter.go, sstable/block.go, sstable/reader.go, sstable/testdata/reader/iter, testdata/level_iter_seek
Fix a bug in `levelIter.Next` when stepping away from the smallest
boundary only calls `Next` on the child iterator, rather than `First`. A
similar bug existed in `levelIter.Prev` when stepping away from the
largest boundary.
=> db: fix levelIter.{Next,Prev} when stepping away from opposite boundary

error_test.go, ingest.go, iterator.go, level_checker_test.go, level_iter_test.go, merging_iter.go, merging_iter_test.go, sstable/reader.go, sstable/writer_test.go, table_cache.go, tool/sstable.go
* Changed `NewRangeDelIter()` to return its error instead of panicking with it.
* Fixed a bug in `Iterator.Close()` where we weren't returning the error from the underlying `mergingIter.Close()`.
* Fixed a bug in `mergingIter` where we weren't returning errors from children iterators until they reached the top of the heap, which could be after we already returned wrong results.
Fixes #466.
=> multiple fixes for filesystem read error propagation

compaction.go, compaction_test.go, level_iter.go, merging_iter.go, testdata/manual_compaction, testdata/merging_iter
`compaction.newInputIter` iterates over the inputs to a compaction by
constructing a merging iter composed of 4 level iterators: 1 point and 1
range-del `levelIter` for the two input levels. The range-del
`levelIter` is constructed using a `newRangeDelIter` closure. This
closure was returning `nil` if an sstable did not contain a range
tombstones. Unfortunately, this interacted badly with
`levelIter.loadFile` which had an odd contional to assume that return a
`nil` iterator and a `nil` error indicated some sort of "end of
iteration" indication. This was completely bogus. The interaction of
these two problems was droppage of range tombstones during a compaction
whenever an sstable contained a range tombstone and an earlier sstable
in the same level that was part of the compaction did not …
=> db: never return a nil iterator on success from newRangeDelIter

table_cache.go
We were closing the `tableCacheNode.loaded` channel on error before
removing the `tableCacheNode` from the map, causing a race which allowed
the error to be reported and a subsequent operation to find the error
before the node was actually removed.
Fixes #469
=> db: deflake TestTableCacheRetryAfterFailure

internal/metamorphic/meta_test.go, internal/metamorphic/options.go
When running the `TestMeta` with `-count > 1`, it is nice to exit on the
first failure rather than continuing.
Remove some redundant options from `standardOptions()`.
=> internal/metamorphic: exit on the first failure

compaction.go, compaction_test.go, range_del_test.go, testdata/manual_compaction
Fix the generation of the sstable's smallest boundary key when that key
comes from a range tombstone. This is necessary, otherwise the smallest
key metadata for an sstable can be "larger" than the first range
tombstone stored in a file which mucks up handling of range tombstones
during iteration.
=> db: fix sstable smallest boundary generation

compaction.go
Verify that the start key of the smallest range tombstone in a
compaction output is greater than or equal to the largest key in the
previous sstable output by the compaction. This is guaranteed by
`rangedel.Fragmenter.FlushTo()` truncating any remaining tombstones to
the end key of the previous sstable.
=> db: add a compaction invariant check

internal/rangedel/seek.go, internal/rangedel/seek_test.go, internal/rangedel/testdata/seek
Fix a bug in `SeekLE` where it was returning the oldest tombstone rather
than the newest visible tombstone. The problem scenario involved 4
tombstones:
```
5: a-c
3: a-c
1: a-c
5:   c-e
```
A call to `SeekLE("c", 4)` was returning the tombstone `a-c#1` rather
than the correct tombstone `a-c#3`. The problem was that the tombstone
`c-e#5` contains the search key, but none of the versions of that
fragment are visible and the code was naively returning the immediately
preceding tombstone.
Removed an invariant that `Seek{GE,LE}` leave the iterator positioned at
the returned tombstone. This wasn't being used anywhere, and resulted in
some confusing code in `SeekLE`. While this invariant falls out
naturally in `SeekGE`, it seems useful for consistency for neither
`SeekGE` or `SeekLE` to provide …
=> internal/rangedel: fix SeekLE returning incorrect tombstone

sstable/block.go, sstable/reader.go, sstable/reader_test.go, sstable/testdata/reader/iter
Fix a bug introduced by the change to skip over empty data blocks. We
were failing to invalidate the data block appropriately when we iterated
off the end of the sstable.
=> sstable: fix a bug with iterator "wrap around" on next/prev

tool/sstable.go, tool/testdata/sstable_scan
Add a `--filter` flag to the `sstable scan` command. When specified, the
filter restrict the records that are output to those with matching keys,
or range tombstones which contain the filter key. The `--filter` flag
also puts the output into filter-mode which prefixes the name of the
sstable the matching record was found in on the output line.
Note that `--filter` is similar to specifying `--start` and `--end`,
though more convient for many use cases where all we wish to know is the
records overlapping a particular key.
See #384
=> tool: add sstable scan --filter flag

internal/metamorphic/meta_test.go
Previously, `--{keep,disk}` were only having an effect when `--run-dir`
was specified. Now they are always properly passed through to the
sub-test.
Also made `--keep` have an effect when `--disk` is not specified and the
test passes.
=> internal/metamorphic: properly pass --{keep,disk} to subtest

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, data_test.go, db.go, ingest.go, iterator_test.go, open.go, options.go, options_test.go, range_del_test.go, testdata/compaction_picker_target_level, testdata/manual_compaction, version_set.go
compactionPicker is now an interface since it makes it cleaner to
try different implementation heuristics. The implementation of
this interface, compactionPickerByScore, is a trivial extension
of the current implementation.
=> db: add support for concurrent compactions.

compaction_test.go, ingest_test.go, iterator.go, sstable/reader_test.go, sstable/table_test.go, table_cache.go, table_cache_test.go, testdata/event_listener, version_set.go, vfs/mem_fs.go, vfs/testdata/vfs, vfs/vfs_test.go
Windows disallows removing open files. In order to catch these case,
`memFS` has been changed to have those same semantics. The two
problematic places in non-test were a failure to close the previous
manifest on rollover, and the asynchronous closing of sstables when they
are evicted from the table cache due to being obsolete.
Fixes #477
=> db: fix cases where we were removing still open files

iterator.go
`Iterator.SeekPrefixGE` was failing to notice that it the prefix no longer
matched when it was stuck in a swath of tombstones. This significantly
affected performance of some workloads, such as `ycsb/F`, causing
performance of various `MVCCGet` calls (in particular from
`EndTxn`) to take longer and longer over time.
```
name            old ops/sec  new ops/sec  delta 
ycsb/F/nodes=3   6.30k ±16%  9.46k ±14%  +50.16%  (p=0.000 n=18+19)
name            old p95      new p95      delta 
ycsb/F/nodes=3    33.7 ±28%    18.6 ± 7%  -44.66%  (p=0.000 n=18+18)
name            old p99      new p99      delta
ycsb/F/nodes=3    78.1 ±40%    49.5 ±44%  -36.55%  (p=0.000 n=18+19)
```
=> db: fix Iterator.SeekPrefixGE+tombstone perf problem

merging_iter.go
Cache the result of any `rangedel.Seek{GE,LE}` call in
`mergingIterLevel.tombstone`. Previously this wasn't done in
`mergingIter.seek{GE,LT}` which was confusing but not a bug because the
range-del-iters are initialized for all levels up to the top item in the
heap in `mergingIter.init{Min,Max}RangeDelIters`.
Fixes #458
=> db: always cache tombstones in mergingIter

data_test.go, event_listener_test.go, ingest.go, ingest_test.go, internal/metamorphic/ops.go, range_del_test.go
Change `DB.Ingest` to match the RocksDB semantics when `move_files` is
specified: the source files are deleted on success.
Fixes #492
=> db: change DB.Ingest to delete source files on success

ingest.go, ingest_test.go, testdata/ingest, testdata/iterator_next_prev, testdata/manual_compaction
Change the `ingestTargetLevel()` heuristics to be closer to RocksDB. If
we can't find a level below L0 to ingest into, ingest into L0 rather
than opening a new level. The primary behavior tended to quickly explode
the number of levels in the LSM which the system was then very slow to
recover from.
=> db: tweak ingestTargetLevel heuristics

tool/manifest.go, tool/testdata/manifest_dump, version_set.go, version_set_test.go
This was caused by the snapshot VersionEdit not containing minUnflushedLogNum and the nextFileNum.
Also print the nextFileNum in the "manifest dump".
Found using the extension to the metamorphic test that closes and reopens the DB.
=> db: fix an incomplete manifest file error when reopening a db

open.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener
Found with a verbose version of mem_fs.go and the db-restarting
metamorphic test. This did not cause the test to fail.
=> db: sync the OPTIONS file

level_iter.go, level_iter_test.go
The `levelIter` invariants were disabled due to a `mergingIter` bug that
had been fixed. We still need a mechanism to disable the invariants for
certain `levelIter` tests which intentionally violate them.
=> db: (re-)enable levelIter invariants

compaction_test.go, ingest.go
The combination of `MemFS+Ingest+DebugCheck` causes awkwardness for the
caller. Disable hard links when this explicit combination occurs, and
copy ingested sstables instead.
Fixes #495
=> db: disable problematic use of hard links in Ingest

compaction.go, compaction_test.go, testdata/compaction_inuse_key_ranges
The previous implementation of `compaction.elideTombstone` was grossly
inefficient. This method is called frequently during compaction to
determine if a tombstone possibly covers a key at a lower level. The
previous implementation walked over all of the file metadata at lower
levels which made this method increasingly inefficient as the size of
the LSM grew. RocksDB optimizes this method by keeping a per-level index
and restarting the search at each level using the index. We take a
slightly different approach: we construct a flattened slice of disjoint
key ranges that are covered by sstables at lower levels.
Fixes #497
=> db: optimize compaction.elideTombstone

sstable/block.go, sstable/reader_test.go, sstable/writer.go, sstable/writer_test.go
* sstable: encode varints directly into buf in blockWriter.store
* sstable: micro-optimize Writer.addPoint()
* sstable: minor cleanup of Writer/blockWriter
* sstable: micro-optimize blockWriter.store
Combined, the optimizations result in a decent improvement on the new
`sstable.Writer` benchmark.
```
name       old time/op  new time/op  delta
Writer-16  94.9ms ± 1%  74.6ms ± 4%  -21.40%  (p=0.000 n=10+20)
```
=> sstable: sstable.Writer optimizations

cmd/pebble/main.go
The `maxOpsPerSec` was being initialized in a loop, making only the last
declaration (for the `ycsb` command) effective.
Fixes #509
=> cmd/pebble: fix --rate flag

cmd/pebble/main.go, internal/arenaskl/skl_test.go, internal/base/internal.go, internal/base/internal_test.go, sstable/block_test.go
Inside skiplist and block iterator we've self-inlined
`base.DecodeInternalKey` for performance and because
Go runtime doesn't inline itself.
However, the inlined versions differ from the actual
method in their handling of insufficient trailer bytes.
This change makes them consistent.
Resolves: #401
=> db: consistently handle key decoding failure

batch.go, compaction.go, db.go, ingest.go, ingest_test.go, mem_table.go
When a memtable (or large batch) is queued for flushing, it is not
necessarily automatically flushed due to the heuristic in
`DB.maybeScheduleFlush` which avoids flushing a small memtable. If
ingestion encounters such a queued memtable, it needs to force the
flushing to occur. Most of the mechanism for doing so already existed
via the `flushable.manualFlush()` method. That has now been renamed to
`flushable.forcedFlush()`.
See cockroachdb/cockroach#44631
=> db: force flushing of overlapping queued memtables during ingestion

batch.go, checkpoint.go, commit_test.go, compaction.go, data_test.go, db.go, get_iter_test.go, ingest_test.go, mem_table.go, mem_table_test.go, open.go
Track the seqnum at which a memtable was created. This is necessary for
correctness when picking sstables for intra-L0
compactions. Additionally, this allowed addressing a long standing TODO
to avoid reading from memtables that are newer than the snapshot being
read at.
=> db: add memTable.logSeqNum

db.go, mem_table.go
Fix an innocuous race. `memTable.logSize` is updated when we're
switching a memtable from being mutable to immutable, yet that field is
read but not used on the read path (in
`DB.{get,newIter}Internal`). Switch to updating and reading the field
atomically. I have an idea for a better long term solution, but this
will suffice in the very short term.
=> db: fix an innocuous race in reading/updating memTable.logSize

internal/arenaskl/arena.go, internal/arenaskl/arena_test.go, internal/arenaskl/skl_test.go, mem_table.go
Remove the unused `extValueThreshold` parameter to `NewArena`. This was
leftover detritus from a time when large values were stored outside of
the `Arena`. This proved to be too slow, and the facility was
removed. Large values (e.g. batches) are now handled by placing them
directly in the list of immutable memtables.
=> internal/arenaskl: remove extValueThreshold detritus

batch.go, checkpoint.go, compaction.go, compaction_test.go, data_test.go, db.go, db_test.go, flushable.go, get_iter.go, ingest.go, mem_table.go, open.go, read_state.go
Extract some common fields from the `flushable` interface into a
`flushableEntry` struct. This struct wraps around a `flushable` and
provides additional metadata that is common to all flushable
implementations, such as `log{Num,Size,SeqNum}`, the `flushed` channel,
and the `flushForced` bit. In addition to removing duplicate code, this
also made it more natural to access individual fields.
=> db: add flushableEntry which wraps a flushable

data_test.go, ingest.go, ingest_test.go, testdata/event_listener, testdata/ingest, testdata/ingest_memtable_overlaps, testdata/ingest_target_level
Ingesting into the lowest possible level while obeying Pebble's
constraints is desirable to reduce write amplification.
Currently to find the target level we stop our search on the level
whose ssts overlap with the ingested file based on the key range covered
by their sst boundaries.
However, we can go further down if there's no actual overlap with the
point and range delete keys of the ssts in a level. This is also what RocksDB
does in it's ingestion logic (see Version::OverlapWithLevelIterator).
Resolves: #221
=> db: better ingestion heuristic

db.go, db_test.go, mem_table.go, open.go, open_test.go, version_set.go
The addition of `memTable.logSeqNum` broke WAL replay in read-only mode
because we were initializing `memTable.logSeqNum` too early and setting
it to the visible sequence number rather than the first sequence number
in the WAL being replayed. This would result in an error during `Open`
that looked like:
```
pebble: batch seqnum 2 is less than memtable creation seqnum 3
```
=> db: fix WAL replay in read-only mode

.travis.yml, db_test.go, docs/memory.md, internal/cache/alloc.go, internal/cache/alloc_test.go, internal/cache/clockpro.go, internal/cache/clockpro_test.go, internal/cache/entry.go, internal/cache/entry_invariants.go, internal/cache/entry_normal.go, internal/cache/robin_hood.go, internal/cache/robin_hood_test.go, internal/cache/value.go, internal/cache/value_invariants.go, internal/cache/value_normal.go, internal/cache/value_notracing.go, internal/cache/value_tracing.go, internal/manual/manual.go, internal/manual/manual_32bit.go, internal/manual/manual_64bit.go, internal/manual/manual_nocgo.go, sstable/block.go, sstable/data_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/writer_test.go, testdata/event_listener, testdata/metrics
Use C malloc/free for the bulk of cache allocations. This required
elevating `cache.Value` to a public citizen of the cache package. A
distinction is made between manually managed memory and automatically
managed memory. Weak handles can only be made from values stored in
automatically managed memory. Note that weak handles are only used for
the index, filter, and range-del blocks, so the number of weak handles
is O(num-tables).
A finalizer is set on `*allocCache` and `*Cache` in order to ensure that
any outstanding manually allocated memory is released when these objects
are collected.
When `invariants` are enabled, finalizers are also set on `*Value` and
sstable iterators to ensure that we're not leaking manually managed
memory.
Fixes #11
=> internal/cache: move the bulk of allocations off the Go heap

sstable/properties.go
`reflect.Value.IsZero` arrived with go1.13, but CockroachDB still
verifies that the source is buildable using go1.12 (even though it
creates binaries using go1.13). Remove this go1.13-ism temporarily.
=> sstable: avoid use of reflect.Value.IsZero

compaction_picker.go, testdata/compaction_picker_target_level
Enhance `conflictsWithInProgress` to prevent concurrent compactions to
the same output level even if the compactions have different input
levels. The scenario seen in the wild was a compaction from L0->L5 and
then a concurrent compaction from L4->L5. Both compactions targeted the
same sstables: boom! There are several possibilities for how both
compactions could target the same sstables. The L0 sstable may not have
overlapped with any of the L4 sstables. When the L4 sstable was
compacted we expanded the inputs to include the same L5 sstable. This
could also occur due to the new ingestion target-level heuristic which
allows ingestion below L0 even if there is sstable overlap if there is
no key overlap.
We'll be able to allow concurrent compactions to the same output level
in the future …
=> db: prevent concurrent compactions to same output level

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, get_iter.go, get_iter_test.go, ingest.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go, level_checker.go, level_checker_test.go, level_iter.go, level_iter_test.go, merging_iter_test.go, tool/find.go, tool/make_incorrect_manifests.go, tool/manifest.go
Change type of `Version.Files` to be slices of `*FileMetadata` rather than
`FileMetadata`. This fixes a few places where we were escaping local
variables to the heap, and will bring consistency for the level 
representation when L0 sublevels are introduced.
The number of allocations should be unchanged. While every
`*FileMetadata` is now allocated individually, we were previously 
allocating `FileMetadata.refs` individually. This may be a win on 
performance for very large numbers of files because
`BulkVersionEdit.Apply` now only moves pointers (8 bytes) instead of
`FileMetadata` (112 bytes).
=> internal/manifest: change type of Version.Files

cmd/pebble/db.go, compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, internal/manifest/version.go, table_cache.go, testdata/compaction_picker_intra_L0, testdata/compaction_picker_target_level
Intra-L0 compactions are compactions from L0 to L0. They reduce read
amplification in scenarios where L0->Lbase compactions cannot keep
up. One such scenario is the `sysbench/otlp_update_index` benchmark
which is an update heavy workload.
Intra-L0 compactions are only scheduled when an existing L0->Lbase
compaction is already running. We copy the RocksDB heuristics which
require the compaction to involve a minimum of 4 L0 files, and to only
perform an intra-L0 compaction if the number of L0 files exceeds
`L0CompationThreshold+2`. Additionally, we copy the RocksDB heuristic
for determination of which files to include. Specifically, we keep on
adding files to the compaction as long as the average file size keeps
increasing. There isn't much commentary in RocksDB on what this
heuristic is …
=> db: add support for intra-L0 compactions

batch.go, batch_test.go, cache.go, data_test.go, db.go, db_test.go, internal/cache/clockpro.go, internal/cache/value_invariants.go, internal/metamorphic/ops.go, open_test.go, range_del_test.go, snapshot.go, snapshot_test.go, version_set_test.go
Fix `DB.Get` to make a copy of the value rather than returning a pointer
that potentially points into cache memory. The cached memory can get
reclaimed/reused as soon as the `getIter` is closed.
Fixes #537
=> db: fix DB.Get to return non-cache memory

ingest.go, sstable/properties.go, sstable/properties_test.go
Rather than a map from property name to block offset, simply keep track
of which fields were loaded from disk. This removes a significant source
of allocations from the `Properties` struct (one per loaded property).
Note that RocksDB uses something like `ValueOffsets` in order to find
the offset of the `GlobalSeqNum` property on disk and overwrite it
within the sstable during ingestion. This mechanism was later replaced
with storing the `GlobalSeqNum` in the MANIFEST which is significantly
cleaner. Pebble has never supported overwriting the sstable's property
during ingestion.
=> sstable: replace Properties.ValueOffsets with Loaded map

internal/record/log_writer.go, internal/record/log_writer_test.go
If a `LogWriter` is closed while we were waiting for the
min-sync-interval timer to expire, the queued sync requests would never
be processed leading to a blockage of the commit pipeline.
=> internal/record: fix blockage when using min-sync-interval

docs/range_deletions.md, docs/rocksdb.md
The docs around range deletion were inconsistent around whether the
points within the range with the same sequence number as the range
deletion would be deleted. This PR updates the docs to consistently say
that this point would not be included in the range deletion.
=> docs: minor fix to range deletion docs

internal/rangedel/fragmenter_test.go, internal/rangedel/get.go, internal/rangedel/seek.go, internal/rangedel/truncate.go, internal/rangedel/truncate_test.go
The `rangedel.iterator` interface was added before
`base.InternalIterator` came into existence. Now that we have
`base.InternalIterator`, it makes sense to use it.
=> internal/rangedel: replace iterator with base.InternalIterator

compaction.go, compaction_test.go, testdata/manual_flush
This change short-circuits the method to figure out if a range
tombstone should be elided during compaction, if the compaction
is a flush. This is because when the output is to L0, it's possible
for a range tombstone in one memtable to overlap keys in another
memtable in the same level that was flushed earlier (but within
the same compaction).
Will fix https://github.com/cockroachdb/cockroach/issues/45581
when this lands in the cockroach repo.
=> compaction: Don't elide range tombstones when flushing memtables

iterator.go
We were reusing the underlying iterator's value buffer as the
outer iterator's value buffer without copying it, even though
in some cases the underlying buffer would change. In particular,
this was observed to return wrong values when reverse iterating
around the start key of an L6 SSTable.
Found by the MVCC metamorphic tests.
=> iterator: Copy iterValue before Prev() on internal iterator

internal/metamorphic/meta_test.go
This change provides additional information to determine the cause such as #560 on CI.
=> internal/metamorphic: log ops and options when panic

tool/manifest.go, tool/testdata/manifest_dump, tool/util.go
As in title. Comes in handy when investigating ingestions, etc,
where the actual sequence number is in the manifest and not
in the SST's properties.
=> tool: Show smallest/largest sequence numbers for SSTs in manifest

internal/metamorphic/meta_test.go
We have already logged ops and options for #560 but can not reproduce them, so reinforced the log.
=> internal/metamorphic: log history when panic

README.md, log_recycler.go, log_recycler_test.go, open.go
WAL recycling depends on the recycled WAL only containing log records
written with the recyclable record format. Pebble always writes WAL
files with the recyclable record format, but RocksDB only uses that
format if WAL recycling is enabled. If Pebble recycles a RocksDB-written
WAL that doesn't use the recyclable record format, it can leave valid
looking log entries in the tail of the log. A subsequent replay of the
WAL by either Pebble or RocksDB could then replay those already
committed log entries. The most common way this badness would be
detected is by Pebble's L0 consistency checks, though the varieties of
badness here are almost unlimited (deleted records reappearing, written
records being deleted, etc). In order to protect against this, Pebble
now only recycles WAL files that it …
=> db: do not recycle WAL files used for recovery

compaction_picker.go, compaction_picker_test.go, testdata/compaction_picker_target_level
This addresses one case seen in MVCC metamorphic tests where the
manual compactor enqueues a compaction, but before that compaction
is run, a concurrent automatic compaction clears up the start level
and increments the base level, causing a panic in newCompaction.
=> compaction_picker: Skip manual compaction if start level is empty

compaction.go, db_test.go, version_set.go
This fixes one concurrency error in maybeScheduleCompaction(),
that happened if logLock() resulted in the mutex being released and a
concurrent db.Close() was allowed to run successfully. The closing
routine would not wait for any compactions since there are none
scheduled yet, but maybeScheduleCompaction would step in and schedule
one _after_ the close, resulting in a panic.
Discovered by MVCC metamorphic tests in CI:
https://github.com/cockroachdb/cockroach/issues/46366
Fixes #560
=> compaction: Check closed flag after logLock returns

compaction.go, metrics.go, metrics_test.go
Previously Pebble exposed a BytesWritten metric that included
both flush and compaction writes. This change exposes an additional
BytesFlushed metric.
=> metrics: expose bytes flushed metric

error_test.go, ingest_test.go, internal/errorfs/errorfs.go
This change moves the errorFS type within the top-level pebble
package's test files into an internal package. This will allow
the metamorphic tests to use the errorfs to inject errors into
filesystem operations as part of #438.
It also introduces an interface so that metamorphic tests can
use a probability instead of a fixed index.
=> internal/errorfs: move to new package

db.go
The Close documentation states that Close may be called multiple times,
but Close deliberately panics if the DB has already been marked as
closed.
=> db: document that Close may not be called twice

compaction.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/record/log_writer.go, level_checker.go, open.go, sstable/table.go, version_set.go
Go 1.13 introduced a new format string verb `%w`. This verb is used
with fmt.Errorf to wrap the old error, avoiding erasing the original
error when adding context.
This will be useful for #438, allowing us to retry only injected
errors by checking the root error through `errors.Is`.
https://blog.golang.org/go1.13-errors
=> *: use Go 1.13 error wrapping

compaction.go, compaction_test.go, ingest.go, ingest_test.go, internal/metamorphic/test.go, open.go, options.go, range_del_test.go, read_state.go
Previously, pebble.Options had a boolean DebugCheck field that when
set to true caused Pebble to run `(*DB).CheckLevels` when a new version
was installed. This commit refactors that Options field to be a function
of the signature `func(*DB) error`, allowing custom functions to be
called instead. In addition a `DebugCheckLevels` function with the
matching signature is exposed so the existing use is still ergonomic
for callers.
This was motivated by #438. When injecting errors into filesystem
operations, CheckLevels may fail with an injected error. With this
change, the metamorphic tests can provide a custom DebugCheck function
that wraps `DebugCheckLevels` with a retry loop for injected errors.
=> db: modify Options.DebugCheck to be a function

filenames_test.go, internal/lint/lint_test.go, internal/metamorphic/ops.go, internal/record/record_test.go, sstable/data_test.go, sstable/table_test.go, sstable/writer_fixture_test.go
Prevent usage of the stdlib "errors" package and of `fmt.Errorf`. We now 
require the usage of the functions in `github.com/cockroachdb/errors`.
=> internal/lint: prohibit usage of "errors" and fmt.Errorf

sstable/block.go, sstable/reader.go
The err field of blockIter was never assigned. Remove it and all the
unnecessary reads from it.
=> sstable: remove unused blockIter.err

compaction_test.go, ingest.go, internal/errorfs/errorfs.go, level_checker_test.go, level_iter_test.go, merging_iter_test.go, sstable/data_test.go, sstable/reader.go, sstable/reader_test.go, sstable/table_test.go, sstable/writer_test.go, table_cache.go, tool/find.go, tool/sstable.go
Add an error return value to `NewIter` and `NewCompactionIter`. If either of
these functions error, they guarantee they clean up after themselves
and return `nil, err`.
Also, remove `Init` from the `sstable.Iterator` interface because it's unused
outside of the sstable package.
=> sstable: add error return value to NewIter, NewCompactionIter

iterator.go
A *pebble.Iterator's Close method must be called once. Additional calls
to Close result in undefined behavior because the Iterator is zeroed
out and returned to a sync.Pool for reuse.
=> db: fix Iterator.Close documentation

batch.go, db.go, error_test.go, internal/base/iterator.go, iterator.go, level_iter.go, merging_iter.go, sstable/reader.go
This change updates iterator (internal and external) error handling such
that errors are cleared before performing absolute positioning
operations (SeekGE, SeekLT, First, Last, etc). Relative positioning
operations (Next, Prev) are unchanged and return immediately if the
iterator has accumulated an error.
Additionally, if an error occurs while creating a new *pebble.Iterator,
the iterator's resources are immediately cleaned up and a
*pebble.Iterator that will always error is returned.
=> db: clear iter err before absolute positioning

db.go, ingest.go, ingest_test.go, internal/errorfs/errorfs.go, internal/record/log_writer.go
Previously, if `ingestTargetLevel` returned an error, Ingest would
return without unlocking the manifest. Any future updates to the
manifest would block indefinitely.
This commit also includes a few additional small fixes that fell out of
the TestIngestError unit test.
* check unchecked iterator Errors in a couple locations within ingestLoad1
* nil out a record.LogWriter's Closer once it's Close method has been
called. This prevents a panic from a double Close of the underlying
file.
=> db: unlock manifest on ingest error

internal/errorfs/errorfs.go, internal/metamorphic/meta_test.go, internal/metamorphic/ops.go, internal/metamorphic/retryable.go, internal/metamorphic/test.go, vfs/vfs.go
Add  an -error-rate flag to the metamorphic tests to inject errors
into read operations at the provided rate.
=> internal/metamorphic: add error rate

sstable/reader.go, sstable/reader_test.go
If an error occurred while estimating disk usage on a sstable with a
partitioned index, the two cache handles of the bottom-tier index blocks
were leaked.
=> sstable: unref cache handle on error in EstimateDiskUsage

internal/record/record.go, internal/record/record_test.go
When a record spans blocks in the WAL it is broken into chunks. We were
erroneously returning a truncated record if a non-first chunk for a
record was at the tail end of the WAL.
Fixes #620
=> internal/record: don't return partial records (again)

compaction_iter.go, db_test.go, internal/base/merger.go, iterator.go, level_checker.go, level_checker_test.go
This PR adds the `io.Closer` return value to the `ValueMerger.Finish` method to allow returned merge results to be recycled once its not used anymore by the iterators. See #617.
@petermattis I'm not sure how I can test this during a compaction, is there a way to facilitate the conditions needed?
=> Recyclable Merger Result

internal/metamorphic/options.go, options.go, options_test.go
Add `ParseHooks.NewCache` to allow configuration of whether
`Options.Parse` creates a cache or not. This fixes a bug in the `db
{scan,lsm,check}` tools which were leaving a dangling cache reference
because `Options.Parse` was creating a cache they weren't expecting.
=> db: add ParseHooks.NewCache

bloom/bloom.go, bloom/bloom_test.go
The `hash()` function was producing different results from RocksDB's
`BloomHash()` function when one of the trailing bytes had the high-bit
set. The LevelDB code from which `hash()` was adapted was not explicit
on its handling of these bytes, relying on the C compiler to have signed
characters. This was likely overlooked in the translation to Go for
which the `byte` type is unsigned.
The incompatible bloom hash functions meant that Pebble would sometimes
fail to find a record written by RocksDB.
Fixes github.com/cockroachdb/cockroach#47406
=> bloom: fix hash() to be compatible with RocksDB

bloom/bloom.go, bloom/bloom_test.go, internal/metamorphic/options.go, options.go, options_test.go
* bloom: fix hash() to be compatible with RocksDB
* db: add ParseHooks.NewCache
=> [release-20.1] backports

tool/sstable.go, tool/testdata/sstable_properties
Fixes a nil panic if sstable.NewReader errored in a few sstable tool
commands.
=> tool: fix sstable panic

tool/db.go, tool/sstable.go, tool/testdata/db_properties, tool/testdata/sstable_properties
Add an 'aggprops' db subcommand that reads properties from all SSTables
across all levels and prints aggregates of them per-level and overall.
I needed this for getting a sense of the RANGEDEL distribution across
levels but thought it might be useful more generally as well.
=> tool: add db properties subcommand

sstable/reader.go, tool/sstable.go
Enhance `sstable check` to verify that every key in an sstable can be
found using `SeekPrefixGE` when a split function is defined for the
comparer.
=> tool: enhance `sstable check` to catch bloom filter problems

compaction.go, compaction_test.go, ingest.go, internal/base/comparer.go, internal/base/internal.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/rangedel/tombstone.go, level_checker.go, level_checker_test.go, merging_iter_test.go, sstable/writer.go, tool/data_test.go, tool/db.go, tool/find.go, tool/lsm.go, tool/manifest.go, tool/sstable.go, tool/testdata/find, tool/testdata/sstable_layout, tool/testdata/sstable_scan, tool/testdata/wal_dump, tool/util.go, tool/wal.go, version_set.go
Rename `tool.formatter` to `tool.keyFormatter` and add
`tool.valueFormatter`. This allowed plumbing through the use of
`Comparer.FormatValue` throughout the tool commands.
Fixes #630
=> *: introduce Comparer.FormatValue

internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels, internal/manifest/version.go
This change introduces L0SubLevels, a data structure to encaptulate
all information to compute L0 Sublevels, flush split keys, and
base / intra-L0 compactions. This data structure will be generated
every time there's a file addition/deletion in L0, the integration
bits will come in future PRs.
The methods to pick base / intra-L0 compactions will come in a
separate PR.
Captures some of the largest code pieces of #563, and effectively
replaces a part of that PR. Sumeer wrote the bulk of this code as
part of his prototype, so thanks Sumeer for his work.
Most of these functions are dead code at the moment, only invoked
by the provided datadriven and non-datadriven tests.
=> internal/manifest: Introduce L0SubLevels data structure

internal/manifest/l0_sublevels.go
Merging #614 and #635 in quick succession broke the master build.
This change updates L0SubLevels with the type rename.
=> internal/manifest: Fix merge skew with Formatter -> FormatKey change

compaction.go, options.go, sstable/options.go, sstable/table_test.go, sstable/writer.go
This change updates sstable.Writer to check if a TablePropertyCollector
exposes a NeedCompact method. If it does and it returns true, mark the
resulting file as requiring compaction. This mirrors RocksDB and
prepares for cockroachdb/cockroach#47763.
I avoided adding the NeedCompact method to the TablePropertyCollector
interface so that clients with existing TablePropertyCollectors don't
need to be updated for a change that should be temporary. A compaction
heuristic that appropriately values compacting range deletions should
obviate the need for this explicit compaction trigger.
=> sstable: support NeedCompact method for property collectors

internal/metamorphic/meta_test.go
If a metamorphic test fails when comparing histories, print the options
and operations of the test alongside the history diff.
=> internal/metamorphic: print options, ops on comparison failures

internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels
This change adds methods to L0SubLevels to help pick, score,
and generate L0 -> LBase, and L0 -> L0 compactions, based on
information captured in the data structure about L0 sublevels.
Also adds associated datadriven unit tests, and a benchmark.
Covers a large part of #563. Thanks Sumeer for his work, most of
this was written by him.
First commit is #614 , which this PR builds on top of.
=> internal/manifest: Add L0SubLevels methods to pick compactions

internal/arenaskl/skl.go
Fix a lint warning about an unnecessary variable and a lint warning
about unsigned comparison always being true. The latter could have
caused real problems for a corrupted memtable.
=> internal/arenaskl: small lint warning fixes

internal/manual/manual.go, internal/manual/manual.s
Rather than returning a nil slice, panic with "out of memory" on
allocation failure in order to provide a clearer signal that allocation
has failed. The "out of memory" message matches the message the Go
runtime uses.
Fixes #652.
=> internal/manual: panic with "out of memory" on allocation failure

tool/manifest.go, tool/testdata/manifest_dump
This change updates the manifest commands that output an LSM
structure to also show L0 sublevels if they exist.
=> tool: Show sublevels at the end of manifest dump

cmd/pebble/compact.go, cmd/pebble/compact_new.go, cmd/pebble/main.go, cmd/pebble/mvcc.go
Add a compactbench command that runs write-only workloads for
evaluating changes to compaction heuristics.
A compactbench workload is created by first running load against a
Pebble instance configured with the pebble.ArchiveCleaner. Next the
`compactbench create-workload` subcommand reads the pebble instance's
archive gathering sstable creation and deletion entries from manifests
and rewriting sstables to remove duplicate keys and zero sequence
numbers. It writes the sstable history and modified sstables to a new
directory representing the workload.
A change to a compaction heuristic can be evaluated by compiling the
compactbench command with the change and running `compactbench run`
passing the path to the prepared workload. The `run` subcommand ingests
sstables from the workload, …
=> cmd/pebble: add bench compact subcommands

cmd/pebble/main.go, tool/data_test.go, tool/find.go, tool/testdata/wal_dump, tool/tool.go, tool/wal.go
Some tools such as the WAL inspection tool are unable to infer
the appropriate comparer. For these tools, allow configuring a default
comparer.
Additionally, convert the Register{Comparer|Filter|Merger} methods into
options passed into New. These are always configured at tool
instantiation and providing them upfront ensures that the `find` tool can
print the true default comparer for its `--comparer` flag in its help
output.
I assumed it's okay to break the interface for the tool package?
Fix #638.
=> tool: use Option pattern, add DefaultComparer option

cmd/pebble/compact_new.go
The first record of a manifest establishes the current version's file
set. Previously, the `bench compact new` subcommand would interpret the
first record of a manifest as an addition of new files from a flush or
ingest because the version edit contained exclusively additions.
This meant that `pebble bench compact new` would add files twice if a
store had created multiple MANIFESTs, and running the benchmark
would fail when attempting to ingest an already-ingested sstable.
=> cmd/pebble: skip first manifest record in `bench compact new`

internal/manifest/testdata/version_check_consistency, internal/manifest/version.go, internal/manifest/version_test.go, open.go
Add `Version.CheckConsistency` which checks that the files listed in the
version exist and their on-disk sizes match the sizes listed in the
version.
Call `Version.CheckConsistency` during `DB.Open` after loading the
MANIFEST.
Fixes #651
=> internal/manifest: add Version.CheckConsistency

internal/arenaskl/arena.go, internal/arenaskl/arena_test.go, internal/arenaskl/node.go, internal/arenaskl/race_test.go
This commit solves the same problem as #667 but for the arenaskl. A
node allocated at the end of the arena might straddle the edge of the
arena's allocated memory. The Go 1.14 checkptr compile flag (which is
enabled on -race builds) would complain when these boundary nodes were
converted to a `*node`.
=> internal/arenaskl: ensure entire node points to allocated memory

cmd/pebble/compact.go, cmd/pebble/compact_new.go, flush_external.go, internal/private/flush_external.go, internal/replay/replay.go
This PR has two commits. One introduces a private hook for ingesting sstables with nonzero sequence numbers directly into L0. The other adapts cmd/pebble's bench compact commands to use the new hook.
=> cmd/pebble: replay ingests, flushes faithfully

open.go, open_test.go, tool/testdata/db_lsm
Don't create a mutable memtable while replaying read-only mode.
Previously we used d.mu.versions.logSeqNum as the seqnum for the mutable
memtable, but that isn't guaranteed to be less than the sequence number
of any additional logs that we've yet to replay.
See cockroachdb/cockroach#48660.
=> db: don't create mutable memtable in read-only mode

open.go, open_test.go, tool/testdata/db_lsm
20.1 backport of #671.
---
Don't create a mutable memtable while replaying read-only mode.
Previously we used d.mu.versions.logSeqNum as the seqnum for the mutable
memtable, but that isn't guaranteed to be less than the sequence number
of any additional logs that we've yet to replay.
=> crl-release-20.1: db: don't create mutable memtable in read-only mode

db.go, iterator.go, merging_iter.go
* db: avoid an allocation in Iterator
* db: avoid an allocation in mergingIter
=> db: minor iterator allocation optimizations

cmd/pebble/compact.go, commit.go, flush_external.go, internal/private/flush_external.go, internal/replay/replay.go
Previously, the internal/replay package and `pebble bench compact` did
not account for flushes with lower sequence numbers than preceding
ingestions. These flushes are possible when keys accumulate in a
memtable and do not overlap with the ingestion that succeeds them.
This change updates internal/replay to ratchet nextSeqNum up to the
ingested file's original sequence number from when it was ingested in
the reference database. It also updates the external flush logic to only
ratchet and publish sequence numbers when required.
These changes mean that during the course of a replay, keys may appear
at historical sequence numbers. This is okay because the database does
not escape from the replay.DB wrapper which never performs reads. It's
also okay because the replay will converge on a …
=> internal/replay: assign ingested tables correct sequence number

cmd/pebble/badger.go, cmd/pebble/boltdb.go, cmd/pebble/db.go, cmd/pebble/main.go, cmd/pebble/mvcc.go, cmd/pebble/random.go, cmd/pebble/rocksdb.go, cmd/pebble/rocksdb_disabled.go, cmd/pebble/scan.go, cmd/pebble/sync.go, cmd/pebble/test.go, cmd/pebble/ycsb.go, internal/metamorphic/generator_test.go, internal/metamorphic/meta_test.go, internal/randvar/flag.go, internal/randvar/randvar.go, internal/randvar/skewed_latest.go, internal/randvar/skewed_latest_test.go, internal/randvar/uniform.go, internal/randvar/zipf.go, internal/randvar/zipf_test.go, internal/rate/rate.go
* internal/randvar: reduce exclusive locks in randvar
* cmd/pebble: miscellaneous ycsb benchmark improvements
* internal/rate: change Reserve{,N} to return a value
* cmd/pebble: take CPU profiles every 10 seconds
* cmd/pebble: pull in the current CRDB version of MVCC routines
* cmd/pebble: fix badger/boltdb/rocksdb build problems
* cmd/pebble: match CRDB Pebble options
* cmd/pebble: fix reverse scan keys metric
=> cmd/pebble: miscellaneous ycsb benchmark improvements

open.go, table_cache.go, table_cache_test.go
The Clock-PRO cache replacement algorithm avoids ever using an exclusive
lock on access (even a batched/deferred exclusive lock). The common case
for the tableCache is that it is sized so that size-based evictions are
never performed. Avoiding exclusive locks on access performs
significantly better in that common case, removing `tableCacheShard.mu`
as a contention bottleneck.
The impact on `pebble bench ycsb --workload=C` (100% reads) is dramatic:
```
name     old ops/sec  new ops/sec  delta
ycsb/C   617k ± 1%   1346k ± 1%  +118.15%  (p=0.000 n=10+10)
```
The mutex contention profile showed the old table cache spending
significant time with the shard lock exclusively held while "recording
hits":
```
----------------------------------------------------------+-------------
flat  flat% …
```
=> db: replace tableCacheShard LRU with Clock-PRO

internal/manual/manual.s, internal/rawalloc/rawalloc.s
They are no longer needed for `go:linkname` to function, but cause
problems as without additional work they can cause the binary to have
executable stacks.
Fixes #680
=> internal/{manual,rawalloc}: remove empty assembly files

docs/rocksdb.md, internal/cache/clockpro.go, internal/cache/clockpro_test.go, internal/cache/entry.go, sstable/reader.go, testdata/event_listener, testdata/metrics
Weak cache handles were introduced to reduce the overhead of looking up a
block in the cache. For blocks such as sstable index blocks, rather than
looking the block up in the cache, a weak handle would held a reference to
the cache entry. This reference could then be converted to a "strong
handle" and used to retrieve the cache value. Weak handles thus avoided the
sharding locking and the map lookup. But in order to implement weak
handles, additional locking and reference counting was necessary. Cache
entries needed to be reference counted, and the value pointed to be a cache
entry required a `RWMutex`. The overhead of the
`RWMutex` was showing up prominently in CPU profiles of read heavy 
workloads. And thus overhead was mainly coming from the normal
`Cache.Get()` code path, not from the …
=> internal/cache: remove weak cache handles and optimize cache.Delete()

cmd/pebble/ycsb.go
Specifying `update=x` as a custom workload for the `--workload` flag was
failing because the `iWeights` and `weights` slices were sized
incorrectly.
=> cmd/pebble: fix out-of-bounds slice access with custom workload

cmd/pebble/badger.go, cmd/pebble/boltdb.go, cmd/pebble/db.go, cmd/pebble/rocksdb.go, cmd/pebble/ycsb.go
Batches are not released for reuse unless they are closed. This plugs a
significant source of GC pressure in `bench ycsb`.
=> cmd/pebble: close batches after committing them

commit.go, flush_external.go, internal/private/flush_external.go
Update private.RatchetSeqNum to ratchet the visible sequence number too.
Previously, we would use RatchetSeqNum to ratchet the sequence number
before an Ingest, but with 9ff7ba9 the Ingest would spin waiting for a
sequence number to be published that would never be published.
=> internal/private: ratchet visible sequence number too

cmd/pebble/random.go, internal/rate/rate.go, pacer.go, pacer_test.go
Add `Limiter.Delay{,N}` as an alternative to `Limiter.Reserve{,N}` that
is more convenient for mocking (because the internal fields of a
`Reservation` are not exported). This allows using `DelayN` in the
`internalPacer` implementation rather than the timer allocation heavy
`WaitN`.
=> internal/rate: add Limiter.Delay{,N}

compaction_picker.go, compaction_test.go, testdata/compaction_picker_estimated_debt, testdata/event_listener, testdata/metrics, tool/testdata/db_lsm
The previous calculation was assuming multiple L0->Lbase compactions
that would overlap with everything in Lbase. In reality, L0->Lbase
compactions currently will take everything from L0. With L0 sublevels,
L0->Lbase compactions will only overlap with a fraction of Lbase.
Fixed the calculation to not include "move-based" compactions in the
debt. For example, if L0 has data but Lbase is empty, we can move the
sstables directly from L0 to Lbase.
=> db: fix estimated compaction debt calculation

cmd/pebble/compact.go, cmd/pebble/compact_new.go
Use L0 read amplification to set pacing in `pebble bench compact run`,
rather than L0 byte size.
Also, print the actual before and after database sizes alongside the
space amplification.
=> cmd/pebble: use read amp for pacing

tool/db.go, tool/find.go, tool/sstable.go, tool/tool.go
Previously, we were using a cache that lived for the lifetime of
`tool.T`. Now we create a cache in the various tools as needed. This
required sprinkling a few missing `*.Close()` calls in various places.
=> tool: remove use of runtime.SetFinalizer

internal/cache/clockpro.go, internal/cache/robin_hood.go
Only install the `Cache` finalizer, which checks that the cache has been
properly reference counted, when the "race" build tag is *not*
specified. We only specify this finalizer for non-race builds because
there appears to be a bug in the race detectors handling of
finalizers. But we want this finalizer enabled for non-race builds as
mishandling of cache reference counts is a common error (both in Pebble
and CRDB tests).
Only install the `robinHoodMap` finalizer, which checks that the map has
been properly closed, when the "invariants" build tag is specified. This
finalizer has not been catching problems since the initial introduction
of manual memory management, because the lifetime of the `robinHoodMap`
is tied to the `Cache` lifetime.
=> internal/cache: restrict when finalizers are used

README.md
Removing mention of pacing of flushes/compactions as that functionality
is currently disabled.
=> db: remove USE WITH CAUTION warning

cmd/pebble/compact.go, metrics.go
Over the course of a compaction benchmark, sample the database's read
amplification periodically and print a few quantiles at the end. This
change also reformats the final stat output to look like:
```
__elapsed__compacts__w-amp__r-amp(_p50__p95__p99__max_)__space(_____amp__stable___final__average__)
3.00m       153   1.10           2    5    5    5          62279.23    64 G   1.1 M     32 G
```
=> cmd/pebble: sample read amp throughout compaction benchmarks

compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go
This change tweaks the compaction picker interface to expose a getScores
method rather than a getLevelMaxBytes method, so that (*db).Metrics does
not need to duplicate score calculation logic to include
compaction-picking scores.
This was motivated by the change to a min-overlapping ratio heuristic
with compensated sizes. With compensated sizes, accurate scores cannot
be computed with just real level file sizes.
I figured it was okay to expose scores through the interface because
compactionPickerByScore is currently the only non-test implementation
and the concept of 'scores' already leaks through into the Metrics
output.
=> db: use compaction picker's scores directly in Metrics

vfs/mem_fs.go, vfs/testdata/vfs
The standard library's `os.RemoveAll` returns nil if the path does not
exist. Update the in-memory fs implementation to do the same.
=> vfs: return nil from RemoveAll for nonexistent paths

cmd/pebble/compact.go, compaction.go, db.go, get_iter.go, get_iter_test.go, ingest.go, internal/manifest/testdata/version_check_ordering, internal/manifest/version.go, level_checker.go, level_checker_test.go, level_iter.go, level_iter_test.go, merging_iter_test.go, testdata/compaction_check_ordering
This change is in anticipation for #675 (and has an exact copy of the original
two commits from that PR). Basically, it relaxes invariants checked in
`Version.CheckOrdering` and the `level_checker` (used in tests) to account
for cases where sstables can have matching start or end (or both) sequence
numbers. These cases are possible when range tombstones are truncated to
file bounds when flushing.
=> *: Update level_checker and Version.CheckOrdering for flush splits

vfs/mem_fs.go, vfs/testdata/vfs
Update MemFS's RemoveAll implementation to return a nil error when the
parents don't exist. This matches the behavior of os.RemoveAll.
I missed this case in bb2f856b.
=> vfs: return nil from MemFS.RemoveAll if parent doesn't exist

internal/record/log_writer.go, internal/record/record_test.go
Bump LogWriter's pending queue size from 4 to 16. The impact is muted
and not statistically significant with small records but at larger
record sizes the impact is appreciable.
This may help with cockroachdb/cockroach#49750, but I don't think it's
the primary issue. I'm going to try to measure its impact on Cockroach
workloads with roachtests.
```
name                       old time/op    new time/op    delta
RecordWrite/size=8-16        32.7ns ± 5%    32.2ns ± 5%     ~     (p=0.055 n=24+25)
RecordWrite/size=16-16       33.8ns ± 7%    33.6ns ± 5%     ~     (p=0.663 n=23+25)
RecordWrite/size=32-16       36.6ns ± 4%    36.6ns ± 9%     ~     (p=0.755 n=23+24)
RecordWrite/size=64-16       41.5ns ± 5%    41.5ns ±12%     ~     (p=0.890 n=24+24)
RecordWrite/size=256-16      68.2ns ± 5%    67.9ns …
```
=> internal/record: bump LogWriter pending queue size

internal/manual/manual.go, internal/manual/manual.s, internal/rawalloc/rawalloc.s
Rather than returning a nil slice, panic with "out of memory" on allocation
failure in order to provide a clearer signal that allocation has failed.
The "out of memory" message matches the message the Go runtime uses.
Fixes #652.
=> release-20.1: internal/manual: panic with "out of memory" on allocation failure

open.go
If an error occurs during Open, close the tableCache. Previously, this
was unnecessary because we already accounted for unrefing the cache
twice: once for the tableCache and once for the db. Now that the
tableCache may have # shards gorouintes that are spawned by init(), we
need to clean them up too.
This was caught by the goroutine leak detector in
pkg/cli.TestOpenExistingStore test in Cockroach.
=>  db: close tableCache on open error

internal/metamorphic/history.go, internal/metamorphic/history_test.go, internal/metamorphic/meta_test.go, internal/metamorphic/ops.go, internal/metamorphic/test.go, level_iter.go, merging_iter.go, testdata/merging_iter
internal/metamorphic: fail tests on calls to Fatalf
Fail the entire test if Pebble calls Fatalf on its Logger. This matches
the current behavior of errors surfaced through the EventListener.
Also, improve some of the output in failure scenarios to make it easier
to find the root error.
db: fix mergingIter corner case surrounding range tombstones
The metamorphic tests were seeing a failure where a levelIter would seek
beyond the upper bound and return the file's RANGEDEL boundary instead
of nil. A subsequent Prev call would cause the mergingIter to switch to
a max heap. Because the levelIter had returned a RANGEDEL key instead of
a nil key, the mergingIter would try to back the levelIter up through
Prev calls, which triggered the levelIter bounds invariant check.
The symmetric problem …
=> internal/metamorphic: fail tests on calls to Fatalf

compaction_picker.go, testdata/compaction_picker_target_level
Reduce how aggressively concurrent compactions are
triggered. Previously, concurrent compactions were only allowed for
levels with a score >= 1.5, independently of how many concurrent
compactions were already in progress. In write-heavy workloads with
large values, concurrent compactions were occurring too frequently,
starving log writes of disk bandwidth. This commit changes the heuristic
so that the threshold for allowing a concurrent compaction is dependent
on the number of concurrent compactions already in progress using the
formula: 2^num-in-progress-compactions. So the first concurrent
compaction will only be performed if a level has a score >= 2, the next
will be performed only if a level has a score >= 4, etc.
There is still work to be done on large-value handling, but this does …
=> db: tweak the compaction concurrency heuristics

compaction_picker.go, internal/manifest/l0_sublevels.go, internal/manifest/testdata/l0_sublevels
A leftover from an old iteration of the sublevels work: we were
returning an error if two intra-L0 compactions were being scheduled
in parallel. An error wrapper message in compaction_picker was also
incorrectly classifying this as a base compaction error when it
was actually an intra-L0 compaction.
Fixes #739.
=> internal/manifest: Don't error when intra-L0 seed file is compacting

internal/record/record.go, open.go, version_set.go
When coming across an io.EOF error when reading the next 32kb
block in a multi-chunk record during WAL/manifest recovery, we return
an ErrUnexpectedEOF which gets passed through to the Open() caller.
This change updates manifest/WAL recovery code to instead stop recovery
at that point and to ignore the last record, as that record did not
get written to disk completely at the time of the crash.
=> internal/record: Handle ErrUnexpectedEOFs like invalid records

compaction.go, compaction_test.go
Multiple goroutines can be blocked on `DB.mu.cleaner.cond` waiting for
cleaner conditions to change and the conditions being waited for
differ. We need to wake all of the waiters rather than a single one
because one of the waiters may not be able to make progress while
another can. In particular, if a waiter is blocked in
`DB.disableFileDeletions` and another waiter is blocked in
`DB.acquireCleaningTurn`, `DB.releaseCleaningTurn` needs to wake
both. If it wakes only one and the goroutine woken is the one in
`DB.acquireCleaningTurn`, that goroutine will not be able to make
progress because `DB.mu.cleaner.disabled` will be non-zero due to the
goroutine in `DB.disableFileDeletions`.
Fixes #743
=> db: wake all waiters on cleaner.cond on state transitions

internal/record/record.go, open.go, version_set.go
When coming across an io.EOF error when reading the next 32kb
block in a multi-chunk record during WAL/manifest recovery, we return
an ErrUnexpectedEOF which gets passed through to the Open() caller.
This change updates manifest/WAL recovery code to instead stop recovery
at that point and to ignore the last record, as that record did not
get written to disk completely at the time of the crash.
=> release-20.1: internal/record: Handle ErrUnexpectedEOFs like invalid records

compaction.go, compaction_test.go
Multiple goroutines can be blocked on `DB.mu.cleaner.cond` waiting for
cleaner conditions to change and the conditions being waited for
differ. We need to wake all of the waiters rather than a single one
because one of the waiters may not be able to make progress while
another can. In particular, if a waiter is blocked in
`DB.disableFileDeletions` and another waiter is blocked in
`DB.acquireCleaningTurn`, `DB.releaseCleaningTurn` needs to wake
both. If it wakes only one and the goroutine woken is the one in
`DB.acquireCleaningTurn`, that goroutine will not be able to make
progress because `DB.mu.cleaner.disabled` will be non-zero due to the
goroutine in `DB.disableFileDeletions`.
Fixes #743
=> release-20.1: db: wake all waiters on cleaner.cond on state transitions

db.go, snapshot_test.go
Fix a race in NewSnapshot that could cause recently-written keys to be
missing. Previously, NewSnapshot's reading of the current sequence
number and appending to the database's snapshot list was not atomic.
This meant that a concurrent write and flush or compaction might cause
keys at the snapshot number to be dropped. This commit locks d.mu before
reading the current sequence number, which prevents flushes and
compactions from reading d.mu.snapshots before we've updated it.
Also, this commit adds a new test case to exercise this race. The test
case doesn't reliably fail before the fix, but run under `stress` it
fails within the first batch of runs.
Discovered as a part of investigating cockroachdb/cockroach#50182.
=> db: fix race in NewSnapshot

db.go, snapshot_test.go
Backport of #751 for the crl-release-20.1 branch.
=> crl-release-20.1: db: fix race in NewSnapshot

internal/arenaskl/skl.go, internal/fastrand/fastrand.go, internal/fastrand/fastrand_test.go
Currnely, when write in batch, pebble use a rand with mutex to generate random height for skiplist. This is so much slow where write is heavy. In my benchmark,  [`skiplist.randomheight`](https://github.com/cockroachdb/pebble/blob/master/internal/arenaskl/skl.go#L349-L360) costs about 1/3 of time. By replace it with [`runtime.fastrand`](https://golang.org/pkg/runtime/?m=all#fastrand) provided by go runtime, this costs disappears.
When there is little(or none) deleted keys in db, `isNextEntryDeleted` still takes more the 60% of the cpu times. So add a slice to record sub iters that contains deletes can eliminate this cost.
=> db: use lock free rand for skiplist

tool/data/lsm.css, tool/data/lsm.js, tool/lsm.go, tool/lsm_data.go
The bulk of the JS changes were to allow for dynamically
determined heights of levels and number of sublevels,
as well as to effectively redraw sstables and levels when the
"flatten sublevels" checkmark is toggled.
In the process I also found and fixed
a bug where we were not rendering the sstables in the very first
version edit until the slider was moved forward and backward at least
once.
Fixes #661.
=> tool: Enhance lsm visualization to show L0 sublevels

tool/data/lsm.css, tool/data/lsm.js, tool/lsm_data.go
Currently, our css height calculation works on the viewport
height, which is not influenced by content height. This change
dynamically sets the height of the svg element using JS, and
updates the container div to use scrollbars when its child
node overflows.
=> tool: Allow vertical scrolling if visualization overflows

get_iter_test.go, internal/manifest/testdata/version_check_ordering, internal/manifest/version.go, testdata/compaction_check_ordering
20.1 backport of one of the two commits in #715 .
---
This change updates L0 ordering invariants to only check for files
being in a sorted order by largest sequence numbers. This is because
the strictly-increasing seqno check can no longer be done with
flush splits (in cases where the largest sequence number is by
the same split range tombstone). Similarly, the ingestion-related
checks for files having coincident sequence numbers would no longer
work for the same reason.
=> release-20.1: internal/manifest: Relax L0 CheckOrdering invariants for flush splits

level_iter.go, merging_iter.go, testdata/merging_iter
Backport of the mergingIter bug fix from #738 & #744.
=> crl-release-20.1: db: fix mergingIter corner case surrounding range tombstones

batch.go, compaction.go, db.go, flushable.go, open.go, options.go, options_test.go, range_del_test.go
When a range deletion is added to a memtable, set a timer. If the
memtable isn't flushed by the time the timer expires, force a flush to
ensure the range deletions are written to disk and may reclaim disk
space.
For now I put this feature behind an experimental option, thinking that
we may want to remove this feature altogether if delete-only compactions
alleviate the need for it.
https://github.com/cockroachdb/cockroach/pull/50508#pullrequestreview-435962162
=> db: force flush memtables with range deletions after delay

compaction_picker.go, db.go, internal/metamorphic/options.go, options.go, options_test.go, testdata/compaction_picker_target_level
Change the signal used to adjust compaction concurrency from the level
compaction score to L0 read-amp. The level compaction score worked
reasonably for small data sizes, but had the deficiency that the
compaction score tends to decrease over time as the DB size
increases. The level score is based on level size and target level
size. The speed at which this score can change decreases as the level
size gets larger because the input rate of new data is limited. In
contrast, L0 read amp tends to be a reflection of the data input rate
and independent of the DB size (modulo the effect that a larger DB size
tends to have higher write amplification which slows down compacting out
of L0).
The before and after numbers are slightly deceiving as the recent change
to compaction scoring hurt the …
=> db: switch compaction concurrency signal from level score to L0 read-amp

cmd/pebble/db.go
Enable L0-sublevel compactions and flush splits for the `pebble bench`
commands.
=> cmd/pebble: enable L0-sublevel compactions and flush splits

internal/metamorphic/config.go, internal/metamorphic/generator.go, internal/metamorphic/ops.go, internal/metamorphic/parser.go
Add new operations to the metamorphic tests for manual `Compact`, `Flush`
calls and `Checkpoint` calls.
Fix #753.
=> internal/metamorphic: add checkpointOp, compactOp and flushOp

compaction.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels
When the largest key for an LBase file is the range deletion sentinel,
that file does not actually contain that user key. We should
not be tacking on any L0 files into that compaction if they
have versions of that user key.
Fixes #770.
=> compaction: Exclude largest key when extending L0 compactions if it's sentinel

compaction_picker.go, testdata/compaction_picker_L0
Currently, if an intra-L0 compaction ends up being a move
compaction, we would trigger an assertion as the file would
appear to be deleted and added to the same level in the same
version edit.
=> compaction: Don't do a move compaction within L0.

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, data_test.go, db.go, ingest.go
Refactor the `startLevel` and `outputLevel` fields of `compaction` to be
structs, encapsulating the level and input file list. Also, refactor the
inputs field to be a variable-length slice of these new
`compactionLevel` structs. This makes most codepaths more readable,
rather than relying on the implicit knowledge that `inputs[0]` is the
start level and `inputs[1]` is the output level. This will also allow
modeling compactions across more than two levels as a part of the
existing `compaction` struct.
Some codepaths that use `startLevel` and `outputLevel` might be able to
be refactored in terms of only `inputs` and made agnostic to the # of
levels involved in a compaction. I left that for future work.
=> db: refactor compaction startLevel, outputLevel

batch.go, sstable/block.go, sstable/unsafe.go
go1.14 introduced runtime checks in race builds that unsafe pointer
conversions are "safe". One of these checks is to verify that the type
being cast to fits within the available bytes of the source of the
cast. This was being violated in `batchDecodeStr` when the string being
decoded from was smaller than 5 bytes. The use of `*[5]uint8` in
`batchDecodeStr` was a convenience. The exact same code is produced if
we do pointer arithemetic on a `*uint8`, it is just somewhat more
verbose.
=> db: avoid go1.14 unsafe pointer conversion violations

sstable/reader.go, sstable/reader_test.go, tool/testdata/sstable_check
Noticed while investigating github.com/cockroachdb/cockroach#50445 using
`pebble sstable check`. `singleLevelIterator.skip{Forward,Backward}` was
previously ignoring errors when `loadBlock` returned false. Now it does
not.
Took the opportunity to improve the `checksum mismatch` error message.
=> sstable: don't skip over errored blocks during iteration

ingest_test.go, open.go
If a crash occurs during an ingest after linking the files but before
the MANIFEST commit, the ingest links with the new file numbers still
exist on the file system. On Open, Pebble scans the directory
accumulating and then deleting any existing obsolete files. However, if
the Remove call fails for any reason (eg, on Windows if the file is an
ingested sstable pointing to a file that's open elsewhere), Pebble
ignores the error and continues.
Since the MANIFEST was never committed, Pebble could reuse one of these
unremoved sstables' file numbers despite unsuccessfully removing the
file. When Pebble writes to the file, it'll overwrite the external file.
This change updates scanObsoleteFiles to also update the versionSet's
nextFileNum to be greater than any obsolete files. This guarantees …
=> db: bump nextFileNum past obsolete file numbers on Open

ingest_test.go, open.go
=> release-20.1: db: bump nextFileNum past obsolete file numbers on Open

ingest.go, level_checker_test.go, level_iter_test.go, merging_iter_test.go, sstable/reader.go, sstable/writer_test.go, table_cache.go, table_stats.go, table_stats_test.go, testdata/manual_compaction, testdata/table_stats, tool/find.go, tool/sstable.go
Previously, when estimating the size of the data beneath a range
tombstone, the table stats collector was not truncating tombstones to
the bounds of the containing files. This resulted in overinflating the
estimate for fragmented tombstones earlier in the user key space.
=> db: truncate tombstones to file bounds when calculating table stats

Makefile, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels
Currently the interval / sublevel calculation considers all user
keys to be the same, and all sstable start/end boundary user keys to be
contained (i.e. inclusive) in those files. However this is not
true if the end key has a trailer matching the sentinel key,
which happens a lot when we truncate rangedel tombstones
as part of flush splits.
This change updates sublevel generation to treat the sstable
end key as exclusive if it's the sentinel key. Interestingly enough,
all other interval logic is written well enough to "just work", making
this a simpler change than I was expecting.
Also add -test.v as a flag when running stress* with the makefile.
Something changed recently (go 1.14 I think?) that prevents the test
command from printing the number of runs / failures unless this
flag is …
=> internal/manifest: Don't create new sublevel if overlap is on sentinel key

cmd/pebble/db.go, compaction.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels, options.go
Currently, the calculation of flush split bytes does not account
for the "height" of L0 sublevels; as the number of sublevels
increases, flush split keys are emitted closer to one another,
as more bytes are covered between keys close together as more
SSTables overlap. This change updates the flush split calculation
to multiply the passed-in flush split bytes constant with the
sublevel count.
This change also updates the target flush file size to match
that of Lbase-1 as opposed to L0. This seems to perform
better in practice with scan-heavy benchmarks.
First commit is #796
=> internal/manifest: Have flush split bytes account for # of sublevels

cmd/pebble/badger.go, cmd/pebble/boltdb.go, cmd/pebble/db.go, cmd/pebble/rocksdb.go, cmd/pebble/ycsb.go
This change addresses a TODO in cmd/pebble/ycsb around
measuring read-amp of scan operations. This makes measuring
differences in ycsb/E performance easier.
=> cmd: Address TODO on measuring scan read-amp

internal/mkbench/mkbench.go
Trim off trailing whitespace before removing the fixed prefix and
suffix. This fixes an overly strict bit of parsing encountered where a
manual edit of `data.js` caused a trailing newline to be added to the
file.
Don't segfault if the `data` directory does not exist.
=> internal/mkbench: be more permissive in data.js parsing

docs/css/app.css, docs/index.html, docs/js/app.js
Switch to a single column layout when the display is too narrow.
=> docs: nightly benchmarks fixes and tweaks

tool/data/lsm.js, tool/lsm.go, tool/lsm_data.go
This change updates the LSM visualization generator to
only add L0 files to the sublevel field in edits in the
json object if the sublevel changed in that edit. To make
this work, there's a client-side JS change
to iterate back along edits to find the last set sublevel
for each L0 file. This significantly cuts down on JSON parsing time.
Fixes #764.
=> tool: Only encode sublevel changes in lsm json object

internal/metamorphic/generator.go, internal/metamorphic/generator_test.go, internal/metamorphic/meta_test.go, internal/metamorphic/parser_test.go, internal/metamorphic/utils.go
Generate tests operations and random options deterministically from a
pseudorandom number generator seed. On failure, print the seed alondside
the test results.
Add a new `--seed` flag for passing a specific seed, allowing
re-executing a full metamorphic test run on the same SHA from just the
seed.
We may want to augment the seed with a small checksum over the
operations and options to ensure that accidental introduction of outside
randomness or use of a seed on a different SHA doesn't confuse us.
Close #785.
=> internal/metamorphic: generate deterministically from prng seed

compaction_picker.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels, testdata/compaction_picker_L0
This change updates the call to PickBaseCompaction for sublevel
compactions to use a min compaction depth of 1. This allows for
base compactions where we would completely "clear out" L0,
something that was not happening with the previous setup. To
compensate for this change, we account for L0CompactionThreshold
in the L0 score instead, by dividing the existing score with it.
This change also calls p.grow when trying to optionally grow
a compaction. This calls version.Overlaps, which is more
optimistic in picking overlapping L0 files than
extendCandidateToRectangle. This helps in reducing write-amp
in some workloads.
In practice, this seems to work better in read-heavy benchmarks
where sublevel compactions would fail to clear out L0 while
having them disabled would clear out L0 and result …
=> *: Always pick base compactions with minCompactionDepth = 1

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, ingest.go, internal/manifest/level_iterator.go, internal/manifest/version.go, internal/manifest/version_test.go, table_stats.go
Add a FileIterator type to hide the underlying representation of a slice
of a level's files. Switch `(*Version).Overlaps` to return a
`FileIterator`. Some call sites are a little burdensome to convert all
at once, so add a temporary `OverlapsSlice` method that returns the
previous `[]*FileMetadata` return type.
This is in preparation for representing `Version.Files` using a btree.
This might not be the final return type of `(*Version).Overlaps`. I've
experimented with refactors that use a `LevelSlice` type and a
`FileIterator` type that seemed promising but more refined and ergonomic
types can come later.
=> internal/manifest: add FileIterator struct

compaction.go, compaction_picker.go, compaction_test.go, db.go, ingest.go, ingest_test.go, internal/manifest/version.go, table_stats.go, table_stats_test.go, testdata/compaction_delete_only_hints
Implement a new form of compaction that may delete files from any
number of levels without scanning when the files are known to be
completely covered by a range tombstone.
When the table stats collector calculates an estimate of the bytes
covered by a range deletion, it also looks for sstables that are
completely covered by the tombstone. If it finds any, it creates a
'delete compaction hint' with the user key range, the sequence number
range of the tombstones and the lowest sequence number of any of the
covered files.
Whenever considering a new compaction, Pebble checks all existing hints
to see if all of its sequence numbers fall into the same snapshot
stripe. If they do, it constructs a special delete-only compaction
that does not specify an output level and may contain inputs from …
=> db: implement delete-only compactions

event.go
Use the existing `redact.StringWithoutMarkers` in event `Stringer`
implementations and remove `redactSprint`.
Export `LevelInfo.SafeFormat` for consistency.
Refactor `safeFormatInputs` into a type alias over a slice of `LevelInfo`.
Thanks @knz for the suggestions!
=> db: use redact.StringWithoutMarkers

compaction.go, compaction_picker_test.go, compaction_test.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level_iterator.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_test.go, level_checker.go
Update `Version.Levels` to be an array of `LevelMetadata` types, which
for now is just an alias of `[]*FileMetadata`. This allows the
incremental introduction of methods to the `LevelMetadata` struct before
completely obscuring its internals.
Also, update `CheckOrdering`, `(*Version).Pretty`,
`(*Version).DebugString` and `(*Version).CheckConsistency` to use the
`LevelIterator` type to iterate over level metadata.
=> internal/manifest: add LevelMetadata type alias

checkpoint.go, data_test.go, db.go, get_iter.go, table_stats.go, tool/db.go, tool/manifest.go
Convert a handful of various usages of `(*Version).Levels` to use an
iterator rather than ranging over the slice of file metadata.
=> db: use manifest.LevelIterator in additional places

sstable/reader.go, sstable/reader_test.go, sstable/testdata/readahead, table_cache.go, testdata/event_listener, testdata/metrics, vfs/fadvise_generic.go, vfs/fadvise_linux.go, vfs/prefetch_linux.go, vfs/vfs.go
This updates the dynamic readhaead logic in singleLevelIterator
to call fadvise(FADV_SEQUENTIAL) when deviating from a sequential
access pattern seems very unlikely (i.e. when the max readahead
size has been reached).
In practice, this sort of dynamic fadvising() seems
to dramatically speed up TPCC-4k backups from taking 1h on avg
to around 20-25mins. It significantly reduces the number of
read IOPS, and makes the workload more CPU/write IO heavy instead
of being bottlenecked on reads.
=> sstable: Fadvise sequential when max readahead size is reached

sstable/reader.go, sstable/reader_test.go, sstable/testdata/readahead, table_cache.go, testdata/event_listener, testdata/metrics, vfs/fadvise_generic.go, vfs/fadvise_linux.go, vfs/prefetch_linux.go, vfs/vfs.go
20.1 Backport of #817 
---
This updates the dynamic readhaead logic in singleLevelIterator
and sstable.Reader to spin up a new file descriptor with
fadvise(FADV_SEQUENTIAL) called on it, to take advantage of OS
level readahead instead of continuing to use pebble-driven
readahead.
In practice, this reliance on OS-level readahead
to dramatically speed up TPCC-4k full backups from taking 1h on avg
to around 20-25mins. It significantly reduces the number of
read IOPS, and makes the workload more CPU/write IO heavy instead
of being bottlenecked on reads.
=> release-20.1: sstable: Fadvise sequential when max readahead size is reached

compaction.go, db.go, db_test.go, flush_external.go, ingest.go, open.go, snapshot_test.go, table_stats.go
Capture the stack trace of the first call to `Close` in the `ErrClosed`
error that is returned when an operation is performed on a closed DB.
=> db: capture stack trace of closed call for ErrClosed

compaction.go, compaction_picker.go, version_set.go
Replace the remaining uses of `totalSize` with calls to the
`manifest.LevelSlice` type's `SizeSum` method, and delete `totalSize`.
=> db: use LevelSlice.SizeSum where applicable

version_set_test.go
This fixes a dropped test error in the `pebble` package.
=> pebble: fix dropped test error

compaction.go, internal/rangedel/testdata/truncate, internal/rangedel/truncate.go, internal/rangedel/truncate_test.go, table_stats.go
This change updates rangedel.Truncate, which is used to wrap file-specific
range tombstone iterators during compaction, to ignore any range tombstones
outside a file's bounds.
As the non-L0 compaction writing logic
writes untruncated range tombstones on both sides of an SST split
between versions of the same user key (see comments around
fragmenter.FlushTo), it's possible for the compaction mergingIter
to have a rangedel iterator pointing to a range tombstone on the
left-hand side of a split while the same level's point key iterator
has moved onto the right-side file. This could cause a deleted
key in the right-side file to resurface even if it's covered by
a range del tombstone in that same file.
This issue only occurs during
compactions, as non-compaction levelIters manage the …
=> internal/rangedel: Skip range tombstones outside a file's bounds

compaction_test.go, db.go, get_iter_test.go, internal/manifest/version.go, level_checker.go, level_checker_test.go, level_iter_test.go, merging_iter_test.go, version_set.go
In test cases, use a new NewVersion function to construct versions in
tests. Also, update a few additional call sites to use
manifest.LevelIterator.
=> db: use manifest.NewVersion constructor in tests

compaction_picker.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go
Update the `(*manifest.L0Sublevels).PickBaseCompaction` method to take a
LevelSlice rather than a slice of `*FileMetadata`.
=> internal/manifest: take a LevelSlice in L0Sublevels.PickBaseCompaction

ingest.go
This change updates the comment at the function signature of
db.Ingest to highlight that all callers to that method need to
ensure all writes to sstables are synced to disk, to guarantee
durability of ingested data.
Fixes #787.
=> *: Update comment on Ingest() on callers needing to Sync() 

compaction.go, internal/manifest/testdata/version_check_ordering, internal/manifest/version.go, testdata/compaction_check_ordering, testdata/manual_compaction
Previously, during compaction a tombstone that would eventually be
elided could be used to set a grandparent limit equal to the next key, a
tombstone with that same key as its start. This would cause the creation
of a table that starts and ends at the same user key, containing only a
range tombstone. The sstable end boundary would be set to the infinite
sequence number, violating the ordering of sstable boundaries.
=> db: fix tombstone elision, grandparent limit bug

internal/errorfs/errorfs.go, vfs/disk_usage_unix.go, vfs/disk_usage_windows.go, vfs/errors_unix.go, vfs/errors_windows.go, vfs/mem_fs.go, vfs/vfs.go, vfs/vfs_test.go
In future when we want to auto recover from no space errors, we'll need to check for free disk space and recover if it is above a certain threshold. For that purpose, this change adds the OS-specific way of getting the free disk space and also checking if an error is a no space error.
=> vfs: Add FS.GetFreeSpace, IsNoSpaceError

compaction.go, compaction_picker.go, compaction_picker_test.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go
Refactor the `LevelMetadata` type into a struct with its file metadata
slice unexported. This ensures that all usages outside of the manifest
package are agonstic to the in-memory representation of a level's file
metadata.
=> internal/manifest: unexport LevelMetadata files

internal/mkbench/mkbench.go
This picks up an `err` that was being passed into a `filepath.WalkFunc()` but not being handled.
=> internal/mkbench: fix dropped walkfunc error

compaction.go, internal/manifest/testdata/version_check_ordering, internal/manifest/version.go, internal/rangedel/fragmenter.go, testdata/compaction_check_ordering, testdata/manual_compaction
Backport of #809. The patch did not apply cleanly, so it
deserves a critical eye.
=> crl-release-20.1: db: fix tombstone elision, grandparent limit bug

batch.go, internal/rangedel/fragmenter.go, internal/rangedel/fragmenter_test.go, internal/rangedel/seek_test.go, internal/rangedel/testdata/fragmenter, internal/rangedel/testdata/fragmenter_deleted, internal/rangedel/truncate_test.go, level_checker_test.go, level_iter_test.go, mem_table.go, merging_iter_test.go, sstable/data_test.go, sstable/reader.go, sstable/testdata/writer, testdata/event_listener, testdata/metrics
Propagate the `base.FormatKey` type to `rangedel.Fragmenter`, and use it
format keys in the event of a panic. The raw key can cause tools to treat the
log file as a binary file and generally make it more difficult to debug.
Motivated by cockroachdb/cockroach#50963.
=> internal/rangedel: format keys in Fragmenter panics

cmd/pebble/compact.go, compaction.go, data_test.go, flush_external.go, ingest.go, ingest_test.go, metrics.go, metrics_test.go, open.go, testdata/ingest, version_set.go
Previously, level sizes were recomputed from scratch with each new
version. This showed up in CPU profiles of stores with large numbers of
sstables (#718). This change updates logAndApply callers to populate the
passed LevelMetrics' `NumFiles` and `Size` fields with the incremental
diff of each version edit.
=> db: compute file count and size metrics incrementally

internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go, internal/manifest/version_test.go, tool/lsm.go
Refactor the L0 sublevels code to take a `*LevelMetadata` and avoid
direct use of the underlying `[]*FileMetadata`. The L0 sublevel
data structures still build their own `[]*FileMetadata` slices which I
don't intend on changing, but this change will avoid the unnecessary
copying of the entire L0 btree into a slice.
=> internal/manifest: use LevelMetadata in L0 sublevels

options.go
The `(*Options).Parse` function strives to support a nil `*ParseHooks`
argument. There was one place where it would panic if `cache_size` was
specified but `*ParseHooks` was nil.
=> db: handle nil ParseHooks for cache_size option

batch.go, compaction.go, compaction_iter.go, compaction_test.go, ingest.go, internal/base/error.go, internal/manifest/l0_sublevels_test.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/record/record.go, iterator.go, mem_table.go, open.go, sstable/block.go, sstable/raw_block.go, sstable/reader.go, sstable/table.go, testdata/compaction_check_ordering, tool/db.go, tool/manifest.go, version_set.go
For better error handling, we need to classify errors to decide their severity and accordingly handle them. This change marks errors that indicate data corruption in WAL, MANIFEST, sstable. In future when we introduce ErrorHandler, these will be treated as unrecoverable errors.
=> db: mark corruption errors

compaction_test.go, internal/manifest/level_metadata.go
Remove the Collect method from LevelSlice. Enough of the codebase uses
the LevelSlice, LevelIterator and LevelMetadata types that it's no
longer needed.
=> internal/manifest: remove LevelSlice Collect method

batch.go, batch_test.go, db.go
Reset() is called when trying to explicitly reuse an existing Batch, but its applied flag is currently never reset in Reset(). The reused batch will be returned by the pending queue in commitPipeline.publish() in another concurrent commit request before its SeqNum gets set in prepare(). That causes a data race between b.setSeqNum() and b.SeqNum(). 
Another question I have is why fields like Batch.flushable, Batch.tombstones etc. not reset in Reset()?
=> db: clear the applied flag in Batch.Reset()

internal/manifest/btree.go, internal/manifest/btree_test.go
Copy over the B-Tree implementation from Cockroach's
[pkg/util/interval](https://github.com/cockroachdb/cockroach/tree/master/pkg/util/interval) package, stripping its intervals and
go_generics generation.
This PR only adds the B-Tree implementation with minor modifications.
It does not change `LevelMetadata` to use the B-Tree.
=> internal/manifest: add (unused) B-Tree implementation

compaction.go, compaction_picker.go, compaction_test.go, data_test.go, ingest.go, ingest_test.go, internal/manifest/version.go, iterator_test.go, snapshot.go, sstable/properties.go, table_stats.go, testdata/compaction_tombstone_elision_only, testdata/ingest, testdata/manual_compaction, testdata/range_del, testdata/table_stats
Add a new, low-priority compaction type for compacting files in the
bottommost level of the LSM that contain tombstones that may be elided.
If no other compactions are found, the compaction picker scans L6
file metadata looking for files that contain tombstones and whose
sequence numbers fall entirely in the last snapshot stripe. If it finds
one, it creates a new L6 -> L6 compaction with the file's atomic
compaction unit.
See #838
=> db: add elision-only L6 compactions

internal/base/iterator.go, iterator.go, level_iter.go, sstable/block.go, sstable/reader.go
This is a WIP and has the changes for singleLevelIterator.SeekGE.
It requires strengthening the requirement that the user call SeekGE
with a key that respects the lower bound.
The SeqSeek benchmarks are better
```
name                                                 old time/op    new time/op    delta
LevelIterSeqSeekGEWithBounds/restart=16/count=5-16     661ns ± 1%     152ns ± 1%  -76.96%  (p=0.000 n=8+9)
MergingIterSeqSeekGEWithBounds/levelCount=5-16        1.97µs ± 2%    0.72µs ± 2%  -63.37%  (p=0.000 n=9+10)
```
Overall, between this and the preceding PR, the MergingIterSeqSeek
benchmark shows a 5x improvement.
I'd like some feedback before adding SeekLT, SeekPrefixGE, and the
twoLevelIterator changes.
The more complete microbenchmark results comparing with master show
some slowdown, …
=> sstable: optimize seeks to use next

compaction_picker.go
When we call compactionPicker.calculateScores, the scores
returned are sorted by decreasing score, not by level. The
code to handle files with MarkedForCompaction = true
did not take this into account, and ended up pulling the
wrong level's candidateLevelInfo. Unfortunately,
that entire method seems to be untested, so this slipped
past our tests and got caught by a roachtest.
Will fix https://github.com/cockroachdb/cockroach/issues/53121
when this lands in Cockroach.
=> *: Fix level mismatch bug when MarkedForCompaction = true

event.go, options.go, vfs/disk_health.go, vfs/disk_heath_test.go, vfs/syncing_file.go, vfs/syncing_file_linux.go
This change adds a diskHealthChecker struct that stores fields for
logging and reporting slow disk operations using a new EventListener.
The diskHealthChecker is supposed to be instantiated
once-per-file-opened-for-writing, and it's created when a diskHealthCheckingFS
has a file Create()d on it. This FS wraps around vfs.Default when a new Options()
is created. That FS then creates file instances where the write, close, and sync
operations are monitored for slowness.
Having a monitoring goroutine per writer is more efficient than
starting/stopping timers at every disk operation, so the diskHealthChecker
spins up one goroutine in startTicker() to check for any slowness in the
ongoing disk operation.
=> *: Add diskHealthChecking{FS,File}, use it to wrap disk writes 

internal/manifest/btree.go, internal/manifest/btree_test.go
internal/manifest: prohibit overwritten keys in B-Tree
We will be using the B-Tree to organize FileMetadata within a level.
Items will be sorted using the Smallest key for positive-numbered levels
and the tuple of (LargestSeqNum, SmallestSeqNum, FileNum) for L0.
Both of these orderings provide a total ordering of the files within a
level, so an insert of an equal item indicates we're inserting a file's
metadata into a level twice. Treat this as a panic.
internal/manifest: update FileMetadata refcounts within B-Tree
This change updates the B-Tree to increment a file's reference count
when it's first added to a B-Tree node or when a node containing the
file is cloned, and decrement a file's reference count when a containing
B-Tree node is released.
Additionally, rename Reset to Release and …
=> internal/manifest: make small B-Tree adjustments

compaction.go, compaction_test.go, testdata/manual_compaction
Currently, if there is a sequence of consecutive range tombstones,
some of which are elided but not all, we could end up in a scenario
where the last output sstable's end key is significantly earlier
than the last written key to the rangedel fragmenter, and if there's
a grandparent limit in between, that can throw a panic in the fragmenter
when the next output switch happens.
Speculative fix for cockroachdb/cockroach#50963.
=> compaction: Don't set grandparent limit "behind" keys in fragmenter

internal/record/log_writer.go, internal/record/record_test.go, open.go, open_test.go
While closing a LogWriter, write a special EOF record signifying the end
of the log. This EOF record will overwrite trailing garbage from the
recycled log file, allowing us to detect corruption errors in any WALs
earlier than the most recent one.
In Open return an error if any WAL other than the most recent one
encounters an invalid chunk.
Fix #864.
=> internal/record: write an EOF trailer on LogWriter Close

compaction.go, testdata/manual_compaction
This is another piece of fallout from the never-ending saga of
grandparent limits and elided tombstones.
A compaction of two files that only contain range tombstones may elide
all the tombstones up to a grandparent limit. When finishOutput is
called, the conditional introduced in #809 recognizes that the resulting
table has no point tombstones and the limit is equal to the fragmenter's
start key, so it skips creating a table.
However, if the compaction inputs have no more keys, the outer loop
restarts with a nil key and a pending tombstone in the range deletion
fragmenter. Previously, a compaction like this would panic when trying
to set a grandparent limit using a nil key. This updates this condition
to use the rangedel fragmenter start key to find the new grandparent
limit in this case.
=> db: fix nil pointer dereference in compaction

tool/make_test_find_db.go
I think the removed code block does not affect the result because DB.Ingest method deletes source files on success.
=> tool: fix removing same file twice

bloom/bloom_test.go
Adjust the output of `tableFilter.String` to wrap every 8 bytes and to 
output the bits within each byte from high to low (previously it was doing
low to high).
=> bloom: minor test ergonomic adjustments

compaction_iter.go, compaction_iter_test.go, db_test.go, internal/base/merger.go, iterator.go, level_checker.go, level_checker_test.go, testdata/compaction_iter
Add an `includesBase` argument to `ValueMerger.Finish`.  If
`includesBase` is true, the oldest merge operand was part of the
merge. This will always be the true during normal iteration, but may be
false during compaction when only a subset of operands may be
available. Note that `includesBase` is set to true conservatively: a
false value means that we could not definitely determine that the base
merge operand was included.
Fixes #617
Closes #625
=> *: add includesBase argument to ValueMerger.Finish

db.go, error_test.go, internal/errorfs/errorfs.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener
In #871, Open started interpreting any WAL older than the most recent
one more strictly, erroring if it encountered any invalid chunks while
reading the log. This was enabled by a new EOF trailer chunk that's
written when a WAL is closed, ensuring that previous WALs end cleanly
and unambiguously.
However, during a WAL rotation, a crash before the previous WAL was
cleanly closed could leave the previous WAL with recycled garbage at its
tail.
This change updates WAL rotation to close the previous WAL first,
then create/rename the next WAL.
=> db: close previous WAL before linking next WAL

db.go, error_test.go, internal/errorfs/errorfs.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener
=> crl-release-20.2: db: close previous WAL before linking next WAL

compaction.go, compaction_test.go, testdata/compaction_error_on_user_key_overlap
This change updates output finishing logic in compaction.go to ensure
that the flush errors out if different revisions of a user key fall into two
separate sstables. This invariant is already ensured by other compaction
output logic, but it's worthwhile to have an extra sanity check around this
invariant.
=> compaction: Ensure that user keys aren't split across SSTs when flushing

compaction.go, compaction_test.go, testdata/compaction_output_splitters, testdata/manual_compaction
Currently, it's possible for the nonZeroSeqNumSplitter to "withhold"
a compaction split suggestion in such a way that the `limit` variable
in the compaction loop is exceeded, only to advise a compaction split
at a later point.
This is usually not a concern as we just reset `limit`
when that compaction split is actually advised, but if the compaction
were to run out of keys in this narrow window, we would leave the limit
at a non-nil past key, which would violate an invariant in the rangedel
fragmenter as it can't truncate range tombstones to a passed key.
Similar logic already existed in older iteration of this code, which
is in use in the crl-release-20.2 branch. A refactor here introduced
this bug.
This change allows for a 3-way return value from shouldSplitBefore;
in the case where …
=> compaction: Invalidate limit when a splitter defers a split suggestion

compaction.go
Also confirmed by `staticcheck`:
> SA9004: only the first constant in this group has an explicit type (staticcheck)
=> compaction: specify type for compactionKind consts

internal/arenaskl/skl_test.go, internal/base/iterator.go, level_iter_test.go, mem_table_test.go, merging_iter_test.go
Fix the Go `levelIter` and `mergingIter` microbenchmarks to clean up
`*sstable.Readers` before exiting.
Also fix the memtable benchmarks to use an absolute positioning method
before a relative positioning and document this requirement on the
`InternalIterator` interface.
Fix #902.
=> db: fix Go microbenchmarks to clean up correctly

batch.go, batch_test.go
Fix the `SeqNum` and `Reader` methods to handle a zero-value Batch that
has a nil `data` field. Also, fix MakeBatchReader to handle slices
shorter than the batch header.
Fix #909.
=> db: fix a few lazy initializations of Batch data

example_test.go, iterator.go, snapshot.go
Makes a handful of improvements to the godoc documentation:
* Add a suggestion to `SeekPrefixGE`'s comment, directing readers to
iterator bounds for constraining an iterator to a prefix of keys. (Close #907.)
* Fix a spelling mistake in the `(*Snapshot).Close` godoc comment.
* Add the 'hello world' example in the repository README as a compiled
godoc example.
=> db: improve godoc documentation

example_test.go, options.go, options_test.go
Remove `Options.TableFormat` to reduce confusion. Only
`TableFormatRocksDBv2` was supported and there are no plans (or ability) to
support `TableFormatLevelDB`. This was originally added to allow writing
LevelDB format sstables, but that can still be done because
`sstable.Options` is distinct from `pebble.Options`.
Fixes #915
=> db: remove Options.TableFormat

cmd/pebble/compact.go, cmd/pebble/db.go, open.go, options.go
`Options.Min{Flush,Compaction}Rate` have no effect while
`private.enablePacing` is false. So unexport these fields in order to
reduce confusion.
Fixes #911
=> db: unexport Options.Min{Flush,Compaction}Rate

example_test.go, iterator.go
Add an example showing how to iterate over the keys containing a common
prefix. Fix the example of this same pattern in the comments above
`Iterator.SeekPrefixGE`.
Fix #907
=> db: add Example_PrefixIteration

db.go, get_iter.go, internal/manifest/level_metadata.go, internal/manifest/version.go, level_checker.go, tool/manifest.go
Remove the LevelIterator's Empty method and add an Empty method to the
LevelMetadata. It's trickier than expected to implement `Empty` when the
iterators are backed by B-Tree iterators, especially with the semantics
we've been relying on (eg, allowing it to be called on an unpositioned
iterator).
=> internal/manifest: remove LevelIterator.Empty

compaction.go, db.go, metrics.go, metrics_test.go, testdata/event_listener, testdata/ingest, testdata/metrics, tool/testdata/db_lsm, version_set.go
Adds a metric, updated atomically, to track bytes in sstables
written by in-progress compactions so far. As a compaction happens,
it effectively doubles disk space used for that key range until
it finishes and the old files are cleaned up. If we run out of
disk space during a compaction, having more visibility into
how much extra disk space was being used by in-progress
compactions is helpful.
Fixes #862.
=> *: Add Compact.InProgressBytes metric to track in-progress writes

batch.go, bloom/bloom.go, commit.go, compaction.go, data_test.go, db.go, db_test.go, level_checker.go, open.go, options.go, table_cache.go, table_cache_test.go, version_set.go, version_set_test.go
This PR mainly fixes a few compilation failures on 32bits machine.
The most important one is field alignment on 32bits machine. According the the go issue https://golang.org/pkg/sync/atomic/#pkg-note-BUG. `On 32 bit platforms, only 64-bit aligned fields can be atomic.`
But in the pebble codebase, uint64/int64 atomic fields are not aligned properly which will lead to crash.
=> pebble: fix compilation failure on 32bits machine

compaction_picker.go, compaction_picker_test.go, metrics.go, version_set.go
The `versionSet` incrementally computes stats on each level, including
the total size of the level. Use those sizes in the compaction picker's
`initLevelMaxBytes` rather than recomputing the sizes from scratch.
```
name                                        old time/op  new time/op  delta
ManySSTablesNewVersion/sstables=10-16        186µs ± 7%   182µs ± 4%     ~     (p=0.310 n=6+6)
ManySSTablesNewVersion/sstables=1000-16      212µs ± 7%   205µs ± 1%   -3.58%  (p=0.030 n=6+5)
ManySSTablesNewVersion/sstables=10000-16     376µs ± 3%   365µs ± 2%   -2.89%  (p=0.030 n=6+5)
ManySSTablesNewVersion/sstables=100000-16   6.05ms ± 3%  6.01ms ± 2%     ~     (p=0.818 n=6+6)
ManySSTablesNewVersion/sstables=1000000-16  84.0ms ± 4%  73.3ms ± 2%  -12.74%  (p=0.002 n=6+6)
```
=> db: use incrementally-computed sizes in initLevelMaxBytes

compaction.go, compaction_picker.go, compaction_picker_test.go, db.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, testdata/compaction_picker_L0, testdata/compaction_picker_concurrency, version_set.go
Previously, it was possible for compaction picking to pick an L0->LBase
compaction that conflicted with an existing L0->LBase compaction under
specific conditions.
A flush of a new sstable constructs a new Version and sublevel
intervals. If a flushed table does not overlap any individual
currently-compacting files, its intervals within sublevels
datastructures are not marked as compacting, although the flushed table
may still overlap with the active compaction's key range (eg, if the new
sstable sits squarely between two compacting files' keyspaces). If no
files exist in LBase that intersect with the intersection of the newly
flushed sstable's keyspace and the active compaction's keyspace, a
new compaction of the flush sstable would be allowed to start.
This change augments our existing …
=> db: prevent conflicting, concurrent L0->LBase compactions

compaction.go, compaction_picker.go, compaction_picker_test.go, db.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, testdata/compaction_picker_L0, testdata/compaction_picker_concurrency, version_set.go
Backport of #885.
----
Previously, it was possible for compaction picking to pick an L0->LBase
compaction that conflicted with an existing L0->LBase compaction under
specific conditions.
A flush of a new sstable constructs a new Version and sublevel
intervals. If a flushed table does not overlap any individual
currently-compacting files, its intervals within sublevels
datastructures are not marked as compacting, although the flushed table
may still overlap with the active compaction's key range (eg, if the new
sstable sits squarely between two compacting files' keyspaces). If no
files exist in LBase that intersect with the intersection of the newly
flushed sstable's keyspace and the active compaction's keyspace, a
new compaction of the flush sstable would be allowed to start.
This change …
=> crl-release-20.2: db: prevent conflicting, concurrent L0->LBase compactions

internal/metamorphic/parser.go, internal/metamorphic/parser_test.go
The metamorphic tests generates some operations, like `opNewIter` that
sometimes have arguments and sometimes not. When formatted and printed
to disk, an operation formats its empty arguments as the empty string
`""`.
This causes a problem when parsing and replaying persisted operations.
The metamorphic tests would previously reconstruct the arguments as
empty, non-nil slices. This difference changes the behavior of some
operations. For example, iterator bounds `[]byte{}` and `nil` are
treated differently.
This commit changes parsing to treat empty arguments `""` as nil.
=> internal/metamorphic: parse empty string as nil

db.go, open.go, options.go, options_test.go
This change splits the existing BytesPerSync option into two;
the original that now only governs sstable syncs, and a new
WALBytesPerSync option for WALs. The former's default is unchanged,
while the latter has a default of 0. This matches Cockroach+RocksDB
default behaviour where we have a similar bytes_per_sync value
for sstables, but we explicitly set wal_bytes_per_sync to 0.
This change is particularly beneficial in write/compaction
heavy workloads, such as sysbench. Here's a sysbench comparison
where old = #919 + #937, and new = old + this change:
```
name                                                old ops/sec  new ops/sec  delta
sysbench/oltp_read_write/nodes=3/cpu=32/conc=128     48.6k ± 5%   50.0k ± 3%     ~     (p=0.548 n=5+5)
sysbench/oltp_write_only/nodes=3/cpu=32/conc=128 …
```
=> *: Add new WALBytesPerSync option, defaulting to 0

compaction.go, compaction_picker.go, compaction_picker_test.go, testdata/compaction_picker_L0
This change updates output parameters of intra-L0 compactions to
obey flush sematics around file sizes, compaction expansions, and
grandparent / flush limits. This prevents cases where intra-L0
compactions unintentionally produce wide files bridging flush
split boundaries.
=> *: Have intra-L0 compactions follow flush sizes / splits

db.go, open.go, options.go, options_test.go
20.2 backport of #940.
---
This change splits the existing BytesPerSync option into two;
the original that now only governs sstable syncs, and a new
WALBytesPerSync option for WALs. The former's default is unchanged,
while the latter has a default of 0. This matches Cockroach+RocksDB
default behaviour where we have a similar bytes_per_sync value
for sstables, but we explicitly set wal_bytes_per_sync to 0.
This change is particularly beneficial in write/compaction
heavy workloads, such as sysbench. Here's a sysbench comparison
where old = #919 + #937, and new = old + this change:
```
name                                                old ops/sec  new ops/sec  delta
sysbench/oltp_read_write/nodes=3/cpu=32/conc=128     48.6k ± 5%   50.0k ± 3%     ~     (p=0.548 n=5+5) …
```
=> crl-release-20.2: *: Add new WALBytesPerSync option, defaulting to 0

compaction_picker.go, compaction_picker_test.go, options.go, testdata/compaction_picker_concurrency
Adds a new option, defaulting to 800mb, called CompactionDebtConcurrency
that works similarly to L0CompactionConcurrency in that it adds one
additional concurrent compaction slot per CompactionDebtConcurrency
bytes of compaction debt, up to MaxCompactionConcurrency.
The motivation behind this change is to not result in steep drops
in compaction concurrency right after a large base compaction finishes.
This is necessary in write-heavy workloads where we need to maintain
a high compaction concurrency throughout a workload, and to continue
moving files down from Lbase onto lower levels to keep pace with
flushes.
Furthermore, this change removes flushes from the count of
in-progress compactions when calculating concurrency.
These changes (plus #919) resulted in a slight but noticeable …
=> *: Add compaction-debt based signal for compaction concurrency

compaction.go, compaction_picker.go, compaction_picker_test.go, options.go, testdata/compaction_picker_L0, testdata/compaction_picker_concurrency
20.2 backport of #919 and #937
---
*: Have intra-L0 compactions follow flush sizes / splits
This change updates output parameters of intra-L0 compactions to
obey flush sematics around file sizes, compaction expansions, and
grandparent / flush limits. This prevents cases where intra-L0
compactions unintentionally produce wide files bridging flush
split boundaries.
Furthermore, the minimum threshold for overlaps before
an intra-L0 copmaction is chosen was bumped up to a constant of
minIntraL0Count (currently 4) to match RocksDB behaviour.
---
*: Add compaction-debt based signal for compaction concurrency 
Adds a new option, defaulting to 1GB, called CompactionDebtConcurrency
that works similarly to L0CompactionConcurrency in that it adds one
additional concurrent compaction slot per …
=> crl-release-20.2: Have Intra-L0 compactions follow flush sizes, plus compaction-debt-based concurrency

compaction_picker_test.go, testdata/compaction_picker_target_level
This change adds a test to test compaction picking logic where
MarkedForCompaction = true. Previously, this boolean was completely
untested, resulting in panics when Pebble was used on a previously-rocksdb
store directory, as RocksDB often set that boolean to true in the manifest.
Fixes #868.
=> *: Add a simple test for forced compactions

open.go, open_test.go, options.go, options_test.go
A database that was created using RocksDB or a previous version of
Pebble does not guarantee that its closed WALs were closed cleanly.
Detect these cases by the absence of a special private
'strict_wal_tail' option. If this special option is missing from the
OPTIONS file, interpret WALs permissively as they're interpreted in the
RocksDB and Pebble versions that wrote them.
See cockroachdb/cockroach#52729.
=> db: fix WAL checksum error handling during upgrade

open.go, open_test.go, options.go, options_test.go
Backport of #948.
It was a mostly clean cherrypick, just had a mini conflict with the
privatization of the `minCompactionRate`, `minFlushRate`.
=> crl-release-20.2: db: fix WAL checksum error handling from previous versions

internal/record/record.go, tool/data_test.go, tool/db.go, tool/testdata/db_checkpoint
Adds a command to create a checkpoint of an existing pebble directory,
using the db.Checkpoint method. This needs to be exposed to the command
line for use in some of Cockroach's roachtests.
Also makes a change in Checkpoint() to better handle empty manifests.
=> tool: Add `db checkpoint` command

batch_test.go, cmd/pebble/compact.go, compaction_picker_test.go, compaction_test.go, data_test.go, flushable.go, go.mod, go.sum, internal/arenaskl/arena.go, internal/arenaskl/node.go, internal/base/comparer.go, internal/cache/robin_hood_test.go, internal/manifest/l0_sublevels.go, internal/metamorphic/ops.go, internal/pacertoy/pebble/main.go, internal/pacertoy/rocksdb/main.go, internal/rangedel/iter_test.go, level_checker.go, mem_table_test.go, metrics.go, open_test.go, sstable/reader_test.go, sstable/table.go, tool/db.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go
Hey! Thanks for this very cool project.
In this PR, I tried to sparingly fix a couple of linting issues:
* Remove useless `fmt.Sprintf` calls
* `time.Now().Sub(start)` => `time.Since(start)`
* Slice pre-allocations (whenever it was possible)
* Ineffective type casts
* Ineffective assignments
* Useless select / case on a single channel
* Fixing a test that was calling `t.Fatal` within goroutines which is not allowed. I replaced it by a standard `errorgroup` (hopefully it's compliant with your standards)
* Missing gofmts
=> Fixing linting issues

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, get_iter.go, ingest_test.go, internal/manifest/btree.go, internal/manifest/btree_test.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level_metadata.go, internal/manifest/level_metadata_test.go, internal/manifest/testdata/level_iterator, internal/manifest/testdata/version_edit_apply, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, internal/manifest/version_test.go, level_checker.go, level_iter_test.go, merging_iter_test.go, tool/db.go, tool/lsm.go, tool/manifest.go, tool/testdata/manifest_dump, version_set.go
internal/manifest: use B-Tree for organizing level file metadata
Update the LevelMetadata, LevelSlice, LevelIterator types to be backed
by a B-Tree, allowing logarithmic applications of version edits.
internal/manifest: add B-Tree Annotator
Add an Annotator type that allows external packages to define recursive
calculations over LevelMetadata and cache the results on B-Tree nodes.
Use this Annotator type to remove two O(# sstables) operations:
calculating the total compensated size of a level and finding the next
available elision-only compaction.
```
name                                        old time/op  new time/op  delta
ManySSTablesNewVersion/sstables=10-16        182µs ± 4%    62µs ± 1%  -66.20%  (p=0.010 n=6+4)
ManySSTablesNewVersion/sstables=1000-16      205µs ± 1%    65µs ± 5% …
```
=> internal/manifest: use B-Tree for organizing level file metadata

tool/db.go, tool/testdata/db_get_set
Being able to do direct mutations on a pebble DB is sometimes
useful, such as in roachtests (see cockroachdb/cockroach#55840).
This change allows for us to do that in the pebble command.
=> tool: Add `db get` and `db set` commands

checkpoint_test.go, db.go, db_test.go, event_listener_test.go, table_cache.go
~Add an interface to `DB` to get all sst table properties. The interface is like rocksdb's `DB.GetPropertiesOfAllTables`.~
Extend to `DB.SSTables` function to allow return sstable.Properties in each TableInfo
This is useful in case there are  customized `TablePropertyCollector`s in the db, so we can use this API to fetch all the user properties.
=> db: allow method db.SSTables to return sstable properties

.travis.yml
I found that I could cut my build times in half on another golang/Travis project by allowing go's caches to be reused across builds.
=> Enable Travis CI caching of go toolchain artifacts

compaction.go, compaction_test.go, get_iter_test.go, ingest.go, internal/manifest/btree.go, internal/manifest/btree_test.go, internal/manifest/level_metadata.go, level_checker.go, level_checker_test.go, level_iter.go, level_iter_test.go, merging_iter_test.go, table_cache.go, table_cache_test.go
Together these commits reclaim some of the lost ycsb C performance,
but not all. In a single run of the three commits, the commit preceding
the B-Tree integration achieved 1,574,408 ops/sec, the commit with
the B-Tree integrated achieved 1,343,757 ops/sec and this commit
achieved 1,442,248 ops/sec. I'm going to keep investigating, but
figured I'd put these commits up first.
---
db: remove unnecessary allocation from newIters calls
When the B-Tree was integrated with the LevelMetadata, the `newIters`
signature changed to take a `manifest.LevelFile` which includes a
`manifest.LevelSlice` capturing the file's position within the level.
This required cloning B-Tree iterators whenever a new iterator was
created. This change stemmed from refactor confusion around
`newRangeDelIter` when …
=> db: remove unnecessary newIters allocation, inline sort.Search

compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, ingest.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go, internal/manifest/version_test.go, level_checker.go, level_iter_test.go, table_stats.go, version_set.go
This commit contains a few optimizations as fallout from the integration
of the B-Tree:
* Use a pointer receiver for LevelSlice methods.
* Use precomputed level sizes in estimatedCompactionDebt.
* Avoid unnecessary Empty calls on sublevel B-Trees in iterator
initialization.
=> db: use pointer for LevelSlice methods, use precomputed level sizes

compaction_iter.go, iterator.go, testdata/iterator, testdata/snapshot
Prior to this change, a switch in direction would
work only if the iterator was at the next (prev)
position for forward (reverse) iteration and the
direction was switching to reverse (forward).
It the iterator was exhausted, it would be at the
cur position, and we would not recognize that
the direction had changed.
The pos field now explicitly tracks the direction of
the current position. And there is additional
error checking for invariants.
=> db: fix Iterator direction switching behavior

internal/manifest/level_metadata.go
Currently, the comment for SeekGE states that it seeks to the first file
with a `Largest` key "less than or equal" to the given key. The
actual behavior is that it seeks to the first file with a `Largest` key
"greater than or equal" to the given key.
This commit fixes the comment and reorganizes the call to the `Comparer`
to make it slightly more readable and true to the comment.
=> internal/manifest: fix typo in comment for SeekGE

internal/base/filenames.go, internal/base/filenames_test.go, sstable/reader.go, table_cache.go
Panic immediately if opening a sstable ever fails with a file not found
error. This ensures we panic with the stack trace that actually produced
the error, rather than an indirect stack trace like an iterator close.
Some tests rely on the ability to retry filesystem errors loading a
table, so we restrict the panics to 'no such file' errors. This change
is for the 20.2 branch only. In the master branch, we can plumb the same
information by wrapping the error with a stack trace from within the
vfs.FS implementation.
Also, annotate the panic error with a summary of the number of files of
each type currently in the data directory. This may help us ascertain
whether the entire data directory has been wiped from underneath an
active database or just a single table is missing.
Informs …
=> crl-release-20.2: db: panic on 'no such file or directory' error

vfs/dir_unix.go, vfs/dir_windows.go, vfs/errors_unix_test.go, vfs/syncing_file.go, vfs/vfs.go
Many filesystem errors don't get surfaced immediately and instead are
cached on an iterator to be exposed by a call to `Error`. This can make
it difficult to ascertain the source of an I/O error (for example
cockroachdb/cockroach#55351). This commit updates the vfs.Default
fileystem to wrap all of its errors with a current stack trace.
Filesystem errors are expected to be relatively infrequent, so this
wrapping is not expected to hinder performance.
=> vfs: wrap defaultFS errors with a stack trace

internal/base/filenames.go, internal/base/filenames_test.go, sstable/reader.go, table_cache.go
Panic immediately if opening a sstable ever fails with a file not found
error. This ensures we panic with the stack trace that actually produced
the error, rather than an indirect stack trace like an iterator close.
Some tests rely on the ability to retry filesystem errors loading a
table, so we restrict the panics to 'no such file' errors. This change
is for the 20.2 branch only. In the master branch, we can plumb the same
information by wrapping the error with a stack trace from within the
vfs.FS implementation.
Also, annotate the panic error with a summary of the number of files of
each type currently in the data directory. This may help us ascertain
whether the entire data directory has been wiped from underneath an
active database or just a single table is missing.
Informs …
=> db: panic on 'no such file or directory' error

compaction_picker.go, data_test.go, testdata/compaction_tombstone_elision_only
When elision-only compactions were introduced, the
`Stats.RangeDeletionsBytesEstimate` field  for L6 tables started being
populated with an estimate of the bytes within the table that could be
dropped by its own range tombstones once blocking snapshots were closed.
Since these obsolete keys do not contribute to write amplification, this
commit subtracts out the `RangeDeletionsBytesEstimate` field from the
calculation of overlapping bytes in L6. This increases the
prioritization of compacting L6 files with obsolete data in ordinary
automatic compactions.
This should help avoid situations where broad range tombstones entombed
in L6 force ingestions into higher levels, distorting the shape of the
LSM.
=> db: improve min-overlapping ratio heuristic for compactions into L6

sstable/data_test.go, sstable/testdata/writer, sstable/writer.go
This change ensures the slice backing writerMeta.LargestRange
is always solely owned by it. This avoids instances where it
could be mutated by vfs.File wrappers that modify slices passed into
Write() in-place.
This change is already made on master (in commit:
0e61248353a41502074e9be2481c420971fa1ad9) however the test needs to be
forward-ported to it.
=> [crl-release-20.2] sstable: Clone LargestRange in case Writer mutates it

sstable/data_test.go, sstable/testdata/writer, sstable/writer.go
To catch bugs that could only occur when using a vfs.File
wrapper that modifies the slice passed into Write() in-place,
this change adds a modifierFile that flips bits in the slice
passed in.
=> sstable: Add Writer test w/ file that modifies slice in Write()

sstable/data_test.go, sstable/testdata/writer, sstable/writer.go
This change ensures the slice backing writerMeta.LargestRange
is always solely owned by it. This avoids instances where it
could be mutated by vfs.File wrappers that modify slices passed into
Write() in-place.
This change is already made on master (in commit:
0e61248353a41502074e9be2481c420971fa1ad9) however the test needs to be
forward-ported to it.
=> [crl-release-20.1] sstable: Clone LargestRange in case Writer mutates it

ingest_test.go, sstable/data_test.go, sstable/testdata/writer, vfs/mem_fs.go
When invariants are enabled, `memFile.Write` will mutate its input
buffer (invert all the bits) in order to try and flush out bugs in
Pebble which assume the buffer supplied to `Write` is not
modified. Enabling invariants also has the effect of wrapping `memFile`
in a `flushFile` which defines a `Flush()` method. This disables the use
of `bufio.Writer` by `sstable.Writer` which helps to suss out bugs
relating to the mutation of the write buffer.
=> *: make memFile.Write mutate its input buffer

compaction.go, db.go, internal/manifest/btree.go, internal/manifest/btree_test.go, internal/manifest/level_metadata.go, internal/manifest/version.go, internal/manifest/version_test.go, internal/metamorphic/options.go, metrics.go, open.go, options.go, pacer.go, pacer_test.go, testdata/compaction_pacer_maybe_throttle, version_set.go
Currently, file deletions are not rate limited at all. This is
usually not an issue, however if a lot of bytes are deleted
all at once, this could slow down or even stall disk writes on
some SSDs, if an ssd-level garbage collection run gets kicked off.
As it's hard to detect when this would happen in advance, it makes
sense to be pacing deletions at some rate all the time.
This PR implements deletionPacer, which works in some ways like
{compaction,flush}Pacer, except the threshold it has (i.e. free
space on disk in bytes) is treated as a minimum rather than a
maximum for inducing slowness, unlike the other pacers that are
based on read-amplification. The deletion pacer is disabled by
default to make most tests more deterministic, however it will
most likely be enabled in cockroach.
Fixes …
=> *: Implement deletion pacing of obsolete compaction files

compaction_test.go, data_test.go, testdata/compaction_tombstone_elision_only
Automatic compactions might pursue a compaction before the call to
`maybe-compact`.
=> db: fix flaky TestCompactionTombstoneElisionOnly

internal/arenaskl/node.go
The `arena.extValues` (external values) mechanism was removed a long
time ago as it performed poorly. Now large values are handled completely
outside of the memtable arena skiplist using the flushable batch
mechanism.
=> internal/arenaskl: remove mention of arena.extValues

internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go
- instead of maintaining the slices in levelFiles in
sorted order, which is O(n^2), the code appends and
sorts at the end.
- the search for maxIntervalIndex is pruned to start
at minIntervalIndex.
Benchmark results (the K benchmark uses the recent
customer issue MANIFEST that I can't include here):
```
name                    old time/op    new time/op    delta
L0SublevelsInit-16        6.92ms ± 0%    6.69ms ± 0%   ~     (p=1.000 n=1+1)
L0SublevelsInitK-16     4.57s ± 0%     4.31s ± 0%   ~     (p=1.000 n=1+1)
name                    old alloc/op   new alloc/op   delta
L0SublevelsInit-16        3.03MB ± 0%    3.03MB ± 0%   ~     (p=1.000 n=1+1)
L0SublevelsInitK-16    1.20GB ± 0%    1.20GB ± 0%   ~     (p=1.000 n=1+1)
name                    old allocs/op  new allocs/op  delta …
```
=> manifest: small optimizations to NewL0Sublevels

checkpoint_test.go, cmd/pebble/db.go, compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, db_test.go, event_listener_test.go, flush_test.go, ingest_test.go, internal/metamorphic/options.go, level_checker.go, metrics_test.go, options.go, options_test.go, testdata/compaction_picker_target_level, testdata/event_listener, testdata/manual_compaction, tool/db.go, tool/testdata/db_lsm, version_set.go
Now that sublevel compactions (and flush splits) have shipped
in one stable release, it's worthwhile to move the `FlushSplitBytes`
parameter out of the Experimental sub-struct, have it default to
2*L0 Target file size (same as Cockroach), and make sublevel
compactions the only supported option.
A lot of test changes to account for the sublevel compactions /
flush split default world. L0 Compaction threshold was bumped up
in some tests to account for the fact that sublevel compactions
multiply sublevel count by 2, instead of just looking at file count.
=> *: Make sublevel compactions default, remove legacy code

compaction.go, compaction_test.go
A huge Lbase, due to a compaction backlog, can currently
cause a memtable that is wide in the key space to be
flushed as many tiny files. This heuristic is an unrefined
way of preventing such a situation, but at the cost of
wide L0 files.
=> db: heuristic to prevent tiny flushed files due to Lbase

.travis.yml, internal/cache/cgo_disabled.go, internal/cache/cgo_enabled.go, internal/cache/entry_normal.go, internal/cache/value_normal.go
If cgo is disabled, `manual.New` allocates memory using
`make([]byte,...)`. The cache was using this memory as if it was
manually allocated, and casting it to Go structs and then storing Go
pointers inside the structs. But a Go pointer stored inside of a
`[]byte` is invisible to the Go GC, so the GC was merrily reclaiming the
memory which would lead to all sorts of badness in the cache, often
resulting in segfaults or violations of refcount invariants.
Now, when cgo is disabled, the `entry` and `Value` structs are directly
allocated using the Go allocator. The cache code mostly supported this
mode of operation already when the `invariants` tag. The difference
between disabling cgo and enabling invariants is that the latter also
has the effect of adding the finalizers uses for leak …
=> internal/cache: fix memory corruption when CGO_ENABLED=0

db_test.go
An automatic compaction would sometimes complete before the test listed
the contents of the directory, resulting in a new, unexpected MANIFEST
appearing in the directory.
=> db: deflake TestRollManifest

db.go, internal/base/filenames.go, internal/base/filenames_test.go
Provide a little more context in base.MustExist, by reporting the count
of manifests. Also, call MustExist from `makeRoomForWrite` to get
context during failed log rotations.
=> internal/base: provide more context in MustExist

db.go, internal/base/filenames.go, internal/base/filenames_test.go
Provide a little more context in base.MustExist, by reporting the count
of manifests. Also, call MustExist from `makeRoomForWrite` to get
context during failed log rotations.
20.2 backport of #1014.
=> crl-release-20.2: internal/base: provide more context in MustExist

vfs/file_lock_test.go, vfs/file_lock_unix.go, vfs/vfs.go
The behavior of vfs.Default.Lock-ing the same file twice was undefined
in the VFS interface. In practice, on Unix the lock would be dropped
because closing the second attempt's file descriptor would release the
first file descriptor's hold on the lock.
I don't believe this to have caused any problems in practice, but it
seems prudent to handle this case, because transparently dropped locks
are difficult to debug.
This was inspired by facebook/rocksdb#1780 and the associated fix.
=> vfs: prevent double locking from the same process

cmd/pebble/badger.go, cmd/pebble/boltdb.go, cmd/pebble/db.go, cmd/pebble/main.go, cmd/pebble/queue.go, cmd/pebble/rocksdb.go, cmd/pebble/tombstone.go, cmd/pebble/ycsb.go
Add a benchmark for evaluating compaction surrounding point tombstones.
The bunchmarks runs a configurable YCSB workload, alongside a
single-writer queue workload. The queue workload maintains a
fixed-length queue, removing the tail with a point delete.
=> cmd/pebble: add tombstone benchmark

cmd/pebble/queue.go, cmd/pebble/rocksdb.go, cmd/pebble/tombstone.go, compaction_picker.go, compaction_test.go, data_test.go, internal/manifest/version.go, sstable/properties.go, table_stats.go, testdata/compaction_tombstones, testdata/ingest, testdata/manual_compaction, testdata/range_del, testdata/table_stats, tool/sstable.go
Add an estimate of the disk space that may be reclaimed by compacting
point tombstones to the compensated size used in compaction heuristics.
At the end of a 20-minute test on my gceworker using the tombstone
benchmark, the size of the queue keyspace was 16 M as opposed to 1 G
without this commit.
Fix #1016.
=> db: add point tombstone compensation

compaction.go, flush_test.go
Previously, a range deletion beginning with an empty user key could
cause an infinite loop during a flush or compaction. If a compaction
output was empty and the rangedel fragmenter contained a tombstone
beginning with an empty user key, the compaction logic could confuse an
absent limit with the rangedel fragmenter's start key and skip writing
an output table.
Fix #1022.
=> compaction: fix handling of empty user key range deletes

cmd/pebble/compact.go, compaction.go, compaction_picker.go, compaction_picker_test.go, compaction_test.go, db.go, internal/manifest/l0_sublevels_test.go, internal/manifest/level.go, internal/manifest/version.go, internal/manifest/version_edit.go, internal/manifest/version_edit_test.go, iterator.go, iterator_test.go, merging_iter.go, options.go, testdata/compaction_picker_read_triggered, testdata/compaction_read_triggered, testdata/iterator_read_sampling, tool/db.go, tool/manifest.go, version_set.go
Previously, our compactions were triggered on write based heuristics.
This change introduces compactions based on high read activity to improve
read performance in read-heavy workloads. It is inspired from LevelDB's
read based compaction heuristic which is outlined in the following issue:
https://github.com/cockroachdb/pebble/issues/29.
These compactions are triggered using an `AllowedSeeks` parameter on
each file's `FileMetadata`. Reads are sampled based on a rate defined in
`iterator.MaybeSampleRead()`. If a read is sampled, `AllowedSeeks` is
decremented on the file in the top-most level containing the key. Once
`AllowedSeeks` reaches 0, a compaction for the key range is scheduled.
Read triggered compactions are only considered if no other compaction is
possible at the time. This helps …
=> *: Introduce read triggered compaction heuristic

compaction_test.go, db.go, error_test.go, open_test.go, range_del_test.go
We use the user keys to construct InternalKeys that are
(start, InternalKeySeqNumMax, InternalKeyKindMax) and
(end, 0, 0)
so it is not meaningful to have start >= end since it
represents an empty interval. The current behavior
did actual work because of how the memtable overlap
code is written.
This came up in the code review for
https://github.com/cockroachdb/cockroach/pull/57709
=> db: return error if manual compaction start >= end

iterator.go, options.go
This change enables read based compactions by default and sets the read
sampling threshold. This is based on the findings in
https://github.com/cockroachdb/pebble/issues/29.
=> options: enable read based compactions

sstable/reader.go
Previously sstable.Reader.Close() would initialize a new error each time it was called.
In workloads that open and close many readers, this could actually have non-trivial
expense.
Instead, this change adds a pre-initialized error value and just assigns it in Close().
=> sstable: use fixed error in Close

iterator.go
Previously, this used `mergingiter.dir` which does not follow the same
`iterPos` type as `iterator.pos`. This fixes it to use `iterator.pos`.
Follow up PR from https://github.com/cockroachdb/pebble/pull/1031.
=> iterator: use i.pos in sampling

batch.go, batch_test.go, compaction_test.go, data_test.go, db.go, ingest_test.go, iterator.go, iterator_test.go, options.go, range_del_test.go, snapshot.go, testdata/iterator_next_prev
Needed for https://github.com/cockroachdb/cockroach/issues/41720
and https://github.com/cockroachdb/cockroach/issues/55461
=> db: add an Iterator.Clone to iterate over the same db state

compaction.go, compaction_picker.go, compaction_test.go, data_test.go, internal/manifest/version.go, sstable/properties.go, table_stats.go, testdata/compaction_tombstones, testdata/ingest, testdata/manual_compaction, testdata/range_del, testdata/table_stats, tool/sstable.go
This is a 20.2 backport of #1018. I'm teeing this up for the 20.2.4 release, but we can let the master branch bake for a bit.
db: add point tombstone compensation 
Add an estimate of the disk space that may be reclaimed by compacting
point tombstones to the compensated size used in compaction heuristics.
db: scale point tombstone averages according to file size
=> crl-release-20.2: db: add point tombstone compensation 

sstable/options.go, sstable/reader.go, sstable/table.go, sstable/table_test.go, sstable/writer.go
This change does not alter the set of supported checksums -- it is still only crc32c.
This change adds `ChecksumType` to the public API so that `Writer` can be configured with
a requested checksum type (only CRC32c is for now) and alters `Reader` to actually use the
checksum type it read from the footer, rather than assuming it will always have been CRC.
=> sstable: Add ChecksumType to API

batch.go, batch_test.go, mem_table.go, open.go
The upper bound on a memtable node's memory overhead is higher than
a batch's wire encoding, which means a batch's memtable size grows
faster than the batch's backing byte slice.
We enforce a maxBatchSize on size of the batch's backing byte
slice. Previously, if a batch approached the maxBatchSize but didn't
cross it, the memTableSize, a uint32, could overflow. This overflow
would cause Pebble to incorrectly add the batch to the memtable rather
than the flush list and to reserve the wrong amount of space in the
memtable.
This commit fixes the issue by tracking the batch's memTableSize using a
uint64.
See cockroachdb/cockroach#58004.
=> db: use uint64 for batch's memTableSize

go.mod, go.sum, sstable/options.go, sstable/reader.go, sstable/reader_test.go, sstable/table.go, sstable/table_test.go, sstable/writer.go, vendor/github.com/cespare/xxhash/v2/.travis.yml, vendor/github.com/cespare/xxhash/v2/LICENSE.txt, vendor/github.com/cespare/xxhash/v2/README.md, vendor/github.com/cespare/xxhash/v2/go.mod, vendor/github.com/cespare/xxhash/v2/xxhash.go, vendor/github.com/cespare/xxhash/v2/xxhash_amd64.go, vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s, vendor/github.com/cespare/xxhash/v2/xxhash_other.go, vendor/github.com/cespare/xxhash/v2/xxhash_safe.go, vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go, vendor/modules.txt
RockDB supports xxhash (32 bit) and xxhas64 hash-based block checksums, though in the latter
case it only persists and compares the lower 32b of the 64b hash.
This change adds support for xxhash64, using the same checksum type identifier byte and same
truncation to the lower 32 bits.
=> sstable: add xxhash64 checksum support

docs/index.html
Add annotations to the nightly benchmarks for the switch to a B-Tree and
the enabling of read-triggered compactions.
=> docs: add a couple benchmark annotations

sstable/reader.go, sstable/table.go, vfs/prefetch_generic.go, vfs/prefetch_linux.go
This adds vfs.ReadableFile to describe the interface needed by sstable.Reader: ReadAt, Stat and Close.
Breaking this subset out of vfs.File can make it easier to implement a readable file, for example one
backed by a read-only connection to remote storage.
=> vfs,sstable: split out subset of vfs.File used for reading

vfs/vfs.go
Unlike io.Writer, implementations of vfs.File *are* allowed to modify
the slice passed into Write() in-place, and are also not required to
reset its value to what it was at call time. All callers of
Write() on a vfs.File in Pebble and elsewhere need to take this
into account.
This change adds a comment on vfs.File clarifying this.
=> vfs: Add comment on vfs.File.Write about modifying input in-place

compaction.go, db.go
db.Close() currently waits for "cleaner" jobs, but
cleaners can spawn asynchronous deletion goroutines that can
remain dangling after the cleaner goroutines have finished.
This change adds a WaitGroup on db that is incremented upon
starting a new paced deletion, and Done()'d when that finishes.
The Close() method calls Wait on that WaitGroup.
Fixes #1044.
=> *: Wait for deletion goroutines to finish in db.Close

vfs/disk_health.go, vfs/fd.go, vfs/fd_test.go, vfs/syncing_file.go, vfs/syncing_file_test.go
Pebble relies on the existence of an `Fd() uintptr` method on file
handles for some optimizations (eg. WAL preallocation, Prefetch).
However, two of Pebble's own file wrappers used in production,
namely diskHealthCheckingFile and syncingFile, "hide" this
method even if the underlying os.File had it.
This change adds another type, fdFileWrapper, that embeds an "outer"
vfs.File while also reimplementing an Fd() method that bypasses
that outer vfs.File and passes through to the inner file.
Fixes #1047.
=> vfs: Add fdFileWrapper to re-implement Fd() method on file wrappers

vfs/errors_unix.go, vfs/errors_windows.go, vfs/mem_fs.go
`MemFS.Remove` was previously returning `EEXIST` when attempting to
remove a non-empty directory. Now it returns `ENOTEMPTY` which matches
the behavior of unix filesystems and the `rmdir` system call.
=> vfs: fix error return by MemFS.Remove for non-empty dir

options.go
The previous docs were inherited from go-leveldb, but that behavior has
not been true in Pebble for a long time.
Fixes #1052
=> db: fix docs for WriteOptions.Sync

docs/index.html
Also, add an annotation for the recent regression fix.
=> docs: show insert-only workload in nightly benchmarks

internal/fastrand/fastrand.go, internal/fastrand/fastrand_test.go, iterator.go
The allocations in maybeSampleRead were 21.5% of object
allocations in a cockroachdb benchmark
(BenchmarkKV/Update). Read sampling now uses fastrand.
Additionally, we don't bother with executing the
sampling code when the iterator is not valid, since the
key and value fields are meaningless in that case.
There are microbenchmarks that show that this random
generator change is not slower.
BenchmarkSTFastRand-16       	553082136	         2.21 ns/op	       0 B/op	       0 allocs/op
BenchmarkSTDefaultRand/no-new-16         	228876657	         5.12 ns/op	       0 B/op	       0 allocs/op
BenchmarkSTDefaultRand/new-period=10-16  	48703587	        24.6 ns/op	       4 B/op	       0 allocs/op
BenchmarkSTDefaultRand/new-period=100-16 	92016868	        13.9 ns/op	       0 B/op	       0 allocs/op …
=> db: change random generator for read sampling

docs/css/app.css, docs/index.html, docs/js/app.js
We've had some Pebble performance regressions go unnoticed, partially
because it can be difficult to see the regression visually within the
Pebble nightly benchmarks charts. It's especially difficult to see
fluctuations in benchmarks with significantly lower magnitude values
than the maximum across charts. For example, the ycsb/F/values=1024
workload has a throughput of about 26k ops/sec, compared to the
ycsb/c/values=64 workload's 2,800k ops/sec. This change adds a toggle to
the nightly benchmarks to scale each chart to its own maximum.
A little 💪   Friday action.
=> docs: add an option to toggle per-chart scaling

compaction.go
Currently, maybeThrottle is called for every key written to a
compaction output. Since this is a hot path, and since calling
pacer.maybeThrottle requires dynamic dispatch, quite a bit of
CPU cycles were being spent in just repeatedly calling that
method, which did nothing in production uses of Pebble anyway.
This change updates compaction code to just not make that
call if the nilPacer is used as the compaction pacer, which
happens for all non-testing uses of Pebble right now.
Paired w/ @angelazxu on this.
Fixes #1030
=> compaction: Don't call maybeThrottle if nilPacer passed in.

vfs/disk_health.go, vfs/fd.go, vfs/fd_test.go, vfs/syncing_file.go, vfs/syncing_file_test.go
Backport of #1049 to 20.2.
Pebble relies on the existence of an `Fd() uintptr` method on file
handles for some optimizations (eg. WAL preallocation, Prefetch).
However, two of Pebble's own file wrappers used in production,
namely diskHealthCheckingFile and syncingFile, "hide" this
method even if the underlying os.File had it.
This change adds another type, fdFileWrapper, that embeds an "outer"
vfs.File while also reimplementing an Fd() method that bypasses
that outer vfs.File and passes through to the inner file.
Any file wrappers external to Pebble should call WithFd()
in a similar way to ensure they don't hide the Fd() method
unintentionally too.
Fixes #1047.
=> [crl-release-20.2] vfs: Add fdFileWrapper to re-implement Fd() method on file wrappers

batch.go, data_test.go, error_iter.go, get_iter.go, internal/arenaskl/flush_iterator.go, internal/arenaskl/iterator.go, internal/arenaskl/skl_test.go, internal/base/iterator.go, internal/rangedel/iter.go, internal_test.go, iterator.go, iterator_test.go, level_iter.go, level_iter_test.go, merging_iter.go, merging_iter_test.go, sstable/block.go, sstable/data_test.go, sstable/reader.go, sstable/reader_test.go, sstable/testdata/prefixreader/iter, sstable/testdata/reader/iter, testdata/iterator, testdata/level_iter_seek, tool/sstable.go
CockroachDB uses SeekPrefixGE on the Put path to read
the existing value for a key. For a batch of Puts, the
common case is to use the same Iterator with a sequence
of SeekPrefixGE calls (with no intermediate Next calls).
These seek calls use keys that are sorted in ascending
order.
For a CockroachDB benchmark that does
`UPDATE bench.kv SET v = v + 1 WHERE k IN (...)`
for a batch of 100 keys, we see the following benefit
```
name                                old time/op    new time/op    delta
KVAndStorageUsingSQL/versions=2-16    3.27ms ± 2%    2.07ms ± 2%  -36.69%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=4-16    3.28ms ± 1%    2.07ms ± 0%  -36.90%  (p=0.008 n=5+5)
KVAndStorageUsingSQL/versions=8-16    3.65ms ± 1%    2.44ms ± 1%  -33.01%  (p=0.008 n=5+5)
```
Note that the above …
=> *: optimize SeekPrefixGE to use Next

iterator.go
This is especially useful for sparse parts of the
key space which may have large numbers of deleted
versions, as happens with the locks in CockroachDB.
Results from a CockroachDB benchmark are included
below. The separated=true case is what mainly benefits
from this. The actual new numbers are listed after
the diff.
```
name                                                                      old time/op    new time/op    delta
ScanAllIntentDeleted/separated=false/versions=200/percent-flushed=0-16      63.8µs ± 0%    50.2µs ± 0%   -21.27%
ScanAllIntentDeleted/separated=false/versions=200/percent-flushed=50-16     24.4µs ± 0%    24.8µs ± 0%    +1.81%
ScanAllIntentDeleted/separated=false/versions=200/percent-flushed=90-16     5.60µs ± 0%    4.28µs ± 0%   -23.68% …
```
=> db: optimize SeekGE/SeekLT for the noop case

internal/metamorphic/config.go, internal/metamorphic/generator.go, internal/metamorphic/ops.go, internal/metamorphic/parser.go, iterator.go, iterator_test.go, testdata/iterator_seek_opt_errors
- SeekLT had a bug that included the equality case in
the comparison.
- Added an explicit error handling test, that checks
that the optimization is not used when the
InternalIterator returns an error. This test also
exercises some non-error cases, including the bug.
- Added randomization on when the optimization is
applied when invariants.Enabled is true.
- Added a comment explaining why this optimization
is not used when the batch is non-nil. Also, we
no longer copy the seek key when batch is non-nil,
since that copy is wasted.
- Added support for Iterator.Clone to the metamorphic
test.
=> db: fix bug in seek noop optimization and add more testing

range_del_test.go
Amend BenchmarkRangeDelIterate to include benchmarks that iterate
through keys that are deleted by a range tombstone within the same
SSTable.
See #1070.
```
goos: linux
goarch: amd64
BenchmarkRangeDelIterate
BenchmarkRangeDelIterate/entries=10
BenchmarkRangeDelIterate/entries=10/deleted=10
BenchmarkRangeDelIterate/entries=10/deleted=10/snapshotAndCompact=false
BenchmarkRangeDelIterate/entries=10/deleted=10/snapshotAndCompact=false-24         	 1868349	       636 ns/op
BenchmarkRangeDelIterate/entries=10/deleted=10/snapshotAndCompact=true
BenchmarkRangeDelIterate/entries=10/deleted=10/snapshotAndCompact=true-24          	  403632	      2945 ns/op
BenchmarkRangeDelIterate/entries=10/deleted=9
BenchmarkRangeDelIterate/entries=10/deleted=9/snapshotAndCompact= …
```
=> db: amend BenchmarkRangeDelIterate

iterator.go, testdata/iterator
Also clarify the semantics on when bounds slices can be mutated
by the caller.
This optimization was the cause of the failures in CockroachDB's
cdc/bank/cluster-recovery test. There is no new test here since
the contract is now on the caller's side (there will be a
CockroachDB test to ensure that the contract is not being
violated).
=> db: remove Iterator.SetBounds optimization for unchanging bounds

vfs/disk_usage_linux.go, vfs/disk_usage_unix.go
On linux, the Statfs struct contains an Frsize field that should be
preferred over the bsize field.
For example, consider the following example program:
```go
package main
import (
"fmt"
"os"
"golang.org/x/sys/unix"
)
func main() {
path := os.Args[1]
var fs unix.Statfs_t
if err := unix.Statfs(path, &fs); err != nil {
fmt.Fprintf(os.Stderr, "fatal error: %s", err.Error())
}
fmt.Printf("{\n Bfree: %d\n BAvail: %d\n Bsize: %d\n Frsize: %d\n}\n\n", fs.Bfree, fs.Bavail, fs.Bsize, fs.Frsize)
fmt.Printf("Free KB with Bsize:   (%d*%8d)/1024 = %d\n", fs.Bfree, fs.Bsize, (fs.Bfree*uint64(fs.Bsize))/1024)
fmt.Printf("Free KB with Frsize:  (%d*%8d)/1024 = %d\n\n", fs.Bfree, fs.Frsize, (fs.Bfree*uint64(fs.Frsize))/1024)
fmt.Printf("Avail KB with Bsize:  (%d*%8d)/1024 = %d\n", fs.Bavail, fs.Bsize, …
```
=> vfs: Use frsize in GetFreeSpace

internal/cache/clockpro.go, snapshot_test.go, table_cache.go
GOMAXPROCS is usually the same with NumCPU, but it allows control; for
example, we limit GOMAXPROCS for race detector tests.
=> use GOMAXPROCS instead of NumCPU

compaction.go, db.go, iterator_test.go, merging_iter.go, merging_iter_test.go, testdata/merging_iter
This is motivated by the CockroachDB issues discussed
in #1070 where
range tombstones in L6 cause the iterator to go through
all the deleted data. The situation is even worse in that
each successive SeekPrefixGE in a batch request (which is
in sorted order) will typically have to start all over again
since the file at which the seek finally ended its work is
probably later than the file which contains the relevant key.
Note that CockroachDB does not set bounds when using
SeekPrefixGE because the assumption is that the underlying
Pebble implementation can imply bounds, and we don't want
to change this behavior in CockroachDB. Since CockroachDB
primarily uses range tombstones when deleting CockroachDB
ranges, the SeekPrefixGE calls that were slow were probably
on a preceding CockroachDB …
=> db: mergingIter.SeekPrefixGE stops early if prefix cannot match

db.go, internal/cache/clockpro.go, internal/cache/entry_invariants.go, internal/cache/entry_normal.go, internal/cache/robin_hood.go, internal/cache/value_invariants.go, internal/cache/value_normal.go, internal/invariants/finalizer_off.go, internal/invariants/finalizer_on.go, internal/lint/lint_test.go, open.go, sstable/reader.go
Disable all use of `SetFinalizer` in race builds so that finalizers are
never used when running CRDB tests. The use of finalizers causes some
unexplained rapid memory leak when running CRDB tests. Previously
finalizers were sometimes enabled if invariants were enabled which is
true in race builds. All use of `SetFinalizer` is now protected behind
the equivalent of `invariants.Enabled && !invariants.RaceEnabled`.
Fixes #1086
=> *: don't use SetFinalizer in race builds

db.go, db_test.go, open.go
Workaround a limitation with finalizers on cyclic data
structures. Rather than setting a finalizer on `*DB`, we set the
finalizer on `DB.closed` which is the atomic value that is being checked
by the finalizer. Additionally, we don't need the finalizer to run in
the event that `DB.Close()` has been called, so we clear the finalizer
there.
=> db: workaround SetFinalizer(*DB) memory leak

data_test.go, internal/metamorphic/config.go, internal/metamorphic/generator.go, internal/metamorphic/meta_test.go, internal/metamorphic/ops.go, internal/metamorphic/parser.go, internal/metamorphic/retryable.go, iterator.go, iterator_test.go, testdata/iterator
Limited iteration mode is a best-effort way for the caller
to specify an exclusive forward or inclusive reverse limit
on each limited-iteration call. The limit lasts only for
the duration of the call. The limit is exclusive for
forward iteration and inclusive for reverse iteration.
Iterator supports WithLimit variants for SeekGE, SeekLT,
Next, Prev. These are motivated by the O(N^2) complexity
we observe when doing coordinated iteration over the
lock table and MVCC keys in CockroachDB where all the
intents in the lock table are deleted but have not yet
been compacted away. The O(N^2) complexity arises in two
cases:
- Limited scans: the extreme is a limited scan with a
limit of 1. Each successive scan traverses N, N-1, ...
locks.
- Mix of forward/reverse iteration in a single scan: A …
=> db: enhance Iterator with limited iteration mode

compaction.go, db.go, get_iter.go, ingest.go, iterator_test.go, level_checker.go, level_iter.go, level_iter_test.go, merging_iter_test.go, testdata/level_iter_seek
When SeekPrefixGE on the underlying file returns false
due to a bloom filter non-match, levelIter would skip
to the next file. This is wasteful if the upper bound
of the file is beyond the prefix. Additionally, it
defeats the optimization for sparse key spaces like
CockroachDB's lock table, where we try to reuse the
current position of the iterator -- by skipping to the
next file the subsequent SeekPrefixGE will again need
to reload the previous file.
This behavior was first noticed when diagnosing tpcc
slowness in CockroacbDB, where almost half the
overhead of seeking in the lock table could be
attributed to this (see
https://github.com/cockroachdb/cockroach/issues/62078
for details).
The benchmark numbers for bloom=true/with-tombstone=false
are the ones intended to benefit from this …
=> db: optimize levelIter for non-matching bloom filter

compaction.go, data_test.go, db.go, get_iter.go, ingest.go, internal/metamorphic/config.go, internal/metamorphic/generator.go, internal/metamorphic/meta_test.go, internal/metamorphic/ops.go, internal/metamorphic/parser.go, internal/metamorphic/retryable.go, iterator.go, iterator_test.go, level_checker.go, level_iter.go, level_iter_test.go, merging_iter_test.go, testdata/iterator, testdata/level_iter_seek
This optimization was identified as helping with the tpccbench regression
as discussed in https://github.com/cockroachdb/cockroach/issues/62078
See
https://github.com/cockroachdb/cockroach/issues/62078#issuecomment-803003586
for the risk discussion.
=> db: bump 21.1 to include levelIter optimization

docs/index.html, iterator.go, options.go
Currently, we always sample on the first read in a newly-opened
iterator, for determining read compactions. This is because the
zero value of `bytesUntilReadSample`
is always less than the bytes read. In cases where iterators are
short-lived, such as in ycsb workloads, this makes a greater proportion
of reads sampled than we'd like them to be, and it also makes any
changes to the sampling rate less effective.
This change updates Iterator to detect and skip the first time
it tries to sample a read on a newly-opened iterator.
Also makes a change to use `ints` instead of `uints` when
copying over options, to allow for disabling read sampling
by specifying a negative value for ReadSamplingMultiplier
if necessary.
When this change was tested with cockroachdb master, this
performance …
=> *: Skip first iteration of read sample

docs/index.html, iterator.go, options.go
Backport of #1098.
----
Currently, we always sample on the first read in a newly-opened
iterator, for determining read compactions. This is because the
zero value of `bytesUntilReadSample`
is always less than the bytes read. In cases where iterators are
short-lived, such as in ycsb workloads, this makes a greater proportion
of reads sampled than we'd like them to be, and it also makes any
changes to the sampling rate less effective.
This change updates Iterator to detect and skip the first time
it tries to sample a read on a newly-opened iterator.
Also makes a change to use `ints` instead of `uints` when
copying over options, to allow for disabling read sampling
by specifying a negative value for ReadSamplingMultiplier
if necessary.
When this change was tested with cockroachdb master, …
=> [crl-release-21.1] *: Skip first iteration of read sample

.travis.yml
Currently, only the master branch is built. This change
updates .travis.yml to also build the release branches after
every change.
=> *: Build release branches on travis CI

compaction.go, db.go, iterator_test.go, merging_iter.go, merging_iter_test.go, testdata/merging_iter
This is a 20.2 backport of #1085. While investigating cockroachlabs/support#898,
one node hit #1070:
The cherrypick didn't apply cleanly because of other recent iterator optimizations,
so I think we should probably wait for @sumeerbhola to give this a review before
merging.
```
name                                                            old time/op  new time/op  delta
IteratorSeqSeekPrefixGENotFound/skip=1/with-tombstone=false-16  1.42µs ± 4%  1.36µs ± 6%     ~     (p=0.095 n=5+5)
IteratorSeqSeekPrefixGENotFound/skip=1/with-tombstone=true-16   11.0ms ± 5%   0.0ms ± 6%  -99.99%  (p=0.008 n=5+5)
IteratorSeqSeekPrefixGENotFound/skip=2/with-tombstone=false-16  1.39µs ± 4%  1.36µs ±11%     ~     (p=0.310 n=5+5)
IteratorSeqSeekPrefixGENotFound/skip=2/with-tombstone=true-16   11.2ms ± 5% …
```
=> crl-release-20.2: db: mergingIter.SeekPrefixGE stops early if prefix cannot match

tool/data_test.go, tool/tool.go
Add `FS` option to set the filesystem to use by the introspection
tool. This replaces the prior `T.setFS` method which was used by the
datadriven tests.
=> tool: add FS option

iterator.go, options.go
PR #1098 stopped the first iteration of the read sampling
loop in a newly-created iterator from sampling. While
this had the desired effect on Cockroach's benchmarks,
this had a pretty significant regression on Pebble's own
YCSB benchamrks, as a lot of them have very short-lived
iterators.
This change tries to find a middle ground by sampling some
of the first reads, based on how many bytes were read. H/t
to Sumeer for coming up with this idea.
Another change is to move `1 << 4` off of the readBytesPeriod
onto the option, allowing us to control read sampling in
both directions by tweaking the option. Previously, read
sampling could only be made less frequent or disabled,
but not made more frequent.
Pebble ycsb benchmarks (old = before this change):
```
name                old ops/sec  new …
```
=> *: Sample some first iter reads based on size read

iterator.go, options.go
Backport of #1107.
---
PR #1098 stopped the first iteration of the read sampling
loop in a newly-created iterator from sampling. While
this had the desired effect on Cockroach's benchmarks,
this had a pretty significant regression on Pebble's own
YCSB benchamrks, as a lot of them have very short-lived
iterators.
This change tries to find a middle ground by sampling some
of the first reads, based on how many bytes were read. H/t
to Sumeer for coming up with this idea.
Another change is to move `1 << 4` off of the readBytesPeriod
onto the option, allowing us to control read sampling in
both directions by tweaking the option. Previously, read
sampling could only be made less frequent or disabled,
but not made more frequent.
Pebble ycsb benchmarks (old = before this change):
```
name …
```
=> [crl-release-21.1] *: Sample some first iter reads based on size read

db.go, get_iter_test.go, internal/manifest/version.go, internal/manifest/version_edit.go, level_checker.go, tool/lsm.go, tool/manifest.go, version_set.go
This change adds a new slice, SublevelFiles, to the Version struct
for use in creating iterators. This slice is just a shallow copy
of L0Sublevels.Files.
L0Sublevels now gets set to nil when a version is no longer the
newest version. This allows it to get GC'd and prevents the
large slices inside it from hogging memory when there are lots of
versions.
Fixes #1116.
=> internal/manifest: Let L0Sublevels get GCd on non-newest Versions

db.go, get_iter_test.go, internal/manifest/version.go, internal/manifest/version_edit.go, level_checker.go, tool/lsm.go, tool/manifest.go, version_set.go
21.1 backport of #1117
---
This change adds a new slice, SublevelFiles, to the Version struct
for use in creating iterators. This slice is just a shallow copy
of L0Sublevels.Files.
L0Sublevels now gets set to nil when a version is no longer the
newest version. This allows it to get GC'd and prevents the
large slices inside it from hogging memory when there are lots of
versions.
Fixes #1116.
=> [crl-release-21.1] internal/manifest: Let L0Sublevels get GCd on non-newest Versions

internal/humanize/humanize.go, metrics.go, metrics_test.go
Implement redact.SafeFormatter on `*pebble.Metrics` so that when
CockroachDB logs a `*pebble.Metrics`, it does not get redacted.
=> db: implement redact.SafeFormatter on Metrics

checkpoint.go, checkpoint_test.go, testdata/checkpoint, testdata/event_listener
This commit adds a new DB.Checkpoint option to flush and sync the WAL
during checkpoint construction.
This can be useful when performing writes with `Sync` set to `false`,
previously these might otherwise not have been included in the
checkpoint.
Fixes #795.
=> db: add option to flush WAL in Checkpoint

compaction.go, db.go, flush_external.go, flush_test.go, ingest.go, open.go, testdata/manual_flush
A flush isn't marked as complete (and flushing set to
false) until deleteObsoleteFiles returns. Currently,
deleteObsoleteFiles waits for other cleaning turns to complete
before doing its own cleaning. This could make flushes wait
for cleanup after large compactions, causing write stalls.
This change makes flushes move along and mark themselves as
completed if a cleaner job is already running, instead of waiting
for them. This allows for a lower impact on user-observed
write latency.
=> *: Don't block flushes on cleaning turns

compaction.go, db.go, flush_external.go, flush_test.go, ingest.go, open.go, testdata/manual_flush
21.1 backport of #1124.
---
A flush isn't marked as complete (and flushing set to
false) until deleteObsoleteFiles returns. Currently,
deleteObsoleteFiles waits for other cleaning turns to complete
before doing its own cleaning. This could make flushes wait
for cleanup after large compactions, causing write stalls.
This change makes flushes move along and mark themselves as
completed if a cleaner job is already running, instead of waiting
for them. This allows for a lower impact on user-observed
write latency.
=> [crl-release-21.1] *: Don't block flushes on cleaning turns

compaction.go, db.go, flush_external.go, flush_test.go, ingest.go, open.go, testdata/manual_flush
20.2 backport of #1124 
---
A flush isn't marked as complete (and flushing set to
false) until deleteObsoleteFiles returns. Currently,
deleteObsoleteFiles waits for other cleaning turns to complete
before doing its own cleaning. This could make flushes wait
for cleanup after large compactions, causing write stalls.
This change makes flushes move along and mark themselves as
completed if a cleaner job is already running, instead of waiting
for them. This allows for a lower impact on user-observed
write latency.
=> [crl-release-20.2] *: Don't block flushes on cleaning turns

compaction_picker.go, compaction_picker_test.go, testdata/compaction_output_file_size
Elision-only compactions mistakenly passed L6 as the base level when
constructing a picked compaction. This caused these compactions to be
initialized with a target file size of L1 (4 MB).
Fix #1097.
=> db: fix elision-only compaction max output size

compaction_picker.go, compaction_picker_test.go, testdata/compaction_output_file_size
Elision-only compactions mistakenly passed L6 as the base level when
constructing a picked compaction. This caused these compactions to be
initialized with a target file size of L1.
Fix #1097.
=> crl-release-20.2: db: fix elision-only compaction max output size

compaction_picker.go, compaction_picker_test.go, testdata/compaction_output_file_size
Elision-only compactions mistakenly passed L6 as the base level when
constructing a picked compaction. This caused these compactions to be
initialized with a target file size of L1.
Fix #1097.
=> crl-release-21.1: db: fix elision-only compaction max output size

iterator.go, iterator_test.go, testdata/iterator
The calls to internalIterator are tracked in Iterator
since we use both mergingIter and getIter in that role,
and we probably don't need these stats for background
work (compactions) involving mergingIter.
Informs https://github.com/cockroachdb/cockroach/issues/59069
Intended to unblock
https://github.com/cockroachdb/cockroach/pull/64503
=> db: add IteratorStats, for counting the work done in Iterator

options.go, options_test.go
Add serialization and parsing support for
`Experimental.CompactionDebtConcurrency`,
`Experimental.MinDeletionRate`, `Experimental.ReadCompactionRate`, and
`Experimental.ReadSamplingMultiplier` to the OPTIONS file.
Fixes #1144
=> db: add missing options to the OPTIONS file

compaction.go, compaction_picker.go, event.go, metrics.go, testdata/compaction_delete_only_hints, testdata/compaction_read_triggered, testdata/compaction_tombstones, testdata/event_listener
Fill in `CompactionInfo.Reason` with the kind of compaction: default,
move, delete-only, elision-only, or read.
Fixes #1142
=> db: flesh out CompactionInfo.Reason

compaction.go, compaction_picker.go, event.go, metrics.go, options.go, options_test.go, testdata/compaction_delete_only_hints, testdata/compaction_read_triggered, testdata/compaction_tombstones, testdata/event_listener
db: add missing options to the OPTIONS file
Add serialization and parsing support for
`Experimental.CompactionDebtConcurrency`,
`Experimental.MinDeletionRate`, `Experimental.ReadCompactionRate`, and
`Experimental.ReadSamplingMultiplier` to the OPTIONS file.
Fixes #1144
db: flesh out CompactionInfo.Reason
Fill in `CompactionInfo.Reason` with the kind of compaction: default,
move, delete-only, elision-only, or read.
Fixes #1142
=> db: flesh out CompactionInfo.Reason and add missing options

compaction.go, compaction_test.go, internal/manifest/l0_sublevels.go, internal/manifest/l0_sublevels_test.go, internal/manifest/testdata/l0_sublevels, testdata/compaction_inuse_key_ranges
Use the existing structure of L0 sublevels when calculating in-use key
ranges for L0. The sublevel intervals are already sorted and can be used
to efficiently construct the in-use key ranges. The max interval index
of overlapping intervals allows us to skip over swaths of the keyspace
that are known to be covered.
In a subsequent PR, I'll adapt the setupInuseKeyRange function to use
the in-use bounds of higher levels to seek among files in the lower
levels.
Informs #718.
=> internal/manifest: calculate L0 in-use key ranges using sublevels

compaction.go, compaction_test.go, ingest_test.go, internal/manifest/l0_sublevels.go, testdata/compaction_inuse_key_ranges
When computing in-use key ranges for a compaction, merge the intervals
for each level before descending to the next level. This allows for an
optimization where a level iterator may be seeked to the current
accumulated key range's end boundary. Since higher-level tables tend to
be broader, this should help reduce per-sstable work when setting up
flushes/compactions in stores with many sstables.
Pebble benchmarks are largely even.
```
name                old ops/sec  new ops/sec  delta
ycsb/D/values=1024    209k ±10%    206k ± 6%    ~     (p=0.312 n=10+14)
ycsb/C/values=1024    895k ±13%    940k ±16%    ~     (p=0.103 n=10+15)
ycsb/A/values=1024   80.8k ± 1%   80.6k ± 2%    ~     (p=0.643 n=10+15)
ycsb/B/values=1024    383k ± 7%    384k ± 7%    ~     (p=0.978 n=10+15)
ycsb/E/values=1024 …
```
=> compaction: merge in-use key ranges level-by-level

docs/index.html
Label the switch to the new AMI in the nightly benchmarks.
I'm not sure why exactly why throughput is down on the new AMI. The new AMI mounts ext4 with the 64-bit and metadata checksumming options, and uses Linux 5.4.0 instead of the previous 4.40.
fio shows higher average sequential write latency on the new AMI:
```
write: io=294774MB, bw=335387KB/s, iops=1310, runt=900001msec
clat (usec): min=73, max=1029, avg=81.63, stdev= 4.97
lat (usec): min=76, max=1043, avg=84.46, stdev= 5.57
```
vs
```
write: IOPS=1310, BW=328MiB/s (344MB/s)(288GiB/900001msec); 0 zone resets
clat (usec): min=103, max=677, avg=113.44, stdev= 2.36
lat (usec): min=105, max=678, avg=114.91, stdev= 2.38
```
=> docs: label new AMI in nightly benchmarks

compaction.go, db.go, db_test.go, log_recycler.go, log_recycler_test.go, metrics.go, metrics_test.go, open.go, testdata/metrics, version_set.go
Improve metrics surrounding disk space usage, by tracking physical WAL
sizes of both live and obsolete WALs, the OPTIONS file and the MANIFEST
file.
Expose a `(*pebble.Metrics).DiskSpaceUsage` function that handles
summing all the disk usage information from within `Metrics` into a
single value.
See cockroachdb/cockroach#56620.
=> db: improve disk usage accounting metrics

internal/base/comparer.go, sstable/block.go, sstable/writer_test.go
This commit optimizes `SharedPrefixLen` and its inlined version in `blockWriter.store` by "vectorizing" byte comparisons when computing the shared prefix length of two byte slices. As 6cd3310 noted, `blockWriter.store` is called for every single key written to a table, so micro-optimizations like this have an impact.
```
name               old time/op    new time/op    delta
Writer/Default-16     101ms ± 3%      94ms ± 3%  -6.73%  (p=0.000 n=19+20)
Writer/Zstd-16        257ms ± 5%     251ms ± 4%  -2.55%  (p=0.000 n=19+18)
```
On a node that was busy performing compactions, I found this inlined version of `SharedPrefixLen` to be responsible for **2.39%** of total CPU time before this change.
```
Type: cpu
Time: Jun 8, 2021 at 4:55am (UTC)
Duration: 5.12s, Total samples = 10.86s (212.21%) …
```
=> sstable: vectorize shared prefix byte comparison

vfs/disk_full.go, vfs/disk_full_test.go
Add an OnDiskFull VFS function that wraps a vfs.FS with an
implementation that inspects errors from write operations, looking for
errors indicating that the disk is full.
If the FS observes a full disk, it invokes the provided callback,
blocking all incoming writes from proceeding until the callback returns.
The write that encountered the ENOSPC, plus any concurrent writes that
also encountered an ENOSPC all retry their writes exactly once after the
callback completes.
This is intended to be used to automatically manage a ballast file. A
client may remove the ballast file within the callback. The retried
writes will succeed, consuming from the newly available disk space from
the ballast. The callback may also asynchronously trigger processes to
handle the out-of-disk condition, like …
=> vfs: add OnDiskFull VFS wrapper

vfs/disk_usage_linux.go, vfs/disk_usage_unix.go
Some environments reserve free disk blocks for root users, and a
non-root user has less disk space available than the value calculated
from `Bfree` indicates. Note that CockroachDB already uses `Bavail` for
computing store capacity metrics, although it relies on the
github.com/elastic/gosigar module for the calculation.
https://github.com/elastic/gosigar/blob/v0.14.1/sigar_unix.go#L23
See facebook/rocksdb#8370.
=> vfs: use Bavail in GetFreeSpace

compaction.go, internal/errorfs/errorfs.go, vfs/disk_full.go, vfs/disk_heath_test.go, vfs/disk_usage_linux.go, vfs/disk_usage_unix.go, vfs/disk_usage_windows.go, vfs/mem_fs.go, vfs/vfs.go, vfs/vfs_test.go
Refactor GetFreeSpace into GetDiskUsage, exposing a total disk space
capacity value too. I anticipate using this within CockroachDB, rather
than using the gosigar package.
=> vfs: refactor GetFreeSpace into GetDiskUsage

compaction.go
just tiny clean up some dead code found by reading code :)
it seems  `==` condition should be unreachable after https://github.com/cockroachdb/pebble/pull/352, maybe we can delete
=> compaction: clean up useless code

.travis.yml
This adds go 1.16 to the TravisCI build/test matrix.
=> travis: add go 1.16 CI

.travis.yml
Removed all go1.15.x test variants except `go1.15.x-linux`, similar to
https://github.com/cockroachdb/pebble/pull/983.
=> Clean up travis CI config

.github/workflows/ci.yaml
The only difference with Travis is that I added `-v` to `go test` for Windows.
It won't run in this repo until it's on `master`, so I pushed it to my repo too: https://github.com/rail/pebble/actions/runs/980594299
=> Use GitHub Actions

options.go, options_test.go, table_cache.go, testdata/metrics
Users should be able to control the number of cache shards.
In my case, I've got 30k+ idle goroutines on my 64cores server with 500~600 (logically partitioned) db instances.
=> make number of cache shards configurable

event.go, event_listener_test.go
`TeeEventListener` was failing to set a `DiskSlow` or a `TableStatsLoaded` callback. This commit fixes this and adds testing to ensure that the following three functions all avoid this class of bug going forward:
- `(*EventListener).EnsureDefaults`
- `MakeLoggingEventListener`
- `TeeEventListener`
=> Ensure EventListener functions set all callbacks

tool/manifest.go, tool/testdata/manifest_dump
The version edit index is useful for correlating a version edit to the
corresponding version edit in the LSM visualizer.
Related to #1177.
=> tool: include version edit index in dump output

tool/manifest.go, tool/testdata/manifest_summarize
Add a summarize command to the manifest tool. This command uses the most
recent sstable creation timestamp to estimate the current time of a
version edit and buckets statistics about version edits by hour.
Example output:
```
<...snip...>
_______L0_______L1_______L2_______L3_______L4_______L5_______L6_____TOTAL
2021-07-12T23:00:00Z
Ingest+Flush      744 K        .        .        .        .        .        .    744 K
Ingest+Flush    211 B/s        .        .        .        .        .        .  211 B/s
Compact (out)      744 K        .        .        .        .        .        .    744 K
Compact (out)    211 B/s        .        .        .        .        .        .  211 B/s
2021-07-13T00:00:00Z
Ingest+Flush      596 K        .        .        .        .        .        .    596 K …
```
=> tool: add manifest summarize command

vfs/mem_fs.go, vfs/vfs.go
Export an `ErrUnsupported` error that may be used with `errors.Is` by
clients to handle unsupported errors differently. I anticipate using
this within CockroachDB in codepaths that require disk usage capacity
calculations. Today, those codepaths use brittle mechanisms for
detecting whether the store's filesystem is in-memory. I'd like to
refactor these callsites to unconditionally call `GetDiskUsage`,
treating `ErrUnsupported` as we do in-memory stores today.
=> vfs: export ErrUnsupported

Makefile
[Bash brace expansion][1] requires "at least one unquoted comma or a valid
sequence expression", else it treats the filename as including the
curly-braces.
Remove the redundant curly-braces.
[1]: https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html
=> build: fix mod-update target

error_test.go, internal/errorfs/errorfs.go, internal/metamorphic/meta_test.go, open.go, open_test.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener
Write out the new manifest file before creating a new WAL file during
Open. Previously, a crash between the creation of the WAL and the
MANIFEST could leave the second most recent WAL with an unclean tail.
The unclean tail would be considered corruption on a subsequent Open.
See cockroachdb/cockroach#68319.
=> db: write manifest before creating WAL during Open 

internal/manifest/l0_sublevels.go
When allocating files in a manifest version to one or more intervals,
the current implementation makes two passes over the covered intervals.
The work done in the second pass can be moved into the first pass.
Remove superfluous second for-loop.
Minor cleanup to reuse an existing variable to avoid indexing into the
slice of ordered intervals.
=> internal/manifest: remove superflous for-loop

compaction.go, db_test.go, options.go, testdata/event_listener
We want to be able to preserve some older manifests for debugging purposes.
By default we use 128MB manifests, so this shouldn't cause too much clutter.
Resolves: https://github.com/cockroachdb/pebble/issues/1184
=> pebble: Preserve one previous manifest

error_test.go, internal/errorfs/errorfs.go, internal/metamorphic/meta_test.go, open.go, open_test.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener
CockroachDB 21.1 backport of #1212.
----
Write out the new manifest file before creating a new WAL file during
Open. Previously, a crash between the creation of the WAL and the
MANIFEST could leave the second most recent WAL with an unclean tail.
The unclean tail would be considered corruption on a subsequent Open.
See cockroachdb/cockroach#68319.
=> crl-release-21.1: db: write manifest before creating WAL during Open

error_test.go, internal/errorfs/errorfs.go, internal/metamorphic/meta_test.go, open.go, open_test.go, testdata/checkpoint, testdata/cleaner, testdata/event_listener
CockroachDB 20.2 backport of #1212.
----
Write out the new manifest file before creating a new WAL file during
Open. Previously, a crash between the creation of the WAL and the
MANIFEST could leave the second most recent WAL with an unclean tail.
The unclean tail would be considered corruption on a subsequent Open.
See cockroachdb/cockroach#68319.
=> crl-release-20.2: db: write manifest before creating WAL during Open 

vfs/syncing_file_test.go, vfs/vfs.go, vfs/vfs_test.go
Previously, vfs.FS.Create's documented contract was to truncate the file
at the named path if it exists. This was the contract implemented by
vfs.Default but not the contract implemented by *vfs.MemFS, which
replaced the existing file with a new inode. This commit updates the
documented contract and the vfs.Default implementation to match
*vfs.MemFS.
Removing and recreating the file is more resistant to misuse in the
presence of hardlinks. With this change, only `ResuseForWrite` may be
used to open and modify an existing file limiting the surface area for
accidental modification of immutable sstables.
Unfortunately, I don't think there's a way to make the removal and
creation atomic, like `O_TRUNC` was, so there's a now a loop within
`Create` to handle concurrent operations from other …
=> vfs: modify Create to remove and create existing files

cmd/pebble/ycsb.go
randvar.NewWeighted eventually leads to  us calling rand.NewSource.
But Sources created using NewSource aren't safe for concurrent use
and I was seeing a race in the ycsb workload. While the race was
only in the workload, it's worth a fix.
From the go docs,
```
The default Source is safe for concurrent use by multiple goroutines,
but Sources created by NewSource are not.
```
Fixes: https://github.com/cockroachdb/pebble/issues/1222
=> workload: Fix NewSource race in the ycsb workload.

internal/manifest/l0_sublevels.go, internal/manifest/testdata/l0_sublevels
Add three additional test cases to the data-driven test for
`TestL0Sublevels` that mirror the examples provided in the in-line
documentation in `l0_sublevels.go` demonstrating the compaction logic.
Add additional documentation and test case covering the scenario where a
file in L0.0 overlaps with a file in LBase. In this case, the file would
not be included in the compaction. In the case where the overlapping
file in LBase does not exist, the file in L0.0 is included.
=> internal/manifest: add test coverage for L0-sublevel examples

compaction.go, compaction_test.go, options.go
Currently, in cases where invalid keys are present in a file that is
being created or deleted as part of a compaction, either due to
corruption or programmer error, pebble will silently propagate the
corruption, which may not be detected until much later. At such time,
the corruption may have propagated to multiple files.
Add a new experimental option, `CompactionKeyValidationFunc` that when
provided will be used to validate both the smallest and largest key in
both new and deleted files in `versionEdit`s constructed as part of a
compaction.
In the case of a key that fails validation, as there is rarely any
effective remediation that can be taken, pebble will log a fatal error
and exit.
The new option is marked as experimental. In the case where no
validation function is provided, no …
=> compaction: add key validation for compacted files

compaction_test.go, db_test.go
Our DB finalizer currently doesn't run consistently, or in some
situations, it doesn't seem to run ever. This is showcased in this
pr: #1234.
However, the finalizer starts to runs consistently in one of the cases described in the pr
linked above, and detected some leaks.
The tests here are the ones which were causing the failures. So, we
gracefully cleanup in these tests by calling db.Close. There could be
other tests which aren't calling `db.Close`, but the tests pass for now.
=> pebble: call db.Close for these tests.

db_test.go
TestCacheEvict fails infrequently because the cache size isn't 0
at the end of the test. I believe this is due to files getting deleted
asynchronously.
If we call db.Close before checking the cache size, then the files
should be deleted because db.Close deletes the files.
Resolves: #1239
=> pebble: Unflake TestCacheEvict

vfs/atomicfs/marker.go, vfs/atomicfs/marker_test.go, vfs/atomicfs/testdata/marker
Add an AtomicMarker type that may be used for maintaining a 'marker' on
a single file and moving it atomically. This is useful when code
requires atomically switching from one file to another.
This PR would be in replace of #1244.
=> vfs: add AtomicMarker

vfs/atomicfs/marker.go, vfs/atomicfs/marker_test.go, vfs/atomicfs/testdata/marker
Add a NextIter method that allows clients to query an atomic marker for
its next iteration sequence number. In some usages, client code needs to
create a new file and then move the marker to the new file's path.
Creating the new file must not overrwrite the existing marked file.
Incorporating the marker's iteration number into the filename provides a
simple scheme client code may follow.
=> vfs/atomicfs: add Marker NextIter method

internal/metamorphic/generator.go, internal/metamorphic/meta_test.go, internal/metamorphic/ops.go, internal/metamorphic/options.go, internal/metamorphic/parser.go
Generated SINGLEDEL operations are eligible for transformation into less
restrictive DELETE operations.
Transform a fixed percentage of SINGLEDEL operations at generation time
into DELETEs to further exercise the delete execution paths.
Related to cockroachdb/cockroach#69414.
=> metamorphic: transform percentage of SINGLEDEL ops to DELETE ops

sstable/reader.go
In all the instances in `Reader.readBlock` where we return
an error, we free the cache handle before returning the error.
One exception to this was the switch for the checksum type,
so this change adds that Free there as well.
=> sstable: Free cache value when checksum type is corrupt

sstable/testdata/writer, testdata/compaction_iter, testdata/level_checker
Delete keys are not required to have accompanying values. Though they
may in practice, the presence of values for delete or single-delete
records in test data can be confusing.
Remove instances from test data where a DEL or SINGLEDEL has a value
set.
=> testdata: remove values from deletes

db.go, db_test.go, open.go, options.go, options_test.go, table_cache.go, table_cache_test.go
Previously, a table cache was created for each store and
the `MaxOpenFiles` for each store would be configured to be
a process's file descriptor limited divided equally among
all the stores. This prevents us from having larger cache sizes
for more active stores.
With a shared table cache, we don't have to configure the
table cache sizes to be equal.
Resolves: #1178
=> pebble: Make the table cache shareable among stores

compaction_iter.go, compaction_iter_test.go, internal/cache/value_invariants.go, iterator_test.go, sstable/block.go
To increase confidence that use-after-free bugs are not present on
compaction codepaths, use the `invalidatingIter` wrapper to mutate the
previous key and value during iteration.
Alter the `invalidatingIter` to avoid zeroing range deletion key / value
pairs, which aligns with the current assumption
`(*compactionIter).Next()`.
Add an in-line comment to point out that storage of a reference to the
previous key / value pairs is safe for range deletion keys during
compaction iteration.
Enable some previously dead code to mutate released byte slices. This
allows for easier detection of use-after-free-type bugs.
=> db: improve use-after-free test coverage for compactions

db.go, open.go
To configure the shared TableCache from cockroach, we need to export
NumNonTableCacheFiles, MinTableCacheSize  to make cache size calculations
from cockroach.
=> pebble: Export table cache related constants for use in cockroach

cmd/pebble/db.go
In the cmd/pebble benchmark tool, configure the database to use the
most-recent format major version.
=> cmd/pebble: specify format major version

compaction.go, compaction_test.go, options.go
Previously, if a compaction or flush errored and returned a nil version
edit while a `KeyValidationFunc` was configured, `validateVersionEdit`
would panic. This commit add a nil check, plus configures a no-op
KeyValidationFunc default.
Informs cockroachdb/cockroach#70443.
=> compaction: fix nil pointer during errored compactions

compaction.go, compaction_test.go, options.go
Previously, if a compaction or flush errored and returned a nil version
edit while a `KeyValidationFunc` was configured, `validateVersionEdit`
would panic. This commit add a nil check, plus configures a no-op
KeyValidationFunc default.
Backport of #1281.
=> release-21.2: compaction: fix nil pointer during errored compactions

internal/cache/clockpro.go
When we set a value in the cache, the size of the  value isn't necessarily
the same size as the size of its previous value. We use the size of the
latest value when we're setting an entry which was either hot or cold.
After this PR, we also use the size of the latest value when setting an
entry which was in its test period.
=> internal/cache: update entry size in the etTest to etHot transition

event.go, event_listener_test.go
Previously, if a nil logger was passed into
`EventListener.EnsureDefaults`, a call to `BackgroundError` would panic
with a nil pointer. In CockroachDB we use `TeeEventListener`, which
calls `EnsureDefaults(nil)` on its two event listeners. One of these
didn't have `BackgroundError` set and would panic when a background
error occurred.
=> db: handle nil logger in EventListener.EnsureDefaults

internal/cache/clockpro.go, internal/cache/clockpro_test.go
We try to keep shard.coldTarget in the range [0, shard.targetSize()].
This can be seen here:
https://github.com/cockroachdb/pebble/blob/master/internal/cache/clockpro.go#L172,
and here:
https://github.com/cockroachdb/pebble/blob/master/internal/cache/clockpro.go#L465.
However, when we call Cache.Reserve, we end up either increasing or decreasing,
shard.reservedSize, which in turn changes the shard.targetSize(). But we don't
update shard.coldTarget to keep it <= shard.targetSize().
shard.coldTarget not being updated, can cause unnecessary evictions from the cache
as shown in the test.
=> internal/cache: prevent coldTarget from becoming greater than targetSize

internal/cache/clockpro.go
**internal/cache: add hot, cold, test entry counts**
Add hot, cold and test counts to block cache shard. Use `coldCount` to
assert that `coldSize` matches expectations.
This is intended to help gain more insight out of any future
reproductions of the infinite loop encountered in
cockroachdb/cockroach#70154
**internal/cache: include sizeCold in runHandCold stack traces**
Add sizeCold as a parameter to runHandCold so that stack traces from any
future cockroachdb/cockroach#70154 reproductions will include it.
These are @petermattis's ideas from https://github.com/cockroachdb/cockroach/issues/70154#issuecomment-923291288.
=> internal/cache: add additional asserts, debugging context

event.go, event_listener_test.go
Previously, if a nil logger was passed into
`EventListener.EnsureDefaults`, a call to `BackgroundError` would panic
with a nil pointer. In CockroachDB we use `TeeEventListener`, which
calls `EnsureDefaults(nil)` on its two event listeners. One of these
didn't have `BackgroundError` set and would panic when a background
error occurred.
Backport of #1283.
=> crl-release-21.2: db: support nil logger in EventListener.EnsureDefaults

compaction_iter.go, compaction_test.go, internal/base/internal.go, internal/metamorphic/config.go, internal/metamorphic/generator.go, internal/metamorphic/key_manager.go, internal/metamorphic/key_manager_test.go, internal/metamorphic/options.go, testdata/compaction_iter_set_with_del, testdata/manual_compaction, testdata/manual_compaction_set_with_del, testdata/singledel_manual_compaction, testdata/singledel_manual_compaction_set_with_del
Currently, the metamorphic test generator tracks the state of keys that
it generates to determine whether or not certain keys can be used for
specific operations. Specifically, keys that have been set once in the
database are eligible to be SingleDeleted. Future enhancements to the
test suite will likely introduce other desirable sequences of operations
that rely on tracking the state of certain keys through the metamorphic
test.
State tracking for keys is currently embedded directory onto the
`generator` struct. Additional fields that are to be used for state
tracking would continue to complicate the already sizable struct. There
is also significant cognitive overhead with the existing state tracking
for keys.
This commit introduces the concept of a "key manager", dedicated to
tracking …
=> metamorphic: add key manager abstraction and SetWithDelete bug fix

checkpoint.go, checkpoint_test.go, cmd/pebble/compact_new.go, compaction.go, compaction_test.go, db.go, db_test.go, filenames.go, format_major_version.go, ingest.go, ingest_test.go, internal/base/filenames.go, internal/base/filenames_test.go, internal/manifest/version.go, internal/manifest/version_test.go, open.go, table_cache.go, table_cache_test.go, tool/db.go, version_set.go
Split the MakeFilename utility into two variants, one that returns just
the base filename and one that returns the dirname-prefixed filepath.
=> internal/base: split MakeFilename into MakeFile{path,name}

ingest.go
Ingested sstables have all-zero sequence numbers. A sequence number
isn't assigned to the ingested sstables until during Ingest. The
sequence number assigned is persisted by updating the file metadata that
is written to the manifest. When an ingested sstable must be read, the
reader detects that the smallest sequence number equals the largest
sequence number and on-the-fly rewrites the sstable's keys to that
sequence number.
This comment has confused me for a while. It suggests that
`ingestUpdateSeqNum` updates the ingested sstables' properties to record
the assigned sequence number. There is a global sequence number
property, but it's never updated on-disk. Instead, its value is replaced
in-memory when the sstable metadata's smallest and largest sequence
numbers are equal.
=> db: clarify global seqnum comment within Ingest

table_cache.go
I see a small performance win with this pr, when I compare it to master.
tableCacheOpts is shared by every single shard. The theory is that
constant updates to the fields in the tableCacheOpts was causing those
fields, and the surrounding fields to be evicted from the CPU caches,
which was causing a slowdown compared to the table cache performance
before the shared table cache was introduced. When the table cache
was not shared, the fields in the tableCacheOpts weren't shared either.
```
arjunnair@Arjuns-MacBook-Pro abh % benchstat stat_master stat_tc
name              old ops/sec  new ops/sec  delta
ycsb/B/values=64    809k ± 4%    852k ± 7%  +5.28%  (p=0.000 n=9+10)
name              old read     new read     delta
ycsb/B/values=64   27.5G ±16%   27.8G ±16%    ~     (p=0.780 n=9+10) …
```
=> pebble: make tableCacheOpts read-only

compaction_picker.go, compaction_test.go, testdata/compaction_delete_only_hints
Currently, when an elision-only compaction is picked, the smallest /
largest keys on the `pickedCompaction` struct are not set. This can
result in a situation where deletion hints are not correctly removed.
This in turn can result in entries being incorrectly removed from L6
sstables when the elided sequence numbers cause a compaction hint to be
retained (as `h.start` is always compares as greater-than the nil struct
for the smallest user key in the picked compaction).
Set the smallest and largest key on an elision-only `pickedCompaction`.
Add an additional data-driven test to guard against regression.
Fixes #1285.
Informs #1298.
=> db: set smallest / largest keys for elision-only compactions

internal/metamorphic/test.go
Support the use of non memFS file systems in the restartDB
command.
=> internal/metamorphic: prevent panic in restartDB command

compaction_picker.go, compaction_test.go, testdata/compaction_delete_only_hints
This is a backport of #1293.
There was some minor drift in `compaction_picker.go` that needed some addressing.
---
Currently, when an elision-only compaction is picked, the smallest /
largest keys on the `pickedCompaction` struct are not set. This can
result in a situation where deletion hints are not correctly removed.
This in turn can result in entries being incorrectly removed from L6
sstables when the elided sequence numbers cause a compaction hint to be
retained (as `h.start` is always compares as greater-than the nil struct
for the smallest user key in the picked compaction).
Set the smallest and largest key on an elision-only `pickedCompaction`.
Add an additional data-driven test to guard against regression.
Fixes #1285.
Informs #1298.
=> crl-release-20.2: db: set smallest / largest keys for elision-only compactions

compaction_test.go, data_test.go, testdata/compaction_delete_only_hints
A previous PR, #1293, removed a DB option that disabled table stat
collection for `TestCompactionDeleteOnlyHints`. Without this option
disabled, the test becomes racy, given the way in which table stats are
collected asynchronously, and how deletion hints can be updated based on
these hints.
Add an option to `define`, `enable-table-stats` that allows a
data-driven test to set this value.
Bring back the explicit disabling of table stats, and selectively enable
for the test case that relies on the stats being present.
=> db: disable table stats by default in TestCompactionDeleteOnlyHints

.github/workflows/ci.yaml
In order to increase confidence that backported changes to release
branches continue to compile and function as expected, enable CI on PRs
against, and and merges into release branches.
=> ci: enable CI for release branches

batch_test.go, cmd/pebble/compact.go, compaction_picker_test.go, compaction_test.go, flushable.go, go.mod, internal/arenaskl/arena.go, internal/arenaskl/node.go, internal/base/comparer.go, internal/base/filenames.go, internal/cache/robin_hood_test.go, internal/manifest/l0_sublevels.go, internal/metamorphic/ops.go, internal/pacertoy/pebble/main.go, internal/pacertoy/rocksdb/main.go, internal/rangedel/iter_test.go, level_checker.go, mem_table_test.go, metrics.go, open_test.go, sstable/table.go, tool/db.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go
This is a backport of #967 to 20.2, fixing the failing `TestLint` check.
=> crl-release-20.2: Fixing linting issues

compaction_test.go, data_test.go, testdata/compaction_delete_only_hints
This is a backport of #1305 for 21.2.
---
A previous PR, #1293, removed a DB option that disabled table stat
collection for `TestCompactionDeleteOnlyHints`. Without this option
disabled, the test becomes racy, given the way in which table stats are
collected asynchronously, and how deletion hints can be updated based on
these hints.
Add an option to `define`, `enable-table-stats` that allows a
data-driven test to set this value.
Bring back the explicit disabling of table stats, and selectively enable
for the test case that relies on the stats being present.
=> crl-release-21.2: db: disable table stats by default in TestCompactionDeleteOnlyHints

.github/workflows/ci.yaml
Backport of #1304 to 21.2.
---
In order to increase confidence that backported changes to release
branches continue to compile and function as expected, enable CI on PRs
against, and and merges into release branches.
=> crl-release-21.2: ci: enable CI for release branches

.github/workflows/ci.yaml
Backport of #1304 to 21.1.
---
In order to increase confidence that backported changes to release
branches continue to compile and function as expected, enable CI on PRs
against, and and merges into release branches.
=> crl-release-21.1: ci: enable CI for release branches

.github/workflows/ci.yaml
Backport of #1304 to 20.2.
---
In order to increase confidence that backported changes to release
branches continue to compile and function as expected, enable CI on PRs
against, and and merges into release branches.
=> crl-release-20.2: ci: enable CI for release branches

sstable/raw_block.go
Remove an unused err field on rawBlockIter. A raw block iterator never
errors.
=> sstable: remove unused rawBlockIter err field

batch.go, batch_test.go
Refactor MakeBatchReader into ReadBatch, which returns a batch reader
and the entry count within the batch. This will allow the removal of
code within CockroachDB's storage package that parses the count out of a
batch manually. The CockroachDB storage package should be insulated from
Pebble batch serialization.
=> db: expose facility for retrieving batch count

sstable/options.go, sstable/table.go
Currently, there exists an exported `type sstable.ChecksumType uint32`,
intended to be used as an enum, in addition to an unexported `byte` used
for the on-disk representation.
Consolidate the two types, changing the exported type to be an alias for
`byte` and removing the unexported type.
=> sstable: consolidate checksum types

db.go, open.go
This will be used by cockroach when calculating the table cache
size for a shared cache, instead of duplicating the logic.
=> db: Expose logic to calculate the table cache size

mem_table.go
Rename the memtable's `rangeDelCache` and `rangeDelFrags` types to
`keySpanCache` and `keySpanFrags` so they may be used for caching range
key fragments too.
In addition to the pure renames, I made a small refactor to decouple the
dependency on `memTable.tombstones` by adding a pointer to the skiplist
in a `keySpanCache` field.
=> db: genericize rangeDel{Cache,Frags} into keySpan{Cache,Frags}

compaction_test.go, get_iter_test.go, mem_table.go, mem_table_test.go, read_compaction_queue.go, sstable/compression_cgo.go, sstable/compression_cgo_test.go, sstable/compression_nocgo.go, sstable/compression_nocgo_test.go, sstable/reader.go, sstable/reader_test.go
Move some code that's only used within test builds into test files. In
the case of `(*memTable).close`, remove it altogether because it's a
no-op.
For some reason I don't understand, the `staticcheck` linter surfaced
these on a work-in-progress branch of mine that didn't touch anything
related to these, but doesn't surface them on master.
```
mem_table.go:154:20: func (*memTable).get is unused (U1000)
mem_table.go:265:20: func (*memTable).close is unused (U1000)
mem_table.go:270:20: func (*memTable).empty is unused (U1000)
read_compaction_queue.go:29:32: func (*readCompactionQueue).at is unused (U1000)
sstable/compression_cgo.go:24:7: const useStandardZstdLib is unused (U1000)
sstable/reader.go:2060:18: func (*Reader).get is unused (U1000)
```
=> *: move test-only code into test files

.gitignore
Add a .gitignore.
Ignore pprof artifacts generated by benchmarks.
=> Add .gitignore; ignore profiling artifacts

cmd/pebble/write_bench.go
Match the values that Cockroach Admission Control uses as limits for L0
sub-level file and level count.
Split out the defaults to constants, with associated comment explaining
the reasoning for using the particular values.
Related to #1369.
=> cmd: lower the default L0 sub-level count for write benchmarks

internal/mkbench/testdata/write-throughput/summary.json, internal/mkbench/write.go
Currently, the benchmark data parser for the write-throughput benchmarks
attempts to infer the benchmark workload name (e.g. `write/values=1024`)
from the directory structure.
Match the behavior of the YCSB benchmark data parser by using the raw
data from the file.
Flatten a nested map used as a "multi-map" by instead using a struct as
the map key.
Related to #1369.
=> mkbench: use benchmark data to infer names

sstable/writer.go
Currently, `sstable.(*Writer).Close`, calls `errors.New` on the happy
path when finalizing an sstable. While this call is relatively
inexpensive and infrequent, it is unnecessary.
Extract out error definition into a package-level variable that can be
referenced throughout the course of the program's runtime.
=> sstable: use package-level error in place of runtime allocation

.github/workflows/ci.yaml, Makefile
As dependencies are added and updated, the go.mod and go.sum file can
drift. This can result in unnecessary "noise" being introduced into
diffs.
Add a CI check that ensures that running `go mod tidy` on the repo
results in no change to the mod and sum files.
=> ci: add tidy-check lint

sstable/writer.go, sstable/writer_test.go
While working on a separate change that included passing a large number
of pre-generated blocks all to `addIndexEntry` in a tight loop, some of
the allocations it was doing per block flushed became much more apparent in
profiles. By batch allocating keys used as separators, and by adjusting
the buffering of filled sub-index blocks to store their finished byte
representation (also batch allocated) with relevant details, rather than
the whole block writer, that blockWriter can instead be reused, which 
importantly allows reuse of its allocated buffers eliminating a significant source of
allocations.
There overall performance impact to Writer is negligible but was more pronounced 
in another change that flushes blocks in a tight loop.
```
name …
```
=> sstable: reduce writer allocations during index flushing

docs/css/app.css, docs/index.html, docs/js/app.js, docs/js/write-throughput.js
Add a new section to the Pebble Benchmarks page to track the
write-throughput performance over time.
The new section contains a pane on the left that displays the summary
data over time; one datapoint representing the average calculated
sustainable write-throughput (in ops/sec) over all workers participating
in the run.
The summary pane also allows the user to click on an individual day's
data to bring up all of the raw datapoints from all workers
participating in the run for the given day. The detail view shows the
write load for each worker over the duration of the benchmark. This is
intended to highlight the different write-performance characteristics of
the DB over time (i.e.  as various levels open up, etc.).
Initially the only benchmark configuration is the `write/values=1024` …
=> docs: add write-throughput visualization

sstable/writer.go
This reverts commit bd9b59c88beab562413d8049aa8f33263da47a86.
It was discovered during the nightly Pebble benchmark runs that this
commit can result in unbounded memory usage under certain conditions.
Specifically, the YCSB `values=1024` workload failed with an out of
memory error (tracked in cockroachdb/cockroach#73118), and the
write-throughput benchmark exhibited very poor performance after three
hours of runtime, and ultimately did not complete (tracked in
cocroachdb/cockroach#73116).
As a simple reproducer, running YCSB F for 10 minutes with values of
size 1024 bytes shows that prior to the change, memory usage was
approximately 4GB (RSS). With this change, memory usage was at least
20GB, and seemed to be growing steadily. This lines up with the observed
roachtest OOM.
Reproducer, on …
=> Revert "sstable: reduce allocations during index flushing"

sstable/data_test.go, sstable/reader_test.go, sstable/suffix_rewriter.go, sstable/suffix_rewriter_test.go, sstable/testdata/rewriter, sstable/writer.go, sstable/writer_test.go
Pulling this out of #1377, as it is just the Reader->Writer loop implementation,
along with the associated tests and benchmark, to get that benchmark in place
for any other Reader or Writer performance work to check, and so #1377 can then
be just about the parallel-block version.
----
This adds a function to the sstable package that can replace some suffix
with another suffix from every key in an sstable, assuming enforcing
that the sstable consists of only Sets.
For now, this is done by opening a new Writer and simply iterating every
key from the original SST using a reader, replacing the suffix and then
passing it to the writer. However a follow-up change may improve this
implementation by leveraging knowledge of the reader and writer internal
details, such as processing data blocks in …
=> sstable: add RewriteKeySuffixes function

sstable/block_property.go, sstable/block_property_test.go, sstable/compression_cgo.go, sstable/compression_cgo_test.go, sstable/compression_nocgo.go, sstable/compression_nocgo_test.go
Noticed I was seeing spurious diffs when making unrelated edits to files in this
package, so just running everything though 'gofmt -s -w', as of go 1.17.2.
=> sstable: gofmt -s for go 1.17

batch.go, batch_test.go, db.go, internal.go, internal/base/internal.go, internal/base/internal_test.go, internal/rangekey/rangekey.go, internal/rangekey/rangekey_test.go, mem_table.go, range_keys_test.go
Add key kinds for range key sets, unsets and deletes. Add corresponding methods
to the Batch, behind an experimental type. With this commit, these keys may be
encoded into a batch but are discarded when committed.
=> batch: add RangeKey{Set,Unset,Delete} methods

internal/base/comparer.go
Document the new Split requirements necessary for range keys support. See #1341.
=> internal/base: document new Split requirements
