cockroachdb/pebble

- sstable/block/block.go
- sstable/colblk/index_block.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/rowblk/rowblk_index_iter.go
- sstable/rowblk/rowblk_iter.go
Remove the pointer constraints from block.DataBlockIterator and block.IndexBlockIterator interfaces. Instead define new constraints internal to the sstable package adjacent to where they're required. The block.DataBlockIterator and block.IndexBlockIterator interfaces can be used as ordinary interfaces without compile-time knowledge of the type where it's more convenient to do so.
> sstable: separate [Index|Data]BlockIterator interfaces and constraints

- compaction.go
- event_listener_test.go
- ingest_test.go
- internal/compact/spans.go
- level_checker_test.go
- level_iter_test.go
- merging_iter_test.go
- range_del_test.go
- sstable/copier.go
- sstable/random_test.go
- sstable/reader_test.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
- sstable/table_test.go
- sstable/writer.go
- sstable/writer_test.go
- table_stats_test.go
- version_set_test.go
Previously the NewRawWriter type returned a concreate *RawRowWriter type, and some callers (including NewWriter) relied on this. This commit updates the callers appropriately to remove the dependency.
> sstable: return interface type from NewRawWriter

- internal/treesteps/data.go
- internal/treesteps/node_state.go
- internal/treesteps/testdata/segment_tree
- internal/treesteps/tree_steps.go
- internal/treesteps/tree_steps_test.go
This commit introduces a new piece of infrastructure that allows
generating step-by-step illustrations of how an operation propagates
down a hierarchical structure and how the state of the nodes in the
structure changes.
The infrastructure is designed so that no extra arguments need to be
plumbed through the operation stack. We achieve that by maintaining a
global list of nodes that are part of a hierarchy for which we are
"recording".
See `tree_steps_test.go` for sample usage and `testdata/segment_tree`
for sample recordings.
The goal is to integrate this with the iterator stack (in particular
the `mergingIter`, `levelIter`, and sstable iterators). The
integration will be conditioned on `invariants.Enabled` so we won't
add any overhead in production.
> treesteps: infrastructure for visualization of operations on trees

- sstable/reader.go
When opening an sstable and reading the metaindex, we loop over the known filters looking for a block with a matching name. Previously there was an inner loop that statically only ever had one iteration. This inner loop was a vestige from early Pebble's support for 'block-based' bloom filters. There's only ever been a single filter type since #32.
> sstable: remove unnecessary loop while identifying filter block

- sstable/block/compression_cgo.go
- sstable/block/compression_test.go
This test occasionally failed with an index out of range.
Fixes #3922
> sstable/block: fix compression roundtrip test

- db.go
- internal/cache/block_map.go
- internal/cache/entry_normal.go
- internal/cache/value_cgo.go
- internal/cache/value_invariants.go
- internal/manual/manual.go
- internal/manual/manual_cgo.go
- internal/manual/manual_nocgo.go
- mem_table.go
- metrics.go
- metrics_test.go
- open.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/data_test.go
- tool/testdata/db_lsm
This commit adds a breakdown of cgo memory usage in Pebble. This will
show up as part of the periodic LSM metrics dump in the logs.
Fixes #3908
> manual: add cgo memory accounting

- sstable/rowblk_writer.go
- sstable/writer.go
Remove the IsStrictObsolete method from the RawWriter interface. NewWriter is given the WriterOptions and can remember WriterOptions.IsStrictObsolete itself, obviating the need for propagating it through the RawWriter interface.
> sstable: remove RawWriter.IsStrictObsolete

- internal/base/internal.go
- internal/manifest/testutils.go
- sstable/colblk/data_block_test.go
Consolidate two internal key parsing functions into one that supports
both formats. We should reduce uses of the older format over time.
> base: consolidate internal key parsing functions

- .github/workflows/code-cover-gen.yaml
v2 is deprecated.
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> .github: use upload-artifact@v4

- internal/aligned/aligned.go
- internal/binfmt/binfmt.go
- internal/cache/value.go
- sstable/block/compression.go
- sstable/colblk_writer.go
- sstable/colblk_writer_test.go
- sstable/data_test.go
- sstable/format.go
- sstable/format_test.go
- sstable/options.go
- sstable/rowblk_writer.go
- sstable/table.go
- sstable/testdata/columnar_writer/simple_binary
Introduce a new RawWriter implementation that writes sstables using columnar-oriented blocks. This commit lays down the initial stencil of the writer. The new table format is currently excluded from unit tests, in part because the sstable reader does not yet know how to read the new table format.
> sstable: introduce RawColumnWriter

- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/testdata/data_block/bundle_search
- sstable/colblk/testdata/data_block/external_value
- sstable/colblk/testdata/data_block/finish_without_final_row
- sstable/colblk/testdata/data_block/next_prefix
- sstable/colblk/testdata/data_block/simple
- sstable/colblk_writer.go
- sstable/testdata/columnar_writer/simple_binary
Add an isObsolete bitmap to the colblk data block schema, encoding whether a key is obsolete (i.e. shadowed by an identical point key or range deletion with a higher sequence number).
Iteration-time filtering of obsolete keys is not yet implemented.
> colblk: add isObsolete bitmap to data block

- sstable/data_test.go
- sstable/format.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/writer_test.go
Define type aliases singleLevelIteratorRowBlocks and twoLevelIteratorRowBlocks. The full types with all type parameters is a bit unwieldly.
> sstable: define type aliases {single,two}LevelIteratorRowBlocks

- compaction_picker.go
- event.go
- testdata/compaction_setup_inputs_multilevel_write_amp
Previously, we had a missing check for the max "expanded" size of a compaction being exceeded when we were trying to convert a regular compaction to a multi-level compaction. This change adds that check to prevent multi level compactions from getting too big.
Fixes #3120
> db: cap size of multi-level compactions at expanded bytes size

- internal/testkeys/testkeys.go
It's okay to call Split on a bare prefix but not a bare suffix.
Informs #3906.
> testkeys: fix assertion panic message

- sstable/block/block.go
The term 'prefix' is loaded in the context of Pebble, and this commit clarifies the relationship of a SyntheticPrefix to the Comparer's concept of a prefix.
> block: clarify the SyntheticPrefix IterTransform documentation

- sstable/block/block.go
- sstable/block/buffer_pool.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/prefix_bytes.go
- sstable/reader_iter_single_lvl.go
- sstable/rowblk/rowblk_iter.go
Add a DataBlockIterConfig type that wraps a colblk.DataBlockIter and completes
the remainder of the block.DataBlockIterator interface. We choose to implement
the interface on this wrapper type to maintain configuration state (the
KeySchema and lazy value retriever) across usages of for individual blocks,
leaving DataBlockIter to be completely reset for each new block use.
> colblk: implement block.DataBlockIterator

- sstable/colblk_writer.go
- sstable/colblk_writer_test.go
- sstable/options.go
- sstable/random_test.go
- sstable/reader.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/testdata/columnar_writer/simple_binary
- testdata/ingest
- testdata/metrics
Add support for the new TableFormatPebblev5 (which introduces columnar blocks)
into the sstable.Reader. This commit stops short of bumping TableFormatMax to
TableFormatPebblev5 because columnar blocks don't yet support the iterator
transforms.
> sstable: integrate columnar blocks into Reader

- internal/manifest/testutils.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/testutils/indenttree/indent_tree.go
- internal/testutils/indenttree/indent_tree_test.go
- internal/testutils/indenttree/testdata
- merging_iter_test.go
- testdata/merging_iter
This commit adds some helper infrastructure to parse a multi-line
string into a hierarchy based on indentation.
Switch to an indentation-based hierarchy format and use the updated
syntax for file metadata and keys (which match the test output
format).
> db: modernize merging iterator tests

- obsolete_files.go
- open.go
- open_test.go
- replay/testdata/corpus/findManifestStart
- replay/testdata/corpus/high_read_amp
- replay/testdata/corpus/simple
- replay/testdata/replay
- replay/testdata/replay_paced
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/cleaner
- testdata/event_listener
- testdata/flushable_ingest
- testdata/iter_histories/errors
- testdata/metrics
- testdata/open_wal_failover
- testdata/table_stats
- version_set.go
Previously, replayWAL was too tightly coupled with the internals of a flush; it ran a flush directly and would produce a versionEdit that would then be accumulated manually (eg. without a BVE) using assumptions true only for memtable flushes. This required relatively intricate interactions with flushable ingests, and meant that flushable ingested sstables would always go into L0.
To pave the way for flushable ingests+excises, we refactor out all flush logic from replayWAL, and have replayWAL just replay WALs into the flushable queue. After this, Open() just schedules flushes until we're done.
Informs #2676.
> db: refactor replayWAL to use flushes to make versionEdits

- batch.go
- batchrepr/reader.go
- data_test.go
- flushable.go
- flushable_test.go
- format_major_version.go
- format_major_version_test.go
- ingest.go
- ingest_test.go
- internal.go
- internal/base/internal.go
- internal/base/internal_test.go
- mem_table.go
- metamorphic/generator.go
- metamorphic/ops.go
- metamorphic/parser.go
- open.go
- open_test.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/concurrent_excise
- testdata/determinism
- testdata/event_listener
- testdata/excise
- testdata/flushable_ingest
- testdata/ingested_flushable_api
- tool/db.go
- tool/wal.go
Previously, we'd only allow IngestAndExcise to become flushable ingests if we had a guarantee from the caller that the ingestion contained rangedel/rangekeydel overlapping the excise span. This change reworks flushable ingests to return rangedels/rangekeydels from their own iterators, even if one does not exist in the sstables themselves. This, plus the update to the WAL to be able to persist the excise span, allows for IngestAndExcise to allow flushable ingests in more cases than before.
Also resolves TODOs in replayWAL() around properly sequencing flushable ingests so their sstables can go in levels lower than L0. This sequencing was necessary to make excises work correctly; as excises require an up-to-date view of the version to work correctly.
Fixes #2676.
> db: allow excises to unconditionally be flushable ingests

- internal/base/comparer.go
- internal/crdbtest/crdbtest.go
- internal/testkeys/testkeys.go
When synthetic prefix is used, we can trim the synthetic prefix from a
given seek key and compare it with the "bare" key in a table. After
trimming the key prefix can become "empty" (with just the terminator
left). This change extends the comparer test suite to check that we
can remove leading bytes from prefixes and adjusts the testkeys and
crdb comparers.
Fixes #3906
> base: make comparer tolerate empty keys

- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk_writer.go
- sstable/suffix_rewriter_test.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/writer_test.go
**colblk: define behavior of KeyWriter.ComparePrev with no previous**
Define the behavior of KeyWriter.ComparePrev when called on a KeyWriter that
has no previously-written key.
**sstable: set IndexPartitions property in columnar sstable writer**
Populate the IndexPartitions table-level property in the the columnar sstable
writer.
> sstable,colblk: minor bug fixes

- internal/binfmt/binfmt.go
- sstable/colblk/data_block.go
- sstable/colblk_writer.go
- sstable/colblk_writer_test.go
- sstable/format.go
- sstable/layout.go
- sstable/reader.go
- sstable/testdata/columnar_writer/simple_binary
Adapt Layout.Describe to support describing sstables containing columnar blocks.
> sstable: support columnar blocks in Layout.Describe

- flushable.go
- ingest_test.go
- testdata/excise
Previously, we would incorrectly return false (denoting no overlap) between passed-in UserKeyBounds and a flushable ingest, if we see a file that starts after the passed-in bounds, even if there was an excise span overlapping with those bounds. This change fixes that, and adds a unit test to catch this edge case.
Fixes #3963.
> db: fix overlap check for flushable ingest excises

- metamorphic/meta.go
When printing the details of a metamorphic test failure print the path to the file containing the formatted operations rather than the operations themselves. There are typically thousands of operations and scrolling over them is a nuisance.
> metamorphic: abridge failure output

- internal/crdbtest/crdbtest.go
- sstable/colblk/bitmap.go
- sstable/colblk/bitmap_test.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/testdata/bitmap
This change uninlines these functions and adds a test for them.
The previous names were misleading since we can return the same
index.
These variants will be useful for skipping blocks of set bits, for
example to skip obsolete keys.
> colblk: add SeekUnsetBitGE/LE

- compaction.go
- internal/compact/run.go
- internal/compact/splitting.go
- internal/compact/splitting_test.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/writer.go
Extend the RawWriter interface to support two additional methods required by compactions. The RawRowWriter.UnsafeLastPointUserKey method is adapted into ComparePrev so that it may be implemented by RawColumnWriter without materializing the previous key.
> sstable: add ComparePrev, SetSnapshotPinnedProperties to RawWriter

- sstable/block/block.go
- sstable/colblk/bitmap.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/testdata/data_block/transforms
- sstable/layout.go
This commit plumbs the transforms into `DataBlockIter` and implements the synthetic sequence number functionality.
> colblk: implement SyntheticSeqNum transform

- internal/crdbtest/crdbtest.go
- sstable/colblk/cockroach_test.go
Adding a "short" version for the iterator benchmarks. We will add
combinations of various transforms with these selected configs.
We also slightly improve the benchmark naming.
> colblk: minor benchmark refactoring

- sstable/block_property_test.go
- sstable/reader_test.go
- sstable/testdata/block_properties
- sstable/testdata/block_properties_boundlimited
Update unit tests to use the IndexBlockIterator interface and be agnostic to the underlying block format.
> sstable: update unit tests to use block.IndexBlockIterator

- compaction.go
- flushable_test.go
- ingest.go
- table_cache_test.go
- version_set.go
Currently, we have the nextFileNum counter protected by db.mu, which is pretty unnecessary and results in us grabbing the db mutex just for being able to generate a new filenum. This change moves that to an atomic.
> db: use atomic for versionSet.nextFileNum

- sstable/colblk/index_block.go
- sstable/colblk/index_block_test.go
Previously, when an IndexIter was initialized with InitHandle, it erroneously overwrote the handle on the struct while initializing the rest of the struct. This would result in the handle never being Released.
> colblk: ensure IndexIter releases BufferHandles

- internal/base/internal.go
- sstable/colblk/data_block.go
- sstable/colblk/keyspan.go
- sstable/colblk_writer.go
- sstable/random_test.go
- sstable/testdata/writer_v5
- sstable/writer_test.go
Update the TestWriter test to exercise the new TableFormatPebblev5 that enables
columnar blocks. This commit also fixes a couple issues with key ordering checks.
> sstable: update TestWriter to exercise TableFormatPebblev5

- sstable/colblk/data_block.go
- sstable/testdata/rewriter_v5
Go pointer rules require that a Go pointer always point to a byte within a valid allocation. The DataBlockRewriter previously would allocate buffers for keys exactly sized for the largest user key contained within a block. If one were to use pointer arithmetic to compute an exclusive pointer to byte beyond the key, this pointer would violate Go's pointer rules.
As far as I can tell, we don't do this today because only PrefixBytesIter performs pointer arithmetic that might violate this by computing a pointer to the beginning of the suffix. This is only problematic if there is no suffix, but suffix-rewriting always requires a suffix.
To be safe, we allocate an extra byte.
> colblk: safeguard against Go pointer rule violations in DataBlockRewriter

- sstable/block/block.go
- sstable/colblk/bitmap.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/testdata/data_block/transforms
Adding a "short" version for the iterator benchmarks. We will add
combinations of various transforms with these selected configs.
We also slightly improve the benchmark naming.
Benchmark for the no-transform path before/after:
```
name                                                                                old time/op    new time/op    delta
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8/Next-10           12.2ns ± 0%    12.5ns ± 3%  +2.38%  (p=0.008 n=5+5)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,ValueLen=8/SeekGE-10          113ns ± 0%     114ns ± 0%  +0.80%  (p=0.008 n=5+5)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=128,Shared=64,ValueLen=128/Next-10      10.1ns ± 0%    10.3ns ± 0%  +2.30%  (p=0.016 n=5+4) …
```
> colblk: implement HideObsoletePoints in DataBlockIter

- internal/itertest/datadriven.go
- sstable/colblk/data_block_test.go
- sstable/colblk/testdata/data_block/bundle_search
- sstable/colblk/testdata/data_block/external_value
- sstable/colblk/testdata/data_block/finish_without_final_row
- sstable/colblk/testdata/data_block/next_prefix
- sstable/colblk/testdata/data_block/simple
- sstable/colblk/testdata/data_block/transforms
It's pretty hard to look at an `iter` testcase and see which key
matches which command. This commit adds a `ShowCommands` option and
uses it for the data block tests.
> colblk: show iter commands

- sstable/block/block.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/index_block.go
- sstable/colblk/index_block_test.go
- sstable/colblk/testdata/data_block/simple
- sstable/colblk/testdata/index_block
**block,colblk: tighten index iterator semantics**
This commit more tightly defines the IndexBlockIterator semantics around behavior after a call to Invalidate and around positioning operations called after exhaustion. These semantics match the rowblk implementation and are currently required by the sstable iterator.
In the future, we may consider alternative semantics through updating the sstable iterator.
**block,colblk: tighten data block iterator semantics**
Define the semantics of calling a positioning method on an invalidated
DataBlockIterator. The sstable iterator currently depends on these semantics.
> block,colblk: tighten iterator semantics

- sstable/colblk_writer.go
- sstable/format.go
- sstable/format_test.go
- sstable/table.go
- sstable/testdata/writer_value_blocks
- sstable/writer_test.go
Fix a bug in RawColumnWriter's determination of whether to possibly store a value in a value block. It erroneously required the current key kind to NOT be a SET. Also, adapt TestWriterWithValueBlocks to test (Pebble,v5) [columnar blocks].
> sstable: fix RawColumnWriter's value-block determination

- internal/itertest/datadriven.go
- sstable/block/block.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/testdata/data_block/transforms
- sstable/reader_iter_single_lvl.go
- sstable/rowblk/rowblk_iter.go
This commit changes the `CompareFirstUserKey` API to `IsLowerBound`
which can be defined when there are no keys to present. We fix the
columnar implementation to take into account `HideObsoletePoints` and
ignore any leading obsolete points in the block.
> colblk: change CompareFirstUserKey to IsLowerBound

- sstable/data_test.go
- sstable/reader_test.go
- sstable/testdata/hamletreader/hamlet_iter
- sstable/testdata/prefixreader/iter
- sstable/testdata/reader/iter
- sstable/testdata/reader_bpf/Pebblev2/iter
- sstable/testdata/reader_bpf/Pebblev3/iter
- sstable/testdata/reader_hide_obsolete/iter
- sstable/testdata/readerstats_LevelDB/iter
- sstable/testdata/readerstats_Pebblev3/iter
This change is analagous to #3988 but for the sstable package's datadriven iter command. Including the command in the output makes it more legible.
> sstable: show iterator commands

- sstable/colblk/index_block.go
- sstable/colblk/index_block_test.go
- sstable/colblk/testdata/index_block
Previously columnar index blocks always used bytes.Compare during seeks among separators.
> colblk: use configured Compare in index blocks

- sstable/colblk_writer.go
- sstable/properties.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/testdata/writer_v5
- sstable/writer_test.go
Update RawColumnWriter to update sstable properties when writing range deletions and range keys. The properties are computed differently in columnar sstables, because the old accounting was tightly coupled with the encoding.
> sstable: populate range deletion, range key props in RawColumnWriter

- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
This is useful for synthetic suffix replacement and it will also be
useful to implement `SeekPrefixGE` optimizations.
> colblk: make KeySeeker.SeekGE return whether prefix is equal

- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/layout.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
Collapse MultiDataBlockIter and DataBlockIter into one type. This was motivated by chasing down an unintentional allocation in MultiDataBlockIter.InitHandle.
> colblk: unify MultiDataBlockIter and DataBlockIter

- db.go
- iterator.go
- level_checker.go
- level_iter.go
- level_iter_test.go
- merging_iter.go
- merging_iter_test.go
```
goos: darwin
goarch: arm64
│    old.txt    │              newest.txt               │
│    sec/op     │    sec/op     vs base                 │
NewIterReadAmp/10-10   1309.0n ± ∞ ¹   810.7n ± ∞ ¹  -38.07% (p=0.016 n=4+5)
¹ need >= 6 samples for confidence interval at level 0.95
│   old.txt   │          newest.txt          │
│    B/op     │   B/op     vs base           │
NewIterReadAmp/10-10   241.0 ± ∞ ¹   0.0 ± ∞ ¹  ~ (p=0.079 n=4+5)
¹ need >= 6 samples for confidence interval at level 0.95
│   old.txt   │          newest.txt           │
│  allocs/op  │ allocs/op   vs base           │
NewIterReadAmp/10-10   11.00 ± ∞ ¹   0.00 ± ∞ ¹  ~ (p=0.079 n=4+5)
```
Close #4000.
> db: remove unnecessary NewIter allocations

- sstable/reader_test.go
- sstable/testdata/virtual_reader_props
Update the TestVirtualReader/props unit test to explicitly exercise both TableFormatPebblev4 and TableFormatPebblev5.
> sstable: update TestVirtualReader/props to exercise TableFormatPebblev5

- sstable/block_property_test.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
This commit cleans up the TestRewriteSuffixProps unit test, refactoring it to use the testkey comparator and new block-property collectors that are functions of the testkey integer suffix.
It also fixes a bug where if the suffix rewriting WriterOptions contained fewer block property collectors than the original sstable had when it was written, suffix rewriting could fail to decode all the relevant properties from a block handle.
> sstable: clean up TestRewriteSuffixProps, fix subtle bug

- internal/crdbtest/crdbtest.go
- sstable/block/block.go
- sstable/block/block_test.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/prefix_bytes.go
- sstable/colblk/testdata/data_block/transforms
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
First commit is #3996
`DataBlockIter` now takes into account the synthetic prefix and suffix
transforms.
> colblk: implement synthetic prefix and suffix

- internal/crdbtest/crdbtest.go
- sstable/colblk/cockroach_test.go
This commit fixes a number of bugs in `seekGEOnSuffix` which cause
incorrect `SeekGE` results when there are multiple suffixes with the
same prefix or when there isn't an exact key match.
We change the schema to not include the separator 0 byte in the
encoded prefixes and make sure the read and write side agree on this.
> colblk: fix crdb seekGEOnSuffix

- internal/compact/spans_test.go
- sstable/colblk_writer.go
- sstable/colblk_writer_test.go
- sstable/format.go
- sstable/reader_test.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/test_utils.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/testdata/reader/iter
- sstable/testdata/virtual_reader_iter
- sstable/writer.go
- table_stats_test.go
Fix a few bugs in and adjacent to the RawColumnWriter, and bump TableFormatMax to point to TableFormatPebblev5 (which enables columnar blocks).
> sstable: bug fixes, bump TableFormatMax to TableFormatPebblev5 

- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk_writer.go
- sstable/colblk_writer_test.go
- sstable/layout.go
These names are more appropriate because these types don't actually
perform any reading or writing, and there are other associated reader
and writer types.
> colblk: rename DataBlockWriter/Reader to Encoder/Decoder

- sstable/block/block.go
- sstable/block/block_test.go
- sstable/colblk/keyspan.go
- sstable/colblk/keyspan_test.go
- sstable/colblk/testdata/keyspan_block
Fix a bug in (*colblk.KeyspanIter).SeekLT that caused the iterator to surface the wrong span, and implement the FragmentIterTransforms on the colblk.KeyspanIter.
> colblk: implement FragmentIterTransforms, fix SeekLT

- sstable/colblk/cockroach_test.go
This commit improves the code in the cockroach key seeker to first
check the latest timestamp (which will be the one we're looking for in
a majority of cases).
```
name                                                                                                                 old time/op    new time/op    delta
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,KeysPerPrefix=4,Logical=10,ValueLen=8/Next-10                 11.4ns ± 4%    11.2ns ± 1%    ~     (p=0.308 n=8+8)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,KeysPerPrefix=4,Logical=10,ValueLen=8/SeekGE-10                118ns ± 0%     118ns ± 0%  +0.24%  (p=0.023 n=8+8)
CockroachDataBlockIterShort/AlphaLen=8,Prefix=8,Shared=4,KeysPerPrefix=4,Logical=10,ValueLen=8/SeekGELatest-10          109ns ± 0%     108ns …
```
> colblk: check first timestamp before binary search

- db.go
- internal/manifest/annotator.go
- internal/manifest/btree.go
Previously, we required any annotation mutations to be mutually-excluded through, say, db.mu being held. This was problematic as some uses of annotations, like level sizes, were complex to compute and required IO (or network requests). Holding up db.mu while we send a bunch of requests to S3 was causing a huge performance penalty across Pebble, so this change makes annotator safe for concurrent use with a slight possibility of double-calculating annotation values in case of races, something that shouldn't change any results.
Fixes #4001.
> internal/manifest: make annotations concurrent-safe

- internal/lint/lint_test.go
In most cases `go vet` fails because of a build error, in which case
the rest of the tests result in a lot of noise. This commit stops the
lint test suite if `go vet` fails.
> lint: stop test when go vet fails

- sstable/colblk/prefix_bytes.go
The condition `c == 0 && n < sharedPrefixLen` is impossible:
`bytes.Compare` would never report equality if the lengths are
different. We remove this condition and restructure the code so there
is only one conditional in the hot path.
> colblk: minor improvement to PrefixBytes.Search

- sstable/block_property_test.go
- sstable/copier.go
- sstable/layout.go
- sstable/reader.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/table_test.go
- sstable/value_block.go
The code to transform a raw block at load time is not currently used
or tested. Removing it to keep the code a bit cleaner (it's easy
enough to add back if we ever need it again).
> sstable: remove block transforms

- sstable/colblk/prefix_bytes.go
- sstable/colblk/prefix_bytes_test.go
This struct is embedded in block decoders and making them a bit
smaller is desirable.
> colblk: use uint32 in bundleCalc

- data_test.go
- testdata/iter_histories/next_prefix
- testdata/iter_histories/prefix_iteration
- testdata/table_stats
This commit cleans up and consolidates a couple places where we parsed datadriven command args for configuring pebble.Options. It fixes a bug where the block-size command arg would be ignored in one parse site.
> db: consolidate datadriven DB opts parsing; fix block-size bug

- internal/crdbtest/crdbtest.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/prefix_bytes.go
- sstable/colblk/prefix_bytes_test.go
Move the test implementation of a cockroach colblk.KeySchema into crdbtest so that it may be used by other packages, and most notably, the ycsb benchmarks implemented in cmd/pebble.
> crdbtest: move cockroach colblk.KeySchema

- sstable/block_property_test.go
- sstable/copier.go
- sstable/layout.go
- sstable/reader.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_test.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/table_test.go
- sstable/value_block.go
- testdata/checkpoint
- testdata/event_listener
- testdata/ingest
- testdata/metrics
We move the stats and bufferPool arguments into their own
`readBlockEnv` struct. We add specific functions for different block
types.
A functional change is that now we use the buffer pool for the
top-level index block and filter block (this looks like an omission in
the existing code). This changed caused failures in some tests that
were not releasing a pool, which are now fixed.
> sstable: cleanup readBlock usage

- sstable/colblk_writer_test.go
- sstable/table.go
- sstable/testdata/columnar_writer/simple_binary
This directive is very similar to `layout` and we don't need both.
> sstable: remove describe-binary

- sstable/block/compression.go
- sstable/colblk_writer.go
- sstable/copier.go
- sstable/copier_test.go
- sstable/options.go
- sstable/rowblk_writer.go
- sstable/testdata/copy_span
- sstable/writer.go
- testdata/ingest_external
Previously, sstable.CopySpan() was heavily coupled to the internals of a RawRowWriter. This change updates CopySpan and the RawWriter interface to work in a more implementation-agnostic way, so that the columnar writer can also be used with the downloader.
Fixes #4010.
> sstable: make CopySpan() support columnar blocks

- sstable/colblk/prefix_bytes.go
- sstable/colblk/prefix_bytes_test.go
- sstable/colblk/testdata/prefix_bytes
Fix PrefixBytesBuilder.UnsafeGet and add a randomized test.
> colblk: fix PrefixBytesBuilder.UnsafeGet

- sstable/colblk_writer.go
We would skip one data block if we exceeded the size of the buffer.
> sstable: fix colblk copyDataBlocks off-by-one

- sstable/colblk/testdata/uints
- sstable/colblk/uints.go
UintBuilder has a clever fast path for determining the current
encoding. The fast path is a bit pessimistic when we are
useing the "default" mode: it assumes that there will be at least one
value of 0.
The "slow" path is not pessimistic and thus the results might not be
consistent depending on which path is taken. This is a problem because
we could get the Size, add a row, then get the Size for the previous
number of rows again; now we no longer use the fast path and can get a
different result if all the rows have been set to non-zero values.
This commit adds a test that demonstrates this issue.
This commit fixes the UintBuilder bug described in the previous
commit. We make the non-fast-path consistent with the fast path so
that the encoding can't change unexpectedly.
> colblk: fix UintBuilder inconsistent size bug

- internal/crdbtest/crdbtest.go
Previously crdbtest.KeySchema.NewKeySeeker did not make use of the pool when allocating new key seekers.
> internal/crdbtest: use the key seeker pool

- compaction.go
- testdata/compaction_delete_only_hints
Previously we kept around hints that were creating too many virtual sstables instead of dropping them. This change drops them to save future compaction pickers from having to iterate over them.
Fixes #4055.
> db: drop hints that produce too many virtual sstables

- sstable/colblk/prefix_bytes.go
Use UnsafeOffsets.At2 in another instance within PrefixBytes.Search.
> colblk: use UnsafeOffsets.At2 in another instance

- compaction.go
- internal/manifest/version.go
- internal/manifest/virtual_backings.go
Previously, if we had a late cancellation of a compaction (ie. right before we were gonna logAndApply), we would end up not marking compaction outputs as obsolete/zombie, and neither would we delete them rightaway. This change updates the compaction running code to also clean up compaction outputs in this case of compaction cancellation.
Fixes cockroachdb/cockroach#132668.
> db: delete compactions output in case of late cancellation

- compaction.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db_test.go
- event_listener_test.go
- external_iterator_test.go
- format_major_version.go
- ingest_test.go
- iterator_test.go
- metamorphic/ops.go
- testdata/compaction_picker_pick_file
- testdata/compaction_picker_scores
- testdata/metrics
- tool/db.go
Fix a couple instances where the format of a sstable was solely a function of the format major version's maximum supported format, and settings like EnableColumnarBlocks and EnableValueBlocks were not respected.
> db: fix a few instances of the wrong table format

- compaction.go
- compaction_test.go
- metamorphic/options.go
- metamorphic/options_test.go
- options.go
This change adds a dynamic knob in Options to be able to toggle the functionality added in #3926. If the method is undefined or returns false, delete-only compactions only do full-file deletes and not excises.
> options: add EnableDeleteOnlyCompactionExcises Option

- sstable/block/block.go
- sstable/colblk/index_block.go
- sstable/copier.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/rowblk/rowblk_index_iter.go
Extend the IndexBlockIterator interface with two new methods for performing comparisons against the separator at the current iterator position. This is a precursor to decomposing separator keys into prefix and suffix in columnar blocks, as it will allow the colblk index iterator to avoid materializing the separator key unnecessarily.
> sstable: add index separator comparison methods

- db_test.go
- internal/cache/clockpro.go
- internal/cache/clockpro_test.go
- internal/crdbtest/crdbtest_test.go
- sstable/block/block.go
- sstable/block/buffer_pool.go
- sstable/block/flush_governor.go
- sstable/block/testdata/flush_governor
- sstable/block_property_test.go
- sstable/colblk/data_block.go
- sstable/colblk/index_block.go
- sstable/colblk/index_block_test.go
- sstable/colblk/keyspan.go
- sstable/colblk/keyspan_test.go
- sstable/copier.go
- sstable/layout.go
- sstable/reader.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_test.go
- sstable/rowblk/rowblk_fragment_iter.go
- sstable/rowblk/rowblk_fragment_iter_test.go
- sstable/rowblk/rowblk_iter.go
- sstable/table_test.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/value_block.go
- sstable/writer_test.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
We reserve a chunk of each allocation in the cache as
`block.Metadata`. We use this to cache the `colblk.DataBlockDecoder`
so we don't have to reinitialize it each time we use the block.
In subsequent changes we will also cache the key seeker and the
`IndexBlockDecoder`.
> sstable: cache DataBlockDecoder alongside data blocks

- compaction_picker.go
- iterator_test.go
- options.go
- options_test.go
- replay/testdata/replay
Previously, the heuristic to pick tombstone-density compactions did not account for level sizes at all; it solely looked at how tombstone-dense some sstables were. This resulted in cases where if a large part of the LSM was tombstone-dense, we would needlessly spend CPU and IO compacting everything all the way to L6.
This change adds a minimum uncompensated score that a level must meet before we consider a tombstone-density compaction out of that level. This change also bumps up the tombstone dense blocks threshold to 10% of data blocks in an sstable, up from 5%, before an sstable is chosen for a tombstone density compaction.
Fixes #4052.
> compact: set minimum score for tombstone density compactions

- compaction_picker.go
- iterator_test.go
- options.go
- options_test.go
- replay/testdata/replay
Reverts cockroachdb/pebble#4074
I'll redo this change with an overlapping ratio-based threshold instead of a level-score based threshold.
> Revert "compact: set minimum score for tombstone density compactions"

- internal/crdbtest/crdbtest.go
- sstable/colblk/cockroach_test.go
The KeySeeker implementation accidentally materialized four bytes of the wall time as the logical time when encoding a MVCC timestamp with a non-zero logical time.
> crdbtest: fix MaterializeUserKey

- sstable/copier.go
- sstable/copier_test.go
- sstable/testdata/copy_span
Previously we were using the wrong index iterator's Separator when iterating over the entries of a two-level index sstable.
> sstable: fix use of incorrect iterator in CopySpan()

- sstable/block/buffer_pool.go
- sstable/colblk/data_block.go
- sstable/colblk/index_block.go
- sstable/colblk/index_block_test.go
- sstable/colblk/keyspan_test.go
- sstable/layout.go
- sstable/reader.go
```
RandSeekInSST/v4/single-level-10  1.21µs ± 1%  1.25µs ± 5%   +3.40%  (p=0.005 n=8+8)
RandSeekInSST/v4/two-level-10     2.06µs ± 4%  2.06µs ± 1%     ~     (p=0.959 n=8+8)
RandSeekInSST/v5/single-level-10  1.11µs ± 1%  1.06µs ± 1%   -4.03%  (p=0.000 n=8+8)
RandSeekInSST/v5/two-level-10     1.79µs ± 5%  1.59µs ± 1%  -11.45%  (p=0.000 n=7+8)
```
> colblk: cache IndexBlockDecoder in block metadata

- objstorage/test_utils.go
Better implementation for `MemObj.NewReadHandle` which doesn't
allocate (the allocation shows up in microbenchmark profiles and is a
red-herring as the production path would use a preallocated handle).
> objstorage: optimize MemObj.NewReadHandle

- internal/crdbtest/crdbtest_test.go
This function calls `b.Helper()` which has non-trivial overhead,
muddling the result of the benchmark.
> colblk: don't use require.NoError in BenchmarkRandSeekInSST hot path

- sstable/colblk/data_block.go
- sstable/colblk/index_block.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/rowblk/rowblk_fragment_iter.go
- sstable/rowblk/rowblk_index_iter.go
- sstable/rowblk/rowblk_iter.go
- sstable/rowblk/rowblk_rewrite.go
Resetting iterators takes a non-trivial amount of time (15% in the
RandSeekInSST benchmark). Most of it is because we're copying fairly
large structures by value.
We change `ResetForReuse` to reset the iterator in-place, and we use
an unsafe trick to clear out only a section of `singleLevelIterator`.
Benchmark (baseline includes a few other in-flight PRs):
```
name                              old time/op  new time/op  delta
RandSeekInSST/v4/single-level-10  1.15µs ± 0%  1.02µs ± 1%  -10.84%  (p=0.001 n=7+7)
RandSeekInSST/v4/two-level-10     1.99µs ± 2%  1.71µs ± 2%  -13.85%  (p=0.000 n=8+8)
RandSeekInSST/v5/single-level-10   944ns ± 1%   823ns ± 1%  -12.86%  (p=0.000 n=8+8)
RandSeekInSST/v5/two-level-10     1.44µs ± 1%  1.24µs ± 7%  -13.79%  (p=0.000 n=7+8)
```
> sstable: perf improvement for ResetForReuse

- internal/crdbtest/crdbtest.go
- sstable/colblk/data_block.go
- testdata/ingest
- testdata/metrics
We allow caching the KeySeeker in the block metadata, saving on
initialization time.
```
name                              old time/op  new time/op  delta
RandSeekInSST/v4/single-level-10  1.22µs ± 1%  1.22µs ± 1%    ~     (p=0.565 n=7+7)
RandSeekInSST/v4/two-level-10     2.07µs ± 3%  2.08µs ± 3%    ~     (p=0.744 n=8+8)
RandSeekInSST/v5/single-level-10  1.06µs ± 1%  1.01µs ± 1%  -5.22%  (p=0.000 n=8+8)
RandSeekInSST/v5/two-level-10     1.60µs ± 3%  1.54µs ± 5%  -3.17%  (p=0.021 n=8+7)
```
> colblk: cache KeySeeker in the block metadata

- compaction_picker.go
- compaction_picker_test.go
- iterator_test.go
- options.go
- options_test.go
- replay/testdata/replay
- table_stats.go
Previously, we didn't account for the overlapping ratio of a file when picking it for a tombstone density compaction. The overlap ratio likely tells us how sparse the tombstones are across the keyspace, and files with a high amount of overlap below them should likely be excluded from tombstone density compactions as these compactions are likely to be unnecessarily large, incurring extra write-amp.
Fixes #4052.
> compact: cap overlap ratio of tombstone density compactions

- cmd/pebble/db.go
- internal/compact/spans_test.go
- internal/crdbtest/crdbtest_test.go
- level_checker_test.go
- options.go
- sstable/colblk/cockroach_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk_writer_test.go
- sstable/copier_test.go
- sstable/data_test.go
- sstable/options.go
- sstable/random_test.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/suffix_rewriter_test.go
- table_stats_test.go
- testdata/ingest
- testdata/metrics
- tool/tool.go
We pass and store `KeySchema` by value in many places; this struct is
~64 bytes in size, so it adds a bit of size to various structs.
Switch to using `*KeySchema`, which is also consistent with how we use
the `Comparer`.
RabdSeekInSST benchmark is unaffected:
```
name                              old time/op  new time/op  delta
RandSeekInSST/v5/single-level-10   505ns ± 2%   504ns ± 0%   ~     (p=0.718 n=7+8)
RandSeekInSST/v5/two-level-10     1.02µs ± 3%  1.01µs ± 2%   ~     (p=0.591 n=8+8)
```
> sstable: pass KeySchema by pointer

- internal/crdbtest/crdb.go
- sstable/block/block.go
- sstable/block/testdata/flush_governor
- sstable/colblk/block.go
- sstable/colblk/data_block.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
We add a fixed-size KeySchema-specific header to the beginning of the
custom block header. A KeySchema implementation can store there
information and retrieve it when initializing the key seeker.
We use this to add a byte to cockroach blocks which indicates what
types of suffixes are contained in the block (mvcc, empty, non-mvcc).
This will be used for optimized fast paths for the common cases.
> colblk: add a KeySchema-specific header

- sstable/block/block.go
- sstable/block/compression.go
- sstable/value_block.go
- sstable/writer_test.go
This allocation snuck in during the block package refactors.
```
│   old.txt    │                new.txt                │
│  allocs/op   │  allocs/op   vs base                  │
Writer/format=(Pebble,v2)/block=4.0KB/filter=true/compression=NoCompression-10    18.985k ± 0%   9.533k ± 0%  -49.79% (p=0.000 n=10)
Writer/format=(Pebble,v2)/block=4.0KB/filter=true/compression=Snappy-10           18.991k ± 0%   9.536k ± 0%  -49.79% (p=0.000 n=10)
Writer/format=(Pebble,v2)/block=4.0KB/filter=true/compression=ZSTD-10              66.29k ± 0%   56.84k ± 0%  -14.25% (p=0.000 n=10)
Writer/format=(Pebble,v2)/block=4.0KB/filter=false/compression=NoCompression-10   18.974k ± 0%   9.521k ± 0%  -49.82% (p=0.000 n=10)
Writer/format=(Pebble,v2)/block=4.0KB/filter=false/compression=Snappy-10 …
```
> block: remove unnecessary CompressAndChecksum allocation

- metamorphic/generator.go
- metamorphic/key_manager.go
- metamorphic/options.go
Previously we assumed that external objects would keep keys with different suffixes but the same prefix when doing key tracking in the key manager. This wasn't in line with what newExternalObjOp was doing, and led to cases of keys being marked as eligible for singledel when they were not.
Fixes #4047.
> metamorphic: deduplicate prefixes in key_manager for external objs

- sstable/colblk/index_block.go
A CI run observed a nil pointer in BlockHandleWithProperties during the
sstable.TestIterator_RandomErrors unit test. I haven't been able to reproduce
yet. This commit adds an invariants-build assertion that we're reading a valid
row.
Additionally, it fixes a bug in IndexIter.Close that could cause a subsequent
call to Valid() to return true.
> colblk: fix IndexIter.Close, add a defensive assertion in IndexIter

- internal/crdbtest/crdb.go
- sstable/colblk/data_block.go
`KeySchemaHeader` returns the header that was written instead of
relying on the caller to provide the correct size. This makes things
less error-prone and also allows for extending the header while
allowing backward compatibility.
> colblk: don't require the header size for KeySchemaHeader

- db.go
- external_iterator.go
- internal/crdbtest/crdb_bench_test.go
- iterator.go
- level_iter.go
- level_iter_test.go
- merging_iter_test.go
- sstable/block_property_test.go
- sstable/category_stats.go
- sstable/random_test.go
- sstable/reader.go
- sstable/reader_common.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_test.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/reader_virtual.go
- table_cache.go
- testdata/metrics
Shard the categorized iterator stats to avoid mutex contention in high-read workloads that are frequently closing sstable iterators.
> sstable: shard categorized iterator stats

- cmd/pebble/main.go
- tool/tool.go
Update the cmd/pebble CLI tool to populate opts.KeySchemas with commonly used KeySchemas. This was motivated by a desire to use the cmd/pebble CLI tool with a sstable constructed by the metamorphic tests.
> cmd/pebble: populate common KeySchemas

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/colblk/data_block.go
- sstable/colblk_writer.go
When the invariants build tag is enabled, assert that the KeyComparison returned by the columnar data block writer is accurate by computing the KeyComparison from a buffered user key.
Informs #4103.
> sstable: assert KeyComparison correctness under invariants

- internal/crdbtest/crdb.go
- internal/crdbtest/key_schema_test.go
- sstable/colblk/data_block.go
We were writing the terminator length byte incorrectly.
> crdbtest: fix bug in cockroachKeyWriter.MaterializeKey

- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/testdata/data_block/external_value
- sstable/colblk/testdata/data_block/next_prefix
- sstable/colblk_writer.go
Add a Validate method to DataBlockDecoder that validates invariants of the decoded data block.
Informs #4103.
> colblk: add DataBlockDecoder.Validate

- internal/compact/iterator.go
- sstable/colblk/data_block.go
In #4070, CompareSuffixes was split into CompareRangeSuffixes and ComparePointSuffixes. This commit fixes a few errant uses of CompareRangeSuffixes on point key suffixes.
> colblk: fix a few errant uses of CompareRangeSuffixes

- sstable/colblk/bitmap.go
- sstable/colblk/bitmap_test.go
Previously, Invert used slices.Grow to grow the b.words slice if necessary. If len(b.words) < cap(b.words), words in the unused capacity were not initialized to zero and were assumed to be zero. Most of the time this was okay, because Reset zeroed b.words up to len(b.words).
However if the BitmapBuilder was previously used to Finish fewer rows than were Set, it's possible Finish may have truncated b.words to exclude words with non-zero bits. Since Reset only reset words within len(b.words), the truncated words were left unzeroed.
This commit updates Invert to make no assumptions as to the value of words beyond len(b.words). It also removes the zeroing in Reset which obscured this bug in most cases, instead relying on Set, Finish and Invert to properly initialize memory as necessary as …
> colblk: Bitmap, BitmapBuilder bug fixes

- compaction.go
- internal/manifest/version.go
- internal/manifest/virtual_backings.go
24.2 backport of #4053.
----
Previously, if we had a late cancellation of a compaction (ie. right before we were gonna logAndApply), we would end up not marking compaction outputs as obsolete/zombie, and neither would we delete them rightaway. This change updates the compaction running code to also clean up compaction outputs in this case of compaction cancellation.
Fixes cockroachdb/cockroach#132668.
> release-24.2: db: delete compactions output in case of late cancellation

- sstable/block/kv.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/value_block.go
- sstable/writer_test.go
Currently the type `valueBlockReader` implements both
`block.GetLazyValueForPrefixAndValueHandler` and `base.ValueFetcher`.
The lifetime of the `ValueFetcher` needs to extend beyond that
of the iterator.
This commit splits it into two objects - `valueBlockReader` continues
to implement `block.GetLazyValueForPrefixAndValueHandler` but the new
`valueBlockFetcher` now implements `base.ValueFetcher`. The
`valueBlockReader` lazily allocates the `valueBlockFetcher` the first
time it is asked to produce a `LazyValue`. The result is that we
should avoid the allocation if we are never positioned on a KV with
non-in-place value (which is the norm when we get the latest version
of a single key).
```
name                              old time/op    new time/op    delta …
```
> sstable: lazily allocate ValueFetcher

- compaction.go
- db.go
- get_iter_test.go
- ingest.go
- ingest_test.go
- level_iter.go
- metamorphic/ops.go
- metrics.go
- metrics_test.go
- options.go
- scan_internal.go
- scan_internal_test.go
- snapshot.go
- sstable/category_stats.go
- table_cache.go
- testdata/metrics
Instead of using arbitrary strings, we use an enum. Categories must
now be registered upfront (from an `init` function). We also associate
the QoS level upon registration, simplifying the plumbing.
> sstable: make Category an enum

- batch.go
- commit.go
- compaction.go
- db.go
- go.mod
- go.sum
- internal/batchskl/skl.go
- internal/randvar/rand.go
- obsolete_files.go
- open.go
- pacer.go
- pacer_test.go
- record/log_writer.go
- sstable/reader.go
- vfs/disk_health.go
- vfs/disk_health_test.go
- wal/failover_writer.go
This commit updates crlib and changes the "production" parts of pebble
to use `crtime.Mono` instead of `time.Time` or unix nanos. `NowMono()`
is about 2x faster than `time.Now` (and is much cleaner than working
with unix nanos).
Informs https://github.com/cockroachdb/cockroach/issues/133315
> *: use crtime.NowMono instead of time.Now

- .github/workflows/ci.yaml
The macOS-12 image is deprecated.
See https://github.com/actions/runner-images/issues/10721
> .github: bump macos image

- compaction.go
- metrics.go
Add metrics for the count and bytes written by cancelled compactions.
Close #4097.
> db: add Metrics.Compact.Cancelled{Count,Bytes}

- checkpoint.go
- checkpoint_test.go
- data_test.go
- open.go
- options.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/copy_checkpoint_options
- testdata/event_listener
This commit adapts Checkpoint to omit the [WAL Failover] section of the OPTIONS file from the checkpoint's OPTIONS file. The WAL failover configuration is specific to the original database. We want our checkpoints to be fully encapsulated and complete, so we copy WAL files from both the primary WAL directory and the failover secondary. This means a database opening the checkpoint does not need the secondary directory to be provided as a WALRecoveryDir.
With this commit, Checkpoint parses the old OPTIONS file and copies its contents verbatim to a new file in the checkpointed directory. If the old OPTIONS file had a WAL Failover configuration, its entire section is commented out within the checkpoint.
> db: ensure checkpointed database with WAL failover is openable

- .github/workflows/ci.yaml
- checkpoint.go
- checkpoint_test.go
- compaction.go
- data_test.go
- metrics.go
- open.go
- options.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/copy_checkpoint_options
- testdata/event_listener
24.3 backport of #4133, #4132 and #4130.
> crl-release-24.3: backport a few fixes

- sstable/reader_iter_single_lvl.go
- sstable/value_block.go
In #4123 we switched to allocating the fetcher lazily and restricting
the `valueBlockReader` lifetime to that of the iterator. However, the
lifetime of the `*LazyFetcher` stored in the value must outlive the
iterator and it currently lives inside `valueBlockReader`.
This change fixes the bug by moving the `LazyFetcher` to
`valueBlockFetcher`.
Fixes #4131
> sstable: fix LazyFetcher lifetime

- internal/base/comparer.go
- level_iter.go
- sstable/table_test.go
- testdata/iter_histories/prefix_iteration
- testdata/iterator_seek_opt
- testdata/level_iter
Don't load arbitrarily later files during levelIter.SeekPrefixGE. This avoids unnecessary IO and CPU overhead.
Close #3575.
> crl-release-23.2: db: avoid loading later files for a level in SeekPrefixGE

- sstable/block/flush_governor.go
- sstable/block/flush_governor_internal_test.go
- sstable/block/testdata/flush_governor
- sstable/options.go
Currently the FlushGovernor logic results in blocks that are too small
(about 60% of the target). This was a result of a misinterpretation of
the previous code.
We now find the allocation size boundary that is closest to our target
and consider that boundary and the following one. For the 32KB
cockroach default block size, the boundaries are 32KB and 40KB. We
will flush right before exceeding the 32KB boundary, unless we have a
large enough KV that fits better in the 40KB class.
Informs https://github.com/cockroachdb/cockroach/issues/134420
> block: improve FlushGovernor logic

- internal/metamorphic/metaflags/meta_flags.go
- metamorphic/test.go
We've seen some operation timeouts being hit on teamcity agents with inexplicably slower runs than anywhere else. This change tries to quieten those failures by bumping up the default per-op timeout as well as the timeout for downloads which are especially susceptible to slowdowns in the presence of a lot of files.
Fixes #4114
Fixes #4120
> metamorphic: increase per-operation timeouts

- sstable/block/flush_governor.go
- sstable/block/flush_governor_internal_test.go
- sstable/block/testdata/flush_governor
- sstable/options.go
Currently the FlushGovernor logic results in blocks that are too small
(about 60% of the target). This was a result of a misinterpretation of
the previous code.
We now find the allocation size boundary that is closest to our target
and consider that boundary and the following one. For the 32KB
cockroach default block size, the boundaries are 32KB and 40KB. We
will flush right before exceeding the 32KB boundary, unless we have a
large enough KV that fits better in the 40KB class.
Informs https://github.com/cockroachdb/cockroach/issues/134420
> crl-release-24.3: block: improve FlushGovernor logic

- sstable/colblk_writer.go
- sstable/data_test.go
- sstable/testdata/writer_v5
- sstable/writer_test.go
Previously, the EstimatedSize method of the columnar sstable writer would panic when the writer was configured with DisableValueBlocks enabled.
> sstable: fix nil pointer with DisableValueBlocks set

- sstable/colblk_writer.go
- sstable/testdata/writer_v5
When keys are written to a sstable writer out-of-order, the writer returns an error message. The error messages returned from the row-based and column-based writers varied, in part because the columnar writer did not readily have the previous key at hand. This commit adapts the column writer to synthesize the previous user key for the purpose of embedding it within the returned error message.
This will ensure cockroach unit tests that assert on these errors behave correctly when metamorphically switching between row and column blocks.
> sstable: reconcile out-of-order key error messages

- sstable/colblk/unsafe_slice.go
> colblk: remove unused UnsafeBuf

- cmd/pebble/main.go
- tool/db.go
- tool/find.go
- tool/sstable.go
- tool/tool.go
Use MakeReaderOptions when constructing the sstable.ReaderOptions in individual subcommands. This is more maintainable and fixes a bug whereby the find command was unable to read columnar sstables written in a non-default KeySchema.
> tool: use MakeReaderOptions

- sstable/colblk_writer.go
- sstable/data_test.go
- sstable/testdata/writer_v5
- sstable/writer_test.go
24.3 backports of #4146 and #4147
> crl-release-24.3: backport sstable writer bug fixes

- internal/cache/clockpro.go
- internal/cache/entry.go
- Removed entry.peekValue, since there was existing code in clockpro.go that directly accesses e.val, and the method indirection hinders readability.
- Updated the comment about cgo pointer rules since entry no longer points to shard.
- Removed the comment about shard size which suggested that all the blocks of a file are mapped to the same shard, since that is not true.
- Added an assertion when a test entry has a value being set.
> cache: misc tiny cleanups

- table_cache.go
- testdata/ingest
- testdata/metrics
An `sstable.ReaderProvider` is necessary whenever an sstable has value
blocks. Currently, we allocate one every time we create a point
iterator.
This commit makes the `tableCacheShardReaderProvider` usable in
parallel and maintains a long-lived instance in the `tableCacheValue`.
> table cache: use a long-lived ReaderProvider

- internal/keyspan/span.go
- sstable/rowblk/rowblk_fragment_iter.go
- sstable/writer.go
- sstable/writer_rangekey_test.go
Previously the ordering of range keys within a range key block was a bit muddled and undefined. Before encoding a Span of range keys to the underlying RawWriter, the sstable.Writer type previously sorted the span's keys by suffix. However, the row-based sstable writer always serializes RANGEKEYSETs of a Span first, followed by RANGEKEYUNSETs and then RANGEKEYDELs.
Confusingly, the rowblk fragment iterator also sorted keys by trailer when iterating backwards, but not forwards. The columnar RawWriter preserved the order of keys in the span passed to EncodeSpan, and this order was preserved during iteration.
This commit adapts the sstable.Writer type to sort a range key Span's keys by trailer and then suffix before encoding. This provides determinism and matches the ordering of keys produced …
> sstable: order range keys consistently in colblk and rowblk encodings

- sstable/colblk/testdata/uints
- sstable/colblk/uints_test.go
Previously the body of the array doubling loop in UintBuilder.Set was
unexercised:
```
for n2 <= row {
n2 <<= 1 /* double the size */
}
```
In part due to the initialization that precedes the loop:
```
n2 := max(b.array.n<<1, 32)
```
This commit adds a datadriven test case that exercises it, and a new
TestUintsRandomized randomized test that is reasonably likely to exercise it as
well.
> colblk: ensure test coverage of UintBuilder array doubling

- tool/sstable.go
Avoid seeking to the empty key, instead calling First to seek to the beginning of the table, if `sstable scan` is called without providing a start key.
> tool: use First in scan if no start key is provided

- internal/keyspan/span.go
- sstable/rowblk/rowblk_fragment_iter.go
- sstable/writer.go
- sstable/writer_rangekey_test.go
24.3 backport of #4160.
----
Previously the ordering of range keys within a range key block was a bit muddled and undefined. Before encoding a Span of range keys to the underlying RawWriter, the sstable.Writer type previously sorted the span's keys by suffix. However, the row-based sstable writer always serializes RANGEKEYSETs of a Span first, followed by RANGEKEYUNSETs and then RANGEKEYDELs.
Confusingly, the rowblk fragment iterator also sorted keys by trailer when iterating backwards, but not forwards. The columnar RawWriter preserved the order of keys in the span passed to EncodeSpan, and this order was preserved during iteration.
This commit adapts the sstable.Writer type to sort a range key Span's keys by trailer and then suffix before encoding. This provides determinism and matches …
> crl-release-24.3: sstable: order range keys consistently in colblk and rowblk encodings

- open.go
- wal/reader.go
- wal/wal.go
When we finish replaying a WAL, log the logical log which will encode all the replayed segment files (if WAL failover resulted in multiple physical files).
```
[JOB 1] WAL 000002: {(data,000)} stopped reading at offset: (data/000002.log: 0); replayed 0 keys in 0 batches
```
Additionally, implement the SafeFormatter interface to ensure that relevant details are not redacted.
Informs #4162.
> db: log additional WAL details during replay

- db_test.go
- go.mod
- go.sum
- options.go
- sstable/options.go
- sstable/reader.go
The `fifo` library has moved into `crlib`; switch to the updated
location.
> bump crlib, switch to crlib/fifo

- checkpoint.go
- db_test.go
- wal/failover_manager.go
- wal/failover_manager_test.go
- wal/standalone_manager.go
- wal/wal.go
Copy all the WALs provided by the wal.Manager. This is guaranteed to be a superset of the WALs in the flushable queue. Additionally, collect the WALs while holding DB.mu to ensure the DB can't complete a flush and mark a relevant WAL as obsolete before the call to (wal.Manager).List acquires the WAL manager's mutex.
> db: clean up Checkpoint collection of WALs

- sstable/colblk_writer.go
- sstable/layout.go
- sstable/reader.go
- sstable/rowblk_writer.go
- sstable/testdata/writer_value_blocks
- sstable/valblk/valblk.go
- sstable/valblk/valblk_test.go
- sstable/valblk/writer.go
- sstable/value_block.go
- sstable/writer_test.go
Move value-block Handle types, encoding/decoding routines and the value block Writer into a new valblk package. Add additionally commentary to document the new valblk package's interface.
> sstable/valblk: new package

- internal/buildtags/invariants_off.go
- internal/buildtags/invariants_on.go
The `off` and `on` file names were reversed (in https://github.com/cockroachdb/pebble/pull/4117). This leads to confusion
in the bazel build files and patches.
> buildtags: correct file names

- metamorphic/ops.go
- metamorphic/options.go
Previously, if we had external storage enabled, we'd always download in a download op. This meant we didn't really test cases where a download could change the state of the LSM relative to not doing the download.
This change adds a metamorphic test option (toggled randomly) that disables the download operation in 50% of runs.
> metamorphic: add a test option to make downloadOp no-op

- sstable/internal.go
- sstable/layout.go
- sstable/options.go
- sstable/reader.go
- sstable/reader_common.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/reader_virtual.go
- sstable/valblk/reader.go
- sstable/valblk/valblk.go
- sstable/value_block.go
- sstable/writer_test.go
- table_cache.go
Move the facilities around reading value blocks into the valblk package.
> valblk: move reader, fetcher

- ingest.go
- internal/base/comparer.go
- iterator_histories_test.go
- open.go
- testdata/iter_histories/prefix_iteration
We now allow sstables to have range key bounds that have suffixes in them, during ingestion. This is to allow for Cockroach-side defragmentation of range keys. This change ensures that such suffixed range keys are adjacent and defrag cleanly with rangekeys in other ingested sstables, to not cause panics later on in the read path.
Fixes #3829.
> db: verify ingest sst bounds are suffixless or adjacent

- wal/failover_writer_test.go
> wal: reduce flake in TestConcurrentWritersWithManyRecords

- sstable/colblk_writer.go
- sstable/copier_test.go
- sstable/testdata/copy_span
Previously, in the colblk implementation of copyDataBlocks, we were reusing a buffer that could under some cases be passed directly to the write queue and would get written to sstable while later blocks are being read into the same buffer.
This change also improves tests around CopySpan() to better test cache hit/miss cases.
Fixes https://github.com/cockroachdb/cockroach/issues/131332.
> sstable: fix improper buffer reuse in copyDataBlocks

- sstable/colblk_writer.go
- sstable/copier_test.go
- sstable/testdata/copy_span
Backport of #4181 
Previously, in the colblk implementation of copyDataBlocks, we were reusing a buffer that could under some cases be passed directly to the write queue and would get written to sstable while later blocks are being read into the same buffer.
This change also improves tests around CopySpan() to better test cache hit/miss cases.
Fixes https://github.com/cockroachdb/cockroach/issues/131332.
> crl-release-24.3: sstable: fix improper buffer reuse in copyDataBlocks

- sstable/colblk/index_block_test.go
This test TestIndexIterInitHandle relies on the test block remaining in the block cache. Hold on to a handle for the duration of the test to ensure it.
Fix #4172.
> colblk: fix handle misuse in TestIndexIterInitHandle

- iterator.go
This commit optimizes the process of zeroing the iterAlloc struct in the `Iterator.Close` method.
The function resets the alloc struct, re-assign the fields that are being recycled, and then return it to the pool. We now split the first two steps, instead of doing them in a single step (e.g. `*alloc = iterAlloc{...}`). This is because the compiler can avoid the use of a stack allocated autotmp iterAlloc variable (~12KB, as of Dec 2024), which must first be zeroed out, then assigned into, then copied over into the heap-allocated alloc. Instead, the two-step process allows the compiler to quickly zero out the heap allocated object and then assign the few fields we want to preserve.
```
name                                           old time/op    new time/op    delta …
```
> iterator: optimize zeroing of iterAlloc in `Iterator.Close`

- internal/base/comparer.go
- internal/crdbtest/crdb.go
- internal/crdbtest/crdb_bench_test.go
- internal/crdbtest/crdb_test.go
- internal/crdbtest/key_schema_test.go
- internal/crdbtest/rowblk_bench_test.go
- sstable/block/block.go
- sstable/block_property_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/index_block.go
- sstable/colblk/index_block_test.go
- sstable/colblk_writer.go
- sstable/copier.go
- sstable/layout.go
- sstable/reader.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/rowblk/rowblk_bench_test.go
- sstable/rowblk/rowblk_fragment_iter.go
- sstable/rowblk/rowblk_fragment_iter_test.go
- sstable/rowblk/rowblk_index_iter.go
- sstable/rowblk/rowblk_iter.go
- sstable/rowblk/rowblk_iter_test.go
- sstable/rowblk/rowblk_rewrite.go
This commit adapts colblk.DataBlockIter to use a base.ComparePointSuffixes func
to compare keys against the synthetic suffix. Previously we used base.Compare
which is no longer a valid use of the base.Compare contract.
Informs https://github.com/cockroachdb/cockroach/issues/136709.
24.3 backport of #4189.
> crl-release-24.3: sstable: use ComparePointSuffix to compare against synthetic suffix

- tool/wal.go
Previously, we treated the entirety of the cmd line argument passed in as a filename for figuring out the log file's number. This change updates that logic to split out the filename before parsing the file number, to better work in cases where the WAL file is not in the current directory and/or has a ./ before it.
Fixes #3863.
> tool: fix wal filename parsing to only work on filename

- compaction.go
- compaction_picker.go
- internal/base/compaction.go
- internal/compact/run.go
- options.go
This change adds an interface that users of Pebble can implement to integrate a compaction limiter that gets information about compaction bytes read and bytes written. This change also threads that interface (and a simple no-op implementation by default) through the compaction and flush code paths.
Informs #1329.
> db: add an interface for a slot-based compaction limiter

- internal/arenaskl/arena.go
- internal/arenaskl/arena_test.go
- internal/arenaskl/node.go
The field was added in c34894c4 and has been unused since c34894c4.
The `node` struct remains the same size due to padding.
I found this while looking into cache misses in the memtable's arena-backed skiplist and exploring ways (e.g. value separation, value + key suffix separation) to improve memory locality. So far, I haven't found anything that shows promise on microbenchmarks.
> arenaskl: remove node.allocSize field

- internal/cache/clockpro.go
- internal/cache/read_shard.go
- internal/cache/read_shard_test.go
- internal/cache/refcnt_normal.go
- internal/cache/refcnt_tracing.go
- internal/cache/testdata/read_shard
- sstable/block/buffer_pool.go
- sstable/colblk/index_block_test.go
- sstable/colblk/keyspan_test.go
- sstable/reader.go
Concurrent reads of the same block have been observed to cause very high
memory usage, and cause significant CPU usage for allocations/deallocations.
We now coordinate across multiple concurrent attempts to read the same
block via a readEntry, which makes the readers take turns until one
succeeds.
The readEntries are embedded in a map that is part of a readShard, where
there is a readShard for each cache.Shard. See the long comment in the
readShard declaration for motivation.
Callers interact with this new behavior via Cache.GetWithReadHandle,
which is only for callers that intend to do a read and then populate
the cache. If this method returns a ReadHandle, the caller has permission
to do a read. See the ReadHandle comment for details of the contract.
Fixes #4138
> cache,db: de-dup concurrent attempts to read the same block

- sstable/block/compression.go
- sstable/block/compression_test.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/rowblk_writer.go
- sstable/writer_test.go
When we don't compress a data buffer, the `RawColumnWriter` makes a
clone of the data buffer. In the sysbench workload, we see this
allocation taking place for almost half of the blocks (suggesting that
the data isn't very compressible).
Use the buffer that we would have used for the compressed data instead
of allocating a new one.
> sstable: optimize allocation of uncompressed buffers

- internal/base/lazy_value.go
- internal/base/merger.go
- internal/compact/iterator.go
- internal/compact/iterator_test.go
- internal/compact/run.go
During compaction iteration, defer the retrieval of values stored in value blocks until either:
a) we need to copy the value before stepping the iterator, or b) the compaction iterator yields the value to the main compaction loop.
This refactor ensures that when a KV is elided by a tombstone, we avoid unnecessarily loading its value from the external value block. Additionally, refactoring the compaction iterator interfaces to propagate LazyValues will be used by value separation (#112) in which we will sometimes propagate external value references to output sstables without ever retrieving the value.
Close #4197.
Informs #112.
> internal/compact: defer retrieval of external values

- internal/cache/read_shard.go
- acquire a read lock instead of a write lock, when context is canceled.
- add another assertion.
> cache: tiny tweaks to readShard

- sstable/valblk/writer.go
- sstable/writer_test.go
Add varying `vals-per-key` parameter and add an `EstimatedSize()` call
per key (which happens during compactions).
`Writer.Size()` unnecessarily loops through all the blocks instead of
using `totalBlockBytes`. This seems like an oversight: we only append
to `blocks` in `compressAndFlush` where we also update
`totalBlockBytes`. I verified that in all Pebble tests these values are
the same, using `if sz != w.totalBlockBytes { panic() }`.
```
name                                                                                                        old time/op    new time/op     delta
WriterWithVersions/vals-per-key=1/format=(Pebble,v5)/block=32KB/filter=false/compression=NoCompression        77.2ms ± 1%     76.6ms ± 0%    -0.70%  (p=0.008 n=5+5) …
```
> valblk: fix Writer.Size() performance

- sstable/colblk_writer.go
- sstable/writer_test.go
Add varying `vals-per-key` parameter and add an `EstimatedSize()` call
per key (which happens during compactions).
`Writer.Size()` unnecessarily loops through all the blocks instead of
using `totalBlockBytes`. This seems like an oversight: we only append
to `blocks` in `compressAndFlush` where we also update
`totalBlockBytes`. I verified that in all Pebble tests these values are
the same, using `if sz != w.totalBlockBytes { panic() }`.
> crl-release-24.3: valblk: fix Writer.Size() performance

- cmd/pebble/main.go
- tool/db.go
Add a version flag to `pebble` and `pebble db` which prints the
supported format versions.
```
$ go run ./cmd/pebble --version
pebble benchmarking/introspection tool
supported Pebble format versions: 13-19
$ go run ./cmd/pebble db --version
DB introspection tools
supported Pebble format versions: 13-19
```
> cmd/pebble: add version flag

- internal/invalidating/iter.go
- internal/invariants/invariants.go
- internal/invariants/off.go
- internal/invariants/on.go
- objstorage/objstorageprovider/vfs_readable.go
- sstable/colblk/keyspan.go
- sstable/colblk/uints.go
- sstable/reader_iter.go
- sstable/rowblk/rowblk_fragment_iter.go
The `invariants.Sometimes()` was not being inlined even though it
resolves to a `return false` when invariants aren't on. It looks like
the inline decision happens before some phases of dead code
elimination. This function is called in some very hot paths inside the
columnar block builder.
This change moves `Sometimes()` into the `on.go/off.go` files where it
can be simplified for the `off` case. We also add some
`invariants.Enabled` and `invariants.UseFinalizers` checks (which are
constant, unlike function calls) in hot paths.
```
CockroachDataBlockWriter/AlphaLen=4,Prefix=8,Shared=2,KeysPerPrefix=2,valueLen=8-10  75.3µs ± 1%  74.4µs ± 0%  -1.19%  (p=0.000 n=8+8)
```
> invariants: fix non-inlined empty function call

- metamorphic/config.go
- metamorphic/key_manager.go
- metamorphic/options.go
- metamorphic/options_test.go
- metamorphic/testkeys.go
Allow KeyFormat to specify a KeySchema that should be used by the metamorphic tests for columnar block sstables. This is in preparation for use of the cockroachkvs package within the metamorphic test.
Informs #4167.
> metamorphic: allow KeyFormat to specify a KeySchema

- cmd/pebble/main.go
- tool/db.go
Add a version flag to `pebble` and `pebble db` which prints the
supported format versions.
```
$ go run ./cmd/pebble --version
pebble benchmarking/introspection tool
supported Pebble format versions: 1-16
$ go run ./cmd/pebble db --version
DB introspection tools
supported Pebble format versions: 1-16
```
> pebble-release-1.1: cmd/pebble: add version flag

- cmd/pebble/main.go
- tool/db.go
Add a version flag to `pebble` and `pebble db` which prints the supported format versions.
```
$ go run ./cmd/pebble --version
pebble benchmarking/introspection tool
supported Pebble format versions: 13-19
$ go run ./cmd/pebble db --version
DB introspection tools
supported Pebble format versions: 13-19
```
> pebble-release-2.0: cmd/pebble: add version flag

- tool/db.go
- tool/testdata/db_upgrade
Add a `db upgrade` command that ratches up the DB version to the newest one.
> pebble-release-2.0: tool: add db upgrade command

- tool/data_test.go
- tool/db.go
- tool/testdata/db_upgrade
Add a `db upgrade` command that ratches up the DB version to the
newest one.
> pebble-release-1.1: tool: add db upgrade command

- compaction.go
- options.go
- options_test.go
Add a way to configure Pebble with an informative partitioning of the
key space. Each partition is a named key category; we use these for
pprof labels.
We currently set these pprof labels for compactions. In the future, we
will allow turning on labels in the read/write paths for specific
investigations.
Sample CRDB configuration code:
```
var userKeyCategories = pebble.MakeUserKeyCategories(
EngineComparer.Compare,
[]pebble.UserKeyCategory{
{Name: "local-1", UpperBound: toEngineKey(keys.LocalRangeIDPrefix.AsRawKey())},
{Name: "rangeid", UpperBound: toEngineKey(keys.LocalRangeIDPrefix.AsRawKey().PrefixEnd())},
{Name: "local-2", UpperBound: toEngineKey(keys.LocalRangePrefix)},
{Name: "range", UpperBound: toEngineKey(keys.LocalRangePrefix.PrefixEnd())},
{Name: "local-3", UpperBound: …
```
> db: add UserKeyCategories

- file_cache.go
- testdata/ingest
- testdata/metrics
With the addition of blob files, blob file readers will also be stored in the file cache (to ensure that Cockroach respects file-descriptor limits). This commit updates the fileCacheValue.reader field to be an untyped interface in preparation.
Informs #112.
> db: use interface for fileCacheValue reader

- cmd/pebble/ycsb.go
- internal/randvar/randvar.go
- internal/randvar/skewed_latest.go
- internal/randvar/uniform.go
- internal/randvar/zipf.go
- metamorphic/config.go
- metamorphic/generator.go
- metamorphic/generator_test.go
- metamorphic/key_manager.go
- metamorphic/key_manager_test.go
- metamorphic/meta.go
- metamorphic/options_test.go
- metamorphic/parser_test.go
- metamorphic/testkeys.go
Add a method to the KeyGenerator interface for informing a key generator of the existence of a previously-used key. Use this for updating the distribution of suffixes generated by the testkey generator.
In future work, the Cockroach key generator will use it to parse keys and update its distribution of MVCC suffixes as well.
> metamorphic: add KeyGenerator.RecordPrecedingKey

- cockroachkvs/cockroachkvs.go
- cockroachkvs/cockroachkvs_test.go
Add functions to format cockroach keys into human-readable strings and parse the human-readable strings back out into the binary format. This will be used by the metamorphic test when it serializes operations.
For parity with the Cockroach repo's key pretty-printing, timestamps use a formatting matching the hlc timestamp's pretty printing format.
> cockroachkvs: add FormatKey, ParseFormattedKey

- sstable/blob/blob.go
- sstable/blob/blob_test.go
- sstable/blob/testdata/writer
- sstable/block/compression.go
- sstable/layout.go
- sstable/valblk/valblk.go
- sstable/valblk/writer.go
Add blob FileWriter type for writing out blob files, consisting of a series of
value blocks, a value block index and a footer.
Add the initial, largely unimplemented stencil of a FileReader type.
Informs #112.
> sstable/blob: new package

- internal/cache/block_map.go
- internal/cache/clockpro.go
- internal/cache/read_shard.go
- internal/cache/read_shard_test.go
Minor cleanup to the cache code:
- use the `key` type in the shard interface
- remove the `fileKey` type that's not used directly
- use fibonacci hash for shard hash function
> cache: use key type internally

- metamorphic/config.go
- metamorphic/options.go
- metamorphic/testkeys.go
Move the configuration of block-property collectors into the KeyFormat, since it's dependent on the key format used.
> metamorphic: move block property collectors into KeyFormat

- sstable/colblk_writer.go
- sstable/data_test.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
- sstable/writer.go
Previously the suffix rewriter required the sstable being rewritten be held entirely in memory but relied on a type assertion to a *sstable.memReader deep in a complicated call stack. This commit refactors this call stack to explicitly propagate the byte slice holding the in-memory sstable, making this requirement explicit and unambiguous.
> sstable: lift suffix rewriting in-memory requirement into type signature

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- download.go
- internal/compact/run.go
Previously, we did not release a base.CompactionSlot after move, copy or delete-only compactions, resulting in huge leaks in slot utilization in any non-noop implementation of slots. This change fixes that.
> compaction: fix release of compaction slots

- sstable/block/compression.go
- sstable/layout.go
`vfs.Write` is allowed to mangle the input buffer (it happens with
encryption). Consequently the layout writer can mangle block data;
this change documents this for the relevant methods.
> sstable: document layout methods that can mangle block data

- internal/keyspan/keyspanimpl/testdata/level_iter
- metrics.go
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/testdata/db_lsm
We never use a secondary cache in practice. Remove the statistic
unless there is something to show.
> db: don't print secondary cache stats when they are empty

- db_test.go
- internal/cache/clockpro.go
- internal/cache/clockpro_test.go
- internal/cache/entry.go
- internal/cache/read_shard.go
- internal/cache/read_shard_test.go
- internal/cache/value.go
- sstable/block/buffer_pool.go
- sstable/block/buffer_pool_test.go
- sstable/block/compression_test.go
- sstable/colblk/index_block_test.go
- sstable/colblk/keyspan_test.go
- sstable/copier.go
- sstable/reader.go
- sstable/rowblk/rowblk_fragment_iter_test.go
- sstable/writer_test.go
The cache `Handle` is just a `*Value` and the distinction is
confusing. In particular, functions like `Set` take a `*Value` and
return that same value as a `Handle` (and yet you can't make a
`Handle` yourself from a `*Value`).
This change removes the `Handle` and replaces its usage with `*Value`.
> cache: remove Handle

- sstable/colblk/index_block_test.go
We were initializing the index block decoder using the go data buffer
(resulting in that buffer only being referenced from Cgo memory). Fix
the `Init` call to use the actual buffer.
Fixes #4242
> colblk: fix decoder initialization in TestIndexIterInitHandle

- sstable/block/compression.go
- sstable/block/compression_test.go
Fix a bug whereby Buffer.AppendValue would fail to sufficiently grow the capacity of its backing byte slice. Previously, AppendValue used cap(buf) when calculating the argument to slices.Grow, but slices.Grow expects its argument to be in terms of the slice's current length, not capacity.
Add a focused randomized test that catches the bug. Also, add invariant assertions around a BufHandle's existence in or out of a pool.
Fix #4247.
> sstable/block: fix Buffer growth bug

- internal/compact/iterator.go
Previously saveValue would copy the current iteration value into valueBuf, but if valueBuf was grown to accommodate a larger value, valueBuf wasn't stored. This lead to repeated re-allocations of buffers sufficiently large to hold the iteration value.
> compact: save the resized valueBuf when saving values

- compaction.go
- db.go
- event.go
- event_listener_test.go
Add an event when the low disk space runs low. We post an event when
we go below each threshold (10%, 5%, 2%, 1%) and we keep posting the
event periodically.
Informs https://github.com/cockroachdb/cockroach/issues/129319
> db: add a LowDiskSpace event

- objstorage/objstorageprovider/vfs_writable.go
- sstable/block/compression.go
- sstable/layout.go
- sstable/rowblk_writer.go
Pepper in some invariant-only buffer mangling on block write paths.
With this we can repro the failure in
https://github.com/cockroachdb/cockroach/issues/138662 with the meta
test.
Fix `RawRowWriter.addDataBlock` to make a copy of the block data when
it's not compressed (similar to the columnar writer), because in that
case the writing out can mangle the buffer.
The sstable copier (during Download) uses `addDataBlock` with a buffer
from the cache, which we are not allowed to modify.
Informs https://github.com/cockroachdb/cockroach/issues/138662
> sstable: fix row writer mangling of cache block

- objstorage/objstorageprovider/vfs_writable.go
- sstable/block/compression.go
- sstable/layout.go
- sstable/rowblk_writer.go
Pepper in some invariant-only buffer mangling on block write paths.
With this we can repro the failure in
https://github.com/cockroachdb/cockroach/issues/138662 with the meta
test.
Fix `RawRowWriter.addDataBlock` to make a copy of the block data when
it's not compressed (similar to the columnar writer), because in that
case the writing out can mangle the buffer.
The sstable copier (during Download) uses `addDataBlock` with a buffer
from the cache, which we are not allowed to modify.
Informs https://github.com/cockroachdb/cockroach/issues/138662
> crl-release-24.3: sstable: fix row writer mangling of cache block

- objstorage/test_utils.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
- sstable/suffix_rewriter_test.go
Previously, during suffix rewriting, both row and columnar sstable writers
could pass the input sstable's filter block into objstorage.Writable.Write by
passing a subslice of the original input sstables byte slice. The Write method
is permitted to mangle the input buffer, which in this case would corrupt the
original input sstable.
> sstable: copy filter block during suffix rewriting

- cockroachkvs/cockroachkvs_bench_test.go
- data_test.go
- file_cache.go
- ingest.go
- level_checker_test.go
- level_iter_test.go
- merging_iter_test.go
- sstable/blob/blob.go
- sstable/blob/blob_test.go
- sstable/block/block.go
- sstable/copier_test.go
- sstable/data_test.go
- sstable/options.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/writer_test.go
- tool/db.go
- tool/find.go
- tool/sstable.go
Add block.ReaderOptions and refactor sstable.ReaderOptions to contain them, and the blob reader to also use block.Reader and block.ReaderOptions.
> sstable: refactor ReaderOptions

- cockroachkvs/cockroachkvs.go
Bringing in a few comments from the CRDB code.
Informs [139068](https://github.com/cockroachdb/cockroach/issues/139068)
> cockroachkvs: minor updates

- metamorphic/ops.go
The metamorphic tests sometimes generates iterators with block-property filters constraining the set of MVCC timestamps that should be observed. Previously keys that were not suffixed were guaranteed to always be surfaced. The testkeys block-property collector would map an unsuffixed key to the maximal interval, ensuring any block containing an unsuffixed key would be visited by all time-bound iterators.
The cockroachdb block-property collector does not give non-MVCC keys the same treatment. Instead, it simply ignores non-timestamped keys for the purpose of calculating block-property collectors. This results in non-deterministic presence of non-MVCC keys in a time-bound iterators iteration. With the introduction of cockroach kvs in the metamorphic test, we'll need consistent, …
> metamorphic: skip non-suffixed keys on time-bound iterators

- checkpoint.go
- open_test.go
- testdata/checkpoint
- testdata/event_listener
- testdata/mkdir_all_and_sync_parents
- vfs/mem_fs.go
Previously Open with a relative path containing a single element would fail on real filesystems, because Open would attempt to open the empty path.
Backport of #3847 for #4268.
> pebble-release-1.1: db: fix Open issue with single-item relative paths

- internal/cache/clockpro.go
In invariants builds, perform the invariant checks in metaCheck only 1% of the time. In a Cockroach runtime-assertion roachtest performing an import, these checks consumed 40% of CPU.
Informs cockroachdb/cockroach#139424.
Informs cockroachdb/cockroach#139396.
Informs cockroachdb/cockroach#139485.
Informs cockroachdb/cockroach#139401.
Informs cockroachdb/cockroach#139401.
Informs cockroachdb/cockroach#139446.
> cache: only sometimes perform metaCheck invariant checks

- metamorphic/key_manager.go
- metamorphic/ops.go
- metamorphic/testdata/key_manager
When constructing an external object, only the first point key with each unique prefix is added to the sstable. The key manager strives to maintain consistency with this behavior to ensure that the it maintains correct key histories after an ingestion of an external object. The key manager however also will discretize range deletions, sometimes creating keyMetas for keys that do not exist as point keys on the associated writer. The presence of these was confusing the key manager's calculation of which keys would end up in the external object.
This commit updates the external object calculation to account for the existence of the range deletions. Future work may refactor the tracking of range deletions to track range deletions separately from point keys and as continuous spans.
Fix #4267.
> metamorphic: ignore rangedels for deduplicating point prefixes

- external_test.go
- internal/manifest/manifest_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- internal/metamorphic/metarunner/main.go
- metamorphic/config.go
- metamorphic/example_test.go
- metamorphic/generator.go
- metamorphic/generator_test.go
- metamorphic/key_manager.go
- metamorphic/key_manager_test.go
- metamorphic/meta.go
- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/options_test.go
- metamorphic/parser.go
- metamorphic/parser_test.go
- metamorphic/testkeys.go
This commit fixes a handful of bugs in the abstraction of the KeyFormat (today only the testkeys KeyFormat exists). It also introduces a --key-format= CLI flag for configuring the key format to use in a particular run of the metamorphic test.
> internal/metamorphic: fix bugs in KeyFormat abstraction

- cockroachkvs/blockproperties.go
- cockroachkvs/cockroachkvs.go
Copy the MVCC time interval block property collector and filter implementations from CockroachDB's pkg/storage package. These will be used within the metamorphic test when using the cockroachkvs key format.
> cockroachkvs: pull in MVCC block-property collector, filter

- internal/cache/clockpro.go
- internal/cache/read_shard.go
- internal/cache/refcnt_normal.go
- internal/cache/refcnt_tracing.go
We use a separate `readShard` mutex to to protect the `readMap` and
each entry's ref count. This removes the possibility of a couple of
cornercases, making the code much cleaner. We also now avoid
write-locking the entire cache shard when we start a read.
This will also potentially allow moving read buffer management into
`readShard` in the future (and having separate `readShard` sets per
store).
> cache: readShard: use a separate mutex

- metamorphic/config.go
- metamorphic/generator.go
- metamorphic/ops.go
- metamorphic/parser.go
- metamorphic/testkeys.go
In 8a1bd363 the filterMin and filterMax fields were converted to encoded suffixes so that they could accommodate more complex representations of timestamps, including those used by the CockroachDB key format. The commit in 8a1bd363 inadvertently inverted the meaning of filterMin and filterMax due to the descending ordering of timestamp suffixes. This accidentally inverted the comparisons in SkipPoint, resulting in excessive filtering.
This commit defines filterMin as the suffix that sorts smaller [the one with a larger timestamp], and filterMax as the suffix that sorts larger [the one with a smaller timestamp]. The ordering of these fields in serialized ops is reversed so that parsing an ops file produced by a previous Pebble version populates the appropriate field.
Assertions and …
> metamorphic: fix time-bound filtering

- cockroachkvs/cockroachkvs.go
- cockroachkvs/cockroachkvs_test.go
- cockroachkvs/key_schema_test.go
- compaction.go
- ingest.go
- internal/base/comparer.go
- internal/testkeys/testkeys.go
- metamorphic/key_manager.go
- options.go
- sstable/rowblk/rowblk_rewrite.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
Add a new optional ValidateKey func to the Comparer type. There are many instances where we reconsititute or rewrite user keys. When the Comparer provides a way to assert that a key is well structured, we can catch any malformed keys closer to the moment of corruption.
The AssertComparer is updated to make use of ValidateKey, and the CheckComparer func is updated to ensure that all the keys it constructs validate if ValidateKey is provided. Additionally, the metamorphic key generator is updated to validate new keys at generation time.
> db: add optional ValidateKey Comparer func

- cockroachkvs/cockroachkvs.go
- cockroachkvs/testdata/key_schema_key_seeker
The untimestamped key is special and sorts before all other keys. Previously the cockroachkv KeySeeker treated it as sorting after all other keys for the purposes of IsLowerBound.
> cockroachkvs: handle untimestamped keys in IsLowerBound

- metamorphic/build.go
- metamorphic/ops.go
**metamorphic: add additional key validation**
Add additional calls to Comparer.ValidateKey throughout the metamorhpic tests.
**metamorphic: format keys in iterator positions**
When printing iterator positions, format keys according to the KeyFormat.
> metamorphic: add additional key validation

- cockroachkvs/cockroachkvs.go
- sstable/rowblk_writer.go
**cockroachkvs: allow empty keys in ValidateKey**
Previously (cockroachkvs.Comparer).ValidateKey considered an empty key to be
invalid. Empty keys are possible in some circumstances (notably in an index
block in a sstable that contains no point keys). Adapt ValidateKey to allow
these keys so that we can apply ValidateKey to separator keys.
**sstable: validate separator keys before writing**
Validate separator keys before writing them out to an index block by calling
Comparer.ValidateKey.
> sstable: validate index separator keys before writing

- sstable/block/compression.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/rowblk_writer.go
Currently `CompressAndChecksum` can alias the original data buffer if
we do not compress the data (either because compression is disabled,
or the data was not compressible enough). In most cases, we write out
the resulting data which can mangle the buffer. This leads most
callers to check if the buffer is not compressed and make a copy.
This change moves the copy into `CompressAndChecksum`; we always use
the dst buffer, even if we don't compress. This simplifies the callers
and makes things less fragile.
> sstable: always use target buffer for CompressAndChecksum

- cockroachkvs/cockroachkvs.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- metamorphic/cockroachkvs.go
- metamorphic/config.go
- metamorphic/generator_test.go
Add a new KeyFormat that uses the cockroach encoding of KV pairs in the
metamorphic test, expanding test coverage to cover the cockroachkvs package.
Fixes #4167.
> metamorphic: add CockroachKeyFormat

- cockroachkvs/blockproperties.go
Add an Init method to MVCCWallTimeIntervalRangeKeyMask that initializes the mask appropriately, inclluding setting the appropriate block-property name.
> cockroachkvs: add MVCCWallTimeIntervalRangeKeyMask.Init

- external_iterator.go
- external_iterator_test.go
- iterator.go
Use a block.BufferPool to hold on to allocated block buffers during iteration
of external sstables. During external iteration, blocks read aren't inserted
into a shared block cache. Previously this meant that every block read
allocated a new buffer for the block. Using a small buffer pool allows block
reads to reuse buffers over the life of the external iterator, reducing CPU
from requesting memory from the memory allocator. Additionally, plumbing a
buffer pool means the block reader won't attempt to store the block in the
zero-sized, ephemeral block cache used by the external iterator.
```
goos: darwin
goarch: arm64
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │ …
```
> db: use BufferPool on external iterators

- compaction.go
- internal/base/cleaner.go
- internal/base/filenames.go
- internal/base/filenames_test.go
- objstorage/objstorageprovider/provider.go
- objstorage/objstorageprovider/provider_test.go
- objstorage/objstorageprovider/testdata/provider/local
- objstorage/objstorageprovider/vfs.go
- obsolete_files.go
- open.go
- open_test.go
- testdata/cleaner
- testdata/version_check_consistency
- tool/testdata/db_excise
- version_set.go
Introduce a new file type for blob files. These files will contain the values
for keys stored in separate sstables. This commit introduces the new file type
and plumbs some simple machinery, including around deleting obsolete blob files
subject to the same deletion pacing as sstables.
Informs #112.
> objstorage: add FileTypeBlob

- sstable/block/block.go
- sstable/block/buffer_pool.go
Currently if we create an `sstable.Reader` without setting cache
options, a zero-sized cache is created just for that reader. We change
the code to not require a cache and we clean up the Read code a little
by separating the "normal" path.
> block: allow Read without a cache

- db.go
- file_cache.go
- file_cache_test.go
- iterator.go
- open.go
This change renames `fileCacheContainer` to a more appropriate
`fileCacheHandle`. The function to create a handle is now a method on
`FileCache` and the "create new file cache if nil" logic is pulled out
into the caller.
Some cleanup of the fileCache tests, which makes it more clear how the
caches are initialized.
> db: minor file cache cleanup

- cmd/pebble/db.go
- cmd/pebble/replay.go
- cmd/pebble/replay_test.go
- external_test.go
- internal/manifest/manifest_test.go
- metamorphic/options.go
- metamorphic/options_test.go
- metamorphic/test.go
- open.go
- options.go
- options_test.go
Add a `CacheSize` option which is used when a `Cache` is not
specified. This removes the need for the awkward `NewCache` option
parsing hook, which creates a `Cache` that has to be `Unref`ed
elsewhere.
> db: add CacheSize option

- internal/manifest/testdata/version_edit_decode
- internal/manifest/version_edit_test.go
Convert the TestVersionEditDecode unit test to use a datadriven test file.
> internal/manifest: convert TestVersionEditDecode to datadriven

- file_cache.go
See https://github.com/cockroachdb/cockroach/issues/140454
> db: tolerate fileCacheHandle.metrics() call after close

- db.go
- file_cache.go
- file_cache_test.go
- open.go
- open_test.go
- options.go
- options_test.go
The `fileCache` is integrated with the block Cache and uses the
`cache.ID` to separate files from different stores.
We can achieve the same by keying on the `*fileCacheHandle` instead of
`cache.ID`, which simplifies things a bit. It would also allow using
a single file cache and multiple block caches if we ever need that
(perhaps for value separation).
> db: key fileCache by handle

- internal/manifest/blob_metadata.go
- internal/manifest/blob_metadata_test.go
- internal/manifest/testdata/version_edit_decode
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
Extend the version edit binary encoding to support encoding the addition and removal of blob files and recording a sstable's reference to a blob file. This commit only introduces the binary serialization of this data and the corresponding Go structures. Future work will connect it to version edit application and the current Version.
Informs #112.
> internal/manifest: extend version edits for blob metadata

- sstable/colblk/prefix_bytes.go
- sstable/colblk/uints.go
- sstable/colblk/uints_test.go
```
name              old time/op  new time/op  delta
ByteWidth/n=1-10  1.06ns ± 1%  0.63ns ± 0%  -40.84%  (p=0.001 n=7+7)
ByteWidth/n=2-10  1.05ns ± 0%  0.63ns ± 0%  -40.60%  (p=0.000 n=8+8)
ByteWidth/n=4-10  1.06ns ± 0%  0.63ns ± 0%  -40.71%  (p=0.000 n=8+7)
ByteWidth/n=8-10  1.05ns ± 0%  0.63ns ± 0%  -40.61%  (p=0.000 n=8+8)
```
Add a more efficient variant used for offsets, where the minimum value
is always 0.
Reorganize the code so that we only check one `if` in the common path.
Benchmark shows a slight improvement (I expect it to be a higher when
the keys are very small).
```
PrefixBytes/alphaLen=2/building-10    710µs ± 0%   708µs ± 0%  -0.34%  (p=0.029 n=4+4)
```
This value is not used outside of `Put` so we don't need to keep two
of its values around.
----
Fixes #4322
> colblk: optimizations to PrefixBytesBuilder.Put and DetermineUintEncoding

- compaction_picker_test.go
- compaction_test.go
- data_test.go
- external_iterator_test.go
- format_major_version_test.go
- ingest_test.go
- iterator_test.go
- mem_table.go
- merging_iter_test.go
- metamorphic/test.go
- obsolete_files_test.go
- open.go
- options.go
- options_test.go
- tool/db.go
Simplify the awkward `EnsureDefaults` API; it no longer accepts a nil
receiver.
> db: simplify EnsureDefaults

- file_cache.go
- sstable/reader_iter.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
The file cache implements a closure it calls the 'closeHook' which is propagated to opened iterators to be invoked when the iterators are closed. This hook is responsible for releasing hte ref count on the open sstable Reader. In race builds, it's also used to track the stack traces of iterator opens to aid debugging leaks of open iterators. This closeHook previously required the iterator pass in itself as a sstable.Iterator interface value, but the closeHook really only required its pointer and none of the interface methods. It also returned an error that was never non-nil. This commit removes the error return value and updates the iterator parameter to be any type.
This ensures that other usages of the file cache, such as blob files, can use close hooks with non-sstable.Iterator types.
> db: relax type of fileCache's closeHook

- sstable/rowblk/rowblk_bench_test.go
- sstable/rowblk/rowblk_iter.go
Remove the unused and unnecessary Key and Value methods on the Iter type. Additionally, fix up the comments on RawIter which incorrectly referred to the internal iterator interface which RawIter no longer implements.
> rowblk: remove unused Iter methods, clean up RawIter comments

- cockroachkvs/cockroachkvs_test.go
- cockroachkvs/key_schema_test.go
- internal/compact/iterator.go
- sstable/copier_test.go
- sstable/rowblk/rowblk_index_iter.go
- sstable/rowblk/rowblk_iter_test.go
When applicable, prefer InternalKV's value helpers over directly accessing the InternalKV's V field. This is in preparation for refactorings surrounding the LazyValue that will be easier with fewer direct accesses.
> *: prefer InternalKV value helpers

- internal/cache/cache_test.go
- internal/cache/clockpro.go
On x86 an atomic.Load is a simple load, whereas a Store is an atomic
`XCHG` operation which involves a memory barrier. Frequently accessed
blocks are likely to be accessed many times between two sweeps of the
clockpro hand.
On a gceworker:
```
name         old time/op    new time/op    delta
CacheGet-24    20.1ns ± 4%    18.9ns ± 5%  -5.82%  (p=0.002 n=10+10)
```
Fixes #4328
> cache: Load before Store

- compaction.go
- compaction_test.go
- db.go
- file_cache.go
- level_checker_test.go
- level_iter.go
- level_iter_test.go
- merging_iter_test.go
- testdata/metrics
The internalIterOpts struct had all the fields of a block.ReadEnv. Replace them with a block.ReadEnv field. Additionally, update instances where we construct internalIterOpts to eagerly retrieve a categorized iterator stats accumulator.
> db: embed block.ReadEnv in internalIterOpts

- compaction.go
- flushable.go
- ingest.go
- internal/manifest/annotator_test.go
- internal/manifest/btree.go
- internal/manifest/btree_test.go
- internal/manifest/l0_sublevels.go
- internal/manifest/level_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_test.go
- version_set.go
Rework the collection of obsolete files during a Version unref to accumulate the obsolete files into a new ObsoleteFiles type. This is in preparation for the introduction of blob files into manifest Versions. Unreferences will also need to unreference blob files and accumulate obsolete blob files.
> internal/manifest: add ObsoleteFiles type

- db_test.go
- file_cache.go
- file_cache_test.go
- internal/genericcache/cache.go
- internal/genericcache/cache_test.go
- internal/genericcache/node.go
- internal/genericcache/shard.go
- obsolete_files.go
- open.go
- sstable/reader.go
- testdata/ingest
- testdata/metrics
This code extracts the internal logic of the file cache and makes it
into a generally useful type.
We no longer intermingle the cache infrastructure logic with the file
cache specifics. This will help when we extend the file cache to
support blob files.
> db: rework fileCache to use genericcache

- ingest.go
- internal/manifest/blob_metadata.go
- internal/manifest/btree.go
- internal/manifest/level_metadata.go
- internal/manifest/testdata/version_edit_apply
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
Extend the BlobReference type with a pointer to a shared BlobFileMetadata
struct describing the blob file. Apply reference counting to these
BlobFileMetadata to track the lifecycle of a blob file.
Informs #112.
> internal/manifest: maintain BlobFileMetadata references

- sstable/block/buffer_pool.go
- sstable/copier.go
- sstable/layout.go
- sstable/reader.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_test.go
- sstable/reader_virtual.go
- sstable/suffix_rewriter.go
- testdata/ingest
- testdata/metrics
- tool/find.go
- tool/sstable.go
Reduce the size of the Reader struct by 152 bytes by removing a few redundant Comparer fields and moving the meta buffer pool off the struct and into a heap pool. Pebble maintains a Reader struct per open sstable. In large LSMs, per-Reader memory is non-trivial.
Additionally, fix a bug during Reader initialization if the sstable's comparer did not match the default ReaderOptions.Comparer. Previously, we'd initialize the individual comparer funcs correctly, using the Comparer we retrieved from the o.Comparers map, but incorrectly initialized the top-level Comparer field to point to the default ReaderOptions.Comparer.
> sstable: reduce size of Reader struct

- batch.go
- cockroachkvs/cockroachkvs_bench_test.go
- cockroachkvs/cockroachkvs_test.go
- internal/arenaskl/skl_test.go
- internal/base/internal.go
- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
- internal/base/value.go
- internal/compact/iterator.go
- internal/invalidating/iter.go
- iterator.go
- level_checker.go
- merging_iter.go
- metamorphic/build.go
- scan_internal.go
- scan_internal_test.go
- sstable/block/kv.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/layout.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/rowblk/rowblk_iter.go
- sstable/valblk/reader.go
- sstable/writer_test.go
Add an InternalValue type as an internal-only type representing a value or instructions on how to retrieve the value. For now, InternalValue is a simple wrapper around a LazyValue. Separating the two allows us to extend the interval value type without expanding the public API unnecessarily. With the introduction of values externalized in blob files (#112), we expect to further modify the InternalValue.
> *: add InternalValue

- internal/manifest/testdata/version_edit_apply
- internal/manifest/testdata/version_edit_decode
- internal/manifest/testutils.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
Add TableMetadata.BlobReferenceDepth, which is an upper bound on the number of blob files that a reader scanning the table would need to keep open if they only open and close each referenced blob file once. The BlobReferenceDepth will be approximated in practice, by assigning the outputs of a compaction a blob reference depth equal to the sum of the highest blob reference depth in each input level of the compaction.
This commit introduces the field and adds it to the encoding and debug output of TableMetadata and VersionEdits.
Informs #112.
> internal/manifest: add BlobReferenceDepth and encode in manifest

- go.mod
- go.sum
Incorporate latest changes to `swiss` which add support for go1.24 and
s390x.
> go.mod: bump swiss

- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
- internal/base/value.go
- sstable/block/kv.go
- sstable/block/kv_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/rowblk/rowblk_iter.go
- sstable/rowblk_writer.go
- sstable/valblk/reader.go
- sstable/valblk/valblk.go
- sstable/writer_test.go
The value length is encoded as a uint32, but the ValueFetcher's Fetch method expected a signed int32.
> *: refactors for value separation

- cockroachkvs/cockroachkvs_bench_test.go
- cockroachkvs/rowblk_bench_test.go
- sstable/colblk/raw_bytes.go
- sstable/colblk/uints.go
Using `benchdiff` for this package is impractical, there are many
hundreds of config variations across the benchmarks. This commit
switches to using a small number of configs instead.
There is not much benefit to using an unsafe slice rather than a
regular slice. We still use an unchecked get (except that we can check
the bounds in invariant builds).
```
name                                                                                                                                         old time/op    new time/op    delta
CockroachDataColBlockWriter/AlphaLen=8,Prefix=8,Shared=4,KeysPerPrefix=4,Logical=10,ValueLen=8-24                                               139µs ± 1%     140µs ± 1%    ~     (p=0.853 n=10+10)
CockroachDataColBlockWriter/AlphaLen=8,Prefix=128,Shared=64,KeysPerPr …
```
> colblk: remove use of UnsafeRawSlice in UintBuilder

- excise.go
- ingest.go
Move DB.excise to its own file. Additionally, refactor the accumulation of EFOS protected ranges of EFOSes that overlap the excise span by moving it into a helper function in excise.go.
> db: move excise to a separate file

- checkpoint_test.go
- compaction_picker_test.go
- data_test.go
- db.go
- db_test.go
- excise.go
- ingest.go
- ingest_test.go
- metrics_test.go
- table_stats_test.go
- testdata/determinism
- testdata/excise
Add an Excise method to the DB allowing an excise without an accompanying ingestion. This will be used in CockroachDB to recover from corruption by excising out corrupted sstables.
For now, this implementation uses DB.ingest. I think a future refactor should be able to clean these code paths up and potentially refactor excise to be independent of the ingest codepath. Today, it's necessary to reuse the logic to perform excises as 'flushable ingests.'
Closes #4286.
> db: add DB.Excise

- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
- sstable/blob/blob.go
- sstable/blob/blob_test.go
- sstable/blob/fetcher.go
- sstable/blob/fetcher_test.go
- sstable/blob/testdata/value_fetcher
- sstable/blob/testdata/writer
- sstable/block/block.go
- sstable/block/kv.go
- sstable/block/kv_test.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/valblk/reader.go
Add a ValueFetcher type that implements base.ValueFetcher for fetching values
from blob files. Additionally, fix a couple bugs around block lengths in the
serialization of blob files that were hidden by the lack of read-path testing.
Closes #4321.
Informs #112.
> blob: add ValueFetcher

- Makefile
- commit_test.go
- internal/buildtags/slow_build_off.go
- internal/buildtags/slow_build_on.go
- internal/intern/intern_test.go
- internal/lint/lint_test.go
- internal/manifest/btree_test.go
- internal/manifest/manifest_test.go
- internal/metamorphic/metaflags/meta_flags.go
- objstorage/objstorageprovider/sharedcache/shared_cache_test.go
- replay/replay_test.go
The asan build has been mostly failing due to timeouts. These slower
tests automatically adjust for race builds, but not for asan builds.
This commit adds a `buildtags.Instrumented` constant which indicates
if this is a race or asan or msan build. We switch various
`RaceEnabled` test checks to the new flag so we include these builds.
> avoid timeouts and failures with asan builds

- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
- internal/base/value.go
- internal/compact/iterator.go
- internal/compact/iterator_test.go
- internal/compact/testdata/iter
Adapt the compaction iterator to preserve blob file references by cloning the
LazyValues. Compactions that do not rewrite blob files will avoid ever
retrieving the corresponding values.
Additionally, fix LazyValue.Clone to copy the BlobFileNum of the LazyFetcher.
Informs https://github.com/cockroachdb/pebble/issues/112.
> internal/compact: preserve blob references

- event.go
- file_cache.go
- file_cache_test.go
- obsolete_files.go
- open.go
- sstable/blob/blob.go
- testdata/ingest
- testdata/metrics
Adapt the file cache to implement the blob.ReaderProvider interface, supporting
the caching of blob files alongside sstable files. The two file types will
share a cache since open sstables and blob files both contribute towards the
same open file descriptor limits.
Informs https://github.com/cockroachdb/pebble/issues/112.
> db: implement blob.ReaderProvider on fileCacheHandle

- sstable/internal.go
- sstable/table.go
- sstable/valblk/valblk.go
This commit removes the +1 from valblk.HandleMaxLen. The code treats the handle as the data after the valuePrefix byte, noninclusive of the byte. The assertion that blockHandleLikelyMaxLen is large enough now incorporates the +1 of the valuePrefix byte explicitly. This was the only usage the depended on HandleMaxLen being inclusive of the valuePrefix byte.
Additionally, this commit documents blockHandleMaxLenWithoutProperties and adds an assertion that blockHandleLikelyMaxLen is larger than the length of an inline blob value handle (blob.MaxInlineHandleLength) plus the valuePrefix byte.
> sstable: clean up and document maximum handle lengths

- batchrepr/reader.go
- cockroachkvs/cockroachkvs.go
- sstable/colblk/prefix_bytes.go
- sstable/rowblk/rowblk_iter.go
- sstable/valblk/valblk.go
Use unsafe.Add to simplify pointer math throughout the codebase, primarily in manually-inlined varint decoding routines.
> *: use unsafe.Add throughout

- internal/compact/spans_test.go
- sstable/test_utils.go
ReadAll is importing testutils which is pulling testify and other test dependencies in the final binary
move function to separate package since it's only called from test files
> sstable: update testutil readall to return an error

- internal/devtools/roachvet/forbidden_imports.go
- internal/devtools/roachvet/main.go
Disallow `pebble`, `cmd/pebble`, and `sstable` from depending on
`testing`.
This test fails now but will pass once #4389 merges.
> devtools: add a forbidden imports linter

- objstorage/test_utils.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
Previously, during suffix rewriting, both row and columnar sstable writers
could pass the input sstable's filter block into objstorage.Writable.Write by
passing a subslice of the original input sstables byte slice. The Write method
is permitted to mangle the input buffer, which in this case would corrupt the
original input sstable.
Informs cockroachdb/cockroach#141493.
Backport of #4265.
> crl-release-24.3: sstable: copy filter block during suffix rewriting

- objstorage/test_utils.go
- sstable/suffix_rewriter.go
Previously, during suffix rewriting, both row and columnar sstable writers
could pass the input sstable's filter block into objstorage.Writable.Write by
passing a subslice of the original input sstables byte slice. The Write method
is permitted to mangle the input buffer, which in this case would corrupt the
original input sstable.
Informs cockroachdb/cockroach#141493.
Backport of #4265.
> crl-release-24.2: sstable: copy filter block during suffix rewriting

- sstable/suffix_rewriter.go
Previously, during suffix rewriting, both row and columnar sstable writers could pass the input sstable's filter block into objstorage.Writable.Write by passing a subslice of the original input sstables byte slice. The Write method is permitted to mangle the input buffer, which in this case would corrupt the original input sstable.
Backport of #4265.
Informs cockroachdb/cockroach#141493.
> crl-release-23.2: sstable: copy filter block during suffix rewriting

- internal/manifest/blob_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/strparse/strparse.go
Pull out the manifest package's debugParser used to facilitate parsing of debug representation's of data structures into a new internal package. This is in preparation for an additional use in parsing debug representations of blob handles.
> internal/strparse: new package

- sstable/colblk/testdata/prefix_bytes
Add a simple test case demonstrating PrefixBytes using English words beginning with 'inter'.
> colblk: add a PrefixBytes test case using 'inter-' words

- internal/manifest/l0_sublevels.go
- internal/manifest/level_metadata.go
- internal/manifest/version.go
- testdata/compaction_check_ordering
All callers of `makeBTree` either need just the tree or just the
slice, so make a separate function for the slice.
> manifest: cleanup related to making level slices

- compaction.go
- event.go
- event_listener_test.go
- ingest_test.go
- testdata/concurrent_excise
Small change to not report `ErrCancelledCompaction` as a background
error. We still log it as an `Infof`, but we do it in Pebble and not
in the event listener.
> db: don't report compaction cancelled errors

- internal/manifest/l0_sublevels.go
Use slices.SortFunc instead of implementing the sort.Interface in the implementation of L0 sublevels.
> internal/manifest: use slices.SortFunc

- compaction_picker_test.go
- testdata/compaction_picker_target_level
This test did not properly set up the `L0Sublevels` with the
compaction information (in regular operation, `L0Sublevels` is kept in
sync with in-progress compactions).
To fix this, we use `L0Sublevels.InitCompactingFileInfo()` before
picking a compaction. This prevents an error case during compaction
picking.
> db: fix CompactionPickerTargetLevel test

- internal/manifest/l0_sublevels.go
- internal/manifest/version.go
Add sanity checking to `L0Sublevels`.
The `L0Index` check was failing, suggesting that the code below made
an incorrect assumption about files exactly matching the last files in
the new levelMetadata:
```
// Update interval indices for new files.
for i, f := range files {
f.L0Index = s.levelMetadata.Len() + i
```
I added extra checks to `AddL0Files` to bail out if this assumption is
not correct.
> manifest: add L0Sublevels sanity checks, fix L0Index

- event.go
- event_listener_test.go
- file_cache.go
- file_cache_test.go
- sstable/block/block.go
We now add the `DataCorruptionInfo` to corruption errors and allow
users to extract it using `ExtractDataCorruptionInfo()`.
> db: embed DataCorruptionInfo into corruption errors

- internal/manual/manual_cgo.go
It's unclear if the Go race detector can detect race in memory that's allocated by cgo, but under the assumption it can't, this commit adapts the manual package to allocate some of its allocations using standard Go allocations in race builds. The hope is that if data races exist in the data structures allocated using the manual package, sometimes Go-allocating this memory will surface them in our race-build test runs.
Motivated by cockroachdb/cockroach#142868.
> internal/manual: sometimes Go-allocate memory in race builds

- objstorage/objstorageprovider/remote.go
- objstorage/objstorageprovider/remote_backing.go
- objstorage/objstorageprovider/remote_readable.go
- objstorage/objstorageprovider/remote_readable_test.go
- objstorage/objstorageprovider/testdata/provider/shared_attach_after_unref
- objstorage/remote/mem.go
- sstable/reader_test.go
An external file can go missing after we "open" it (i.e. after we
obtain a `remote.ObjectReader`). This should be marked as a corruption
error; this commit fixes this and adds a test.
Informs #4285
> objstorage: check for missing file in remoteReadable

- compaction_scheduler.go
- open.go
- open_test.go
- options.go
It was incorrectly using the same compaction scheduler across two DB open calls.
Fixes #4421
> db: fix TestCheckpointManyFiles

- .github/workflows/nigthly-tests.yaml
- go.mod
Also update nightly build to stop testing against 1.23. Adding 1.24
will be investigated separately.
> go.mod: require go 1.23

- compaction_test.go
- data_test.go
- external_iterator.go
- external_iterator_test.go
- format_major_version.go
- format_major_version_test.go
- ingest.go
- ingest_test.go
- internal/testutils/blob_handles.go
- testdata/external_iterator
- testdata/ingest_load
This commit adds validation to NewExternalIter and the ingestion pathways prohibiting the external iteration or ingestion of sstables containing blob references.
This could conceivably be relaxed in the future if we provide a mechanism to provide the referenced blob files too, but for now this is an error condition.
Additionally the most recent experimental format major version that introduces the TableFormatPebblev6 is renamed to capture the fact that it most significantly will enable use of blob value separation (in addition to the introduction of a checksum covering sstable footer data).
> db: prohibit ingestion or external iteration of sstables with blob refs

- rangedel/rangedel.go
- rangekey/rangekey.go
Add a new `rangedel` package and define some aliases that can be used
from outside Pebble, similar to the `rangekey` package.
> rangedel: expose Fragmenter and Decode

- data_test.go
- external_iterator_test.go
- ingest_test.go
- internal/blobtest/handles.go
- value_separation_test.go
Move blob-related testutils into a separate blobtest package. Future work will require a transitive dependency on the sstable package (via internal/manifest).
> internal/blobtest: move blob testutils

- compaction_picker.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
I'm not sure this can fail currently, but we should still check it. A
WIP change caused `l0SublevelInfo not created for compaction out of
L0` because of this missing check.
> db, manifest: clean up error cases when picking compactions

- sstable/colblk_writer.go
- sstable/format.go
- sstable/table.go
- sstable/table_test.go
- sstable/testdata/writer_v6
Use the correct footer size in (*RawColumnarWriter).EstimatedSize, and refactor some of the footer size accesses to use a new FooterSize method on the TableFormat type.
> sstable: use correct footer size in EstimatedSize

- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
- sstable/colblk/testdata/data_block/external_value
- sstable/testdata/writer_blob_value_handles
In data blocks, set the 'isValueExternal' bit for rows encoding handles to values stored in external blob files. Previously only value block handles set this bit.
> colblk: mark blob handles as external values

- compaction_test.go
- format_major_version.go
- format_major_version_test.go
- range_del_test.go
- testdata/compaction_picker_pick_file
- testdata/compaction_picker_scores
- testdata/ingest_external
- testdata/metrics
- tool/testdata/db_upgrade
Export the new format major version that enables use of TableFormatPebblev6, and update FormatNewest to point to this format major version. This new table format adds the checksum over the sstable footer, and allows the encoding of blob handles within the value column.
> db: export FormatTableFormatV6

- cockroachkvs/cockroachkvs_bench_test.go
- external_iterator.go
- file_cache.go
- level_iter_test.go
- merging_iter_test.go
- sstable/block_property_test.go
- sstable/random_test.go
- sstable/reader.go
- sstable/reader_common.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_test.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/reader_virtual.go
Add a IterOptions struct for propagating point iterator configuration options. The set of possible configuration options has ballooned and the struct makes call sites a little more legible.
> sstable: add IterOptions

- obsolete_files.go
- options.go
- options_test.go
- pacer.go
- pacer_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
- testdata/metrics
closes https://github.com/cockroachdb/pebble/issues/2674
expose delete pacing options:
```
// FreeSpaceThreshold specifies the minimum amount of free disk space that Pebble
// attempts to maintain. If free disk space drops below this threshold, deletions
// are accelerated above TargetByteDeletionRate until the threshold is restored.
// Default is 16GB.
FreeSpaceThreshold uint64
// FreeSpaceTimeframe sets the duration (in seconds) within which Pebble attempts
// to restore the free disk space back to FreeSpaceThreshold. A lower value means
// more aggressive deletions. Default is 10s.
FreeSpaceTimeframe uint64
// ObsoleteBytesMaxRatio specifies the maximum allowed ratio of obsolete files to
// live files. If this ratio is exceeded, Pebble speeds up deletions above the
// …
```
> db: allow delete pacing knobs to be configurable

- compaction.go
- compaction_test.go
- get_iter_test.go
- internal/compact/splitting_test.go
- internal/keyspan/keyspanimpl/level_iter_test.go
- internal/manifest/annotator_test.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/manifest_test.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
- level_checker_test.go
- open_test.go
- replay/replay.go
- tool/db.go
- tool/lsm.go
- tool/manifest.go
- version_set.go
Require a non-nil version to simplify the interface and the code a
bit.
We also remove unnecessary nil checks for `Version.L0Sublevels`, which
is never the case.
> manifest: simplify BulkVersionEdit.Apply

- internal/manifest/version_edit.go
In invariants.Enabled, we rebuild the L0 sublevels from scratch to
cross-check the result of the incremental updating. However, this
rebuilding reinitializes the fields inside TableMetadata (like
L0Index), correcting any mistake made by `AddL0Files` (but only in
invariant builds..)
This change adds an `invariant.Sometimes(10)` to only do this
sometimes.
In the future, we will want to move out the TableMetadata fields we're
modifying and cross-check those values too.
> manifest: don't crosscheck AddL0Files result every time

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- download_test.go
- file_cache_test.go
- ingest.go
- ingest_test.go
- internal/manifest/annotator_test.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/level_metadata.go
- internal/manifest/manifest_test.go
- internal/manifest/version.go
- internal/manifest/version_edit_test.go
- internal/manifest/version_test.go
- iterator_test.go
- level_checker.go
- lsm_view.go
- open.go
- table_stats.go
- tool/db.go
- tool/lsm.go
- tool/manifest.go
- version_set.go
- version_set_test.go
Use the new Go 1.23 iter.Seq type to range over collections of TableMetadata. The LevelMetadata and LevelSlice types are updated with All methods, returning an iter.Seq[*TableMetadata].
> *: use iter.Seq for ranging over TableMetadata

- internal/blobtest/handles.go
- internal/compact/run.go
- internal/manifest/blob_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- sstable/blob/blob_test.go
- sstable/blob/handle.go
- sstable/data_test.go
- value_separation.go
- value_separation_test.go
Define a BlobReferenceDepth and move the documentation of the blob reference
depth from the TableMetadata field onto the type, making the documentation more
discoverable.
Define a BlobReferences type for a slice of blob references, and use it on the
TableMetadata for its BlobReferences field. When yielding an InternalValue
backed by a blob value handle to higher levels, an iterator will need to map
the blob handle's file reference index to the file number. This type will
implement the interface to perform this mapping.
> internal/manifest: define BlobReferenceDepth type

- external_iterator.go
- external_iterator_test.go
If creating a point or range key iterator fails, we leak some
iterators that were already opened. This immediately leads to a
BufferPool-related panic when closing the `Iterator`.
This change adds an enhancement to a test which reproduces the panic
and patches up the error paths.
Informs github.com/cockroachdb/cockroach/issues/141606
> crl-release-25.1: pebble: add missing cleanup in a NewExternalIter error case

- external_iterator.go
- external_iterator_test.go
If creating a point or range key iterator fails, we leak some
iterators that were already opened. This immediately leads to a
BufferPool-related panic when closing the `Iterator`.
This change adds an enhancement to a test which reproduces the panic
and patches up the error paths.
Informs github.com/cockroachdb/cockroach/issues/141606
> crl-release-24.3: pebble: add missing cleanup in a NewExternalIter error case

- sstable/block/block.go
- sstable/block/compressor.go
- tool/testdata/sstable_check
Remove mention of 'table' from codepaths used by both sstable and blob file readers.
> block: remove 'table' from error messages

- .github/workflows/ci.yaml
This will make a difference when we fork the next pebble-release
branch.
> github: add pebble-release branches to CI

- compaction.go
- download.go
- excise.go
- ingest.go
- ingest_test.go
- internal/manifest/version.go
This set of changes attempts to tame the function that excises a file which is several screens long.
This is in preparation for work on #4417.
`Version.Overlaps()` returns all "indirect" overlaps in L0. This is
not what we want when we look for files to excise.
This change replaces `Overlaps()` with using `LevelSlice.Overlaps()`
on each sublevel/level.
Now that we only call it when there is overlap, `exciseTable` asserts
that the table is overlapping.
Add a separate function for applying an excise to a `VersionEdit`;
`exciseTable` is simplified to return the left and right tables.
> db: file excise code cleanup

- internal/keyspan/keyspanimpl/level_iter_test.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/manifest_test.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- replay/replay.go
- tool/db.go
- tool/manifest.go
- version_set.go
In `logAndApply`, we `Apply` the bulk version edit without holding
`DB.mu`. `Apply` internally updates `L0Organizer` which is supposed to
be protected by `DB.mu`.
Note that the same thing was happening before the `L0Organizer`, but
because the incremental updating of sublevels doesn't work with
compactions, we were always generating new `L0Sublevels`, so the
previous version's sublevels were still usable.
We separate the updating of L0 sublevels from `Apply` so we can do the
former under the lock.
Fixes #4471
> db: fix L0Organizer race during logAndApply

- compaction.go
- file_cache_test.go
- format_major_version.go
- ingest.go
- metrics.go
- version_set.go
Replace the ad-hoc `map[int]*LevelMetrics` that is passed to
`logAndApply` with a `levelMetricsDelta` type which makes it more
clear what it is and how it is used.
> db: clean up level metric updates

- compaction.go
- db.go
- obsolete_files.go
- testdata/cleaner
- testdata/event_listener
- testdata/version_set
- version_set.go
- version_set_test.go
Add a zombieObjects type for tracking the lifecycle of zombie objects. Today this is used for zombie sstable objects. With the introduction of blob files (#112) we'll also need to track the lifecycle of zombie blob file objects.
Additionally, refactor the lifecycle so that a file is considered either zombie or obsolete but not both. And avoid scanning the list of zombie objects on every call to Metrics, instead incrementally maintaining stats on the zombieObjects type.
> db: refactor obsolete, zombie file tracking

- internal/manifest/version_test.go
Add a unit test that asserts ranging over a LevelMetadata or LevelSlice through their All methods result in zero allocations.
> internal/manifest: add test for zero allocs when ranging

- sstable/layout.go
- sstable/rowblk/rowblk_iter_test.go
- sstable/rowblk_writer.go
In 0bd9d12668041bcc2b2be84afcf97a123cf13b3a I missed a couple of call sites that should propagate errors.
> sstable: fix swallowed errors

- cockroachkvs/rowblk_bench_test.go
- options.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/options.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/rowblk/rowblk_bench_test.go
- sstable/rowblk/rowblk_fragment_iter_test.go
- sstable/rowblk/rowblk_iter_test.go
- sstable/rowblk/rowblk_rewrite.go
- sstable/rowblk/rowblk_writer.go
- sstable/rowblk/rowblk_writer_test.go
- sstable/rowblk_writer.go
- sstable/writer_test.go
25.1 backport of #4503 and #4507.
----
Relax the maximum block size to reclaim 7-unused bits within the restart offsets. This provides additional leeway for massive blocks we're sometimes forced to construct due to very large key-value pairs. Additionally, this commit turns this check into an error that we propagate up and out of the sstable Writer rather than panicking with an assertion failure. In practice this means a DB that hits this limit may fail a compaction without bringing down the node. The DB may repeat the compaction in a busy loop, but it's possible for the DB to make some forward progress in the meantime.
> crl-release-25.1: rowblk: raise max block size to (1<<31)-1; error rather than panic

- internal/crdbtest/rowblk_bench_test.go
- options.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/options.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/rowblk/rowblk_bench_test.go
- sstable/rowblk/rowblk_fragment_iter_test.go
- sstable/rowblk/rowblk_iter_test.go
- sstable/rowblk/rowblk_rewrite.go
- sstable/rowblk/rowblk_writer.go
- sstable/rowblk/rowblk_writer_test.go
- sstable/rowblk_writer.go
- sstable/writer_test.go
24.3 backport of #4503 and #4507.
----
Relax the maximum block size to reclaim 7-unused bits within the restart offsets. This provides additional leeway for massive blocks we're sometimes forced to construct due to very large key-value pairs. Additionally, this commit turns this check into an error that we propagate up and out of the sstable Writer rather than panicking with an assertion failure. In practice this means a DB that hits this limit may fail a compaction without bringing down the node. The DB may repeat the compaction in a busy loop, but it's possible for the DB to make some forward progress in the meantime.
> crl-release-24.3: rowblk: raise max block size to (1<<31)-1; error rather than panic

- data_test.go
- testdata/ingest_external
Modernize the ingest_external test to use the SST contents format
instead of the batch format for `build-remote`.
> db: use ParseTestSST in TestIngestExternal

- options.go
- sstable/block.go
- sstable/block_test.go
- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/writer.go
- sstable/writer_test.go
23.2 backport of #4503 and #4507.
----
Relax the maximum block size to reclaim 7-unused bits within the restart offsets. This provides additional leeway for massive blocks we're sometimes forced to construct due to very large key-value pairs. Additionally, this commit turns this check into an error that we propagate up and out of the sstable Writer rather than panicking with an assertion failure. In practice this means a DB that hits this limit may fail a compaction without bringing down the node. The DB may repeat the compaction in a busy loop, but it's possible for the DB to make some forward progress in the meantime.
> crl-release-23.2: rowblk: raise max block size to (1<<31)-1; error rather than panic

- options.go
- sstable/block_test.go
- sstable/block_writer.go
- sstable/reader.go
- sstable/suffix_rewriter.go
- sstable/writer.go
- sstable/writer_test.go
24.1 backport of #4503 and #4507.
----
Relax the maximum block size to reclaim 7-unused bits within the restart offsets. This provides additional leeway for massive blocks we're sometimes forced to construct due to very large key-value pairs. Additionally, this commit turns this check into an error that we propagate up and out of the sstable Writer rather than panicking with an assertion failure. In practice this means a DB that hits this limit may fail a compaction without bringing down the node. The DB may repeat the compaction in a busy loop, but it's possible for the DB to make some forward progress in the meantime.
> crl-release-24.1: rowblk: raise max block size to (1<<31)-1; error rather than panic

- data_test.go
- ingest_test.go
- internal/blobtest/handles.go
- sstable/data_test.go
- sstable/layout.go
- sstable/test_utils.go
- sstable/testdata/writer_blob_value_handles
- sstable/writer_test.go
Minor refactor so `blobtest` doesn't depend on `manifest` and can be
used from `sstable`.
Use blobtest and replace the one-off `blobInlineHandle` parsing.
> sstable: use blobtest

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- go.mod
- go.sum
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/problemspans/by_level.go
- internal/problemspans/by_level_test.go
- internal/problemspans/doc.go
- internal/problemspans/set.go
- internal/problemspans/set_test.go
- internal/problemspans/testdata/by_level
- internal/problemspans/testdata/set
- open.go
- testdata/compaction_corruption
- testdata/compaction_picker_pick_file
Note: first commit is #4403.
The structure uses a library I wrote over the weekend: https://github.com/RaduBerinde/axisds
I hope to add (over time) more data structures around intervals, order maintenance, etc.
Package problemspans provides functionality for tracking and managing
key spans that have been identified as problematic. It allows users to
add spans with associated expiration times, check if a given key range
overlaps any active (non-expired) spans, and remove spans when issues
are resolved.
We check the problem spans to avoid any overlap when picking
compactions. Note that normally the problem spans are empty and these
checks are avoided.
We add a test that verifies that compactions still go through after
trying to compact a non-existent external file.
Fixes #4285
Informs #1192
> db: add problem spans data structure, check when picking auto compactions

- compaction.go
- compaction_picker.go
- compaction_test.go
- data_test.go
- db.go
- file_cache_test.go
- flushable_test.go
- format_major_version.go
- ingest.go
- version_set.go
- version_set_test.go
This commit replaces `logAndApply` with an `UpdateVersionLocked`
function that takes a closure and performs the log "locking" around
that closure. This makes it impossible for a caller to mess up the
locking.
I plan to look at the remaining uses of logLock/logUnlock separately.
> db: rework logAndApply

- sstable/rowblk/rowblk_64bit_test.go
- sstable/rowblk/rowblk_iter_test.go
Move tests that should only run on 64-bit architectures behind a build flag.
> rowblk: move 64-bit tests build flag

- sstable/colblk/key_value_block.go
- sstable/layout.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/reader.go
- sstable/rowblk/rowblk_iter.go
We now pass in an iterator to `load` in order to range all over the keys and values.
> sstable: refactor prop block load

- db.go
- metrics.go
- metrics_test.go
- obsolete_files.go
- testdata/metrics
- version_set.go
This patch adds a method to our `Metrics` struct, `RemoteTablesTotal`,
that will compute the total size and count of remote tables.
Informs: [#143850](https://github.com/cockroachdb/cockroach/issues/143850)
> db: add support for remote table metrics

- sstable/rowblk/rowblk_64bit_test.go
- sstable/rowblk/rowblk_iter_test.go
Move tests that should only run on 64-bit architectures behind a build flag.
> crl-release-25.2: rowblk: move 64-bit tests build flag

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- go.mod
- go.sum
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/problemspans/by_level.go
- internal/problemspans/by_level_test.go
- internal/problemspans/doc.go
- internal/problemspans/set.go
- internal/problemspans/set_test.go
- internal/problemspans/testdata/by_level
- internal/problemspans/testdata/set
- open.go
- testdata/compaction_corruption
- testdata/compaction_picker_pick_file
Package problemspans provides functionality for tracking and managing
key spans that have been identified as problematic. It allows users to
add spans with associated expiration times, check if a given key range
overlaps any active (non-expired) spans, and remove spans when issues
are resolved.
We check the problem spans to avoid any overlap when picking
compactions. Note that normally the problem spans are empty and these
checks are avoided.
We add a test that verifies that compactions still go through after
trying to compact a non-existent external file.
Fixes #4285
Informs #1192
> crl-release-25.2: db: check problem spans when picking auto compactions

- cmd/pebble/write_bench.go
- compaction.go
- compaction_picker_test.go
- file_cache_test.go
- ingest.go
- iterator_test.go
- metrics.go
- metrics_test.go
- obsolete_files.go
- version_set.go
- version_set_test.go
Rename LevelMetrics fields that refer to 'files' to refer to 'tables' instead. With the introduction of value separation, significant volumes of data will live in blob files not accounted within these particular existing metrics.
> db: rename LevelMetrics table fields

- options.go
If `KeySchema` isn't found in the map, we silently fall back to the
default key schema. We now panic in this case.
> options: don't tolerate invalid KeySchema in MakeWriterOptions

- checkpoint.go
- compaction.go
- compaction_picker.go
- compaction_test.go
- data_test.go
- db.go
- download.go
- download_test.go
- excise.go
- file_cache.go
- file_cache_test.go
- ingest.go
- internal/manifest/level_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- internal/manifest/virtual_backings.go
- internal/manifest/virtual_backings_test.go
- lsm_view.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/virtual/virtual_reader_params.go
- table_stats.go
- tool/db.go
- tool/lsm.go
- tool/manifest.go
- version_set.go
- version_set_test.go
We don't know the value of this flag just from the TableMetadata,
which precludes pre-initializing `VirtualReaderParams`.
We initialize the virtual params in the file cache, but this is racy.
To fix this:
- we change Virtual to a bool, and change `VirtualReaderParams` to a
non-pointer field.
- we add `AttachVirtualBacking` and use that instead of setting
`FileBacking` directly. This function also initializes the
`VirtualParams`.
Fixes #4536
> db: fix virtual table race

- compaction.go
- excise.go
- excise_test.go
- ingest.go
- ingest_test.go
- testdata/excise
- testdata/excise_bounds
This PR is for the top commit only:
In the future we can easily change the policy for IngestAndExcise as
well if we decide to.
Fixes #4417
> db: allow loose excised table bounds when using DB.Excise()

- internal/metamorphic/metaflags/meta_flags.go
This test occasionally OOMs with `GOARCH=386`. Reduce the size of the
test for 32-bit builds.
> metamorphic: reduce test size for 32-bit

- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- internal/metamorphic/metarunner/main.go
- metamorphic/meta.go
`RunOnce` takes the `KeyFormat` separately, but the one we pass is
derived from the flags, not the one that is passed to us from e.g.
`TestMetaCockroachKVs`. This change fixes this.
Note that when running the test normally, the top-level process passes
`--key-format` to the child process, so in that case it works out.
> metamorphic: fix key format when running a single config

- compaction_test.go
- testdata/compaction_corruption
We use a larger keyspace and tweak L0 compaction knobs and target file
size to encourage more compactions into Lbase.
We also increase the timeouts to a generous 2 minutes and widen the
key range of the missing external file.
I stress tested this locally with `-p 10` and 5 second timeouts and
hit no failures in 200,000 iterations.
Fixes #4544
> db: deflake CompactionCorruption

- db.go
- internal/manifest/blob_metadata.go
- internal/manifest/blob_metadata_test.go
- internal/manifest/testdata/current_blob_file_set
- internal/manifest/version_edit.go
- metrics.go
- version_set.go
Previously although machinery existed to support removal of blob files in a
VersionEdit's DeletedBlobFiles, the field was never populated because there was
no logic to notice that the final reference to a blob file was removed. This
commit introduces a new type CurrentBlobFileSet that tracks the set of blob
files that are referenced within the latest Version of the LSM. The versionSet
is updated to maintain a CurrentBlobFileSet.
Before applying a new version edit, we pass the version edit through
CurrentBlobFileSet's ApplyAndUpdateVersionEdit. This method updates the
CurrentBlobFileSet's accounting of all extant references to blob files and adds
new entries to VersionEdit.DeletedBlobFiles if any blob file is now
unreferenced.
In the future CurrentBlobFileSet's index of blob files can be …
> manifest: track current blob file state in CurrentBlobFileSet

- compaction.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- download.go
- event.go
- format_major_version.go
- format_major_version_test.go
- obsolete_files.go
- open_test.go
- options.go
- options_test.go
- read_state.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/compaction/value_separation
- testdata/event_listener
- testdata/flushable_ingest
- testdata/iter_histories/blob_references
- testdata/value_separation_policy
- value_separation.go
Introduce a new experimental option and (unexported) format major verson that
together enable compaction-time separation of values into external blob files.
Informs #112.
> db: add compaction value separation mechanics

- compaction_test.go
- db.go
- get_iter.go
- testdata/compaction/value_separation
Adapt the getIter (used within the implementation of DB.Get) to initialize a blob value fetcher and propagate it down the iterator tree, ensuring we can retrieve the value of a blob-file separated value.
Informs #112.
> db: support reading separated values from DB.Get

- sstable/colblk_writer.go
- sstable/properties.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/testdata/writer_blob_value_handles
- sstable/testdata/writer_v5
- sstable/testdata/writer_v6
- sstable/testdata/writer_value_blocks
The RawColumnWriter has several bugs related to setting properties:
IndexSize: In previous table formats, IndexSize recorded the _uncompressed_ size of the index block.  The RawColumnWriter incorrectly totalled the compressed sizes of all index blocks.
TopLevelIndexSize: The RawColumnWriter did not set this property at all.
NumDataBlocks: When a table had a two-level index, the RawColumnWriter miscalculated NumDataBlocks. It improperly set the value to the number of entries in the first index block multipled by the count of bottom-level index blocks.
> sstable: fix IndexSize, TopLevelIndexSize and NumDataBlocks

- testdata/compaction/value_separation
Fix merge skew in TestCompaction/value_separation resulting from new sstable file sizes.
> db: fix TestCompaction/value_separation merge skew

- checkpoint.go
- objstorage/objstorage.go
- objstorage/objstorageprovider/provider.go
- testdata/checkpoint
When checkpointing the database through (*pebble.DB).Checkpoint, link or copy blob files referenced by sstables included in the checkpoint. When a checkpoint operation is limited by key range, the checkpoint will exclude blob files that are part of the current Version of the LSM but not referenced by any sstable overlapping the checkpointed key ranges. Similarly to excluded sstables, these excluded blob files will be marked as removed by a final version edit appended to the checkpoint's MANIFEST so that the MANIFEST accurately reflects the set of blob files in the checkpoint.
Close #4555.
> db: include blob files in checkpoints

- sstable/colblk_writer.go
- sstable/properties.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/testdata/writer_blob_value_handles
- sstable/testdata/writer_v5
- sstable/testdata/writer_v6
- sstable/testdata/writer_value_blocks
The RawColumnWriter has several bugs related to setting properties:
IndexSize: In previous table formats, IndexSize recorded the _uncompressed_ size of the index block.  The RawColumnWriter incorrectly totalled the compressed sizes of all index blocks.
TopLevelIndexSize: The RawColumnWriter did not set this property at all.
NumDataBlocks: When a table had a two-level index, the RawColumnWriter miscalculated NumDataBlocks. It improperly set the value to the number of entries in the first index block multipled by the count of bottom-level index blocks.
> crl-release-25.2: sstable: fix IndexSize, TopLevelIndexSize and NumDataBlocks

- sstable/colblk_writer.go
- sstable/properties.go
- sstable/testdata/columnar_writer/simple_binary
- sstable/testdata/writer_v5
- sstable/testdata/writer_value_blocks
The RawColumnWriter has several bugs related to setting properties:
IndexSize: In previous table formats, IndexSize recorded the _uncompressed_ size of the index block.  The RawColumnWriter incorrectly totalled the compressed sizes of all index blocks.
TopLevelIndexSize: The RawColumnWriter did not set this property at all.
NumDataBlocks: When a table had a two-level index, the RawColumnWriter miscalculated NumDataBlocks. It improperly set the value to the number of entries in the first index block multipled by the count of bottom-level index blocks.
> crl-release-25.1: sstable: fix IndexSize, TopLevelIndexSize and NumDataBlocks

- testdata/checkpoint
A spurious log rotation on the `db` database was showing up in the logs during later test cases that use different databases.
Example failure: https://github.com/cockroachdb/pebble/actions/runs/14539220052/job/40793696777
> db: deflake TestCheckpoint

- objstorage/objstorageprovider/remote_backing_test.go
- objstorage/objstorageprovider/remote_obj_name.go
- objstorage/objstorageprovider/remote_obj_name_test.go
- objstorage/objstorageprovider/remoteobjcat/catalog_test.go
- objstorage/objstorageprovider/remoteobjcat/testdata/catalog
- objstorage/objstorageprovider/remoteobjcat/version_edit.go
- objstorage/objstorageprovider/remoteobjcat/version_edit_test.go
Extend the objstorageprovider implementation to support files of type FileTypeBlob.
Close #4582.
> objstorageprovider: support remote blob files

- data_test.go
- iterator_histories_test.go
- testdata/large_keys
- version_set_test.go
Add a new datadriven unit test that exercises large keys with a long common shared prefix. This test demonstrates the worst-case unbounded block sizes.
Informs #4518.
> db: add TestLargeKeys

- internal/base/filenames.go
- internal/base/filenames_test.go
We should rename all uses of `FileNum` to `TableNum`. But changing all
uses would be a massive diff, causing problems with backports.
This change renames `base.FileNum` to `TableNum` and leaves a
`FileNum` alias that we will deprecate in time.
> base: introduce TableNum

- sstable/values.go
- tool/find.go
- tool/sstable.go
- tool/tool.go
This patch adds the ability for commands in the `tool` package (`find`, `sstable check`,`sstable scan`) that read sstables in isolation to support printing the inline blob handles of val-separated kvs.
Informs: #4448
> tool: add blob handle print mode to tools

- compaction_test.go
- data_test.go
- format_major_version.go
- format_major_version_test.go
- options.go
- value_separation.go
Export the format major version that allows use of value separation, but
leaving FormatNewest pointing to the previous format major version. Exporting
the format allows us to use the format major version from other packages (eg,
the metamorphic tests, the tool package, etc).
**db: avoid use of internal type in ValueSeparationPolicy**
Avoid use of the internal/manifest.BlobReferenceDepth type in the external
ValueSeparationPolicy type. Users are expected to construct a
ValueSeparationPolicy and must be able to construct a MaxBlobReferenceDepth
value.
Also, sneak in a small change to address this comment while we're here: https://github.com/cockroachdb/pebble/pull/4564#pullrequestreview-2778613182
> db: export FormatExperimentalValueSeparation

- go.mod
- go.sum
I forked `google/btree` into a new `btreemap` repository and changed
it to a better map-like API (changes are in many separate commits in
https://github.com/RaduBerinde/btreemap/commits/master/).
I updated `axisds` to use this instead of `btree` in
https://github.com/RaduBerinde/axisds/pull/1.
This will allow crdb to use Pebble without having to upgrade `btree`.
Informs https://github.com/cockroachdb/cockroach/issues/144488
> crl-release-25.2: go.mod: update axisds

- go.mod
- go.sum
I forked `google/btree` into a new `btreemap` repository and changed
it to a better map-like API (changes are in many separate commits in
https://github.com/RaduBerinde/btreemap/commits/master/).
I updated `axisds` to use this instead of `btree` in
https://github.com/RaduBerinde/axisds/pull/1.
This will allow crdb to use Pebble without having to upgrade `btree`.
Informs https://github.com/cockroachdb/cockroach/issues/144488
> go.mod: update axisds

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_scheduler.go
- compaction_test.go
- testdata/compaction/score_compaction_picked_before_manual
- testdata/compaction_picker_L0
- testdata/compaction_picker_read_triggered
Score-based compactions are important for maintaining LSM health.
Fixes #4571
> db: run score-based compactions before manual compactions

- internal/manifest/version_edit.go
- open.go
- record/record.go
- record/record_test.go
- record/testdata/walSync
- version_set_test.go
- wal/testdata/reader
> manifest,record: disambiguate unexpected EOFs

- compaction_test.go
- testdata/compaction_delete_only_hints
In CockroachDB snapshot reception ingests sstables. In some circumstances and verisons of CockroachDB, these sstables have RANGEDEL and RANGEKEYDEL keys spanning the entirety of the KV range's span in order to clear any previous range state.
When a replica is destroyed, CockroachDB may choose to write a RANGEDEL (and possibly a RANGEKEYDEL) over the replica's span to delete the data. If an original sstable from snapshot reception still exists, we would like this sstable to be dropped by a simple deletion-only compaction. This commit adds a unit test that demonstrates this behavior.
> db: test replica removal of snapshot sstable

- compaction_test.go
- testdata/compaction_delete_only_hints
In CockroachDB snapshot reception ingests sstables. In some circumstances and verisons of CockroachDB, these sstables have RANGEDEL and RANGEKEYDEL keys spanning the entirety of the KV range's span in order to clear any previous range state.
When a replica is destroyed, CockroachDB may choose to write a RANGEDEL (and possibly a RANGEKEYDEL) over the replica's span to delete the data. If an original sstable from snapshot reception still exists, we would like this sstable to be dropped by a simple deletion-only compaction. This commit adds a unit test that demonstrates this behavior.
> crl-release-24.3: db: test replica removal of snapshot sstable

- compaction.go
- compaction_test.go
- table_stats.go
- testdata/compaction_delete_only_hints
Previously resolving a deletion-only compaction hints did not consider an
sstable with an end boundary that's exclusive. This prevented the hint from
being applied in circumstances where it could have been used. In particular, in
the context of CockroachDB this bug prevented the range deletions of replica
removals from removing a sstable that was ingested as a part of snapshot
reception with bounds exactly equal to the range's bounds.
> crl-release-24.1: fix deletion-only compaction bound comparison

- internal/manifest/version_edit.go
- open.go
- record/record.go
- record/record_test.go
- record/testdata/walSync
- version_set_test.go
- wal/testdata/reader
> crl-release-25.2: manifest,record: disambiguate unexpected EOFs

- internal/manifest/version_edit.go
- record/record.go
- record/record_test.go
- version_set_test.go
> crl-release-25.1: manifest,record: disambiguate unexpected EOFs

- internal/manifest/version_edit.go
- record/record.go
- record/record_test.go
- version_set_test.go
> crl-release-24.1: manifest,record: disambiguate unexpected EOFs

- internal/manifest/version_edit.go
- record/record.go
- record/record_test.go
- version_set_test.go
> crl-release-24.3: manifest,record: disambiguate unexpected EOFs

- internal/manifest/version_edit.go
- record/record.go
- record/record_test.go
- version_set_test.go
> crl-release-23.2: manifest,record: disambiguate unexpected EOFs

- compaction.go
- ingest.go
- table_stats.go
Check `PointDeletionsBytesEstimate` and `RangeDeletionsBytesEstimate`
for extreme values and log them (at most once every 30s). This is to
help identify the cause of very high level scores observed in a
cluster.
> db: log extreme values for deletion estimates

- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/testdata/writer_v5
- sstable/testdata/writer_v6
- testdata/compaction/set_with_del_sstable_Pebblev5
- testdata/compaction/set_with_del_sstable_Pebblev6
- testdata/compaction/value_separation
- testdata/large_keys
- testdata/metrics
When computing the estimated size of a sstable being built, incorporate size of the pending index blocks, value blocks, range deletion block and range key block. None of these quantities were incorporated into the RawRowWriter's estimated size.
The RawColumnWriter incorporated these, but did not incorporate the current pending data block or current pending index block.
Most of these quantities are uncompressed. We consider this pessimism to be acceptable, because these quantities are expected to be small most of the time. When they're not, they increase memory usage and splitting earlier than we otherwise would have helps bound memory usage.
Informs #4518.
> sstable: improve writer EstimatedSize

- data_test.go
- iterator_histories_test.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/testdata/writer_v5
- sstable/testdata/writer_v6
- testdata/large_keys
- testdata/manual_compaction_set_with_del_sstable_Pebblev5
- testdata/manual_compaction_set_with_del_sstable_Pebblev6
- testdata/metrics
- version_set_test.go
25.2 backport of #4583 and #4618.
> crl-release-25.2: sstable: improve writer EstimatedSize

- data_test.go
- internal/strparse/strparse.go
- iterator_histories_test.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/testdata/writer_v5
- testdata/large_keys
- testdata/manual_compaction_set_with_del_sstable_Pebblev5
- testdata/metrics
- version_set_test.go
25.1 backport of https://github.com/cockroachdb/pebble/pull/4583 and https://github.com/cockroachdb/pebble/pull/4618.
> crl-release-25.1: sstable: improve writer EstimatedSize

- .github/workflows/nightlies.yaml
Disable fail-fast which cancels the other matrix builds if one fails.
The canceled jobs make it more difficult to find the actual failure.
> github: disable fail-fast on nightlies

- compaction_test.go
This test can still be flaky in CI. Tweaking it to generate many
non-overlapping L0 files instead of many L0 sublevels; this way there
are no intra-L0 compactions that compete with the compactions we care
about.
I ran it under stress locally for a few hours (700k runs) with the 2
minute internal timeout reduced to 15s.
Fixes #4634
> db: deflake TestCompactionCorruption

- data_test.go
- internal/strparse/strparse.go
- iterator_histories_test.go
- sstable/colblk_writer.go
- sstable/rowblk_writer.go
- sstable/testdata/writer_v5
- testdata/large_keys
- testdata/manual_compaction_set_with_del_sstable_Pebblev5
- testdata/metrics
- version_set_test.go
24.3 backport of backport of https://github.com/cockroachdb/pebble/pull/4583 and https://github.com/cockroachdb/pebble/pull/4618.
> crl-release-24.3: sstable: improve writer EstimatedSize

- compaction_test.go
- testdata/compaction_corruption
We use a larger keyspace and tweak L0 compaction knobs and target file
size to encourage more compactions into Lbase.
We also increase the timeouts to a generous 2 minutes and widen the
key range of the missing external file.
I stress tested this locally with `-p 10` and 5 second timeouts and
hit no failures in 200,000 iterations.
Fixes #4544
This test can still be flaky in CI. Tweaking it to generate many
non-overlapping L0 files instead of many L0 sublevels; this way there
are no intra-L0 compactions that compete with the compactions we care
about.
I ran it under stress locally for a few hours (700k runs) with the 2
minute internal timeout reduced to 15s.
Fixes #4634
> crl-release-25.2: db: deflake TestCompactionCorruption

- testdata/compaction/value_separation
- value_separation.go
Fix the calculation of a compaction's output tables' blob reference depths to take into account that L0 input sstables in different sublevels overlap one another. This commit sums the maximum blob reference depth in each sublevel.
> db: fix L0 blob reference depth calculation

- compaction.go
- compaction_picker_test.go
- data_test.go
- db.go
- excise.go
- excise_test.go
- file_cache.go
- file_cache_test.go
- get_iter.go
- ingest.go
- ingest_test.go
- internal/keyspan/keyspanimpl/level_iter.go
- internal/keyspan/keyspanimpl/level_iter_test.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_test.go
- iterator.go
- level_iter.go
- lsm_view.go
- scan_internal.go
- table_stats.go
- testdata/ingest_load
- testdata/ingest_update_seqnums
This patch introduces (and uses) a new `InternalKeyBounds` struct to represent
both the smallest, largest range keys (if they exist) in our
`TableMetadata` struct. These keys are now stored as a single string --
spliced by a separator index for individual access.
This allows us to save 24 bytes for our `TableMetadata` struct.
---
This patch uses our `InternalKeyBounds` struct to represent
both the smallest, largest point keys in our `TableMetadata` struct.
These keys are now stored as a single string -- spliced by a separator index
for individual access.
This allows us to save 24 bytes for our `TableMetadata` struct.
---
Since range keys are rare, we make our range key bounds a pointer to
save on 32 bytes.
---
This field is also rare and only used for virtual sstables.
Fixes: …
> manifest: optimize sizeof TableMetadata

- metamorphic/options.go
The metamorphic test runs with the level checker validating every new readState. This level checking happens while holding the database mutex, preventing the test from making forward progress. Some configurations can create pathological LSMs with tens of thousands of sstables, which are slow to validate with the level checker.
This commit addresses this issue by tracking the test wall time and the cumulative wall time spent in the level checker. It avoids running the level checker if the cumulative time spent in the level checker exceeds 25% of the overall run's run time.
Additionally, regardless of the cumulative time budget, it skips the level checker half the time. This is intended to ensure that inserting artifical latency during read-state installation through level checking doesn't …
> metamorphic: bound time spent level checking

- external_iterator.go
- file_cache.go
- internal/problemspans/doc.go
- sstable/attributes.go
- sstable/copier.go
- sstable/reader.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_test.go
- sstable/suffix_rewriter.go
- sstable/testdata/reader_attributes
- table_stats.go
This commit introduces the bitset type `Attributes` to track which features are
in use in an sstable. The field is derived from the sstable properties on Reader
creation.
Initially, we include the following attributes:
- AttributeValueBlocks
- AttributeRangeKeySets
- AttributeRangeKeyUnsets
- AttributeRangeKeyDels
- AttributeRangeDels
- AttributeBlobValues
Closes: https://github.com/cockroachdb/pebble/issues/4557
> sstable: introduce `Attributes` bitset field for Reader

- db.go
- metrics.go
- options.go
- sstable/block/compression.go
- sstable/block/compression_test.go
- sstable/block/compressor.go
- sstable/format.go
- sstable/options.go
- sstable/test_utils.go
- sstable/testdata/writer_v5
- sstable/testdata/writer_v6
- sstable/writer_test.go
- table_stats.go
We fall back to Snappy for older formats.
Fixes #4633
> sstable: only support MinLZ for v6+ tables

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/colblk/bitmap.go
- sstable/colblk/data_block.go
- sstable/colblk/prefix_bytes.go
- sstable/colblk/raw_bytes.go
Add invariants-only bound checking, especially before accessing
`UnsafeOffset`s. We also change to using `At2()` instead of two `At()`
calls in a few places.
> colblk: add more bound checks

- open_test.go
Add a new randomized unit test adapted from TestWALFailoverRandomized that stresses recovery from a hard crash.
Fix #4651.
> db: add TestWALHardCrashRandomized

- db.go
- metrics.go
- options.go
- sstable/block/compression.go
- sstable/block/compression_test.go
- sstable/block/compressor.go
- sstable/format.go
- sstable/options.go
- sstable/test_utils.go
- sstable/testdata/writer_v5
- sstable/testdata/writer_v6
- sstable/writer_test.go
- table_stats.go
We fall back to Snappy for older formats.
Fixes #4633
> crl-release-25.2: sstable: only support MinLZ for v6+ tables

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/colblk/bitmap.go
- sstable/colblk/data_block.go
- sstable/colblk/prefix_bytes.go
- sstable/colblk/raw_bytes.go
Add invariants-only bound checking, especially before accessing
`UnsafeOffset`s. We also change to using `At2()` instead of two `At()`
calls in a few places.
> crl-release-25.2: colblk: add more bound checks

- compaction_test.go
- data_test.go
- excise.go
- excise_test.go
- internal/manifest/blob_metadata.go
- testdata/compaction/value_separation
During excise, we now preserve the top-level blob references
across virtual ssts created. The value size of each blob
reference is approximated by the proportion of the virtual table's
size to the original table's size.
Fixes: #4595
> db: preserve blob reference metadata across excise

- cmd/pebble/db.go
- cmd/pebble/replay_test.go
- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- db_test.go
- iterator_test.go
- metamorphic/options.go
- metamorphic/options_test.go
- options.go
- options_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
- testdata/compaction_picker_concurrency
- testdata/manual_compaction_set_with_del_sstable_Pebblev4
Backport of https://github.com/cockroachdb/pebble/pull/4635.
`MaxConcurrentCompactions()` returns an upper limit on the compaction
concurrency. Within this upper limit, Pebble decides what the
concurrency limit is (depending on L0 amplification and compaction debt).
There are cases where we want more concurrency for other reasons (like
space amp). Having a knob can be useful to tweak things in a
production environment.
This change changes `MaxConcurrentCompactions()` to
`CompactionConcurrencyRange()` which returns both a lower and upper
value. The lower limit is the "baseline" value for the concurrency,
which Pebble can increase dynamically up to the upper limit. Prior to
this change, the (implicit) lower limit was always 1.
> crl-release-24.1: db: change MaxConcurrentCompactions() to return a range

- cmd/pebble/db.go
- cmd/pebble/replay_test.go
- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- db_test.go
- error_test.go
- iterator_test.go
- metamorphic/options.go
- metamorphic/options_test.go
- options.go
- options_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
- testdata/compaction_picker_concurrency
- testdata/manual_compaction_set_with_del_sstable_Pebblev4
- testdata/manual_compaction_set_with_del_sstable_Pebblev5
- testdata/metrics
Backport of #4635.
`MaxConcurrentCompactions()` returns an upper limit on the compaction
concurrency. Within this upper limit, Pebble decides what the
concurrency limit is (depending on L0 amplification and compaction debt).
There are cases where we want more concurrency for other reasons (like
space amp). Having a knob can be useful to tweak things in a
production environment.
This change changes `MaxConcurrentCompactions()` to
`CompactionConcurrencyRange()` which returns both a lower and upper
value. The lower limit is the "baseline" value for the concurrency,
which Pebble can increase dynamically up to the upper limit. Prior to
this change, the (implicit) lower limit was always 1.
> crl-release-24.3: db: change MaxConcurrentCompactions() to return a range

- cmd/pebble/db.go
- cmd/pebble/replay_test.go
- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- db_test.go
- error_test.go
- iterator_test.go
- metamorphic/options.go
- metamorphic/options_test.go
- options.go
- options_test.go
- replay/testdata/replay
- replay/testdata/replay_paced
- testdata/compaction_picker_concurrency
- testdata/manual_compaction_set_with_del_sstable_Pebblev4
- testdata/manual_compaction_set_with_del_sstable_Pebblev5
- testdata/metrics
Backport of #4635.  Had a lot of merge conflicts, so the diff is worth a look.
`MaxConcurrentCompactions()` returns an upper limit on the compaction
concurrency. Within this upper limit, Pebble decides what the
concurrency limit is (depending on L0 amplification and compaction debt).
There are cases where we want more concurrency for other reasons (like
space amp). Having a knob can be useful to tweak things in a
production environment.
This change changes `MaxConcurrentCompactions()` to
`CompactionConcurrencyRange()` which returns both a lower and upper
value. The lower limit is the "baseline" value for the concurrency,
which Pebble can increase dynamically up to the upper limit. Prior to
this change, the (implicit) lower limit was always 1.
> crl-release-25.1: db: change MaxConcurrentCompactions() to return a range

- internal/manifest/l0_sublevels.go
- internal/manifest/version.go
- open_test.go
In a Pebble ycsb/C benchmark, 1.83% of CPU was spent in (*TableMetadata).Largest. These functions were just barely over the budget to be inlined. This commit refactors these functions to ensure they're inlined and adds gcassert assertions to ensure they remain inlined.
> manifest: ensure TableMetadata.{Smallest,Largest} inline

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/properties.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- table_stats.go
> crl-release-24.1: sstable: fix deletion properties for virtual tables

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/properties.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- table_stats.go
> crl-release-24.3: sstable: fix deletion properties for virtual tables

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/properties.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- table_stats.go
> crl-release-25.1: sstable: fix deletion properties for virtual tables

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/properties.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- table_stats.go
> crl-release-25.2: sstable: fix deletion properties for virtual tables

- compaction.go
- event.go
- internal/compact/iterator.go
- internal/compact/iterator_test.go
- internal/compact/testdata/iter_delete_sized
Introduces a new `APIMisuseKind` event type `MissizedDelete` and corresponding `MissizedDeleteCallback` method to address #4234.
> db: surface missized DELSIZED tombstones via PossibleAPIMisuse

- internal/invariants/off.go
- internal/invariants/on.go
- sstable/properties.go
- sstable/testdata/virtual_reader_props
- table_stats.go
> sstable: fix deletion properties for virtual tables

- metamorphic/options.go
The metamorphic test runs with the level checker validating every new readState. This level checking happens while holding the database mutex, preventing the test from making forward progress. Some configurations can create pathological LSMs with tens of thousands of sstables, which are slow to validate with the level checker.
This commit addresses this issue by tracking the test wall time and the cumulative wall time spent in the level checker. It avoids running the level checker if the cumulative time spent in the level checker exceeds 25% of the overall run's run time.
Additionally, regardless of the cumulative time budget, it skips the level checker half the time. This is intended to ensure that inserting artifical latency during read-state installation through level checking doesn't …
> crl-release-25.2: metamorphic: bound time spent level checking

- db.go
- db_test.go
We now include just the scaled `CommonProperties` for virtual tables.
Fixes: #4573
> db: scale props for virtual SSTs in DB.SSTables

- external_test.go
- file_cache.go
- internal/manifest/blob_metadata.go
- level_iter_test.go
- merging_iter_test.go
- tool/find.go
- tool/sstable.go
**db: add BenchmarkPointLookupSeparatedValues**
Add a microbenchmark that exercises a point lookup wihtin a database with
separated values.
Informs #112.
**manifest: avoid BlobReferences interface allocation**
The manifest.BlobReferences type is used to satisfy the sstable.BlobReferences
interface. Previously the interface was implemented on the slice receiver type.
This caused an allocation whenever we used this type to satisfy the
sstable.BlobReferences interface. This commit moves the implementation onto the
pointer type, avoiding the need to heap-allocate a copy of the slice header.
```
goos: darwin
goarch: arm64
│ before.txt  │              after.txt               │
│   sec/op    │   sec/op     vs base                 │ …
```
> manifest: avoid BlobReferences interface allocation

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- db.go
- file_cache_test.go
- ingest.go
- internal/manifest/blob_metadata.go
- internal/manifest/level_metadata.go
- internal/manifest/version.go
- metrics.go
- metrics_test.go
- obsolete_files.go
- table_stats.go
- value_separation.go
- value_separation_test.go
- version_set.go
- version_set_test.go
Add estimation of the physical size of a table's separated values and use this to compute an 'aggregate size' of a level. Use this size when determining level scores.
Informs #112.
> db: track aggregate size, inclusive of separated values

- ingest.go
- ingest_test.go
- internal.go
- internal/base/key_bounds.go
Move the KeyRange type into base, and re-export it in the pebble package. The ingest.go file is a bit unwieldy and I'd like to trim off the fluff.
> db: move KeyRange into base

- cockroachkvs/cockroachkvs_bench_test.go
- compaction_test.go
- format_major_version.go
- format_major_version_test.go
- open_test.go
- sstable/colblk_writer.go
- sstable/format.go
- sstable/format_test.go
- sstable/layout.go
- sstable/properties.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/table.go
- sstable/testdata/rewriter_v7
- sstable/testdata/writer_blob_value_handles
- sstable/testdata/writer_v7
- sstable/testdata/writer_value_blocks
- sstable/writer_test.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/cleaner
- testdata/compaction/set_with_del_sstable_Pebblev7
- testdata/compaction_delete_only_hints
- testdata/compaction_tombstones
- testdata/event_listener
- testdata/flushable_ingest
- testdata/ingest
- testdata/marked_for_compaction
- testdata/tracing
Add new sstable format version `TableFormatPebblev7` and internal format major
version to write attributes in sstable footer.
Persists sstable.Attributes to the footer for table formats greater than or
equal to `TableFormatPebblev7`. For now we continue to derive the attributes
from the properties when loading the sstable, and simply validate that the
attributes read from the footer are equivalent.
Closes: https://github.com/cockroachdb/pebble/issues/4652
> sstable: persist attributes in sstable footer

- excise.go
- testdata/value_separation_policy
- value_separation.go
This patch ensures that keys of the `DeleteSized` kind
do not get value-separated as such values are not worth
externalizing and sometimes used by compaction.
---
When scaling blob references' `ValueSize` during excise, we need to ensure 
that we round up to the nearest integer. Otherwise, a low `ValueSize` we want to
scale could easily be rounded to `0`.
> db: ensure deletesized keys don't get separated, fix zero size blob ref vals

- ingest.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- testdata/metrics
- testdata/table_stats
> crl-release-25.1: sstable: fix invariants panic due to zero virtual table size

- ingest.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- testdata/metrics
- testdata/table_stats
> crl-release-24.1: sstable: fix invariants panic due to zero virtual table size

- ingest.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/reader_virtual.go
> crl-release-25.2: sstable: fix invariants panic due to zero virtual table size

- ingest.go
- sstable/properties.go
- sstable/properties_test.go
- sstable/reader_virtual.go
- sstable/testdata/virtual_reader_props
- testdata/metrics
- testdata/table_stats
> crl-release-24.3: sstable: fix invariants panic due to zero virtual table size

- go.mod
- go.sum
- sstable/block/compression_test.go
- sstable/block/compressor.go
MinLZ has an 8MB block limit. We fall back to Snappy for the unlikely
case of larger blocks. The MinLZ compressor `Compress()` call can
return `SnappyCompressionIndicator`, which is unintuitive.
This commit hides this unfortunate detail inside the MinLZ
implementation. The decompression relies on the fact that the MinLZ
library can detect when it is used to decode a Snappy block. The
MinLZ compressor now always returns `MinLZCompressionIndicator`.
> block: push down MinLZ->Snappy fallback

- ingest.go
- internal/manifest/version.go
- testdata/compaction/value_separation
- testdata/excise
- testdata/ingest_external
- testdata/version_set
We allow external ingestions that have the same underlying remote
object, and we deduplicate the backings in this case. However, the
logic to set the backing size did not take deduplication into account.
We fix this by summing the `Size` of external files sharing a backing
within the same ingestion operation. When a backing is reused across
separate operations, we cap the virtual table size to the backing
size.
> db: fix size of deduplicated external backings

- internal/base/internal.go
- internal/manifest/bench_test.go
- internal/manifest/btree.go
- internal/manifest/level_metadata.go
- internal/manifest/level_metadata_test.go
Previously LevelIterator's seek methods accepted an opaque
func(*TableMetadata)bool to perform comparisons. This commit specializes each
instance as separate functions, ensuring comparisons can be inlined where
possible. Special attention is given to SeekGE, which is the hot path for point
lookups.
```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/pebble/internal/manifest
│   old.txt   │             newest2.txt             │
│   sec/op    │   sec/op     vs base                │
LevelIteratorSeekGE-10   144.3n ± 2%   110.0n ± 1%  -23.74% (p=0.000 n=10)
```
> internal/manifest: specialize LevelIterator seek methods

- ingest.go
- internal/manifest/version.go
- testdata/excise
- testdata/ingest_external
- testdata/version_set
We allow external ingestions that have the same underlying remote
object, and we deduplicate the backings in this case. However, the
logic to set the backing size did not take deduplication into account.
We fix this by summing the `Size` of external files sharing a backing
within the same ingestion operation. When a backing is reused across
separate operations, we cap the virtual table size to the backing
size.
> crl-release-25.2: db: fix size of deduplicated external backings

- docs/index.html
Add a annotation to the pebble nightly benchmarks indicating the date when value separation was enabled (only affecting the values=1024 variant currently). Also remove old annotations that are older than the 1-year of data we retain.
> docs: add value separation annotation

- cmd/pebble/write_bench.go
- cmd/pebble/ycsb.go
- compaction.go
- compaction_test.go
- db.go
- file_cache.go
- ingest.go
- metrics.go
- metrics_test.go
- replay/replay.go
- testdata/compaction/value_separation
Clarify the LevelMetrics fields related to byte quantities as bytes of
sstables by prefixing them with 'Table'.
Add totals about blob files to LevelMetrics and use them to correct the write
amplification calculation in the presence of value separation.
> db: expand blob file LevelMetrics

- table_stats.go
> db: bump maximum {Range,Point}DeletionsBytesEstimate

- go.mod
There is no benefit to requiring 1.24 right now, and it blocks Pebble
bumps until CRDB is switched over.
We should only bump it back up after CRDB was switched over and
everything is stable (and we want to use some go1.24 feature).
> go.mod: revert to 1.23

- internal/compression/compression.go
- internal/compression/compression_test.go
- internal/compression/minlz.go
- internal/compression/minlz_test.go
- internal/compression/noop.go
- internal/compression/snappy.go
- internal/compression/zstd_cgo.go
- internal/compression/zstd_nocgo.go
- sstable/block/compression.go
- sstable/block/compression_test.go
- sstable/block/compressor.go
- sstable/writer_fixture_test.go
Move the compression code to a separate package. This package will
expose compression levels (useful for running experiments), while the
`sstable/block` options will remain higher level.
> compression: move low level compression code to separate package

- internal/devtools/go.mod
> devtools: revert go.mod to 1.23

- cmd/pebble/ycsb.go
Correct the ycsb benchmarks bytes written metric to include blob file bytes.
> cmd/pebble: correct ycsb bytes-written metric

- sstable/blob/fetcher_test.go
Add a randomized test that exercises fetching a value stored in a blob file.
Informs #112.
> sstable/blob: add TestValueFetcherRetrieveRandomized

- table_stats.go
> crl-release-24.1: db: bump maximum {Range,Point}DeletionsBytesEstimate

- table_stats.go
> crl-release-24.3: db: bump maximum {Range,Point}DeletionsBytesEstimate

- table_stats.go
> crl-release-25.1: db: bump maximum {Range,Point}DeletionsBytesEstimate

- table_stats.go
> crl-release-25.2: db: bump maximum {Range,Point}DeletionsBytesEstimate

- db.go
- open.go
- tool/testdata/db_space
This patch ensures that blob files are also included in disk usage estimation.
Fixes: #4621
> db: incorporate blob files into EstimateDiskUsage

- compaction.go
- compaction_test.go
- data_test.go
- testdata/compaction_tombstones
This PR introduces a performance optimization for tombstone density compactions in Pebble. The optimization allows certain tombstone density compactions to be converted into a move operation, avoiding unnecessary file rewriting and improving compaction efficiency.
Fixes #4161 
---
- **`compaction.go`**:  
- Enhanced the compaction selection logic to allow tombstone density compactions (not just default compactions) to be optimized as a move when:
- The compaction is of kind `tombstone-density` (and not targeting the last level).
- There is a single input file with high tombstone density.
- The output level has no overlapping files.
- The grandparent overlap is below the configured threshold.
- This change enables more efficient handling of files with high tombstone density by moving them …
> compact: move tombstone density compactions

- options.go
- options_test.go
The current format requires per-level sections to look like
`[Level "1"]`. The quotes can be a pain to escape, especially when
this is passed through the `--store` command line.
This change makes the parsing more tolerant to allow but not require
quotes, so that `[Level 1]` also works.
> db: don't require quotes around level number in options section

- excise.go
- excise_test.go
- testdata/excise
We were still opening external backing tables when excising, in order
to determine the remaining size. This commit fixes this; we now set a
somewhat arbitrary size of half of that of the original table.
Fixes #4417
> db: don't open external backing table on excise

- compaction.go
- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/options_test.go
- sstable/blob/blob.go
Due to value separation, a compaction can be writing to
blob files and sstables in parallel. This means that a race
condition can occur in which updates to our per-compaction
`written` accumulator might be lost. This patch fixes this
behavior by using the `atomic.Int64` type to synchronize our
`written` accumulator.
---
This patch prohibits the creation of shared sstables with blob references and
prevents sstables with blob references from going through a
copy compaction.
If a compaction is configured to output to shared storage, it will run
with the `neverSeparateValues` `compact.ValueSeparation` implementation.
Fixes: https://github.com/cockroachdb/pebble/issues/4693
---
Previously, it was possible for a race condition to occur between
blob file writers because the logic to close a file …
> metamophic: integrate value separation

- compaction_test.go
- options_test.go
In unit tests that use Options.testingRandomized to vary the pebble.Options, randomize the configuration of value separation.
Informs #112.
> db: randomize value separation configuration in some unit tests

- options.go
- options_test.go
Backport of #4731.
The current format requires per-level sections to look like
`[Level "1"]`. The quotes can be a pain to escape, especially when
this is passed through the `--store` command line.
This change makes the parsing more tolerant to allow but not require
quotes, so that `[Level 1]` also works.
> crl-release-25.2: db: don't require quotes around level number in options section

- options.go
- options_test.go
Backport of #4731.
The current format requires per-level sections to look like
`[Level "1"]`. The quotes can be a pain to escape, especially when
this is passed through the `--store` command line.
This change makes the parsing more tolerant to allow but not require
quotes, so that `[Level 1]` also works.
> crl-release-25.1: db: don't require quotes around level number in options section

- options.go
- options_test.go
Backport of #4731.
The current format requires per-level sections to look like
`[Level "1"]`. The quotes can be a pain to escape, especially when
this is passed through the `--store` command line.
This change makes the parsing more tolerant to allow but not require
quotes, so that `[Level 1]` also works.
> crl-release-24.3: db: don't require quotes around level number in options section

- db_test.go
- objstorage/objstorageprovider/vfs_readable.go
Expecting specific table numbers is flaky; use a regexp.
Fixes #4744
> db: fix TestLargeBatch flake

- metrics.go
- sstable/blob/blob.go
- sstable/reader.go
Update  the magic number constant in StringForTests() to match the changes to `sstable.Reader` and `blob.FileReader` structs and add comments for future reference.
Fixes: #4677
> fix: update the magic number constant in StringForTests() for consistent testing

- .github/actions/post-issue/action.yaml
Change the "here-doc" `<<EOF` to `<<'EOF'` which prevents escapes and
expansion.
> github: fix bug in post-issue

- data_test.go
- iterator.go
- testdata/iter_histories/blob_references
The contract of an InternalIterator states that the caller must Clone the LazyValue if the caller will use the LazyValue beyond the next positioning operation.  Previously, it was possible for an iterator repositioned in the backwards direction to step onto a range key without clearing i.value. Although the stale i.value was never returned to the caller, an internal maybeSampleRead function could improperly read its Len().
Fix #4741.
> db: fix access of an invalid LazyValue

- db.go
- external_iterator.go
- iterator.go
- range_keys.go
Remove unused fields on the iteratorRangeKeyState struct and the init method that initializes them.
> db: remove iteratorRangeKeyState.init

- compaction_test.go
- data_test.go
- external_iterator.go
- file_cache.go
- file_cache_test.go
- ingest.go
- level_checker_test.go
- level_iter_test.go
- merging_iter_test.go
- metamorphic/build.go
- metamorphic/options_test.go
- objstorage/objstorageprovider/vfs_readable.go
- replay/replay.go
- sstable/blob/blob.go
- sstable/compressionanalyzer/file_analyzer.go
- sstable/copier_test.go
- sstable/data_test.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/test_utils.go
- table_stats_test.go
- tool/db.go
- tool/find.go
- tool/sstable.go
Previously, if an error was encountered while opening a blob file reader, the objstorage Readable created by the file cache was leaked and never closed.
Fix #4745.
> db: close blob file readable if unable to open blob reader

- file_cache.go
- internal/manifest/version.go
- replay/replay.go
- replay/replay_test.go
- replay/testdata/corpus/findWorkloadFiles
- replay/testdata/corpus/simple_val_sep
- replay/testdata/replay_val_sep
- replay/workload_capture.go
- replay/workload_capture_test.go
This patch ensures that `replay` is able to monitor & replay flushes with
value separation enabled.
Fixes: https://github.com/cockroachdb/pebble/issues/4459
> replay: support blob files 

- metamorphic/build.go
- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/test.go
- objstorage/remote/localfs.go
- open.go
- options.go
These commits fix various aspects around external and shared storage in the context of the crossversion test, where we start with an initial state.
Informs #4732
The metamorphic test uses in-mem remote storage, which doesn't work
when starting with an initial state (as in the crossversion tests).
Note that there is code to save the remote storage contents to disk
when the store is in-memory, but they are not read back when used as
initial state.
This commit changes to using FS-based remote storage in `shared`
and `external` subdirs inside the data dir. Note that the store itself
can still be in-memory; the data gets saved automatically with the
store.
We improve the FS-based Storage implementation to sync data and list
objects. We can now allow simulating crashes in the metamorphic test …
> metamorphic: remote storage fixes for crossversion

- metamorphic/meta.go
- metamorphic/options.go
- open.go
- open_test.go
- options.go
- options_test.go
- testdata/open_wal_failover
Relative WAL paths (including the actual WAL, the failover path, and
the recovery paths) are (unfortunately) interpreted as relative to the
current working directory.
The cross-version metamorphic test copies a store from a previous run
as the initial state for a new test. The options will fail the
compatibility check since the path changes.
This change adds support for using a special `{store_path}` prefix to
the path. Any such prefix is replaced with the store directory.
We also improve the missing WAL recovery dir error to show what
directories are actually configured.
Informs: #4732
> db: support store-relative paths for WAL dirs

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
This requires https://github.com/cockroachdb/pebble/pull/4760 and https://github.com/cockroachdb/pebble/pull/4755 (and those need to be backported).
Informs #4732
Error out if `--initial-state` is used without `--previous-ops`.
Lack of this flag is the root cause for the crossversion tests not
actually testing across versions (instead, each run was separate).
> metamorphic: sanity check initial-state and previous-ops flags, pass --previous-ops flag

- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/options_test.go
- metamorphic/test.go
- options.go
The test parsing code assumes that the presence of a flag means that
it is turned on. One of the standard options uses `=false` which is
actually interpreted as true.
This commit adds an assertion and fixes the problematic option.
We don't use the secondary cache at all, so remove it from the
standard settings and reduce the probability of it being turned on
when randomizing options.
We also remove support for `disable_value_separation` as we can just
set the Pebble setting directly.
When multiple stores are used, the shared and external directories
were set up inside the data dir of each store, which is not correct.
This commit fixes the paths.
> metamorphic: fix shared and external directories, fix testing of multiple instances

- compaction_test.go
We added a skip in race mode but that doesn't include other slow
builds (like address sanitizer builds). Switch to checking for
`buildtags.SlowBuild`.
> db: skip TestCompactionCorruption on slow builds

- Makefile
This matches the teamcity test.
> Makefile: start stress-crossversion with 24.1

- file_cache.go
- internal/metamorphic/reduce_test.go
Improve the panic message when we try to evict a file that is still in
use.
> db: improve file cache panic

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- metamorphic/build.go
- metamorphic/meta.go
- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/test.go
- objstorage/remote/localfs.go
- open.go
- open_test.go
- options.go
- options_test.go
- testdata/open_wal_failover
Backport of #4777
Informs #4732
The metamorphic test uses in-mem remote storage, which doesn't work
when starting with an initial state (as in the crossversion tests).
Note that there is code to save the remote storage contents to disk
when the store is in-memory, but they are not read back when used as
initial state.
This commit changes to using FS-based remote storage in `shared`
and `external` subdirs inside the data dir. Note that the store itself
can still be in-memory; the data gets saved automatically with the
store.
We improve the FS-based Storage implementation to sync data and list
objects. We can now allow simulating crashes in the metamorphic test
when shared storage is enabled.
If the metamorphic test has `CreateOnShared` set to something other
than "none" and we start with …
> crl-release-25.1: metamorphic: fix shared and external directories

- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
Previously retrieving a value from a LazyValue would save the retrieved value on the ValueFetcher. Subsequent value retrievals would use this cached value, avoiding some overhead of re-extracting the value. The memory lifetime of cached values was very subtle and error prone.
With blob-file backed values, certain interleavings of iterator operations could result in a pebble.Iterator returning a LazyValue that already had its value retrieved and cached, but the memory backing the cached value had already been invalidated. See #4765.
This caching subtly relied on the pebble.Iterator not retrieving values as a part of its iteration. This commit removes teh caching altogether.
Fix #4765.
> base: don't cache fetched LazyValue values

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- metamorphic/build.go
- metamorphic/meta.go
- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/test.go
- objstorage/remote/localfs.go
- open.go
- open_test.go
- options.go
- options_test.go
- testdata/open_wal_failover
Backport of #4777
Informs #4732
The metamorphic test uses in-mem remote storage, which doesn't work
when starting with an initial state (as in the crossversion tests).
Note that there is code to save the remote storage contents to disk
when the store is in-memory, but they are not read back when used as
initial state.
This commit changes to using FS-based remote storage in `shared`
and `external` subdirs inside the data dir. Note that the store itself
can still be in-memory; the data gets saved automatically with the
store.
We improve the FS-based Storage implementation to sync data and list
objects. We can now allow simulating crashes in the metamorphic test
when shared storage is enabled.
If the metamorphic test has `CreateOnShared` set to something other
than "none" and we start with …
> crl-release-24.3: metamorphic: fix shared and external directories

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- metamorphic/build.go
- metamorphic/meta.go
- metamorphic/ops.go
- metamorphic/options.go
- metamorphic/test.go
- objstorage/remote/localfs.go
- open.go
- open_test.go
- options.go
- options_test.go
- testdata/open_wal_failover
Backport of #4777
Informs #4732
The metamorphic test uses in-mem remote storage, which doesn't work
when starting with an initial state (as in the crossversion tests).
Note that there is code to save the remote storage contents to disk
when the store is in-memory, but they are not read back when used as
initial state.
This commit changes to using FS-based remote storage in `shared`
and `external` subdirs inside the data dir. Note that the store itself
can still be in-memory; the data gets saved automatically with the
store.
We improve the FS-based Storage implementation to sync data and list
objects. We can now allow simulating crashes in the metamorphic test
when shared storage is enabled.
If the metamorphic test has `CreateOnShared` set to something other
than "none" and we start with …
> crl-release-24.1: metamorphic: fix shared and external directories

- data_test.go
- db.go
- file_cache.go
- ingest.go
- sstable/reader.go
- table_stats.go
- testdata/compaction/value_separation
- testdata/event_listener
- testdata/ingest
- testdata/metrics
It seems that during close, the file cache may attempt to access structures
managed by the objstroage provider during the eviction process, such as sending
to channels used for tracing events. We should close the file cache before the
obj storage provider.
----------------------------------
Remove remaining reads of `Properites` on the reader struct. This commit also
removes the Properties field from the reader.
Closes: https://github.com/cockroachdb/pebble/issues/4383
----------
Previous: https://github.com/cockroachdb/pebble/pull/4773
> pebble: use ReadPropertiesBlock when accessing reader props

- table_stats.go
- table_stats_test.go
This commit cleans up some lingering branching on virtual sstables that was missed when we removed the concept of a virtual sstable reader in #4375. Additionally we take the opportunity to propagate a context throughout the table stats collection, remove an unused parameter and apply other small hygiene improvements.
> db: clean up table stats collection

- internal/manifest/annotator.go
- internal/manifest/annotator_test.go
- internal/manifest/btree.go
- internal/manifest/btree_test.go
- internal/manifest/l0_sublevels.go
- internal/manifest/level_metadata.go
- internal/manifest/testdata/version_edit_apply
- internal/manifest/version.go
- tool/testdata/manifest_dump
Convert the B-Tree used for organizing and reference counting TableMetadata
into a generic collection. This is in preparation for storing blob file
metadata in a B-Tree for copy-on-write reference counting. The iterator type is
left specialized to *TableMetadata because we will not need arbitrary iteration
over the blob file B-Tree.
We can consider eventually using an alternative B-Tree implementation, like the
one in the btreemap package, but we would need to introduce support for
copy-on-write reference counting. The existing table metadata B-Tree
implementation supports the reference counting semantics we need.
> internal/manifest: genericize btree

- ingest_test.go
- internal/manifest/table_metadata.go
- internal/manifest/table_metadata_test.go
- table_stats.go
Add these properties to table stats so we don't need to load the properties block when calculating table stats.
Closes: #4792
> sstable: add `RawKeySize` and `RawValueSize` to TableStats

- objstorage/objstorageprovider/objiotracing/obj_io_tracing.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_off.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_on.go
- objstorage/objstorageprovider/objiotracing/obj_io_tracing_test.go
- sstable/blob/blob.go
- sstable/blob/fetcher.go
- sstable/block/block.go
- sstable/block/blockkind/kind.go
- sstable/compressionanalyzer/block_analyzer.go
- sstable/compressionanalyzer/buckets.go
- sstable/compressionanalyzer/buckets_test.go
- sstable/compressionanalyzer/file_analyzer.go
- sstable/compressionanalyzer/testdata/buckets
- sstable/compressionanalyzer/testdata/file_analyzer
- sstable/layout.go
- sstable/reader.go
- sstable/valblk/reader.go
Introduce an enum of block kinds. This replaces two existing similar
enums - one in the compression analyzer and one in objiotracing.
This will allow integrating the compression analyzer in the read path,
and implementing a more complex `block.Compressor` which can take the
kind into account.
I used a separate package to avoid a circular dependency through objiotracing.
> block: introduce blockkinds

- Makefile
- metamorphic/parser.go
- metamorphic/testdata/parser
- open.go
Informs #4729
Remove a check that was too strict; even if the existing store version
is older, we will ratchet it up to `opts.FormatMajorVersion`, which
must support shared objects (checked by `opts.Validate()`).
This prevents a crossversion failure when parsing the NewIter op,
which switched from integers to strings in the filterMin/filterMax
arguments.
> crl-release-25.1: metamorphic: more crossversion fixes

- Makefile
- metamorphic/parser.go
- metamorphic/testdata/parser
- open.go
Remove a check that was too strict; even if the existing store version
is older, we will ratchet it up to `opts.FormatMajorVersion`, which
must support shared objects (checked by `opts.Validate()`).
> crl-release-25.2: metamorphic: show op name on parsing panics

- sstable/blob/blob.go
- sstable/block/compression.go
- sstable/block/compression_test.go
- sstable/block/compressor.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/rowblk_writer.go
- sstable/suffix_rewriter.go
- sstable/valblk/writer.go
- testdata/compaction/value_separation
- testdata/compaction_tombstones
- testdata/iter_histories/blob_references
CompressionProfile is intended as a replacement for Compression; it
allows using different compressors for data vs other blocks, and it
allows tuning of the minimum reduction percentage (previously
hardcoded to 12.5%).
> block: introduce CompressionProfile

- .github/actions/post-issue/action.yaml
The `jq` command was printing out `null` and we were treating that as
an existing issue number and trying to add a comment to it.
> github: fix post-issue

- internal/metamorphic/crossversion/crossversion_test.go
- metamorphic/meta.go
- scripts/run-crossversion-meta.sh
The diff output in a meta test failure is huge; once the histories
diverge, it's expected that a fraction of remaining operations will
differ.
This change shows only the first chunk of differences; it also
switches to showing diffs line-by-line instead of using unified diff
which groups differences into chunks.
Sample output:
```
===== DIFF =====
_meta/250604-110807.3903755035503/{standard-000,standard-025}
iter11.Prev("sziamgyg@5") // [valid,"vlqfkriwzhr",<no point>,["vlqfkriwzhr","yydpkltsctb")=>{"@11"="g","@9"="wbcwhbfszyji"}*] <nil> #802
db1.Set("yujhfwdgxzzk@9", "hgptsktbwcnkw") // <nil> #803
snap8.Get("cemsyb") // [""] pebble: not found #804
iter11.Last() // [true,"vlqfkriwzhr",<no point>,["vlqfkriwzhr","yydpkltsctb")=>{"@11"="g","@9"="wbcwhbfszyji"}] <nil> #805
db1.Set("bhxdce@12", …
```
> crl-release-25.1: metamorphic and crossversion debugging improvements

- checkpoint.go
- compaction.go
- data_test.go
- event.go
- internal/compact/run.go
- internal/manifest/blob_metadata.go
- internal/manifest/blob_metadata_test.go
- internal/manifest/btree.go
- internal/manifest/btree_test.go
- internal/manifest/level_metadata.go
- internal/manifest/table_metadata.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- testdata/compaction/value_separation
- testdata/iter_histories/blob_references
- value_separation.go
- value_separation_test.go
- version_set.go
- version_set_test.go
Rework the reference counting of in-use blob files to decouple the reference counts from the TableMetadatas' blob references. With the introduction of blob file rewrites and replacement, the physical blob file and the logical blob file's references have distinct lifetimes. A physical blob file that has been replaced will need to be removed once all Versions that predate the replacement have been unreferenced.
This commit renames the struct previously known as BlobFileMetadata to PhysicalBlobFile, describing metadata particular to a physical file backing a logical blob file. A new BlobFileMetadata struct is introduced that holds a BlobFileID and a pointer to the PhysicalBlobFile.
This commit additionally adapts the physical blob file referencing to occur through a separate B-Tree of …
> manifest: rework blob file reference counting

- internal/metamorphic/crossversion/crossversion_test.go
- metamorphic/meta.go
- scripts/run-crossversion-meta.sh
The diff output in a meta test failure is huge; once the histories
diverge, it's expected that a fraction of remaining operations will
differ.
This change shows only the first chunk of differences; it also
switches to showing diffs line-by-line instead of using unified diff
which groups differences into chunks.
Sample output:
```
===== DIFF =====
_meta/250604-110807.3903755035503/{standard-000,standard-025}
iter11.Prev("sziamgyg@5") // [valid,"vlqfkriwzhr",<no point>,["vlqfkriwzhr","yydpkltsctb")=>{"@11"="g","@9"="wbcwhbfszyji"}*] <nil> #802
db1.Set("yujhfwdgxzzk@9", "hgptsktbwcnkw") // <nil> #803
snap8.Get("cemsyb") // [""] pebble: not found #804
iter11.Last() // [true,"vlqfkriwzhr",<no point>,["vlqfkriwzhr","yydpkltsctb")=>{"@11"="g","@9"="wbcwhbfszyji"}] <nil> #805
db1.Set("bhxdce@12", …
```
> crl-release-25.2: scripts: run-crossversion-meta: use artifacts subdir

- db.go
- obsolete_files.go
- open.go
- version_set.go
Previously a race existed in the calculation of obsolete file metrics resulting in underflow. The values within versionSet.metrics were reset and recalculated to reflect the set of files in versionSet.obsolete{Tables,Blobs} whenever new files were added to obsoleteFiles. Additionally, the cleanup manager invoked a callback to decrease versionSet.metrics whenever a table was deleted.
The recalculation of versionSet.metrics could reset the metrics to less than the sum of outstanding pending deletes. When the cleanup manager eventually deleted the pending tables, these metrics would underflow.
This commit fixes the bug by maintaining separate stats for all files that have been enqueued for the cleanup manager and all files that have been successfully deleted. The volume of outstanding, …
> db: fix obsolete file metric underflows

- open.go
- options.go
- options_test.go
- testdata/open_wal_failover
If the existing store did not have a `WALDir` set and the new options
have one, the store path itself must be either a failover secondary or
a recovery dir. This was not covered by the compatibility check (it
would have saved a lot of time debugging a crossversion failure).
We also make sure we check the previous WAL dir even if the `wal_dir=`
entry doesn't appear (as was the case in tests).
> options: fix missing case in WAL recovery dir check

- internal/metamorphic/crossversion/crossversion_test.go
- metamorphic/meta.go
- scripts/run-crossversion-meta.sh
The diff output in a meta test failure is huge; once the histories
diverge, it's expected that a fraction of remaining operations will
differ.
This change shows only the first chunk of differences; it also
switches to showing diffs line-by-line instead of using unified diff
which groups differences into chunks.
Sample output:
```
===== DIFF =====
_meta/250604-110807.3903755035503/{standard-000,standard-025}
iter11.Prev("sziamgyg@5") // [valid,"vlqfkriwzhr",<no point>,["vlqfkriwzhr","yydpkltsctb")=>{"@11"="g","@9"="wbcwhbfszyji"}*] <nil> #802
db1.Set("yujhfwdgxzzk@9", "hgptsktbwcnkw") // <nil> #803
snap8.Get("cemsyb") // [""] pebble: not found #804
iter11.Last() // [true,"vlqfkriwzhr",<no point>,["vlqfkriwzhr","yydpkltsctb")=>{"@11"="g","@9"="wbcwhbfszyji"}] <nil> #805
db1.Set("bhxdce@12", …
```
> scripts: metamorphic and crossversion debugging improvements

- open.go
- options.go
- options_test.go
- testdata/open_wal_failover
If the existing store did not have a `WALDir` set and the new options
have one, the store path itself must be either a failover secondary or
a recovery dir. This was not covered by the compatibility check (it
would have saved a lot of time debugging a crossversion failure).
We also make sure we check the previous WAL dir even if the `wal_dir=`
entry doesn't appear (as was the case in tests).
> crl-release-25.1: options: fix missing case in WAL recovery dir check

- compaction.go
- format_major_version.go
We currently have a race when opening an older (pre-shared-storage)
store and having shared storage enabled in the object. We ratchet the
FMV to the appropriate one, but until that is done any
flushes/compactions can still create shared sstables. These sstables
will have an old format that is not supported with shared storage.
We modify the code paths that decide where to create objects to check
the FMV as well.
> crl-release-25.1: db: create shared objects only once the format is new enough

- compaction.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- download.go
- format_major_version.go
We currently have a race when opening an older (pre-shared-storage)
store and having shared storage enabled in the object. We ratchet the
FMV to the appropriate one, but until that is done any
flushes/compactions can still create shared sstables. These sstables
will have an old format that is not supported with shared storage.
We modify the code paths that decide where to create objects to check
the FMV as well.
> db: create shared objects only once the format is new enough

- db.go
- obsolete_files.go
- open.go
Previously a race existed in the calculation of obsolete file metrics resulting in underflow. The values within versionSet.metrics were reset and recalculated to reflect the set of files in versionSet.obsoleteTables whenever new files were added to obsoleteFiles. Additionally, the cleanup manager invoked a callback to decrease versionSet.metrics whenever a table was deleted.
The recalculation of versionSet.metrics could reset the metrics to less than the sum of outstanding pending deletes. When the cleanup manager eventually deleted the pending tables, these metrics would underflow.
This commit fixes the bug by maintaining separate stats for all files that have been enqueued for the cleanup manager and all files that have been successfully deleted. The volume of outstanding, pending …
> crl-release-25.2: db: fix obsolete file metric underflows

- db.go
- obsolete_files.go
- open.go
Previously a race existed in the calculation of obsolete file metrics resulting in underflow. The values within versionSet.metrics were reset and recalculated to reflect the set of files in versionSet.obsoleteTables whenever new files were added to obsoleteFiles. Additionally, the cleanup manager invoked a callback to decrease versionSet.metrics whenever a table was deleted.
The recalculation of versionSet.metrics could reset the metrics to less than the sum of outstanding pending deletes. When the cleanup manager eventually deleted the pending tables, these metrics would underflow.
This commit fixes the bug by maintaining separate stats for all files that have been enqueued for the cleanup manager and all files that have been successfully deleted. The volume of outstanding, pending …
> crl-release-25.1: db: fix obsolete file metric underflows

- db.go
- internal/invariants/off.go
- internal/invariants/on.go
- obsolete_files.go
- open.go
Previously a race existed in the calculation of obsolete file metrics resulting in underflow. The values within versionSet.metrics were reset and recalculated to reflect the set of files in versionSet.obsoleteTables whenever new files were added to obsoleteFiles. Additionally, the cleanup manager invoked a callback to decrease versionSet.metrics whenever a table was deleted.
The recalculation of versionSet.metrics could reset the metrics to less than the sum of outstanding pending deletes. When the cleanup manager eventually deleted the pending tables, these metrics would underflow.
This commit fixes the bug by maintaining separate stats for all files that have been enqueued for the cleanup manager and all files that have been successfully deleted. The volume of outstanding, pending …
> pebble-release-2.0: db: fix obsolete file metric underflows

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- internal/metamorphic/reduce_test.go
- metamorphic/history.go
- metamorphic/meta.go
Allow supplying an initial state when trying to reproduce a failure.
We were saving the entire root dir which is huge; switch to saving
just the relevant run(s) (along with any initial states). Note that
the `rootDir -> r.dir` change was already made on master in #4282.
> crl-release-25.1: crossversion: debugging improvements

- metamorphic/options.go
When we set up an initial state and the `WALDir` changed, we add the
previous directory as a WAL recovery dir. But the logic uses the
existence of a `wal` subdirectory; this is incorrect in the case where
the initial store used a `WALDir` in the past, but not in the most
recent iteration.
We fix this by finding the latest OPTIONS file and parsing it instead.
In addition, if the previous store did not use a WAL dir, we remove
any `wal` subdirectory that was left over. We make the analogous fixes
for the WAL secondary.
> crl-release-25.1: metamorphic: fix WAL recovery dirs logic

- metamorphic/options.go
When we set up an initial state and the `WALDir` changed, we add the
previous directory as a WAL recovery dir. But the logic uses the
existence of a `wal` subdirectory; this is incorrect in the case where
the initial store used a `WALDir` in the past, but not in the most
recent iteration.
We fix this by finding the latest OPTIONS file and parsing it instead.
In addition, if the previous store did not use a WAL dir, we remove
any `wal` subdirectory that was left over. We make the analogous fixes
for the WAL secondary.
> metamorphic: fix WAL recovery dirs logic

- compaction.go
- format_major_version.go
We currently have a race when opening an older (pre-shared-storage)
store and having shared storage enabled in the object. We ratchet the
FMV to the appropriate one, but until that is done any
flushes/compactions can still create shared sstables. These sstables
will have an old format that is not supported with shared storage.
We modify the code paths that decide where to create objects to check
the FMV as well.
> crl-release-24.3: db: create shared objects only once the format is new enough

- internal/metamorphic/meta_test.go
- internal/metamorphic/metaflags/meta_flags.go
- internal/metamorphic/reduce_test.go
- metamorphic/history.go
- metamorphic/meta.go
Allow supplying an initial state when trying to reproduce a failure.
> crl-release-25.2: crossversion: debugging improvements

- scripts/run-crossversion-meta.sh
We add the SHA to the binary name to avoid collisions and only extract
the version when it's an crl-release branch.
> crl-release-25.1: scripts: run-crossversion-meta fix aliasing of test binaries

- compaction.go
- file_cache.go
If we are racing with the db version being ratcheted, it is possible
that we plan to use shared storage when planning the compaction but
the old table format prevents us from doing so.
This check is too strict: we could have a file that was ingested
through a non-shared ingestion (and which has no obsolete points)
which was then copied to shared storage.
> crl-release-25.1: more fixes around shared objects and upgrade

- options.go
- sstable/block/compression.go
Add a profile that automatically selects between Snappy and MinLZ
depending on the platform. This will replace the similar code in CRDB
(which is causing CI failures because of different cluster setting
defaults for different platforms).
> block: add FastestCompression profile

- internal/manifest/l0_sublevels_test.go
- internal/manifest/table_metadata.go
- internal/manifest/version.go
Update both SortBySeqNum and SortBySmallest to use slices.SortFunc instead of the more verbose, less-efficient sort.Interface. Additionally, unexport SortBySeqNum and move it into a test-only file because it is now only used by a unit test.
> manifest: clean up SortBySeqNum, SortBySmallest

- compaction.go
Today, a compaction has an associated version (c.version) that is used sparingly in a few compaction edge cases. This version is never referenced and may become unreferenced and cleared while a compaction is running. This has generally been okay, because compaction picking must explicitly coordinate with running compactions so that sstables that are inputs to compactions aren't inputs to some other compactions.
With the introduction of blob files (#112) and blob file rewriting, a compaction may need to use the Version's BlobFileSet to lookup the mapping from a BlobFileID to a physical disk file number. To ensure the BlobFileSet is still valid to read, the Version needs to remain referenced.
This version ref-ing also allows us to remove some existing, subtle code that would reference an …
> db: maintain a Version reference during compactions

- internal/metamorphic/crossversion/crossversion_test.go
- internal/metamorphic/metaflags/meta_flags.go
- metamorphic/meta.go
- metamorphic/parser.go
Older versions had an extra bool arg; this mismatch is causing
failures in the (recently functional again) crossversion test.
Informs #4729
We are passing the ops from the previous run. We need to pass ops from
all the runs that culminated in the initial state; this is necessary
for issuing correct SingleDel operations.
We change `--previous-ops` to take a list of files, separated by a
comma.
> crl-release-25.1: crossversion: pass all previous ops

- sstable/colblk_writer.go
- sstable/copier.go
- sstable/rowblk_writer.go
- sstable/writer.go
I saw a `copyFilter` crash in a crossversion test - the
`WriterOptions` had no filter policy set. We fix the logic to verify
that the filter policy matches.
> crl-release-25.2: sstable: fix crash in copyFilter

- sstable/colblk_writer.go
- sstable/copier.go
- sstable/rowblk_writer.go
- sstable/writer.go
I saw a `copyFilter` crash in a crossversion test - the
`WriterOptions` had no filter policy set. We fix the logic to verify
that the filter policy matches.
> crl-release-24.3: sstable: fix crash in copyFilter

- metamorphic/key_manager.go
We partially "replay" previous ops. This populates the `objKeyMeta`
map for various objects from the previous run. These object IDs will
conflict with objects from a new run, so we have to clear them out. We
retain only the keys for the db itself, since that's all that carries
over from the previous run.
A symptom of this problem was
`metamorphic test internal error: external object empty`
This is because a batch that had just been created and was empty
already had an `objKeyMeta` that had bounds.
> crl-release-24.3: metamorphic: remove obj metadata created from previous ops

- internal/manifest/blob_metadata.go
- internal/manifest/table_metadata.go
- internal/manifest/testdata/version_edit_apply
- internal/manifest/version_edit.go
- testdata/version_set
- value_separation.go
- version_set_test.go
Previously a TableMetadata's BlobReferences maintained a pointer to the original PhysicalBlobFile that existed when the reference was created. This was confusing state and only existed for the purpose of calculating the estimated physical size of the referenced values.
This commit replaces the *PhysicalBlobFile pointer with a EstimatedPhysicalSize field that's calculated once upfront. Some of the version edit accumulation and application logic is also simplified, removing the need to track referenced *PhysicalBlobFiles.
Informs #112.
> manifest: remove BlobReference.OriginalMetadata

- file_cache.go
- metrics.go
- metrics_test.go
- testdata/compaction/value_separation
- testdata/event_listener
- testdata/ingest
- testdata/metrics
- tool/testdata/db_lsm
The file cache metrics now keep track of the table and blob file
counts separately. We fix the 32-bit memory size adjustment for tests
and make it easy (and mandatory) to keep up to date.
Fixes #4831
> db: improve file cache metrics, fix 32-bit platform adjustment

- internal/compression/compression.go
- internal/compression/minlz.go
- internal/compression/noop.go
- internal/compression/snappy.go
- internal/compression/zstd_cgo.go
- internal/compression/zstd_nocgo.go
- sstable/block/compression.go
- sstable/block/compressor.go
- sstable/block/compressor_test.go
- sstable/options.go
A possible "balanced" setting could be to use Zstd1 for value blocks
and MinLZ for everything else.
> block: support different setting for value blocks

- sstable/copier_test.go
- sstable/layout.go
- sstable/reader.go
- sstable/test_utils.go
- sstable/testdata/copy_span
Previously, (*sstable.Reader).Layout only included 1 filter block and only if it matched the reader's configuration. This commit updates the Layout method to collect the block handles of all filter blocks contained within the metaindex block.
> sstable: include all filter blocks in Reader.Layout

- sstable/values.go
- tool/find.go
- tool/sstable.go
- tool/testdata/find
- tool/testdata/sstable_scan
- tool/tool.go
- tool/util.go
This allows us to specify a relative path for our scan tool instead of enforcing some rule about the order of arguments to scan.
> tool: separate blob mode flags

- compaction.go
- event.go
- testdata/value_separation_policy
- value_separation.go
- value_separation_test.go
When separating a value, we call a user-provided 'ShortAttributeExtractor' to extract a few bits of data from the value. These bits, known as the 'short attribute', are stored in-place with the sstable key for fast retrieval.
Previously, if the user-provided ShortAttributeExtractor errored, the calling flush or compaction would abort and bubble the error up. If this was during a flush, the engine was unable to make progress, repeatedly attempting to flush a key that cannot be flushed.
This commit updates the logic to fallback to storing a value in-place if the short attribute extractor is unable to parse a value. The error is still surfaced through the PossibleAPIMisuse event.
> db: add fallback behavior if ShortAttributeExtractor errors

- external_test.go
- options.go
`Clone()` was allowing a shallow copy of `*WALFailover`. This caused a
lot of time debugging a test which unwittingly aliased the WAL
failover FS and dir of two stores.
This commit fixes this and adds a test that would have caught it.
We should probably make `WALFailover` a non-pointer (with an `Enabled`
field); even if we do, the new test is still valuable.
> db: fix Options.Clone()

- checkpoint.go
- checkpoint_test.go
- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- ingest.go
- ingest_test.go
- version_set.go
- version_set_test.go
Consolidate the various fields that hold mutable state describing the latest version. Consolidating helps highlight the distinction that this state is expected to be mutated, unlike an immutable manifest.Version.
Additonally, this prepares for passing additional mutable state into the compaction picker so that the compaction picker is capable of picking blob file rewrite compactions.
> db: move latest version state into a shared struct

- internal/metamorphic/crossversion/crossversion_test.go
The meta test itself already runs many configs in parallel. Running
one meta test per core is overkill and can lead to a lot more memory
usage (we have seen OOMs in CI).
I verified that a crossversion run still saturates all 10 cores on my
machine.
> crossversion: don't parallelize calls to the meta test

- objstorage/objstorageprovider/vfs_readable.go
- sstable/compressionanalyzer/file_analyzer.go
- sstable/compressionanalyzer/file_analyzer_test.go
- tool/db.go
- tool/db_analyze_data.go
- tool/db_analyze_data_test.go
- tool/tool.go
We use a "real" `objstorage.ReadHandle` and set it up for readahead.
We add support for analyzing ssts from cloud storage (backups). A tool
option is used to register a function that can take a URI and return a
`remote.Storage` implementation.
With remote storage, retrieving the size of each file one by one takes
too long when there are many files, so we don't do that upfront. Most
of the refactoring is to support tracking progress by file count only
in case of remote storage.
> tool: analyze-data: support remote storage

- options_test.go
Fix a 32-bit overflow introduced in 23da05e. Additionally, keep the value separation policy constant throughout the filetime of a Options configured with testingRandomized(). Previously every invocation of the ValueSeparationPolicy func would generate new random values.
Fix #4930.
Fix #4931.
> db: fix 32-bit overflow

- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db.go
- ingest.go
- internal/base/key_bounds.go
- internal/base/key_bounds_test.go
- internal/manifest/l0_sublevels.go
- internal/manifest/l0_sublevels_test.go
- internal/manifest/version.go
- internal/manifest/version_edit.go
- internal/manifest/version_test.go
- metrics.go
These commits attempt to organize and comment the compaction and pickedCompaction structs. This is motivated by blob-file rewrite 'compactions' which share little of the same state as compactions but need to be considered similarly in some instances (eg, concurrent compaction limiting).
> db: clean up compaction, pickedCompaction structs

- cmd/pebble/db.go
- cmd/pebble/replay_test.go
- compaction.go
- compaction_picker.go
- compaction_test.go
- data_test.go
- iterator_test.go
- metamorphic/options.go
- metrics_test.go
- options.go
- options_test.go
- range_del_test.go
- scan_internal_test.go
`LevelOptions.TargetFileSize` is used in a way that is not consistent
with the rest of the level options. Whereas other level options apply
to the expected level (e.g. `Levels[1]` applies to `L1`), the target
file size applies to the level relative to Lbase. Specifically for
i > 0, `Levels[i].TargetFileSize` is the target file size of Lbase+i-1.
We move this field to its own separate array and add a convenience
`TargetFileSize()` method.
We don't change the options encoding.
> db: move TargetFileSize out of LevelOptions

- external_test.go
- internal/manifest/manifest_test.go
- metamorphic/example_test.go
- metamorphic/meta.go
- metamorphic/options.go
- metamorphic/options_test.go
- open.go
- wal/failover_manager.go
- wal/standalone_manager.go
Add a test that performs two restarts in quick sequence and checks the
KVs are correct. Reproduces the bug in cockroachdb/cockroach#148419
We improve `RandomOptions` to allow a bit more control on what
features we enable.
We were incorrectly deleting all initial WALs after the first flush
completes. This is a problem when we have multiple flushes to perform,
which can happen if the WALs contain a batch that doesn't fit in the
memtable.
Informs cockroachdb/cockroach#148419
> db: fix incorrect cleanup of initial WALs

- data_test.go
- testdata/compaction/value_separation
- testdata/iter_histories/blob_references
Now that the Version.DebugString prints a Version's blob files, the datadriven test helpers don't need to explicitly print it too.
> db: remove redundant blob files in datadriven output

- blob_rewrite.go
- blob_rewrite_test.go
- internal/base/lazy_value.go
- internal/base/lazy_value_test.go
- internal/blobtest/handles.go
- internal/compact/iterator_test.go
- sstable/blob/blob.go
- sstable/blob/fetcher.go
- sstable/blob/fetcher_test.go
- sstable/layout.go
- sstable/reader.go
- sstable/runlength_bitmap.go
- sstable/runlength_bitmap_test.go
- sstable/valblk/reader.go
- testdata/blob_rewrite
This patch adds logic for rewriting a blob file, given referencing sstables, by `OR`ing together all referencing sstables' bitmaps to avoid writing never-referenced values.
> db: add logic for blob file rewriting

- cmd/pebble/db.go
- metamorphic/options.go
Disable blob file rewriting compactions for now in the standard options.
Close #4955.
> metamorphic: disable blob file rewriting for now

- internal/compression/zstd_nocgo.go
One of the commits in https://github.com/cockroachdb/pebble/pull/4937 accidentally reverted the change to return Setting from Compress.
> compression: fix zstd Compression to return Setting

- sstable/single_lvl_iter_benchmark_test.go
Here is the benchmark between eager load and lazy load behavior of the single level iterator. The tests just run against the iterator, in order to get the metrics, you will need to run before and after the commit #4916 
Ideally I expect to see the difference between construction time (or the index block load overhead, or 444 ns here) is similar to other differences. However, it seems they are higher. I believe the main reason is the Timer overhead introduced given the way the code is written+other noise. Given the difference is small (~200 ns at most), I'd argue it's good enough.
I'm only interested in the first-time access of these functions, which will trigger index block loading when the lazy load logic is applied. Therefore I cannot organize the test in form of
```
b.StartTimer()
for …
```
> test: introduce single level iterator lazy load benchmark test

- blob_rewrite.go
- blob_rewrite_test.go
- internal/blobtest/handles.go
- sstable/blob/blob.go
- sstable/blob/blob_test.go
- sstable/blob/blocks.go
- sstable/blob/fetcher.go
- sstable/blob/rewrite.go
Uncouple the logic around actually writing out a rewritten blob file from the
logic around identifying which values remain live. This will help us test both
parts in isolation.
> blob: uncouple blob file rewriting logic

- blob_rewrite.go
- blob_rewrite_test.go
- sstable/blob/fetcher.go
Fix bug in which during blob file rewriting, the pending BlockID was not
updated.
Previously the ValueFetcher did not correctly translate the ValueID of a
blob.Handle to the index of the value in the block if the blob file was
rewritten. This commit fixes the bug. Unit tests covering this case will be
added in future commits.
Add a randomized test of blob file rewrites.
TestBlobRewriteRandomized tests blob file rewriting by constructing a blob file
and n sstables that each reference one value in the blob file.
It then runs a blob rewrite repeatedly, passing in a random subset of the
sstables as extant references. Each blob rewrite may rewrite the original blob
file, or one of the previous iteration's rewritten blob files.
> db,blob: blob file rewrite bug fixes, randomized test

- blob_rewrite.go
- compaction_picker.go
Blob rewrite compactions reference the version they use for the duration of the compaction. Previously the reference was added during compaction picking. This allowed the reference to be leaked if the compaction was picked and cached but never got an opportunity to run before the DB was closed. This commit defers referencing the Version until the compaction is scheduled.
> crl-release-25.3: db: don't ref version until blob rewrite compaction is scheduled

- metamorphic/options.go
The metamorphic test runs with the level checker validating every new readState. This level checking happens while holding the database mutex, preventing the test from making forward progress. Some configurations can create pathological LSMs with tens of thousands of sstables, which are slow to validate with the level checker.
This commit addresses this issue by tracking the test wall time and the cumulative wall time spent in the level checker. It avoids running the level checker if the cumulative time spent in the level checker exceeds 25% of the overall run's run time.
Additionally, regardless of the cumulative time budget, it skips the level checker half the time. This is intended to ensure that inserting artifical latency during read-state installation through level checking doesn't …
> crl-release-24.3: metamorphic: bound time spent level checking

- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_test.go
- sstable/reader_iter_two_lvl.go
- sstable/reader_iter_two_lvl_benchmark_test.go
- testdata/checkpoint
- testdata/cleaner
- testdata/event_listener
- testdata/flushable_ingest
This commit implements the index block lazy loading in single-level iterator as default behavior. The index block loading is now deferred until first access. At the same time, it leads to semantic changes as the file reading ordering changes because of this.
Here is a quick overview of the change.
Before (eager loading)
1. Iterator Construction:
1.1 the constructor calls readTopLevelIndexBlock()
1.2 readTopLevelIndexBlock() calls readIndexBlock()
1.3 readIndexBlock(() calls blockReader.Read()
1.4 blockReader.Read() calls objstorage ReadHandle ReadAt()
1.5 ReadAt() loads the index block
1.6 construction completes
2. First Positioning (e.g., First(), SeekGE(), SeekPrefixGE()):
2.1 the positioning function uses the already-loaded index via PI(&i.index)
2.2 file opened for data read
2.3 …
> sstable: lazy load the index block in single- and two- level iterator

- metamorphic/options.go
The metamorphic test runs with the level checker validating every new
readState. This level checking happens while holding the database mutex,
preventing the test from making forward progress. Some configurations can
create pathological LSMs with tens of thousands of sstables, which are slow to
validate with the level checker.
This commit addresses this issue by tracking the test wall time and the
cumulative wall time spent in the level checker. It avoids running the level
checker if the cumulative time spent in the level checker exceeds 25% of the
overall run's run time.
Additionally, regardless of the cumulative time budget, it skips the level
checker half the time. This is intended to ensure that inserting artifical
latency during read-state installation through level checking doesn't …
> crl-release-24.2: metamorphic: bound time spent level checking 

- internal/metamorphic/meta_test.go
Use the leaktest in the metamorphic unit tests to catch any leaked goroutines.
Inform cockroachdb/cockroach#148649.
> metamorphic: use leaktest in metamorphic test

- Makefile
set crl-release-25.2 as previous version and update crossversion target
I accidentally pushed the change to upstream directly rather than origin :(
This is the commit to cockroachdb/pebble crl-release-25.3: https://github.com/cockroachdb/pebble/commit/35f8f8027691a32bbe753d8db15e76d33c5327d1
I create a separate commit in my own forked branch to cut this PR.
> Makefile: set crl-release-25.2 as previous version and update crossversion target

- sstable/properties.go
- table_stats.go
- testdata/table_stats
Table stats collection estimates compression ratios for the purpose of
calculating the size of data deleted by tombstones. Previously, this
compression ratio calculation included the size of both keys and values in the
pre-compression sum but only included sstables in the post-compression sum.
This resulted in wildly overestimating the effectiveness of compression when
values were separated into external blob files.
This commit incorporates a table's references estimated physical size into the
calculation.
Informs https://github.com/cockroachdb/cockroach/issues/149147.
> crl-release-25.3: db: incorporate separated values when estimating compression ratios

- internal/compression/adaptive_test.go
Deflake TestAdaptiveCompressorCompressible by increasing the minimum size of the payload that's compressed. If the payload is too small, compression cannot result in a significant enough reduction in the size of the compressed payload and the compressor yields the uncompressed payload instead.
Fix #5012.
> compression: deflake TestAdaptiveCompressorCompressible

- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- testdata/compaction/multilevel
- testdata/compaction/value_separation
- testdata/compaction_delete_only_hints
Previously, we decide to run a multilevel compaction if the write amp with the additional level is less than that of the original compaction. We now add these additional constraints:
- The max compaction concurrency for the db must be greater than 1. This is to prevent the ML compaction from being the only compaction running, which could spike L0.
- At most one multiLevel compaction may be running at any time.
Part of: #4139
> pebble: add additional constraints to running multiLevel compactions

- compaction.go
- data_test.go
- internal/compact/run.go
- options.go
- options_test.go
- testdata/compaction/value_separation
- testdata/static_span_policy_func
- value_separation.go
- value_separation_test.go
Allow the user to configure that a keys within a particular key-range are tolerant of high latency of value retrieval, indicating that their values should be more aggressively separated when value separation is enabled.
We intend to use this in CockroachDB to separate the values of KVs within the raft log. Typically raft log entries are never read because the relevant KVs are cached in-memory until the log is truncated.
Close #5017.
> db: support overriding value separation minimum-size by key span

- blob_rewrite.go
If a blob rewrite compaction fails for any reason (eg, the blob becomes unreferenced while the compaction is in-progress), we enqueue the blob file we created as an 'obsolete' blob file. This enqueue did not insert the blob file in sorted order.
Fix #5022.
Fix #5026.
> db: merge in obsolete blob file during failed blob rewrite compaction

- blob_rewrite.go
If a blob rewrite compaction fails for any reason (eg, the blob becomes unreferenced while the compaction is in-progress), we enqueue the blob file we created as an 'obsolete' blob file. This enqueue did not insert the blob file in sorted order.
Fix #5022.
> crl-release-25.3: db: merge in obsolete blob file during failed blob rewrite compaction

- internal/keyspan/interleaving_iter.go
Previously if the internal point iterator encountered an error during NextPrefix and the iterator was currently positioned within a span, the InterleavingIter improperly swallowed the error without surfacing an exhausted iterator position (indicating that the caller should call Error()).
Fix #5032.
Informs #2785.
> internal/keyspan: fix swallowed error in InterleavingIter.NextPrefix

- db.go
- internal/base/directory_lock.go
- open.go
- open_test.go
- options.go
- testdata/cleaner
- testdata/event_listener
- wal/failover_manager.go
- wal/standalone_manager.go
- wal/wal.go
Ensure that we acquire locks for WAL directories when they are configured.
Fixes: #4919
> pebble: lock wal directories on Open

- open.go
- open_test.go
Do not attempt to reacquire lock on the  wal recovery dir when it is the same as the dir being opened.
Fixes: #5051
> pebble: fix wal recovery dir lock acquisition in Open

- file_cache.go
- ingest.go
- sstable/reader.go
- sstable/reader_test.go
- sstable/testdata/virtual_reader_props
- table_stats.go
- tool/sstable.go
Previously, we did not set up any iterator transforms during EstimateDiskUsage -- leading to an inaccurate disk usage estimation that was eventually used in compaction heuristics. This patch fixes this bug by grabbing the IterTransforms from the table we are reading and using it during disk usage estimation.
Fixes: #4597
> sstable: set up proper iterator transforms during EstimateDiskUsage

- options.go
This function and type are used by the users of Pebble, so they need to be exported from a non-internal package.
> db: re-export base.LockDirectory, base.DirLock

- internal/base/directory_lock.go
- open.go
- testdata/cleaner
- testdata/event_listener
Previously if an error occurred during Open after the WAL manager had been initialized, it was possible for a directory lock to be Closed multiple times. This commit refactors the error handling to ensure we release the WALDir and WALFailover.Secondary locks at most once.
> db: fix double Close of directory lock during failed Open

- compaction.go
- format_major_version.go
- format_major_version_test.go
- ingest.go
- internal/manifest/testdata/version_edit_apply
- internal/manifest/testdata/version_edit_decode
- internal/manifest/version_edit.go
- internal/strparse/strparse.go
- open_test.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/event_listener
- testdata/flushable_ingest
- tool/testdata/db_upgrade
This adds a new struct field that maps excise span to the sequence number at which it was performed, this will allow to strengthen invariant checking on manifest replay as it was not updated with excise operations, this field is also implemented in version_edit_apply and version_edit_decode tests.
Addresses #4798
> manifest: explicitly encode excise operations in the MANIFEST

- internal/manual/manual_cgo.go
- internal/manual/manual_nocgo.go
In invariants builds, sometimes mangle manually-managed buffers just before freeing them. This can help surface code paths that are inadvertently using the memory after it's been freed.
> manual: sometimes mangle freed buffers in invariants builds

- compaction.go
- ingest.go
Only populate the ve.ExciseBoundsRecord if the version is eligible
> db: check FormatExciseBoundsRecord against the current format version

- sstable/blob/blocks.go
- sstable/blob/fetcher.go
- sstable/block/block.go
- sstable/block/buffer_pool.go
- sstable/colblk/data_block.go
When allocating memory for a new block, we allocate an additional block.MetadataSize bytes for holding a Go structure containing decoded data describing the block and maintaining pointers into the block's contents. This allows us to decode the block structure once when the block is loaded into the block cache. Readers that find the block in the cache simply cast this 'block metadata' preamble into the appropriate type.
When a block is not found within the block cache, we: load the block, decode the block's header and initialize the block's unique metadata. We initialize the metadata by first casting the allocation's pointer to the appropriate Go pointer type. Then we decode the block's data, initializing the metadata struct accordingly. In the interim between the pointer cast and the …
> sstable: prevent block metadata pointers to garbage

- sstable/blob/blocks.go
- sstable/blob/fetcher.go
- sstable/block/block.go
- sstable/block/buffer_pool.go
- sstable/colblk/data_block.go
When allocating memory for a new block, we allocate an additional block.MetadataSize bytes for holding a Go structure containing decoded data describing the block and maintaining pointers into the block's contents. This allows us to decode the block structure once when the block is loaded into the block cache. Readers that find the block in the cache simply cast this 'block metadata' preamble into the appropriate type.
When a block is not found within the block cache, we: load the block, decode the block's header and initialize the block's unique metadata. We initialize the metadata by first casting the allocation's pointer to the appropriate Go pointer type. Then we decode the block's data, initializing the metadata struct accordingly. In the interim between the pointer cast and the …
> crl-release-25.3: sstable: prevent block metadata pointers to garbage

- go.mod
- go.sum
- sstable/properties.go
- sstable/properties_test.go
This method belongs on the `CommonProperties` type.
> sstable: avoid overflow in GetScaledProperties

- sstable/colblk_writer.go
- sstable/layout.go
- sstable/rowblk_writer.go
- sstable/valblk/writer.go
- sstable/writer_test.go
The compressor and checksummer are used together but in many code
paths we use a checksummer in a blockBuf. Remove this and always use a
checksummer initialized alongside the compressor.
> sstable: remove checksummer from blockBuf

- compaction.go
- ingest.go
- internal/datatest/datatest.go
- metrics.go
- replay/replay.go
- replay/replay_test.go
- replay/testdata/corpus/simple_ingest
- replay/testdata/replay_ingest
this commit adds ingestion and ingest-and-excise tests on replay package for improving benchmarks and accounts for excise operations during ingestion as well.
see #5048
> replay: adding ingest and ingest-and-exicse testing

- internal/compression/compression.go
- internal/compression/compression_test.go
- sstable/block/compression_stats.go
- sstable/block/compression_stats_test.go
- sstable/block/compressor.go
- sstable/testdata/writer_value_blocks
Generalize `CompressionStats` so that it can be used with an arbitrary
number of settings.
This will be necessary to read the compression stats from existing
tables (after Open).
> block: generalize CompressionStats, add ParseCompressionStats

- sstable/blob/blob.go
- sstable/block/physical.go
- sstable/colblk_writer.go
- sstable/layout.go
- sstable/rowblk_writer.go
- sstable/valblk/writer.go
- sstable/write_queue.go
This change moves the responsibility of releasing the `PhysicalBlock`s
to the code that writes out the block. This makes the higher level
code simpler and more robust.
To avoid misuse, we add an `OwnedPhysicalBlock` type which is used to
indicate that once passed, the function takes responsibility for
releasing the block. The only way to create an `OwnedPhysicalBlock`
clears the `PhysicalBlock` so it can't be incorrectly used again.
> sstable: free physical buffers on write

- data_test.go
- table_stats.go
- testdata/compaction/set_with_del_sstable_Pebblev5
- testdata/compaction/set_with_del_sstable_Pebblev6
- testdata/compaction/set_with_del_sstable_Pebblev7
- testdata/compaction_picker_scores
- testdata/compaction_tombstones
- testdata/table_stats
A copy/pasta. I found this while working on a separate change that
makes the API around table stats much less fragile.
> db: fix bug in scaling compression stats for virtual tables

- .github/workflows/nightlies.yaml
- Makefile
- go.mod
- internal/devtools/go.mod
Cockroach now uses 1.24.5; change go.mod to use the same version and
stop testing nightlies on 1.23.
> go.mod: require go1.24

- internal/arenaskl/skl_test.go
- internal/batchskl/skl_test.go
- internal/testutils/reflect.go
Add a test asserting that the node structs used in both skiplist implementations do not contain any pointer types. We reuse memory backing both of these types without zeroing it. If we introduce a pointer type, we could expose ourselves to an issue similar to the one fixed in #5085: garbage memory could be misinterpreted as a pointer value before the pointer value has been appropriately initialized.
> arenaskl,batchskl: add test ensuring node contains no pointer types

- sstable/block/blockkind/kind.go
- sstable/block/compressor_test.go
- sstable/reader.go
It is used in the same way as the SSTableIndex Kind, and its entry in the kindString was never populated.
> blockkind: remove the Index Kind

- db_test.go
- internal/base/stopwatch.go
- internal/cache/cache.go
- internal/cache/read_shard_test.go
- metrics_test.go
- sstable/block/block.go
- sstable/block/category_stats.go
- testdata/metrics
- testdata/tracing
cache.Handle.GetWithReadHandle returns a non-zero wait duration on
a cache miss, which resulted in the request waiting for a turn
to do the read, or to wait for the block to be read by another
reader.
Tracing now happens on high wait duration. Wait duration is included
in iterator stats, since this is a block miss. And wait duration is
included in the read duration when the block was read by the caller
after waiting.
> block,cache: trace and stats for wait duration (for concurrent reads)

- db.go
- excise_test.go
- ingest_test.go
- metamorphic/ops.go
- options.go
- scan_internal.go
- scan_internal_test.go
- snapshot.go
Update ScanInternal methods to take options via the (now exported) ScanInternalOptions struct. Previously the function signature was a bit unwieldy.
> db: take ScanInternal options through an options struct

- compaction_test.go
This test is still flaky (though failures seem much more rare). Use an
in-memory logger and dump all the logs when the test fails; hopefully
this gives us more information about what is happening when it fails.
> db: add more logs to TestCompactionCorruption

- compaction.go
- compaction_test.go
- internal/compact/iterator.go
- internal/compact/iterator_test.go
- internal/compact/testdata/iter
- internal/compact/testdata/iter_delete_sized
- internal/compact/testdata/iter_set_with_del
- testdata/excise
This commit refactors the compaction iterator to perform an additional transformation to MERGE keys that are known to be the oldest version of their key in the LSM, transforming their key kind to SET. This ensures that iterators or compactions stepping over the key avoid invoking the merge operator when unnecessary.
Fix #5178.
> compact: convert MERGE keys to SET when bottommost

- compaction.go
- compaction_test.go
- internal/compact/iterator.go
- internal/compact/iterator_test.go
- internal/compact/testdata/iter
- internal/compact/testdata/iter_delete_sized
- internal/compact/testdata/iter_set_with_del
- testdata/excise
This commit refactors the compaction iterator to perform an additional transformation to MERGE keys that are known to be the oldest version of their key in the LSM, transforming their key kind to SET. This ensures that iterators or compactions stepping over the key avoids invoking the merge operator when unnecessary.
Fix #5178.
> crl-release-25.3: compact: convert MERGE keys to SET when bottommost

- compaction.go
- compaction_test.go
- internal/compact/iterator.go
- internal/compact/iterator_test.go
- internal/compact/testdata/iter
- internal/compact/testdata/iter_delete_sized
- internal/compact/testdata/iter_set_with_del
- testdata/excise
This commit refactors the compaction iterator to perform an additional transformation to MERGE keys that are known to be the oldest version of their key in the LSM, transforming their key kind to SET. This ensures that iterators or compactions stepping over the key avoid invoking the merge operator when unnecessary.
Fix #5178.
> crl-release-24.3: compact: convert MERGE keys to SET when bottommost

- internal/strparse/strparse.go
- internal/strparse/strparse_test.go
Add an Offset method to the strparse Parser to allow the retrieval of the next token's byte offset within the original input string.
Additionally, add a ExpectAll func allowing a caller to expect a variable-length token of a set of characters indicated by a predicate.
> strparse: add (*Parser).Offset

- compaction.go
- data_test.go
- internal/base/internal.go
- options.go
- options_test.go
- sstable/blob/blocks.go
- sstable/blob/fetcher.go
- sstable/colblk/data_block.go
- tiering.go
The policy is specified as a TieringPolicy struct and in combination with
an extractor func, to extract the tiering attribute, for use in
compactions and flushes. It is exposed via a TieringPolicyAndExtractor
interface embedded in the SpanPolicy.
SpanPolicy now contains a KeyRange, which was conceptually already in
existence, but was only partly exposed (via the end key). Exposing both
bounds allows Pebble to check that the invariant related to an immutable
spanID are not violated.
> [tiered prototype] db: add tiering policy

- file_cache.go
- file_cache_test.go
- internal/genericcache/cache.go
- internal/genericcache/cache_test.go
- internal/genericcache/shard.go
- sstable/blob/fetcher.go
- sstable/blob/fetcher_test.go
- sstable/block/block.go
- sstable/copier.go
- sstable/options.go
- sstable/reader.go
- sstable/reader_iter_single_lvl.go
- sstable/reader_iter_two_lvl.go
- sstable/valblk/reader.go
- testdata/event_listener
- testdata/iter_histories/blob_references
- testdata/iter_histories/iter_optimizations
- testdata/iter_histories/range_key_masking
- testdata/iter_histories/stats_no_invariants
- testdata/iterator_stats
- testdata/metrics
- tool/tool.go
initFileOpts only contains InitFileReadStats, which allows the caller to provide stats collected by iterators. Reads done when creating a Reader specifically because an iterator was needed on that file, will now be captured in the corresponding iterator stats.
This reduces the uncertainty when we see slowness in traces around iteration, and are unsure whether it happened prior to operations on the iterator. We continue to have some unaccounted latency:
- Footer reads are not included in the stats.
- File cache entry initialization is shared when there are concurrent attempts to create the entry, and the latency (via iterator stats) is only accounted in the one that did the Reader creation.
initFileOpts are also plumbed to valblk.blockProviderWhenClosed, when
it needs to open a …
> db: add initFileOpts for initializing in the FileCache

- testdata/iter_histories/stats_no_invariants
This test broke in https://github.com/cockroachdb/pebble/pull/5164, even though CI was green.
> db: fix incorrect testdata for TestIterHistories

- file_cache.go
- sstable/reader_iter_single_lvl.go
- sstable/valblk/reader.go
The ReadValueBlock method was unnecessarily accepting a stats parameter, since the common case is the implementation provided by singleLevelIterator.
Additionally, we now plumb a context to blockProviderWhenClosed, though the plumbing there is still incomplete, as noted in a todo.
> valblk: simplify valblk.IteratorBlockReader interface

- compaction.go
- compaction_picker.go
- data_test.go
- ingest.go
- internal/manifest/table_metadata.go
- internal/manifest/table_metadata_test.go
- table_stats.go
- testdata/table_stats
This will allow us to derive more concise backing properties (for
example the tombstone-dense ratio).
We no longer rely on scaling the entire `CommonProperties`; this was
really only used for the point deletion bytes estimate, which we now
scale after calculating.
> manifest: store the tombstone-dense block ratio in TableBackingStats

- internal/compact/iterator.go
- internal/compact/testdata/iter_delete_sized
Fix one of the instances where we report a missized DELSIZED tombstone but did not include the expected tombstone size. If a DELSIZED tombstone with a non-zero value meets another tombstone during a compaction, it indicates the more recent DELSIZED was missized--it deleted a key that did not exist (and was already deleted). Previously when invoking a callback to report this missizing, the compaction iterator passed expectedSize=0. This was misleading because the DELSIZED explicitly carried a non-zero size which allowed to us to determine there was a missizing in the first place.
This commit adapts the compaction iterator to decode the DELSIZED's value in this case and propagate it into the missized delete callback.
> compact: include expected size in MissizedDeleteCallback

- sstable/tieredmeta/block.go
- sstable/tieredmeta/histogram.go
The block will map TieringSpanID to a histogram. The support is
incomplete, with some todos for future PRs.
> [tiered prototype] tieredmeta: add some code for a tiering histogram block

- blob_rewrite_test.go
TestBlobRewriteRandomized logs a lot of context on its random state and operations and it's overwhelming when running tests with -v. This commit updates the test to write this context into an in-memory buffer, logging the contents only if the test fails.
> db: reduce TestBlobRewriteRandomized log spam

- internal/manifest/annotator.go
- internal/manifest/blob_metadata.go
- internal/manifest/btree.go
- internal/manifest/btree_test.go
- internal/manifest/level_metadata.go
We currently allocate either a `leafNode` or a `node` and cast between
them. This is potentially unsafe, since at times we are holding a
`*node`, part of which is outside a `leafNode` object.
We remove this hack by moving the children list to a separate object
and having a pointer to it inside `node`. We also move the
`subtreeCount` to save space, since it is not useful in the leaves
(this offsets the size of the extra pointer for leaves, which are the
vast majority).
The separate object is still allocated together with the inner node,
so this does not increase the number of allocations.
Fixes #5200
> manifest: remove btree memory abuse

- internal/compact/run.go
- sstable/colblk_writer.go
- sstable/testdata/writer_value_blocks
- testdata/compaction/mvcc_garbage_blob
- value_separation.go
This patch allows the `SetWithDelete` key kind to be eligible for MVCC garbage consideration. This effectively allows `SetWithDelete` keys to be separated into value blocks and blob files.
Fixes: #4424
> sstable: allow SetWithDelete keys to be considered as MVCC garbage

- db.go
This panic causes an "unlock of unlocked mutex" panic on unwinding, which obscures the original panic. Change to a `Fatalf`.
Fixes #5225
> [pebble-release-2.0] manifest: change panic to Fatalf

- internal/base/comparer.go
- internal/base/comparer_test.go
Previously this was not set, although its documentation says it is. Add tests for both branches of EnsureDefaults where it is set.
> internal/base: set ComparePointSuffixes in EnsureDefaults

- filenames_test.go
- internal/base/filenames.go
Reduce allocations while constructing a filename from a disk file number. MakeFilename alocations made up ~1.5% of all allocations during a pebble ycsb/A run of the nightly benchmarks.
```
goos: darwin
goarch: arm64
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
MakeFilename-10   167.10n ± 1%   67.38n ± 0%  -59.68% (p=0.000 n=25)
│   old.txt   │              new.txt               │
│    B/op     │    B/op     vs base                │
MakeFilename-10   40.000 ± 0%   8.000 ± 0%  -80.00% (p=0.000 n=25)
│  old.txt   │              new.txt               │
│ allocs/op  │ allocs/op   vs base                │
MakeFilename-10   4.000 ± 0%   1.000 ± 0%  -75.00% (p=0.000 n=25)
```
> base: reduce MakeFilename allocations

- db.go
- iterator.go
- scan_internal.go
Under invariants builds, assert that the iterAlloc struct has been zeroed out. We allow some fields that deliberately recycle fields to be exempted. Additionally we allow pointers to zeroed structs and slices with len()=0 and underlying capacity that is all zeroed.
> db: assert that iterAlloc has been zeroed under invariants

- compaction.go
- db.go
- ingest.go
- internal/manifest/table_metadata.go
- internal/manifest/table_metadata_test.go
- metrics.go
- sstable/blob/blob.go
- sstable/colblk_writer.go
- sstable/reader.go
- sstable/tieredmeta/block.go
- sstable/writer.go
- table_stats.go
- testdata/compaction/l0_to_lbase_compaction
- testdata/compaction/value_separation
- testdata/ingest
- testdata/metrics
As a temporary step, we read the histograms into TableStats and then use an AnnotationAggregator to aggregate them per level, so they can seen in metrics.
We will use the per sstable TableStats to make tiering decisions for compactions in future PRs.
> [tiered prototype] db: read and aggregate tiering histograms

- blob_rewrite_test.go
- compaction_picker.go
- compaction_test.go
- excise.go
- format_major_version.go
- format_major_version_test.go
- internal/manifest/blob_metadata.go
- internal/manifest/table_metadata.go
- internal/manifest/testdata/current_blob_file_set
- internal/manifest/testdata/version_edit_decode
- internal/manifest/version_edit.go
- internal/manifest/version_edit_test.go
- open_test.go
- testdata/checkpoint
- testdata/checkpoint_shared
- testdata/compaction/backing_value_size
- testdata/event_listener
- testdata/flushable_ingest
- tool/testdata/db_upgrade
- value_separation.go
- value_separation_test.go
This field will be added for virtual tables with blob refs.
--------------------------------------------------------------
Track BackingValueSize for blob references, which is the uncompressed value
size in blob files referenced by the backing sstable. For non-virtual sstables,
this equals the existing ValueSize field. The BackingValueSize should only be
popualted for FMV >= FormatBackingValueSize, falling back to reading ValueSize
when the BackingValueSize is 0.
Use BackingValueSize in the estimation of referencedValueSize for the
CurrentBlobFileSet. This prevents wasteful blob file rewrite compactions when
virtual sstables are involved, as blob compactions currentlyr rewrite based
on value references tracked by the original table.
Part of: #4915
> manifest: add BackingValueSize field for blob refs

- internal/base/internal.go
- internal/manifest/level_metadata.go
- internal/manifest/table_metadata.go
- internal/manifest/version.go
1. moved InternalKeyBounds from manifest to base
2. added two new methods SmallestTrailer and LargestTrailer
> manifest: move InternalKeyBounds from manifest to base package

- blob_rewrite_test.go
- compaction.go
- compaction_test.go
- db.go
- get.go
- internal/manifest/version.go
- level_checker.go
- scan_internal.go
- sstable/blob/fetcher.go
- sstable/blob/fetcher_test.go
- sstable/blob/rewrite.go
- sstable/values.go
- tool/blob_files.go
The blob.ValueFetcher maintains a small cache of open blob file readers. This allows a scan that's retrieving values to avoid repeatedly re-opening the same blob file and re-retrieving the index block from the block cache. This cache previously used a fixed size of 5 in all contexts. This commit updates the fetcher to configure the size of the cache dynamically. Iterator construction now sets a cache size of 5 times the number of non-empty levels in the LSM, capturing the fact that deeper LSMs will reference more blob files over a span.
Close #5181.
```
│   all.txt    │
│   ops/sec    │
ycsb/A/values=1024   383.6k ± ∞ ¹
ycsb/B/values=1024   619.7k ± ∞ ¹
ycsb/C/values=1024   1.005M ± ∞ ¹
ycsb/D/values=1024   232.8k ± ∞ ¹
ycsb/E/values=1024   96.19k ± ∞ ¹
ycsb/F/values=1024   82.91k ± ∞ ¹ …
```
> blob: vary max cached readers by read amplification

- sstable/blob/fetcher.go
- sstable/blob/fetcher_test.go
Previously a blob.ValueFetcher's cached readers were implicitly pooled through the pooling of a pebble.Iterator. This commit updates the ValueFetcher to explicitly pool cached reader slices separately. The fetcher's cached readers are only retrieved if an external value is actually retrieved.
> blob: pool []cachedReader slices separately

- batch.go
The Iterator no longer exposes a RefreshBatchSnapshot method. Instead, the user must call SetOptions in order to refresh an Iterator's view of a mutated batch.
> db: remove comment's reference to RefreshBatchSnapshot

- sstable/block/compression_test.go
- sstable/block/compressor.go
CompressionStats is supposed to hold up to four settings but because of an off-by-one bug it only allows three. The "built-in" profiles use at most three, but it is possible for a user to define their own profile which might require four.
Fix and add a test.
Informs #5260
> block: fix off-by-one bug in CompressionStats

- scripts/stress.sh
We extend the stress time for certain packages that are more important
and have more/slower tests.
Fixes #5172
> scripts: improve stress.sh

- scripts/stress.sh
Increase the number of runs as many packages have very fast tests.
Also, use reduced parallelism only for the bigger packages.
Informs #5172
> scripts: more improvements to stress.sh

- compaction_picker_test.go
- compaction_test.go
- data_test.go
- db_test.go
- disk_usage_test.go
- excise_test.go
- ingest_test.go
- iterator_histories_test.go
- iterator_test.go
- lsm_view_test.go
- metrics_test.go
- range_del_test.go
- table_stats_test.go
- testdata/compaction/l0_to_lbase_compaction
- testdata/compaction/multilevel
- testdata/compaction/set_with_del_sstable_Pebblev4
- testdata/compaction/set_with_del_sstable_Pebblev5
- testdata/compaction/set_with_del_sstable_Pebblev6
- testdata/compaction/set_with_del_sstable_Pebblev7
- testdata/table_stats
- version_set_test.go
In `TestTableStats` any options passed to `define` persist through to
the next `define`, which is very unexpected.
We fix this by re-initializing the options each time.
We split off the main part of `TestCompaction`. Now each test file
initializes new state (which is less fragile and allows reproducing a
specific test file failure with a given seed).
In some tests (`TestCompaction`), the passed argument is incorrect
anyway (because `runDBDefineCmd` overwrites the FS we think we're
using).
We no longer require copying `CompactionConcurrencyRange` from the old
options.
Consolidate the two variants of this function: we create a new `MemFS`
only if `opts.FS` is not set (which is much more intuitive).
Note that we no longer call `EnsureDefaults()` before modifying the
options passed to the …
> db: clean up compaction test infrastructure

- internal/manifest/blob_metadata.go
- testdata/compaction/value_separation
When a virtual table is created from an existing sstable, the virtual table inherits the backing sstable's blob references. The BlobReference's ValueSize is computed by linearly interpolating according to the approximate virtual table size. This could be grossly inaccurate.
In #5214, we began tracking a virtual table's blob references' backing value size and using this to determine a blob file's eligibility for blob file rewrite compactions. Using the backing's value size is pessimistic, which avoids fruitlessly rewriting a blob file that is actually fully referenced.
The BackingValueSize introduced by #5214 is only populated for DBs at FormatBackingValueSize and later. We've observed instances (#5306) where blob file rewrite compactions repeatedly rewrite the same blob file due to this …
> manifest: don't compact blob files with uncertain outstanding references

- internal/cache/value.go
- internal/manual/manual_cgo.go
- internal/manual/manual_nocgo.go
This reverts commit dd58b8432fe899bfeeb55feb3ee76cf9d129b0e0.
The pebble ycsb benchmarks show a regression around the time this commit was merged. A comparison of the CPU profiles before and after show ~5.32% time in _Cfunc_calloc before and ~12.10% time in _cgo_cmalloc after.
> Revert "cache: use malloc instead of calloc"

- cockroachkvs/cockroachkvs.go
- cockroachkvs/cockroachkvs_test.go
- sstable/colblk/data_block.go
- sstable/colblk/data_block_test.go
```
goos: darwin
goarch: arm64
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
DataBlockDecoderInit-10   94.53n ± 0%   82.12n ± 0%  -13.13% (p=0.000 n=25)
│  old.txt   │              new.txt               │
│    B/op    │   B/op     vs base                 │
DataBlockDecoderInit-10   48.00 ± 0%   0.00 ± 0%  -100.00% (p=0.000 n=25)
│  old.txt   │               new.txt               │
│ allocs/op  │ allocs/op   vs base                 │
DataBlockDecoderInit-10   1.000 ± 0%   0.000 ± 0%  -100.00% (p=0.000 n=25)
```
Fix https://github.com/cockroachdb/pebble/issues/5339.
> colblk: remove BlockDecoder allocation

- cockroachkvs/cockroachkvs.go
- cockroachkvs/cockroachkvs_bench_test.go
The change in https://github.com/cockroachdb/pebble/pull/5345 prevented BlockDecoder from escaping to the heap when using
the testkeys.KeySchema, but with the cockroachkvs.KeySchema the key seeker init
func's local BlockDecoder still escaped. This commit updates the key seeker to
call colblk.DecodeColumn directly, which is enough for the Go compiler to avoid
moving the arg to the heap.
```
goos: darwin
goarch: arm64
pkg: github.com/cockroachdb/pebble/cockroachkvs
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
InitDataBlockMetadata-10   135.5n ± 1%   110.8n ± 0%  -18.20% (p=0.002 n=6)
│  old.txt   │              new.txt              │
│    B/op    │   B/op     vs base                │
InitDataBlockMetadata-10 …
```
> cockroachkvs: avoid cockroachKeysSeeker.init allocation

- db_test.go
- internal/cache/cache.go
- internal/cache/cache_test.go
- internal/cache/clockpro.go
- internal/cache/read_shard_test.go
- sstable/block/block.go
We don't want block cache hits for compactions to cause the respective
block to stay in the cache longer (in fact, it is about to become
obsolete). This change adds a `Peek()` method to the block cache which
is like `Get()` but does not mark the block as recently accessed.
> cache: don't mark blocks as accessed for background work

- obsolete_files.go
- obsolete_files_test.go
When `TargetByteDeletionRate` is set to a low value, `DB.Close()` can hang for a long time because deletion pacing uses `time.Sleep()` that can't be interrupted.
This change modifies `maybePace()` to check for early termination and use interruptible `select` instead of `time.Sleep()`.
Resolves: #5347
> fix cleanupManager.Close() hanging when deletion pacing is active

- checkpoint.go
- internal/manifest/virtual_backings.go
- version_set.go
This commit adapts the VirtualBackings type, replacing its ForEach and Backings methods with an All method that returns an iter.Seq of table backings. Additionally, use maps.Keys and slices.Collect where applicable.
> manifest: simplify VirtualBackings interface

- obsolete_files.go
- obsolete_files_test.go
Follow-up to #5348.
This test is ineffective because the `FreeSpaceThresholdBytes` option disables pacing. Fix by setting that option to 1 byte.
We also remove the extra checking of `stopCh` - if it is closed, we will exit the pacing loop right away so there's no need for this special check.
> db: fix TestCleanupManagerCloseWithPacing

- internal/compact/run.go
- replay/testdata/corpus/simple_val_sep
- replay/testdata/replay_val_sep
- sstable/colblk_writer.go
- sstable/internal/genprops/gen_props.go
- sstable/properties.go
- sstable/properties_gen.go
- sstable/rowblk_writer.go
- sstable/writer.go
- testdata/checkpoint
- testdata/compaction/backing_value_size
- testdata/compaction/compaction_cancellation
- testdata/compaction/mvcc_garbage_blob
- testdata/compaction/score_compaction_picked_before_manual
- testdata/compaction/set_with_del_sstable_Pebblev5
- testdata/compaction/set_with_del_sstable_Pebblev6
- testdata/compaction/set_with_del_sstable_Pebblev7
- testdata/compaction/value_separation
- testdata/compaction_delete_only_hints
- testdata/compaction_picker_pick_file
- testdata/compaction_picker_scores
- testdata/compaction_tombstones
- testdata/iter_histories/blob_references
- testdata/marked_for_compaction
- testdata/metrics
- testdata/table_stats
- value_separation.go
- value_separation_test.go
Add ValueSeparationKind and ValueSeparationMinSize to sstable properties to
track the value separation policy used when writing the table.
> sstable: track value separation policy props used

- open_test.go
> db: add TestCrashDuringOpenRandomized

- metamorphic/cockroachkvs.go
We should also keep generating a new suffix if our suffixIdx is == 0 - since a zero suffix sorts before all non-zero suffixes.
Fixes: #5349
> metamorphic: fix bug in suffix generation when prefix == startPrefix

- compaction_picker.go
- internal/manifest/testdata/virtual_backings/rewrite_candidates
- internal/manifest/virtual_backings.go
- options.go
- testdata/compaction/virtual_rewrite
Virtual rewrite compactions should run more conservatively. This commit
introduces a new option to configure the garbage ratio required by a backing
table to trigger a virtual rewrite compaction. We also adjust the estimation of
the  data still referenced such that blob references are assumed to remain
within the backing's virtual tables.
> crl-release-25.4: pebble: materialize virtual tables only if backing contains >= 30% garbage

- sstable/block/compression.go
- sstable/compressionanalyzer/buckets.go
- sstable/compressionanalyzer/testdata/buckets
- sstable/compressionanalyzer/testdata/file_analyzer
We change the "good" profile to use Zstd1 instead of adaptively
choosing between MinLZ1 and Zstd3. We also reduce some of the
thresholds and improve comments.
We also update the compression analyzer profiles. We no longer measure
MinLZ2 since it's almost as slow as Zstd1 with much smaller size
benefit over MinLZ1.
> block: minor improvements to compression profiles

- wal/failover_manager.go
- wal/failover_manager_test.go
- wal/failover_writer.go
- wal/failover_writer_test.go
- wal/testdata/manager_failover
When WAL failover is configured, a single logical WAL may be composed of multiple physical segment files. The creation of these physical segment files occurs asynchronously. This asynchronous creation may race with the closing of the failover writer.
Specifically, an outstanding attempt to create a segment file may block. Meanwhile, writes persisting all the necessary records may complete on the other device. If the logical WAL is now finished, the failover writer may be closed by higher-level code while the outstanding attempt to create a file remains. The system progresses, accumulating a list of obsolete files based on the set that existed at the time that the writer was closed. Eventually, the outstanding file creation may complete, creating a new file.
Previously this race resulted …
> wal: clean up all segment files

- .github/workflows/nightlies.yaml
- db.go
- go.mod
- go.sum
- internal/inflight/in_flight.go
- internal/inflight/in_flight_bench_test.go
- internal/inflight/in_flight_test.go
- iterator.go
- metamorphic/ops.go
- metamorphic/options.go
- open.go
- options.go
- options_test.go
- scan_internal.go
- scripts/run-tests-with-custom-go.sh
I will try to figure out how to test this with CRDB. I also plan to run sysbench to see if there is any observable perf hit.
Add a script and a nightly target that runs tests with the
custom Go runtime and the `cockroach_go` tag. The script is lifted
from crlib.
This will be used to report long-lived iterators.
We wire up iterators to an `inflight.Tracker`. Every 5 minutes we log
a report on iterators that have been open for more than 1 minute.
We disable iterator tracking by default (since the overhead is
measurable). In addition, we allow disabling tracking for specific
iterators via `IterOptions`.
In CRDB we will enable iterator tracking but exempt those in the
hottest batch eval paths.
> db: track and report long-standing iterators

- blob_rewrite.go
- compaction.go
- compaction_picker.go
- compaction_picker_test.go
- compaction_test.go
- data_test.go
- download.go
- options.go
- value_separation.go
We currently store a table format in compaction. In practice, this is
always `d.TableFormat()`, and we don't even end up using it when we
write the output (we use `d.TableFormat()` again).
This change removes the table format from the compaction to simplify
things a bit. This allows adding a simpler `DB.makeWriterOptions()`
(which makes future extensions easier).
> db: don't store table fromat in compaction

- wal/failover_manager.go
- wal/failover_manager_test.go
- wal/failover_writer.go
- wal/failover_writer_test.go
- wal/testdata/manager_failover
25.3 backport of https://github.com/cockroachdb/pebble/pull/5388 and https://github.com/cockroachdb/pebble/pull/5403.
When WAL failover is configured, a single logical WAL may be composed of
multiple physical segment files. The creation of these physical segment files
occurs asynchronously. This asynchronous creation may race with the closing of
the failover writer.
Specifically, an outstanding attempt to create a segment file may block.
Meanwhile, writes persisting all the necessary records may complete on the
other device. If the logical WAL is now finished, the failover writer may be
closed by higher-level code while the outstanding attempt to create a file
remains. The system progresses, accumulating a list of obsolete files based on
the set that existed at the time that the writer …
> crl-release-25.3: wal: clean up all segment files

- wal/failover_manager.go
- wal/failover_manager_test.go
- wal/failover_writer.go
- wal/failover_writer_test.go
- wal/testdata/manager_failover
25.4 backport of #5388 and #5403.
----
When WAL failover is configured, a single logical WAL may be composed of
multiple physical segment files. The creation of these physical segment files
occurs asynchronously. This asynchronous creation may race with the closing of
the failover writer.
Specifically, an outstanding attempt to create a segment file may block.
Meanwhile, writes persisting all the necessary records may complete on the
other device. If the logical WAL is now finished, the failover writer may be
closed by higher-level code while the outstanding attempt to create a file
remains. The system progresses, accumulating a list of obsolete files based on
the set that existed at the time that the writer was closed. Eventually, the
outstanding file creation may complete, creating a …
> crl-release-25.4: wal: clean up all segment files

- wal/failover_manager.go
- wal/failover_manager_test.go
- wal/failover_writer.go
- wal/failover_writer_test.go
- wal/testdata/manager_failover
25.2 backport of https://github.com/cockroachdb/pebble/pull/5388 and https://github.com/cockroachdb/pebble/pull/5403.
When WAL failover is configured, a single logical WAL may be composed of
multiple physical segment files. The creation of these physical segment files
occurs asynchronously. This asynchronous creation may race with the closing of
the failover writer.
Specifically, an outstanding attempt to create a segment file may block.
Meanwhile, writes persisting all the necessary records may complete on the
other device. If the logical WAL is now finished, the failover writer may be
closed by higher-level code while the outstanding attempt to create a file
remains. The system progresses, accumulating a list of obsolete files based on
the set that existed at the time that the writer …
> crl-release-25.2: wal: clean up all segment files

- metamorphic/options.go
- options.go
Add `DBCompressionSettings` that uses `FastCompression` on L6 (which
automatically chooses between MinLZ or Zstd1 for value blocks).
> db: add DBCompressionFast

- blob_rewrite.go
This param gets overwritten by the cached file reader. Remove setting this, as we also need to specify the corresponding argw henever this field is set.
Resolves: #5343
> pebble: remove unnecessary set of  ReportCorruptionFn
