cockroachdb/pebble

mem_table.go
mem_table_test.go

Replace the use of a `RWMutex` with atomic operations to update the
cached slice of tombstone fragments.

Lock-free updates of the cached tombstone fragments

---

internal/arenaskl/skl_test.go

The "TestConcurrentOneKey" test was assuming at least one write finished
before one hundred reads finished, which somehow was not the case 0.01%+
of the runs. We can wait for one write to finish at the beginning to
make sure this is the case. The test also runs in the old mode
(`startEmpty == true`) to prevent loss of coverage, except now it will
not require any reads to have seen data in that mode.

Make skiplist test more deterministic

---

compaction.go
sstable/writer.go
storage/syncing_file.go
storage/syncing_file_generic.go
storage/syncing_file_linux.go
storage/syncing_file_test.go

See the individual commits for more details.

Miscellaneous fixes to syncingFile

---

db/merger.go

db: improve the merge operator documentation

---

db/options.go
db/options_test.go
open.go
open_test.go

Verify comparer and merger name in OPTIONS file

---

compaction.go

Don't mark the memtables as flushed until after the deletion of obsolete
files from the flush job has completed. This makes testing easier, and
provides similar behavior to manual compactions where the compaction is
not marked as complete until the deletion of obsolete files job has
completed.
Fixes #119
Fixes #120

Deflake TestRecycledLogs and TestEventListener

---

compaction.go
db/event.go
event_listener_test.go
testdata/event_listener

For events available to `EventListener` for which the user has not
provided any custom handler, log them to the `db.Options.Logger`.

log EventListener events by default

---

cmd/pebble/main.go
cmd/pebble/test.go

Add --wait-compactions flag to wait for background compactions

---

cmd/pebble/ycsb.go

The --prepopulated-keys flag allows specifying how many keys are already
in the database. This allows running repeated read-only workloads
without inserting additional keys.

Enable specifying prepopulated keys for ycsb command

---

table_cache.go

The locking mechanism in tableCacheNode for retrieving the associated
sstable.Reader was showing up as a significant bottleneck. This was
clearly seen when running a read-only ycsb workload:
```
./pebble ycsb bench \
--workload scan=100 \
--duration 10s \
--initial-keys 0 \
--prepopulated-keys 10000000 \
--keys uniform \
--concurrency 10 \
--scans 1
```
```
____optype__elapsed_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
scan_100    10.0s        1037672       103771.7      0.1      0.1      0.1      0.2     16.8
```
With `--concurrency 1`, the performance was nearly identical. For a
workload like this, we expect the performance to increase almost
linearly with the number of CPUs. The blocking profile showed that the
tableCacheNode channel was the source of …

Fix a concurrency bottleneck in tableCache

---

sstable/writer.go

This field was mirroring the value in Writer.meta.Size. No need to
maintain both. Noticed while investigating #181.

Remove Writer.offset

---

batch.go

Lazy initialization of the range deletion tombstones in a flushableBatch
was not thread-safe. Additionally, this lazy initialization was not
providing any benefit as the tombstones would eventually be required
when the batch was flushed. The tombstones are now initialized when the
flushableBatch is created.

Fix concurrency bug in flushableBatch.newRangeDelIter

---

cmd/pebble/rocksdb.go
compaction_picker.go

This shouldn't every happen, but the check should be correct at least.

Fix the check for an empty compaction

---

commit.go
commit_test.go
db.go
db_test.go

The previous reworking of the `commitQueue` implementation accidentally
omitted an important invariant: `commitQueue.dequeue()` should only
return "applied" batches. The lack of this check was allowing the
visible sequence number to be ratcheted for unapplied batches. Added an
assertion that this invariant is not violated.
The change to not hold `DB.mu` during log writes failed to adequately
protected `DB.mu.log.LogWriter` allowing that field to be modified
concurrently with a call to `LogWriter.SyncRecord`. The concurrent
modification was occurring because `DB.mu` no longer protects that
field, yet some callers of `DB.makeRoomForWrite` were not synchronized.
Specifically, the calls in `DB.{Compact,Flush,AsyncFlush}`.
The change to not use `DB.mu` for commit pipeline synchronization also …

Fix a triple of synchronization bugs

---

iterator.go

Yes, the iterator direction switching code is subtle, but it is also
tested and there are no known issues. An attempt to implement the TODO
resulted in code that was as complex as the current code.
Fixes #90

Remove TODO about iterator direction switching code

---

docs/rocksdb.md

Added flush and compaction pacing notes to the Pebble vs RocksDB document.

Add pacing notes to docs/rocksdb.md

---

sstable/reader_test.go
sstable/testdata/hamletreader/hamlet_iter
sstable/testdata/prefixreader/iter
sstable/testdata/reader/iter

Added sstable reader tests with prebuilt SSTs.
These tests ensure that reading from these SSTs produce consistent results.
In particular, it ensures that the two level index reader is functioning as expected.

Add sstable reader tests with prebuilt SSTs

---

sstable/reader_test.go

Test that comparers and mergers are verified at sstable open

---

batch.go
commit.go
commit_test.go
compaction.go
compaction_test.go
db.go
db_test.go
filenames.go
ingest.go
ingest_test.go
internal/base/filenames.go
internal/base/filenames_test.go
internal/record/record.go
internal/record/record_test.go
mem_table.go
mem_table_test.go
open.go
open_test.go
table_cache.go
table_cache_test.go
tool/sstable.go
tool/testdata/sstable_scan
tool/testdata/wal_dump
tool/util.go
tool/wal.go
tool/wal_test.go
version.go
version_set.go

* Add Reader.Offset() for retrieving the record offset
* Move filename building and parsing to internal/base
* Export Batch.{SetNum,Count}
* Remove unused reverse fields

Implement `wal dump` tool

---

compaction.go
compaction_picker.go
compaction_picker_test.go
compaction_test.go
data_test.go
db.go
db_test.go
get_iter.go
get_iter_test.go
ingest.go
ingest_test.go
internal/manifest/version.go
internal/manifest/version_edit.go
internal/manifest/version_edit_test.go
internal/manifest/version_test.go
level_iter.go
level_iter_test.go
metrics.go
open.go
read_state.go
table_cache.go
table_cache_test.go
tool/manifest.go
tool/manifest_test.go
tool/testdata/manifest_dump
tool/tool.go
tool/util.go
version.go
version_set.go
version_test.go

* Move Version, and VersionEdit to internal/manifest
* Cut circular dependency between version and versionSet

Implement `manifest dump`

---

open.go
tool/data_test.go
tool/db.go
tool/db_test.go
tool/testdata/db_check
tool/testdata/db_lsm
tool/testdata/db_scan
tool/tool.go
tool/util.go
version_set.go

Implement `db {check,lsm,scan}`

---

.travis.yml

Add go1.13 normal and race configs

---

compaction.go
db.go
ingest.go
ingest_test.go
internal/base/event.go
testdata/ingest
version_set.go

Elide ingestion of empty sstables

---

db_test.go
ingest.go
open_test.go

db: add missing closed and read-only checks to DB.Ingest

---

internal/manifest/version_edit.go
internal/manifest/version_edit_test.go

RocksDB requires some entry in the MANIFEST to have `LastSeqNum` set
even if the value is zero. We ensure this happens by encoding
`LastSeqNum` if `VersionEdit.Comparer` has been set.

internal/manifest: fix a small RocksDB incompatibility with the MANIFEST

---

compaction.go
compaction_test.go

If `Options.DisableWAL` is set, the flush invariant checking around log
numbers needs to be disabled because there are no logs.

disable flush invariant check in the presence of DisableWAL

---

commit.go
commit_test.go
internal/record/log_writer.go

The `commitPipeline` and `record.LogWriter` coordinate in the amount of
concurrency allowed for `LogWriter.SyncRecord` operations. The contract
is that `SyncRecord` can only be called by `SyncConcurrency` goroutines
concurrently. This was failing to take into account the implicit
`SyncRecord` performed by `LogWriter.Close`. The off-by-one could lead
to a "queue is full" panic from the `LogWriter` code.
Fixes #301

fix "queue is full" panic

---

commit_test.go

Address code review comment and remove `syncDelayFile.waiting` which was
no longer necessary.

cleanup TestCommitPipelineWALClose

---

ingest.go
ingest_test.go
internal/base/internal.go
internal/base/internal_test.go
testdata/ingest_load
testdata/ingest_sort_and_verify

Also check for invalid keys.
Fixes #272

check for non-zero seqnums when ingesting sstables

---

ingest_test.go
internal/base/options.go
internal/base/options_test.go
open.go

Add support for parsing options. The intention is to use this in the
metamorphic testing.

add Options.Parse

---

compaction.go
db.go
event_listener_test.go
ingest.go
internal/base/event.go
internal/manifest/version.go
testdata/event_listener

implement DB.SSTables

---

batch.go
db.go
open.go
open_test.go

Correctly handle full memtable when replaying WAL.

---

batch.go
batch_test.go

Remove the unnecessary `*WriteOptions` parameter. That parameter is
necessary for the non-deferred methods to adhere to the `Writer`
interface.
Remove the `error` return value from the `*Deferred` ops. This was done
by changing the type of `Batch.count` from a `uint32` to a `uint64` and
checking for overflow when the count is set in `Batch.Repr()` (or really
any time `Batch.Count()` is called).
Manually inline encoding of varint32s. Simplify some of the slice math
in `Batch.prepareDeferred*`.
```
name                 old time/op  new time/op  delta
BatchSet-16          22.9ns ± 1%  15.5ns ± 2%  -32.26%  (p=0.000 n=10+10)
BatchSetDeferred-16  22.1ns ± 4%  13.7ns ± 1%  -37.85%  (p=0.000 n=10+9)
```

optimize the Batch.*Deferred methods

---

internal/record/log_writer.go

Note that this doesn't actually fix the panic seen in #346, but I've
been unable to reproduce that through repeated stressing of this code
and the test that failed. If the panic happens again, we'll have more to
debug.
Fixes #346

internal/record: improve handling of flushLoop panics

---

internal/record/log_writer.go
internal/record/log_writer_test.go

`LogWriter.Close()` was previously failing to wait for the flush-loop to
terminate which led to a rare race condition in the `internal/record`
tests where a buffer shared between a writer and a reader could be
written to by the writer's flush-loop after the writer had been
closed. Added additional synchronization to allow waiting for the
flush-loop to terminate after `Close` has signalled for it to close.
Fixes #356

internal/record: wait for flush-loop to terminate in LogWriter.Close

---

Makefile

We're using go modules to vendor, but `GO111MODULE=auto` now enables
modules when running within `GOPATH` under go1.13. Explicitly disable
the usage of the module cache so that we can use the vendored source. We
could also specify `-mod=vendor` under go1.13, but that flag doesn't
work the same under go1.12.
Removed the `bench` target. This was useful at one time, but with the
growth of the code base it is better/easier to run `go test -v -run -
-bench <test>` from the command line.

explicitly disable go module support for {test*,stress*,generate}

---

db.go
testdata/event_listener
version_set.go

close the manifest on DB.Close()

---

options.go
tool/db.go

Automatically infer the comparer/merger for the `db` commands by loading
the `OPTIONS` file. Added support for skipping unknown options and
sections which was necessary to make this work when running a `db`
command on a RocksDB generated DB.
Initialize the pretty formatter for `db scan` if the comparer has one
specified.
Fixes #391

tool: automatically infer comparer/merger for db commands

---

compaction.go
internal/base/cleaner.go
testdata/cleaner

like ArchiveCleaner, is being used.
Fixes #396

Do not recycle WAL files when a cleaner that needs the file contents,

---

tool/db.go
tool/manifest.go
tool/sstable.go
tool/testdata/db_scan
tool/testdata/sstable_scan
tool/wal.go

* tool: add -v/--verbose to all commands

tool: add --count flag to {db,sstable} scan

---

sstable/block.go

Add a comment that makes reading / understanding this code and
the interactions between offsets and restarts easier.

sstable/block: add comment about restart points and numRestarts

---

compaction.go
internal/record/log_writer.go
table_cache.go

Add pprof labels for compaction, flushing, table loading, and WAL
flushing/syncing. This allows filtering out profiling samples for those
operations using the `tagfocus=` pprof command.

sprinkle some pprof labels

---

level_checker.go

Properly close all of the iterators opened by
`DB.CheckLevels`. Previously we were failing to do this in various error
paths, and also failing to close the range-del iterators even on
success.

ensure all iters opened by CheckLevels are closed

---

db.go

properly close iterators on error in DB.newIterInternal

---

internal/metamorphic/generator.go
internal/metamorphic/history.go
internal/metamorphic/test.go

* internal/metamorphic: improve history output
* internal/metamorphic: only use lowercase letters for random keys/values

internal/metamorphic: minor improvements

---

compaction_iter_test.go
testdata/compaction_iter

Follow-up from the last PR which I forgot to push.

db: reset allowZeroSeqnum on every TestCompactionIter "iter" command

---

open.go
open_test.go

db: fix arena full failures in Open() caused by slowly growing memtable

---

table_cache.go
table_cache_test.go

This allows readers to retry operations without hitting the same error
every time due to a cached table reader in error state. This PR also
fixes a segfault when `sstable.NewReader` fails.

release readers that failed to open from table cache

---

sstable/reader.go

Don't skip a `twoLevelIterator` forward/backward if iteration has
reached the upper/lower bound.

sstable: optimize twoLevelIterator.skip{Forward,Backward}

---

compaction.go
compaction_test.go

Noticed the 5s time for this test while debugging #493 and decided to
fix it. Per the suggestion in #463, the approach to avoiding the
`time.Sleep` in the test is to add a `manualCompaction.retries` count
which is incremented on the head manual compaction whenever
`DB.maybeScheduleCompaction` is called and the manual compaction cannot
be run.

db: remove time.Sleeps from TestManualCompaction

---

compaction.go
db.go
db_test.go

The DB.Close() racing ahead of deletion caused an error if the DB
was immediately reopened and the new DB also scheduled some of the
same files for deletion.
Discovered by the changes to the metamporphic test that closes and
reopens the DB.

db: make DB.Close() wait for any ongoing deletion of obsolete files

---

.travis.yml

* ci: trim down build matrix
* ci: only build PRs targeted at master

ci: miscellaneous changes

---

compaction.go
ingest_test.go

Previously, concurrent compaction picking and ingestion could collide
because compaction picking was operating with an out-of-date view of the
`Version`. The solution is for compaction picking to acquire
`versionSet.logLock` for the duration of its work. Note that concurrent
compactions did not suffer the same problem because they are stored in
`DB.mu.compact.inProgress`. Ingestions are not stored there because we
don't know until the ingestion is committed which level we'll be
ingesting into. And each file in an ingestion can be ingested into a
different level.
Fixes #528

db: properly lock compaction picking and ingestion

---

internal/record/record.go
internal/record/record_test.go

When a record spans blocks in the WAL it is broken into chunks. We were
erroneously returning a truncated record if a non-first chunk for a
record was part of different WAL incarnation. This could happen if we
wrote one chunk of the record and then crashed (or were terminated)
before writing the rest of the chunks.
Removed `Reader.started` which was equivalent to `Reader.blockNum >= 0`.
Fixes #540

internal/record: don't return partial records

---

internal/metamorphic/generator.go
internal/metamorphic/meta_test.go
internal/metamorphic/ops.go
internal/metamorphic/options.go

* internal/metamorphic: add option to use DB.Apply for DB.Ingest operations
* internal/metamorphic: randomly choose [1,3] batches to ingest

internal/metamorphic: duo of ingestion improvements

---

compaction_test.go
db.go

When a memtable (or large batch) is queued for flushing, it is not
necessarily automaticaly flushed due to the heuristic in
`DB.maybeScheduleFlush` which avoids flushing a small memtable. If
compaction encounters such a queued memtable, it needs to force flushing
to occur. We previously saw this same problem with ingestion in #515.
Fixes #556

db: force flush of queued memtables when manually compacting

---

internal/intern/intern.go
internal/intern/intern_test.go
sstable/properties.go

sstable: intern loaded property strings

---

open.go
open_test.go

This adds a helper function, IsWrittenTo, that opens the newest
options file and checks if it was written by pebble, through
the existence of the pebble_version key.

open: Add helper to check if pebble last wrote to directory

---

batch.go
compaction.go
db.go
error_iter.go
get_iter.go
ingest.go
internal/arenaskl/flush_iterator.go
internal/arenaskl/iterator.go
internal/arenaskl/skl_test.go
internal/base/iterator.go
internal/batchskl/iterator.go
internal/rangedel/fragmenter.go
internal/rangedel/iter.go
internal/rangedel/tombstone.go
internal/rangedel/tombstone_test.go
internal_test.go
iterator_test.go
level_checker.go
level_checker_test.go
level_iter.go
level_iter_test.go
merging_iter.go
merging_iter_test.go
sstable/block.go
sstable/reader.go
sstable/reader_test.go
testdata/level_checker

Include new checks in DB.CheckLevels:
1) Point key ordering in SSTs.
2) Ordering and fragmentation of rangeDelV2 formatted blocks in SSTs.
3) Successful processing of all MERGE records.
Issue: #264

tool: enhance db check

---

iterator.go

db: rework doc comment on Iterator.SeekPrefixGE

---

internal/arenaskl/iterator.go
internal/batchskl/iterator.go

fix doc for Skiplist Iterator

---

iterator_test.go

This change builds off a discussion in #572 around better testing
of reuse of unsafe iterator key/value slices. This change adds
an invalidatingIter wrapper that sets the last key/value slice
to 1s after eve ry positioning call. This wrapper is used for
the main iterator datadriven tests, as well as all tests involving
fakeIter.
Fixes #574.

iterator_test: Add invalidatingIter wrapper that sets last key/val to 1s

---

internal/metamorphic/meta_test.go
internal/metamorphic/ops.go
internal/metamorphic/options.go

* internal/metamorphic: fix ingest_using_apply implementation
* internal/metamorphic: randomize MaxConcurrentCompactions
* internal/metamorphic: enable run comparison by default
* internal/metamorphic: temporarily disable ingest_using_apply

internal/metamorphic: a quartet of changes

---

internal/metamorphic/meta_test.go

This commit adds a `-trace-file` flag to support taking traces during
metamorphic tests. The `go test` command has a `-test.trace` flag, but
the flag won't cross `exec.Command`-ing subtests.
When this new `-trace-file` flag is supplied, it gets propagated to
subtests through the `go test` `test.trace` flag.

internal/metamorphic: add trace flag

---

compaction.go
options.go
sstable/options.go
sstable/table_test.go
sstable/writer.go

[release-20.1] sstable: support NeedCompact method for property collectors

---

tool/db.go

Previously when `pebble db properties` was run on a database with a
nondefault merger, it'd error with an 'unknown merger' error. The
sstable.Reader was constructed without the sstable.Mergers option.

tool: fix `db properties` on DBs with nondefault merger

---

internal/cache/clockpro.go
internal/cache/clockpro_test.go

If `shard.Set` was setting a key that already existed in the cache, a
call to evict was being performed before the entry was being
acquired. The `shard.evict()` call could end up evicting the entry being
set, which made the subsequent `entry.acquire` call invalid allowing the
entry to be double-freed. The double-freed entry would then be
double-allocated, leading to all sorts of badness such as nil-pointer
dereferences.

internal/cache: fix double-free of cache entries

---

tool/lsm.go

Add a method to pebble tool that returns underlying command
implementations.  This accessor makes it possible for the caller
to customize command invocation (such as redirecting stdout to
non-default location).

tool: Add accessors for the underlying command

---

snapshot_test.go

Add a unit test that exercises interactions between snapshots and range
deletions.

db: add stress test of snapshots and range deletions

---

internal/cache/clockpro.go
internal/cache/clockpro_test.go

If `shard.Set` was setting a key that already existed in the cache, a
call to evict was being performed before the entry was being
acquired. The `shard.evict()` call could end up evicting the entry being
set, which made the subsequent `entry.acquire` call invalid allowing the
entry to be double-freed. The double-freed entry would then be
double-allocated, leading to all sorts of badness such as nil-pointer
dereferences.

release-20.1: internal/cache: fix double-free of cache entries

---

event.go

Fix CompactionInfo documentation surrounding the level of
Input.Tables[1].

db: fix CompactionInfo documentation

---

internal/batchskl/skl.go

The batchskl uses the unsafe package to avoid unnecessary allocation
when a node is not the maximum height. Previously, if a node was
allocated at the end of the arena, the node struct could straddle the
end of the arena, with the unused links extending into unallocated
memory.
Go 1.14 adds a checkptr check to -race builds that checks for pointer
alignment issues, and it flags the conversion of these
partially-allocated nodes at the arena boundary.
This commit changes the allocation logic to grow the arena such that the
entirety of the last node struct is allocated.
Fix #667.

internal/batchskl: ensure entire node points to allocated memory

---

commit.go
ingest_test.go

Fix a bug where an ingest and a concurrent, overlapping write might
cause a violation of the sequence number invariant.
Previously, an overlapping, concurrent write with an earlier sequence
number might be skipped by an ingestion when checking for overlapping
memtable writes. If the concurrent write had not yet been applied to the
memtable, the ingestion would not wait for the write to be applied and
flushed. This would result in the ingested file with a newer sequence
number appearing beneath the earlier overlapping write in the LSM.
Now ingests will pause after allocating sequence numbers, waiting for
all proceeding writes to complete before continuing and checking the
memtables.

db: wait for pending writes during ingestion

---

cmd/pebble/ycsb.go

Fix the keys/sec metric which was broken by the use of a global
`ycsbOpsMap`. This map translates op name to op enum, but the name is
the "full name" which includes the weight of the op, such as `read_95`
or `insert__5`.

cmd/pebble: fix key/sec metric

---

internal/randvar/uniform.go

Use an atomic increment for adjusting the max value for a `Uniform`
random variable, rather than using a mutex. The atomic increment is
significantly faster under contention.

internal/randvar: optimize Uniform.IncMax

---

db.go
table_cache.go

Refactor the tableCache estimateDiskUsage methods into a more general
withReader function that accepts a closure. This change paves the way
for a the range deletion—aware compaction heuristic which will also
need direct access to *sstable.Readers.

db: refactor tableCache.estimateDiskUsage into withReader

---

cmd/pebble/compact.go

In the `pebble bench compact run` command, wait for background
compactions by counting active compactions through the event listener.
Previously, it looked at `(*DB).Metrics` scores, but a heuristic may
decide to compact a table for reasons beyond the level score.

cmd/pebble: wait for background compactions using tracker

---

internal/record/log_writer.go

The `LogWriter` was performing an unnecessary allocation every few block
flushes. Noticed in passing while looking at a heap profile. Very
unlikely for this to be impactful, but fixing was easy.

internal/record: remove an unnecessary allocation in LogWriter

---

commit.go
ingest_test.go

Backport of #674 for the 20.1 branch.

crl-release-20.1: db: wait for pending writes during ingestion

---

cmd/pebble/compact.go
cmd/pebble/test.go

Add --profile, --trace flags to collect pprof profiles and Go traces
while running compaction benchmarks.

cmd/pebble: collect profiles, traces during compaction benchmarks

---

batch.go
batch_test.go
open.go
options.go
options_test.go

db: add max memtable and max batch size checks

---

compaction.go
compaction_test.go
db.go
get_iter.go
ingest.go
internal/manifest/l0_sublevels_test.go
internal/manifest/level.go
internal/manifest/level_test.go
internal/manifest/version.go
internal/manifest/version_edit.go
level_checker.go
level_iter.go
level_iter_test.go
merging_iter_test.go

Add Level type which represents a level and sublevel for logging and
error messages.

internal/manifest: add Level type

---

table_cache.go

* db: add a per-tableCacheShard table closing goroutine
* db: remove table loading goroutine

db: adjust tableCache goroutine handling

---

internal/record/log_writer.go

Previously, `LogWriter` would allocate all of the free blocks up front
and use a channel for "allocating" them. With a record block size of
32KB and 16 free blocks, this meant that every `LogWriter` would
allocate 512KB of memory. This pushed CI race builds over the edge and
caused out of memory conditions. The handling of free blocks has been
reworked to use a mutex and a channel. New blocks are allocated on
demand up to a maximum of 16 total blocks in flight by a single
`LogWriter`. If log throughput is low, or the number of records written
by a test is small, only a single 32KB block will be allocated.

internal/record: rework the handling of LogWriter free blocks

---

internal/cache/entry_normal.go

Disable the use of the entry alloc cache in race builds because that
cache requires the use `runtime.SetFinalizer` which triggers a bug in
the Go race detector in go1.15 and earlier versions.

internal/cache: avoid SetFinalizer in race builds

---

checkpoint.go
checkpoint_test.go

Fix a data race where Checkpoint could read the current manifest size
while a concurrent manifest write was updating it. Add a test that
without the fix exercises this data race while run under the Go race
detector and flakes with a corrupted checkpoint when not.
Fixes #748.

db: fix Checkpoint race condition

---

cmd/pebble/ycsb.go

Replace the keys/sec metric with cumulative ops/sec. The keys/sec metric
is related to ops/sec and thus wasn't adding much info. Displaying
cumulative ops/sec provides an early indication of where a test run will
finish. This also matches the behavior of the Cockroach `workload` tool.

cmd/pebble: replace keys/sec with ops/sec(cum)

---

compaction.go
compaction_picker.go
compaction_test.go
data_test.go
db.go
error_test.go
event.go
event_listener_test.go
flush_external.go
ingest.go
ingest_test.go
internal/manifest/version.go
internal/manifest/version_test.go
metrics_test.go
open.go
options.go
range_del_test.go
sstable/writer.go
table_stats.go
table_stats_test.go
testdata/ingest
testdata/manual_compaction
testdata/range_del
testdata/table_stats

Implement a variant of RocksDB's min-overlapping ratio compaction heuristic.

db: implement min-overlapping ratio heuristic

---

checkpoint.go
compaction.go
compaction_picker.go
compaction_picker_test.go
compaction_test.go
data_test.go
db.go
get_iter.go
get_iter_test.go
ingest.go
internal/manifest/l0_sublevels.go
internal/manifest/l0_sublevels_test.go
internal/manifest/version.go
internal/manifest/version_edit.go
internal/manifest/version_edit_test.go
internal/manifest/version_test.go
level_checker.go
level_checker_test.go
merging_iter_test.go
table_stats.go
tool/db.go
tool/manifest.go
version_set.go

* internal/manifest: rename L0Sublevels.Files to L0Sublevels.Levels
* internal/manifest: rename Version.Files to Version.Levels

internal/manifest: rename *.Files to *.Levels

---

table_stats_test.go

The loadedStats.TableStatsInfo pointer was previously protected by
loadedStats.Mutex, but wait-loaded-initial didn't lock the mutex before
dereferencing the pointer.
In fixing this bug, I simplified loadedStats to use the DB.mu to prevent
concurrent access instead, because DB.mu is already held while
TableStatsColleccted is invoked.
Fixes #761.

db: fix race in TestTableStats

---

merging_iter.go

In #738, I fixed an invariant violation stemming from an exhausted
levelIter. The fix seeked the levelIter when switching directions if the
levelIter's key was a range tombstone. @petermattis pointed out the fix
was overeager, seeking whenever a levelIter was at a sstable boundary,
rather than only when exhausted.

db: tighten merging iterator's seek conditions

---

batch.go
range_del_test.go

The DeleteRangeFlushDelay implementation had a bug where it only applied
to delete range tombstones directly added to a batch that was committed.
If a batch is modified through SetRepr or Apply, this change updates the
Batch's state so that it will trigger the DeleteRangeFlushDelay if
necessary.

db: fix DeleteRangeFlushDelay for batches edited with SetRepr, Apply

---

cmd/pebble/ycsb.go
iterator.go
metrics.go

Output a Go-bench format summary line at the end of `bench ycsb`. This
summary includes ops/sec, bytes read, bytes written, average read
amplification, and ending write amplification.
Add `Metrics.Total()` which returns the sum of the level metrics and the
WAL metrics.
Add `Iterator.Metrics()` method and `IteratorMetrics` struct. Currently,
`IteratorMetrics` only contains a `ReadAmp` field which measures the
read-amplification experienced by the iterator. The read-amplification
is the sum of the memtables, the L0 sublevels and the non-empty Ln
levels.

cmd/pebble: output a Go-bench format summary line for `bench ycsb`

---

internal/rate/rate_test.go

internal/rate: deflake TestLongRunningQPS

---

internal/mkbench/mkbench.go

Allow raw data to be gzip'd or uncompressed.

internal/mkbench: don't require bzip compression of raw data

---

docs/js/app.js
internal/mkbench/mkbench.go

When loading "raw" data, walk through symlinks. The symlink setup is used
by the TeamCity setup to avoid some awkward directory movement. There are
other ways to avoid symlinks, but simply walking them seems easiest.
Render data for missing days with a dashed line.

docs,internal/mkbench: walk through symlinks, and handling missing data

---

batch.go

db: clarify Batch.Reset docs

---

docs/css/app.css
docs/index.html
docs/js/app.js

* docs: display annotation in chart title when hovered
* docs: allow hovering over the detail line
* docs: add last updated text to nightly benchmarks

docs: misc improvements to nightly benchmarks

---

compaction_picker.go

Update a few L0 compaction-picking routines to use the
manifest.LevelIterator rather than directly accessing the level file
metadata slice.

db: update L0 compaction-picking to use manifest.LevelIterator

---

internal/record/log_writer.go
internal/record/log_writer_test.go

Once we stop panicking on commitPipeline failures and start placing DB into
read-only mode, all queued writers waiting for their sync need to be notified
of the sync error so that they can run to completion.
See also: #270

record: propagate WAL sync errors to queued writers

---

cmd/pebble/rocksdb.go

This fixes build errors in the cmd/pebble/rocksdb.go file.
- Implement rocksDBIterator.SeekLT, crdbPebbleDBIterator.SeekLT, as interface has been changed in PR #796
- Change method signature of crdbPebbleDB.Scan, as interface has been changed in PR #796
- Change type conversion, as type of 'Size' field has been changed in PR #845

cmd/pebble: fix rocksdb build errors

---

sstable/unsafe.go
sstable/unsafe_test.go

sstable: support >1GB sstable blocks

---

compaction.go

Remove the unused `compaction.maxExpandedBytes` field which was
accidentally left around when compaction picking info was moved into the
`pickedCompaction` struct.

db: remove unused compaction.maxExpandedBytes

---

db.go

db: remove unneeded assignments

---

internal/manifest/btree.go
internal/manifest/btree_test.go

Uncapitalize/unexport the methods of the package's `btree` and `iterator`
types. These types are internal to the package and only accessed via
`LevelMetadata`, `LevelSlice`, `LevelIterator` types. Uncapitalizing
makes their usage and scope unambiguous.

internal/manifest: unexport internal btree type methods

---

internal/manifest/btree.go
internal/manifest/btree_test.go

When using the B-Tree implementation to back the LevelSlice and
LevelIterator data structures, B-Tree iterators will need to be compared
to enforce bounds. This add a cmpIter function for comparing two B-Tree
iterators by comparing their positions within their stacks, starting
from the root.

internal/manifest: add helper for comparing B-Tree iterator positions

---

internal/metamorphic/meta_test.go

Previously, when running the metamorphic test multiple times using the
Go test flag `-count`, each run would use the same prng seed. This is
unexpected and a footgun. This change updates TestMeta to generate a new
seed each time it runs if the `-seed` flag was not provided.

internal/metamorphic: generate a new seed every run

---

ingest_test.go

Currently, the number of sstables in the database has a large effect on
the latency of creating a new version (#718). The planned use of a
B-Tree to hold a level's FileMetadata structures should address most of
this effect. This commit adds a new microbenchmark that should see
improvement when LevelMetadata is backed up by the B-Tree.
```
goos: darwin
goarch: amd64
BenchmarkManySSTablesNewVersion/sstables=10-16         	   10000	    183010 ns/op
BenchmarkManySSTablesNewVersion/sstables=1000-16       	   10000	    208511 ns/op
BenchmarkManySSTablesNewVersion/sstables=10000-16      	    3805	    387492 ns/op
BenchmarkManySSTablesNewVersion/sstables=100000-16     	     198	   6185426 ns/op
BenchmarkManySSTablesNewVersion/sstables=1000000-16    	      13 …
```

db: add benchmark for creating a new version with many sstables

---

compaction_test.go

Add a unit test that tests a compaction that fails part-way through. The
pending outputs should be removed from the filesystem.
I originally missed the defer func in `runCompaction` that handles this
and thought it was a deficiency.

db: add unit test for removing failed compaction outputs

---

internal/manifest/btree.go

The B-Tree implementation copied from Cockroach recycles nodes returning
them to a `sync.Pool` when their refcount drops to zero. We will use
the reference counting for file reference counting, decrementing file
reference counts when containing B-Tree nodes' refcounts are decremented
to zero. This happens when a Version becomes obsolete, allowing the
underlying files to be marked as obsolete and deleted from the
filesystem.
These new B-Tree reference counting semantics pose a problem. A Version
becoming obsolete does not mean that the Version's level metadata is not
in use. Multiple concurrent compactions may be created from the same
version and obtain handles into the Version's level metadata. Whichever
compaction finishes first can mark the Version as obsolete. Reclaiming
the version's …

internal/manifest: remove node recycling

---

sstable/reader.go
sstable/reader_test.go

Previously, sstable.reader was performing readahead ramp-up for reads.
Given that compactions always read entire input files, the ramp-up
can be skipped to reduce disk read ops.
This change adds additional setup for compactions, which lets the reader
skip the readahead ramp-up by setting the `sequentialFile` parameter of
the iterator.
Fixes #854.

sstable: skip readahead ramp-up for compactions

---

ingest_test.go

CockroachDB relies on the idempotence of ingestion and may ingest a file
multiple times. RocksDB errors if the same inode is ingested multiple
times. Going forward, CockroachDB can remove the complicated error
checking surrounding ingestion as long as Pebble does not error on
duplicate ingestions. Ensure that we preserve this behavior with a test.

db: add test for ingest idempotence

---

vfs/mem_fs.go

Add `memFile.Flush` so that users of `memFile` (such as
`sstable.Writer`) know that it is buffered and don't wrap it in a
`bufio.Writer`. This prevents unnecessary buffering and allows the
`memFile` invariants to work better. Benchmarked that this was not a
performance problem with `sstable.BenchmarkWriter`. If anything, this
might be slightly faster:
```
name       old time/op    new time/op    delta
Writer-16    80.7ms ± 2%    80.1ms ± 1%    ~     (p=0.400 n=10+9)
name       old alloc/op   new alloc/op   delta
Writer-16    23.2MB ± 0%    23.1MB ± 0%  -0.02%  (p=0.000 n=10+9)
name       old allocs/op  new allocs/op  delta
Writer-16       709 ± 0%       707 ± 0%  -0.28%  (p=0.000 n=10+10)
```

vfs: add memFile.Flush, remove flushFile

---

sstable/table.go

Adjust comment about `sstable.Iterator` usage to reflect current
API. Adjust comment about `sstable.Writer` usage to reflect current API.

sstable: fix doc comment to remove reference to Reader.Get

---

internal/metamorphic/generator.go

metamorphic: reposition all batch iterators after mutation

---

db.go

In some cases, the db.deleters.Wait() at the end of db.Close()
added in #1045 could end up causing a deadlock, as the closing
goroutine would continue holding the db mutex while the deleting goroutine
could be trying to grab it to update stats.
This change fixes that deadlock by having the closing goroutine
release db.mu while it waits for deleters.

db: Fix possible deadlock between Close and delete goroutines

---

iterator.go

This change removes a TODO that was added to reference issue #1029.
As we've determined that that issue is not worth fixing (see #1041),
this change removes that TODO.
Also removes an unused variable in the readSampling struct.
Fixes #1029.

*: Remove TODO in sampleRead, remove unused var

---

README.md

update README with note about production readiness

---

iterator.go

We were returning to the caller of an Iterator positioning
call, the return value of find{Next,Prev}Entry. The
Iterator.Valid() method returns the Iterator.valid field.
The find{Next,Prev}Entry methods could leave Iterator.valid
as true, in some rare error cases, when returning false.
The code now explicitly returns Iterator.valid everywhere.

db: cleanup Iterator.valid behavior

---

db.go
iterator.go

@sumeerbhola
In theory repeated conditions and two iterAlloc and getIterAlloc fields inside Iterator structure can be ommited by utilizing interface with three methods SetKeyBuf and SetPrefixKey... and Release to release struct to specific pool (iterAllocPool or getIterAllocPool),   if it's ok for you I can modify this.
Smth like this? https://github.com/cockroachdb/pebble/pull/1096

db: reduce getInternal allocations of getIter and Iterator

---

compaction.go
compaction_test.go

A huge Lbase, due to a compaction backlog, can currently
cause a memtable that is wide in the key space to be
flushed as many tiny files. This heuristic is an unrefined
way of preventing such a situation, but at the cost of
wide L0 files.

db: heuristic to prevent tiny flushed files due to Lbase

---

compaction.go
metrics.go
metrics_test.go
testdata/event_listener
testdata/ingest
testdata/metrics
tool/testdata/db_lsm
version_set.go

db: add per-compaction type counts to Metrics.Compact

---

db.go
db_test.go

This patch reduces the number of slice allocations for a new
iterator when the read amplification is larger than 10.
Pebble benchmarks are mostly unchanged:
```
name                old ops/sec  new ops/sec  delta
ycsb/A/values=64      819k ± 6%    812k ± 7%    ~     (p=0.739 n=10+10)
ycsb/B/values=64     1.09M ± 7%   1.08M ± 5%    ~     (p=0.853 n=10+10)
ycsb/C/values=64     2.27M ±28%   2.40M ±22%    ~     (p=0.529 n=10+10)
ycsb/D/values=64      897k ± 7%    891k ± 7%    ~     (p=0.971 n=10+10)
ycsb/E/values=64      214k ± 5%    213k ± 6%    ~     (p=0.739 n=10+10)
ycsb/F/values=64      239k ± 1%    239k ± 1%    ~     (p=0.684 n=10+10)
ycsb/A/values=1024   77.1k ± 4%   77.4k ± 3%    ~     (p=0.796 n=10+10)
ycsb/B/values=1024    323k ± 8%    326k ± 9%    ~     (p=0.912 n=10+10) …
```

db: reduce number of iterator allocations when read amp is high

---

compaction.go

This commit doubles down on the change made in 4419cc6 in response to #1030.
Even with that change, I'm seeing cases where the `pacer != nilPacer` check is
responsible for **7.4%** of total CPU time on a moderately hot node that is spending
about **86%** of it time performing compactions.
```
File: cockroach
Type: cpu
Time: Jun 4, 2021 at 9:53pm (UTC)
Duration: 5.12s, Total samples = 12.43s (242.86%)
Showing nodes accounting for 12.43s, 100% of 12.43s total
----------------------------------------------------------+-------------
flat  flat%   sum%        cum   cum%   calls calls% + context
----------------------------------------------------------+-------------
0.92s   100% |   github.com/cockroachdb/pebble.(*DB).compact1 /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroach …
```

compaction: hoist nilPacer check outside compaction loop

---

cmd/pebble/compact.go
event.go

I plan to use this is CockroachDB to tee events to a new `pebbleMetricListener`
object that will listen to and expose metrics on write stalls. This will give us
better visibility into these events.

Export TeeEventListener

---

tool/lsm.go

Add an edit count flag to the LSM visualizer tool so that we can
visualize a subset of a MANIFEST's edits. I'm currently using this
change to visualize part of a MANIFEST from cockroachlabs/support#1063
that otherwise is prohibitively expensive to visualize.
Related to #1177.

tool: add --edit-count flag to LSM visualizer

---

cmd/pebble/fsbench.go
cmd/pebble/fsbenchlist.go
cmd/pebble/main.go
cmd/pebble/test.go

The code includes the benchmarks, and also some benchmarks which can be run.
Each benchmark is written as a function which returns a struct which contains
all the information required to run the benchmark.

benchmarks : code for file system benchmarks

---

internal/manifest/version.go

Go allocations are guaranteed to be 64-bit aligned which we take advantage
of by placing the 64-bit fields which we access atomically at the beginning
of the FileMetadata struct. For more information, see
https://golang.org/pkg/sync/atomic/#pkg-note-BUG.

internal/manifest: Move Atomic field in FileMetaData to the top.

---

internal/manifest/l0_sublevels.go

Currently, the `fileInterval` struct contains both a `files` slice and a
`fileCount` int. The latter can be computed from the former.
Remove the redundant `fileCount` field.

internal/manifest: remove redundant `files` field

---

sstable/reader.go
sstable/reader_test.go

To provide better detection of corruption upon ingestion of an SSTable,
add the ability for an `sstable.Reader` to validate the checksums of all
blocks in the underlying file for the SSTable.
The new `(*sstable.Reader).ValidateBlockChecksums` will be used by a
subsequent change to perform validation of an SSTable upon ingestion,
with any corruption that may be detected detected passed to the
corruption reporting and recovery mechanism outlined in
cockroachdb/cockroach#67568.
See also: #1203.

sstable: support block checksum validation for entire SSTables

---

internal/metamorphic/meta_test.go
internal/metamorphic/options.go

Currently, by default, the metamorphic tests use a MemFS-backed DB by
default. The `-disk` flag can be used to override all tests to use a
disk-backed filesystem. The behavior is "all or nothing".
To better simulate use of Pebble with a real, disk-backed filesystem,
randomly generate test configurations that use disk.
Tweak the flags to allow specifying an override filesystem type. In the
case that "mem" or "disk" are specified, all metamorphic tests will use
that FS type, ignoring the randomly generated FS type. The default is to
use the randomly generated FS types. Disk-backed filesystems are used
25% of the time for the randomly generated configurations.
Related to cockroachdb/cockroach#69414.

metamorphic: randomly use disk for tests

---

vfs/atomicfs/marker.go
vfs/atomicfs/marker_test.go
vfs/atomicfs/testdata/marker

Add a ReadMarker function for reading an atomic marker's value without
opening it for writing.

vfs/atomicfs: add ReadMarker

---

internal/metamorphic/meta_test.go

We have some sources of randomness in our code, so having shorter runs allows
us to run the test more times in a time period, which allows us to reproduce
diffs faster.
Directly comparing two options can reduce the time taken to run the test
from over a minute to ~1-2 seconds.

internal/metamorphic: add cli to diff specific options outputs

---

cmd/pebble/compact.go
cmd/pebble/compact_new.go
cmd/pebble/random.go
error_test.go
internal/manifest/btree.go
internal/manifest/btree_test.go
internal/manifest/l0_sublevels.go
internal/metamorphic/test.go
internal/pacertoy/pebble/main.go
internal/pacertoy/rocksdb/main.go
sstable/raw_block.go
tool/data_test.go
tool/util.go

Address U1000 – Unused code.
Addresses #1327.

*: address staticcheck lint check U1000

---

.github/workflows/ci.yaml
internal/lint/lint_test.go

Enable the staticcheck static analysis tool in CI.
Closes #1327.

*: enable staticcheck

---

docs/index.html

Add a closing `</body>` tag to the HTML.

docs: add closing body tag in index.html

---

cmd/pebble/write_bench.go

Currently, each goroutine driving load as part of the `pebble bench
write` benchmark is configured with a burst of `incBase`, which by
default is 100. In aggregate, when multiplied by the number of
goroutines (typically 1024), large bursts occur when the test has been
in the cooldown period and not driving load (i.e. all goroutines idle).
Reduce the configured burst value for each rate limiter to the minimum
value to avoid excessive bursting.

cmd/pebble: avoid bursts in `pebble bench write`

---

iterator_test.go

After flush, there are 5 files in L6, each with ~4000 keys, so
even the highest match-interval of 1000 will need to read
something from each file. As expected the block property
filtering is faster as the match-interval increases and ~50x
faster for the highest match-interval.
The small difference for match-interval=1 is noise.
The allocation increase is all due to
https://github.com/cockroachdb/pebble/blob/c0661aef47c559c4ec3225a6b055cadab9ad2354/sstable/block_property.go#L408
which is paid once per file iterator creation.
```
BenchmarkBlockPropertyFilter/match-interval=1/filter=false-16         	     130	   8906014 ns/op	      40 B/op	       0 allocs/op
BenchmarkBlockPropertyFilter/match-interval=1/filter=true-16          	     136	   8786348 ns/op	     175 B/op	      10 allocs/op …
```

db: add a benchmark for block property filtering

---

compaction_iter.go
compaction_iter_test.go
internal/base/merger.go
iterator.go
iterator_test.go
merger.go
testdata/compaction_iter
testdata/iterator

DeletableValueMerger allows the caller to indicate if the key is deletable.
Related issue #1219

db: add deletable value merger

---

db.go

Fix a small compliation error stemming from merge skew.

db: fix merge skew

---

compaction.go

Previously, if compaction-splitting logic indicated we should finish the
current output before the current key, a flush would first call
`TruncateAndFlushTo` to flush pending tombstones up to the current key.
However, the logic to finish the output would also pass the current key to
`finishOutput` to serve as the split key, calling `compactionIter.Tombstones`
and then `TruncateAndFlushTo`.

compaction: remove redundant TruncateAndFlushTo call

---

sstable/writer.go

Once writer/compression queues are introduced, we're going to need some
datastructure to pass the compressed/uncompressed data to the writer/
compression queues. Since, these slices will be owned by the dataBlockBuf
anyway, this pr adds compressed/uncompressed fields to the dataBlockBuf.

sstable: add compressed/uncompressed fields to the dataBlockBuf

---

sstable/writer.go

Move the logic to compute a checksum onto the `checksummer` type and make it
infallible. Previously the only possible failure was misconfiguring the
checksummer with an unsupported checksum type.

sstable: move checksum logic onto checksummer

---

internal/manifest/l0_sublevels.go

We do some duplicate work in calculating the {min,max}IntervalIndex for a file
which can be avoided. This pr uses a line sweep algorithm to process the file
intervals, and avoids the binary search used to calculate {min, max}IntervalIndex.
Improvement in L0Sublevels creation:
```
name                old time/op    new time/op    delta
L0SublevelsInit-24    9.44ms ± 5%    7.30ms ± 5%  -22.66%  (p=0.010 n=4+6)
name                old alloc/op   new alloc/op   delta
L0SublevelsInit-24    2.98MB ± 0%    3.08MB ± 0%   +3.58%  (p=0.029 n=4+4)
name                old allocs/op  new allocs/op  delta
L0SublevelsInit-24     33.8k ± 0%     33.8k ± 0%     ~     (all equal)
```

internal/manifest: use a line sweep to optimize NewL0Sublevels 

---

sstable/write_queue.go
sstable/writer.go

Once parallel compression/writers are enabled, the sstable size estimation will
no longer be correct, as we could have inflight block writes.
This pr introduces a mechanism to estimate the contribution of these inflight
blocks to the sstable size.
We also need to estimate the indexBlock size. When parallelism is enabled, index
blocks are only updated from the writeQueue goroutine. However, the index block size
needs to be accessed from the Writer client goroutine. The index block size is
accessed to determine the EstimatedSize of the sstable, and to also determine if
the index block needs to be flushed. We need to determine whether to flush index
blocks in the Writer client goroutine, to support block property collectors.
The index block estimation will be done in a future pr.

sstable: estimate Writer.EstimatedSize when parallelism is enabled

---

sstable/writer.go

The buffer used to compute separator keys cannot be stored in the indexBlockBuf,
because the same indexBlockBuf can be accessed by the Writer client and the
writeQueue. Instead, we store it in the dataBlockBuf, since a dataBlockBuf is
guaranteed to be only accessed by either the Writer client or the writeQueue.

sstable: fix race in sstable when parallelism is enabled

---

docs/RFCS/20220112_pebble_sstable_format_versions.md

Update the RFC status to `completed`.
Update the RFC body to match the implementation.
Add a section on the Cockroach cluster version sequencing for table
format version bumps.

docs: minor tweaks to table format version RFC

---

docs/RFCS/20220311_pebble_flushable_ingested_sstable.md

Forgot to include this diff in the last cycle of reviews for #1586.

docs/rfc: flushable ingested sstable addition

---

open_test.go

This was a missing piece of testing I found given the all of the
testing in this commit:
https://github.com/cockroachdb/pebble/commit/2dde123d9e26e56538a49d80f8fcf1115ddc83e3
This pr confirms that a table cache passed into db.Open is actually used.

db: add additional table cache test for the Open function

---

sstable/writer.go

When parallelism is disabled in the sstable Writer, the estimate of the
estimated sizes of the sstables and the index blocks should match the
estimated sizes of the sstables and the index blocks.

sstable: enforce sstable size estimation invariants

---

merging_iter.go

Fix a data race in SeekPrefixGE. The merging iterator's findNextEntry method
has an optimization for prefix iteration: When the merging iterator observes a
range deletion and seeks lower-level iterators to the deletion's end boundary,
the merging iterator checks whether the current iteration prefix is exhausted.
Previously, if the entire iterator was exhausted, this optimization would
accidentally read the heap root key `m.heap.items[0].key` for a heap that is
empty. The iterator that surfaced `m.heap.items[0].key` would have already been
exhausted, and the key could point into memory already released (eg, a sstable
iterator already returned to a pool).
This data race is not likely to have caused any inconsistencies in production,
because under the conditions the race was possible the …

crl-release-21.2: db: fix data race in SeekPrefixGE

---

iterator_test.go

Test different seek operations, include range keys and split keys across
multiple levels.

db: expand TestSetOptionsEquivalence code coverage

---

external_iterator.go

This change updates NewExternalIter to skip creation of a point-key
mergingIter if there is only one merging iter level and there are
no range dels. It also skips creation of a simpleLevelIter if there
is only one file that would be contained in it. And it skips
creation of a rangeKey interleaving iterator if there are no range
keys. These optimizations avoid overhead that's only necessary for
multi-file, range-key cases.
Together, these optimizations produce a ~45% performance gain
for forward iteration:
```
name                                                   old time/op  new time/op  delta
SSTIterator/keys=10000/variant=pebble/verify=false-10  1.22ms ± 0%  0.67ms ± 0%  -45.27%  (p=0.001 n=5+10)
```

*: optimize external iters for single-file, no-rangekey cases

---

table_cache.go

During tableCache.Close, wait for each shard's releasing goroutine to exit.
Fix #1898.

db: wait for table cache releasing goroutines to exit

---

iterator_test.go

The range key masking implementation can be subtle. Especially if
we use a block property filter to make iteration faster.
This pr introduces a randomzied test which varies target file sizes,
block sizes, and whether the iterator uses a filter or not for the
masking.
It compares the results from a simple configuration with the random
configuration.

db: stress rangekey masking implementation in a randomized test

---

internal/metamorphic/crossversion/crossversion_test.go

**metamorphic/crossversion: copy temp dir on failure**
On failure, copy the failing temporary directory into the current
working directory.
**metamorphic/crossversion: avoid linking test binaries**
Avoid linking the test binaries into the test directory; it's
unnecessary and causes complications in CI.

metamorphic/crossversion: various improvments

---

format_major_version.go
format_major_version_test.go

Presently there's a race with concurrent compactions and the logic in `compactMarkedFilesLocked` where we expect each call to `maybeScheduleCompactionPicker` to create at least one compaction, when that is not guaranteed especially around concurrent compactions.
This change updates the logic there to only wait on compactions if we actually scheduled one.
Fixes #2044.

*: Fix race in compactMarkedFilesLocked with concurrent compactions

---

format_major_version.go
format_major_version_test.go

22.2 backport of #2060 .
---
Presently there's a race with concurrent compactions and the logic in `compactMarkedFilesLocked` where we expect each call to `maybeScheduleCompactionPicker` to create at least one compaction, when that is not guaranteed especially around concurrent compactions.
This change updates the logic there to only wait on compactions if we still have marked files for compaction at wait time.
Fixes #2044.

[crl-release-22.2] *: Fix race in compactMarkedFilesLocked with concurrent compactions

---

internal/metamorphic/crossversion/crossversion_test.go

Run the metamorphic test runs on the individual initial states in parallel, with a maximum parallelism set through a new `--parallelism` command-line flag. This can reduce the wall-time for a run of the crossversion metamorphic test, and improve utilization of the host machine. Default to using half the available CPUs to account for the metamorphic tests' own parallelism when running with `--max-threads` > 1.
Close #2079.

crossversion: parallelize metamorphic test runs

---

compaction.go
compaction_picker.go
internal/metamorphic/meta_test.go
internal/metamorphic/options.go
options.go
options_test.go
table_stats.go

Cockroach 21.2 backports of #2081, #2092 and #2093.

crl-release-21.2: metamorphic: various improvements

---

compaction.go
compaction_picker.go
internal/metamorphic/meta_test.go
internal/metamorphic/options.go
options.go
options_test.go
table_stats.go

Cockroach 22.2 backports of #2081, #2092 and #2093.

crl-release-22.2: metamorphic: various improvements

---

compaction.go
compaction_picker.go
internal/metamorphic/meta_test.go
internal/metamorphic/options.go
options.go
options_test.go
table_stats.go

Cockroach 22.1 backports of #2081, #2092 and #2093.

crl-release-22.1: metamorphic: various improvements

---

internal/base/lazy_value.go
internal/base/lazy_value_test.go

This will be used in CockroachDB's pebbleIterator.
Informs https://github.com/cockroachdb/pebble/issues/1170

base: add LazyValue.TryGetShortAttribute

---

compaction.go
internal/metamorphic/options.go
options.go
options_test.go

Informs https://github.com/cockroachdb/pebble/issues/1170

db: make EnableValueBlocks dynamically configurable

---

replay/replay.go

Fix a data race caused by accessing an atomic-only member variable without an an atomic load. Rename the variable to clarify that it should be accessed through atomics only.
Fix #2214.

replay: fix data race

---

open.go
open_test.go

Some of the error paths were very hard to read through.

db: minor cleanup in Open

---

vfs/disk_health.go

If `invariants.Enabled`, this change replaces the atomic Stores with CompareAndSwaps to ensure that only one write operation at a time is writing to this disk health checking file. This increases confidence in our disk health checking, as the logic relies heavily on there being one write operation per file at a time.
Fixes #2274.

vfs: enforce serialized writes in diskHealthCheckingFile

---

sstable/writer_test.go

sstable: add v3 to BenchmarkWriters

---

cleaner_test.go
compaction.go
options.go

This reverts commit 31c333655e2d743aa9bc455a3a73e840d6acfe99.

Revert "db: unflake TestArchiveCleaner"

---

compaction.go
objstorage/provider.go
open.go

Update obsolete object deletion to go through objstorage.

objstorage: delete obsolete objects through provider

---

sstable/reader.go
sstable/reader_test.go

sstable: add readahead for value blocks

---

compaction.go

sstasble: allow duplicate deletes in deleteObsoleteObject

---

db.go
internal/manifest/version.go
metrics.go
table_stats.go
testdata/metrics

db: add per-level ValueBlocksSize gauge to Metrics

---

.github/workflows/ci.yaml
bloom/bloom_test.go
compaction_test.go
data_test.go
internal/lint/lint_test.go
internal/metamorphic/ops.go
record/record_test.go
replay/workload_capture_test.go
sstable/reader_test.go
sstable/writer_rangekey_test.go
vfs/vfs_test.go

Use the latest version of Go in CI.

ci: test against go1.20

---

objstorage/objstorageprovider/provider.go
objstorage/objstorageprovider/provider_test.go

objstorage: test shared objects with TestNotExistError

---

metamorphic/generator.go
metamorphic/ops.go
metamorphic/parser.go

This commit adds restriction spans to the checkpoint op in the metamorphic test (with 50% probability).

metamorphic: add spans to checkpoint op

---

objstorage/objstorageprovider/vfs_readable.go
sstable/reader.go

This commit adds a "shortcut" through the objstorageprovider which allows using a preallocated read handle. This avoids two sync.Pool-backed allocations in `singleLeveliter.init`.
Informs https://github.com/cockroachdb/cockroach/issues/101299.

sstable: optimize NewReadHandle allocations

---

batch_test.go
compaction_picker_test.go
compaction_test.go
data_test.go
external_iterator_test.go
go.mod
go.sum
ingest_test.go
iterator_histories_test.go
iterator_test.go
mem_table_test.go
range_del_test.go
scan_internal_test.go

**go.mod: update cockroachdb/datadriven dependency**
**db: use datadriven convenience utilities where beneficial**
Use convenience utilities for scanning command arguments where beneficial.

db: use datadriven convenience utilities where beneficial 

---

db_test.go

This change adds a unit test that utilizes the EventListener to
slow down compactions/flushes to reproduce https://github.com/cockroachdb/cockroach/issues/101896.

db_test: Add a unit test to exercise memtable/ingestion inversion

---

compaction.go
db.go

We were counting flushes for the bytes-in-progress metric (which is not the intention of the metric). When replaying the WAL, we perform a flush but do not clean up the metric, resulting in an one-time leak. The result is that we always see the same non-zero value instead of zero.
The fix is to not count at all during flushes. As a test, we run an invariants-only check on the metrics on close; we could potentially check other things here as well. This new assertion fails without this fix.
Fixes #2548

crl-release-23.1: db: fix leak for compaction bytes-in-progress metric

---

objstorage/objstorageprovider/shared_cache.go
objstorage/objstorageprovider/shared_cache_test.go

Part of https://github.com/cockroachdb/pebble/issues/2541. Follow up on https://github.com/cockroachdb/pebble/pull/2553.
**sharedcache: improved randomized test, fix bugs**
This commit improves the randomized test based on a suggestion from Radu. The test now does 100 distinct reads to the same file. This leads to cache eviction happening, which has flushed out bugs in the handling of the case where we only read a prefix of data from the cache.
This commit fixes the found bugs, while also refactoring the logic for clarity, again based on a suggestion from Radu. The two found bugs were in the cache's ReadAt method. The first was the use of ofs instead of ofs+n in the computation of the length of the cache-block-multiple-sized buffer to read into. The second was the use of ofs instead of …

sharedcache: improved randomized test, fix bugs

---

internal/base/metrics.go
replay/replay.go
replay/replay_test.go

During compaction benchmarking, compute flush utilization.

replay: surface FlushUtilization metric

---

cmd/pebble/ycsb.go

Previously, if a ycsb benchmark performed no reads (eg, workload F), then no read amplification was reported because no reads were performed. Now in these cases a separate goroutine will periodically sample the database's worst-case read amplification.
Close #2590.

cmd/pebble: sample read amp during write-only ycsb workloads

---

compaction.go
compaction_test.go

Delete pacing is used to avoid slowdowns on certain SSDs caused by
deleting many large files. We don't want this pacing when deleting
shared objects.

db: don't pace deletions of shared objects

---

ingest.go

22.2 backport for #2610.
After #2486 went in, we added some cases of writerRef/writerUnref without ensuring we schedule a flush after taking away the last writer ref. This resulted in some deadlocks if a future goroutine would wait for a flush while the unreffing goroutine didn't follow the convention of calling maybeScheduleFlush. This change adds those calls.
Fixes #2597.

[crl-release-22.2] db: Call maybeScheduleFlush after writerUnref

---

batch.go
batch_test.go

This change adds an AddInternalKey method that can be used as an umbrella method to add any (indexable) internal key, in place of calling Set,Merge,Delete,SingleDelete, etc. More convenient for external callers that deal with internal keys instead of user keys.

batch: Add method to add internal keys

---

table_cache.go
table_cache_test.go

Informs https://github.com/cockroachlabs/support/issues/2340

db: wrap error when creating Reader with backing filenum

---

ingest.go

Previously we would delay the call to maybeScheduleFlush in ingestApply mostly out of readability. However it's safe to call it directly as the flush will wait for the manifest lock (which we are holding in that method) before it applies anyway. Furthermore, calling it directly avoids a bug where error cases in ingestApply could lead to us not scheduling a flush for a flushable memtable.

ingest: Call maybeScheduleFlush immediately in ingestApply

---

cmd/pebble/replay.go

When the `pebble bench replay` tool is passed a `--count`, run each iteration by exec-ing the binary, replacing the existing process. The goal is to remove any process state that might interfere with the independence of each run.

cmd/pebble: exec for each iteration of the benchmark

---

ingest_test.go

Currently, `TestIngestValidation` ingests a file from the local filesystem. The ingested file uses a path that remains the same across test runs. This limits the ability of the test to run in parallel.
Alter the test to use `t.TempDir()` to ensure that the path is unique across test runs.
Fix #2640.

db: support concurrency in TestIngestValidation

---

compaction.go

Previously, if we had logLock()'d but found us conflicting with a recently-completed excise, we would not end up releasing the manifest lock, stalling all future writes to the manifest. This change fixes it.

compaction: Call logUnlock on errored compactions

---

open.go

This PR logs the number of keys and the offset that we stopped reading from when replaying a WAL file. This logging can help with support issues such as https://github.com/cockroachlabs/support/issues/2369
Fixes: #2618

pebble: Log Replay WAL Metrics

---

internal/manifest/l0_sublevels_test.go

internal/manifest: link issue to skipped test

---

compaction_picker_test.go
testdata/compaction_picker_scores

db: deflake TestCompactionPickerScores

---

internal/manifest/l0_sublevels_test.go

Previously we had skipped the L0Sublevels_LargeImport test as
it was not well-written and buggy. On closer inspection it does
not provide any net new test coverage and is just a sanity test
with loading a large manifest and picking some compactions in a row,
something that will happen with metamorphic test runs too. Plus,
the same manifest is already loaded in some benchmarks. Fixing
the test added 60+ seconds to the runtime of the whole test suite.
This change deletes this test.
Fixes #2710

internal/manifest: delete L0Sublevels_LargeImport test

---

pacer.go
pacer_test.go

@jbowens this is a proposal to improve the behavior of the delete pacer heuristics.
----
The delete pacer has two heuristics to disable pacing altogether: one is when the free space drops below 16GB and one when the ratio of obsolete to live bytes goes over 20%.
Disabling pacing altogether can lead to a very sudden burst of large deletions, causing large latency spikes. In particular the obsolete bytes heuristic can be triggered when a large table is deleted.
In this change we make the transition smoother, using the idea that we want to get back to the desired thresholds within a given timeframe (10 seconds for the free bytes heuristic, 5 minutes for the obsolete bytes heuristic). Instead of effectively increasing the pacing rate to infinity, we increase it based on how many bytes are …

db: smoother thresholds for the delete pacer

---

db.go

The SSTables() method returns sstable info from a Pebble db instance. This change adds an additional field denoting the type of storage backing a given sstable in addition to all other sstable properties; i.e. whether an sstable is local, shared (non-foreign), shared+foreign, or external.

db: Add StorageType to SSTableInfo

---

vfs/disk_health_test.go

Previously this unit test used a short sleep to emulate a disk stall. It then relied on the disk-health checking goroutine running and noticing the briefly stalled operation. This was fragile and unlucky goroutine pauses or general host CPU starvation could result in the disk-health checking goroutine not observing the stall. This commit switches the test to stall the filesystem operation until it's observed.
Fix #2792.

vfs: deflake TestDiskHealthChecking_Filesystem

---

rangekey/rangekey.go

This pull request exports the keyspan.Fragmenter to be used in Cockroach's MultiSSTWriter changes.
Related pr: https://github.com/cockroachdb/cockroach/pull/106771

pebble: Export keyspan.Fragmenter

---

vfs/disk_health.go

The diskHealthCheckingFile is designed with the expectation that file write operations are serial. Previously, under the invariants build tag we would verify this expectation through updating state with a CompareAndSwap, asserting that the previous value equaled the value previously written by the same goroutine.
This commit moves this logic out of the invariants.Enabled gating. While an atomic swap operation may be slower than a simple atomic store, any additional cost should be negligible relative to the latency of the I/O write operation itself. This can improve confidence that we're obeying this contract in all instances, including direct VFS-usage within CockroachDB.
Informs cockroachdb/cockroach#97968.

vfs: always swap and verify in health checking updates

---

compaction.go
db.go

When we have a large batch we append it separately to the queue as a flushableBatch, with the same `logNum` as the last memtable.
The code sets the last memtable's `logNum` to 0. This is intended as a defensive measure (in case we flush the memtable without the flushableBatch) but it is incorrect: on flush, if the memtable is the first that is not ready to flush, its `logNum` will be chosen as the `minUnflushedLogNum` which will trigger the invariant violation error.
Note that this condition seems to be very rare, likely because large (~32MB) batches in Cockroach are rare and because it requires a writer reference to the memtable to last longer than it takes for the large batch to be flushed to the WAL.
The fix is to leave the memtable's `logNum` as is; together with the `logNum` …

crl-release-22.2: db: don't clear logNum when appending flushable batch

---

compaction.go

Previously, compaction-picking invariants guaranteed us that we would never delete a compaction's input file while it was in progress. However, the introduction of Excise changes this; a compaction's inputs could get excised, and we could consider those files as obsolete because compactions don't explicitly grab a ref of either the current version or readState otherwise.
This change introduces a version ref/unref in runCompaction so we don't try to delete a compaction's inputs during a compaction, only to panic because there are sstable iterator refs still on the underlying sstables.
Will fix cockroachdb/cockroach#110090 when it lands in cockroach master.

compaction: maintain a ref of current version in runCompaction

---

.github/workflows/nightly-code-cover.yaml

This allows the workflow to be triggered manually.

github: update nightly-code-cover.yaml

---

iterator.go

Informs: https://github.com/cockroachdb/cockroach/issues/110765

db: add invariant for ValueAndErr

---

open.go
open_test.go

Previously, we were ratcheting nextFileNum ahead of all locally present obsolete sstables, but not doing the same for obsolete sstables in shared storage. This would cause errors due to FileNum clashes on restart after a mid-compaction process abort where some new sstables were created and persisted in the provider.
This change addresses that by ratcheting nextFileNum during Open() ahead of all known objects in the provider too.

open: Ratchet nextFileNum ahead of objprovider objects

---

open.go

During Open, Pebble verifies the consistency between the Version and the object catalog. Previously if this function encountered an error or inconsistency, it would return a new error that erased the type(s) of the original errors. This commit modifies the function to use errors.Join and avoid the type erasure. This is necessary for the metamorphic test's error injection, which must be able to test an error to observe whether it is an errorfs.ErrInjected error.
Informs #1115.

db: return structured errors from checkConsistency

---

batch.go
batch_test.go
db.go
iterator.go
range_keys.go
snapshot.go
testdata/indexed_batch_mutation

Informs https://github.com/cockroachdb/cockroach/issues/113090

db: add Batch.NewBatchOnlyIter that reads only from the Batch

---

db.go
scan_internal_test.go
testdata/scan_statistics

Also give one example of how to interpret these statistics. And clarify that SnapshotPinned* are not counting what they are claiming to count.

db: add KeyStatistics.LatestKindsCount

---

metamorphic/ops.go

Previously, for what was likely an unintentional omission, we were not ingesting range keys in the ingest operation in metamorphic tests. In both the apply and the ingest cases, we would construct a batch/sstable that excluded range keys. This change updates the ingestOp to ingest range keys.

metamorphic: ingest range keys

---

metamorphic/ops.go

Ingesting a batch closes it. As a result we should also be syncing
on the db where a batch came from, even if it's not the db that the
batch was ingested into. This prevents cases where we close the db
before we ingest a batch that came off of it, and deletes on the
batch would then panic because the underlying db (where we do an
isFMV() call) would be nil by then.
Fixes #3055.

metamorphic: sync on derived dbs in ingestOp

---

compaction.go

In rare cases, it's possible for an excise to come in and cancel
a move/copy compaction, and for us to try to read an input file for the
compaction that no longer exists. In that case we previously
would return an `objprovider: file not found` error, when in reality
we should return ErrCancelledCompaction so it's handled correctly
higher up in the stack, such as in metamorphic tests.
Found with #3044.

compaction: return correct error if copy/move compaction is cancelled

---

table_stats.go

The size of an External file represents the portion of the file within some bounds, not the size of the entire file.

skip size check for External files

---

compaction_iter.go

Informs https://github.com/cockroachdb/cockroach/issues/114421

db: more invariant checking for InternalKeyKind in compactionIter

---

sstable/block_property.go

This brings the number allocs/op in CRDB's
`BenchmarkRefreshRange/linear-keys/refresh_window=[99.00,99.00]` from 61 down to 20.

sstable: reduce allocs in intersectsUserPropsAndFinishInit

---

sstable/properties.go

This call has a lot of overhead. We replace this call with `FieldByIndex`. For this to work, we have to make sure we generate the correct sequence of field struct indexes.
This should fix some microbenchmark regressions.
See benchmark results in https://github.com/cockroachdb/pebble/pull/3126

crl-release-23.2: sstable: remove FieldByName call in Properties.load

---

sstable/block_property.go

This brings the number allocs/op in CRDB's
`BenchmarkRefreshRange/linear-keys/refresh_window=[99.00,99.00]` from 61 down to 20.

crl-release-23.2: sstable: reduce allocs in intersectsUserPropsAndFinishInit

---

record/log_writer_test.go

This commit attempts to fix a very rare flake in this test (which I could not reproduce). It is conceivable that the background tasks get delayed and thus the write latency they observe is lower.
We improve this by running `Close()` at the start of the sleep, which will force a flush as soon as possible. We also up the sleep to 100ms.
Fixes #1877

record: fix TestMetricsWithSync flakiness

---

open.go

This is in response to the hazard raised in
https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1702923954950209?thread_ts=1702921711.638549&cid=C0KB9Q03D (internal link).

db: code comment about guaranteeing durability of initial state

---

sstable/format.go
table_cache.go

Also added a comment about optimizing compaction reads of these
foreign ssts.

sstable: update comment about SINGLEDEL, foreign ssts and compactions

---

external_iterator.go

Previously, we'd sometimes double-close Readers if `finishInitializingExternal` returned an error. This is because we would put all the sstable.Readers in a slice so we could close them in case of error, but we also called dbi.Close() which closes them in one return case. Double-closing would lead to an `inconsistent reference count: -1` panic.
Informs cockroachdb/cockroach#116566 (will fix when lands in cockroach).

external_iterator: don't double-close Readers in case of err

---

metamorphic/options.go
options.go

The code comment motivating this change is copied from https://github.com/cockroachdb/cockroach/pull/116889.
Fixes #3183

metamorphic: don't panic on SingleDeleteInvariantViolationCallback

---

table_cache_test.go

db: set correct bounds in TestVirtualReadsWiring

---

data_test.go
iterator_test.go
testdata/iterator_table_filter

db: switch from table to block property collector in iterator test

---

metamorphic/key_manager.go

This change updates the key manager to track changes to writer bounds caused by range key operations. These could affect the success/failure of ingestions, which is something the key manager determines.
Fixes #3226.

metamorphic: track bounds of rangekey operations in key manager

---

metamorphic/generator.go
metamorphic/key_manager.go
metamorphic/key_manager_test.go

This commit merges the `byObj`, `byObjMap` and `bounds` maps into a
single map to a consolidated `*objKeyMeta`.
We no longer store keys in two structures; we only use a map.  We
simplify and improve `mergeKeysInto` to use the target map instead of
sorting and merging all keys; this should be much faster when the
target is the database.

metamorphic: consolidate key manager per-object structures

---

checkpoint.go
cleaner.go
compaction.go
db.go
db_test.go
event.go
internal/base/cleaner.go
internal/base/filenames.go
metrics.go
open.go
testdata/checkpoint
testdata/cleaner
testdata/event_listener
testdata/metrics
tool/find.go
version_set.go
wal/log_recycler.go
wal/standalone_manager.go
wal/wal.go

wal: standalone implementation (single log file per WAL)
db: use wal package
Informs https://github.com/cockroachdb/pebble/issues/3230
Informs [CRDB-35401](https://cockroachlabs.atlassian.net/browse/CRDB-35401)

db,wal: standalone implementation and integration

---

compaction.go
ingest.go

Previously, we'd panic on an excise excising under an EventuallyFileOnlySnapshot even if the excise's version edit was slated to come after the flush that would transition the EFOS to a file-only snapshot. This change moves this check to after the logAndApply, so that the check happens after the excise is complete.
Also, previously we were not transitioning an EFOS to file-only if there were any memtables with any unflushed keys with seqnums lower than an EFOS' seqnum, even if that memtable had no keys within the EFOS' protected bounds. This change relaxes the criteria to transition an EFOS to a file-only snapshot to mimic the logic in the ingestion side, eliminating cases where we were expecting a flush to transition an EFOS but it didn't, resulting in a panic.
Fixes #3258.

ingest: narrow transition of EFOS to file-only, delay excise panic

---

metamorphic/generator.go

This change adds a function that generates an integer with the
exponential distribution, where larger values are exponentially less
probable. This is useful to provide some coverage for larger values
while keeping the value small in most cases.

metamorphic: add helper for random int with exponential distribution

---

table_cache.go

Minor cleanup in the table cache reader to make it less likely that we
will plumb virtual table properties into the physical reader.

table cache: improve comments, simplify loadInfo

---

sstable/reader_iter_single_lvl.go
sstable/reader_iter_two_lvl.go

sstable: document some invariants in virtualLastSeekLE

---

compaction.go

Pull out logic to transition EFOSes to file-only after a flush into a helper function. The flush1 function is growing large and will grow larger with #3233.

db: extract a helper from flush1

---

docs/index.html

See cockroachdb/cockroach#117852.

docs: annotate change in benchmark hardware

---

wal/failover_writer_test.go

wal: skip TestFailoverWriter on windows

---

wal/testdata/failover_writer/errors

wal: disable a flaky failoverWriter test case

---

db.go

Previously, if the db was closed and a Download() call was waiting on a download to finish, we could see an indefinite wait because `maybeScheduleCompactionPicker` would not schedule any compactions, and the cond lock would never be broadcasted to. This change addresses this by checking for db closure before waiting on the compaction cond lock in downloadSpan().

db: don't wait on compaction cond lock if db is closed

---

db.go
metrics.go
wal/failover_manager.go
wal/failover_manager_test.go
wal/testdata/manager_failover
wal/wal.go

wal,db: add wal.FailoverStats

---

table_cache_test.go

db: fix TestVirtualReadsWiring flake

---

data_test.go
ingest_test.go
testdata/ingest_external

ingest_test: support reopening engine in test

---

open.go
open_test.go

When a user sets Options.Lock to pass in an already-acquired directory lock, Open validates that the lock was acquired for the same directory. Previously, this didn't account for uncleaned paths, relative paths, symlinks, etc. This commit adjusts the check to fall back to using os.SameFile to check whether the locked directories match if the paths are not identical.

db: allow Options.Lock's dirname to be equivalent path

---

metamorphic/config.go
metamorphic/generator.go
metamorphic/ops.go
metamorphic/parser.go

Test `DB.Download` in the metamorphic test.

metamorphic: add DownloadOp

---

metamorphic/config.go

Opened #3430 to track fixing and reenabling.
Fixes #3426.

meta: temporarily disable downloadOp

---

vfs/vfstest/open_files.go

Previously, in error cases that returned a typed nil, WithOpenFileTracking would wrap the typed nil file with open file tracking, incorrectly identifying file leaks that don't exist.

vfs/vfstest: adjust WithOpenFileTracking to not wrap typed nils

---

wal/failover_writer.go
wal/failover_writer_test.go

wal: fix recordQueue bug due to forgetting to mod when indexing

---

metamorphic/ops.go

We weren't simulating the excise when the batch wasn't empty but it
yielded an empty sst (e.g. it only contained a `LogData`). Fix that
and refactor the code a bit to avoid three copies of this code.
Informs #3448

metamorphic: add a missing simulated excise

---

metamorphic/options.go

The level checker can significantly slow down downloads and background
compactions in the metamorphic test.
This change makes the level checker run only once per 500ms (on
average).
Informs #3460

metamorphic: run the level checker less frequently

---

metamorphic/config.go

Disable download op until #3470 is fixed.

metamorphic: disable download op

---

internal/manifest/level_metadata.go

I verified that the assertion works (by undoing the TestExcise fix in
the previous PR).

manifest: cleaner implementation of assertNotL0Cmp

---

cleaner.go
compaction.go
data_test.go
db.go
db_internals.go
flushable_test.go
format_major_version.go
ingest.go
ingest_test.go
open.go
table_cache_test.go
table_stats.go
version_set.go

Introduce a `JobID` type and a helper to create a new job ID.

db: minor jobID cleanup

---

metamorphic/key_manager_test.go

metamorphic: fix TestLoadPrecedingKeys

---

sstable/block_property.go
sstable/block_property_test.go
sstable/suffix_rewriter.go
sstable/suffix_rewriter_test.go
sstable/writer.go

We omit block properties that are empty when we encode. When we
decode, we have to handle any missing properties as empty. The code
that does this is hard to follow. This change moves this logic into
the decoder, which makes things much cleaner.

sstable: move empty block property logic to decoder

---

level_iter.go

The comment about levelIter.boundaryContext was outdated and only discussed the use of sstable boundary keys to truncate untruncated range tombstones at read time. With the current version of Pebble, untruncated range tombstones no longer exist and the boundaryContext's usage is more constrained.

db: fix levelIter boundaryContext comment

---

level_checker.go

Break up the level checker's simpleMergingIter.skip method by pulling out the logic specific to point keys.

db: extract level checker's handling of point keys

---

internal/manifest/l0_sublevels.go

This field was probably named before we could have exclusive end
bounds. Renaming from `isLargest` to `isInclusiveEndBound`.

manifest: rename intervalKey.isLargest

---

level_iter.go
merging_iter.go

Previously, mergingIter.switchTo{Max,Min}Heap had complicated logic to avoid violating the levelIter's invariants when higher-level range deletions caused cascading seek keys to extend beyond iteration bounds. With 6fa3fe9d, the levelIter behaves like other internal iterators and is capable of being relative positioned away from an exhausted state without violating its bounds-checking invariants.
This commit applies the same logic of 6fa3fe9d to the synthetic iterator bound keys that are interleaved when a levelIter reaches a distant bound, allowing a relative positioning method to step away from these synthetic iterator bounds. This allows us to simplify mergingIter.switchTo{Max,Min}Heap.

db: simplify mergingIter.switchTo{Max,Min}Heap

---

compaction.go

This commit pulls out most of the code from `newOutput`; only the code
that modifies captured variables is left.

compact: pull out most of newOutput

---

ingest.go

Previously ingest calls passed in ingestTargetLevel to ingest to facilitate some testing that needed to force an ingestion into a specific level. The relevant testing no longer exists. This commit removes the indirection.

db: remove ingestTargetLevelFunc indirection

---

internal/compact/iterator.go
internal/compact/iterator_test.go

Remove the `Valid`, `Key`, `Value` methods which were only used during
tests (and the `valid` field which is now unused).

compact: some Iter cleanup

---

metamorphic/options.go

Previously it was possible for the metamorphic test to generate an invalid WAL failover configuration where the healthy interval was too long for the given probe interval, resulting in a healthy interval that could never be satisfied with the fixed 120-entry probe history.
Informs #3618.

metamorphic: fix WAL failover config generation

---

internal/manual/manual_64bit.go
internal/rawalloc/rawalloc_64bit.go

#3630
fix: add loong64 support

fix: add loong64 support #3630

---

metamorphic/test.go

Bump up the timeout for these ops, which can be very slow if both the block size and target file size are small and we end up with a ton of tiny tables.
Informs #3618

metamorphic: bump timeout for Compact/Download/NewSnapshot

---

internal/compact/iterator.go

When the compaction iterator is inside a range del, it has to compare
each key to `Span.End`. In this commit we reduce these key comparisons
by registering a frontier for the end of the span.

compact: use frontier to "expire" the last range del span

---

objstorage/objstorageprovider/remote_readable.go

During heavy reads of remote files, the `r.buffered.data = make([]byte, length)` line was observed to account for more than half of CRDB's total space allocations.

objstorageprovider: reuse buf from pooled remoteHandle

---

error_test.go

Disable the random latency injection on Windows - the default timer
resolution is really bad, leading to Sleep waiting at least 15ms in
most cases.
Fixes #3684

db: fix TestDBCompactionCrash on Windows

---

sstable/block/block.go
sstable/block_property_test.go
sstable/copier.go
sstable/filter.go
sstable/layout.go
sstable/reader.go
sstable/reader_iter_single_lvl.go
sstable/reader_iter_two_lvl.go
sstable/reader_test.go
sstable/suffix_rewriter.go
sstable/table.go
sstable/table_test.go
sstable/value_block.go
sstable/value_block_test.go
sstable/write_queue.go
sstable/writer.go
sstable/writer_test.go

Rename sstable.BlockHandle to sstable/block.Handle.

sstable/block: move Handle type

---

sstable/block/block.go
sstable/reader.go
sstable/rowblk/rowblk_fragment_iter.go
sstable/rowblk/rowblk_iter.go

Move the blockFragmentIter into the rowblk package.

sstable/rowblk: move fragmentIter

---

sstable/rowblk/rowblk_fragment_iter.go

Fixes #3678
I ran the meta test a bunch on this, I will run it some more before merging.

stable: reenable fragmentBlockIter pool

---

internal/keyspan/keyspanimpl/level_iter.go

This change reimplements the way straddle spans are generated in LevelIter. The existing code is hard to change to allow empty files in range key mode. It also makes things harder to reason about because there are subtle differences in state depending on the mode.
We now store a generalized position which can be "at" a file or "before/after" a file (corresponding to a straddle span).

keyspan: reimplement straddle spans in LevelIter

---

vfs/mem_fs.go

Resetting the filesystem state to synced state while files are open (and possibly receiving writes) results in nondeterminism, and is likely never the intention of the test writer. Add a safety mechanism to ensure that all files have been closed when ResetToSyncedState is called.
Informs cockroachdb/cockroach#124845.

vfs: require no open files in MemFS.ResetToSyncedState

---

internal/manifest/annotator.go
internal/manifest/annotator_test.go

cockroachdb#3760 contained a bug which causes Annotator
values to be incorrectly aggregated when pointer values
should be overwritten. This is because the `vtyped`
variable was not being modified due to being on the
stack.
This change fixes this and adds a unit test for
`PickFileAggregator` to catch this issue in the future.
cockroachdb#3759 should already not be affected by
this due to the different way it handles aggregation.

manifest: fix incorrect Annotator pointer aggregation

---

sstable/block_property_test.go
sstable/reader_test.go
sstable/testdata/block_properties
sstable/testdata/block_properties_boundlimited
sstable/testdata/writer
sstable/writer_test.go

Extract logic to format the WriterMetadata in sstable unit tests into a common test helper.

sstable: extract formatWriterMetadata test helper

---

internal/crdbtest/crdbtest.go
sstable/rowblk/rowblk_bench_test.go

Add microbenchmarks for block building and iteration that use Cockroach MVCC keys. These microbenchmarks will provide a comparison point for colblk equivalents.

rowblk: add cockroach microbenchmarks

---

internal/crdbtest/crdbtest.go

Tolerate empty keys in the crdbtest comparer. This is consistent with
the real CRDB comparer.

crdbtest: tolerate empty keys

---

sstable/colblk/unsafe_slice_test.go

Take the random row index generation out of the measured path.
```
name                                 old time/op  new time/op  delta
UnsafeIntegerSlice/uint64,delta8-10  3.54ns ± 0%  1.25ns ± 1%  -64.65%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint64,delta4-10  3.44ns ± 0%  0.94ns ± 0%  -72.70%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint64,delta2-10  3.36ns ± 0%  0.63ns ± 0%  -81.36%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint64,delta1-10  3.30ns ± 0%  0.63ns ± 1%  -80.74%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint64,delta0-10  3.30ns ± 1%  0.51ns ± 0%  -84.43%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint32,delta4-10  3.44ns ± 0%  0.94ns ± 2%  -72.55%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint32,delta2-10  3.36ns ± 0%  0.63ns ± 1%  -81.39%  (p=0.029 n=4+4)
UnsafeIntegerSlice/uint32,delta1-10  3.34ns ± …
```

colblk: fix for BenchmarkUnsafeIntegerSlice

---

internal/crdbtest/crdbtest.go
sstable/colblk/block.go
sstable/colblk/cockroach_test.go
sstable/colblk/data_block.go
sstable/colblk/data_block_test.go
sstable/colblk/prefix_bytes.go
sstable/colblk/prefix_bytes_test.go
sstable/colblk/raw_bytes.go
sstable/colblk/testdata/data_block/bundle_search
sstable/colblk/testdata/data_block/external_value
sstable/colblk/testdata/data_block/next_prefix
sstable/colblk/testdata/data_block/simple
sstable/colblk/unsafe_slice.go

Introduce facilities for reading and writing data blocks using user-specified columns for user keys. The full data block schema is not yet complete (eg, the 'is obsolete' bit, etc has not yet been integrated).

colblk: add data block builder, iterator

---

sstable/colblk/index_block.go
sstable/colblk/index_block_test.go
sstable/colblk/testdata/index_block

Add writer, reader and iterator types for index blocks.

colblk: add index block writer, reader, iterator

---

vfs/mem_fs.go

Stop using `maps.Clone` because of https://github.com/golang/go/issues/69110
Fixes #3894

vfs: workaround for a maps.Clone bug

---

sstable/colblk/block.go
sstable/colblk/data_block.go
sstable/colblk/index_block.go
sstable/colblk/index_block_test.go
sstable/colblk/keyspan.go
sstable/colblk/keyspan_test.go
sstable/colblk/raw_bytes.go
sstable/colblk/testdata/block_writer
sstable/colblk/testdata/data_block/bundle_search
sstable/colblk/testdata/data_block/external_value
sstable/colblk/testdata/data_block/next_prefix
sstable/colblk/testdata/data_block/simple
sstable/colblk/testdata/index_block
sstable/colblk/testdata/keyspan_block
sstable/colblk/unsafe_slice.go

Various tweaks to the columnar block primitives that have fallen out of work on the sstable writer integration.

colblk: various tweaks, interface extensions

---

internal/cache/entry.go
internal/cache/entry_invariants.go
internal/cache/entry_normal.go

This "ref count" is not actually being used or maintained.

cache: remove entry.refcnt

---

compaction_picker_test.go
compaction_test.go
go.mod
go.sum
replay/workload_capture_test.go
snapshot_test.go
sstable/data_test.go

Use `Lines` where it helps us remove an extra check for empty lines.

update crlib and use crstrings.Lines in a few tests

---

sstable/reader.go

Adapt Reader.EstimateDiskUsage to be generic over the index block iterator type.

sstable: adapt EstimateDiskUsage to be agnostic to index block impl

---

record/log_writer.go

Note: This is a PR as I'm just starting to learn the project, so any feedback on the changes, PR format, or anything else would be greatly appreciated. Thanks!

record: add unpack method annotation

---

record/log_writer_test.go

record: fix error log

---

sstable/reader_iter_two_lvl.go

Genericize the iterator over the type of the top-level index iterator too.

sstable: genericize top-level index type

---

sstable/reader_iter_two_lvl.go

sstable: fix merge skew

---

sstable/colblk/keyspan.go
sstable/colblk/keyspan_test.go

Refactor the exported interface surrounding the KeyspanIter to accommodate the expected usage: constructing heap-allocated *KeyspanIters that read through a cache/pool handle. The previous KeyspanIter type was refactored as an unexported keyspanIter type, and a new KeyspanIter implements cache-awareness as well as recycling of objects on Close.

colblk: add NewKeyspanIter, object pooling

---

open_test.go

db: remove race in TestCrashOpenCrashAfterWALCreation

---

ingest_test.go

db: fix TestExcise data race

---

sstable/colblk/data_block.go
sstable/colblk/data_block_test.go
sstable/colblk/index_block.go
sstable/colblk/testdata/data_block/rewrite_suffixes
sstable/colblk_writer.go
sstable/data_test.go
sstable/suffix_rewriter.go
sstable/testdata/rewriter
sstable/testdata/rewriter_v3
sstable/testdata/rewriter_v5
sstable/testdata/writer
sstable/testdata/writer_v3
sstable/writer_test.go

Add DataBlockRewriter for rewriting a columnar data block with a new suffix on
every key.

colblk,sstable: implement colblk suffix rewriting

---

sstable/reader.go

Fix a couple of lingering assumptions of rowblk blocks within the sstable reader.

sstable: support columnar blocks in NewCompactionIter, EstimateDiskUsage

---

open.go
options.go

The format log is missing a parameter

db: fill missing parameters

---

iterator.go

db: don't pass invalid argument to Uint32N

---

internal/lint/lint_test.go

lint: stop test when go vet fails (take two)

---

compaction.go

Previously, we didn't grab a version ref before running a delete-only compaction. This resulted in possible races with conflicting excises as the file could disappear underneath us if the delete-only compaction tried excising a file that has already been deleted in an IngestAndExcise, and the delete-only compaction's excise would need to read the file to determine the new bounds. This change grabs that version ref, similar to regular compactions.
This change also updates the delete-only compaction code to clean up CreatedBackingFiles if a file got virtualized and then removed in the delete-only compaction's execution.
Fixes #4030.
Fixes #4020.

db: grab version ref before delete-only compaction

---

sstable/layout.go

Use specific block read methods instead of the generic
`readBlockInternal`. This will matter when `readDataBlock` and
`readIndexBlock` will also initialize some metadata associated with
the block.

sstable: use specific block reading methods in Describe

---

iterator_test.go

Add a new randomized iterator test that ensures SeekPrefixGE finds the largest key with each prefix. This test is motivated by a bug in a wip branch that surfaces in TestSetOptionsEquivalence but not in other, simpler randomized tests. This test makes it easier to reproduce and isolate.

db: add TestIteratorSeekPrefixGERandomized

---

internal/crdbtest/crdb.go

As a part of merging the production KeySchema implementation for CockroachDB, some edits and bug fixes were applied relative to what we've been testing in the Pebble implementation. This commit merges these edits back into the Pebble implementation.

crdbtest: port back Cockroach KeySchema edits

---

internal.go
internal/keyspan/fragmenter.go

Necessary to unblock cockroachdb/cockroach#67284

crl-release-23.2: export keyspan.Fragmenter

---

wal/failover_manager.go

The WAL failover monitor tracks the duration spent writing to the primary and secondary WAL directories. Previously it was possible for updates to these durations to be negative (despite implicitly using the time.Time's monotonic time), because the time was retrieved before acquiring the mutex guarding the accumulated durations. A goroutine that measured the current time first was not necessarily the first to enter the critical section and update the monitor's lastAccumulateIntoDurations field.
This commit moves these time measurements under the mutex and adds an assertion that the monitor's understanding of time moves monotonically forward.
Informs cockroachdb/cockroach#136317.

wal: prevent negative durations

---

wal/failover_manager.go

24.3 backport of #4183 to avoid test flakes on the 24.3 release branch.
----
The WAL failover monitor tracks the duration spent writing to the primary and secondary WAL directories. Previously it was possible for updates to these durations to be negative (despite implicitly using the time.Time's monotonic time), because the time was retrieved before acquiring the mutex guarding the accumulated durations. A goroutine that measured the current time first was not necessarily the first to enter the critical section and update the monitor's lastAccumulateIntoDurations field.
This commit moves these time measurements under the mutex and adds an assertion that the monitor's understanding of time moves monotonically forward.
Informs cockroachdb/cockroach#136317.

crl-release-24.3: wal: prevent negative durations

---

sstable/colblk_writer.go

This allocation is about 0.1% of all allocations in a sysbench
workload. Reuse a buffer instead.

sstable: don't clone the last key for each data buffer

---

compaction.go
file_cache.go

We add a label for the compaction output level.
We also remove the "table-cache" label which is not very useful - you can just focus on `load() / releaseLoop()` to get the same information. This label "erases" the top-level labels because the context is not plumbed correctly.
Below is an example from sysbench (using pprof flag `-tagroot pebble,output-level`). This suggests that we could enable `zstd` only on L6 and see ~4x less perf impact.

db: improve pprof labels for compactions

---

tool/db.go
tool/testdata/db_upgrade

Add a `db upgrade` command that ratches up the DB version to the
newest one.

tool: add db upgrade command

---

internal/cache/read_shard.go

This PR is only for the last commit (first one is https://github.com/cockroachdb/pebble/pull/4229).
This structure is not necessary because it stores fields from
`readEntry` that don't change. What's important is not that we read
them under the lock, but that we read them before we release the
refcount; we can do this in the same method where they are used.

cache: remove tryRemoveState in readShard

---

internal/manifest/manifest_test.go

I saw a timeout of this test in race mode. The timeout was during the
execution of the metamorphic execution (which constructs the state prior
to the actual test). This change reduces the number of operations in
race mode.

manifest: reduce TestInuseKeyRangesRandomized ops in race mode

---

internal/cache/clockpro.go
internal/cache/read_shard.go
internal/cache/read_shard_test.go

This makes the `waitForReadPermissionOrHandle` cleaner and makes
following the life of the refcount from `GetWithReadHandle` easier.
@sumeerbhola hope you don't mind I keep messing with this code. I just kind of nerd-sniped myself, it's fascinating that the problem we're solving here is conceptually straightforward at a high level but the details are so non-trivial.

cache: readShard: unref outside of waitForReadPermissionOrHandle

---

vfs/mem_fs.go

Adding a testing facility to allow `MemFS` to mock disk usage stats.
This will be used in CRDB for a test for the low disk space event
(together with the sticky registry).

vfs: add MemFS.TestingSetDiskUsage

---

comparer.go

Refer to base.CheckComparer for usage.

Update stale comment in comparer.go

---

open_test.go

The errorfs-based instrumentation had a race between the wal creation actually happening on the underlying FS and a dir sync (and/or between the dir sync actually happening on the underlying FS and a subsequent operation).
We use a custom instrumented FS that acts *after* the operation happens on the MemFS.
Fixes #4306

db: fix TestCrashOpenCrashAfterWALCreation flake

---

internal/arenaskl/skl_test.go

Remove the iterAdapter used in test cases. When the internal iterator interface changed, this adapter was used to defer updating the unit tests in the arenaskl package. Clean up the tests to use the new interface and remove the adapter.

internal/arenaskl: remove iterAdapter

---

internal/compact/iterator.go
internal/compact/iterator_test.go
internal/compact/run.go

Update compact.Iter to return *InternalKVs from its positioning methods, mirroring the analogous methods on the InternalIterator interface.  The *compact.Iter type still does not implement the full InternalIterator interface. We unify the return values for consistency and to remove a direct dependency onto the LazyValue type.

internal/compact: return *InternalKV from Iter

---

iterator_test.go
merging_iter_test.go

Fix bug in iterator microbenchmarks that used buildLevelsForMergingIterSeqSeek. The buildLevelsForMergingIterSeqSeek returned open readers using a cache handle that had been closed prematurely.

db: fix iterator microbenchmarks' cache use

---

go.mod
go.sum

Bump swiss to incorporate https://github.com/cockroachdb/swiss/pull/44

go.mod: bump swiss

---

event.go
event_listener_test.go

The cancelled compaction error is expected, so reduce the log level to info as suggested in #3938.

db: reduce log level to info for cancelled compaction

---

.github/actions/post-issue/action.yaml
.github/workflows/nightly-s390x.yaml
Makefile
sstable/rowblk/rowblk_iter_test.go

This commit adds a make target for testing s390x with qemu and adds a
nightly github action that runs it. We also add an action that is used
to automatically post an issue when there is a failure. In future PRs,
we will use this action for all nightlies.

Makefile, .github: add test target for s390x

---

external_iterator.go
external_iterator_test.go

If creating a point or range key iterator fails, we leak some
iterators that were already opened. This immediately leads to a
BufferPool-related panic when closing the `Iterator`.
This change adds an enhancement to a test which reproduces the panic
and patches up the error paths.
Informs github.com/cockroachdb/cockroach/issues/141606

crl-release-24.1: pebble: add missing cleanup in a NewExternalIter error case

---

go.mod
go.sum

The update includes better logging and error output.

go.mod: update datadriven

---

.github/workflows/ci.yaml

It won't block merging but it will run again on all PRs.

github: add testrace back to PR checks

---

level_checker.go

Update the level checker to initialize a blob value fetcher and use it.

db: support blob values in the level checker

---

db.go

db: include TableStats in SSTableInfo

---

internal/compact/run.go

A running compaction maintains a cumulative total of bytes written to disk for the purpose of informing the compaction scheduler of write bandwidth consumed. Incorporate completed blob files into this cumulative total.

compact: include blob files in CumulativeWrittenSize

---

data_test.go
db.go
ingest_test.go
metrics.go
metrics_test.go
testdata/event_listener
testdata/ingest
testdata/metrics
tool/data_test.go
tool/testdata/db_lsm

Add the count of sstables that are pending stats collection, and
whether the initial loading completed.
Fixes #4572

metrics: show info about pending stats collection

---

metrics.go
metrics_test.go
testdata/event_listener
testdata/ingest
testdata/metrics
tool/testdata/db_lsm

PR is only for the top commit.

metrics: print Keys metrics

---

data_test.go
metrics_test.go

db: deflake TestMetrics

---

compaction_picker.go
db.go
internal/manifest/version.go
metrics.go
table_stats.go
testdata/compaction_picker_scores
testdata/compaction_tombstones
testdata/metrics
testdata/table_stats

db: add metrics for garbage due to point and range deletions

---

checkpoint_test.go
compaction_test.go
data_test.go
db.go
db_test.go
error_test.go
event_listener_test.go
excise_test.go
file_cache_test.go
format_major_version_test.go
ingest_test.go
iterator_test.go
metamorphic/ops.go
metrics_test.go
objstorage/objstorageprovider/objiotracing/obj_io_tracing_test.go
obsolete_files_test.go
open_test.go
range_del_test.go
snapshot_test.go
testdata/compaction/compaction_cancellation
tool/testdata/make-fixtures.go

db: allow cancellation of manual compactions

---

vfs/atomicfs/README.md

Adding a `README.md` with a high-level explanation (generated by GPT
o4-mini-high).

atomicfs: add README

---

ingest.go
sstable/properties.go
sstable/properties_test.go

sstable: fix invariants panic due to zero virtual table size

---

cmd/pebble/ycsb.go

The cmd/pebble ycsb benchmarks have an --initial-keys flag that configures the benchmark to insert the provided count of keys before running the benchmark. During the nightlies, this initial seeding of a database is performed once and each run of the benchmark uses a copy of this initial database. When a substantial volume of keys are committed, the LSM is typically inverted. Immediately beginning the benchmark introduces additional noise, as many available resources are spent performing compactions at the benchmark's start.

cmd/pebble: wait for compactions to stabilize after initial seeding

---

cmd/pebble/db.go

Enable value separation in the cmd/pebble ycsb nightly benchmarks. Configure a minimum size that effectively means the value=1024 variants of the benchmarks will separate values, and the value=64 variants will not.
Informs #112.

cmd/pebble: enable value separation in benchmarks

---

metrics.go
metrics_test.go
testdata/metrics

Account blob files' sizes when calculating disk space in (*Metrics).DiskSpaceUsage.
Informs #4581.

db: account blob files in Metrics.DiskSpaceUsage

---

sstable/blob/blob.go
sstable/block/compression.go
sstable/block/compression_test.go
sstable/block/compressor.go
sstable/colblk_writer.go
sstable/layout.go
sstable/rowblk_writer.go
sstable/suffix_rewriter.go
sstable/valblk/writer.go

sstable: misc compression code improvements

---

obsolete_files.go

When deciding whether to pace a file deletion, avoid looking up the object in the objstorage provider. We now have an isLocal field readily available on the obsoleteFile.

db: avoid provider lookup when pacing file deletions

---

.github/workflows/instrumented.yaml
.github/workflows/s390x.yaml
.github/workflows/stress.yaml
.github/workflows/tests.yaml

Add the job name to issue titles and contents.

github: fix issue titles

---

tool/blob_files.go
tool/find.go
tool/manifest.go
tool/sstable.go
tool/tool.go

Refactor the tool package's interfaces surrounding blob references in preparation for blob file replacement.

tool: refactor blob file mappings

---

db.go

Informs https://github.com/cockroachdb/cockroach/issues/147740

db.ScanStatistics: sanity check LimitBytesPerSecond

---

range_del_test.go

reduce TestFlushDelayStress runs in slow builds

---

internal/metamorphic/meta_test.go
internal/metamorphic/metaflags/meta_flags.go

The metamorphic test has some flags specific to the "outer" Run, and
some flags specific to `--run-dir/--compare`. If a flag is passed that
doesn't apply to the mode, it is ignored.
In this change we instead error out the test. This will reduce sources
of confusion, especially when trying to run things manually.
Examples:
```
--- FAIL: TestMeta (0.00s)
meta_test.go:96: flag "previous-ops" is not allowed with --run-dir
--- FAIL: TestMeta (0.00s)
meta_test.go:118: flag "try-to-reduce" is only allowed with --compare or --run-dir
```
Fixes #4845

metamorphic: error out if flags are used incorrectly

---

compaction_test.go

db: wait for initial scan for TestCompaction metrics

---

blob_rewrite.go
compaction.go
metrics.go
testdata/compaction/value_separation
testdata/event_listener
testdata/ingest
testdata/metrics
tool/testdata/db_lsm
value_separation.go
version_set.go

Increment compaction count and bytes written for blob file rewrite compactions.

pebble: account for blobFileRewriteCompaction in compaction metrics 

---

sstable/blob_reference_index.go
sstable/blob_reference_index_test.go

Add a randomized test of blob value liveness writer.

sstable: add blob value liveness writer random test

---

metrics.go
metrics_test.go
testdata/compaction/l0_to_lbase_compaction
testdata/compaction/value_separation
testdata/event_listener
testdata/ingest
testdata/metrics
tool/data_test.go
tool/db.go
tool/testdata/db_lsm

Reformat the string outputted by Metrics.String to add more organization.

db: reformat Metrics.String

---

open_test.go

Fix the relative path subtests.
Fixes: #5053

pebble: fix TestOpenAlreadyLocked

---

open.go

pebble: close the manifest file on Open failure

---

compaction_test.go

One test, TestCompaction_UpdateVersionFails, has a leak that I haven't dug into yet.

db: add leaktest to compaction unit tests

---

testdata/ingest

Fixes #5101
Fixes #5102
Fixes #5103
Fixes #5104
Fixes #5105
Fixes #5106

fix merge skew

---

compaction_test.go

Making some changes that hopefully make this test reliable (I can't
reproduce failures locally):
- we automatically pause the workload while a compaction is
happening, which ensures the flushes don't outpace compactions
- we reduce the value sizes which are no longer relevant to induce
compactions (we use `L0CompactionFileThreshold`).

db: deflake TestCompactionCorruption

---

compaction.go
db.go
ingest.go
ingest_test.go
internal/manifest/table_metadata.go
internal/manifest/table_metadata_test.go
metrics.go
metrics_test.go
sstable/block/compression_stats.go
sstable/block/compression_stats_test.go
sstable/block/compressor.go
sstable/suffix_rewriter.go
table_stats.go
testdata/compaction/l0_to_lbase_compaction
testdata/compaction/value_separation
testdata/event_listener
testdata/ingest
testdata/metrics
tool/testdata/db_lsm

Update the compression metrics to use the new compression statistics.

metrics: expose new compression stats

---

sstable/colblk/data_block.go

colblk: fix keySchemaMeta alignment

---

sstable/tieredmeta/histogram.go

There is no test yet, so there may be bugs.

[tiered prototype] tieredmeta: fix todos in TieredHistogram

---

blob_rewrite_test.go
internal/compact/run.go
value_separation.go
value_separation_test.go

https://github.com/cockroachdb/cockroach/pull/152355#issuecomment-3215310146

compact: remove allocation from closure

---

internal/manifest/l0_sublevels.go

Clean up some code by replacing the intervalKeySorter type with calls to slices.SortFunc.

manifest: replace intervalKeySorter with slices.SortFunc

---

blob_rewrite.go

When performing a blob file rewrite compaction, assert that the rewritten blob file has a smaller value size. We should never choose to rewrite a blob file that is fully referenced. If we do, it reflects a bug in our statistics or compaction picking.
Informs #5306.

db: assert that blob file rewrites reduce value size

---

internal/manifest/l0_sublevels.go

**manifest: apply a few small hygiene improvements to L0 sublevels**
Apply a few small code hygiene improvements, like using min and max builtins
and the slices.Clone function.
**manifest: use slices.SortFunc**
Replace a lingering implementation of the sort.Interface with a use of
slices.SortFunc.

manifest: apply a few small hygiene improvements to L0 sublevels 

---

vfs/disk_full_test.go

Deflake the TestOnDiskFull* tests. Previously these tests relied on time.Sleep so that several goroutines would observe the same injected ENOSPC in parallel. This commit switches to using a mutex and condition variable to ensure all the injected ENOSPCs are observed before any of the goroutines continue.
Fix #5197.

vfs: deflake TestOnDiskFull tests

---

sstable/tieredmeta/histogram.go

Just a proof-of-concept with no test (so bugs are likely).

tieredmeta: add commentary and code for generalizing the histogram

---

cleaner.go
cleaner_test.go

When `TargetByteDeletionRate` is set to a low value, `DB.Close()` can hang for a
long time because deletion pacing uses `time.Sleep()` that can't be interrupted.
This change modifies `maybePace()` to check for early termination and use
interruptible `select` instead of `time.Sleep()`.
Backport of #5348 and #5361.

pebble-release-1.1: fix cleanupManager.Close() hanging when deletion pacing is active

---

Makefile

Informs: https://github.com/cockroachdb/cockroach/issues/149116

Makefile: set crl-release-25.3 as prev, update crossversion target

---

internal/arenaskl/skl_test.go

Add a randomized unit test for FindSplice.

internal/arenaskl: add TestSkiplistFindSplice

---

open.go
testdata/cleaner
wal/wal.go

db: remove obsolete WALs before proceeding with init
